### ISSUE TITLE
Add emoticons view 

### ISSUE THREAD

**Issue by Base2526** [FaridSafi/react-native-gifted-chat#1005]
Hi all friend
  if i want add view emoticons   by picture
![untitled](https://user-images.githubusercontent.com/900211/47561613-ffa87100-d945-11e8-9179-b45d8163fd09.png)

thx.

**Comment by anhnt2309** [comment]
Have you found the solution yet?

**Comment by sibelius** [comment]
use this package https://github.com/missive/emoji-mart
