### ISSUE TITLE
About the pull up the page to load more content 

### ISSUE THREAD

**Issue by flyinghawker** [FaridSafi/react-native-gifted-chat#1006]
Yes, it is pull up not pull down.
for case that load first line of new message and load more subsequent message when pull up to bottom, which is pretty similar to Wechat

The issue is that I directly use refreshControl, and because this is inverted list, after new msg appended, it directly reaches the end of chat list. But I expect it to stay at the same position before new msg appended so user can continue to read the msg smoothly. Thanks!

**Comment by linhtv97** [comment]
Open
