### ISSUE TITLE
add contributors

### ISSUE THREAD

**Issue by sibelius** [FaridSafi/react-native-gifted-chat#1008]
This repo is great, but we need much more contributons to review issues and pull requests

I think the right path is to move to https://github.com/react-native-community and add much more contributors

**Comment by yurykorzun** [comment]
It looks like there is no one responsible for merging pull requests and doing releases.

**Comment by fbartho** [comment]
I'd love to contribute here too. I just pushed an update to github.com/taskrabbit/react-native-parsed-text that fixes a bug that affects react-native-gifted-chat

**Comment by sibelius** [comment]
send me pull requests that you want to be reviewed and merged

I'll try to take a look on some of them

**Comment by sibelius** [comment]
ping me if you need any issue or PR to be reviewed
