### ISSUE TITLE
Issue with InputToolbar Height

### ISSUE THREAD

**Issue by danZheng1993** [FaridSafi/react-native-gifted-chat#1011]
#### Issue Description

I was trying to limit the maximum height of input toolbar.
But when I was trying to implement this, I get this issue.

![chat](https://user-images.githubusercontent.com/33262634/48105690-6ea19600-e273-11e8-93ef-83c2f564d4f0.gif)

#### Steps to Reproduce / Code Snippets

Here's what I did
```
const styles = {
  inputToolbar: {
    maxHeight: 100,
  },
  composerText: {
    maxHeight: 100,
  },
};

renderInputToolbar = props => <InputToolbar {...props} containerStyle={styles.inputToolbar} />;
renderComposer = props => <Composer {...props} textInputStyle={styles.composerText} />;

<GiftedChat
  /* ...  */
  renderInputToolbar={this.renderInputToolbar}
  renderComposer={this.renderComposer}
/>

```

#### Expected Results

When adding new lines in the message box, the content will stop move up when height of Input Toolbar reaches 100 pt and stays there.

#### Additional Information

* Nodejs version: 8.11.4
* React version: 16.4.1
* React Native version: 0.56.0
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): ios

**Comment by IsharaHansaka** [comment]
did u try minHeight? that will fix your problem.

**Comment by GustavoDinizMonteiro** [comment]
Hi, any solution ? i have the same problem here :(

**Comment by GustavoDinizMonteiro** [comment]
@danZheng1993 did you find a solution?

**Comment by gmontemayor1987** [comment]
I know this is an old post, but maybe it could help someone. I had to make this in the composer
`<Composer {...props} textInputStyle={{maxHeight: 100}}/>`

And also set the same height in `maxComposerHeight`
`<GiftedChat
    ... 
    maxComposerHeight={100}
/>`
