### ISSUE TITLE
How to place a button in the text Input and keep the existing send button static ?

### ISSUE THREAD

**Issue by ronastlelobo** [FaridSafi/react-native-gifted-chat#1012]

**Comment by maherzaidoune** [comment]
you use the renderActions , renderComposer and renderSend prop functions to create you custom input toolbar , here is an example using renderActions function [GiftedChat_Video](https://github.com/maherzaidoune/GiftedChat_Video/blob/master/App.js)

**Comment by ronastlelobo** [comment]
Thank You @maherzaidoune , I got the expected Result !
