### ISSUE TITLE
React JS compatibility

### ISSUE THREAD

**Issue by abhisheksdm** [FaridSafi/react-native-gifted-chat#1015]
Hello.. Can it be configured with React JS?
I was using react-chat-widget, but it supports only plain text messages. I also need to send images as well.
Please suggest me any solution.
Thank you.

**Comment by sibelius** [comment]
You should try with react native web, and let us know

**Comment by johniak** [comment]
I tried to fork and modified gifted chat to work in web (ReactJS)
You can find it there:

https://github.com/johniak/react-web-gifted-chat
