### ISSUE TITLE
How can I fix react-native vector icons in this code

### ISSUE THREAD

**Issue by eniayeye** [FaridSafi/react-native-gifted-chat#1016]
#### Issue Description

import React from'react';
import {Text, View,header,StatusBar} from 'react-native';

import {TabNavigator} from "react-navigation"

//import {createMaterialBottomTabNavigator} from 'react-navigation-material-bottom-tabs'
import {createMaterialTopTabNavigator, createBottomTabNavigator } from  'react-navigation'
import { createNavigator, SafeAreaView, TabRouter } from 'react-navigation';
import { createAppContainer } from 'react-navigation';
import Icon from 'react-native-vector-icons/FontAwesome';

import member from './components/member'
import member2 from './components/member2'
import member3 from './components/member3'
import member4 from   './components/member4'
import back from './components/back'

var  MainScreenNavigator = TabNavigator({

  Tab1: {screen: member},
  Tab2: {screen: member2},
  Tab3: {screen: member3},
  Tab4: {screen: member4},
},{
  tabBarPosition:'bottom',
  swipeEnabled: true,
  tabBarOptions: {
    activeTintcolor:'darkgreen',
    inactiveTintColor:'black',
    inactiveBackgroundColor:'green',
 },
  
});

MainScreenNavigator.navigationOption= {
  title: "Tab example"

};
  export default MainScreenNavigator;

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by sibelius** [comment]
Not related to this package
