### ISSUE TITLE
Is there a way to prepend some text on a  message onPress?

### ISSUE THREAD

**Issue by nandiniparimi1107** [FaridSafi/react-native-gifted-chat#1017]
#### Issue Description

I would like to add another row on the top of a message onPress of a message, How can i do that?

#### Expected Results
Say for example the conversation is : 

Alex : Hi
Bob: Hello
Alex : How is your day going
Bob: Good.

Now if Alex clicks on bob;s message, this is what i want to see on UI

Alex : Hi
This message was sent with some metadata
Bob :Hello
Alex : How is your day going
Bob: Good.

**Comment by linux08** [comment]
@nandiniparimi1107  you got any solution to this?
