### ISSUE TITLE
isAnimated doesn't show any change in behavior, no matter if it is set to true or false.

### ISSUE THREAD

**Issue by RominHalltari** [FaridSafi/react-native-gifted-chat#1021]
#### Issue Description

I put `isAnimated={true}` but in Android it doesn't do anything. The behavior is the same as `isAnimated={false}`.

#### Steps to Reproduce / Code Snippets

I just used the example shown in the official docs, and added `isAnimated={true}` to the GiftedChat component but it doesn't seem to be any different than when I use `isAnimated={false}`. 

#### Expected Results

When `isAnimated` is set to true, it should animate the view when showing/hiding the keyboard. Instead, it behaves the same (no animation), no matter what value is passed to `isAnimated`.

#### Additional Information

* Nodejs version: 8.11.4
* React version: 16.5.0
* React Native version: 0.57
* react-native-gifted-chat version: ^0.4.3
* Platform(s) (iOS, Android, or both?): Android. Not tested on iOS.

**Comment by nandiniparimi1107** [comment]
Did you find a solution?
