### ISSUE TITLE
How to put a Progress Indicator when sending a Image on the Message Box ?

### ISSUE THREAD

**Issue by ronastlelobo** [FaridSafi/react-native-gifted-chat#1026]

**Comment by mafiusu** [comment]
It's just simple ReactJS here. You can extend the MessageImage.js file with a loading prop. 

if the loading prop is passed (true) you will render an activity indicator :)

**Comment by Faolain** [comment]
@mafiusu could this also be a solution? I don't see a `loading` prop existing already on MessageImage.js so this fix could allow this to be done without needing to extend the file which should be a feature that's supported out of the box.  https://github.com/FaridSafi/react-native-gifted-chat/pull/1003
