### ISSUE TITLE
I find one more issue for message showing in IOS  ?

### ISSUE THREAD

**Issue by onusvishal** [FaridSafi/react-native-gifted-chat#1027]
> Step 1  - IOS Send Message 
> Step 2 - Android SendMessage 
> Step3 - IOS Send Message both IOS Message Are Parlour ,

see this video 
![chatissue](https://user-images.githubusercontent.com/45001798/49284863-d4242380-f4bb-11e8-970a-9ddd52da0802.gif)

**Comment by maherzaidoune** [comment]
i don't think this problem is related to the library , just make sure you are using the right id in your msg objects
