### ISSUE TITLE
renderSystemMessage not working

### ISSUE THREAD

**Issue by chih98** [FaridSafi/react-native-gifted-chat#1028]
#### Issue Description

renderSystemMessage is not being called as a prop inside `<GiftedChat renderSystemMessage{...} />`

#### Steps to Reproduce / Code Snippets

`<GiftedChat renderSystemMessage{this.renderSystemMessage} />` should call `renderSystemMessage(props)` and render a custom system message, but it doesn't.

#### Expected Results

Custom function to be called similar like renderSend, renderBubble, etc.

#### Additional Information

* Nodejs version: v8.12.0
* React version: N/A
* React Native version: 0.55.4
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by lwf804** [comment]
Same with me.

**Comment by JorgeMoralesLopez** [comment]
1+
