### ISSUE TITLE
back-end for gifted chat?

### ISSUE THREAD

**Issue by haseebehsan** [FaridSafi/react-native-gifted-chat#1030]
Hi I want guide for integrating this gifted chat in my application specifically I can't figure out what kind of back-end gifted chat requires? is there a solution for that?

**Comment by mafiusu** [comment]
You can use this chat component with any backend you like. There is an example on YouTube where @FaridSafi show how to do it with the backend Firebase.

**Comment by haseebehsan** [comment]
> You can use this chat component with any backend you like. There is an example on YouTube where @FaridSafi show how to do it with the backend Firebase.

thanks for the reply =, can you suggest me back-ends other than firebase? and does gifted-chat provide UI for call option like in whatsapp?

**Comment by sibelius** [comment]
We gonna accept docs to improve this, basically your backend should return a list of messages from a conversation, and provide a way to add a new message for a conversation

I recommend using GraphQL and Relay Modern to scale

**Comment by StormFactory** [comment]
> You can use this chat component with any backend you like. There is an example on YouTube where @FaridSafi show how to do it with the backend Firebase.

@haseebehsan Here is the link mentioned above https://www.youtube.com/watch?v=7Ot5LSGHLyY

**Comment by sibelius** [comment]
I've made a basic modelling of this using GraphQL https://github.com/sibelius/semcomp-graphql/tree/master/src/model

and can get this as starting point
