### ISSUE TITLE
Add examples of group messaging

### ISSUE THREAD

**Issue by anjumpaul** [FaridSafi/react-native-gifted-chat#1031]
Group messaging is possible?

**Comment by mafiusu** [comment]
Yes!

**Comment by anjumpaul** [comment]
@mafiusu,how to implement group messaging?

**Comment by anjumpaul** [comment]
please share sample code

**Comment by mafiusu** [comment]
This chat component only reflects a basic chat User Interface. To create groups like in WhatsApp you have to create a Chat List Screen and do many things in your backend.

**Comment by anjumpaul** [comment]
how to implement chat with multiple chat participants.can you share some example?

**Comment by Faolain** [comment]
@anjumpaul as noted by @mafiusu this requires backend work as well which is not covered by react-native-gifted-chat and that solution is up to your discretion. Gifted chat allows you to pass any messages that you want, including that from multiple participants (multiple user _id's) but handling this on the backend requires work that is out of the scope of this library.

@cooperka can we please close this?

**Comment by cooperka** [comment]
@Faolain I updated the title to reflect the actual need here. Feel free to note any similar questions as duplicates of this one. I don't think closing it will help unless there's an actual answer to the question that users can refer to (people will just keep opening new issues to ask the same thing).

**Comment by cooperka** [comment]
On a related note, if you reach out to Farid he's generally quite friendly and he may grant you collaborator access so you can help clean up these issues. Unfortunately I personally don't have the time right now to actively maintain these issues, but I appreciate your help.
