### ISSUE TITLE
  How to clear the value of TextInput 

### ISSUE THREAD

**Issue by zSergeant** [FaridSafi/react-native-gifted-chat#1044]
#### Issue Description

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by xcarpentier** [comment]
Please use stackoverflow: https://stackoverflow.com/questions/tagged/react-native-gifted-chat
