### ISSUE TITLE
how to edit position message for user 

### ISSUE THREAD

**Issue by Mrezagolbaba** [FaridSafi/react-native-gifted-chat#1045]
how to change position for Bubble left and right

**Comment by Kyonru** [comment]
Every message has a property named user.
And the gifted-chat has a props name user, if they both has the same `_id`, the message will be displayed on the left or the right

**Comment by Parthasarath** [comment]
> Every message has a property named user.
> And the gifted-chat has a props name user, if they both has the same `_id`, the message will be displayed on the left or the right

But
messages: [
    {
        _id: 1,
        text: ‘Hi developer',
        createdAt: new Date(),
        user: {
            _id: "sarathy",
            name: 'React Native’
        },
    },
    {
        _id: 2,
        text: ‘Hello developer',
        createdAt: new Date(),
        user: {
            _id: "partha",
            name: 'React Native',
           },
    },
    {
        _id: 3,
        text: ‘How r u?’,
        createdAt: new Date(),
        user: {
            _id: "sarathy",
            name: 'React Native'
        },
    },
],
 Above my message structure contains '_id' on both user but still my messages displayed left side only, how to fix this issue? @Kyonru 
FYI -- [https://stackoverflow.com/questions/54309578/messages-displayed-on-one-side-only-left-hand-side-of-the-screen-react-nativ]()

**Comment by Kyonru** [comment]
try adding the user who is writting to the giftedChat:

```
 <GiftedChat
    isAnimated
    messages={this.props.messages}
    onSend={messages => this.onSend(messages)}
    user={{
        _id: 'sarathy',
        name: 'Minecraft',
    }}
/>
```

Every message that has the user's ` _id: 'sarathy'` will be displayed on the right.

**Comment by Kyonru** [comment]
@Mrezagolbaba can you provide any example about what you mean with "group chat"? If you are talking about multiple users in the same chat, yeah, there is no problem, because each message should have a different user.

**Comment by Mrezagolbaba** [comment]
@Kyonru is possible with different id about any user?

**Comment by NoumanSakhawat** [comment]
> try adding the user who is writting to the giftedChat:
> 
> ```
>  <GiftedChat
>     isAnimated
>     messages={this.props.messages}
>     onSend={messages => this.onSend(messages)}
>     user={{
>         _id: 'sarathy',
>         name: 'Minecraft',
>     }}
> />
> ```
> 
> Every message that has the user's ` _id: 'sarathy'` will be displayed on the right.

this is not working...

**Comment by dody87** [comment]
This is still not working.
