### ISSUE TITLE
Fixed the keyboard issue on android without adjustResize on manifest

### ISSUE THREAD

**Issue by nandiniparimi1107** [FaridSafi/react-native-gifted-chat#1050]
There are a bunch of issues around keyboard pushing up the toolbar /  not having to hardcode adjustResize on the manifest since other screens might need to have adjustPan etc.

I am finally able to crack it without updating manifest file or importing an outdated library.
@FaridSafi how can i incorporate my changes and contribute to this project? My changes include adding bridge code.

**Comment by jsochurek** [comment]
can you share your code?

**Comment by nandiniparimi1107** [comment]
Hey there @jsochurek ,
I added a bridge method which can be called on every screen you want the soft input mode to be changed. That way you don't need to hardcode the resize option in the manifest file.

Something like this :  
```

@ReactMethod
   public void setSoftInputMode(final int softInputMode) {
        final Activity activity = getCurrentActivity();
        if (activity == null) {
            return;
        }
        activity.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                activity.getWindow().setSoftInputMode(softInputMode);
            }
        });
    }
```

**Comment by jsochurek** [comment]
This worked great for me, thanks @nandiniparimi1107 !!

**Comment by cristian-milea** [comment]
is this implemented? i have some issues with the keyboard as well

**Comment by pheuter** [comment]
Same issues—are there plans to incorporate this into the library without having to eject from Expo?

**Comment by steinroe** [comment]
@nandiniparimi1107 could you give a few more details or an example on how to use your bridge method?
