### ISSUE TITLE
How to add the attach button, the video button and the microphone button next to the text field 

### ISSUE THREAD

**Issue by EbrahimiM** [FaridSafi/react-native-gifted-chat#1053]
First of all, I would like to thank everyone who is trying to develop this software and In advance I apologize if my question is simple and obvious

I want to add the attach button, the video button and the microphone button next to the text field like WhatsApp.

 

Would you please guide me how to do this?
is there any sample how doing that?

thank you very much for taking the time to answer my questions

**Comment by evertonco** [comment]
You have to use render functions provided by GiftedChat. In your case, use renderComposer and renderSend.

> renderSend (Function) - Custom send button; you can pass children to the original Send component quite easily, for example to use a custom icon
> 
> renderComposer (Function) - Custom text input message composer

General example:

import { Composer } from 'react-native-gifted-chat'

...
renderComposer = props => {
  return (
    <View style={{flexDirection: 'row'}}>
      <Composer {...props} />
      <CustomImageButton />
      <CustomAttachButton />
    </View>
  );
}

renderSend = props => {

  if (!props.text.trim()) { // text box empty
    return <AudioButton />;
  }

  return (
    <SendTextButton />;
  );
}

render () {
return  <GiftedChat 
  ...
  renderComposer={this.renderComposer}
  renderSend={this.renderSend}
  />
}

**Comment by stingray91** [comment]
hi @evertonco or anyone , if i were to add something like 

`renderComposer = props => {
  return (
    <View style={{flexDirection: 'row', textAlign:'left'}}>
      <Composer {...props} />
     <Ionicons name="md-camera" color="grey" size={40}>
     </Ionicons>

    </View>
  );
}`

my send button will be replaced, how do I make use of the 
` return (
       <SendTextButton />;
   );`

as currently now it will return me an error of unexpected token, expected ","

**Comment by evertonco** [comment]
Remove ";"

return <SendTextButton />

SendTextButton is only example. You must implement it

**Comment by lakshayma** [comment]
From where can i import The Components like (SendTextButton , AudioButton , CustomAttachButton , CustomImageButton) ? As it is not available in the react-native-gifted-chat

**Comment by evertonco** [comment]
You must implement all these components. It's just example.

**Comment by fukemy** [comment]
if u wrap composer inside a View, then you can not received composer height changed

**Comment by HomeroKemmerich** [comment]
How can I work with the press event using `renderSend`? When trying to implement it and assigning a function to it, I get an error which does not specify where it's coming from.

![Image](https://github.com/user-attachments/assets/958e3105-a3ee-4593-9711-2dff6aab2d8a)

```tsx
export default function Index() {
  const handleSend = (newMessages: IMessage[]) => {
    setMessages((previousMessages) =>
      GiftedChat.append(previousMessages, newMessages)
    );

    const userMessage = newMessages[0].text;
    const botResponse = generateChatbotResponse(userMessage);

    setMessages((previousMessages) =>
      GiftedChat.append(previousMessages, [
        {
          _id: Math.round(Math.random() * 1000000),
          text: botResponse,
          createdAt: new Date(),
          user: { _id: 2, name: "Chatbot" },
        },
      ])
    );
  };
const renderSend = (props: any) => {
    return (
      <View style={{ flexDirection: 'row' }}>
        <Button
          title="Enviar"
          onPress={(newMessages: any) => handleSend([testeMensagem])}
        />
      </View>
    )
  }

  return (
    <View
      style={{
        flex: 1,
      }}
    >
      <GiftedChat
        renderSend={renderSend}
        messages={messages}
        onSend={(newMessages: IMessage[]) => handleSend(newMessages)}
        user={{ _id: 1, name: "User" }} />
    </View>
  );
```

What could I be missing?
