### ISSUE TITLE
get user's Location

### ISSUE THREAD

**Issue by EbrahimiM** [FaridSafi/react-native-gifted-chat#1057]
Dear Sir,
Would you please, how I can get user's Location in Gifted Chat?
In advance thank you for your help.
Whit best Regards

**Comment by mafiusu** [comment]
Get users location is not handled by the GiftedChat component. You have to look at the React Native docs under Geolocation.

https://facebook.github.io/react-native/docs/geolocation

**Comment by EbrahimiM** [comment]
I really appreciate you taking the time to respond me.
