### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by nandiniparimi1107** [FaridSafi/react-native-gifted-chat#1059]
I am eagerly waiting for the next release. @xcarpentier when will that be?

**Comment by xcarpentier** [comment]
Sorry this is not an issue :/
But I will try to publish next week.
And you can use master BTW.

**Comment by jaspervanbrian** [comment]
Please release!

**Comment by nandiniparimi1107** [comment]
@xcarpentier please let us know when will be the next release

**Comment by xcarpentier** [comment]
Done [v0.6.0](https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/v0.6.0)
