### ISSUE TITLE
Adding a background image on chat bubble?

### ISSUE THREAD

**Issue by nandiniparimi1107** [FaridSafi/react-native-gifted-chat#1061]
How to add a background image on a chat bubble? 
I need to add my own image as background,

**Comment by mafiusu** [comment]
This feature is still not supported by the GiftedChat component. You have to extend the codebase a little bit. When I have time, I'll take a look at it this evening :)

**Comment by nandiniparimi1107** [comment]
@mafiusu please let me know or give some suggestions  to fix it.

**Comment by evertonco** [comment]
Just wrap Bubble component on ImageBackground component on renderBubble prop.

```
renderBubble = props => {
...
<ImageBackground>
  <Bubble {...props} />
</ImageBackground>
}
```
