### ISSUE TITLE
Re-display messages to the user after re-login

### ISSUE THREAD

**Issue by EbrahimiM** [FaridSafi/react-native-gifted-chat#1063]
Dear Sir,
As you know, messages are erased when user log out of the chat application. In order for the user to see his last messages after re-login the application, I am investigating whether SQLite is a suitable method for storing and displaying messages (text, Image and Map). If there is a better solution, would you please introduce it to me?
In advance I appreciate for your help.

Whit best Regards

**Comment by xcarpentier** [comment]
Sorry but this is not thé place to ask this such of issue. Please try stackoverflow.
