### ISSUE TITLE
Feature Request: set MAX_COMPOSER_HEIGHT in the props

### ISSUE THREAD

**Issue by graphee-gabriel** [FaridSafi/react-native-gifted-chat#1065]
#### Issue Description
Feature Request

#### Steps to Reproduce / Code Snippets
Write a long text. Right now the text input grows too big on some screens

#### Expected Results
Be able to limit the height the input can grow to by setting a prop maxComposerHeight.

**Comment by xcarpentier** [comment]
Done [v0.6.0](https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/v0.6.0)

**Comment by graphee-gabriel** [comment]
Thank you so much :-)
