### ISSUE TITLE
How can i implement transient quick reply buttons

### ISSUE THREAD

**Issue by moschap** [FaridSafi/react-native-gifted-chat#1067]
I am using Gifted Chats for a Chatbot, and there is a functionality that i want to design, to make the conversation as controlled as possible i want to design a transient quick reply button, like what is available in 
[Facebook Messenger](https://developers.facebook.com/docs/messenger-platform/send-messages/quick-replies), i have tried to add the quick reply button directly in a chat bubble but it is not very neat, please is there a better way to implement this functionality. 

NB: It is not important for the actions to be transient.

* Nodejs version: 8.3
* React version: 16.6.1
* React Native version: 0.57.7
* react-native-gifted-chat version: 0.5.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by l-Legacy-l** [comment]
I'm looking for the same feature, is there any solution to make it work ?

**Comment by RoninSTi** [comment]
I implemented this by using the `renderChatFooter` prop. When I want to show quick reply options, I have this function return a component that is essentially a horizontal flatlist of buttons with options. Clicking the button fires the `onSend` method with the selected message.

**Comment by nccharles** [comment]
> I implemented this by using the `renderChatFooter` prop. When I want to show quick reply options, I have this function return a component that is essentially a horizontal flatlist of buttons with options. Clicking the button fires the `onSend` method with the selected message.

@RoninSTi Can you drop your code here please?

**Comment by roshansingh21** [comment]
> I implemented this by using the `renderChatFooter` prop. When I want to show quick reply options, I have this function return a component that is essentially a horizontal flatlist of buttons with options. Clicking the button fires the `onSend` method with the selected message.

@RoninSTi I am working on same but having trouble using the onSend method. Could you share your code here please?
