### ISSUE TITLE
Bottom Offset applies to other iphones as well.

### ISSUE THREAD

**Issue by nandiniparimi1107** [FaridSafi/react-native-gifted-chat#1073]
#### Issue Description
If we wrap giftedchat component in safeAreaView , it adds a space between keyboard and inputtoolbar on keyboard open. 

To solve this issue if we add bottomOffset the bottomOffset also applies to other iphones( i.e., iphone 7 etc).

How do we add bottomOffset only if its iphone X?

**Comment by tehwayne** [comment]
you can use a library like https://github.com/ptelad/react-native-iphone-x-helper#readme to code behavior for the offset
