### ISSUE TITLE
how can I change the default timezone en to Australia timezone? the locale prop seems like not working

### ISSUE THREAD

**Issue by ManuRodgers** [FaridSafi/react-native-gifted-chat#1077]
#### Issue Description

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by xcarpentier** [comment]
Please fill the issue description. Thanks.
