### ISSUE TITLE
how can I only render 3 messages at once and I can scroll list view to see other messages

### ISSUE THREAD

**Issue by ManuRodgers** [FaridSafi/react-native-gifted-chat#1081]
#### Issue Description
I am working on a chat app with React Native and my boss wants to have the result that only show three or four messages at once just like what Instagram does.
[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[
![image](https://user-images.githubusercontent.com/33333844/51145352-b3ffc680-18a7-11e9-9c3f-7a2987a3b420.png)
the picture is the current result 
FILL THIS OUT]

#### Expected Results

[
![image](https://user-images.githubusercontent.com/33333844/51145459-08a34180-18a8-11e9-80aa-13a38b76adf4.png)
FILL THIS OUT]

the picture above is something I want to achieve

#### Additional Information

* Nodejs version:v10.10.0

* React version: [FILL THIS OUT]
* React Native version:  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 60.35 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 27
        Build Tools: 26.0.3, 27.0.3, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.5 => 0.57.5 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

* react-native-gifted-chat version: 0.5.0
* Platform(s) (iOS, Android, or both?): IOS

**Comment by kevingalvez-pro** [comment]
As far as I know this is not a feature in gifted chat. You can just limit the messages you feed in the "messages" prop.
