### ISSUE TITLE
Load earlier messages by pull

### ISSUE THREAD

**Issue by konclave** [FaridSafi/react-native-gifted-chat#1082]
#### Issue Description

Now there's a way to add load earlier button at the top of the messages list, or refresh list by passing `onRefresh and refreshing` props to FlatList via `listViewProps`. 
In the second case refresh will be done on pulling list from the bottom to the top.

Is there a way to keep inverted FlatList, but load earlier messages by scroll to the earliest message loaded (at the very top of the list) and pull the list from the top to bottom and control list scroll to keep current earliest element at the place when earlier messages will be loaded?

#### Additional Information

* Nodejs version: 10.10.0
* React version: 16.6.1
* React Native version: 0.57.5
* react-native-gifted-chat version: 0.6.0
* Platform(s) (iOS, Android, or both?): both

**Comment by evertonco** [comment]
Have you try wrap GiftedChat on ScrollView component and implement refresh control on ScrollView?

**Comment by konclave** [comment]
@evertonco wrapping GiftedChat into ScrollView doesn't give me control on on scroll position inside GiftedChat. I can't keep list position when new messages are loaded and added to the list.

**Comment by MarcoLLeite** [comment]
I also tried to wrap GiftedChat into a ScrollView, but I dont have control of the refresh section. And I assume I will have the same issue as @konclave.

At the moment I am just using the button, but I would rather not.
Anyone know a clear way to implement the pull to load more?

Thanks

**Comment by evertonco** [comment]
Hey guys, have you tried use [onEndReach](https://facebook.github.io/react-native/docs/flatlist#onendreached) and [onEndReachedThreshold](https://facebook.github.io/react-native/docs/flatlist#onendreachedthreshold) props?

**Comment by MarcoLLeite** [comment]
@evertonco I have tried with this:

```
listViewProps={
    {
      onEndReached: this.onEndReached,
      onEndReachedThreshold: 1000,
    }
}
```

But this didn't seem to work correctly, but it seems to trigger before getting to the end of the list, way before. I explain better:
I have about 100 messages loaded on initial load.
Without scrolling, I can see around 12-15 messages.
As soon as I start scrollig the OnEndReached action gets triggered.

I have also tried to wrap the Gifted chat around a Scroll View with a refresh control, but the screen gets confusing between scrolling and refreshing.

**Comment by trane294** [comment]
Any update on that?

**Comment by zzbynzz** [comment]
Any update on solution about this ?

**Comment by ntnamag** [comment]
This issue is very necessary. No any update?

**Comment by TheYoungBoss** [comment]
> This issue is very necessary. No any update?

indeed I'm facing to the same problem. Any idea ?

**Comment by hubermat** [comment]
onEndReachedThreshold is a value between 0 and 1.

This works for me perfectly:

```
listViewProps={
  {
    onEndReached: this.onLoadEarlier.bind(this),
    onEndReachedThreshold: 0.5,
  }
}
```

**Comment by Srinidhi1561997** [comment]
"Load earlier message" button is displaying when there are no previous messages also. I have wriiten a code for it but still it's not working.`Please help me with this, i'm disabling the load earlier message button when there no any earlier messages, but this particular code is not working.


*emphasized text*this.loadCompletionListener = emitter.addListener('loadMoreCompled', () => {
      console.log('load earlier complete');
      this.setState({ loadEarlier: false, isLoadingEarlier: false, isLoadingMessages: false });
      this.forceUpdate();
    });`

**Comment by AdityaBelani** [comment]
### The most awaited solution everybody has been waiting for!!

I was surprised to see how over the whole internet the solution for such a simple problem was not there. After wasting 2 days of my life I finally ended up with such simple solution of this problem.  Just add the following code in the 'listviewprops':
```
listViewProps={{
      refreshControl: <RefreshControl refreshing={refreshing} onRefresh={_onLoadEarlier} />,
}}
```

Declare this variable on top:
```
const [refreshing, setRefreshing] = React.useState(false);
```

Declare the contents inside the method which would be called when pull to refresh happens:
```
const _onLoadEarlier = React.useCallback(() => {
        setRefreshing(true);
        setTimeout(() => {
            setRefreshing(false);
        }, 2000);
        //Any action which needs to be performed when pull to refresh happens
        setRefreshing(false);
}, []);
```

Also make sure to remove the following props from the code as they might interfere with this:
```
loadEarlier={state.loadEarlier}
isLoadingEarlier={state.isLoadingEarlier}
onLoadEarlier={_onLoadEarlier}
```

**Please give a reaction or reply in thread if it solves your problem. Or even if you're not able to understand it from here, you can contact me directly. I will help you out.
Thank You :computer:**

**Comment by bogdanSgithub** [comment]
my refresh control is at the bottom of the screen and don't know how to fix it...
```jsx
<GiftedChat
          messages={messages}
          onSend={(messages) => onSend(messages)}
          user={{
            _id: safeParams.myId,
            name: safeParams.myUsername
          }}
          renderTime={() => null}
          renderAvatar={() => (
            <Image source={{ uri: safeParams.avatar }} style={{ width: 36, height: 36, borderRadius: 18, marginLeft: 8 }} />
          )}
          maxComposerHeight={100}
          listViewProps={{
            refreshControl: <RefreshControl progressViewOffset={20} refreshing={refreshing} onRefresh={_onLoadEarlier} />,
          }}
        />
```

**Comment by bogdanSgithub** [comment]
> ### The most awaited solution everybody has been waiting for!!
> I was surprised to see how over the whole internet the solution for such a simple problem was not there. After wasting 2 days of my life I finally ended up with such simple solution of this problem. Just add the following code in the 'listviewprops':
> 
> ```
> listViewProps={{
>       refreshControl: <RefreshControl refreshing={refreshing} onRefresh={_onLoadEarlier} />,
> }}
> ```
> 
> Declare this variable on top:
> 
> ```
> const [refreshing, setRefreshing] = React.useState(false);
> ```
> 
> Declare the contents inside the method which would be called when pull to refresh happens:
> 
> ```
> const _onLoadEarlier = React.useCallback(() => {
>         setRefreshing(true);
>         setTimeout(() => {
>             setRefreshing(false);
>         }, 2000);
>         //Any action which needs to be performed when pull to refresh happens
>         setRefreshing(false);
> }, []);
> ```
> 
> Also make sure to remove the following props from the code as they might interfere with this:
> 
> ```
> loadEarlier={state.loadEarlier}
> isLoadingEarlier={state.isLoadingEarlier}
> onLoadEarlier={_onLoadEarlier}
> ```
> 
> **Please give a reaction or reply in thread if it solves your problem. Or even if you're not able to understand it from here, you can contact me directly. I will help you out. Thank You 💻**

Hello, my refresh control is at the bottom of the screen and don't know how to fix it...
I tried playing with inverted={false} but then i believe there to be performance issues using that since you have to reverse the list of messages yourself.
```jsx
<GiftedChat
          messages={messages}
          onSend={(messages) => onSend(messages)}
          user={{
            _id: safeParams.myId,
            name: safeParams.myUsername
          }}
          renderTime={() => null}
          renderAvatar={() => (
            <Image source={{ uri: safeParams.avatar }} style={{ width: 36, height: 36, borderRadius: 18, marginLeft: 8 }} />
          )}
          maxComposerHeight={100}
          listViewProps={{
            refreshControl: <RefreshControl progressViewOffset={20} refreshing={refreshing} onRefresh={_onLoadEarlier} />,
          }}
        />
```

**Comment by asadhmv** [comment]
The refreshControl is no more available in the props of the listView. Is it still a working way ?
