### ISSUE TITLE
attachments appending twice.

### ISSUE THREAD

**Issue by inceptivetech** [FaridSafi/react-native-gifted-chat#1086]
#### Issue Description

When user send the attachments like picture, video and recording, lastly send attachment are appending twice in chat at the sender as well as receiver side. The attachment are sending to the firebase one time as well as get the attachment is also one time but rendering attachment twice. I have attached the chatscreen.zip file below.

#### Steps to Reproduce / Code Snippets

 renderBubble = (props) => { 
return (
                        <View>
                            {
                                props.messages[0].type === "image" ?

                                    props.messages[0].user._id !== userStore.uid ?
                                        <View>
                                            {/* {alert("id :" + props.messages[0]._id)} */}
                                            {/* {this.renderId()} */}
                                            <TouchableOpacity onPress={() => Actions.ViewImage({ data_image: props.messages[0].path, title: "Image" })}>
                                                <Image
                                                    source={{ uri: props.messages[0].path }}
                                                    style={{
                                                        width: 250,
                                                        height: 150,
                                                        borderRadius: 13,
                                                        borderColor: '#4F8EF7',
                                                        borderWidth: 1,
                                                        margin: 3,
                                                        resizeMode: 'cover',
                                                    }}
                                                />
                                            </TouchableOpacity>
                                        </View> : <View>
                                            <TouchableOpacity onPress={() => Actions.ViewImage({ data_image: props.messages[0].path, title: "Image" })}>
                                                <Image
                                                    source={{ uri: props.messages[0].path }}
                                                    style={{
                                                        width: 250,
                                                        height: 150,
                                                        borderRadius: 13,
                                                        borderColor: '#feca2f',
                                                        borderWidth: 1,
                                                        margin: 3,
                                                        resizeMode: 'cover',
                                                    }}
                                                />
                                            </TouchableOpacity>
                                        </View>

                                    : null
                            }

                            {
                                props.messages[0].type === "video" ?
                                    props.messages[0].user._id !== userStore.uid ?

                                        <View style={{ width: '100%', padding: 10, backgroundColor: '#000000', borderWidth: 1, borderColor: '#4F8EF7', borderRadius: 10, flexDirection: 'row' }}>
                                            {/* {this.renderId()} */}
                                            {alert("image_type : " + JSON.stringify(props.messages[0].id_))}
                                            <TouchableOpacity onPress={() => Actions.ViewVideo({ data_image: props.messages[0].path, title: "Video Playback" })}>

                                                <VideoPreview
                                                    source={{ uri: props.messages[0].path }}
                                                    style={styles.preview} >

                                                </VideoPreview>
                                                <Icon name="ios-play-circle" color="#4F8EF7" size={35} style={{ position: 'absolute', top: 65, left: 120 }} />
                                            </TouchableOpacity>
                                            {/* <Text>Play Video</Text> */}
                                        </View> :
                                        <View onPress={() => Actions.ViewVideo({ data_image: props.messages[0].path, title: "Video Playback" })} style={{ width: '100%', borderRadius: 10, backgroundColor: '#000000', borderWidth: 1, borderColor: '#feca2f', flexDirection: 'row' }}>
                                            {this.renderId(props.messages[0]._id)}
                                            <TouchableOpacity onPress={() => Actions.ViewVideo({ data_image: props.messages[0].path, title: "Video Playback" })}>
                                                <VideoPreview
                                                    source={{ uri: props.messages[0].path }}
                                                    style={styles.preview} >

                                                </VideoPreview>
                                                <Icon name="ios-play-circle" color="#feca2f" size={35} style={{ position: 'absolute', top: 65, left: 120 }} />
                                            </TouchableOpacity>
                                            {/* <Text>Play Video</Text> */}
                                        </View> : null}

                            {this.state.messages[0].type === 'audio' ?
                                props.messages[0].user._id !== userStore.uid ?
                                    <View style={{ width: '100%', padding: 10, backgroundColor: '#ffffff', borderRadius: 10, flexDirection: 'row' }}>
                                        {/* {this.renderId()} */}
                                        <Icon
                                            onPress={() => {
                                                this.setState({ playAudio: !this.state.playAudio });
                                                const sound = new Sound(props.messages[0].path, "", error => {
                                                    if (error) {
                                                        console.log("failed to load the sound", error);
                                                    }
                                                    this.setState({ playAudio: false });
                                                    sound.play(success => {
                                                        console.log(success, "success play");
                                                        if (!success) {

                                                            Alert.alert("There was an error playing this audio");
                                                        }
                                                    });
                                                });
                                            }
                                            }

                                            name={this.state.playAudio ? "ios-pause" : "ios-mic"}
                                            // name = "ios-pause"
                                            size={35}
                                            color={"#1589FF"}

                                            style={
                                                {
                                                    left: 90,
                                                    position: "relative",
                                                    shadowColor: "#000",
                                                    shadowOffset: { width: 0, height: 0 },
                                                    shadowOpacity: 0.5,
                                                    backgroundColor: "transparent"
                                                }
                                            }
                                        />
                                    </View> :
                                    <View style={{ width: '100%', padding: 10, backgroundColor: '#feca2f', borderRadius: 10, flexDirection: 'row' }}>
                                        {/* {this.renderId()} */}
                                        <Icon
                                            onPress={() => {
                                                this.setState({ playAudio: !this.state.playAudio });
                                                const sound = new Sound(props.messages[0].path, "", error => {
                                                    if (error) {
                                                        console.log("failed to load the sound", error);
                                                    }
                                                    this.setState({ playAudio: false });
                                                    sound.play(success => {
                                                        console.log(success, "success play");
                                                        if (!success) {

                                                            Alert.alert("There was an error playing this audio");
                                                        }
                                                    });
                                                });
                                            }
                                            }

                                            name={this.state.playAudio ? "ios-pause" : "ios-mic"}
                                            // name = "ios-pause"
                                            size={35}
                                            color={"#1589FF"}

                                            style={
                                                {
                                                    left: 90,
                                                    position: "relative",
                                                    shadowColor: "#000",
                                                    shadowOffset: { width: 0, height: 0 },
                                                    shadowOpacity: 0.5,
                                                    backgroundColor: "transparent"
                                                }
                                            }
                                        />
                                    </View>
                                : null}
                            <Bubble {...props}
                                wrapperStyle={{
                                    right:
                                    {
                                        backgroundColor: '#feca2f',
                                    },
                                    left:
                                    {
                                        backgroundColor: '#ffffff',
                                    },
                                }}

                                textStyle={{
                                    right: {
                                        color: '#000',
                                    },
                                }}

                            />
                        </View>
                    );
                }

code for the appending message :

 Firebase.database().ref(`user_chats/${userStore.uid}/posts`).child(`${this.props.data.puid}`).once('value',
            (snapshot) => {
                Actions.refresh({ title: friendName })
                this.setState({
                    status: snapshot.val().status,
                    postProps: snapshot.val(),
                });

                 Firebase.database().ref(`user_chats/${userStore.uid}/posts`).child().once("value", function(snapshot) {
                     alert("There are "+snapshot.numChildren()+" messages");
                   })
                 if (snapshot.val().text) {
                     this.setState((previousState) => {
                        return {
                          messages: GiftedChat.append(previousState.messages,
                               {
                                     _id: snapshot.val()._id,
                                     text: snapshot.val().text,
                                     createdAt: new Date(message.createdAt),
                                     type: message.type,
                                    path: message.path,
                                    user:
                                    {
                                       _id: snapshot.val().uid,
                                         name: snapshot.val().username,
                                     },
                                }),
                        }
                     })
                }
            });

        this._loadMessages((message) => {
            {alert("message on load :" + message._id)}
            this.setState((previousState) => {
                return {

                    messages: GiftedChat.append(previousState.messages, {
                        _id: message._id,
                        text: message.text,
                        createdAt: new Date(message.createdAt),
                        type: message.type,
                        path: message.path,
                        user: {
                            _id: message.user._id,
                            name: message.user.name,
                        }

                    }),

                     messages: GiftedChat.append(previousState.messages, message),
                    
                }

            })

        });

#### Expected Results
The attachment should be send only once.

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version:0.55.4
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?):android

[ChatScreen.zip](https://github.com/FaridSafi/react-native-gifted-chat/files/2767316/ChatScreen.zip)

**Comment by evertonco** [comment]
Maybe you are appending messages to store twice and problem is not related to this code piece.

**Comment by songxiaoliang** [comment]
@inceptivetech 解决了吗？

**Comment by izemauricio** [comment]
I have the same problem, the image ballon, for some reason, is rendered twice when a new text message is attached
