### ISSUE TITLE
auto scroll down when scroll up (only in android 9) 

### ISSUE THREAD

**Issue by piggy2303** [FaridSafi/react-native-gifted-chat#1087]
#### Issue Description

my code work well in android 8.1 
but today i upgrade my phone to android 9 and have this bug

i have ~ 151 mess in my screen when i scroll up to read more mess is auto scroll down ,

* React version: 16.4.1
* React Native version: 0.56.0
* react-native-gifted-chat version:  0.4.3
* Platform(s) (iOS, Android, or both?): only on android 9

**Comment by Athinodoros** [comment]
I also have the same issue. But if I scroll slowly it doesn't scroll to bottom and it also does it the other way... if you try to scroll down fast it scrolls to top and vise versa. 

Is this only happening on Android 9 ?

**Comment by rodolphefauquez** [comment]
To everyone still having this bug, it's not related to this library: This is fixed with RN0.58 but i think they already fixed it with a workaround with RN0.57.6 update.

**Comment by joey3060** [comment]
Upgrading the version to 0.58.6, the problem still exists
