### ISSUE TITLE
Unable ti import video component from react native video library after import react native gifted chat

### ISSUE THREAD

**Issue by Manrajparmar** [FaridSafi/react-native-gifted-chat#1093]
#### Issue Description

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by adilosa** [comment]
Also hit this issue after upgrading to Gifted Chat 0.6.0

Issue Description

I have react-native-video installed separately for use elsewhere in the app. 

Upgraded to Gifted Chat 0.6.0, started getting red screen error saying "Tried to register two views with the same name RCTVideo".

Changed react-native-video version from 4.0.1 --> 3.2.1 to match Gifted Chat dependency. Issues persisted.

Steps to Reproduce / Code Snippets

[FILL THIS OUT]

Expected Results

[FILL THIS OUT]

Additional Information

Nodejs version: [FILL THIS OUT]
React version: 16.6.3
React Native version: 0.57.8
react-native-gifted-chat version: 0.6.0
Platform(s) (iOS, Android, or both?): iOS (only tested iOS)

**Comment by adilosa** [comment]
Uninstalling react-native-video fixes the crash. Ideally, a fix would allow for both react-native-video and react-native-gifted-chat to be installed at the same time.

**Comment by vanhungoz** [comment]
at the moment, i delete react-native-video in gifted-chat/node-module. i is just a trick

**Comment by jaspervanbrian** [comment]
Yep same issue here. I also deleted gifted-chat/node-modules/react-native-video dir. **Hoping** to get a solution from you.

**Comment by vanhungoz** [comment]
it should work :D

**Comment by khushhal** [comment]
Thanks, i found the alternate solution only if you are not having video in chat you can downgrade the version to use both libraries together
**"react-native-gifted-chat": "^0.4.3"**

But with this video will **not supported** in chat.

**Comment by jgbaEmento** [comment]
maybe it's a 'yarn' problem, I was able to remove this error, simply by removing 'yarn.lock' and remove node_modules and clear yarn cache and re-running yarn install. 
`rm yarn.lock && rm -rf node_modules && yarn cache clean && yarn`

**Comment by SumitThakr** [comment]
I have solve this problem by following steps--
  1> install separately "react-native-video"
  2> Delete  "react-native-video" folder from Node-Modules of Gifted Chat repositories, if it is exist..
  3>after  that  "react-native link react-native-video"
       like That:
         include ':react-native-video'
        project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react- 
        native-video/android')

     ensure that link with only "android" not with "android-exoplayer"

**Comment by benwong118** [comment]
> I have solve this problem by following steps--
> 1> install separately "react-native-video"
> 2> Delete "react-native-video" folder from Node-Modules of Gifted Chat repositories, if it is exist..
> 3>after that "react-native link react-native-video"
> like That:
> include ':react-native-video'
> project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-
> native-video/android')
> 
> ```
>  ensure that link with only "android" not with "android-exoplayer"
> ```
It works for me even using the last version. Thanks 

    "react": "^16.8.6",
    "react-native": "^0.59.4",
    "react-native-video": "^4.4.1",
    "react-native-video-player": "^0.10.0",
    "react-native-gifted-chat-video-support": "^0.4.6",

**Comment by hnrqsss** [comment]
In my case gifted-chat has the react-native-video to so inside package.json in the gifited-card i see the version is the video is 3.2.1  on my global package.json i install the same version.
rm -rf node_modules/
yarn install --frozen-lockfile.
