### ISSUE TITLE
FlatList spaces between newly added messages [bug]

### ISSUE THREAD

**Issue by shaheem-khanzada** [FaridSafi/react-native-gifted-chat#1098]
![screenshot_20190123-122706 1](https://user-images.githubusercontent.com/37620819/51590097-a337fc00-1f0a-11e9-8b9b-e3a7d9c86c98.png)

**Comment by Parthasarath** [comment]
const COMPOSER_HEIGHT = 60;

****
renderInputToolbar(props) {
   return <InputToolbar {...props} containerStyle={[styles.inputToolBar]} />;
}

renderComposer(props) {
   return <Composer 
             {...props} 
             placeholder={'Type a message...'} 
             placeholderColor={'#BCBCBC'} 
             textInputStyle={styles.composerText}
          />;
}

****

<GiftedChat
  composerHeight={COMPOSER_HEIGHT}
  minInputToolbarHeight={COMPOSER_HEIGHT}
  renderAvatar={null}
  messages={currentInbox ? currentInbox.messages.slice().reverse() : []}
  renderBubble={props => this.renderBubble(props)}
  renderMessageText={props => this.renderMessageText(props)}
  renderTime={props => this.renderTime(props)}
  renderInputToolbar={props => this.renderInputToolbar(props)}
  renderComposer={props => this.renderComposer(props)}
  renderActions={props => this.renderActions(props)}
  renderSend={props => this.renderSend(props)}
  renderMessageImage={props => this.renderMessageImage(props)}
  onSend={messages => this.onSend(messages)}
  user={user}
/>

****

styles

inputToolBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    maxHeight: COMPOSER_HEIGHT,
    minHeight: COMPOSER_HEIGHT,
    justifyContent: 'center',
    borderTopWidth: 0,
    shadowOpacity: 0.10,
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: -2
    },
    elevation: 2,
    shadowRadius: 2
  },
  composerText: {
    maxHeight: COMPOSER_HEIGHT,
    fontFamily: 'Quicksand-Medium',
    color: '#333333',
    fontSize: Normalize(14),
  },

Change composer height to adjust that spaces between newly added messages.

**Comment by shaheem-khanzada** [comment]
have you also faced same issue ??

**Comment by Parthasarath** [comment]
> have you also faced same issue ??

Yes

**Comment by shaheem-khanzada** [comment]
i am still facing i set both composerHeight={COMPOSER_HEIGHT}
minInputToolbarHeight={COMPOSER_HEIGHT} but noting happens

**Comment by Parthasarath** [comment]
> i am still facing i set both composerHeight={COMPOSER_HEIGHT}
> minInputToolbarHeight={COMPOSER_HEIGHT} but noting happens

render() {
 const COMPOSER_HEIGHT = 60;
return (
 <GiftedChat
                        composerHeight={COMPOSER_HEIGHT}
                        minInputToolbarHeight={COMPOSER_HEIGHT}
                        messages={this.state.messages}
                        onSend={messages => this.onSend(messages)}
                        user={{ _id: this.state.customerId }}
                        />
) }

Try this method

**Comment by shaheem-khanzada** [comment]
noting happens i guess its not problem with composer height its problem with flatList

**Comment by xcarpentier** [comment]
Hi,
@shaheem-khanzada Can you please make a PR with your code fix?
Thanks

**Comment by shaheem-khanzada** [comment]
its not get fixed yet because shouldComponentUpdate do great job with performace but when we remove component should update life cycle it start rendering all messages again  and do not create space

**Comment by xcarpentier** [comment]
Fixed in [v0.7.2](https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/v0.7.2)
