### ISSUE TITLE
When user sends the image or video it displaces at receiver side. 

### ISSUE THREAD

**Issue by inceptivetech** [FaridSafi/react-native-gifted-chat#1099]
#### Issue Description
When the sender sends the image or video it display at the receiver side. It should be at the sender side i.e.on right hand side.

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: 16.3.0-alpha.0
* React Native version: 0.55.4
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): android

**Comment by xcarpentier** [comment]
Hi,
Are you sure you setup user correctly on Image or Video message?
Best regards

**Comment by inceptivetech** [comment]
Hi,
thanks for your feedback. We are very sure about user information here, we have checked default text message format for user and same is used in case of audio and video. 
We have noticed this issue only with video/audio message with user avatar. When no user avatar is there these messages comes properly for sender and receiver.
Please check attached screenshot

**Comment by LG1710** [comment]
I have the same problem

**Comment by muhammadwfa** [comment]
Hi, when you send a message `{... user: {_id: 'a'}}`

on receiver side you should have this as message as it was at sender side  `{... user: {_id: 'a'}}`
I am sure when you receive the message you gave it diffrent user.
