### ISSUE TITLE
InputToolbar rises up to the top when user types

### ISSUE THREAD

**Issue by nubeble** [FaridSafi/react-native-gifted-chat#1102]
I'm using a ejected app (ios) from expo.
Everything was fine before I tested in ios. If I touched the input text, keyboard showed, I typed a letter then the input text jumps to the top. 
Does anyone know about this issue?

here's my code.

    <View style={{ flex: 1 }} >
                    <GiftedChat
                        minInputToolbarHeight={56}
                        textInputProps={{
                            style: {
                                width: '86%',
                                height: 56,
                                fontSize: 16,
                                color: "white",
                                paddingTop: 6,
                                paddingLeft: 16,
                                paddingRight: 16
                            }
                        }}
                        renderSend={this.renderSend}
                        renderInputToolbar={this.renderInputToolbar}
                    >
                    <KeyboardSpacer />
    </View>

    renderSend(props) {
        return (
            <Send {...props} >
                <View style={{
                    marginBottom: 14
                }}>
                    <Ionicons name='ios-send' color={Theme.color.selection} size={28} />
                </View>
            </Send>
        );
    }

    renderInputToolbar(props) {
        return <InputToolbar {...props} containerStyle={{
            backgroundColor: Theme.color.background,
            borderTopColor: Theme.color.textInput
        }} />
    }

![1](https://user-images.githubusercontent.com/30099148/51691069-6587c000-203d-11e9-9dba-62f1b28bf228.PNG)
![2](https://user-images.githubusercontent.com/30099148/51691074-67ea1a00-203d-11e9-80c2-a9c6da4ea518.PNG)
![3](https://user-images.githubusercontent.com/30099148/51691078-69b3dd80-203d-11e9-897f-6f326430bd4a.PNG)

#### Additional Information
. React Native + Expo -> eject
. working fine in android, only in ios this issue occurred
. latest version of react-native-gifted-chat

**Comment by xcarpentier** [comment]
Can you please test on v0.7.1 and let us know if it's still the case?

**Comment by nubeble** [comment]
I tried with v0.7.1. But still same.

I found out the KeyboardSpacer component cause this issue.
If I remove <KeyboardSpacer> from <GiftedChat> under <View style={{ flex: 1 }} > this issue not happening. But the InputToolBar is not showing when keyboard opened. (But, if I text a letter then It appeared.)

So, have to find more solution for this.

**Comment by xcarpentier** [comment]
Ok, please let us know ;)

**Comment by NicWickman** [comment]
I am experiencing the same symptoms as Nubeble. When I open the keyboard, everything disappears (moves out of place), but pops back into place after typing on the keyboard.

**Comment by infaz** [comment]
Im also facing the same issue. If you are using "react-native-keyboard-manager", then disable it in this view,

```
componentDidMount() {
    KeyboardManager.setEnable(false);
    KeyboardManager.setEnableAutoToolbar(false);
 }
```

**Comment by IshanNaktode** [comment]
+1 @xcarpentier 

Same issue here. Only for iOS. Expo App.

Had issue with android also, but doing below fixed it. 

```
<KeyboardAvoidingView behavior="padding" style={{flex:1}}>
    <App/>
</KeyboardAvoidingView>
```

This might be causing issues with iOS due to differences in result of behavior prop on iOS and Android - [Check out this link](https://facebook.github.io/react-native/docs/keyboardavoidingview#behavior)

**Comment by projectpublius** [comment]
Since I also use KeyboardAvoidingView, I fixed this issue by editing GiftedChat.js in the `getKeyboardHeight()` function at line 180, replacing
`return this._keyboardHeight;`
with
`return 0;`

**Comment by wangdicoder** [comment]
> Since I use KeyboardAvoidingView, I fixed this issue by editing GiftedChat.js in the `getKeyboardHeight()` function at line 174, replacing
> `if (Platform.OS === 'android' && !this.props.forceGetKeyboardHeight) {`
> with
> `if (!this.props.forceGetKeyboardHeight) {`
> so that the function will return 0 for both ios and android.

Should consider checking whether `KeyboardAvoidingView` is used to determine the keyboard height at that line?

**Comment by ManuEpi** [comment]
Does someone have a solution for it ? (In the case where we don't want to modify source files)

**Comment by ManuEpi** [comment]
+1

**Comment by jamonholmgren** [comment]
I was able to fix it by setting `isKeyboardInternallyHandled={false}` on the `GiftedChat` component.

**Comment by usamamoinakhter** [comment]
Facing same issue

**Comment by rentedpanda** [comment]
any solution? permanent?

**Comment by socialcode-rob1** [comment]
It doesn't happen on all android versions.
I see it on Android 10.  

On Android 8 it works fine.

**Comment by epalacio90** [comment]
> I was able to fix it by setting `isKeyboardInternallyHandled={false}` on the `GiftedChat` component.

Having the same problem, I was able to fix it with this

**Comment by ysng007** [comment]
"react-native-gifted-chat": "^2.4.0"
Currently, there is still this issue on iOS. Setting isKeyboardInternalHandled={false} cannot solve the problem, and the performance is similar to before. When the keyboard pops up, there is still a large gap between the input box and the keyboard.
