### ISSUE TITLE
next.createdAt.getTime is not a function when loading or sending messages

### ISSUE THREAD

**Issue by 2021debaisen** [FaridSafi/react-native-gifted-chat#1105]
I think the latest version of Gifted Chat that was updated 7 hours ago broke the entire rendering of messages. I had just updated to 0.7.1 and on loading of my messages from a firebase server, which is passed to redux and then passed as a prop to the messages in gifted chat, I get an error saying 

TypeError : next.createdAt.getTime is not a function (In 'next.createdAt.getTime()', 'next.createdAt.getTime' is undefined)

I have since reverted back to 0.6.0 (the previously working version) and it is working perfectly.

I expected that my messages would be updated on the screen after I sent this text, but right as I sent the text, or loaded the messages from firebase, I got the aforementioned error.

#### Additional Information

* Nodejs version: v10.14.2
* React version: 16.7 (latest at the time)
* React Native version: 0.58 (latest at the time)
* react-native-gifted-chat version: 0.7.1 -> error : 0.6.0 -> no error
* Platform(s) (iOS, Android, or both?): IOS

**Comment by xcarpentier** [comment]
Close with https://github.com/FaridSafi/react-native-gifted-chat/commit/2c915f0281f8475331025f992ad9098c79a01e1a
