### ISSUE TITLE
How to add an initial view to the conversation?

### ISSUE THREAD

**Issue by AideProjet** [FaridSafi/react-native-gifted-chat#1106]
Hi, 

Wondering how to add an initial conversation view, like in messenger where you have some introduction text and you can see both avatars.

Thanks,

Théo

**Comment by xcarpentier** [comment]
Hi Théo,

You maybe can investigate into `SystemMessage` and `renderMessage` props if it's system is true.

This is not an issue so, I will close it but you can continue to ask here with no problem 👍

**Comment by AideProjet** [comment]
Parfait Xavier, merci! Exactement ce dont j'avais besoin :) Si tu passes sur Bordeaux on a toujours besoin de dev React Native!

Bien à toi, 

Théo
