### ISSUE TITLE
Message Container missed call 'detatchKeyboardListeners' after unmout

### ISSUE THREAD

**Issue by MingFaiYau** [FaridSafi/react-native-gifted-chat#1107]
#### Issue Description
When we create / goto a new chat room, the length of message is 0 ,it will call 'attachKeyboardListeners'.

MessageContainer.js line 30
```
    if (props.messages.length === 0) {
      this.attachKeyboardListeners(props);
    }
```

And it will call 'detatchKeyboardListeners' after created a new message 

MessageContainer.js line 35
```
  componentWillReceiveProps(nextProps) {
    if (this.props.messages.length === 0 && nextProps.messages.length > 0) {
      this.detatchKeyboardListeners();
    } else if (this.props.messages.length > 0 && nextProps.messages.length === 0) {
      this.attachKeyboardListeners(nextProps);
    }
  }
```

If we don't create a new one and just go back , it won't call 'detatchKeyboardListeners' 
and it will get warning if we trigger keyboard event with other inputtext view. 

So we should add detatchKeyboardListeners after unmount ? or i missed sth?
Thanks.

**Comment by xcarpentier** [comment]
Close here: https://github.com/FaridSafi/react-native-gifted-chat/commit/d01272e95dcdae2b380a7f77135f1f9e74f3ce75
