### ISSUE TITLE
How to render the timestamp in custom renderBubble ?

### ISSUE THREAD

**Issue by inceptivetech** [FaridSafi/react-native-gifted-chat#1108]
#### Issue Description

When user sends the video or audio, it does not shows the timestamp for that message. after sending the another message, timestamp displays for previous message. We have using the custom renderBubble for video and audio.
#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

Timestamp should displays for the video and audio at the time of sending.

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: 16.3.0-alpha.0
* React Native version: 0.55.4
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): android

**Comment by mackclark** [comment]
I am seeing the same issue. I'm using custom renderBubble and custom renderSend for all messages, and I am seeing that the timestamp only appears for the previous received message when the user sends a message. Timestamps for sent messages never appear at all.

**Comment by inceptivetech** [comment]
Have you tried any solution for this issue ? If you tried any, please suggest.

**Comment by xcarpentier** [comment]
Please ask here: https://stackoverflow.com/questions/tagged/react-native-gifted-chat
