### ISSUE TITLE
How to align message and timestamp to be in a row (and not a column)?

### ISSUE THREAD

**Issue by TriinK** [FaridSafi/react-native-gifted-chat#1113]
#### Issue Description

How to add flexDirection: 'row' to <Bubble/> content so that the timestamp would be in row with the message?

#### Expected Results
<img width="197" alt="untitled" src="https://user-images.githubusercontent.com/33719534/51945207-b4ab6780-2426-11e9-832e-a21e0059fba2.png">

**Comment by xcarpentier** [comment]
Please use stackoverflow: https://stackoverflow.com/questions/tagged/react-native-gifted-chat

**Comment by mrshahzeb7** [comment]
@TriinK madam did you find the solution?
