### ISSUE TITLE
how do i get image url on tap of image message?

### ISSUE THREAD

**Issue by saikiranoptisol** [FaridSafi/react-native-gifted-chat#1115]
Hi, 

In my application it is something like i need to display image in thumbnail url in chat screen whose resolution is very less. Now on tap of that large size image has to bs shown by changing the thumbnail key to large in the url of the image. 
So, first of all how can i print that url in my JS file and then how to remove thumbnail and add large in the url. 
Ex url: https://cloudfrontURL/thumbnail/3184df63-3044-43da-a5d6-2156067d3201.jpg 

i place of thumbnail i need to replace large on tap of the image in chat room.

**Comment by xcarpentier** [comment]
Please use stackoverflow: https://stackoverflow.com/questions/tagged/react-native-gifted-chat
