### ISSUE TITLE
How to target chat bubble with ref

### ISSUE THREAD

**Issue by NicholasEli** [FaridSafi/react-native-gifted-chat#1116]
This is not a bug, but a question.

I have created a bubble in the renderBubble method and I am trying to attach a reference attribute to each bubble.  But I can not seem to accomplish this event if I assign a reference to the GiftedChat component and tunnel through it.

My main reason for wanting to target the bubble is to return things like x and y position.

**Comment by muhammadwfa** [comment]
```
<GiftedChat renderBubble={this.renderBubble} 
  // other props goes here ...
 />
```

```
bubbles = [];
renderBubble = props => {
   return (
     <Bubble {...props} ref = {bubble => {
           this.bubbles.push(bubble);
      }} />
   );
}
```

I made something like this but it didnt work for me if this help you please let me.
and also here I have opened an issue if you can help me please let me know

[My Issue](https://github.com/FaridSafi/react-native-gifted-chat/issues/1114)
