### ISSUE TITLE
message that user sent appear as grey message when reload the app

### ISSUE THREAD

**Issue by Graymark** [FaridSafi/react-native-gifted-chat#1117]
#### Issue Description

I have an app which is using Gifted-chat. When i write message in the gifted chat component they appear as sent message (in blue) as normal, but when i reload and call my message during the componentDidMount method, they appear as received message (in grey) even if the user ID is good. 

![image1](https://user-images.githubusercontent.com/23309661/52133264-455d8f80-2641-11e9-9e1a-18c72e8e6d63.PNG)
![image2](https://user-images.githubusercontent.com/23309661/52133266-45f62600-2641-11e9-8869-17e6ee9f3c3d.PNG)

#### Steps to Reproduce / Code Snippets

i put here my code snippets

![image](https://user-images.githubusercontent.com/23309661/52133374-7c33a580-2641-11e9-90f5-9287c17929c0.png)

![image](https://user-images.githubusercontent.com/23309661/52133459-a8e7bd00-2641-11e9-95f5-a8a051a940b4.png)

#### Expected Results

I would like that when i come back on my account the messages that i sent are still in blue

thank you for help :)

**Comment by xcarpentier** [comment]
Be sure you still have the same user, you stored the user id in your class, this is not really conventional prefer to store it in state or giving from props.

**Comment by Graymark** [comment]
Indeed i found my mistake, i was'nt passing the good user id

I have another question that you didn't answer in the other "Issue" on gitHub.

How can i have a sticky header at the top of my gifted chat component?
because actually i have a header, but when the keyboard appear the header is moving away from the screen
see [here](https://github.com/FaridSafi/react-native-gifted-chat/issues/799) the same topic issue.
