### ISSUE TITLE
Update react-native to 0.58 for best performance of flatList and animations

### ISSUE THREAD

**Issue by shaheem-khanzada** [FaridSafi/react-native-gifted-chat#1119]
#### Issue Description

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by xcarpentier** [comment]
react-native is a peer dependency
