### ISSUE TITLE
How to display no messages found if messages object is empty.

### ISSUE THREAD

**Issue by saikiranoptisol** [FaridSafi/react-native-gifted-chat#1122]
I was trying to render a view to display 'No messages found' if the messages object is empty. 
for this which function i need to use. Currently I tried using renderMessage but got error. i just want to figure it out how this can be achieved

My code is

```jsx
               <GiftedChat
                    composerHeight={COMPOSER_HEIGHT}
                    minInputToolbarHeight={COMPOSER_HEIGHT}
                    messages={this.state.messages}
                    onSend={messages => this.onSend(messages)}
                    user={{ _id: this.state.senderUserName }}
                    loadEarlier={this.state.loadEarlier}
                    isLoadingEarlier={this.state.isLoadingEarlier}
                    onLoadEarlier={this.onLoadEarlier}
                    placeholder="Type your message"
                    renderSend={this.renderSend}
                    alwaysShowSend={true}
                    renderActions={this.imageSend.bind(this)}
                    renderInputToolbar={this.renderInputToolbar}
                    renderBubble={this.renderBubble.bind(this)}
                    renderMessage={this.renderMessage.bind(this)}
                    renderMessageImage={this.renderMessageImage}
                    renderAvatar={null}
                    inverted={true}
                />
```

In render message my code is :
```jsx
renderMessage(props) {
  if(this.state.messages.length !==0){
       return <Message {...props} />;
 } else {
  return <View style={{flex:1, backgroundColor:'red'}}>
    <Text>Hello no data found</Text>
  </View>
}
return null
}
```
I know i'm doing wrong. But i can't be able to find correct result. any suggestions?

**Comment by xcarpentier** [comment]
Please use StackOverflow: https://stackoverflow.com/questions/tagged/react-native-gifted-chat

**Comment by saikiranoptisol** [comment]
for every question i was asking here you are mentioning to check in stackoverflow. But after checking in stackoverflow only i have posted here this. and yes i do have posted the same in stackoverflow as well https://stackoverflow.com/q/54529508/10966893  . please provide proper solution that will do needful for me

**Comment by xcarpentier** [comment]
Sorry :/ 
This is just because this project needs to be cleaned to have a proper updates flow. Too much question in issue is not so good, please understand...

**Comment by xcarpentier** [comment]
Not only check but ask on StackOverflow, I try to drive question on better tools than GitHub issue

**Comment by saikiranoptisol** [comment]
@xcarpentier  i agree with what you said but it's more than 8 hrs but i didn't get aby response there in stackoverflow. i need to do it as soon as possible, kindly help

**Comment by xcarpentier** [comment]
Did you try it: https://stackoverflow.com/a/54550286/1458375

**Comment by hadpro24** [comment]
@xcarpentier  

> Did you try it: https://stackoverflow.com/a/54550286/1458375

But it's not display a InputText if they used message.length == 0
