### ISSUE TITLE
How to access TextField's onFocus  using textInputProps

### ISSUE THREAD

**Issue by gomac** [FaridSafi/react-native-gifted-chat#1132]
I want to detect when the user clicks/presses the text field, before they enter text. Accessing the onInputTextChanged will only notify me once text is input. I'd like to know before.

Using onFocus seems like the go and I've read that it can be done with textInputProps
[https://github.com/FaridSafi/react-native-gifted-chat/issues/1118]
 but I'm a new to React Native and not sure how to do this. Could you provide an example?

**Comment by MingFaiYau** [comment]
you can try [onFocus](https://facebook.github.io/react-native/docs/textinput#onfocus)

```
onFocusHandler = ( e ) => {
      .....
}

<GiftedChat
...
textInputProps = {
      onFocus: this.onFocusHandler ,
}

...
/>

```

**Comment by gomac** [comment]
Yesss, I can confirm that
textInputProps = {{
      onFocus: this.onFocusHandler ,
}}

works. Thank you, Gordon
