### ISSUE TITLE
createAt not showing date/hours, and initial chat date

### ISSUE THREAD

**Issue by adriancuco** [FaridSafi/react-native-gifted-chat#1134]
#### Issue Description

When setting messages with proper createAt, when loaded first time, left side all messages at the beginning, I am able to see the chat date and other hours, by suddenly dates and times are vanished when moved owner messages to the right side.

Thanks a lot
Regards
#### Additional Information

* React Native version: 0.57 / 0.58
* react-native-gifted-chat version: 0.4.3 , 0.7.2
* Platform(s) (iOS, Android, or both?): Android, both emulator and physica device

**Comment by adriancuco** [comment]
I think the issue is when having same _id both msg and user. I set both by mistake with same value.
I will be confirming it later.
It's a little bit weird to use both _id  which might mislead, you know.

**Comment by adriancuco** [comment]
My fault. I found the issue.

Sorry for inconveniences ;)

Great job!!

Thx

**Comment by jeancabral** [comment]
> My fault. I found the issue.
> 
> Sorry for inconveniences ;)
> 
> Great job!!
> 
> Thx

Hi @adriancuco   I have the same problem. How did you solve it?

**Comment by uguraktas** [comment]
how did you solve the problem? explain, please

> My fault. I found the issue.
> 
> Sorry for inconveniences ;)
> 
> Great job!!
> 
> Thx

how did you solve the problem? explain, please
