### ISSUE TITLE
Is there any way to customize message when there are server message.

### ISSUE THREAD

**Issue by WebsitebuilderAU** [FaridSafi/react-native-gifted-chat#1138]
#### Issue Description

Actually, I have three types message, sender, receiver and server message.
I want to show server message without any avatar image and full width, center align.
But I didn't get any customization in the library to handle three types of message, please let me know how I can manage this case. 

#### Steps to Reproduce / Code Snippets
![chat](https://user-images.githubusercontent.com/47411953/52835848-4c3ed480-310e-11e9-9ca1-852687cdf3aa.png)

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by rakesh-eltropy** [comment]
@WebsitebuilderAU We also have same requirement. Did you find the solution?
