### ISSUE TITLE
System Message only visible to a specific user

### ISSUE THREAD

**Issue by LG1710** [FaridSafi/react-native-gifted-chat#1141]
#### Issue Description

I would like to know if this is possible to display System Message only for a particular user.
How can you do this ?...

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

A warning message for example concerning only a particular user.

#### Additional Information

* Nodejs version: 10.13.0
* React version: 16.6.0-alpha.8af6728
* React Native version: 0.57.4
* react-native-gifted-chat version: 0.7.2
* Platform(s) (iOS, Android, or both?): both

**Comment by carloscurcino** [comment]
Did you solved this?
