### ISSUE TITLE
gifted chat cant render large number of messages (There are blanks)

### ISSUE THREAD

**Issue by xcxooxl** [FaridSafi/react-native-gifted-chat#1146]
#### Issue Description

When there are a lot of messages, Gifted chat renders blanks.

#### Steps to Reproduce / Code Snippets

Just create an array of message of large size 1k-10k and start scrolling you will start noticing blanks, many unrendered messages, That won't even render in the future.

#### Expected Results
Should always be able to see chat messages.

#### Additional Information

* Nodejs version: 10.15
* React version: 16.6.3
* React Native version: 0.57.8
* react-native-gifted-chat version: 0.7.2
* Platform(s) (iOS, Android, or both?): Tested only android atm.

I believe the problem is just with how FlatList/SectionList works. Seems better solutions are to have a custom recycling list, Will this be a feature in this project? I'm searching everywhere for a good implementation for chat.

**Comment by muhammadwfa** [comment]
Same issue here.
This is really important.
There is a package under name of react-native-largelist
if it would be better thatn flatlist will be better to add it instead of flatlist

**Comment by mayconmesquita** [comment]
The best choice would be implement the chat with https://github.com/Flipkart/recyclerlistview
