### ISSUE TITLE
cant able to view send icon for large text when i want to edit in the middle

### ISSUE THREAD

**Issue by saikiranoptisol** [FaridSafi/react-native-gifted-chat#1147]
![screenshot](https://user-images.githubusercontent.com/40380599/53159652-494f5280-35ec-11e9-96cf-fcd82b568193.jpg)
   In screenshot as you can see i cant able to view the send icon for input toolbar if i type long message and i want to edit in the middle.

i.e: if i entered big text the send button will be shown. now in that big text if i click on somewhere in the text the input toolbar some portion of input toolbar is hiding beyond keyboard and i cant able to see send option.
How to fix this any workaround?

this happens only with android. I have already set MAX_COMPOSER_HEIGHT because of that it works fine in ios but not in android

**Comment by Blue0X** [comment]
I have the same issue.

**Comment by saikiranoptisol** [comment]
use keyboardSpacer component : Ex: <GiftedChat
                        composerHeight={COMPOSER_HEIGHT}
                        minInputToolbarHeight={COMPOSER_HEIGHT}
                        messages={this.state.messages}
                        onSend={messages => this.onSend(messages)}
                        onInputTextChanged={text => container.setState({isReportModalVisible: false})}
                        //textInputProps = {{onFocus: ()=> container.setState({isReportModalVisible:false})}}
                        user={{_id: this.state.senderUserName}}
                        loadEarlier={this.state.loadEarlier}
                        placeholder="Type Your Message"
                        isLoadingEarlier={this.state.isLoadingEarlier}
                        onLoadEarlier={this.onLoadEarlier}
                        renderSend={this.renderSend}
                        alwaysShowSend={true}
                        renderActions={this.imageSend.bind(this)}
                        renderInputToolbar={this.renderInputToolbar}
                        //renderComposer={this.renderComposer}
                        renderBubble={this.renderBubble.bind(this)}
                        renderMessageImage={this.renderMessageImage.bind(this)}
                        renderAvatar={null}
                        inverted={true}
                        listViewProps={
                            {
                                onEndReached: this.onEndReached,
                                onEndReachedThreshold: 100
                            }
                        }
                        parsePatterns={linkStyle => [
                            {
                                pattern: /#(\w+)/,
                                style: {...linkStyle, color: 'lightgreen'},
                                onPress: props => alert(`press on ${props}`),
                            },
                        ]}
                    />
                    {Platform.OS === 'android' ? <KeyboardSpacer topSpacing={-1000}/> : null}

**Comment by fukemy** [comment]
very long text make app too. slow, how did u solved this?
