### ISSUE TITLE
current and next within shouldComponentUpdate inside Message class always return the same value.

### ISSUE THREAD

**Issue by muhammadwfa** [FaridSafi/react-native-gifted-chat#1148]
**Bubble messages**

`next.text` and `current.text` always return the same message.
for example: 
      `next.text === current.text `=> always return true
      `next.image === current.image` => always return true

Code: I tested it with console.log

```
  shouldComponentUpdate(nextProps) {
    const next = nextProps.currentMessage;
    const current = this.props.currentMessage;

> console.log('current message: ' + current.text + ", next message: " + next.text);

    const { nextMessage } = this.props;
    const nextPropsMessage = nextProps.nextMessage;
    return (
      next.sent !== current.sent ||
      next.received !== current.received ||
      next.pending !== current.pending ||
      next.createdAt !== current.createdAt ||
      next.text !== current.text ||
      next.image !== current.image ||
      next.video !== current.video ||
      next.audio !== current.audio ||
      nextMessage !== nextPropsMessage
    );
  }
```

**Expected Results**

it must not return the same.

#### Additional Information

* React version: 16.6.3
* React Native version: 0.57.8
* react-native-gifted-chat version: 0.7.2
* Platform(s) (iOS, Android, or both?): android

**Comment by muhammadwfa** [comment]
@xcarpentier, could you please have a look at this
thank you before

**Comment by raaannzzz** [comment]
hey @muhammadwfa , have you resolved this issue?

**Comment by fukemy** [comment]
Hi, I am facing same issues, any solution now?
