### ISSUE TITLE
Npm package not updated

### ISSUE THREAD

**Issue by swlaunch** [FaridSafi/react-native-gifted-chat#1149]
#### Issue Description

I can see new prop `alignTop` added on readme but not published on NPM yet

#### Steps to Reproduce / Code Snippets

I am installing the package using Yarn and it still installs the version that was published one month ago

#### Expected Results

New version with `alignTop` prop to be installed

#### Additional Information

* Nodejs version: [10.15.0]
* React version: [16.5.0]
* React Native version: [https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz]
* react-native-gifted-chat version: [0.7.2]
* Platform(s) (iOS, Android, or both?): [BOTH]

**Comment by pavelbabenko** [comment]
Same issue

**Comment by azzadrood** [comment]
Same issue here

**Comment by muhammadwfa** [comment]
same issue here.
and I suggest to replace react-native-lightbox with `react-native-image-view`
Because react-native-lightbox is not active
react-native-image-view is update and have image slidshow capability
