### ISSUE TITLE
Cannot read property 'Constants' of undefined

### ISSUE THREAD

**Issue by lacajanegra** [FaridSafi/react-native-gifted-chat#1150]
#### Issue Description

When sent a video message i receive this error:
![whatsapp image 2019-02-26 at 12 39 01](https://user-images.githubusercontent.com/5133232/53426440-bcc6da80-39c5-11e9-8b6b-2352a93579d7.jpeg)

#### Steps to Reproduce / Code Snippets

 ```  this.setState(() => {
      return {
        messages: [
          {
            _id: 1,
            text: "My message",
            createdAt: new Date(Date.UTC(2016, 5, 11, 17, 20, 0)),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://facebook.github.io/react/img/logo_og.png"
            },
            video:
              "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
          }
        ]
      };


#### Additional Information

* Nodejs version: v10.15.0 
* React version: 16.3.1
* React Native version: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz
* react-native-gifted-chat version: 0.7.2
* Platform(s) (iOS, Android, or both?): iOS

**Comment by joelpiccoli** [comment]
I'm facing the same issue with RN 0.58.0... anyone that could help?

**Comment by joelpiccoli** [comment]
passing some messageVideoProps through Bubble component did the trick for me!

```
renderBubble(bubbleProps) {
    return (
      <Bubble
        {...bubbleProps}
        wrapperStyle={styles.wrapper}
        textStyle={styles.text}
        messageVideoProps={{}}
      />
    );
  }
```

**Comment by diamont1001** [comment]
same issue with RN 0.59.5

**Comment by HikaruKun** [comment]
> same issue with RN 0.59.5

Are there any workarounds ? How to fix it ? Anybody solves it ?

**Comment by dekameron22** [comment]
+1

**Comment by mjmaix** [comment]
@bot don't close

**Comment by Jojr** [comment]
Same issue here with RN 0.60.4.
No solution yet?

**Comment by EdisonDevadoss** [comment]
Same issue here with RN 0.59.9.
No solution yet?

**Comment by geceba** [comment]
Following with documentation of react native video, you should use pod install and add 
`pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'` in Podfile and android you can check the manual installation
