### ISSUE TITLE
extraData isn't working

### ISSUE THREAD

**Issue by venkatmithunk** [FaridSafi/react-native-gifted-chat#1160]
#### Issue Description
RenderMessage function isn't running when data in extraData changes.

#### Steps to Reproduce / Code Snippets

```
       <GiftedChat
          messages={this.props.messages}
          renderAvatar={null}
          onSend={this.onSend}
          user={{
            _id: this.props.user._id, 
          }}
          extraData={this.state.selectedMessages}
          renderSend={this.renderSend}
          renderActions={this.renderCustomActions}
          keyboardShouldPersistTaps="never"
          renderMessage={this.renderMessage}
          renderChatFooter={this.renderChatFooter}
          renderInputToolbar={this.renderInputToolbar}
          renderComposer={this.renderComposer}
        />
```

#### Expected Results

I want renderMessage function to run when selectedMessages in state updates.

#### Additional Information

* Nodejs version: 10.0.0
* React version: 16.6.3
* React Native version: 0.58.5
* react-native-gifted-chat version: 0.7.2
* Platform(s) (iOS, Android, or both?): Android

**Comment by dekameron22** [comment]
+1

**Comment by anchetaWern** [comment]
any ideas how to get this to work?
in my case, I actually had to pass an object containing the state data that should trigger the update:

```
extraData={{ pressed_message_id, viewed_by_users }}
```

But it didn't.

**Comment by rarira** [comment]
shouldUpdateMessage prop is the way to go..
it is just like react shouldComponentUpdate lifecycle method

```
shouldUpdateMessage = {(props, nextProps) => {
     return props.extraData.someData !== nextProps.extraData.someData
}}
```

**Comment by antoinefotso** [comment]
My list only re render went I pressed the first  or last message, other messages have no effect.
Pls help

**Comment by diegmarcello** [comment]
> shouldUpdateMessage prop is the way to go.. it is just like react shouldComponentUpdate lifecycle method
> 
> ```
> shouldUpdateMessage = {(props, nextProps) => {
>      return props.extraData.someData !== nextProps.extraData.someData
> }}
> ```

This worked for me (v0.16.3) 

`<GiftedChat
...
extraData={{loadingMessages}}
shouldUpdateMessage={(props, nextProps) => props.extraData.loadingMessages !== nextProps.extraData.loadingMessages}
/>`

**Comment by fukemy** [comment]
> shouldUpdateMessage = {(props, nextProps) => {
>      return props.extraData.someData !== nextProps.extraData.someData

no, shouldUpdateMessage called from shouldComponentUpdate in Message class, where currentProps text and nextProps Text were the same

**Comment by fukemy** [comment]
https://github.com/FaridSafi/react-native-gifted-chat/issues/1148
