### ISSUE TITLE
Prepend error

### ISSUE THREAD

**Issue by Huzaifaak** [FaridSafi/react-native-gifted-chat#1162]
#### Issue Description

HI Everyone, I am trying to add pagination. I am getting date above every message that i prepend. 

#### Steps to Reproduce / Code Snippets
Prepending message's should unshift message's to the array

#### Expected Results

![Screenshot_1552305589](https://user-images.githubusercontent.com/9552894/54122845-ff55d180-441f-11e9-8df7-85edebb10687.png)

#### Additional Information

* Nodejs version: 6.4.1
* React version: 16.6.0-alpha.8af6728
* React Native version: 0.57.4
* react-native-gifted-chat version: ^0.7.2
* Platform(s) (iOS, Android, or both?): both

**Comment by drachyovmaxim** [comment]
any update on this? same here.
![image](https://user-images.githubusercontent.com/3596230/57871521-8f4a3a00-781a-11e9-8e96-866d84e31041.png)
