### ISSUE TITLE
How to add an image with composer actions?

### ISSUE THREAD

**Issue by NicWickman** [FaridSafi/react-native-gifted-chat#1166]
I don't understand from reading through the example app how an image is actually getting added to the image.

A basic explanation of how messages are composed and how to access the message object before sending it, would be hugely appreciated.

I am using firebase and would like to select an image with react-native-image-picker. No problem: 

-I create a custom action which opens react-native-image-picker
-I select an image, upload it to firestore and get back the URI... 
...and then...now what? I simply don't understand where I am supposed to return this URI to add it to the contents of the message.

In fact, I don't understand how the "message" object is being composed at all, even when using only text.

**Comment by HarshitMadhav** [comment]
@NicWickman Hi did you managed to get a solution for this?

**Comment by mu-tayyab** [comment]
me to ....please give some solution?
