### ISSUE TITLE
Keyboard issues when have others components on screen

### ISSUE THREAD

**Issue by ramos-lucas** [FaridSafi/react-native-gifted-chat#1168]
#### Issue Description

I have a screen with some components besides chat (Header, Player, ChatTab and Chat).

In android works normally, but on iOS I only got one of the following results:
When pressing the textInput, the keyboard appears normally but when typing the textInput moves up.
When pressing the textInput, the keyboard appears over the textInput but when typing it appears normally.

I want it to have the default behavior of always staying in the footer.

I have already tried using the KeyboardAvoidingView and KeyboardSpacer but none solved my problem.

#### Steps to Reproduce / Code Snippets

Add some components to the Chat screen
<div style="display: inline">
<img src="https://user-images.githubusercontent.com/18932708/54652279-1c7c4700-4a95-11e9-9017-6219ab2fc96e.png" width="300">
<img src="https://user-images.githubusercontent.com/18932708/54652283-20a86480-4a95-11e9-8434-30d15f3d2c67.png" width="300">
</div>

```javascript
return (
      <View style={{ flex: 1 }}>
        <View style={{ height: 50, backgroundColor: 'yellow' }} />
        <View style={{ flex: 1, backgroundColor: 'red' }} />
        <View style={{ height: 50, backgroundColor: 'blue' }} />
        <GiftedChat />
        <KeyboardAvoidingView behavior="padding" />
      </View>
    )
```

#### Expected Results

The same behavior of Android.
<div style="display: inline">
<img src="https://user-images.githubusercontent.com/18932708/54652603-31a5a580-4a96-11e9-9f52-892784af8743.png" width="300">
<img src="https://user-images.githubusercontent.com/18932708/54652609-3407ff80-4a96-11e9-985a-a2163559770d.png" width="300">
</div>

#### Additional Information

I can't update react-native-gifted-chat because it conflicts with video library. 

* Nodejs version: 11.8.0
* React version: 16.6.1
* React Native version: 0.57.6
* react-native-gifted-chat version: ^0.5.0
* Platform(s) (iOS, Android, or both?): iOS

**Comment by Mhany95** [comment]
I have had the same problem on iOS.
I have a tab bar from react navigation library at the bottom of the screen, but I came up with a workaround for iOS:
Using 'react-native-device-info' to get if the device has a notch
```
handleBottomOffset = () => {
  if (Platform.OS === 'ios') {
     const tabHeight = Header.HEIGHT; //HEADER is imported from react-navigation

     if (DeviceInfo.hasNotch()) 
        return tabHeight + 20; // "20" is the value of the height of the pill in iphone x, iphone xs .. etc.

      return 50; // "50" was the value that worked on iphone devices REGARDLESS of the actual value of the tabHeight. this was tested on all sizings including SE.
  }
  return 0; 
};

<GiftedChat 
   bottomOffset={this.handleBottomOffset()}
/>
```
