### ISSUE TITLE
Scroll To Bottom

### ISSUE THREAD

**Issue by devmalvinder** [FaridSafi/react-native-gifted-chat#1169]
#### Issue Description

On appending new messages to the Gifted Chat it only scrolls one message.
I mean lets say I am scrolling the list to top and viewing old messages, meanwhile I receive a new message from the user. in that case it does not scrolls to the new message, instead, it only scrolls down one message.

* Nodejs version: 10
* React version: 16.3.1
* React Native version: 0.55.4
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): both

**Comment by devmalvinder** [comment]
Any update on this ticket from the team ? Or somebody can help resolve this issue from the community ?

**Comment by superphil0** [comment]
same error in 0.9.0-beta.6
