### ISSUE TITLE
Multiline Support + Initials for avatars support (PR + VIDEO)

### ISSUE THREAD

**Issue by faceyspacey** [FaridSafi/react-native-gifted-chat#117]
I'm sure everyone loving this package has been interested in getting it to mimic the iOS text message app completely. Well, here's one more step in that direction. With this PR the textinput grows with each line when you press *Return*. But more importantly though, the placement of the ListView goes where it's supposed to be. For example, if you only have a few messages, but it starts to move up with a keyboard and tall textinput visible, when you blur it will re-attach to the top. But if there are more messages than there is height available, the bottom messages will attach to the bottom. It's all animated and nice. I've only tested on iOS. Here's a video:

https://www.youtube.com/watch?v=iUmIHIXGj88&feature=youtu.be

Also, there's support for initials as the avatar. It will try to figure out the initials based on the `name` key of `rowData`. See my changes in the Readme for how to use it.

https://github.com/FaridSafi/react-native-gifted-messenger/pull/116

**Comment by faceyspacey** [comment]
Also note: it shines best with `keyboardShouldPersistTaps={false}`. Rather than having to swipe around to hide the keyboard. With this prop you can see the re-positioning of the ListView best.

**Comment by FaridSafi** [comment]
multiline and avatar are supported in react-native-gifted-chat

**Comment by faceyspacey** [comment]
awesome!
