### ISSUE TITLE
Tried to register two views with the same name RCTVideo

### ISSUE THREAD

**Issue by tmjordan** [FaridSafi/react-native-gifted-chat#1170]
#### Issue Description

First of all, thanks for that lib, it really makes me save a lot of time.
When installing the last version of RNGiftedChat (0.7.2), an error is thrown at the application launch. It seems related to the message video bubble component of the library.
I'm also using react-native-video in my project, maybe it is related??
The last version of RN Gifted Chat which works with my project is 0.5.0
But i want to use the last version of the lib.

#### Steps to Reproduce / Code Snippets

Install the last version of RN Gifted Chat, currently 0.7.2

#### Expected Results

Use RN Gifted Chat in my project

#### Additional Information

* Nodejs version: 10.13.0
* React version: 16.6.3
* React Native version: 0.57.8
* react-native-gifted-chat version: 0.7.2
* Platform(s) (iOS, Android, or both?): Both

![IMG_2820](https://user-images.githubusercontent.com/27443995/54917394-04288400-4efc-11e9-8e78-a988ca65b40b.PNG)

**Comment by loga4** [comment]
the same

**Comment by juanjsebgarcia** [comment]
Fix is here: 
```https://github.com/react-native-community/react-native-video/issues/1450```

I think Gifted chat is at fault here, the package should avoid installing a second copy of RNVideo. However I'm not knowledgeable enough to provide a fix.

```rm -r node_modules/react-native-gifted-chat/react-native-video/```
This will get it working for now.

**Comment by tmjordan** [comment]
Yes, we should move react-native-video from dependencies to peer-dependencies.
I made a fork of the package, and that's what i did for me and it's working very well.

**Comment by fidelsam1992** [comment]
The correct command is : 
`rm -r node_modules/react-native-gifted-chat/node_modules/react-native-video/`
