### ISSUE TITLE
Event if "sendButton" toggles (alwaysShowSend)

### ISSUE THREAD

**Issue by xstable** [FaridSafi/react-native-gifted-chat#1174]
- you have alwaysShowSend={true}
- begin to type something into the textfield
- the `send` button appears

Is there a way to catch this event... if the send-button appears? 
I need to deactivate other Buttons if the sendButton is activted

**Comment by pierroo** [comment]
> * you have alwaysShowSend={true}
> * begin to type something into the textfield
> * the `send` button appears
> 
> Is there a way to catch this event... if the send-button appears?
> I need to deactivate other Buttons if the sendButton is activted

Hello @xstable,

Were you able to find a solution to this?

I'm trying to do the same.

(hiding accessory bar when inputing text; but I don't want to handle the text state myself for performance reason)

I would appreciate your feedback! :)

**Comment by xstable** [comment]
@pierroo 
Sorry, no solution for this. I've managed it this way, that I've created an small overlay which pop up from the Muttom and cover the Input-Toolbar.

**Comment by pierroo** [comment]
> @pierroo
> Sorry, no solution for this. I've managed it this way, that I've created an small overlay which pop up from the Muttom and cover the Input-Toolbar.

Thank you for answering.

Actually I found a temporary solution as well, slightly different:

I listen for keyboard event, when it show, my renderAccessoryBar function returns null.
When it's closed, I return it back.

It might be easier to handle than the small overlay popup you added, you might want to give it a try. :)

**Comment by xstable** [comment]
@pierroo good Idea :+1:
