### ISSUE TITLE
How to change message view style for tick like color after sending the message sent?

### ISSUE THREAD

**Issue by kamleshsindhal08** [FaridSafi/react-native-gifted-chat#1178]
#### Issue Description

How to change message view style for tick symbol like the color after sending the message sent.

I am using this functionality when a remote user views our message, so how to make change the color of tick symbol like what ups App.

#### Expected Results

![Screenshot_20190328_122740](https://user-images.githubusercontent.com/14357332/55136799-5adcca80-5155-11e9-8d6a-a438a4aa4505.png)

#### Additional Information

* React Native version: 0.58.6
* react-native-gifted-chat version: ^0.7.2
* Platform(s) (iOS, Android, or both?): Both

**Comment by evertonco** [comment]
You must use tickStyle prop

**Comment by Ahmed067Abdullah** [comment]
You can simple use ternary operator in tickStyle prop on Bubble component
` function renderBubble(props) {
    return <Bubble
      {...props}
      tickStyle={{ color: props.currentMessage.seen ? '#34B7F1' : '#999' }}
    />
  }` 
  
  Don't forget to add renderBubble props on GiftedChat component
  
  `<GiftedChat
      ...
      renderBubble={renderBubble}
    />`
