### ISSUE TITLE
Message input hidden behind keyboard on Android

### ISSUE THREAD

**Issue by anthonycmain** [FaridSafi/react-native-gifted-chat#1179]
#### Issue Description

The message input is hidden behind the keyboard making it impossible to use. 

See video: 
https://photos.google.com/share/AF1QipM99g0V76kH6vFN3ARObaM6OcFTRfUo1bxSKZ8IpGZuEr3VluzwnKEA4G5q53o2MQ/photo/AF1QipONnL_D6HT1-3N8l9SfbZ8Mocp3TDHppRkVIPyN?key=cF9RVWJDcjVXc3pyR1RKRDl4bVlJR1huZjdaOHZ3

This may be an Expo issue only

#### Steps to Reproduce / Code Snippets

Open the Expo demo using a device running Android P (others may also be effected)

Seen on a Huawei Mate 10 Pro running EMUI 9

#### Expected Results

Message field should be shown above the keyboard

#### Additional Information

* Platform(s) (iOS, Android, or both?): Android

**Comment by Kreztastic40** [comment]
This is not an expo issue only.  I just tested with my app in Google Play which is in internal test and the issue exists there as well.

**Comment by agarant** [comment]
I confirm that the issue is happening on RN 0.59.2. It works fine on IOS. I tried all the solutions proposed in the Readme but nothing worked. Also, the bottomOffset has no effect on the size of the chat.

**Comment by anthonycmain** [comment]
Looks like this has been addressed, its just not present in their Expo demo

https://github.com/FaridSafi/react-native-gifted-chat/issues/680#issuecomment-359699364
