### ISSUE TITLE
CustomView implementation for rendering HTML content

### ISSUE THREAD

**Issue by abhishek10ju** [FaridSafi/react-native-gifted-chat#1180]
#### Issue Description

really liked gifted chat for implementing chatbot quickly. Implemented CustomView to render HTML contents in message bubbles. I am new at react-native and tried to implement WebView for this purpose.

Using WebView as Custom View for HTML type of messages does not show the messages in proper chat bubble and subsequent messages are not even visible

#### Steps to Reproduce / Code Snippets

export default class CustomView extends React.Component {

  renderHtml() {
    return (
        <WebView
        source={{html: this.props.currentMessage.text}}
        style={{flex: 1}} 
        />
    );
  }

  render() {
    if (this.props.currentMessage.contentType == 'html') {
      return this.renderHtml();
    }
    return null;
  }
}

#### Expected Results

HTML content sent as messages should be displayed properly

#### Additional Information

* Nodejs version: 10.15.1
* React version: 16.6.3
* React Native version: 0.58.3
* react-native-gifted-chat version: 0.7.2
* Platform(s) (iOS, Android, or both?): Android

**Comment by rakesh-eltropy** [comment]
@abhishek10ju  We also have same requirement. Did you find the solution?

**Comment by rahulgit** [comment]
I am also having same issue with webview , web view not properly rendering inside chat bubble. If webvew contain any select drop down and once it clicked chat bubble quickly renders renders proper design

**Comment by ucallQA** [comment]
is this problem fixed or any updates? I need webview with gifted chat and was unsure if there is any proper support. Thanks
