### ISSUE TITLE
Gifted chat component loads/renders slower then the data received from back end.

### ISSUE THREAD

**Issue by ToshalGhimire** [FaridSafi/react-native-gifted-chat#1181]
#### Issue Description
So I get my messages data from firebase, but the gifted chat component loads these a lot slower then it should. It ruins the user experience and is an existing issue with this component that has no clear solution. If anyone knows how to fix this comment it ASAP. 

The gif below shows the issue. The JSON data on top is loaded from a firebase back end, and the gifted chat is rendered much later then it should be. 
![Alt Text](https://media.giphy.com/media/1dIXawqvmpA2teAv25/giphy.gif)

Existing issues #606 #228 #473 and #928 

#### Steps to Reproduce / Code Snippets

Load data and set messages state to it on componentwillmount() and try to render gifted chat with that messages state

#### Expected Results

The gifted chat UI should load right when the data becomes available, not 5 seconds later

#### Additional Information

* Nodejs version: v10.15.0
* React version: ^16.5.0
* React Native version: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
* react-native-gifted-chat version: ^0.7.2
* Platform(s) (iOS, Android, or both?): Both using expo

**Comment by NicWickman** [comment]
I am also wondering this... It is a major usability issue. Bouncing between chats feels awful.

**Comment by evertonco** [comment]
It looks like gifted-chat needs a preparation task before render. You must use a loader component to improve your user experience. From the docs:

`renderLoading (Function) - Render a loading view when initializing`

**Comment by hubermat** [comment]
See also #769

**Comment by Rk5422686** [comment]
https://github.com/FaridSafi/react-native-gifted-chat/issues/2149#issuecomment-1310858808

Answer on this thread helped me fixed the slow rendering.
