### ISSUE TITLE
Problem with isLoadingEarlier in LoadEarlier 

### ISSUE THREAD

**Issue by brunoosilva** [FaridSafi/react-native-gifted-chat#1182]
#### Issue Description

I used the example and the don't work, look the video below:

https://github.com/FaridSafi/react-native-gifted-chat/tree/master/example

#### Steps to Reproduce / Code Snippets

![ScreenRecording_033020190735](https://user-images.githubusercontent.com/3465257/55275073-58967f80-52bf-11e9-8f3a-acbccc4c8075.gif)

#### Expected Results

Show loading

#### Additional Information

* Nodejs version: v8.11.3
* React version: 16.0.0-alpha.12
* React Native version: 0.46.3
* react-native-gifted-chat version: 0.7.2
* Platform(s) (iOS, Android, or both?): both

**Comment by kuisis** [comment]
Same issue here. I'm passing `true` to `isLoadingEarlier`, while waiting for response from backend, and then pass `false`, when i get the response. But ActivityIndicator isn't showing

**Comment by Hirbod** [comment]
Same issue here. If I set "isLoadingEarlier" initially to true, I actually see the ActivityIndicator but it won't show up when I change the state

**Comment by AbhiShrek** [comment]
+1

**Comment by lakst** [comment]
Any updates on this?

**Comment by khuyendev** [comment]
+1, please fix it

**Comment by mahavirvataliya** [comment]
+1

**Comment by mahavirvataliya** [comment]
when we change **isLoadingEarlier** in a state we also have to change the message too like

`this.setState(previousState => ({
        messages: GiftedChat.prepend(previousState.messages, []),
        isLoadingEarlier: true,
      }));`

**Comment by mahavirvataliya** [comment]
or add this property to Component
See There is prop in GiftedChat that also can solve this.
`
isLoadingEarlier={this.state.isLoadingEarlier}
onLoadEarlier={() => this.getMoreMessages()}
extraData={this.state}
`

**Comment by AleksandarSavic95** [comment]
> or add this property to Component
> See There is prop in GiftedChat that also can solve this.
> `isLoadingEarlier={this.state.isLoadingEarlier} onLoadEarlier={() => this.getMoreMessages()} extraData={this.state}`

This is not working.. People already wrote that it doesn't work like this, and You didn't provide any workaround.

**Comment by AleksandarSavic95** [comment]
Also, don't forget to set `loadEarlier={true}`, because the `ActivityIndicator` (i.e. the loader) appears only if button for loading earlier messages is visible. 😄
