### ISSUE TITLE
Suggestion: use dayjs

### ISSUE THREAD

**Issue by RWOverdijk** [FaridSafi/react-native-gifted-chat#1197]
Currently this module uses momentjs. Nothing wrong with that, but it's a rather large library that I'd like to exclude from my builds.

Dayjs is an excellent alternative that I've been used in four projects so far, and it just works. Also it's a lot smaller than moment.

Perhaps moment can be made a peerDependency that's used when installed?

It's not the biggest issue on the planet, I realize that. 😄

**Comment by RWOverdijk** [comment]
Made my own chat. With blackjack, and gestures.

**Comment by tmjordan** [comment]
hi @RWOverdijk do you have a repo for your chat?
