### ISSUE TITLE
use id instead of _id

### ISSUE THREAD

**Issue by ElegantSoft** [FaridSafi/react-native-gifted-chat#1199]
#### Issue Description
I use mysql database and messages get with id

**Comment by cmmartin** [comment]
Agree with this one. `_id` is not a common convention

**Comment by evertonco** [comment]
You must use _id. It's not difficult use a map method to converting 'id' to '_id', also.

**Comment by 3luyka** [comment]
Maybe @FaridSafi should provide prop something like `messageIdKey` with default value to `_id`?

**Comment by FunkSoulNinja** [comment]
The best solution is to just fork this repo and then simply implement something like messageIdKey (as stated by @3luyka). It would take only a few minutes. That's the beauty of open-source. You could even submit a pull request.

**Comment by aguscha333** [comment]
Or you can do what I did and use [patch-package](https://www.npmjs.com/package/patch-package) so you don't need to fork the package and be messing around with the builds and republishing.
