### ISSUE TITLE
position of "CustomView" component

### ISSUE THREAD

**Issue by 3luyka** [FaridSafi/react-native-gifted-chat#1201]
#### Issue Description

I want to render `CustomView` below the text message. Could you please provide prop for that so I can choose position for `CustomView`?

#### Additional Information

* Nodejs version: 11.7
* React version: 16.8.3
* React Native version: 0.59.5
* react-native-gifted-chat version: 0.7.3
* Platform(s) (iOS, Android, or both?): both

**Comment by evertonco** [comment]
renderCustomView allows you render whatever you want. So you can do something like: 
```
renderCustomView = ({ currentMessage, ...otherProps }) => {
  return (
    <View>
      <Text>{currentMessage.text}</Text>
      <YourCustomContentComponent />
    </View>
  )
}
```
