### ISSUE TITLE
Gap between Keyboard & text input component when using createBottomTabNavigator

### ISSUE THREAD

**Issue by AbhiShrek** [FaridSafi/react-native-gifted-chat#1202]
#### Issue Description

I used createBottomTabNavigator from react-navigation to create a bottom tab bar.
One of the tabs is messages tab, where I added the example chat code (given in readme)
When running this ios simulator, as soon as the keyboard shows up, there is a big gap between the keyboard and the text input component.

When no keyboard, its fine :
<img width="292" alt="Screenshot 2019-04-24 at 6 34 26 AM" src="https://user-images.githubusercontent.com/11253347/56625478-288e9200-665b-11e9-9b58-a3a83c1e3e4d.png">

When click inside the text input box, and keyboard shows up :
<img width="295" alt="Screenshot 2019-04-24 at 6 35 03 AM" src="https://user-images.githubusercontent.com/11253347/56625511-49ef7e00-665b-11e9-9e18-5b188e31f70a.png">

#### Steps to Reproduce / Code Snippets

Run the example code given in readme in a tab within createBottomTabNavigator from react-navigation, on ios simulator.
 
#### Expected Results

No gap between keyboard and text input box

#### Additional Information
* Nodejs version: 10.6.2
* React version: 16.5.2
* React Native version: 0.56.0
* react-native-gifted-chat version: 0.7.3
* Platform(s) (iOS, Android, or both?): ios
* react-navigation: 2.12.1

#### props
```
render() {
    return (
      <GiftedChat
        messages={this.state.messages}
        onSend={messages => this.onSend(messages)}
        alwaysShowSend={true}
        user={{
          _id: 1
        }}
      />
    );
  }

```

**Comment by prozwang** [comment]
+1

**Comment by untilla** [comment]
If you look to source code, you will see what only two constants are used to set up tab bar height:
const DEFAULT_HEIGHT = 49;
const COMPACT_HEIGHT = 29;

And if you put this value to bottomOffset parameter of GiftedChat - problem will be solved.

![image](https://user-images.githubusercontent.com/33196481/57175891-ee42a300-6e59-11e9-8762-ddf48d2dab15.png)


![image](https://user-images.githubusercontent.com/33196481/57175867-7bd1c300-6e59-11e9-9d61-0182bff54e06.png)

**Comment by ethanyuwang** [comment]
@untilla its working for ios but not for android. there's still a gap when keyboard is up. how should i fix this?
