### ISSUE TITLE
Empty Chat Message sending

### ISSUE THREAD

**Issue by AbhiShrek** [FaridSafi/react-native-gifted-chat#1205]
#### Issue Description

When the prop `alwaysShowSend={true}`
Without any text message, if click **Send** , it will send an empty message.
This is not appropriate. Empty messages should not be sent.

<img width="297" alt="Screenshot 2019-04-26 at 8 56 23 AM" src="https://user-images.githubusercontent.com/11253347/56781743-ccb23d80-6801-11e9-97b9-5e56597a91a3.png">

#### Steps to Reproduce / Code Snippets

Set the prop `alwaysShowSend={true}` and click Send button from UI.
It will send empty message.

#### Expected Results

Empty message should be be sent.

#### Additional Information

* Nodejs version: 10.6.2
* React version: 16.5.2
* React Native version: 0.56.0
* react-native-gifted-chat version: 0.7.3
* Platform(s) (iOS, Android, or both?): checked on iOs only.

**Comment by adilosa** [comment]
Since messages may be extended with custom fields, e.g. image messages, the definition of "empty" would also need to be customizable. Perhaps an additional prop could be added that accepts a function which defines how to filter messages. 

However, this can already be accomplished by implementing `onSend`. 


```typescript
onSend = (messages: IMessage[]) => 
    messages.filter(msg => msg.text !== "").forEach(msg => sendMyMessage(msg));
```

**Comment by evertonco** [comment]
> #### Issue Description
> When the prop `alwaysShowSend={true}`
> Without any text message, if click **Send** , it will send an empty message.
> This is not appropriate. Empty messages should not be sent.
> 
> <img alt="Screenshot 2019-04-26 at 8 56 23 AM" width="297" src="https://user-images.githubusercontent.com/11253347/56781743-ccb23d80-6801-11e9-97b9-5e56597a91a3.png">
> 
> #### Steps to Reproduce / Code Snippets
> Set the prop `alwaysShowSend={true}` and click Send button from UI.
> It will send empty message.
> 
> #### Expected Results
> Empty message should be be sent.
> 
> #### Additional Information
> * Nodejs version: 10.6.2
> * React version: 16.5.2
> * React Native version: 0.56.0
> * react-native-gifted-chat version: 0.7.3
> * Platform(s) (iOS, Android, or both?): checked on iOs only.

@AbhiShrek This must be your responsability. You forced to always show send button. It means you know what you doing.

**Comment by avegrv** [comment]
As a solution, you can pass your own `Send` component. And rewrite `onPress` method inside `Send`.

```
onPress={() => {
  if (text && onSend) {
    onSend({ text: text.trim() }, true)
  }
}}
```

**Comment by bidetaggle** [comment]
I'm on the opposite situation: I'd like `onSend` to be triggered even if the text input is empty (to send an attached image), I set `alwaysShowSend` prop to true and literally always show the send button, not trigger it. If someone has a simple way to do it I'd be glad to know it

**Comment by Marcados** [comment]
@bidetaggle same situation here. Did you find something ?

**Comment by bidetaggle** [comment]
@Marcados unfortunately I gave up on this and I hope this default behavior will fit in my project. I'm still highly interested by a solution because I plan to go in dirty hacks if it's required to make it works as I wished at first.

**Comment by Marcados** [comment]
@bidetaggle the hack I used is filling textInput with ' ', but yeah, I assume that is dirty. Thank you for your answer though.

**Comment by bidetaggle** [comment]
That's what I'm talking about, and trim the message if not empty to remove the front blank space.

**Comment by olarra** [comment]
My solution was to use a custom send component and manually trigger the on-send method. after that i had to add a text and onInputTextChanged props in order to reset text input https://github.com/FaridSafi/react-native-gifted-chat#notes-for-redux.

` <Send {...props} >
          <IconButton
            icon="send-circle"
            onPress={async () => {
              if (text && handleSend) {
                setInputText("");
                await handleSend([{ text: props.text.trim() }]);
              }
       }}
            style={{ margin: 0, padding: 0, height: 46 }}
          />
        </Send>`

**Comment by allanRoberto** [comment]
@cromatikap The solution I found was similar to the one mentioned above, but I manipulated the "text" value directly in the "<Send />" component through the "text" property:

```
const [files, setFiles] = useState();
...
const renderSend = (props) => {
   return (
      <Send
         {...props}
         text={files.length > 0 ? " " : props.text} // check files.length
         containerStyle={{
              justifyContent: "center",
         }}
        >
            <Ionicons name="send" color={Colors.primary} size={28} />
        </Send>
    )
}

...

       <GiftedChat
          ...
          renderSend={renderSend}
        />
```
