### ISSUE TITLE
Remove the dependency on react-native-video

### ISSUE THREAD

**Issue by cmmartin** [FaridSafi/react-native-gifted-chat#1207]
Video playback seems out of the scope of this project and creates a lot of headaches.

- If you are already using `react-native-video` in your project, adding this library will break it
- This library uses an outdated version of `react-native-video` so even if you jump through the hoops of using the version in this library, instead of the one you installed yourself, you now must use an old version

This would resolve a number of open issues. Most notably...

https://github.com/FaridSafi/react-native-gifted-chat/issues/1093
https://github.com/FaridSafi/react-native-gifted-chat/issues/1172

**Comment by Tochukwuibe** [comment]
Yes please, I cannot use react-native-video as well as gifted chat in the same project. I might end up having to remove gifted chat if this issue is not resolved.

**Comment by CatapultJesse** [comment]
For the moment I just run a postinstall:
`"postinstall": "rimraf node_modules/react-native-gifted-chat/node_modules/react-native-video",`
But agree it should be made a peerDependency

**Comment by tboulis** [comment]
Any update on this? Will this be fixed or should we implement the workarround posted?

**Comment by danilobuerger** [comment]
not stale

**Comment by tboulis** [comment]
not stale

**Comment by xcarpentier** [comment]
Now removed
