### ISSUE TITLE
socket.io with giftedchat problem

### ISSUE THREAD

**Issue by mirik999** [FaridSafi/react-native-gifted-chat#1216]
Hi everyone, i have a question about giftedchat with socket.io . I tried to implement real chat but something went wrong. Messages replace each other. 

```
function Chat(props) {
  const [messages, setMessages] = useState([]);

  useEffect(() => {
   //this works well
    socket.emit('loadMessages', {});
    socket.on('loadMessages', msg => {
      setMessages(msg);
    })
  }, []);

  function _onSend(msg) {
    socket.emit('newMessage', msg);
    socket.on('newMessageAll', msg => {
      setMessages(GiftedChat.append(messages, msg));
    })
  }

  console.log(messages)

  return (
    <GiftedChat
      messages={messages}
      onSend={msg => _onSend(msg)}
      user={{
        _id: props.user.id,
        name: props.user.nick,
      }}
      placeholder="Type here..."
      loadEarlier={true}
      renderSend={customSend}
      renderAvatar={(e) => customAvatar(e, props.user)}
      renderBubble={(e) => customBubble(e, props.user)}
    />
  );
}
```

backend

```
socket.on('newMessage', msg => {

      const newMessage = new Chat({
        _id: new mongoose.Types.ObjectId(),
        text: msg[0].text, 
        user: msg[0].user._id,
        createdAt: msg[0].createdAt 
      })
      newMessage
        .save(function(err) {
          if (err) {
            console.log('err', err)
            return;
          }
          newMessage.populate('user', 'nick guild color alliance', function(err, doc) {
            io.sockets.emit('newMessageAll', doc)
          });
        })
    })
```

**Comment by rafaelvinicius** [comment]
@mirik999 
Were you able to solve this problem?
I have the same problem.

**Comment by rafaelvinicius** [comment]
I solved the problem like this:

`    const onSend = async (message = []) => {
        const newMessages = await GiftedChat.append(messages, message)
        socket.on('chat message', newMessages => { setMessages(newMessages) });
        socket.emit('chat message', newMessages);
    }
`
I hope that help others

**Comment by Naphuc94** [comment]
> I solved the problem like this:
> 
> ` const onSend = async (message = []) => { const newMessages = await GiftedChat.append(messages, message) socket.on('chat message', newMessages => { setMessages(newMessages) }); socket.emit('chat message', newMessages); }`
> I hope that help others

i trying this work, but I have wrong render messages it not render by user id just random render message between users and i can not fix it. can you help me? my chatroom just 1:1 users
