### ISSUE TITLE
Adding support to SafeAreaView for iphoneX

### ISSUE THREAD

**Issue by JesuHrz** [FaridSafi/react-native-gifted-chat#1217]
#### Issue Description

When a safeAreaView is added an extra space is added between the keyboard and the input.

![GiftChat-1](https://user-images.githubusercontent.com/28031187/57249826-921f8080-700b-11e9-916c-80b291819b7c.gif)

#### Steps to Reproduce / Code Snippets

```
<SafeAreaView style={{flex: 1,  backgroundColor: '#F5FCFF' }}>
    <GiftedChat
      messages={this.state.messages}
      onSend={messages => this.onSend(messages)}
      user={{
        _id: 1
      }}
    />
</SafeAreaView>
```
#### Expected Results

![GiftChat-2](https://user-images.githubusercontent.com/28031187/57249841-9e0b4280-700b-11e9-9c8f-a16f1c4b5e79.gif)

#### Additional Information

* Nodejs version: 10.12.0
* React version: 16.8.3
* React Native version: 0.59.5
* react-native-gifted-chat version: 0.8.0
* Platform(s) (iOS, Android, or both?): iOS

**Comment by Hirbod** [comment]
Just add `bottomOffset={36}` to <GiftedChat/>. That's it :)
(of course it should be wrapped inside the SafeAreaView with flex: 1

**Comment by YousefAlsbaihi** [comment]
> Just add `bottomOffset={36}` to . That's it :)
> (of course it should be wrapped inside the SafeAreaView with flex: 1)
> 
> Make sure to add a isIphoneX check to it
> 
> ```js
>     isIphoneX() {
>         const {width, height} = Dimensions.get('window');
>         return (
>             Platform.OS === 'ios' &&
>             !Platform.isPad &&
>             !Platform.isTVOS &&
>             ((height === 812 || width === 812) ||(height === 896 || width === 896))
>         );
>     }
> ```
> 
> ```
> bottomOffset={this.isIphoneX() ? 36 : 0}
> ```

this would work but in android it will not be a good view do i modified it a little bit by adding space to the main view to margin from the bottom incase it's iPhone X



    <View style={{flex: 1, marginBottom: this.isIphoneX() ? 20 : 0}}>
      <GiftedChat
        messages={this.state.messages}
        onSend={this.addMessage.bind(this)}
        renderActions={this.renderCustomActions}
        bottomOffset={this.isIphoneX() ? 20 : 0}
      />
    </View>
