### ISSUE TITLE
Typescript fails to compile the library

### ISSUE THREAD

**Issue by panvourtsis** [FaridSafi/react-native-gifted-chat#1221]
#### Issue Description

I found some issues using this library with Typescript on my project.
There are compile errors on the project when someone imports it.

![image](https://user-images.githubusercontent.com/6433679/57530763-9f58aa00-7340-11e9-8daf-ec40e1faebe4.png)

i am using
react-native: 0.59.1
typescript: 3.4.5

#### Steps to Reproduce / Code Snippets

You must have a RN project with typescript. Import the library on a screen.
Then run `tsc .` and you will see the compile errors

#### Expected Results

Expecting not to have errors from this library

#### Additional Information

* Nodejs version: 10.14.1
* React version: 16.8.4
* React Native version: 0.59.1
* react-native-gifted-chat version: 0.8.0
* Platform(s) (iOS, Android, or both?): irrelative

**Comment by bintoll** [comment]
+ 1

**Comment by xcarpentier** [comment]
fixed on v0.8.2

**Comment by panvourtsis** [comment]
appreciated!
