### ISSUE TITLE
How to make chatbox(like emoji panel) switch with keyboard smoothly

### ISSUE THREAD

**Issue by flyinghawker** [FaridSafi/react-native-gifted-chat#1222]
Maybe someone know QQ or wechat, there is emoji panel or other options such as call, uploading image.
Basically chatbox cover almost same area as keyboard in screen. How to make them switch smoothly. This troubles a lot and I have tried many ways to figure out but still not that ideal. It always have unendurable delay when switch.
![IMG_0514](https://user-images.githubusercontent.com/13193798/57546280-ff763d00-738e-11e9-96e2-0aa6ccafe56a.PNG)

**Comment by 3luyka** [comment]
@flyinghawker you need something like "react native custom keyboard".
