### ISSUE TITLE
add babel.config.js to npmignore

### ISSUE THREAD

**Issue by mmerickel** [FaridSafi/react-native-gifted-chat#1223]
It looks like `.babelrc` was moved to `babel.config.js` and the `.npmignore` was not updated accordingly. This causes some issues with `eslint-import-resolver-babel-module` such as the following when used with eslint. Considering the old `.babelrc` was ignored in `.npmignore` I think it was just a refactoring oversight.

```
[eslint-import-resolver-babel-module] { Error: Cannot find module '@babel/preset-typescript' from '...snip.../app/node_modules/react-native-gifted-chat'
```

**Comment by xcarpentier** [comment]
Close 71a5245d7db2a3d6cddf2466feb96bafb5f5e3ed
