### ISSUE TITLE
Nothing is rendered, the component is empty when using react-navigation

### ISSUE THREAD

**Issue by stilllife00** [FaridSafi/react-native-gifted-chat#1224]
#### Issue Description

Nothing is rendered. The component is empty.

**EDIT**: found out that the problem happens only inside a `react-navigation` `createBottomTabNavigator`

#### Steps to Reproduce / Code Snippets

Setup a basic list of messages according to the readme using latest Expo version and latest version of the library.

#### Expected Results

The library works.

#### Additional Information

* Nodejs version: 8.15.1
* React version: "16.5.0"
* React Native version: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
* react-native-gifted-chat version: happens with 0.8.0 and 0.7 (i guess it just happens with any version)
* Platform(s) (iOS, Android, or both?): both
"react-navigation": "^3.0.9",

````
<GiftedChat
                messages={this.state.messages}
                onSend={messages => this.onSend(messages)}
                user={{
                    _id: 1
                }}
            />

this.state.messages contains 2 messages formatted according to the docs

````

![image](https://user-images.githubusercontent.com/3191603/57569884-fa9ba280-73fb-11e9-9c47-4c09e082fad5.png)

**Comment by bhartendu27** [comment]
[Here's a fix](https://github.com/wix/react-native-navigation/issues/399#issuecomment-256423963
)
```
import Dimensions from 'Dimensions';
<View style={{height: Dimensions.get('window').height - 65}}></View>
```
