### ISSUE TITLE
Props showUserAvatar does not work when disabled

### ISSUE THREAD

**Issue by bockc** [FaridSafi/react-native-gifted-chat#1229]
#### Issue Description

Props `showUserAvatar` does not work. There's a gap between the message bubble and the border of the screen even though it's disabled.
You can see on the screenshot below the gap, the red background obviously showing the gap inside the ListView component.
![image](https://user-images.githubusercontent.com/10670669/57710127-96cbe080-766c-11e9-8bad-0ba1be7d627c.png)

#### Steps to Reproduce / Code Snippets

The component is configured like this:
```
<GiftedChat
    onSend={messages => this.onSend(messages)}
    user={{ _id: this.props.jid }}
    keyboardShouldPersistTaps="never"
    bottomOffset={50}
    placeholder={TradSingleton.getTrad('chat.input')() || 'Type a message...'}
    messages={this.state.messages}
    locale={device.getTradLanguage()}
    listViewProps={{ backgroundColor: 'red' }}
    showUserAvatar={false}
/>
```

#### Expected Results

There should be no gap between the border of the screen and the message bubble.

#### Additional Information

* Nodejs version: v.10.12.0
* React version: 16.5.0
* React Native version: 0.57.1
* react-native-gifted-chat version: ^0.8.2
* Platform(s) (iOS, Android, or both?): iOS
* TypeScript version: ???

**Comment by bockc** [comment]
Just figured this out: 
the props user contains only the id of my user. I tried setting a name and suddenly the initials appeared as the avatar. Then I set the avatar to null and the gap disappeared. Sorry for opening this issue, I didn't think about trying this out before opening it.

It seems the props `showUserAvatar` is ignored when avatar is undefined in the `user` props, you should consider adding a small fix for that :)

**Comment by RocketeerFly** [comment]
Hi @bockc ,
I'm having the same issue. I want to show only avatar of other users and the other users could see my avatar.

**Comment by bockc** [comment]
If you don't want to show your own avatar, try setting it to `null` like that :

```
this.setState({
            chatItem,
            me: {
                _id: me.id,
                name: `${me['last_name']} ${me['first_name']}`,
                avatar: null,
            },
        })
```

Now your avatar won't be displayed next to your own messages and other people should still be able to see it.
