### ISSUE TITLE
Prevent Gifted Chat from scrolling when new item is added

### ISSUE THREAD

**Issue by cyberpunp** [FaridSafi/react-native-gifted-chat#1230]
#### Issue Description

I'm building a chat app using react-native-gifted-chat, which is using flatlist. The problem is that whenever new item is being, the list is scrolling automatically one row down, which is definetely not good if user is reading older messages at the same time. I was looking to catch this functionality and modify the code in Message,GiftedChat and MessageContainer files in src, but no result.

#### Steps to Reproduce / Code Snippets

I have followed this tutorial and issue is the same: https://medium.com/@phylypo/react-native-simple-chat-with-firebase-and-giftedchat-f7dbdff2883a
here is the demo from the tutorial: https://snack.expo.io/@bacon/firebase-basic-chat

#### Expected Results

Avoid automatic scroll when new item is added and user is reading older messages at same time.

#### Additional Information

* Nodejs version: 10
* React version: 16.5.0
* React Native version: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
* react-native-gifted-chat version: ^0.7.2
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by LGANGXY** [comment]
在this.state.showScrollBottom=true让FlatList的data不更新

**Comment by cyberpunp** [comment]
@LGANGXY thanks for the answer, but this is not what I'm looking for. I found this demo here: https://snack.expo.io/@rainliu123/flatlisttest and it's exactly what I'm trying to do but it seems that it doesn't work for Android at the moment, only for iOS

**Comment by kirillpisarev** [comment]
Right, maintainVisibleContentPosition works only for iOS (but works perfectly!).
Does anyone have an idea how to achieve the same behavior on Android?? I have faced the same problem and i have surprised that there is no known solution for such a usual for chats case... Any advices are welcome!

**Comment by watadarkstar** [comment]
> Right, maintainVisibleContentPosition works only for iOS (but works perfectly!). Does anyone have an idea how to achieve the same behavior on Android?? I have faced the same problem and i have surprised that there is no known solution for such a usual for chats case... Any advices are welcome!

@kirillpisarev Did you ever figure this out?
