### ISSUE TITLE
Send chart from react-native-chart-kit in Bubble

### ISSUE THREAD

**Issue by MLK57** [FaridSafi/react-native-gifted-chat#1237]
Hello I use GiftedChat for a chat bot and i use react-native-chart-kit to create some chart. I would like to send some chart during the conversation. But I have no idea how to do that.

It's an important part of my project..

Would anyone have an idea or solution?

* Nodejs version: [FILL THIS OUT]
* React version: 16.5.0
* React Native version: 0.57.1
* react-native-gifted-chat version: 0.9.0-beta.0
* Platform(s) (iOS, Android, or both?): Both

**Comment by xcarpentier** [comment]
See `renderCustomView`

**Comment by AtdheUruqi** [comment]
@MLK57 did you solve it ? i still have that problem !

**Comment by MLK57** [comment]
> @MLK57 did you solve it ? i still have that problem !

Yes ! I use renderCustomVIew !

**Comment by MLK57** [comment]
> See `renderCustomView`

thanks ! it's work
