### ISSUE TITLE
Scroll to Top  when when next page

### ISSUE THREAD

**Issue by acv-quyencv** [FaridSafi/react-native-gifted-chat#1239]
#### Issue Description

- I have a long Flatlist and it's data divided into many page: [ {item1}, {item2}, {end_page1}, { item4}, {item5}, {end_page2}, .........]

- When i tap on screen will show new message and expand to flatlist.

- How to scroll to top screen when reach new page ..??? And keep first item of new page on top screen when show next item until reach bottom. ???

EXPECTED RESULT
like gif screenshot below

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/32561050/58172712-7da5de00-7cc3-11e9-8cf2-7ab67e3d4271.gif)

**Comment by VladislavArkavenko** [comment]
Waiting for possible solutions also (or at least workarounds).
