### ISSUE TITLE
Documentation missing for sent/received ticks - need to declare renderTicks

### ISSUE THREAD

**Issue by shaktalles** [FaridSafi/react-native-gifted-chat#1241]
#### Issue Description

Documentation does not specify how to render sent/received ticks.
As of, you need to pass a renderTicks function to the GiftedChat component.

#### Expected Results

Simple 'renderTicks' entry on docs would have saved me over 2 hours time.

**Comment by xcarpentier** [comment]
Oups sorry, Prs are welcome ;)

**Comment by shaktalles** [comment]
Great, it will be my first on github.
By the way, thanks by the awesome library!

**Comment by hindsricardo** [comment]
is it renderTicks={true} to display ticks?

**Comment by Aryk** [comment]
I get an error with "renderTicks". I don't think it's in the library.  I'm on the latest version.

**Comment by yashkataruka** [comment]
renderTicks isn't a prop in <GiftedChat /> in the latest version that I have. It is inside renderBubble() component. Inside renderBubble() you have to write "renderTicks = {() => <Text>Ticks</Text>" and you can pass on the styles by using tickStyle = {}

**Comment by nbaua** [comment]
I am still looking for the **renderTicks** docs, can anyone share a working repo or a proper documentation with sample code?

**Comment by roshansingh21** [comment]
`
<GiftedChat
          ...
          renderTicks={renderTicks}
        />
`

`const renderTicks = (message) => {
    return (
      (message.received || message.sent) && (
        <Ionicons
          name={message.received ? "checkmark-done" : "checkmark"}
          size={16}
          style={{ paddingRight: 5 }}
          color={themes.LIGHT_COLOR}
        />
      )
    );
  };`

Hope this help someone.

**Comment by xuelink** [comment]
> `<GiftedChat ... renderTicks={renderTicks} />`
> 
> `const renderTicks = (message) => { return ( (message.received || message.sent) && ( <Ionicons name={message.received ? "checkmark-done" : "checkmark"} size={16} style={{ paddingRight: 5 }} color={themes.LIGHT_COLOR} /> ) ); };`
> 
> `{ _id: 1, text: 'My message', createdAt: new Date(Date.UTC(2016, 5, 11, 17, 20, 0)), user: { _id: 2, name: 'React Native', avatar: 'https://facebook.github.io/react/img/logo_og.png', }, sent: true, received: true, pending: true, }` Make sure your updated message has sent, recieved. You can write your own conditional rendering of ticks in renderTicks. Hope this help someone.

Thank you!
