### ISSUE TITLE
Fast scroll bug on Android

### ISSUE THREAD

**Issue by MamyChow** [FaridSafi/react-native-gifted-chat#1243]
#### Issue Description

Hi,
My problem is when i fast scroll it go in the wrong direction (test on OnePlus 6) so i try to add invertible={false} this solution stop the fast scroll bug but know if i send a message i don't see the message because it doesn't automatically scroll on bottom. I think the problem come from the invertibleScrollView but i don't know why.

If someone got a solution, thank you <3

#### Steps to Reproduce / Code Snippets

Fast scroll on Android real device

**Comment by rxhivzero** [comment]
https://github.com/facebook/react-native/issues/23158

**Comment by nubeble** [comment]
Same issue happened to me.
tested on Samsung Galaxy S7, Asus Tango, Xiaomi Mi A1.
Any help?

**Comment by MamyChow** [comment]
i upgrade react-native to 0.59.3 and now it's working
