### ISSUE TITLE
No message show on Android

### ISSUE THREAD

**Issue by hiepecom** [FaridSafi/react-native-gifted-chat#1244]
#### Issue Description

My messages cannot render on Android but on iOS is ok

#### Expected Results

Messages can render both iOS and Android

#### Additional Information

* Nodejs version: 11.0.0
* React version: 16.6.3
* React Native version: 0.58.4
* react-native-gifted-chat version: ^0.9.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by xcarpentier** [comment]
Can you precise the android device details ?

**Comment by hussainahmad** [comment]
@xcarpentier  I hope he is getting same issue as #736 I am getting this with `forceGetKeyboardHeight={true}` and on default this is showing like this in android.  `TextInput` is overlapping on Message List. 
![Screenshot_20190619-182413](https://user-images.githubusercontent.com/5903522/59776192-ce612480-92cb-11e9-8714-117cee2ddf0c.png)

**Comment by hussainahmad** [comment]
I am getting this on android Nexus P6
