### ISSUE TITLE
How to install fork of Gifted chat from git?

### ISSUE THREAD

**Issue by ajaykumar97** [FaridSafi/react-native-gifted-chat#1245]
#### Issue Description
I want to install a fork of ``react-native-gifted-chat`` in my project. I have created a fork of the project and updated some files according to my needs. But the ``src`` folder is not included in the ``node_module/react-native-gifted-chat`` folder. Can anyone tell me how to install a fork of this project.

#### Steps to Reproduce / Code Snippets

I tried to install the fork using command:

``npm install --save git://github.com/my_username/react-native-gifted-chat#master``

But the ``src`` folder is missing from the directory.

**Comment by xcarpentier** [comment]
Sorry but this is not an issue related to this project.

**Comment by ethanyuwang** [comment]
also have the same question

**Comment by ahartzog** [comment]
I would really like to be able to fork this directly off github as well.
