### ISSUE TITLE
How to send a view with Buttons on Gifted-Chat ? 

### ISSUE THREAD

**Issue by AtdheUruqi** [FaridSafi/react-native-gifted-chat#1246]
#### Issue Description

Hello guys,

how can i send a view with buttons something like this ? 
for example: when i click the hand on the input, it will send a view with buttons !

![GIThelp](https://user-images.githubusercontent.com/43423742/58422250-62a3e700-8092-11e9-95ab-05607ec35905.PNG)

**Comment by xcarpentier** [comment]
You’ve to use `renderCustomView`

**Comment by AtdheUruqi** [comment]
@xcarpentier now it render every-time i type something!
How can i manage that ?
I want when the user type and when it hit send now, to not render the CustomView that i made :/
![Screenshot_1559234946](https://user-images.githubusercontent.com/43423742/58649168-b5d49e80-830b-11e9-99b0-55a67dc7f8b1.png)

**Comment by xcarpentier** [comment]
`renderCustomView(currentMessage)` you have to test your data in message when you want to display custom view from message meta.

**Comment by AtdheUruqi** [comment]
@xcarpentier not sure i truly understand :/ , any example would be a great help .

**Comment by evertonco** [comment]
It's very simple. Create a custom field on your message object, like "invitation". On rendercustomview method, check if currentmessage own invitation field, eg if(currentmessage.invitation). Otherwise, returno null
