### ISSUE TITLE
Show loading indicator for Typing/server response

### ISSUE THREAD

**Issue by vivekhumnabad** [FaridSafi/react-native-gifted-chat#1248]
I wanted to build a chatbot with your lib
I want to show an indicator (in System response side) while I make a server response and once I get the response I should hide loader and show message or custom component. Is this possible???

**Comment by evertonco** [comment]
Site. Just implement a "typing" websocket event on server and listen to It on client

**Comment by asong4211** [comment]
I implemented mine by `setState({loading:true})`, do some backend calls, and then `setState({loading:false})`. Then in your <GiftedChat /> pass in the your own renderFooter props, like this:
```
const renderFooter = () => {
     return ( 
           <View> 
                 <Image source={require('../../assets/loading.png')} /> 
            </View>
}
```
- You can replace the loading image with the ActivityIndicator as well
