### ISSUE TITLE
Customize message structure

### ISSUE THREAD

**Issue by superandrew** [FaridSafi/react-native-gifted-chat#1251]
#### Issue Description

This is more of a help request than a real issue.

I would like to use my field names, for example for the "_id" field

#### Steps to Reproduce / Code Snippets

The type of field for the message is not editable. Unless I didn't understand how to customize it.

#### Expected Results

Since I need to send message using an API, I am forced to change my "id" field to "_id", my "picture" field to "image" and similar. It would be nice to have a "mapping" of the file types. I assume that https://github.com/FaridSafi/react-native-gifted-chat/issues/210 answers this question, but I didn't understand how to do it from the documentation.

#### Additional Information

* Nodejs version:11
* React version: 16.5
* React Native version: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
* react-native-gifted-chat version: 0.9.3
* Platform(s) (iOS, Android, or both?):both
* TypeScript version: tslib 1.9.3

**Comment by walidvb** [comment]
@superandrew you'll want to do smth of the sort(with any sort of syntax, of course): 

```
const mappedMessages = originalMessages.map(({id: _id, picture: image, ...otherProps}) => ({
    ...otherProps,
    _id,
    image,
}))

const chatComponent = <GiftedChat messages={mappedMessages} />
```

**Comment by aguscha333** [comment]
@superandrew if you don't want to be parsing all the messages like that you can do what I did and use [patch-package](https://www.npmjs.com/package/patch-package). I installed it, added the post-install command that calls it and then just opened the folder of gifted chat inside the node_modules on a text editor and searched for all instances of `_id` and replaced them with `id`.

then run `yarn patch-package react-native-gifted chat` and it worked like a charm.

**Comment by superandrew** [comment]
@aguscha333 you rock! But this does seem to be like something that won't work on distributed environments, or does it?

**Comment by ethanyuwang** [comment]
Hi did you figure out a more graceful solution?

**Comment by walidvb** [comment]
@superandrew what do you mean, on distributed environments?
If you add a `"postinstall": "npx patch-package"` to your `package.json`, it will patch the packages after you install, so should work across machines.

Careful though, `npm` automatically runs the postinstall hook, while with yarn it must be run manually(afaik)
