### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Avishaidev** [FaridSafi/react-native-gifted-chat#1254]
#### Issue Description
error: bundling failed: Error: Unable to resolve module `tslib` from `C:\testApps\react-native-firebase-starter\node_modules\react-native-gifted-chat\lib\Avatar.js`: Module `tslib` does not exist in the Haste module map

#### Additional Information

* Nodejs version: 8.9.2
* React Native version: 0.59.3
* react-native-gifted-chat version: 0.9.3
* Platform(s) (iOS, Android, or both?): android

**Comment by Avishaidev** [comment]
fix by npm install react-native-gifted-chat@0.2.x

**Comment by afacar** [comment]
I'm having the same problem. But are we supposed to use v@0.2.x not to get this error?
