### ISSUE TITLE
Duplicate date display if i add messages during scroll.

### ISSUE THREAD

**Issue by rajscet** [FaridSafi/react-native-gifted-chat#1257]
I have implemented load more during scroll but i am getting duplicate time on center(4 th june you can see in this picture)
![dddd](https://user-images.githubusercontent.com/6961313/58954648-67b21600-87b7-11e9-9157-b205eacb5786.PNG)

I want to avoid this repeating date

**Comment by xcarpentier** [comment]
Hi,
Can you please test in the latest version?
Thank you
