### ISSUE TITLE
is there a way to add image and video from our phone?

### ISSUE THREAD

**Issue by ManuRodgers** [FaridSafi/react-native-gifted-chat#1260]
like there are two buttons on the left of input bar and once I click those two buttons and I can choose whatever pictures or videos that I want to send. is there any demo for this features?

**Comment by pzatorski** [comment]
There is something similar to what you are looking for:
1) Clone this repository.
2) in your Terminal run `cd react-native-gifted-chat`
3) Inside the project run `npm install` or `yarn install`
4) expo start

If this helps, please close the issue..

**Comment by joshuakoh7** [comment]
Is there a demo for this without expo but something like react-native-image-picker?
