### ISSUE TITLE
tslib not found

### ISSUE THREAD

**Issue by afacar** [FaridSafi/react-native-gifted-chat#1263]
#### Issue Description

I just created new react-native project and installed gifted-chat. But I'm getting the following error while trying to run project on windows&android emulator.

> error: bundling failed: Error: Unable to resolve module `tslib` from `C:\Users\ASUS\Apps\EvdeBakim\node_modules\react-native-gifted-chat\lib\Avatar.js`: Module `tslib` does not exist in the Haste module map

I tried already to remove node_modules and npm install again. Thanks for the great module and any help in advance.

#### Steps to Reproduce / Code Snippets

`npm install react-native-gifted-chat --save`
`react-native run-android`

#### Expected Results

Gifted Chat screen!

#### Additional Information

* Nodejs version: v10.4.0
* React version: 16.8.3
* React Native version: 0.59.9
* react-native-gifted-chat version: ^0.9.3
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: No TypeScript

**Comment by maxgfr** [comment]
+1

**Comment by dnolbon** [comment]
You should run  `npm install --save tslib`

**Comment by afacar** [comment]
@dnolbon thanks for the answer. It solved the issue.
Just wondering, why this wasn't an issue before and happened with latest version? is it a new dependency for the gifted-chat?

**Comment by xcarpentier** [comment]
Hi guys,
Sorry about that, I've just changed the TS config to not have a require dependency to `tslib`.
Please test the new version `0.9.4`.
Thanks

**Comment by afacar** [comment]
@xcarpentier thanks for quick fix.
