### ISSUE TITLE
Request: Allow for user Ids in messages to be strings?

### ISSUE THREAD

**Issue by unfrgivn** [FaridSafi/react-native-gifted-chat#1264]
#### Issue Description

Formatted chat message user Id must be a number or else all chats appear on the left side

#### Steps to Reproduce / Code Snippets

Set user._id to string when formatting messages

#### Expected Results

The issue is if your system uses 64-bit integers for unique message/user Ids then you cannot cast these as numbers in Javascript or they will get truncated. Not sure if there is a reason this has to be a number?

As a workaround I am using the [big-integer package](https://www.npmjs.com/package/big-integer) which seems to work fine with the native comparison operators.

#### Additional Information

* Nodejs version: 11.11
* React version: 16.6.3
* React Native version: 0.57.8
* react-native-gifted-chat version: 0.8.0
* Platform(s) (iOS, Android, or both?): both

**Comment by unfrgivn** [comment]
I must have been mistaken, BigInt() is not working so I am back to the drawing board

**Comment by xcarpentier** [comment]
Hi,
Can you make a PR?
