### ISSUE TITLE
How to include share location in gifted chat?

### ISSUE THREAD

**Issue by akhiljasrotia** [FaridSafi/react-native-gifted-chat#1268]
#### Issue Description
I want to share location in gifted chat and there's no documentation about that.

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by xcarpentier** [comment]
Hi,
You can find an example here: https://github.com/FaridSafi/react-native-gifted-chat/blob/87bc0410928ce3a72c7e2fc91ac3a2635ff01e2b/example-expo/mediaUtils.js#L31

**Comment by akhiljasrotia** [comment]
Hey,
I tried passing the location and I'm able to send it to the firebase storage but I'm not able to display it in the app. I checked the message type and I didn't find any "messageLocation" file. How can I display it in the app?

**Comment by xcarpentier** [comment]
You have to investigate around the renderCustomMessage function.

**Comment by akhiljasrotia** [comment]
> You have to investigate around the renderCustomMessage function.

Hey,
I used the customMessage function and it is working perfectly. Thanks :)

**Comment by seansio1995** [comment]
Could you please give me a detailed example about how to send location through renderCustomMessage function? I really appreciate it 👍

**Comment by azor0** [comment]
Any update on this? I am getting a weird error when I try to pass location props for this:
```
if (currentMessage.location) {
      return (
        <TouchableOpacity
          style={[styles.container, containerStyle]}
          onPress={this.openMapAsync}
        >
          <MapView
            style={[styles.mapView, mapViewStyle]}
            region={{
              latitude: currentMessage.location.latitude,
              longitude: currentMessage.location.longitude,
              latitudeDelta: 0.0922,
              longitudeDelta: 0.0421,
            }}
            scrollEnabled={false}
            zoomEnabled={false}
          />
        </TouchableOpacity>
      )
    }
```

**Comment by drbhol** [comment]
> > You have to investigate around the renderCustomMessage function.
> 
> Hey,
> I used the customMessage function and it is working perfectly. Thanks :)

@akhiljasrotia 
can you please explain the customMessage function about location?

**Comment by meta-utkarsh-ahuja** [comment]
how can we use this can anyone please help how a user send its current location using gifted chat please help
