### ISSUE TITLE
Setting react keys for quickreplies

### ISSUE THREAD

**Issue by superphil0** [FaridSafi/react-native-gifted-chat#1269]
https://github.com/FaridSafi/react-native-gifted-chat/blob/c3c4539fc75a9d7d18211f167f8f663df6fe733d/src/QuickReplies.tsx#L155

Hi referenced the line where keys for the react components of quickreplies are being set.
In my case we sometimes have multiple quickreplies with identical value (so we can mock user choices or as placeholders for later) But react does not allow same keys for elements in a list

This is why I think the id should be set to messageId which has to be set in each reply anyways.

br

**Comment by xcarpentier** [comment]
Please feel free to create a PR

**Comment by superphil0** [comment]
https://github.com/FaridSafi/react-native-gifted-chat/pull/1270

**Comment by xcarpentier** [comment]
I reviewed
