### ISSUE TITLE
Integrating Dialogflow cards

### ISSUE THREAD

**Issue by itsrrworld** [FaridSafi/react-native-gifted-chat#1274]
#### Issue Description

Currently am working with integrating dialogflow with react-native using GiftedChat and  am unable to render the weather card exported from dialogflow.

#### Code Snippets

This is the code (Node.js) am using in dialogflow for producing weather card.
```
agent.add(new Card({
          title: `Weather in ${address}`,
          text: round(result.data.main.temp-273.15) + `°C with a humidity of ` + result.data.main.humidity,
          image: {
            url: 'https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwizvIGO3O7iAhUIWX0KHTX2C6YQjRx6BAgBEAU&url=https%3A%2F%2Fcodemyui.com%2Fcartoony-weather-animation%2F&psig=AOvVaw3alm_xctlM4pkolrtbTppx&ust=1560799128219647',
            accessibilityText: 'Google Logo',
          },
 }));
```

#### Expected Results

![w1](https://user-images.githubusercontent.com/25461059/59668739-9c21cb00-91d6-11e9-969b-8f232ce69185.png)

Can someone help me with this?

**Comment by xcarpentier** [comment]
You have to investigate renderCustomView function

**Comment by Woolei** [comment]
i am using Azure Bot Service, you may try my script below.
*i didnt put full script, as i believe you already make the chat work?

//your giftedchat js
renderAdaptiveView(props) {
    return <AdaptiveView {...props} />
  }

 <GiftedChat
 renderCustomView ={this.renderAdaptiveView}
/>

//Adaptiveview.js (you can amend from the sample CustomView.js)
//check currentMessage type
 if (currentMessage.attachments[0].contentType === "application/vnd.microsoft.card.video")
      {
        if (currentMessage.attachments[0].content)
        {
             adaptiveBody =<View>
              <Image style={{width:'100%',height:200,resizeMode:'cover',alignSelf:'center',}}  source={{uri: currentMessage.attachments[0].content.image.url}}></Image>
              <Text style={{fontWeight:'bold',}}>{currentMessage.attachments[0].content.title}</Text>
              <Text style={{fontWeight:'bold',}}>{currentMessage.attachments[0].content.subtitle}</Text>
              <Text style={{}}>{currentMessage.attachments[0].content.text}</Text>
           </View>
        }
     }

 return (
             <View style={{padding:10, flexDirection: 'column',justifyContent: 'space-between'}}>
             {adaptiveBody}
        
          </View>
          )


Enjoy.
