### ISSUE TITLE
Sending message with enter button on keyboard

### ISSUE THREAD

**Issue by batuhansahan** [FaridSafi/react-native-gifted-chat#1279]
#### Issue Description

How can i send message with enter button on keyboard

#### Additional Information

* Nodejs version: 8.x
* React version: 16
* React Native version: 0.56
* react-native-gifted-chat version: latest
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: [FILL THIS OUT]

**Comment by Woolei** [comment]
are you building web or mobile?
for mobile, this doesn't seem necessary.

**Comment by batuhansahan** [comment]
i am building web, and i can't handle trigger send button in composer

**Comment by michaelihwang** [comment]
> i am building web and i can't handle trigger send button in composer.js

I'm building for mobile, but here's how I got around it.

```
renderInputToolbar = (props) => {
  return (
    <InputToolbar {...props}
      textInputProps={{
        onSubmitEditing: () => {
          if (props.text && props.onSend) {
            let text = props.text;
            props.onSend({ text: text.trim() }, true)
          }
        };
      }}
    />
  );
}
```
So I'm pulling in `text` and `onSend` props that are being passed down from parent  into TextInput. After some digging around, I found the if statement in the `Send` component where they handle `onPress`.

**Comment by smxdevst** [comment]
@FaridSafi  Any other solution on that?

**Comment by pssgo** [comment]
same issue 
send Message with enter button on Keyboard for mobile
