### ISSUE TITLE
How to handle keyboard autocorrect when using send button.

### ISSUE THREAD

**Issue by xiaopow** [FaridSafi/react-native-gifted-chat#128]
Hey guys, been trying to read through your source code to see how to let auto correct edit text first before the send button sends the text. I am currently having the following issue.

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/10229915/15561738/8a9ffd6a-232b-11e6-89cf-d342ea0ef727.gif)

As you can see, the auto correct is not able to change the text if I just press "Send". I would like to know what I need to do to have the auto correct edit the text first before it is sent. Thank you.

**Comment by CodeTitanian** [comment]
+1

**Comment by anativ** [comment]
+1

**Comment by Blquinn** [comment]
You can probably simulate a space bar press at the beginning of the send button's onPress function. I believe that would enter the candidate spell correction. Just a shot in the dark.

**Comment by Moamber100x** [comment]
textInputProps={{autoCorrect: false}}
          use this as props . Thanks
