### ISSUE TITLE
[Feature] SystemMessage support message image

### ISSUE THREAD

**Issue by wallevy** [FaridSafi/react-native-gifted-chat#1280]
#### Issue Description

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by xcarpentier** [comment]
Hi,
Thanks for asking.
You have to investigate `renderCustomMessage`.

**Comment by wallevy** [comment]
@xcarpentier 
Thank you! I am currently using the renderSystemMessage to render image for SystemMessage. I think it would be better if the `gifted-chat` support this in the future.
