### ISSUE TITLE
SpeechToText in custom Action and reader it to text field box before send

### ISSUE THREAD

**Issue by Woolei** [FaridSafi/react-native-gifted-chat#1281]
#### Issue Description

![image](https://user-images.githubusercontent.com/6512444/60084539-4dda7200-976a-11e9-882b-269e2206dd59.png)

Hi Guys,
i am currently develop a speech control, when i click and speak, it will auto render the speechtotext result at textfield.

any idea how to pass it?

or to make it simple, when i click the "Mic" button, i want to pass a static text "i m speaking" to the text field, after 2 second, i want to auto trigger "send" event to the chatbox.

#### Expected Results

1) Speech by click on that button (done)
2) text render into the text field (how to do?)
3) send after preview in text field.

**Comment by vkkan** [comment]
@Woolei How did you manage to add those buttons below text box , pls share the snippet ? highly appreciated your help

**Comment by Woolei** [comment]
https://github.com/FaridSafi/react-native-gifted-chat/blob/master/example-expo/AccessoryBar.js

@vkkan, it is the default example, just do another fresh clean clone and you will see it on your new project.

**Comment by vkkan** [comment]
> https://github.com/FaridSafi/react-native-gifted-chat/blob/master/example-expo/AccessoryBar.js
> 
> @vkkan, it is the default example, just do another fresh clean clone and you will see it on your new project.

Thanks for the link

**Comment by Mukesh-Singh** [comment]
> #### Issue Description
> ![image](https://user-images.githubusercontent.com/6512444/60084539-4dda7200-976a-11e9-882b-269e2206dd59.png)
> 
> Hi Guys,
> i am currently develop a speech control, when i click and speak, it will auto render the speechtotext result at textfield.
> 
> any idea how to pass it?
> 
> or to make it simple, when i click the "Mic" button, i want to pass a static text "i m speaking" to the text field, after 2 second, i want to auto trigger "send" event to the chatbox.
> 
> #### Expected Results
> 1. Speech by click on that button (done)
> 2. text render into the text field (how to do?)
> 3. send after preview in text field.

@Woolei is there any update on it, have you implemented this.
