### ISSUE TITLE
compile error with react-native-web?

### ISSUE THREAD

**Issue by lmessinger** [FaridSafi/react-native-gifted-chat#1282]
#### Issue Description
Trying to compile new TSX version with react-native-web . 
results on error at:
const GiftedActionSheet = ActionSheet as any
                                                                ^

#### Steps to Reproduce / Code Snippets
started from create-react-app
added AppRegistry entries
added yarn add typescript
yarn start/build

#### Expected Results
no error! 

thanks!!!! for any hint

**Comment by xcarpentier** [comment]
Please look at this: https://github.com/FaridSafi/react-native-gifted-chat/pull/1284

**Comment by ReallyLiri** [comment]
@xcarpentier any ETA on merging the PR?

**Comment by xcarpentier** [comment]
@ReallyLiri more reviews I'll have fastest it should be :)
Don't hesitate to read the code and let me know if you find some errors.
