### ISSUE TITLE
React components not extendable as props interfaces are private in .d.ts files

### ISSUE THREAD

**Issue by ankhzet** [FaridSafi/react-native-gifted-chat#1283]
#### Issue Description

React components not extendable as props interfaces are private in `.d.ts` files:
``` typescript
// SystemMessage.d.ts

// here props interface is not exported
interface SystemMessageProps<TMessage extends IMessage> {
    currentMessage?: TMessage;
    containerStyle?: StyleProp<ViewStyle>;
    wrapperStyle?: StyleProp<ViewStyle>;
    textStyle?: StyleProp<TextStyle>;
}
export default class SystemMessage<TMessage extends IMessage = IMessage> extends Component<SystemMessageProps<TMessage>> {
```

``` typescript
// GiftedChat.d.ts

// only class definition is used
import SystemMessage from './SystemMessage';

// only class is exported from definition file
export { ..., SystemMessage, ... };
```

#### Steps to Reproduce / Code Snippets

``` typescript
import { SystemMessageProps } from 'react-native-gifted-chat'; // TS2305: Module '"node_modules/react-native-gifted-chat/lib"' has no exported member 'SystemMessageProps'.

interface Props extends SystemMessageProps {
  currentMessage: SomeOtherCompatibleType;
}

export class SystemMessage extends React.Component<Props> {
  render() {
    const { currentMessage, containerStyle } = this.props; // TS2339: Property 'containerStyle' does not exist on type 'Readonly<Props> & Readonly<{ children?: ReactNode; }>'.

    return (
      ...
    );
  }
}

```

#### Expected Results

Props interfaces exported in `.d.ts` files.

#### Additional Information

* react-native-gifted-chat version: 0.9.7

**Comment by xcarpentier** [comment]
You can do it like that: `SystemMessage['props']`

**Comment by ankhzet** [comment]
1. Seems like a gross hack. You can, probably, declare iterator parameters in some method via `method(elements: Array[@iterator]) {}`, but would you?
2. Generics fly out of the window.
3. `TS2499: An interface can only extend an identifier/qualified-name with optional type arguments.`.
4. If I try ty bypass №3 via `type SomeIntermediate = SystemMessage['props']; interface Props extends SomeIntermediate {}` or `type Props = SystemMessage['props'] & {}`, then `TS2395: Individual declarations in merged declaration 'SystemMessage' must be all exported or all local.`.

P.S. Also, I'm forced to alias imported class name, 'cause locally defined class: `import { SystemMessage as BaseSystemMessage } from 'react-native-gifted-chat';` and then `BaseSystemMessage['props'] yada yada`, but that's rather minor inconsequence.

**Comment by xcarpentier** [comment]
done on the latest version: [v0.9.8](https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/v0.9.8)

**Comment by ankhzet** [comment]
Great! Thanks, @xcarpentier for quick fix!

Only inconvenience (but not a pressing issue) is as I mentioned:
```typescript
// GiftedChat.d.ts

// only class definition is used
import SystemMessage from './SystemMessage';

// only class is exported from definition file
export { ..., SystemMessage, ... };
```

In `types.d.ts` only declarations from `Bubble.d.ts` are re-exported, so, in case of `SystemMessageProps` and some others, we can import prop typedefs only via specific imports: `import { SystemMessageProps } from 'react-native-gifted-chat/lib/SystemMessage';`

**Comment by xcarpentier** [comment]
Can you please re-open an issue?
And PRs are welcome ;)

**Comment by ankhzet** [comment]
It seems, I can't reopen the issue, if I'm not the one who closed it: https://stackoverflow.com/a/21333938/2109067
I can create new issue, if you okay with that, or just cook-up a PR.
