### ISSUE TITLE
The link for advanced example broken

### ISSUE THREAD

**Issue by emclab** [FaridSafi/react-native-gifted-chat#1285]
The advanced example on main page is broken and display page 404. Here is the current link which displays 404: https://github.com/FaridSafi/react-native-gifted-chat/blob/master/example/App.js.

**Comment by xcarpentier** [comment]
Thanks

**Comment by reidkersey** [comment]
It appears that the entire example folder was deleted in this commit: https://github.com/FaridSafi/react-native-gifted-chat/commit/af7758a935f5fa298befc33261c23155d74afc38
