### ISSUE TITLE
props.value is null in quick reply

### ISSUE THREAD

**Issue by deepankarsandy** [FaridSafi/react-native-gifted-chat#1288]
#### Issue Description

inside callback function of `onQuickReply`, props.value is coming empty.
when debugger mode is on its working. try `Alert.alert(props[0].value)`, it's empty.

#### Steps to Reproduce / Code Snippets

use `onQuickReply` hook and inside callback function see `props[0].value`, it's empty. use `Alert` since it's working while debugger mode is on.

#### Expected Results

Selected replies values

#### Additional Information

Traced down to where it's happening and found that on `handleSend` line 121 it's assigning reply object and messageId to a new object, there assigning is not happening.

[https://github.com/FaridSafi/react-native-gifted-chat/blob/c1e51b0d92e3ba4adf32712844c69e059b6b62aa/src/QuickReplies.tsx#L121](url)

while using ReactNative it's converting to `QuickReplies.js` and there its doing `this.props.onQuickReply(
          replies.map(reply =>
            Object.assign({}, reply, { messageId: currentMessage._id }),
          ),
        )`

when did `Alert.alert()` , new obj.value is empty

**### PROBABLE FIX**
change in js file
` this.props.onQuickReply(
          replies.map(reply => {
            return { ...reply, ...{ messageId: currentMessage._id } }
          }),
        )`

please change in git/npm and push

* Nodejs version:10.15.6
* React version: 16.8.3
* React Native version: 0.59.5
* react-native-gifted-chat version: 0.9.6
* Platform(s) (iOS, Android, or both?): iOS

**Comment by xcarpentier** [comment]
fix on [v0.9.10](https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/v0.9.10)
