### ISSUE TITLE
[Request] Pass in children for additional layout?

### ISSUE THREAD

**Issue by braco** [FaridSafi/react-native-gifted-chat#129]
Great work! 

What do you think of doing something like this to allow for passing in additional layout / items?

```
import Foo from 'foo-module';
<GiftedMessenger bubbleChild={Foo} />
```

Bubble class would render <Foo />. Could also support textChild, etc.

Alternatively,

```
<GiftedMessenger>
    <Foo />
</GiftedMessenger>
```

and render into the row with {this.props.children}

For my case, this is because I need a very simple extra layout element, but I can think of a lot of other reasons to want this feature. Without this, I need to fork the entire project internally.

**Comment by sibeliusseraphini** [comment]
I think this is a good idea, instead of passing custom functions or components for each customizable part we could have default components and just change the ones to handle our needs
