### ISSUE TITLE
How to display the image/video in gifted chat?

### ISSUE THREAD

**Issue by emclab** [FaridSafi/react-native-gifted-chat#1290]
How to display image/video in gifted chat?

Created message object as below:

let r = {
          _id: msg.id,
          text: msg.data.msg_body,
          image: msg.data.image,  //<<=string of URL
          video: msg.data.video,  //<<=string of URL
          createdAt : msg.createdAt,
          user: {
            _id: msg.sender_id,
            name: msg.user_name,
            avatar: msg.user_avatar,
          }
        };

My render code is:

render() {
      return (
          <GiftedChat 
            messages={this.state.messages}
            onSend={messages => this._onSend(messages)}
            user={{_id: this.props.navigation.state.params.user.id,
                   name: this.props.navigation.state.params.user.name,
                   avatar: this.props.navigation.state.params.user.user_data.avatar}}
          /> 
      );
    }

But there is image or video shown. What do I need to do to enable the image/video showing? 

https://snack.expo.io/@xcarpentier/gifted-chat This example didn't give a clue of how to deal with image/video and rest of the example I found so far was only for text message which can be handled by render above. Please help. Thanks. 
 

need know-how

#### Expected Results

Be able to display image/video on chat screen

#### Additional Information

* Nodejs version: 10.16.0
* React version: 16.8.3
* React Native version: 0.59.9
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): Both
* TypeScript version: none

**Comment by xcarpentier** [comment]
It should work as expected.
But we can't show image and video in the same time.

**Comment by virtualLast** [comment]
@xcarpentier are you saying that a single message cannot contain the image and video property? Or that the messages[] cannot contain image and video?

**Comment by xcarpentier** [comment]
a single message cannot contain the image and video property

**Comment by fukhaos** [comment]
is there play/pause button on video message ?

**Comment by dharmendrashah** [comment]
same issue with me

**Comment by luatnd** [comment]
Image sometimes displayed!! I found this issue on iPhone 12 Pro simulator
