### ISSUE TITLE
prevent onInputTextChanged when sending message

### ISSUE THREAD

**Issue by unfrgivn** [FaridSafi/react-native-gifted-chat#1291]
#### Issue Description

The problem is that I am sending an update to my backend whenever the user begins typing or clears the message input to show an indicator for others. However, I don't want this to be triggered when actually sending a message because the `onInputTextChanged` is called before the `onSend handler` and thus User B sees the typing indicator disappear 1-3 seconds before they receive the message which is awkward. 

I can't disable the typing indicator call by checking for empty text because I need to be able to fire it when the user starts typing but then deletes. I'm not sure how to treat the input cleared event differently when the user explicitly does it vs sends the message since this handler only receives the text. Maybe I'm missing something obvious here??

```
messageAddedHandler = async (messageList = {}, rowID = null) => {
    const { Channels, Messages } = this.props;
    await Messages.sendMessage(messageList, Channels.channel._id, rowID);
    
    // Update text in state
    this.setState({ typingText: '' });
}

textChangedHandler = async text => {
    // Update text in state
    this.setState({ typingText: text });

    // Update backend with typing state
    const { Channels } = this.props;
    Channels.channelIsTyping(text != "");
}
```

#### Steps to Reproduce / Code Snippets

When using a remote call to update typing state for another user that triggers a typing indicator via renderFooter, send a message and wait for both of those remote calls to update the state on the second user

#### Expected Results

Ability to control my typing indicator prop changes after the message has been sent and ideally control is completely from the socket listener on the other user by detecting a send event in the input changed handler or other workaround. 

#### Additional Information

* Nodejs version: 10.0
* React version: 16.6.3
* React Native version: 0.57.8
* react-native-gifted-chat version: 0.8
* Platform(s) (iOS, Android, or both?): both

**Comment by xcarpentier** [comment]
You are able to set `<TextInput/>` override almost all props via `textInputProps`.
So I guess you have to investigate which handler fit your goal.
