### ISSUE TITLE
White space above keyboard when emoji is displayed in IOS

### ISSUE THREAD

**Issue by aniciom** [FaridSafi/react-native-gifted-chat#1294]
#### Issue Description
I'm having an issue the plugin is working fine but when in iphone X, I open the emoji keyboard a blank space is added into the TextInput, is there any way to avoid this behaviour? 

I tried many things but i couldn't get it working, one is the thing maybe is implement a custom accessory bar to mask this gap, but in this case i don't need it.

Any help would be appreciated
Thanks.

#### Steps to Reproduce / Code Snippets
I've the next code
 ```
<View  style={{flex:1}}>
          <GiftedChat
            isAnimated={false}
            messages={this.state.messages} 
            onSend={messages => this.onSend(messages)}
            videoProps={{
              paused: true,
            }}
            user={{
              _id: 1,
              name: 'An'
            }}
              ></GiftedChat>

          <KeyboardAvoidingView behavior={ Platform.OS === 'android' ? null :  null} />
        </View>
```

[
![IMG-1559 TRIM](https://user-images.githubusercontent.com/5354596/60513505-c7fc8080-9cad-11e9-8f7c-5c2cb3ceb55e.gif)
](url)
#### Expected Results

No blank space in the TextInput once the emoji keyboard is opened.

#### Additional Information

* Nodejs version: 10.16.0
* React version: 16.8.3
* React Native version: 0.59.9
* react-native-gifted-chat version: 0.9.11
* Platform(s) (iOS, Android, or both?): iOS
* TypeScript version: 3.4.1

**Comment by xcarpentier** [comment]
And without : KeyboardAvoidingView?

**Comment by aniciom** [comment]
The same

**Comment by aniciom** [comment]
Ok it seems the PR https://github.com/FaridSafi/react-native-gifted-chat/pull/1171 from @nandiniparimi1107 fixes the issue, wrapping the animatedview that holds messagesContainerHeight was causing the white gap once the emoji keyboard were opened.

I close this

**Comment by msqar** [comment]
I'm seeing this currently on iPhone XS (real device) latest iOS version. Latest gifted-chat and RN 0.60.5. Only happens when I open the emoji. I set the isAnimated={false} as nandini suggests. But still.
