### ISSUE TITLE
quickReplyStyle doesn't override style

### ISSUE THREAD

**Issue by phoebexy** [FaridSafi/react-native-gifted-chat#1295]
Default QuickReply style isn't overridden with quickReplyStyle

`<GiftedChat quickReplyStyle={styles.quickReply} />`

I notice that quickReplyStyle isn't listed as a default prop, new to React Native so not sure where the problem is in the library.

Expected: change in QuickReply style

* react-native-gifted-chat version: 0.9.11

**Comment by xcarpentier** [comment]
Hi,
Can you copy here the content of this style please: `styles.quickReply` ?

**Comment by nzrin** [comment]
Please re-open. I can't use quickReply props.
