### ISSUE TITLE
Keyboard always dismiss when Send message on iOS

### ISSUE THREAD

**Issue by Stjng** [FaridSafi/react-native-gifted-chat#1300]
#### Issue Description

Keyboard always dismiss when click Send on iOS when using Example Code

#### Steps to Reproduce / Code Snippets

![](https://media.giphy.com/media/LqBohJgWbIaabLHs6t/giphy.gif)
```js
import React from 'react'
import { GiftedChat } from 'react-native-gifted-chat'

class Example extends React.Component {
  state = {
    messages: [],
  }

  componentWillMount() {
    this.setState({
      messages: [
        {
          _id: 1,
          text: 'Hello developer',
          createdAt: new Date(),
          user: {
            _id: 2,
            name: 'React Native',
            avatar: 'https://placeimg.com/140/140/any',
          },
        },
      ],
    })
  }

  onSend(messages = []) {
    this.setState(previousState => ({
      messages: GiftedChat.append(previousState.messages, messages),
    }))
  }

  render() {
    return (
      <GiftedChat
        messages={this.state.messages}
        onSend={messages => this.onSend(messages)}
        user={{
          _id: 1,
        }}
      />
    )
  }
}
```

#### Expected Results

Keyboard shouldn't dismiss.

#### Additional Information

* Nodejs version: 10.4.1
* React version: 16.8.3
* React Native version: 0.59.9
* react-native-gifted-chat version: 0.9.11
* Platform(s) (iOS, Android, or both?): iOS
* TypeScript version: none

**Comment by mihikap2** [comment]
I have the same issue

**Comment by jigaroza287** [comment]
Still facing this issue for iOS, anybody found any solution?

**Comment by hassanQureshi22** [comment]
I am also facing this issue

**Comment by evan-klemen-cleo** [comment]
Since its been a few months, I am also having this issue.

**Comment by hassanQureshi22** [comment]
use prop isKeyboardInternallyHandled to false

**Comment by evan-klemen-cleo** [comment]
> use prop isKeyboardInternallyHandled to false

Thanks for the suggestion. Seems when I set it to false my InputToolbar does not float above the keyboard and becomes obstructed. I tried wrapping in a `<KeyboardAvoidingView>`and it's positioned above the keyboard but the keyboard still dismisses on send :/

**Comment by fukemy** [comment]
please make sure root app does not contain safeareaview or keyboardavoidingview
