### ISSUE TITLE
Have two different events when you tap the Avatar, like press and long press

### ISSUE THREAD

**Issue by LG1710** [FaridSafi/react-native-gifted-chat#1301]
Could you implement long press on the Avatar so that you can have two different events when you tap the Avatar (like see profile or ban profile) ?

Is this possible in the state of things ?...

#### Steps to Reproduce / Code Snippets

Press Avatar

#### Expected Results

Have two different events when you tap the Avatar, like press and long press

#### Additional Information

* Nodejs version: 10.13.0
* React version: 16.8.3
* React Native version: 0.59.4
* react-native-gifted-chat version: 0.9.6
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: [FILL THIS OUT]

**Comment by walidvb** [comment]
In the meantime, you can use `renderAvatar `(source [here](https://github.com/FaridSafi/react-native-gifted-chat/blob/3a9adfee50c240adebeb007a4326637f5fb19749/src/Message.tsx#L141)).

Or maybe [this PR](https://github.com/FaridSafi/react-native-gifted-chat/pull/1322) will be merged, or you can check the commit

**Comment by walidvb** [comment]
thanks @xcarpentier for merging should we close this? Or wait until a release is made?
