### ISSUE TITLE
Android - When Text input is focused, and Action gets clicked, it takes two taps to actually click the icon. (First tap closes keyboard, second actually selects the action)

### ISSUE THREAD

**Issue by nadav2051** [FaridSafi/react-native-gifted-chat#1302]
#### Issue Description

Android - When Text input is focused, and Action gets clicked, it takes two taps to actually click the icon. First tap closes keyboard, second actually selects the action.

#### Steps to Reproduce / Code Snippets

1. Render custom action sheet.
2. Focus TextInput so that the Keyboard will open.
3. While the keyboard is opened, press the action icon.
4. Try selecting an action, my experience is that I have to click twice, first click will dismiss they keyboard, and the second one will execute the action.

#### Expected Results
Keyboard will dismiss as soon as I press the action icon, and return if I cancel it (This is the behavior I'm seeing on iOS).

Or just dismiss the keyboard on the Action button press. (I'll probably work around the issue that way, but I think it's a minor bug of this great library which should be addressed.

#### Additional Information

* Nodejs version: v11.6.0
* React version: 16.8.6
* React Native version: 0.59.3
* react-native-gifted-chat version: 0.9.11
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: (Where do I look for this?)

**Comment by NSNJRGL** [comment]
same here

**Comment by hypesol** [comment]
any solution of this issue?

**Comment by zhu-xiaowei** [comment]
This issue still persists at the end of 2024
