### ISSUE TITLE
Move prop-types to dependencies instead of peerDependencies?

### ISSUE THREAD

**Issue by GollyJer** [FaridSafi/react-native-gifted-chat#1305]
I noticed react-native-gifted-chat expects prop-types as a peer but I'm using Typescript.

Facebook recommends prop-types be installed as a dependency (and not peerDep) for apps and libraries.
https://github.com/facebook/prop-types#how-to-depend-on-this-package

All the best, 💪
Jeremy

**Comment by xcarpentier** [comment]
Hi @GollyJer!
Thanks for this notice, I will do it.

**Comment by xcarpentier** [comment]
fixed c2df2f7
