### ISSUE TITLE
[Bug] timeTextStyle has no effect

### ISSUE THREAD

**Issue by kesha-antonov** [FaridSafi/react-native-gifted-chat#1308]
#### Issue Description

This PR https://github.com/FaridSafi/react-native-gifted-chat/pull/942/files added prop `timeTextStyle`
But I cannot see this code in master: https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/Time.tsx
Though prop `timeTextStyle` is there but not used. Why?

I had to add this:
```
function renderTime(props) {
        return (
            <Time
                {...props}
                textStyle={{
                    left: {
                        color: '#fff',
                    },
                }}
            />
        )
    }
```
instead of `timeTextStyle` in `renderBubble`

**Comment by xcarpentier** [comment]
Will be fixed here: #1284

**Comment by kesha-antonov** [comment]
Nice!

**Comment by graphee-gabriel** [comment]
Any idea when this version will be released :-) ?
