### ISSUE TITLE
Tapping on the status bar scrolls to most recent messages

### ISSUE THREAD

**Issue by mmckinley8** [FaridSafi/react-native-gifted-chat#1314]
#### Issue Description

On iOS, when tapping the status bar, the expected behavior is to scroll to the top of the scroll view. When I do this it scrolls to the most recent message, which is the opposite of iMessage or any other messaging platform

#### Steps to Reproduce / Code Snippets

Tap on the nav bar

#### Expected Results

Should scroll to top of messages

#### Additional Information

* Nodejs version: 12.5.0
* React version: 16.8.6
* React Native version: 0.59.6
* react-native-gifted-chat version: 0.7.3
* Platform(s) (iOS, Android, or both?):  Both

**Comment by xcarpentier** [comment]
Try to use `inverted={false}`
Next version will fix some issue with inverted.

**Comment by mmckinley8** [comment]
While `inverted={false}` does scroll to the top on nav bar press, it also inverts the messages and starts scrolled to the top on initial render. The load earlier messages button is now at the bottom...not a valid solution

**Comment by xcarpentier** [comment]
Yes I know.
Please try this version: [0.10.0-beta.web.10](https://github.com/FaridSafi/react-native-gifted-chat/pull/1284)

**Comment by garymartin87** [comment]
Any workaround to do this ?
