### ISSUE TITLE
Unable to input GIFs from Google Keyboard

### ISSUE THREAD

**Issue by reidkersey** [FaridSafi/react-native-gifted-chat#1318]
#### Issue Description

When user tries to insert a GIF, they get the message 'app_name doesn't support image insertion here'

#### Steps to Reproduce / Code Snippets

Gifted chat example with no other modifications, running on android with Google Keyboard. Use the keyboard to attempt to insert a GIF.

#### Expected Results

Developer should have some way to receive the selected GIF, and chose to deal with it how they deal with pictures etc. (or just have the GIF pop into the message box like Google Messager)

#### Additional Information

* Nodejs version: 11.8.0
* React version: 16.8.3
* React Native version: 0.59.9
* react-native-gifted-chat version: 0.9.11
* Platform(s) (iOS, Android, or both?): Android, iOS untested
* TypeScript version: 3.5.3

**Comment by oromis300** [comment]
Hi, same here. We want to integrate the possibility to send gif via the keyboard.
Do you have any idea how we can do that?

**Comment by ede-sous** [comment]
Hello,

I have the same issue.
Did you found any solution for this?

**Comment by ThemNumbers** [comment]
You need to add listener for ForegroundSharing, i solve this problem

**Comment by bakerac4** [comment]
@ThemNumbers could you expand on your solution?

**Comment by filipef101** [comment]
@ThemNumbers What is that?

**Comment by brkastner** [comment]
I was able to get this working by doing the following:
1. Enable support for rendering gifs in native android project ([rn docs](https://reactnative.dev/docs/0.46/image.html#gif-and-webp-support-on-android))
2. Install [react-native-image-keyboard](https://github.com/Gustash/react-native-image-keyboard) (based on an [open pr](https://github.com/facebook/react-native/pull/26088))
3. Create a callback to extract the local uri for the selected gif:
```tsx
type OnImageChangeCallback = (event: { nativeEvent: { uri: string } }) => void;
const onImageChange: OnImageChangeCallback = ({nativeEvent}) => {
    const {uri} = nativeEvent;
    // upload gif using local uri to somewhere publicly accessible (eg. firebase storage)
    // send a new message with message.image = <publicDownloadUrl>
}
```
4. Override composer using `renderComposer` to connect the callback
```tsx
const renderComposer = props => <Composer {...props} textInputProps={{onImageChange}} />;
return <GiftedChat renderComposer={renderComposer} />
````
5. Send some gifs! 
![tenor_gif186717120405782897](https://user-images.githubusercontent.com/880291/83931990-5a7e8d00-a765-11ea-8dae-5dfdf6edf7a0.gif)
