### ISSUE TITLE
Keyboard automatically got dismissed when clicked the Send button (iOS)

### ISSUE THREAD

**Issue by asong4211** [FaridSafi/react-native-gifted-chat#1321]
#### Issue Description
On iOS, when clicking on the "Send" button, the keyboard automatically dismissed and one would have to click on the "Send" button again in order to send the message.

This behavior happened when I wrote my own custom renderSend method.

This is similar to the issue #358 but I tried putting `keyboardShouldPersistTaps="always"` for the Gifted component as well as the view that wrapped GiftedChat but it doesn't seem to work

#### Steps to Reproduce / Code Snippets
```
renderSend(props) {
      return (
        <View style={{backgroundColor:"gray"}}>
            <Send
              {...props} >
            <View style={{justifyContent:"center", alignItems:"center", paddingHorizontal: 10}}>
              <Ionicons name="md-send" size={30} color="blue" />

            </View>
            </Send>
        </View>
      );
    }
```
#### Expected Results

Expect the keyboard to persist and the user can keep sending more message.

#### Additional Information

* Nodejs version: v10.16.0
* React version: 16.8.6
* React Native version: 0.59.8
* react-native-gifted-chat version: ^0.9.11
* Platform(s) (iOS, Android, or both?): iOS

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31052716/61313769-bee8d480-a7c0-11e9-8cbd-b626f821f83e.gif)

**Comment by r1ckyrockz** [comment]
Duplicate https://github.com/FaridSafi/react-native-gifted-chat/issues/1300?
