### ISSUE TITLE
"this" not working in onLongPress?

### ISSUE THREAD

**Issue by pierroo** [FaridSafi/react-native-gifted-chat#1323]
#### Issue Description

When using onLongPress, any "this.function()" leads to error, with this being undefined.

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

When adding new options to actionSheet, I want to call functions based on the index picked.
As of now, only clipboard seems to be working.

#### Additional Information

* Nodejs version: 10.15.3
* React version: 16.5.0
* React Native version: 0.57.1
* react-native-gifted-chat version: 0.7.2
* Platform(s) (iOS, Android, or both?): Both
* TypeScript version: [FILL THIS OUT]

**Comment by vkkan** [comment]
<GiftedChat
   your options
   onLongPress={(ctx, currentMessage) => this.yourfunction(ctx, currentMessage)}
/>

you can use this way , it works

**Comment by pierroo** [comment]
Thank you vkkan, you are right: I had to bind the function onLongPress so that "this" could be called; otherwise it would not work as a regular fonction.

Case closed, thanks again!
