### ISSUE TITLE
onLongPress on images?

### ISSUE THREAD

**Issue by pierroo** [FaridSafi/react-native-gifted-chat#1329]
#### Issue Description

There is no onLongPress event on Images messages as of now.

#### Expected Results

I would like an onLongPress not only on text messages, but also on image.
Simple tap should open the image, but onLongPress could trigger different events.

I saw the potential duplicate #577, but unfortunately the fix was not merged with the project, and I really don't want to customize the node_modules.
Is there any way to have it implemented; or any plans for it to be merged?

#### Additional Information

Nodejs version: 10.15.3
React version: 16.5.0
React Native version: 0.57.1
react-native-gifted-chat version: 0.7.2
Platform(s) (iOS, Android, or both?): Both

**Comment by pierroo** [comment]
And if this really isn't possible; 

Is there a way to send to lightBoxProps the context / currentMessage props?

Just like the current onLongPress function has context / currentMessage, is it possible to get the same from inside the lightBoxProps?

**Comment by obendevski** [comment]
Hey @pierroo, any luck with this?
