### ISSUE TITLE
scrollToBottomStyle prop never get used in the source code

### ISSUE THREAD

**Issue by Ariavm95** [FaridSafi/react-native-gifted-chat#1343]
#### Issue Description

Reading the code, I found out the scrollToBottomStyle prop never got used in the code; so, setting the scrollToButton style using this prop is useless.

**Comment by kevinyoubrio** [comment]
yep it should be added...it was never used in the source code.

**Comment by GollyJer** [comment]
I just ran into this as well. Thought I was going crazy. 😜

The whole `scrollToBottom` customization is inconsistent with the rest of the codebase. It seems there should be a `renderScrollToBottom` prop that replaces the entire component.

Right now, the `scrollToBottomComponent` prop only allows the replacement of the text inside the grey circle.

**Comment by msqar** [comment]
Guys, i created this PR to solve that. I hope it gets merged soon. I also fixed some little visual glitch whenever using a custom icon, it was cutting my icon in half due to an unnecessary padding.
https://github.com/FaridSafi/react-native-gifted-chat/pull/1387
