### ISSUE TITLE
I lose my avatar when will send have more then one message.

### ISSUE THREAD

**Issue by spock504** [FaridSafi/react-native-gifted-chat#1353]
#### Issue Description
![image](https://user-images.githubusercontent.com/36986341/62758077-e412ef00-baaf-11e9-854b-40e95db7c6f5.png)

#### Steps to Reproduce / Code Snippets
I set props with 
`user={{
                  _id: 1,
                  avatar: 'https://c-ssl.duitang.com/uploads/item/201904/25/20190425192608_KfZRL.thumb.700_0.jpeg',
                }}
                showUserAvatar={true}`
send more then one message.

#### Expected Results

Every message will show avatar image.

* Nodejs version: 10.15.3
* React version: 16.8.3,
* React Native version: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz，
* react-native-gifted-chat version: 0.9.11
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: [FILL THIS OUT]

Thanks.

**Comment by nadav2051** [comment]
Hi, that's the default behavior if I'm not mistaken.

Have you looked at those Gifted Chat props?
**showUserAvatar (Bool)** - Whether to render an avatar for the current user; default is false, only show avatars for other users
**showAvatarForEveryMessage (Bool)** - When false, avatars will only be displayed when a consecutive message is from the same user on the same day; default is false

**Comment by spock504** [comment]
ok.It resolved. Thanks

**Comment by spock504** [comment]
> Hi, that's the default behavior if I'm not mistaken.
> 
> Have you looked at those Gifted Chat props?
> **showUserAvatar (Bool)** - Whether to render an avatar for the current user; default is false, only show avatars for other users
> **showAvatarForEveryMessage (Bool)** - When false, avatars will only be displayed when a consecutive message is from the same user on the same day; default is false

ok.It resolved. Thanks
