### ISSUE TITLE
one-to-one chat example?

### ISSUE THREAD

**Issue by msqar** [FaridSafi/react-native-gifted-chat#1357]
I can't seem to understand on how to create a one-to-one chat as in Whatsapp based on the examples that are provided.
The main _id is the message Id which is fine, then a user object is passed that only contains and shows the sender message data ... but what about the target Id? Can i just modify the message object by adding a targetId?

```
 var message =
        {
            _id: Utils.createUID(3), // message ID
            name: 'Testing', // Why is there a name in here??
            text: this.state.message,
            createdAt: new Date(),
            user: {
                _id: 1, // user who sends it
                name: this.props.chatData.name,
                avatar: 'https://placeimg.com/140/140/any',
                _targetid: 2 // or here?
            },
            target: {
                _id: 2 // the one who receives
            }
        }
```

The idea is to have a chat like in Whatsapp where first you have all the chats in a list, then tap on each swipeRow in order to take you to the messages with that specific person. I will NOT support group chat since chats will be completely private to 1:1 relation.

Can anyone help me, please?

**Comment by Pvybhav** [comment]
please check https://github.com/FaridSafi/react-native-gifted-chat/issues/572

**Comment by msqar** [comment]
@Pvybhav thanks! you're right!
