### ISSUE TITLE
How to send an image message only ? (without sending a text as well)

### ISSUE THREAD

**Issue by blazk0** [FaridSafi/react-native-gifted-chat#1366]
#### Issue Description

I simply want to send an image without typing any text ?
I am using react-native-image-picker and i currently can send an image with a text , but what if i want to send an image only ?
I tried alwaysShowSend and try to send but nothing happens unless the text field is not empty
The docs are very vague on this ...

#### Steps to Reproduce / Code Snippets
``` javascript
  <GiftedChat
        messages={friendMsgs}
        onSend={messages => this.onSend(messages, this.state.image)}
        user={{
          _id: user && user.id,
          name: user && user.firstName,
          avatar: user && user.profilemage
        }}
        text={this.state.text}
        alwaysShowSend={
          this.state.text ? true : false || this.state.image ? true : false
        }
        onInputTextChanged={text => this.setState({ text })}
        renderLoading={() => <Loading />}
        onLoadEarlier={this.loadMessages.bind(this, userParams)}
        isLoadingEarlier={loading}
        isAnimated
        renderAvatarOnTop
        loadEarlier={friendMsgs.length >= 20}
        scrollToBottom
        scrollToBottomComponent={() => (
          <Ionic name='ios-arrow-round-down' size={30} color='#000' />
        )}
        extraData={this.state}
        renderBubble={props => {
          const color = props.currentMessage.read ? '#0084ff' : '#389bff';
          return (
            <Bubble
              {...props}
              wrapperStyle={{ right: { backgroundColor: color } }}
            />
          );
        }}
        renderActions={() => (
          <Feather
            style={styles.uploadImage}
            onPress={this.uploadImage}
            name='image'
            size={30}
            color='#000'
          />
        )}
      />


  onSend(messages = [], image) {
    const { socket, user, navigation } = this.props;
    const { friendMsgs } = this.props.history;

    const receiver = navigation.getParam('user');

    if (socket && socket.readyState === 1) {
      const msg = {
        ...messages[0],
        image
      };

      const sendMsg = GiftedChat.append(friendMsgs, msg);

      const data = {
        senderId: user && user.id,
        receiverType: 'user',
        messageType: 'text',
        receiverId: receiver.id,
        read: false,
        content: messages[0].text
      };

      this.props.sendMsg(data, sendMsg);
    }
  }
```

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* React version: 16.8.3
* React Native version: 0.59.9
* react-native-gifted-chat version: 0.9.11
* Platform(s) (iOS, Android, or both?): both

**Comment by blazk0** [comment]
So i did alittle workaround , I am using react native image picker , when the image is selected and text is empty , i simply fill the text with an empty space .
```
this.setState({ text: ' ' });
```
That way the onSend function works and i can send the image only without any text.

**Comment by charles-goode** [comment]
This doesn't seem to work anymore because GC ignores trailing whitespace. So it decides there's no text, and the view for the image becomes 0 height and 0 width. For the time being, when adding an image to an empty message, I add 'Image' to the text.

**Comment by lorenz068** [comment]
Same problem here

**Comment by anwersolangi** [comment]
Any update on this issue? working around on this issue since a day, still didn't find any solution.

**Comment by charles-goode** [comment]
Haven't tested this but I think 
```
renderSend={(props) => <Send {...props} disabled={this.customDisabled()} />}
alwaysShowSend={true}
```
Should work, where custom disabled is false when image is attached

**Comment by anwersolangi** [comment]
> Haven't tested this but I think
> 
> ```
> renderSend={(props) => <Send {...props} disabled={this.customDisabled()} />}
> alwaysShowSend={true}
> ```
> 
> Should work, where custom disabled is false when image is attached

The onSend function is not invoking if the text field is empty

**Comment by charles-goode** [comment]
Ok true. Then this should work right?
```
renderSend={({onSend, text, sendButtonProps, ...props}) => <Send {...props} sendButtonProps={{...sendButtonProps, onPress: () => this.customOnPress(text, onSend)}} />}
alwaysShowSend={true}
```

where `customOnPress` replaces this in Send.tsx:
```
handleOnPress = () => {
    const { text, onSend } = this.props
    if (text && onSend) {
      onSend({ text: text.trim() } as Partial<TMessage>, true)
    }
  }
```

**Comment by anwersolangi** [comment]
> Ok true. Then this should work right?
> 
> ```
> renderSend={({onSend, text, sendButtonProps, ...props}) => <Send {...props} sendButtonProps={{...sendButtonProps, onPress: () => this.customOnPress(text, onSend)}} />}
> alwaysShowSend={true}
> ```
> 
> where `customOnPress` replaces this in Send.tsx:
> 
> ```
> handleOnPress = () => {
>     const { text, onSend } = this.props
>     if (text && onSend) {
>       onSend({ text: text.trim() } as Partial<TMessage>, true)
>     }
>   }
> ```
> 
> And maybe also include the `disabled` stuff from my previous post if that's at all relevant.

Thanks Alot Man! it really save my day......

**Comment by adnaan2328** [comment]
Hey

**Comment by wahas-mughal** [comment]
You can simply bypass this by using this workaround

  ```
  text={(this.state.recordingUri && "Audio") ||
          (this.state.image && "Image")
    }
```
You can give empty string if you want.
