### ISSUE TITLE
snack demo link not working 

### ISSUE THREAD

**Issue by siddharthshah3030** [FaridSafi/react-native-gifted-chat#1369]
#### Issue Description

snack demo link not working in ios and Android both 

#### Steps to Reproduce / Code Snippets

open the demo link of snack in browser
https://snack.expo.io/@xcarpentier/gifted-chat

#### Expected Results

a functional and working example of react-native-gifted-chat

#### Additional Information

screen shot of snack device
![download](https://user-images.githubusercontent.com/35419948/63634445-2aea1280-c674-11e9-8379-552cd90f0ce4.png)

**Comment by seriiix** [comment]
It's also outdated
