### ISSUE TITLE
Can not select candidate text with an Asia language keyboard on iOS

### ISSUE THREAD

**Issue by xxvvii** [FaridSafi/react-native-gifted-chat#137]
I'm working on a project with Asia language keyboard support
When I type some "composed words", the input candidate box just flashing instead of showing the candidates. I've tried both Chinese and Japanese keyboard but no luck.

I think it's an issue caused by onChangeText and following code in GiftedMessenger.js: 
```
   value={this.state.text}
```
The onChangeText is called every time while user is typing, a new state of text will set back: 
```
  onChangeText(text) {
    this.setState({
      text,
      disabled: text.trim().length <= 0
    });

    this.props.onChangeText(text);
  }
```
That could cause the above issue, so I need some workaround to fix it.

**Comment by dogecrypto** [comment]
This maybe not solved yet.

**Comment by dogecrypto** [comment]
and it looks like react-native bug lul.

https://github.com/facebook/react-native/issues/18403

**Comment by 15914038396** [comment]
RN 0.54.4 inputText Asia language not working 
open Custominput.js add code
constructor(props) {
  super(props);
  this.state = {
    text: '',
  };
}
shouldComponentUpdate(nextProps,nextState){
  if(Platform.OS === 'ios'){
    if(this.props.text !== nextState.text){ //nickname为所要获得的TextInput输入值，
      return false;
    }
  }
  return true;
};


that can work
