### ISSUE TITLE
Functional component examples

### ISSUE THREAD

**Issue by orome** [FaridSafi/react-native-gifted-chat#1371]
#### Issue Description

There are no functional component examples here. All examples use classes, which [are tricky to adapt](https://stackoverflow.com/q/57648128/656912) due to the reliance on callbacks.

#### Additional Information

* Nodejs version: 12.9.0
* React version: 16.8.6
* React Native version: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz
* react-native-gifted-chat version: 0.9.11
* Platform(s) (iOS, Android, or both?): Expo/iOS
* TypeScript version: 3.5.3

**Comment by Alenius** [comment]
Here is a basic example:

`
import React, { useState } from 'react';
import { GiftedChat } from 'react-native-gifted-chat';

const Example = () => {
  const [messages, setMessages] = useState([
    {
      _id: 1,
      text: 'Hello developer',
      createdAt: new Date(),
      user: { _id: 2, name: 'Name' },
    },
  ]);

  const onSend = (newMessage = []) => {
    setMessages(GiftedChat.append(messages, newMessage));
  };

  return (
    <GiftedChat
      messages={messages}
      onSend={newMessage => onSend(newMessage)}
      user={{
        _id: 1,
      }}
    />
  );
};

export default Example;
`

**Comment by Alenius** [comment]
Here is a basic working example with the useState-hook

```
import React, { useState } from 'react';
import { GiftedChat } from 'react-native-gifted-chat';

const Example = () => {
  const [messages, setMessages] = useState([
    {
      _id: 1,
      text: 'Hello developer',
      createdAt: new Date(),
      user: { _id: 2, name: 'Name' },
    },
  ]);

  const onSend = (newMessage = []) => {
    setMessages(GiftedChat.append(messages, newMessage));
  };

  return (
    <GiftedChat
      messages={messages}
      onSend={newMessage => onSend(newMessage)}
      user={{
        _id: 1,
      }}
    />
  );
};

export default Example;
```

**Comment by robertvorthman** [comment]
@orome 
It appears the `append` method of GiftedChat concatenates the newMessage to the initial messages so they are not wiped out.  Here is another hooks example using the spread operator to concatenate the newMessages.  The onSend callback is memoized with useCallback.

```js
const ChatRoom = (props) => {

    const [messages, setMessages] = useState([
        {
            _id: 1,
            text: 'Hello developer',
            createdAt: new Date(),
            user: {
                _id: 2,
                name: 'React Native',
                avatar: 'https://placeimg.com/140/140/any',
            },
        },
    ])

    const onSend = useCallback((newMessages) => {
        setMessages(prevMessages => [...newMessages, ...prevMessages])
    }, [])

    return <GiftedChat
            messages={messages}
            onSend={newMessages => onSend(newMessages)}
            user={{
                _id: 1,
            }}
        />
}
```

**Comment by vinhdothe93** [comment]
> Here is a basic working example with the useState-hook
> 
> ```
> import React, { useState } from 'react';
> import { GiftedChat } from 'react-native-gifted-chat';
> 
> const Example = () => {
>   const [messages, setMessages] = useState([
>     {
>       _id: 1,
>       text: 'Hello developer',
>       createdAt: new Date(),
>       user: { _id: 2, name: 'Name' },
>     },
>   ]);
> 
>   const onSend = (newMessage = []) => {
>     setMessages(GiftedChat.append(messages, newMessage));
>   };
> 
>   return (
>     <GiftedChat
>       messages={messages}
>       onSend={newMessage => onSend(newMessage)}
>       user={{
>         _id: 1,
>       }}
>     />
>   );
> };
> 
> export default Example;
> ```



> Here is a basic working example with the useState-hook
> 
> ```
> import React, { useState } from 'react';
> import { GiftedChat } from 'react-native-gifted-chat';
> 
> const Example = () => {
>   const [messages, setMessages] = useState([
>     {
>       _id: 1,
>       text: 'Hello developer',
>       createdAt: new Date(),
>       user: { _id: 2, name: 'Name' },
>     },
>   ]);
> 
>   const onSend = (newMessage = []) => {
>     setMessages(GiftedChat.append(messages, newMessage));
>   };
> 
>   return (
>     <GiftedChat
>       messages={messages}
>       onSend={newMessage => onSend(newMessage)}
>       user={{
>         _id: 1,
>       }}
>     />
>   );
> };
> 
> export default Example;
> ```

Thanks a lot.
