### ISSUE TITLE
Warning: componentWillReceiveProps is deprecated and will be removed in the next major version

### ISSUE THREAD

**Issue by msqar** [FaridSafi/react-native-gifted-chat#1375]
#### Issue Description
I'm using latest gifted-chat and RN 0.60.4, and it keeps throwing these warnings on console. Even though i could disable them, it would be nice to fix this for the future.

These are the list of warnings i'm getting:

```
Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.

Please update the following components: GiftedChat

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks

Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

Please update the following components: GiftedChat

Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

Please update the following components: MessageContainer

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

#### Steps to Reproduce / Code Snippets
Just add gifted-chat in RN 0.60.4

#### Expected Results
There shouldn't be any warnings.

#### Additional Information

* React version: 16.8.6
* React Native version: 0.60.4
* react-native-gifted-chat version: 
* Platform(s) (iOS, Android, or both?): 0.9.11

**Comment by dev14823** [comment]
I am getting the warning.

    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-gifted-chat": "^0.9.11",
