### ISSUE TITLE
New message is appended to the last message in inputtext

### ISSUE THREAD

**Issue by faustoct** [FaridSafi/react-native-gifted-chat#1377]
#### Issue Description

When type the message for the second time on android. It appends the new message in last message sent. Seems kind of buffer not cleared after message sent.

#### Steps to Reproduce / Code Snippets

````
<GiftedChat
          messages={this.state.messages}
          onSend={messages => this.onSend(messages)}
          showUserAvatar={true}
          user={data}
          listViewProps={{
            onEndReached: this.onEndReached
          }}
        />
````

#### Expected Results

No append previous message

#### Additional Information

* Nodejs version: 11.10.1
* React version: 16.6.3
* React Native version: 0.58.6
* react-native-gifted-chat version: 0.7.3
* Platform(s) (iOS, Android, or both?): Android

**Comment by meowmon** [comment]
same problem :< it appends in last word of last message 
"react": "^16.8.6",
"react-native": "^0.59.9",
"react-native-gifted-chat": "^0.7.2",
Platform(s) (iOS, Android, or both?): Android

**Comment by meowmon** [comment]
Found the problem, it's because of auto correct on device. But when i change autoCorrect to false in textInputProps, nothing happen.

**Comment by faustoct** [comment]
@meowmon any fix? I'm gonna try > https://github.com/FaridSafi/react-native-gifted-chat/issues/767

**Comment by faustoct** [comment]
it solved my problem https://github.com/FaridSafi/react-native-gifted-chat/issues/767#issuecomment-409610967

**Comment by faustoct** [comment]
@meowmon it solved my problem https://github.com/FaridSafi/react-native-gifted-chat/issues/767#issuecomment-409610967

**Comment by hnrqsss** [comment]
I'm still with this issue, i was try everything here , autocorrect, cleartext, block input when sending, but i still with this problem.
RN 59.8 GIfted-chat 0.9.6.
