### ISSUE TITLE
Re-rendering updated component

### ISSUE THREAD

**Issue by conservo-spyce** [FaridSafi/react-native-gifted-chat#1378]
I have an audio component called MessageAudio. Initially **audio** props is set to the local file uri and everything is working as expected. Whenever the audio file is sent, it will be uploaded to the server and returns a new uri of the file and I've reset the audio props to the latest server uri but the component is not re-rendering. 

**Code Snippet:** 

When uploading to server:
let messages = [{
              _id : new Date().getTime() / 1000 | 0,
              createdAt : new Date(),
              msg_status : 0,
              url : response.uri,
              text : '',
              messageType : "audio",
              file_format : fileFormat,
              file_size : response.fileSize,
              file_name : fileName,
              audio: response.uri, //local file URI
              uploadProgress: '',
              user : {
                _id : global.MY_UID
              }
            }];

After file uploaded to server:
messages[0].audio = serverResponse.uri;

The uri doesn't change unless I go back to the previous layout and re-enter. I want it to automatically re-render the component. I know that shouldUpdateMessages / extraData props should do the trick but there is no proper documentation on how to re-render the data. Please help me out.

**Comment by jerearaujo03** [comment]
Did you solved it?

**Comment by kenkotch** [comment]
`shouldUpdateMessage` works like `shouldComponentUpdate`
```
shouldComponentUpdate={(props, nextProps) => {
  return props === nextProps
  // add logic here. return bool
}
```

**Comment by fukemy** [comment]
no https://github.com/FaridSafi/react-native-gifted-chat/issues/1148
