### ISSUE TITLE
v0.2.0 preview

### ISSUE THREAD

**Issue by FaridSafi** [FaridSafi/react-native-gifted-chat#138]
Hi guys,
A new major release is coming, completely rewrote from scratch. You can take a look at the branch 0.2.x https://github.com/FaridSafi/react-native-gifted-messenger/tree/v0.2.x/GiftedMessengerExample

New features:
- customizable components using `renderMessage`, `renderComposer`, `renderAvatar` props
- default `Message` component with built-in Photo/Location views
- default `Composer` component with built-in Photo/Location sharing
- multiline `textInput`
- listview replaced by react-native-invertible-scroll-view (performance still good for long messages list)
- `maxHeight` is calculated automatically
- better management of auto scrolling
- less boilerplate to run minimal example

![simulator screen shot 13 jun 2016 13 29 11](https://cloud.githubusercontent.com/assets/388375/16006010/e091b64e-316a-11e6-919c-8cb9481fc3c2.png)

**Comment by hsvlz** [comment]
Hi Farid,

amazing work, and looking forward to it! Do you think you could also integrate the windowed listview mechanism https://github.com/sghiassy/react-native-sglistview ?

This would improve memory and performance.

Cheers,
Hsvlz

**Comment by dozoisch** [comment]
Awesome work! Looking forward for it.

**Comment by FaridSafi** [comment]
@hsvlz I never tried sglistview but I'm satisfied with `removeClippedSubviews` prop of ScrollView which already offers good performance for long lists

**Comment by ncnlinh** [comment]
This is awesome. Are the current PRs going to be merged in for 1.0 or are we just skipping all of them?

**Comment by yanghuxiao** [comment]
good job!

**Comment by cmdillon** [comment]
fantastic! will it also support sending audio messages?

**Comment by FaridSafi** [comment]
React-native-gifted-chat is released (new name of this component)

@ncnlinh We skip the PRs
@cmdillon Audio requires native modules so it's not supported by default. You can plug easily your implementation in the new release
