### ISSUE TITLE
Cannot access renderMessageVideo prop

### ISSUE THREAD

**Issue by Umair-Asif** [FaridSafi/react-native-gifted-chat#1381]
#### Issue Description
i don't have renderMessageVideo prop available on Gifted Chat.
i am using Gifted Chat version 0.9.11.
i guess it is related to this issue.
https://github.com/FaridSafi/react-native-gifted-chat/issues/1380

**Comment by EdisonDevadoss** [comment]
I also facing the same error could not access renderMessageVideo. 
Please, anybody help me.

**Comment by Joshandrews43** [comment]
Can this be reopened?
