### ISSUE TITLE
scrollToBottom's custom scrollToBottomStyles not working

### ISSUE THREAD

**Issue by msqar** [FaridSafi/react-native-gifted-chat#1386]
#### Issue Description
This property is not working and after digging in the files, there is no this.props.scrollToBottomStyles in the container styling. Only the default one.

Shouldn't this be like this? Or i'm misunderstanding it?

```
renderScrollToBottomWrapper() {
    return (
      <View style={[styles.scrollToBottomStyle, this.props.scrollToBottomStyle]}>
        <TouchableOpacity
          onPress={this.scrollToBottom}
          hitSlop={{ top: 5, left: 5, right: 5, bottom: 5 }}
        >
          {this.renderScrollBottomComponent()}
        </TouchableOpacity>
      </View>
    )
  }
```

**Comment by msqar** [comment]
Created this PR to solve this. https://github.com/FaridSafi/react-native-gifted-chat/pull/1387

**Comment by IWTBCAdeveloper** [comment]
1+

**Comment by msqar** [comment]
@IWTBCAdeveloper still waiting for this to be merged. Nice to see more people interested in this.

**Comment by IWTBCAdeveloper** [comment]
Please merge the PR. I'm very urgent

**Comment by msqar** [comment]
@IWTBCAdeveloper this has been merged now, but now we have to wait for the next release.
