### ISSUE TITLE
Getting "INVALID DATE" if device or emulator not in "debug remotely" mode

### ISSUE THREAD

**Issue by medmo7** [FaridSafi/react-native-gifted-chat#1389]
#### Issue Description
This is the first time i use this great library, and when i debug on chrome the dates are good. 
if i'm not debugging remotely all dates of messages become "INVALID DATE"

#### Steps to Reproduce / Code Snippets
run app without debugging remotely
I use this function to format messages i get from api to be in the library format:
```
formatOneMessage(message) {
    const receiver = this.props.navigation.getParam("receiver");
    const receiverName = receiver.Name;
    const receiverLastName = receiver.lastName;
    const formatedDate = Util.formatDate(message.creation_date)
    const FormatedMessage = {
      _id: message.id,
      text: message.content,
      createdAt: new Date(formatedDate),
      user: {
        _id: message.sender_id,
        name: receiverName + " " + receiverLastName,
        avatar: "https://placeimg.com/140/140/any"
      }
    };

    return FormatedMessage;
  }
```

#### Expected Results
good dates 

#### Additional Information

* Nodejs version: [12.9.0]
* React version: [16.8.6]
* React Native version: [0.60.3]
* react-native-gifted-chat version: [0.9.11]
* Platform(s) (iOS, Android, or both?): [ANDROID]

**Comment by Dearkano** [comment]
same issue here

**Comment by medmo7** [comment]
I used moment.js to resolve this issue.

**Comment by MhamedRamadan10** [comment]
@medmo7 
how you get solve this by using moment?

**Comment by joshudev** [comment]
+1

**Comment by TomDowling** [comment]
I was able to fix this with moment.js as well, I imported the package and then used the standard
`moment().format()`

https://momentjs.com/

**Comment by medmo7** [comment]
Here is how i used moment.js to resolve this issue:
```javascript
 formatOneMessage(message) {
    const receiverName = this.props.navigation.getParam("receiverName");
    const modifiedDate = Util.formatDate(message.creation_date);
    const formatedDate = moment(modifiedDate, "MM-DD-YYYY HH:mm:ss");

    const FormatedMessage = {
      _id: message.id,
      text: message.content,
      createdAt: formatedDate,
      user: {
        _id: message.sender_id,
        name: receiverName,
        avatar: "https://placeimg.com/140/140/any"
      }
    };

    return FormatedMessage;
  }
```
