### ISSUE TITLE
How to retract keyboard for TabBarIOS apps?

### ISSUE THREAD

**Issue by schmoove** [FaridSafi/react-native-gifted-chat#139]
This may be due to a gap in my RN knowledge, rather than a bug with the component, but if you are running it in a TabBarIOS Navigator, how do you retract the keyboard to show the TabBar items again?

I seem to be stuck here:

![simulator screen shot 13 06 2016 1 52 38 pm](https://cloud.githubusercontent.com/assets/1321541/16022717/1ff05bc6-316e-11e6-9d22-5d182f8767e5.png)

Any suggestions would be appreciated!

**Comment by paulbao** [comment]
`https://github.com/FaridSafi/react-native-gifted-messenger/pull/144`
