### ISSUE TITLE
I need to customize composer with my own styles

### ISSUE THREAD

**Issue by pacheco7** [FaridSafi/react-native-gifted-chat#1390]
#### Issue Description

I need to customize the style of the composer. I tried to change the layout using the renderComposer, for some customizations it's done good, but I need to change the border and his position. Has another way to do that?

#### Steps to Reproduce / Code Snippets
My renderComposer:

  renderComposer(props) {
    return (
      <TextInput
 //       {...props}
        placeholder={"Escreva sua mensagem"}
        style={{ paddingLeft: 60, paddingBottom: 60 }}
      />
    )
  }

#### Expected Results

![Captura de Tela 2019-09-10 às 13 23 17](https://user-images.githubusercontent.com/13923231/64631867-630c8780-d3ce-11e9-9dad-424740540d3d.png)

#### Additional Information

* Nodejs version: 10.16.0
* React version: 16.8.3
* React Native version: 16.8.6
* react-native-gifted-chat version: 0.9.11
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: not using

**Comment by msqar** [comment]
You can change the entire bottom layout by using renderInputToolbar() function.

In my case i have something like this:

```
    renderInputToolbar(props) {
        return ( <ChatInputBox
                {...props}
                chatData={ this.props.chatData }
                onSend={ this.onSend }
                onTyping={ this.props.onHandleTyping }
                containerStyle={ styles.inputToolbarStyle }
            />);
    }
```

Created my own ChatInputBox component with the TextInput, buttons for camera and for Send, etc... try that out.

**Comment by pacheco7** [comment]
> You can change the entire bottom layout by using renderInputToolbar() function.
> 
> In my case i have something like this:
> 
> ```
>     renderInputToolbar(props) {
>         return ( <ChatInputBox
>                 {...props}
>                 chatData={ this.props.chatData }
>                 onSend={ this.onSend }
>                 onTyping={ this.props.onHandleTyping }
>                 containerStyle={ styles.inputToolbarStyle }
>             />);
>     }
> ```
> 
> Created my own ChatInputBox component with the TextInput, buttons for camera and for Send, etc... try that out.

About the "chatData", it's a collection of inputed text from TextInput (Can be stated data) ? About the other props, it's a props from another renders? E.g.: renderSend.

**Comment by msqar** [comment]
Don't worry about the chatData, is how I implemented stuff, all you see there is how I send data back and forth about what the user is typing. I handle the onTyping, and the only thing i use from the chatData is the user's ID that i'm writing to. Now that i see it, i should remove it, because i can grab that from the parent :) so you dont need any chatData there. Only a handler when the user types in from the children's input.

**Comment by pacheco7** [comment]
My issue are solved by the tips of @msqar

**Comment by msqar** [comment]
@pacheco7 glad it worked, man :)
