### ISSUE TITLE
Menu not showing

### ISSUE THREAD

**Issue by marcobustillo** [FaridSafi/react-native-gifted-chat#1393]
#### Issue Description

Bubble Chat message onLongPress does not open the menu when the value is a image.
#### Steps to Reproduce / Code Snippets
Step:1: send a image
Step2: longpress over the message not the chat bubble

#### Expected Results
Will open the menu

#### Additional Information

* Nodejs version: v12.6.0
* React version: v16.8.3
* React Native version: v33.0.0
* react-native-gifted-chat version: 0.6.0
* Platform(s) (iOS, Android, or both?): Both
* TypeScript version: Not using

**Comment by BoKKeR** [comment]
could you post code ?
