### ISSUE TITLE
renderInputToolbar and renderSend UI styling.

### ISSUE THREAD

**Issue by jjmcmillan** [FaridSafi/react-native-gifted-chat#1394]
**Issue Description**

Hello! I would like to style giftedchat for my app but I'm having difficulties. I can't seem to get the inputToolbar or renderSend styling to work. See image for explanation: 

![Screenshot_20190913-195228](https://user-images.githubusercontent.com/18230292/64887279-31125400-d660-11e9-9823-bf8dae17aea5.jpg)

I have tried to use bottomOffset but this doesn't seem to be having any effect. I have no idea what is causing the border around the send Icon.

**Steps to Reproduce / Code Snippets**

GiftedChat Code:

```
return (
  <View style={{flex: 1}}>
    <GiftedChat
      renderSend={this.renderSend}
      renderInputToolbar={this.renderInputToolbar}
      messages={this.state.messages}
      onSend={messages => this.onSend(messages)}
      user={{_id: 1,}} 
      renderMessage={this.renderMessage}
      alwaysShowSend={true}
    />
  </View>
)
```

InputToolbar Code:

```
renderInputToolbar (props) {
        return <InputToolbar {...props} containerStyle={styles.inputToolbar} />
      }
```

InputToolbar Styling:
```
inputToolbar: {
        marginLeft: 15,
        marginRight: 15,
        marginBottom: 10,
        borderWidth: 0.5,
        borderColor: 'grey',
        borderRadius: 25
    }
```

renderSend Code:

```
renderSend(props) {
        return (
          <Send {...props}>
              <Icon
                name="send"
                style={styles.sendIcon}
              />
          </Send>
        );
      }
```

sendIcon Styling:

```
    sendIcon: {
        fontSize: 25,
        color: '#3A97F9'
    },
```

**Expected Results**

No border around send Icon. The bottom message should not be obstructed by the input toolbar.

#### Additional Information

* Nodejs version: "12.6.0"
* React version: "16.8.6"
* React Native version: "0.60.4"
* react-native-gifted-chat version: "^0.9.11"
* Platform(s) (iOS, Android, or both?): Both

**Comment by Hammza1** [comment]
@jjmcmillan  Please How did you make the background color white ??

**Comment by ShoaibVirk008** [comment]
> **Issue Description**
> 
> Hello! I would like to style giftedchat for my app but I'm having difficulties. I can't seem to get the inputToolbar or renderSend styling to work. See image for explanation:
> 
> ![Screenshot_20190913-195228](https://user-images.githubusercontent.com/18230292/64887279-31125400-d660-11e9-9823-bf8dae17aea5.jpg)
> 
> I have tried to use bottomOffset but this doesn't seem to be having any effect. I have no idea what is causing the border around the send Icon.
> 
> **Steps to Reproduce / Code Snippets**
> 
> GiftedChat Code:
> 
> ```
> return (
>   <View style={{flex: 1}}>
>     <GiftedChat
>       renderSend={this.renderSend}
>       renderInputToolbar={this.renderInputToolbar}
>       messages={this.state.messages}
>       onSend={messages => this.onSend(messages)}
>       user={{_id: 1,}} 
>       renderMessage={this.renderMessage}
>       alwaysShowSend={true}
>     />
>   </View>
> )
> ```
> 
> InputToolbar Code:
> 
> ```
> renderInputToolbar (props) {
>         return <InputToolbar {...props} containerStyle={styles.inputToolbar} />
>       }
> ```
> 
> InputToolbar Styling:
> 
> ```
> inputToolbar: {
>         marginLeft: 15,
>         marginRight: 15,
>         marginBottom: 10,
>         borderWidth: 0.5,
>         borderColor: 'grey',
>         borderRadius: 25
>     }
> ```
> 
> renderSend Code:
> 
> ```
> renderSend(props) {
>         return (
>           <Send {...props}>
>               <Icon
>                 name="send"
>                 style={styles.sendIcon}
>               />
>           </Send>
>         );
>       }
> ```
> 
> sendIcon Styling:
> 
> ```
>     sendIcon: {
>         fontSize: 25,
>         color: '#3A97F9'
>     },
> ```
> 
> **Expected Results**
> 
> No border around send Icon. The bottom message should not be obstructed by the input toolbar.
> 
> #### Additional Information
> * Nodejs version: "12.6.0"
> * React version: "16.8.6"
> * React Native version: "0.60.4"
> * react-native-gifted-chat version: "^0.9.11"
> * Platform(s) (iOS, Android, or both?): Both

Its happening because of the default border width of send container so simply do that.

renderSend(props) {
        return (
            <Send
                {...props}
                containerStyle={{ borderWidth: 0 }}
            >
                <View style={{ marginRight: 5, marginBottom: 12.5 }}>
                    <Icon name="arrow-up" type="material-community" size={totalSize(3)} color={colors.appColor1} />
                </View>
            </Send>
        );
    }

**Comment by Noorulhuda682** [comment]
Please leave a proper customizing input footer to make using easy the gifted  textInput with left and right buttons

**Comment by henryngchengway** [comment]
This is my solution to remove the border that covers the send icon. This help solved my problem which is same as yours. The problem gifted chat does not provide the Send component props. In order to read all of the props. In windows, ctrl + left click on the <Send/> component. For mac, cmd + left click. Hope it solves your problem too

renderSend(props) {
        return (
          <Send {...props} containerStyle={{ borderWidth: 0}} >
              <Icon
                name="send"
                style={styles.sendIcon}
              />
          </Send>
        );
      }

**Comment by deyanskiq** [comment]
<img width="333" alt="Screenshot 2020-05-05 at 15 08 11" src="https://user-images.githubusercontent.com/11162576/81064363-3ddf0300-8ee2-11ea-9b38-a3d6c69eb2f1.png">

Any ideas how properly set `height` to `inputToolbar` ?

**Comment by gouravgoel** [comment]
![Capture](https://user-images.githubusercontent.com/67143979/118271138-87dbcb00-b4de-11eb-85f5-c4c091ebfe0f.JPG)
Please help how can I reduce the distance between top of the keyboard and the input toolbar

**Comment by DannyelPina** [comment]
Any idea of how can I do this 
![image](https://user-images.githubusercontent.com/25164242/229944712-abd404bf-7930-4b83-9cb7-bfa1f68ef3f1.png)
