### ISSUE TITLE
Flow typedefs

### ISSUE THREAD

**Issue by amiralies** [FaridSafi/react-native-gifted-chat#1395]
is there any plan to add flow definitions?

**Comment by xcarpentier** [comment]
We are using typescript...

**Comment by amiralies** [comment]
and we don't, in our team.
it would be nice if you include flow type defintions, maybe i can send a PR

**Comment by xcarpentier** [comment]
Yes, you can create PR, I was a flow user before TypeScript became the standard.

But maybe you can investigate this solution: https://github.com/flow-typed/flow-typed/ ?

**Comment by amiralies** [comment]
including definitions in this repo adds out of the box support for flow users, i think its better to include them here if we can pay the cost of maintain

**Comment by amiralies** [comment]
@xcarpentier where do you think we should put definitions?
i think since this project is written in ts naming a directory `type-defs` is not suitable, something like `flow-defs` , `flowtype-defs` would be better

**Comment by kesha-antonov** [comment]
@amiralies Hi
Is flow a still a thing to you?
I think everybody is on the typescript nowadays

**Comment by kesha-antonov** [comment]
Just compare downloads:
flow 278k and dropping https://www.npmjs.com/package/flow-bin?activeTab=versions
ts 52.7mil and rising https://www.npmjs.com/package/typescript
