### ISSUE TITLE
Quick reply in react native gifted chat not showing

### ISSUE THREAD

**Issue by sumeetchand5** [FaridSafi/react-native-gifted-chat#1396]
#### Issue Description

Please follow this link to find details of the issue im facing.  
https://stackoverflow.com/questions/57949335/quick-reply-in-react-native-gifted-chat-not-showing

#### Additional Information

* Nodejs version: 10.16.0
* React version: 16.8.3
* React Native version: 0.57.1
* react-native-gifted-chat version: 0.7.2
* Platform(s) (iOS, Android, or both?): Android

**Comment by JanOwiesniak** [comment]
I have a similar issue. This is how my message looks like.

```
    const randomId = "123"

    const message = {
      _id: randomId,
      text: 'accept incoming video call 🤙',
      createdAt: new Date(),
      quickReplies: {
        type: 'radio', // or 'checkbox',
        keepIt: true,
        values: [
          {
            title: '😋 Yes',
            value: 'yes',
          },
          {
            title: '😞 Nope. What?',
            value: 'no',
          },
        ],
      },
      user: {
        _id: this.state.profile.profileId,
        name: this.state.profile.fullName,
        avatar: this.state.profile.imageUrl,
      },
    }
```

Quick replies are not showing up in the messenger. Are they supposed to or do i have to implement one of these methods as well?

> onQuickReply (Function) - Callback when sending a quick reply (to backend server)
> renderQuickReplies (Function) - Custom all quick reply view
> quickReplyStyle (StyleProp) - Custom quick reply view style
> renderQuickReplySend (Function) - Custom quick reply send view

**Additional Information**

Nodejs version: 12.8.1
React version: 16.8.6
React Native version: 0.60.5
react-native-gifted-chat version: 0.9.11
Platform(s) (iOS, Android, or both?): Android & iOS

**Comment by danieljohnmorris** [comment]
Any answer to this?

**Comment by fukemy** [comment]
any answer for this?

**Comment by fukemy** [comment]
ok just define keepIt: true then it's will show
