### ISSUE TITLE
Reduce bundle size: Use DayJS rather than MomentJS

### ISSUE THREAD

**Issue by mayconmesquita** [FaridSafi/react-native-gifted-chat#1397]
So, this component is using MomentJS.

No functional problem here, but this is increasing the bundle size so much. Today, we can use a smaller alternative with the same modern API - the DayJS!

![moment-size](https://user-images.githubusercontent.com/46308804/65056527-61e7d700-d947-11e9-9e38-163c6ccb3d7e.png)
[ **react-native-bundle-visualizer** to view the moment size ]

I have a local fork working nicely (+ locales) with DayJS.

Can i pull request?

Thanks!

**Comment by xcarpentier** [comment]
Yes PR are welcome ;)

**Comment by mayconmesquita** [comment]
Thanks! I will prepare the PR!

**Comment by xcarpentier** [comment]
Any news?

**Comment by xcarpentier** [comment]
@mayconmesquita Still nothing ;) ?

**Comment by xcarpentier** [comment]
Hi @mayconmesquita 
I did it, 7c2b566
Can you look at it and let me know your thought?

**Comment by mayconmesquita** [comment]
Hi @xcarpentier! Sorry for the huge delay, this PR was pretty low on my set of priorities.

Your DayJS implementation is fine! I'm think is ready to merge.

Did you test already?
