### ISSUE TITLE
Version 0.9.11 not re-rendering on messages updating

### ISSUE THREAD

**Issue by kalizi** [FaridSafi/react-native-gifted-chat#1398]
#### Issue Description

I had react-native-gifted-chat v.0.9.11 installed, developed an app that included a chat via some API. During development there was no problems, but when I built release version, the first API call that handled messages fetch didn't update the chat messages view.
First I thought that API call failed for some reason, so I put an Alert, rebuilt everything and got that API call didn't fail. 
So I tried to check for updates with `ncu` and everything was updated.
I finally choose to downgrade react-native-gifted-chat to version 0.9.10, and all worked correctly as in dev mod.

#### Steps to Reproduce / Code Snippets

Messages are fetch in the correct format so I don't need to map them to change keys.

    componentWillMount() {
        this.getCurrentUser().done();
        this.initService().done();
        this.fetchMessages();
    }

    fetchMessages = () => {
        if (this.chatService !== null)
            this.chatService.getChatMessages(
                this.props.navigation.state.params.chatId,
                this.state.nextLink,
                response => {
                    if (response.hasOwnProperty('data') && response.data.length > 0 && response.hasOwnProperty('meta')) {
                        let nextPageLink;
                        let totalPages = +response.meta.pagination.total_pages;
                        let page = +response.meta.pagination.current_page;
                        if (response.meta.pagination.links.hasOwnProperty('next'))
                            nextPageLink = response.meta.pagination.links.next;
                        else
                            nextPageLink = null;

                        this.setState({
                            messages: GiftedChat.append(this.state.messages, response.data),
                            page: page,
                            totalPages: totalPages,
                            nextLink: nextPageLink
                        });
                    }
                },
                error => {
                    console.error(error);
                }
            );
        else
            this.fetchTimer = setTimeout(this.fetchMessages, 150);
    };

    render() {
        const { t } = this.props;
        return (
            <View
                style={styles.container}
                accessible
                accessibilityLabel='main'
            >
                <NavBar>
                    <NavButton onPress={this.closeChat}>
                        <Icon name='chevron-left' onPress={this.closeChat}/>
                    </NavButton>
                    <NavTitle>
                        💬 { this.props.navigation.state.params.otherUser.name }
                    </NavTitle>
                    <NavButton />
                </NavBar>
                <GiftedChat
                    initialText=""
                    placeholder={t('chat.placeholder')}
                    messages={this.state.messages}
                    onSend={this.onSend}
                    user={{
                        _id: this.state.user.id
                    }}

                    alignTop={false}
                    renderUsernameOnMessage={true}
                />
            </View>
        );
    }

#### Expected Results

I expected that in version 0.9.11 messages updated the view triggering a re-render, but didn't. In version 0.9.10 everything worked perfectly.

#### Additional Information

* Nodejs version: 10.16.0
* React version: 16.8.6
* React Native version: 0.60.4
* react-native-gifted-chat version: 0.9.11 **[BUGGED ONE]** --> Replaced with 0.9.10
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: // 
* Babel version: 7.5.5
I'm also using jetifier v.1.6.3

**Comment by xcarpentier** [comment]
should be fixed with the latest version `0.11.0`
