### ISSUE TITLE
Jumpy animation when tapping on 'load earlier messages'

### ISSUE THREAD

**Issue by hsvlz** [FaridSafi/react-native-gifted-chat#140]
Hi,

the _scrollToPreviousPosition =True triggers the scroll down after prepending new messages, but it that the lifecycle is such that the scrollTo only appends after the renderAnimatedView, therefore creating a jumpy animation for a split second.

Is there perhaps a way to freeze the rendering until the scrolling is done?

Otherwise, amazing job.

Cheers,
hsvlz

**Comment by nazywamsiepawel** [comment]
+1, I'm battling the same issue. @hsvlz, did you find any solution?

**Comment by FaridSafi** [comment]
I tried to fix tihs but without success.
Should not be present in upcoming release v0.2.0

**Comment by nazywamsiepawel** [comment]
@FaridSafi Any suggestions on what exactly is causing the issue?

**Comment by FaridSafi** [comment]
Basically the jump appears when the rows are prepended to the top of the listview, then a scroll to previous position is triggered. Couldn't avoid the jump the way the component is written.

Next release is using invertible scroll view so the jump should not appear in case of prepend

**Comment by mtford90** [comment]
@FaridSafi +1 ;)

How far off is that release?

Great work so far mate.
