### ISSUE TITLE
Delay before input activates after sending

### ISSUE THREAD

**Issue by pierroo** [FaridSafi/react-native-gifted-chat#1401]
#### Issue Description

After we type some text and tap the Send button, there is a small delay (1-2s) before we can type again.
Typing fast right after sending will just ignore the characters, and suddenly starts working again.

#### Expected Results

I would like to be able to type right away, without waiting: that is what we are all used to on other chat platforms when typing fast.

#### Additional Information

* Nodejs version: 10.15.3
* React version: 16.8.6
* React Native version: 0.60.5
* react-native-gifted-chat version: 0.9.11
* Platform(s) (iOS, Android, or both?): Android

**Comment by lkm1developer** [comment]
same problem

**Comment by lkm1developer** [comment]
same problem
dirty fix 
replaced all  **this.setIsTypingDisabled(true)**; with **this.setIsTypingDisabled(false)**;
in
**node_modules\react-native-gifted-chat\lib\GiftedChat.js**

**Comment by pierroo** [comment]
> same problem
> dirty fix
> replaced all **this.setIsTypingDisabled(true)**; with **this.setIsTypingDisabled(false)**;
> in
> **node_modules\react-native-gifted-chat\lib\GiftedChat.js**

That sounds promising; did you see any issue after changing this line?

Do you know why this exists in the first place?

**Comment by lkm1developer** [comment]
I am not using all features of gifted chat, m using only chat list and message input box , so application not showing any adverse effect , might be possible if someone uses all features of gifted chat

**Comment by mchewry** [comment]
same issue 2.8.1
