### ISSUE TITLE
How to calculate the location of a message？

### ISSUE THREAD

**Issue by Gardeniaxch** [FaridSafi/react-native-gifted-chat#1411]
#### Issue Description

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by RediaUa** [comment]
Any progress? How can we mark messages as read on scroll event? I've seen a lot of issues about getting coords of message, but no answers :(

**Comment by skizzo** [comment]
+1

**Comment by thipoeta** [comment]
+1
