### ISSUE TITLE
react-native-video not removed as a dependency in v0.10.0

### ISSUE THREAD

**Issue by danilobuerger** [FaridSafi/react-native-gifted-chat#1412]
#### Issue Description

The `README.md` states:

```
Since v0.10.0 removed react-native-video dependency.
```

However, the `package.json` still includes `react-native-video` as a dependency.

This was added back in by @xcarpentier at https://github.com/FaridSafi/react-native-gifted-chat/commit/df01060be113f7d93123b66503364a8e600033cd

#### Steps to Reproduce / Code Snippets

Install `react-native-gifted-chat`

#### Expected Results

Expected: `react-native-video` is not installed.
Actual: `react-native-video` is installed.

#### Additional Information

* react-native-gifted-chat version: 0.10.0

**Comment by xcarpentier** [comment]
Hi @danilobuerger,
`react-native-video` also was in `0.9.1`
Do you find any good reason to remove it?

**Comment by xcarpentier** [comment]
BTW I removed it from readme

**Comment by danilobuerger** [comment]
@xcarpentier For this specific case the reason is that the README.md should reflect the actual code. As a developer, I would expect that if the README.md says its removed, that its actually removed. 

But for more general reasons (other than 0.10.0 specifically) see #1207

**Comment by xcarpentier** [comment]
Ok, as you can see here it's now in `peerDependency`, so that will fix such a case.
https://github.com/FaridSafi/react-native-gifted-chat/blob/28114c3def965d2f68df6d29aed74eed6e5967c1/package.json#L110-L117

**Comment by danilobuerger** [comment]
@xcarpentier No, it won't as it is *also* listed as a `dependency` and will therefor get installed automatically:

https://github.com/FaridSafi/react-native-gifted-chat/blob/28114c3def965d2f68df6d29aed74eed6e5967c1/package.json#L107

**Comment by xcarpentier** [comment]
ok, you mean not installed at all. `v0.10.1` fixes it
