### ISSUE TITLE
MessageContainer scrollToBottomStyle is missing in props

### ISSUE THREAD

**Issue by amiralies** [FaridSafi/react-native-gifted-chat#1416]
#### Issue Description

Build is failing due missing prop
`MessageContainer.tsx:308:35`
`scrollToBottomStyle`

#### Steps to Reproduce / Code Snippets

`yarn build`

**Comment by msqar** [comment]
@xcarpentier hey Xavier, any idea about when the next gifted-chat version is going to be released including all these fixes? Thanks!

**Comment by xcarpentier** [comment]
It should be already, you don't see?
Please open a new issue if find any bug on that, thanks ;)
