### ISSUE TITLE
Gifted chat version 0.10.1 no longer builds due to dependency on react-native-video

### ISSUE THREAD

**Issue by halstjas** [FaridSafi/react-native-gifted-chat#1418]
I need to use a version  of React native gifted chat which has removed the use of the react deprecated life cycle events i.e. ComponentWillReceiveProps

#### Steps to Reproduce / Code Snippets
yarn upgrade react-native-gifted-chat@latest
react-native run-android

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `react-native-video` from `C:\Users\jason\Coding\b2b2\sgB2b\node_modules\react-native-gifted-chat\lib\MessageVideo.js`: Module `react-native-video` does not exist in the Haste module map

The error persists after removing node_modules and performing a complete yarn install.

#### Expected Results

Successful build  

#### Additional Information

* Nodejs version: n/a
* React version: 16.8.6
* React Native version: "0.60.4"
* react-native-gifted-chat version: 0.10.1
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: n/a

**Comment by xcarpentier** [comment]
Are you using `video` in your chat?

**Comment by halstjas** [comment]
I don’t currently support video in my chat. 
I attempted to install and build the react-native-video in but the latest version. 5.0.2 hangs in the build process and timeout. Seems we have created a dependency to an unstable library which now prevents the library react-gifted-chat from building

The release comment in “0.10.1” states that this dependency has been  removed, so this is very confusing

**Comment by xcarpentier** [comment]
You have to set the version you need for your RN version.

**Comment by xcarpentier** [comment]
Can you test this version? `0.10.2-0`
(as said you have to set your rn-video version or maybe not, let me know)

**Comment by xcarpentier** [comment]
should be fixed with version `0.11.0`
