### ISSUE TITLE
Any way to load chat messages immediately?

### ISSUE THREAD

**Issue by GollyJer** [FaridSafi/react-native-gifted-chat#1419]
Looking through the code, it appears gifted chat will always render a loading state (either null, or the passed in loading component) even if the message data being sent in has not changed. It looks like it needs to do some calculating of view heights.

Is this correct? If so, there's no way to load the message content immediately, correct?

If not, how can we get a GiftedChat screen to load immediately when the message history is immediately available?

Thanks for your time! 👍
Jeremy

**Comment by antoinefotso** [comment]
use loadEarlier={true}
and onLoadEarlier={function}

**Comment by GollyJer** [comment]
We've implemented loadEarlier. It doesn't help with this is though.

We ended up patching gifted chat to remove the need to calculate the screen size on each load. Instead we rely completely on flexbox allowing the cached data to load immediately.

**Comment by msqar** [comment]
@antoinefotso that's not the purpose of those props... that's the handler to load previous messages along with the callback function ...

**Comment by Hirbod** [comment]
@GollyJer is your patch available somewhere? Could you provide a PR or something? @xcarpentier also would like to know if there is a non-hacky solution

**Comment by GollyJer** [comment]
Hi. @Hirbod. I just made something available so you can give it a try.

We used [Patch Package](https://github.com/ds300/patch-package#readme).

You will need to 
- Install patch package.
- Create a folder at the root of your project called `patches`.
- Add [this file](https://gist.github.com/GollyJer/9a53bc2b3346b14e811bf0fe5a663ddb) into the `patches` folder.
- Run the `patch-package` command to apply the code.

If anything goes wrong you can just wipe `node_modules`. Read up on Patch Package for all the details of how it works.

Good luck,
Jeremy

**Comment by Hirbod** [comment]
@GollyJer, thank you very much. Also for showing me this patch package method. Interesting. Which version did you use for patching? 

I’ll give it a try tomorrow.

**Comment by GollyJer** [comment]
@Hirbod. You're very welcome. 👍

The patched version is always in the name of the generated patch.
![image](https://user-images.githubusercontent.com/689204/67814706-fe7eb800-fa61-11e9-9db3-ca66bc4da884.png)

**Comment by abdi4** [comment]
Is there a fix for this yet? @FaridSafi
