### ISSUE TITLE
Bubbles are not working properly with styles

### ISSUE THREAD

**Issue by iamnzrv** [FaridSafi/react-native-gifted-chat#1421]
#### Issue Description

I am trying to change bubble background and text color according to appearance which user set in redux store. The problem is when user changes appearance, only background changes but not text style.
#### Steps to Reproduce / Code Snippets

renderBubble code:

```javascript
  renderBubble(props) {
    return (<Bubble {...props}
      wrapperStyle={{
        left: colors[this.props.appearance].leftMessageBackground,
        right: {
          backgroundColor: '#c8e6c9'
        }
      }}
      textStyle={{
        left: colors[this.props.appearance].leftMessageTextStyle,
        right: {
          color: 'black'
        }
      }} />)
  }
```
componentWillReceiveProps code(here I'm trying to re-render all the bubbles to change their styles):

```javascript
  componentWillReceiveProps(nextProps) {
    if (this.props.appearance != nextProps.appearance) {
      this.setState({
        messages: GiftedChat.append([], this.state.messages),
      });
    }
  }
```

#### Expected Results

Message bubble changes according to style.

**Comment by xcarpentier** [comment]
Can you please show me how you pass this renderBubble props?
