### ISSUE TITLE
Cannot read property cache of undefined (0.10.1)

### ISSUE THREAD

**Issue by R8Manzo** [FaridSafi/react-native-gifted-chat#1423]
Cant run the app due to error with that module from the project, react-native-parsed-text.

Installing the app in React Native .60.

![Simulator Screen Shot - iPhone 8 - 2019-09-27 at 12 20 18](https://user-images.githubusercontent.com/19478245/65788665-2dcb9d80-e121-11e9-9724-f4be0936d34b.png)

**Comment by acidhax** [comment]
Also getting this error

**Comment by linux08** [comment]
@R8Manzo did you find a fix yet ?

**Comment by linux08** [comment]
@acidhax  did you find a fix for this yet ?

**Comment by linux08** [comment]
I fixed it by commenting out `api.cache(true);` present in 
`node_modules/react-native-gifted-chat/react-native-parsed-text/babel.config.js`
i.e
```
module.exports = function(api) {
  // api.cache(true);
  return {
    presets: ['babel-preset-expo'],
  };
};
```

**Comment by aymkin** [comment]
> I fixed it by commenting out `api.cache(true);` present in
> `node_modules/react-native-gifted-chat/react-native-parsed-text/babel.config.js`

in my case those steps are taken:

- go to node_modules/react-native-parsed-text/babel.config.js
- coommetnt second line // api.cache(true);
- close Metro Bundler
- run yarn run ios, you may need to run it twice // "ios": "react-native run-ios"

**Comment by johnobrien8642** [comment]
> I fixed it by commenting out `api.cache(true);` present in `node_modules/react-native-gifted-chat/react-native-parsed-text/babel.config.js` i.e
> 
> ```
> module.exports = function(api) {
>   // api.cache(true);
>   return {
>     presets: ['babel-preset-expo'],
>   };
> };
> ```

This is not a "fix".
