### ISSUE TITLE
0.10.2 breaks ExpoKit compilation

### ISSUE THREAD

**Issue by shamilovtim** [FaridSafi/react-native-gifted-chat#1432]
*Downgraded back to 0.10.0.

switch to react-native-gifted-chat": "^0.10.0" and your expokit app should compile.

**Comment by shamilovtim** [comment]
Please see here for what is most likely the breaking change:

https://github.com/FaridSafi/react-native-gifted-chat/commit/1593c2b55525e247ed87ea2c5823bfd7a0548169

**Comment by xcarpentier** [comment]
No you don’t have to downgrade, you just have to declare expo-av yourself.
Please refer warnings on installation or simply peerDependecies you have to declare yourself.

**Comment by shamilovtim** [comment]
The instructions say no expo and the error thrown is for expo-av, which the readme says specifically isn't being used. Adding react-native-video doesn't fix the issue. Not sure I'm understanding

**Comment by xcarpentier** [comment]
Does it fix your issue if you declare expo-av and react-native-video into your dependencies?

**Comment by alexandrius** [comment]
I too experience the problem. I don't want to add the library which I'm not using. I'm thinking to just fork this lib if we are forced to add the expo-av

**Comment by alexandrius** [comment]
@xcarpentier the readme mentions "No expo, no web, just native" and I'm using Expo. I get this error while I should not I guess

**Comment by xcarpentier** [comment]
Ok
I think I will remove both: expo-av and react-native-video tomorrow on a new release. Those are really annoying and we will be able to use customView to provide video support

**Comment by alexandrius** [comment]
@xcarpentier I agree completely. This is amazing library but video is very specific.
