### ISSUE TITLE
Pros has been updated, but the interface is not rendered

### ISSUE THREAD

**Issue by classyuan** [FaridSafi/react-native-gifted-chat#1435]
[####]([url]( @ #url)) Issue Description
I had a rendering problem.Pros has been updated, but the interface is not rendered。
You have to slide components to render

![gifhome_308x640_10s](https://user-images.githubusercontent.com/2560670/66082240-4e21af00-e59c-11e9-910b-4962c5803c2d.gif)

[FILL THIS OUT]

```
<FlatList
          data={messages}
          initialNumToRender={100}
          refreshing={true}
          renderItem={this.renderItem}
        />
        <GiftedChat
          messages={messages}
          onSend={msg => {
            this.onSend(msg);
          }}
          alwaysShowSend={true}
          showUserAvatar={true}
          showAvatarForEveryMessage={true}
          text={chatValue}
          loadEarlier={true}
          renderLoading={() => {}}
          isAnimated={false}
          onInputTextChanged={text => {
            this.setState({ chatValue: text });
          }}
          user={{
            _id: user.user_id,
            name: user.nickname,
            avatar: user.headPortrait
          }}
          renderAvatarOnTop={true}
         
        />
```
[FILL THIS OUT]

**Comment by audiolion** [comment]
@classyuan this might be related to #1436 if you put a `console.log` in your `node_modules/react-native-gifted-chat/lib/GiftedChat.js` file at https://github.com/FaridSafi/react-native-gifted-chat/blob/3cbadaf07ba683d160b35d6a9c42c2204ce48886/src/GiftedChat.tsx#L410 you can see if the `GiftedChat` component is updating your messages or not, that is where `scrollToBottom` is called. The problem seems to be that after sending your message the `scrollToBottom` is not being called or is simply not working.

**Comment by xcarpentier** [comment]
Why I’m your code example we see a FlatList before GiftedChat?

**Comment by classyuan** [comment]
![image](https://user-images.githubusercontent.com/2560670/66105727-ca44e280-e5ee-11e9-9b6b-8db679ca31e4.png)

I found the reason. Do not use mobx store directly   .This is a low-level mistake.


messages={messages} to messages={messages.slice()}

```
<GiftedChat
          test={test}
          messages={messages.slice()}
          onSend={msg => {
            this.onSend(msg);
          }}
          alwaysShowSend={true}
          showUserAvatar={true}
          showAvatarForEveryMessage={true}
          text={chatValue}
          loadEarlier={true}
          renderLoading={() => {}}
          isAnimated={false}
          onInputTextChanged={text => {
            this.setState({ chatValue: text });
          }}
```

**Comment by xcarpentier** [comment]
So it's fixed now?
