### ISSUE TITLE
Multiple problems with inverted prop's functionality

### ISSUE THREAD

**Issue by charles-goode** [FaridSafi/react-native-gifted-chat#1442]
#### Issue Description

I was trying to implement some emoji reactions in a similar fashion to Facebook's Messenger (it appears above the message being reacted to and over top the message above. This where I begin to run into issues. Due to the render order (order of children within a parent) of the messages (default `inverted={true}`), no matter zIndex/elevation value my selector bubble has, it will appear under the previous message (the one above it). After I found out that the render order was to blame, I tried setting `inverted={false}` and then reversing the order of my messages array (so that the overall order of the messages will be same as before but the order of render will be reversed). This had the intended effect (messages in the same order but now the higher zIndex/elevation view actually covers views under it), BUT that made the messages hug the top (as if I had set the alignToTop prop to true). 

ALSO the borderRadius rounding effect on consecutive messages from the same user is not the same as when inverted=

#### Steps to Reproduce / Code Snippets
`<GiftedChat inverted={false}/>`

#### Expected Results

It's not that I expect toggling `inverted` to simply reorder the messages (essentially just doing messages.reverse()). This is in fact the behavior of the same named prop on FlatList, and admittedly even in this use case, `inverted={false}` likely is intended to do what it does. BUT if `alignToTop={false}` as is the default, I DO expect the content to be aligned to bottom. Since these two props may have conflicting uses, I believe it is best to make `inverted` simply control order of messages and `alignToTop` simply control whether content is aligned to top or bottom. 

As for the borderRadius on consecutive messages from the same user problem, I simply expect for it to behave symmetrically to with `inverted={true}` (the default).

Also as a mild convenience for people with similar use cases, it would be nice if defaults accounted for the render order restrictions on zIndexing. 

#### Additional Information

I fixed the overlapping problem with the following:
` listViewProps={{style: {minHeight: '100%', flexDirection: 'column-reverse'}}}`

So my full solution for preventing the overlapping problem I described is:

`inverted={false}`
`listViewProps={{style: {minHeight: '100%', flexDirection: 'column-reverse'}}}`

In onSend: 
- `this.setState({ messages: GiftedChat.prepend(previousMessages, messages)});` assuming all messages were generated with this rule.
OR
 - Keep `GiftedChat.append` and use `messages={[...this.state.messages].reverse()}`. This is on O(n) call every render so I don't recommend. However if you are migrating your messages to this ordering and never bothered to apply the operation on your back-end, this may be a temporary fix.

Anyway, I'm glad to see this library's author has been active on it recently. 

* Nodejs version: v10.16.1
* React version: 16.8.3
* React Native version: 0.59.8
* react-native-gifted-chat version: ^0.9.11
* Platform(s) (iOS, Android, or both?): Both
* TypeScript version: N/A

**Comment by xcarpentier** [comment]
Hi,
Can you please give a try to the last version?

**Comment by amiralies** [comment]
i'm also facing some issues with this, (though im using `inverted={false}` for testing purpose) seems like that `inverted={false}` is quite unstable. if others confirm we can mention in docs and fix later

**Comment by charles-goode** [comment]
Sorry, I've been away from my project for the last few weeks. I haven't yet tried the new version, but I wanted to mention that I discovered my "fix" doesn't actually work because `flexDirection: 'column-reverse'` prevents scrolling. Without that line though, the initial scroll position is the top of the list instead of the bottom. I will upgrade now and see if that makes it better.

**Comment by charles-goode** [comment]
IT WORKS! Thanks @xcarpentier. I upgraded to 0.11.3. I still need have to use `inverted={false}` and `GiftedChat.prepend(prevMessages, newMessages)` in order to get the right render order, but that's all it takes for it to look the same as default settings. I will close this issue now, but you may want to document  the solution for reordering the render so that zIndex elements behave properly in the chat. I think it could be a common use-case.
