### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by longb1997** [FaridSafi/react-native-gifted-chat#1444]
#### Issue `Description`
I'm trying to install this package, but npm return errors
any helpful?
#### Steps to Reproduce / Code Snippets

```
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/EvanBacon/react-native-parsed-text.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LongNH\AppData\Roaming\npm-cache\_logs\2019-10-07T08_24_55_758Z-debug.log
```

#### Additional Information

* Nodejs version: 10
* React Native version: 0.60
* Platform(s) (iOS, Android, or both?): Android

**Comment by Ticfest** [comment]
I am having the same problem. Only difference is that I am using yarn

**Comment by ashish10211** [comment]
I am facing same issue . 
Node version 10
React Native version : 0.61
Android 
![Capture](https://user-images.githubusercontent.com/22025795/66981129-9b566280-f0fe-11e9-8361-f14b05d5a6c0.PNG)

**Comment by ashish10211** [comment]
I had same issue . Install git and it will download package .

**Comment by Ticfest** [comment]
Thank you @ashish10211  but that didn't work

**Comment by dillonharlessNHRMC** [comment]
@ashish10211 this didn't work for me... Anyone having this issue?

**Comment by prospkarl** [comment]
Use GIT
