### ISSUE TITLE
Loading earlier messages should keep ListView at same scroll position

### ISSUE THREAD

**Issue by alleksa** [FaridSafi/react-native-gifted-chat#1447]
#### Issue Description

After load earlier messages, ListView scroll chat on starting position instead of staying at same scroll position. This bug appear after upgrading from v0.9.11 to v.0.11.0

#### Additional Information

* React Native version: 0.61.1
* react-native-gifted-chat version: v.0.11.0
* Platform(s) (iOS, Android, or both?): both

**Comment by srfaytkn** [comment]
I am seeing this issue too

**Comment by smuxx** [comment]
same issue here

**Comment by antoinefotso** [comment]
i still have this issue .
anyone help?

**Comment by tinni95** [comment]
I still have this issue too

**Comment by AlexanderLevinQU** [comment]
Issue is still here

**Comment by dosapati** [comment]
Still facing the same issue, any suggestions. This is really frustrating for our user base. Need quick help. Please suggest the right fix.

**Comment by henokweldemicael** [comment]
Still facing this issue

**Comment by henokweldemicael** [comment]
> 

We're also facing this issue. Lmk if you were able to find a solution

**Comment by samih-sghier** [comment]
same here

**Comment by sulaiman21** [comment]
I am still facing the auto scroll on prepend earlier messages. Any solution or reference to fix it?
