### ISSUE TITLE
Bubble doesn't rerender

### ISSUE THREAD

**Issue by MamyChow** [FaridSafi/react-native-gifted-chat#1449]
#### Issue Description

Hi everyone,
I want to use sent/received ticks. So i have two function onSend that send new message and watchChat that listen all new message from the server. When i send a message the onSend function update the messages array then when watchChat find the new message i modify the last message with sent:true but the ticks doesn't appear (it appear if i send another new message).
I think it's because bubble doesn't rerender but i don't have solution :(

#### Additional Information

* React version: 16.9.0
* React Native version: 0.61.1
* react-native-gifted-chat version: 0.10.1

**Comment by xcarpentier** [comment]
Use 0.11.0

**Comment by MamyChow** [comment]
Hi, i use now 0.13.0 and the problem appear again.

**Comment by usamamoinakhter** [comment]
Dealing with same issue, any solution?

**Comment by MamyChow** [comment]
@xcarpentier I use 16.1 and bubble doesn't rerender (just the last bubble can rerender)

**Comment by rsoury** [comment]
I was used renderMessage to render my state-dependent UI. This could be a temporary workaround.

**Comment by oleksiikiselov** [comment]
> I used renderMessage to render my state-dependent UI. This could be a temporary workaround.

That helps, thank you 👍 

But fix for bubble is still required.

**Comment by Hosam-hsm** [comment]
Still having the issue on 16.3

**Comment by anhdevit** [comment]
Does anyone have a solution for these issues?

**Comment by fukemy** [comment]
still not resolved with 0.16.3
