### ISSUE TITLE
the inputbox's height is error.

### ISSUE THREAD

**Issue by yanghuxiao** [FaridSafi/react-native-gifted-chat#145]
when i use react native 0.28.0,in android system,the inputbox's height is error when focus on.
![nexus 4 jelly bean screenshot 1](https://cloud.githubusercontent.com/assets/1004110/16327537/b0a0c4ca-3a02-11e6-8f87-044b137e5999.png)

**Comment by yanghuxiao** [comment]
ios is all right
![simulator screen shot 2016 6 24 11 58 09](https://cloud.githubusercontent.com/assets/1004110/16327561/f4e925c8-3a02-11e6-9573-14405ae67047.png)
@FaridSafi

**Comment by K-Leon** [comment]
same for me

**Comment by jazzdevils** [comment]
same for me too

**Comment by aries84ct** [comment]
Same for me:
- LG G2 D802 Android 5.0
- Android emulator 6.0 API 23

**Comment by aries84ct** [comment]
Update: I think I found the problem...
Edit GiftedMessenger.js (inside the module's folder) and simply comment the code inside onKeyboardWillShow(e) method:
`   /* Animated.timing(this.state.height, {
      toValue: this.listViewMaxHeight - e.endCoordinates.height,
      duration: 200,
    }).start(); */`

**Comment by shubhambatra** [comment]
@aries84ct Did you get that working ?

**Comment by aries84ct** [comment]
@shubhambatra Sure, please read my previous post
