### ISSUE TITLE
invariant violation

### ISSUE THREAD

**Issue by rahultatvasoft** [FaridSafi/react-native-gifted-chat#1465]
@xcarpentier getting this error after upgrade react native to 0.60.4

![Simulator Screen Shot - iPhone X - 2019-10-14 at 17 51 10](https://user-images.githubusercontent.com/45203243/66750867-3d7e0c80-eeab-11e9-9cb9-3bb041c013cc.png)

* Nodejs version: [11.10.0]
* React version: [16.8.6]
* React Native version: [0.60.4]
* react-native-gifted-chat version: [0.11.0]
* Platform(s) (iOS, Android, or both?): [ios]

**Comment by xcarpentier** [comment]
Hi,
Are you sure that's related to GiftedChat?
