### ISSUE TITLE
Background color issue

### ISSUE THREAD

**Issue by Hammza1** [FaridSafi/react-native-gifted-chat#1470]
#### Issue Description
I aim to change the background color of the whole GiftedChat View, I have changed the ScrollView background to white by using the `listViewProps`, also I am using a custome `InputToolbar`, the scrollView  background color has been changed but in the very bottom it still as  grey. As shown in the picture (url). 
[https://files.slack.com/files-pri/T2BFN9L5C-FPCP3SATZ/screenshot_20191011_215322_com.sportunity.jpg](url)
#### Steps to Reproduce / Code Snippets

[FILL THIS [OUT]](url)

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: 10.16.3
* React version: 16.6.3
* React Native version: 0.58.6
* react-native-gifted-chat version: 0.7.2
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: [FILL THIS OUT]

**Comment by mvelebit** [comment]
Any clues as to how you managed to fix this?
