### ISSUE TITLE
Chat window automatically scrolls to bottom when prepending messages

### ISSUE THREAD

**Issue by jsochurek** [FaridSafi/react-native-gifted-chat#1474]
#### Issue Description

I have a chat with a lot of messages. To start, I load 20, then use `onEndReachedThreshold` and `onEndReached` to automatically fetch and load more messages when I scroll to the top.  `inverted=true`.  When new messages are loaded using `GiftedChat.prepend`, the chat will then scroll all the way to the bottom of the messages, such that I have to scroll back up to see the messages I just loaded.  Note: this seems to behave properly when `inverted=false`.

#### Steps to Reproduce / Code Snippets

```
<GiftedChat
     messages={this.state.messages}
     onSend={messages => this.onSend(messages)}
     user={{
       _id: this.props.messagingID
     }}
     renderBubble={this.renderBubble}
     renderAvatar={this.renderAvatar}
     onPressAvatar={this.handlePressAvatar}
     renderMessageText={this.renderMessageText}
     keyboardShouldPersistTaps="handled"
     renderSend={this.renderSend}
     renderDay={this.renderDay}
     renderTime={this.renderTime}
     renderInputToolbar={this.renderInputToolbar}
     textInputProps={{
         style: {
              fontFamily: "Raleway-Regular" as "Raleway-Regular",
              flex: 1,
              padding: 8,
              paddingTop: 12,
              minHeight: 44
          }
     }}
     minInputToolbarHeight={44}
     renderLoading={this.renderLoading}
     listViewProps={{
         onEndReached: this.handleLoadEarlier,
         onEndReachedThreshold: 0.5
     }}
   />
```

new messages are added like so:
```
       this.setState(
            previousState => {
                return {
                    messages: isBefore
                        ? GiftedChat.prepend(
                              previousState.messages,
                              newMessages
                          )
                        : GiftedChat.append(previousState.messages, newMessages)
                }
            }
        }
```

#### Expected Results

New messages are added to the top, and the view stays there

#### Additional Information

* Nodejs version: 8.16.0
* React version: 16.8.6
* React Native version: 0.60.4
* react-native-gifted-chat version: 0.11.0
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: 3.0.1

**Comment by jsochurek** [comment]
is this the expected/desired behavior?
https://github.com/FaridSafi/react-native-gifted-chat/issues/88

**Comment by jsochurek** [comment]
i guess may be here
https://github.com/FaridSafi/react-native-gifted-chat/issues/1447
but that hasn't been released to npm yet, has it?

**Comment by jsochurek** [comment]
#1447 does in fact fix it, closing this. sorry!

**Comment by tinni95** [comment]
I am still having this problem, even adding with giftedchat.prepend the scrollview goes to the bottom
