### ISSUE TITLE
ref error when resizing parent view and unmounting

### ISSUE THREAD

**Issue by mxhryvo** [FaridSafi/react-native-gifted-chat#1484]
#### Issue Description

> TypeError: Cannot read property 'scrollToEnd' of null
> scrollToBottom
    MessageContainer.js:91:17

When you resize the view where the FlatList of GiftedChat is in, the onLayout event handler of the flatlist calls this.scrollToBottom:
```
        this.scrollToBottom = (animated = true) => {
            const { inverted } = this.props;
            if (inverted) {
                this.scrollTo({ offset: 0, animated });
            }
            else {
                this.props.forwardRef.current.scrollToEnd({ animated });
            }
        };
```
if inverted = false it calls a function of the forwarded ref and in my case it seems that `this.props.forwardRef.current` is null, as the resizing animation ends with unmounting the Chat and therefore FlatList. So the onLayout call appears after FlatList is unmounted and therefore the ref is null.

I could solve it by adding a check if forwardRef.current is null before using scrollToEnd of forwarded ref:
```
// Temporary fix when unmounted before onLayout is called
if(this.props.forwardRef.current !== null)
this.props.forwardRef.current.scrollToEnd({ animated });
```

Should I do a pull request with this change?

#### Steps to Reproduce / Code Snippets

Resize wrapper view of Gifted Chat with inverted=false e.g. by using panresponder and Animated
and then unmount GiftedChat at the end of animation

#### Expected Results

onLayout of FlatList shouldn't be called when FlatList is already unmounted but when it should check if ref still exists

#### Additional Information

* Nodejs version:  10.15.1
* React version: 16.9.0
* React Native version: 0.61.2
* react-native-gifted-chat version: 0.11.3
* Platform(s) (iOS, Android, or both?): tested on iOS, but probably both
* TypeScript version: not using typescript

**Comment by inzy007** [comment]
Any idea when we expect this fix to be included?

**Comment by barakoles** [comment]
same here..

**Comment by pqminh** [comment]
same

**Comment by minhnguyenit14** [comment]
Same here... dont know what to do :(

**Comment by RatebSeirawan** [comment]
+1

**Comment by dblok-changda** [comment]
+1

**Comment by anmolmalik97** [comment]
Any Updates ?

**Comment by Legi0n1138** [comment]
I'm using this chat as one of the tabs of `react-native-tab-view` and this error is getting triggered spontaneously. 
I patched the package with a fix from the top post and it helps but it would be nice if this was fixed :)

**Comment by decreaseme** [comment]
I'm encountering the same issue where on unmount, the chat is trying to scroll to the end. Can this be fixed?

**Comment by decreaseme** [comment]
Seems like the PR has been merged! https://github.com/FaridSafi/react-native-gifted-chat/pull/1636/files

**Comment by prog-24** [comment]
I am still experiencing this issue.

**Comment by Minasokoni** [comment]
@decreaseme It has been merged but there hasn't been a release since December. So it is still a bug in the current release unfortunately

**Comment by Meph1k** [comment]
@FaridSafi please, release a new version. This is important.

**Comment by Sharqiyem** [comment]
Same here.

**Comment by skizzo** [comment]
+1.

**Comment by WillGoGithub** [comment]
Any Updates ?
