### ISSUE TITLE
Missing TypeScript type definition file

### ISSUE THREAD

**Issue by g2** [FaridSafi/react-native-gifted-chat#1488]
#### Issue Description

When using `react-native-gifted-chat` as a dependency in a TypeScript 3.x project, TypeScript Compiler lists a dozen of type script errors because of a missing type definition file, for instance:
```
Could not find a declaration file for module './types'. '***/node_modules/react-native-gifted-chat/lib/types.js' implicitly has an 'any' type.

import { IMessage } from './types';
```

#### Steps to Reproduce / Code Snippets
1. Add `react-native-gifted-chat` as a project dependency in a TS project
2. Import anything from the `react-native-gifted-chat` package
3. Run TSC, e.g `yarn tsc`

#### Expected Results
There are no TypeErrors errors stemming from the fact that the project is using `react-native-gifted-chat`.

#### Additional Information
* Nodejs version: 12.0.0
* React version: 16.8.6
* React Native version: 0.60.5
* react-native-gifted-chat version: 0.11.3
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: 3.5.3

#### Probable reason:
I think the issue might have been introduced in this line:
https://github.com/FaridSafi/react-native-gifted-chat/commit/03372f37864a8a2470c81a4f56a03cc5e9326702#diff-0fd4ef892d9d4990033701887c2f9bccR24
As this commit removes the `types.d.ts` file from files managed by NPM.

**Comment by xcarpentier** [comment]
Sorry about that
