### ISSUE TITLE
App  don't run after importing gifted chat

### ISSUE THREAD

**Issue by linux08** [FaridSafi/react-native-gifted-chat#1491]
#### Issue Description

App fails after importing gifted chat

#### Steps to Reproduce / Code Snippets

When i import and try to view react-native-gifted-chat ,I get the error below

#### Additional Information

* Nodejs version: 10.16.0
* React version: 16.8.1
* React Native version:0.61.2
* react-native-gifted-chat version:  0.11.3
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: 3.6.4
<img width="325" alt="Screenshot 2019-10-26 at 10 04 59 PM" src="https://user-images.githubusercontent.com/14845904/67625963-00b3fd00-f83d-11e9-9f5d-7a86e2fdc98d.png">

**Comment by linux08** [comment]
I fixed it by commenting out api.cache(true); present in
node_modules/react-native-gifted-chat/react-native-parsed-text/babel.config.js
i.e

module.exports = function(api) {
  // api.cache(true);
  return {
    presets: ['babel-preset-expo'],
  };
};

**Comment by aymkin** [comment]
> I fixed it by commenting out api.cache(true); present in
> node_modules/react-native-gifted-chat/react-native-parsed-text/babel.config.js

in my case those steps are taken:
* go to node_modules/react-native-parsed-text/babel.config.js
* coommetnt second line // api.cache(true);
* close Metro Bundler
* run `yarn run ios`, you may need to run it twice //  "ios": "react-native run-ios"
