### ISSUE TITLE
renderUsernameOnMessage shows "~" in front of user names

### ISSUE THREAD

**Issue by alexstoyanov** [FaridSafi/react-native-gifted-chat#1494]
#### Issue Description

renderUsernameOnMessage shows "~" in front of user names

#### Steps to Reproduce / Code Snippets

using renderUsernameOnMessage={true}

#### Expected Results

renderUsernameOnMessage should not show "~" in front of user names

#### Additional Information

* Nodejs version:11.12.0
* React version: 16.10.2
* React Native version: 0.61.2
* react-native-gifted-chat version: 0.11.2
* Platform(s): both
<img width="505" alt="Screenshot 2019-10-29 at 17 47 47" src="https://user-images.githubusercontent.com/6256431/67784305-3f7fc800-fa74-11e9-8c91-c2aff8a95834.png">
<img width="503" alt="Screenshot 2019-10-29 at 17 48 08" src="https://user-images.githubusercontent.com/6256431/67784337-49a1c680-fa74-11e9-9b9b-545d52296fac.png">

**Comment by pqminh** [comment]
You can custom your Bubble to modify like this.
`renderBubble={props => <Bubble {...props} />}`
