### ISSUE TITLE
footer isn't rendered in empty chat

### ISSUE THREAD

**Issue by c-goettert** [FaridSafi/react-native-gifted-chat#1505]
#### Issue Description

The footer (renderFooter) is only displayed when the chat contains messages. I'd expect it to be rendered when the chat is empty as well. In fact it was working this way in earlier versions of gifted-chat (I stumbled across this issue after upgrading to the latest version).

Using `renderChatFooter` would work, but it's not a really nice option for me because I want the footer to be displayed inside the flatlist.

#### Steps to Reproduce / Code Snippets

Render GiftedChat with empty Messages & renderFooter implementation, e.g.:
```
<GiftedChat
       messages={[]}
       renderFooter={() => <Text>Test</Text>}
/>
```
#### Expected Results
Test-Text is displayed (but it's not, it's only displayed when chat contains at least one message)

#### Additional Information

* React Native version: 0.61.3
* react-native-gifted-chat version: 0.11.0

**Comment by Aakashbist** [comment]
Is there any way we can add attachment icon around textfield. I would like to send an attachment url through chat

**Comment by NiharR27** [comment]
Why dis closed?

**Comment by erdemgonul** [comment]
this is an ongoing issue
