### ISSUE TITLE
Question: Call scroll to bottom programmatically 

### ISSUE THREAD

**Issue by Hirbod** [FaridSafi/react-native-gifted-chat#1509]
Hi,

how can I call scrollToBottom programmatically? The reason why I am asking: when the user scrolled up and sends a new message, it stays at the position. I would like to call a method to scroll down in this case.

**Comment by jerearaujo03** [comment]
+1

**Comment by Hirbod** [comment]
@jerearaujo03 it's

`this.giftedChatRef.scrollToBottom();`

Just set a ref to the GiftedChat component.

**Comment by jerearaujo03** [comment]
I'm getting ref = undefined

**Comment by jerearaujo03** [comment]
Ok, it's working when I send a message (onSend), but I want to call it when the chat render for first time (maybe on componentDidMount or on render)

**Comment by Hirbod** [comment]
If you want to use it on componentDidMount, you will have to use React.createRef.

Add 

this.yourRef = React.createRef(); inside your Class or Class Constructor.
Add 

ref={this.yourRef} to the Gifted Chat component.
On componentDidMount, add this.yourRef.current.scrollToBottom().
If you still get an undefined error, try wrapping a setTimeout of 100ms around it (but it should work)

**Comment by jerearaujo03** [comment]
My idea is to wrap it with setTimeout, but can't access ref, i'm getting this error:
![image](https://user-images.githubusercontent.com/7424471/71105400-44bbe200-219c-11ea-989d-624fd8695c39.png)

**Comment by Hirbod** [comment]
you have to use a arrow function or .bind(this) on your function.

**Comment by jerearaujo03** [comment]
```
    setTimeout(() => {
      this.giftedChat.scrollToBottom();
    }, 1000);
```
Thanks for answering, but not working :/

**Comment by Hirbod** [comment]
As I said, use React.createRef() and call this.giftedChat.current.scrollToBottom(). It is working, as I am also using it. You need to make sure that your component is created on time and maybe dig into some principles of JS

**Comment by jerearaujo03** [comment]
It's working, i forgot the `.current`
Thanks a lot!

**Comment by haeniya** [comment]
If someone tries to do this in the latest version (2.4.0) you can do the following:

```
const chatRef = useRef<FlatList<IMessage> | null>(null);

<GiftedChat
    messageContainerRef={chatRef}
    infiniteScroll
    loadEarlier
    ...
/>

// Scrolling to bottom
chatRef.current?.scrollToOffset({
    offset: 0,
    animated: true
});
```

If you don't have your chat inverted use this:

```
chatRef.current?.scrollToEnd();
```

Hope that helps someone.

**Comment by coderpr0grammer** [comment]
> messageContainerRef={chatRef}

Hey thanks so much for this reply, I tried this but for some reason it does not scroll to my custom chat footer using the `renderFooter` prop. I'm trying to create my own custom typing bubble, but the user has to manually scroll down to see it. Anyone also have this issue?

**Comment by Ahmed-M-Osman1** [comment]
@haeniya Thanks man you saved my job🫡😍

**Comment by c-info** [comment]
> If someone tries to do this in the latest version (2.4.0) you can do the following:
> 
> ```
> const chatRef = useRef<FlatList<IMessage> | null>(null);
> 
> <GiftedChat
>     messageContainerRef={chatRef}
>     infiniteScroll
>     loadEarlier
>     ...
> />
> 
> // Scrolling to bottom
> chatRef.current?.scrollToOffset({
>     offset: 0,
>     animated: true
> });
> ```
> 
> If you don't have your chat inverted use this:
> 
> ```
> chatRef.current?.scrollToEnd();
> ```
> 
> Hope that helps someone.

Seems working fine thanks

**Comment by mochadwi** [comment]
there's no `messageContainerRef` unfortunately on `1.1.1` any other suggestion maybe? seems still cannot upgrade for now
