### ISSUE TITLE
[Typescript] Missing renderMessageVideo in GiftedChatProps

### ISSUE THREAD

**Issue by fri0z** [FaridSafi/react-native-gifted-chat#1510]
#### Issue Description
Missing renderMessageVideo in GiftedChatProps. Because of this typescript swears at the lack of renderMessageVideo props. Because of this typescript swears at the lack of props renderMessageVideo, but in the README it is.

#### Additional Information

* Nodejs version: v10.17.0
* React version: 16.9.0
* React Native version: 0.61.4
* react-native-gifted-chat version: 0.11.2
* TypeScript version: 3.6.4

**Comment by gimwee** [comment]
can someone help to release the merged code to a new version? renderMessageVideo prop is still causing type error in current version (0.16.3)

**Comment by Seamus1989** [comment]
+1
