### ISSUE TITLE
Out-of-the-box Animated Typing Indicator?

### ISSUE THREAD

**Issue by JaredDahlke** [FaridSafi/react-native-gifted-chat#1517]
First of all thank you for this amazing library! 

I have implemented gifted chat as a pure function of global state. I have also implemented a custom 'renderFooter' where I have an animated typing indicator (looks just like iPhone's typing indicator).
The problem is that I have no way of making it slide up and down to indicate typing, it just appears and dissapears. I'm trying to implement it exactly like Iphone where it slides up and down. It's very nice looking. 

Does gifted chat have this? I am surprised if not because it is a fundamental part of a chat screen that most people would love to be able to easily implement out of the box.   I've looked into react-native-slide-up-panel but cannot implement that since I have gifted chat in a pure function. Any tips or pointers here?

**Comment by latoda** [comment]
Muchas gracias

**Comment by shamilovtim** [comment]
You're saying instead of the element appearing and disappearing you want it to animate in and out?  Have you looked into react-native's Animation API? You could add it and submit a pull request

**Comment by JaredDahlke** [comment]
Can you confirm that there is currently no out of the box typing indicator?
And yes I've already built it in my app using  the Animation API. It looks
pretty good but it has a little bit too much margin on it that I'm having
trouble fixing.

**Comment by shamilovtim** [comment]
Yeah there is only the `renderFooter` and no out of the box typing indicator. You could always submit a pull request with yours if you think it's good and you want other people to be able to use it. In that case yours would be the out of the box option

**Comment by shamilovtim** [comment]
@JaredDahlke Could it be possible to share your work? I'd like to provide something similar to what you did as part of the plugin.

**Comment by JaredDahlke** [comment]
@shamilovtim I just emailed it to you!
