### ISSUE TITLE
image base64 encoding not showing inside the popup

### ISSUE THREAD

**Issue by syrakozz** [FaridSafi/react-native-gifted-chat#1519]
#### Issue Description

i receve an image with base64 format, it show correcly during the chat, but when i click on it , it show a black image

#### Steps to Reproduce / Code Snippets

recive base64 image and then click on the image

#### Expected Results

show the image inside the poup
#### Additional Information

* Nodejs version: 10.13.0
* React version: 16.11.0
* React Native version: 0.61.4
* react-native-gifted-chat version: 0.11.3
* Platform(s) (iOS, Android, or both?): ios

**Comment by xcarpentier** [comment]
This is not related to gifted chat but the image viewer package, sorry

**Comment by syrakozz** [comment]
i just download the example file its without a thrid party library
