### ISSUE TITLE
When bubble text font size increased, text does not fit.

### ISSUE THREAD

**Issue by kyhnlbyrk** [FaridSafi/react-native-gifted-chat#1520]
#### Issue Description

When font size increased in the bubble, height of the bubble is not increased with font size. 

#### Steps to Reproduce / Code Snippets

`<GiftedChat
                messages={arr}
                placeholder={this.props.lang.write[this.props.language]}
                onSend={messages => this.onSend(messages)}
                user={{
                  _id: this.props.user.id,
                }}
                locale={this.props.language}
                renderSend={this.renderSend}
                renderActions={this.renderCustomActions}
                renderBubble={props => {
                  return (
                    <Bubble
                      {...props}
                      textStyle={{
                        right: {
                          color: '#fff',
                          fontFamily: 'Roboto',
                          fontSize: 60
                        },
                        left: {
                          color: '#093b60',
                          fontFamily: 'Roboto',
                          fontSize: 60
                        },
                      }}
                      wrapperStyle={{
                        left: {
                          backgroundColor: '#f1f1f1',
                          borderWidth: 1,
                          borderColor: '#093b60',
                          borderBottomLeftRadius: 0,
                          flex: 1
                        },
                        right: {
                          backgroundColor: '#093b60',
                          borderWidth: 2,
                          borderColor: '#62b144',
                          borderBottomRightRadius: 0,
                          flex: 1
                        },
                      }}
                    />
                  );
                }}
              />`
the bubble is not growing with the font size even though I removed the flex.. 

#### Expected Results

wrapper should grow with the font

#### Additional Information

* Nodejs version: 10.16.3
* React version: 16.6.3
* React Native version: 0.59.3
* react-native-gifted-chat version: ^0.4.3
* Platform(s) (iOS, Android, or both?): both
* TypeScript version:  "Not using typescript"

*screen shot made with minHeight increased but the result is the same..
![Screenshot from 2019-11-18 17-59-05](https://user-images.githubusercontent.com/17335770/69063208-28a61300-0a2d-11ea-96e7-0220dd6250d1.png)

**Comment by ZaidAbo** [comment]
Same Here :(

**Comment by tborowy** [comment]
Try use fontSize in renderMessageText function:

```renderMessageText={({currentMessage, ...args}) => {
        return (
        <MessageText
          currentMessage={currentMessage}
          customTextStyle={{fontSize:60, lineHeight: 60 // or more it's depend whats font you use}}
          {...args}
        />
      );
    }}```
