### ISSUE TITLE
Samsung Keyboard, textInputBox covered [Expo: 35.0.0]

### ISSUE THREAD

**Issue by virtualLast** [FaridSafi/react-native-gifted-chat#1521]
#### Issue Description

Samsung s7 Edge, using Samsung Keyboard which comes with the phone. The textInputBox is being hidden when the keyboard becomes active.

At the moment I can still see all the messages in the conversation, scroll through them etc. I am wrapping the `<GiftedChat /> `comp in a `<KeyboardAvoidingView />` after reading another github issue here - didnt solve my issue, putting the `<KeyboardAvoidingView />` **after** the `<GiftedChat />` didnt fix the issue either.
 
#### Steps to Reproduce / Code Snippets
```

renderContent = () => {
    const { messages: stateMessages } = this.state;
    const me = this.getMe();
    return (
      <View style={{ flex: 1 }}>
        <KeyboardAvoidingView style={{ flex: 1 }}>
          <GiftedChat
            showUserAvatar
            scrollToBottom
            messages={stateMessages}
            onSend={messages => this.onSend(messages)}
            user={me}
            bottomOffset={55}
            parsePatterns={this.parsePatterns}
            renderActions={this.renderConversationActions}
            renderCustomView={this.renderCustomView}
            renderBubble={this.renderBubble}
            renderMessageVideo={this.renderCustomVideo}
            renderTime={this.renderTime}
            forceGetKeyboardHeight
          />
        </KeyboardAvoidingView>
      </View>
    );
  };

```

#### Expected Results

should be able to scroll and see all messages in conversation as well as the textInput and the message I am typing.

#### Additional Information

I have an android device to test with that is using Gboard as the keyboard software and everything works fine.

* Nodejs version: 12.12.0
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* Expo version: 35.0.0
* react-native-gifted-chat version: ^0.7.3
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: [FILL THIS OUT]

**Comment by virtualLast** [comment]
I was looking through the Keyboard.js file in react-native/Libraries/Components/Keyboard and I found this comment on line 115

> Note that if you set `android:windowSoftInputMode` to `adjustResize`  or `adjustNothing`,
>    * only `keyboardDidShow` and `keyboardDidHide` events will be available on Android.
>    * `keyboardWillShow` as well as `keyboardWillHide` are generally not available on Android
>    * since there is no native corresponding event.

However in GiftedChat.js located in react-native-gifted-caht/src the functions are called onKeyboardWillShow (line 249) so does that mean that these functions are not firing on android?

**Comment by alicancelik** [comment]
+1

**Comment by alicancelik** [comment]
I think i found a solution.  when you put a View to bottom of GiftedChat component you should describe view's height thanks to screen and window's dimensions 

```  <View style={{ height: Dimensions.get('window').height - Dimensions.get('screen').height }} />```

**Comment by virtualLast** [comment]
@alicancelik did your code actually fix the issue? It seems to me that this will add whitespace beneath the   giftedChat component.

**Comment by alicancelik** [comment]
sorry for late answer @virtualLast. Yes when i tried all android phones it seems normal like i want

**Comment by theodelebarre** [comment]
@virtualLast 
Just had the same issue.
Solved it by NOT having forceGetKeyboardHeight prop and by adding the following below GiftedChat component:
`{Platform.OS === "android" && <KeyboardSpacer />}`

[Find it here](https://github.com/Andr3wHur5t/react-native-keyboard-spacer)
I do not know if that works with a Google Keyboard
