### ISSUE TITLE
Bug display placeholder

### ISSUE THREAD

**Issue by tuan072090** [FaridSafi/react-native-gifted-chat#1532]
#### Steps to Reproduce / Code Snippets

The placeholder text when there is no message is 180 rotated.

please look at this screenshot
https://media.meete.co/cache/260x145/2019/12/02/428314ca-2df3-41f2-a5c3-d8aca1d68e6a.jpeg

#### Additional Information

* Platform: iOS

**Comment by xcarpentier** [comment]
Can you provide a piece of code?
