### ISSUE TITLE
Accessory Bar Space

### ISSUE THREAD

**Issue by nathan-pierotti** [FaridSafi/react-native-gifted-chat#1538]
#### Issue Description

A space exists below the send button when manually typing out a word in the example provided. 

#### Steps to Reproduce / Code Snippets

Using the example code provided, this is the result when beginning to manually type a word:

<img width="366" alt="Screen Shot 2019-12-04 at 6 40 24 PM" src="https://user-images.githubusercontent.com/11747411/70197648-27821080-16d2-11ea-961f-a7e6f41106a1.png">

#### Expected Results

When erasing the word and starting again we achieve the expected result:
<img width="363" alt="Screen Shot 2019-12-04 at 8 10 35 PM" src="https://user-images.githubusercontent.com/11747411/70197716-5dbf9000-16d2-11ea-9bdf-34ba5075a171.png">

#### Additional Information

* Nodejs version: v12.11.1
* React version: v16.9.0
* React Native version: v0.61.5
* react-native-gifted-chat version: v0.12.0
* Platform(s) (iOS, Android, or both?): iOS
* TypeScript version: [FILL THIS OUT]

**Comment by marshallshen** [comment]
I confirm that I encountered the same issue, the following steps replicate this issue:

1. Type something
2. Hit *space* either from computer keyboard or phone keyboard
3. Type something again

The spacing for "send" is off after step 3.
