### ISSUE TITLE
Firebase timestamp not converting properly ?

### ISSUE THREAD

**Issue by kishanbharda** [FaridSafi/react-native-gifted-chat#1539]
#### Issue Description

I am using this library with react-redux and firebase. I am successfully sending and receiving messages from firebase. But the problem is that received message is always displaying time 12:00 AM.

Here is how my message `createdAt` field stored in firebase.
![Screenshot 2019-12-06 at 6 20 37 PM](https://user-images.githubusercontent.com/39869106/70326568-d4879500-185a-11ea-9ad2-4c0e53736be1.png)

Message when I fetch it : 
![Screenshot 2019-12-06 at 7 05 31 PM](https://user-images.githubusercontent.com/39869106/70326820-7c04c780-185b-11ea-87f7-d8daf6a59ca0.png)

As you can see I stored `createdAt` as firebase timestamp which is not converting properly at receive time of message. If I store it as string then it is displaying proper time.

How, I can solve this ?

**Comment by lundcm** [comment]
You have to convert the firebase timestamp to a date. I mapped the messages (of type QuerySnapshot) to get everything formatted correctly.

```jsx
    <GiftedChat
      messages={messages.docs.map((message: any) => ({
        _id: message.id,
        createdAt: message.data().createdAt.toDate(),
        text: message.data().text,
        user: {
          _id: message.data().user.id,
          name: getDisplayName(message.data().user),
          avatar: getAvatar(message.data().user)
        }
      }))}
      user={{
        _id: currentUser.uid
      }}
    />
```

**Comment by kishanbharda** [comment]
Here is my own temporary solution : https://stackoverflow.com/a/59223857/8182248
