### ISSUE TITLE
Slow rendering with more than ten messages

### ISSUE THREAD

**Issue by ItachiUchiha91** [FaridSafi/react-native-gifted-chat#1541]
#### Issue Description

![5debbac0ccd8d245786446](https://user-images.githubusercontent.com/17726762/70376353-7c0ed100-1908-11ea-9aef-efb0aea9881f.gif)

As you can see from the gif, if the messages are hardcoded why is there an activity indicator?

Why the app loads first the last ten messages and then the others? Is there something in the source code I can edit in order to change this behaviour?

#### Steps to Reproduce / Code Snippets

You can find the simple code here https://pastebin.com/WCF06v8q

#### Expected Results

A more fluid user experience

#### Additional Information

* Nodejs version: v12.12.0
* React version: 16.8.6
* React Native version: 0.60.5
* react-native-gifted-chat version: 0.12.0
* Platform(s) (iOS, Android, or both?): Android and ios (with and without expo)

**Comment by danyalasif** [comment]
Dealing with the exact same thing right now, after searching for a bit I have found many issues from way back 2018 asking this exact question with the tag "wontfix", I am currently loading 20 messages at a time, which is pretty standard, but the app takes a good 2-3 second delay to load the messages.

**Comment by steinroe** [comment]
Same issue for me, anyone found a solution for this? I want to display 100 messages and it only displays around 5 or 6 on initial render...

**Comment by brianomchugh** [comment]
This  works for me (except all the messages still load slow-- but it is all at once):
```
          <GiftedChat
            messages={this.state.messages}
            onSend={this.onSend}
            user={{
              _id: 1,
            }}
            ref={s => this.giftedChat = s}
            listViewProps={{
              initialNumToRender: 15
            }}
          />
```
