### ISSUE TITLE
Font family of Bubble text not changing on Android, but changes on iOS

### ISSUE THREAD

**Issue by vincegnzls** [FaridSafi/react-native-gifted-chat#1543]
#### Issue Description

I tried changing the fontFamily of the Bubble text component, the font family changes on iOs but it does not change on android. This only occurs when I choose the SemiBold font on Android

#### Steps to Reproduce / Code Snippets

1. Create custom bubble component

    const renderBubble = props => {
        return (
            <Bubble
                {...props}
                textStyle={{
                    right: styles.bubbleTextRight,
                    left: styles.bubbleTextLeft,
                }}
            />
        )
    }

    bubbleTextLeft: {
        fontFamily: Fonts.MuliSemiBold,
        fontSize: responsiveFontSize(1.8),
        color: '#4A4A4A',
    },
    bubbleTextRight: {
        fontSize: responsiveFontSize(1.8),
        fontFamily: Fonts.MuliSemiBold,
    },

2. Run on iOS, fonts work fine
![image](https://user-images.githubusercontent.com/12133723/70427296-6e478000-1aaf-11ea-893d-827681a815bd.png)

3. Run on Android, fonts doesn't change
![image](https://user-images.githubusercontent.com/12133723/70427405-9fc04b80-1aaf-11ea-8bf1-2c2024848b36.png)

P.S. The fonts are linked properly on android because it works on other components outside gifted chat

#### Expected Results

Font family will change on android

#### Additional Information
* React Native version: 0.61.5
* react-native-gifted-chat version: ^0.12.0
* Platform(s) (iOS, Android, or both?): Both

**Comment by vincegnzls** [comment]
Hello, anyone looking on this issue?

**Comment by MamyChow** [comment]
Same probleme did you find solution?

**Comment by kenkotch** [comment]
Try updating styles in `renderMessageText` component

**Comment by PaperMonster** [comment]
I solved this by setting `fontWeight: null` along with `fontFamily` style.

**Comment by sjk024** [comment]
So you basically have to include renderMessageText function in the Bubble. Like
import {Bubble, MessageText} from 'react-native-gifted-chat'
renderBubble=(props)=>{
return(
   <Bubble
      {...props}
      renderMessageText={renderMessageText}
   />
)
}

renderMessageText=(props)=>{
return (
     <MessageText
          {...props}
          textStyle={{
            right:{
              fontSize:12
            }
          }}
        />
)

}
