### ISSUE TITLE
white space above chat when keyboard shows on iOS,listview with margin bottom prop

### ISSUE THREAD

**Issue by jerearaujo03** [FaridSafi/react-native-gifted-chat#1544]
#### Issue Description

I'm using custom composer, who is taller than default. This forces me use `listViewProps={{style: {marginBottom: 60}}}` so the messages list don't show beneath the composer.
This is working ok, but when the keyboard is showed up on iOS, there is a white space between the composer, and the messages list. This doesn't happens on Android. When the keyboard is dismissed, this white space disappears.

#### Steps to Reproduce / Code Snippets

```
<GiftedChat
...
listViewProps={{style: {marginBottom: 60}}}
renderComposer={this.renderComposer}
/>
```

```
renderComposer(props) {
    return(
        <Composer {...props} textInputStyle={{ fontFamily:'Poppins-Regular', fontSize: Platform.OS === 'ios' ? 18 : 20, color: 'rgba(36, 37, 61, .55)', paddingLeft: 0, margin: 0, paddingTop: 0, borderRadius: 8, paddingRight: 15, lineHeight: 25, marginBottom: Platform.OS === 'ios' ? 6 : 0 }} />
    )
} 
```

![ios](https://user-images.githubusercontent.com/7424471/70435056-9c53a280-1a64-11ea-9922-bcaf819a35cd.gif)

#### Expected Results

![android](https://user-images.githubusercontent.com/7424471/70435063-a1b0ed00-1a64-11ea-9198-48111056791f.gif)

#### Additional Information

* Nodejs version: 12.1.0
* React Native version: 0.61.5
* react-native-gifted-chat version: 0.12.0
* Platform(s) (iOS, Android, or both?): both

**Comment by fukemy** [comment]
i found this problem when put SafeAreaView in top of View, trying to find solution

**Comment by asadbjs** [comment]
<GiftedChat
              bottomOffset={45} />
