### ISSUE TITLE
gets padding between avatar and message rendered

### ISSUE THREAD

**Issue by geekymsk** [FaridSafi/react-native-gifted-chat#1552]
#### Issue Description

when rendering the avatar, there is gap between avatar and message

#### Steps to Reproduce / Code Snippets

 renderAvatar(props) {
    return (
      <Avatar
        {...props}
        avatarStyle={{width: 10, height: 10, borderRadius: 5}}
        containerStyle={styles.avatar}
      />
    );
  }

#### Expected Results

there should be no gap between avatar and message

#### Additional Information

* Nodejs version: 10.16.2
* React version: 16.8.6
* React Native version: 0.60.5
* react-native-gifted-chat version: 0.12.0
* Platform(s) (iOS, Android, or both?): both ios and android
* TypeScript version: no [typescript]([url](url
<img width="333" alt="Screenshot 2019-12-10 at 5 48 44 PM" src="https://user-images.githubusercontent.com/23626913/70528940-63572300-1b75-11ea-8a0d-2f3878ee37eb.png">
<img width="331" alt="Screenshot 2019-12-10 at 5 49 31 PM" src="https://user-images.githubusercontent.com/23626913/70528971-74079900-1b75-11ea-9fca-6cac5ab28b32.png">

))

**Comment by cameroncharles** [comment]
@geekymsk did you ever solve this one?
