### ISSUE TITLE
Temporarily disable TextInput

### ISSUE THREAD

**Issue by DuranMoodley** [FaridSafi/react-native-gifted-chat#1554]
#### 
is there a way to temporarily Disable TextInput for the chat. I only want the user to view the chats but not respond to it. is this possible? Would really appreciate some help with this.

**Comment by ali5049** [comment]
Making a pr for this issue.

**Comment by ali5049** [comment]
@DuranMoodley this issue is fixed. Just pass the disableComposer = {true} prop in GiftedChat to disable the composer.

**Comment by Hirbod** [comment]
@Ali-Haider-Ch ideally, this should also deactivate any CustomAction, I just rendered the CustomActions and passed down the prop

**Comment by thejogsa** [comment]
> @DuranMoodley this issue is fixed. Just pass the disableComposer = {true} prop in GiftedChat to disable the composer.

Perfectly working fine, Thanks man. Saved my day.

**Comment by jaenjam** [comment]
Thank you 😭
