### ISSUE TITLE
ERROR (npm ERR! errno -4058)

### ISSUE THREAD

**Issue by tasad-7** [FaridSafi/react-native-gifted-chat#1556]
(https://user-images.githubusercontent.com/56359738/70674647-3e81af00-1c4c-11ea-8534-4b7be483f5ad.PNG)

C:\Users\TAHA\Desktop\ @@@>npm i react-native-gifted-chat
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/EvanBacon/react-native-parsed-text.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TAHA\AppData\Roaming\npm-cache\_logs\2019-12-12T01_08_09_608Z-debug.log

**Comment by RDMCharts** [comment]
Hi guys,

I am having trouble installing react-native-gifted-chat, I have tried Yarn and NPM on Windows machine. Seems to be the same as this issue.

Yarn Error:
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error Couldn't find the binary git
yarnpkg exited with non-zero code: 1
Set EXPO_DEBUG=true in your env to view the stack trace.

NPM Eerror:
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/EvanBacon/react-native-parsed-text.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ryan.chartres.REPUBLIQUE\AppData\Roaming\npm-cache\_logs\2019-12-19T01_14_34_695Z-debug.log

**Comment by tasad-7** [comment]
Yup I'm still having the same issue

**Comment by xcarpentier** [comment]
It's because you need GIT maybe?

**Comment by prospkarl** [comment]
![image](https://user-images.githubusercontent.com/54798409/71713360-5829a700-2e44-11ea-92fe-1197037de970.png)
Same Issue

**Comment by prospkarl** [comment]
Run the command on git. This works for me.

**Comment by aroucha-miguel** [comment]
Sorry for hijacking this thread and the mentions.

I understand the problem and the solution.

However I build my project through CI/CD, and my DevOps guy is really reluctant to add git to that environment to solve this problem. Especially being a project that is forked. His fears are that the repo may be deleted on the future, or open new doors to new poorly maintained projects through dependencies (which yarn pkg repo already ensures).

As a solution, I'm stuck on version 0.9.11 (last one before having EvanBacon version of react-native-gifted-chat).

Do any of you have another workaround, solution or insights to this situation?
What were the real reasons that made from switching from the original react-native-parsed-text to the EvanBacon fork?
Will that fork ever be a package available through yarn?

@xcarpentier @EvanBacon
