### ISSUE TITLE
Render Empty chat view getting inverted

### ISSUE THREAD

**Issue by nayan-pious** [FaridSafi/react-native-gifted-chat#1557]
I have tried the new renderChatEmpty, Its working with inverted value as false. When I have the inverted value as true, the empty chat view is getting inverted.
![Simulator Screen Shot - iPhone X - 2019-12-12 at 13 06 33](https://user-images.githubusercontent.com/45681198/70692592-a7ffcd00-1ce1-11ea-9d5c-60e95fcb78ef.png)

Have a view for renderChatEmpty with a text and make the inverted value to true.

* react-native-gifted-chat version: 0.12.0

**Comment by steffenagger** [comment]
As a _**temp**_ fix, you can add `transform: scaleY(-1)` to the root-element of whatever you're rendering (this will rotate it 180° once more).

**Comment by StagasaurusRex** [comment]
I've been using `inverted={messages.length !== 0}`

**Comment by xcarpentier** [comment]
@StagasaurusRex do you think it's needed into this lib.
If yes, PR? ;)

**Comment by ricardoribas** [comment]
Would it make sense to add these styles in the root component if the list of messages is empty? So, we don't need to make that hack ourselves. Could it be that there is a case where is make sense to have it inverted?

FYI, i've added the following code and it works:
`messagesContainerStyle={{
          transform: [
            {
              scaleY: -1
            }
          ]
        }}`

**Comment by xcarpentier** [comment]
Yes, it's a great idea! But I have no time now.
If anyone can handle it by creating a PR I will be honored to review and merge :)

**Comment by Usamaliaquat123** [comment]
@xcarpentier  sure will do

**Comment by schumannd** [comment]
This issue is still a problem in the newest version. Why is it marked as wontfix?

**Comment by marqroldan** [comment]
@schumannd sorry  for tagging you, but I just wanted to say that the last release on npm is December 16, 2019 so it's not the latest version yet using `npm i`

**Comment by allan-simon** [comment]
problem is still here in 0.16.1

**Comment by ethanwc** [comment]
why close this?

**Comment by mirzahayat** [comment]
> Would it make sense to add these styles in the root component if the list of messages is empty? So, we don't need to make that hack ourselves. Could it be that there is a case where is make sense to have it inverted?
> 
> FYI, i've added the following code and it works: `messagesContainerStyle={{ transform: [ { scaleY: -1 } ] }}`
i think you need to modify some little bit changing. and its work fine.
messagesContainerStyle={messages?.length < 0 && {transform: [{scaleY: -1}]}}

**Comment by Habtamu-Asefa** [comment]
I am still getting this issue. This fix is not working for me.

messagesContainerStyle={messages?.length == 0 && {transform: [{scaleY: -1}]}}


on version

**Comment by adsalihac** [comment]
> i think you need to modify some little bit changing. and its work fine. messagesContainerStyle={messages?.length == 0 && {transform: [{scaleY: -1}]}}

iOS and Android is different.

**Comment by adsalihac** [comment]
```tsx
<GiftedChat
  renderChatEmpty={() =>
    <Empty
      style={{
        ...Platform.select({
          ios: {
            transform: [{ scaleY: -1 }],
          },
          android: {
            transform: [{ scaleX: -1, },
            {
              scaleY: -1,
            }
            ],
          },
        }),
      }}
      title="No messages available"
      description="Start a conversation by sending a message"
    />
   }
 />
```
