### ISSUE TITLE
Feature: Chat typing indicator out of the box

### ISSUE THREAD

**Issue by shamilovtim** [FaridSafi/react-native-gifted-chat#1565]
#### Issue Description

I propose adding a chat typing indicator out of the box which uses an internal state variable `isTyping` to animate a chat bubble in while `isTyping` is true and to animate the chat bubble out while `isTyping` is false. I'll use vectors and react native animations. Should I have the presence of `renderChatFooter` disable this typing indicator?

If this is desirable and no one is working on it then I'll probably be taking a stab at it next week. 

@xcarpentier

**Comment by xcarpentier** [comment]
Do you mean vector icon?

I think we don’t have to change actual renderChatFooter.

I think it may be interesting to have a new type of message like we already have SystemMessage. Or better this `isTyping` is currently a new sort of SystemMessage.

What do you think?

**Comment by shamilovtim** [comment]
@xcarpentier I was thinking just using vectors themselves to display the ". . ." That way the users can style the dots with whatever color they want.

<img width="141" alt="Screen Shot 2019-12-18 at 2 59 10 PM" src="https://user-images.githubusercontent.com/3495974/71118907-fc55f180-21a6-11ea-8567-f93f52a734b9.png">

 I actually don't need a system message because in my system a system message is simply a `message` with `user: { name: system, avatar: 'system.png'}`. This is an extensible way to have a system message that requires nothing from the plugin's side than what it already offers.  

Example of a system message with system avatar:
<img width="316" alt="Screen Shot 2019-12-18 at 3 03 31 PM" src="https://user-images.githubusercontent.com/3495974/71119177-9ae25280-21a7-11ea-821b-78e928822b63.png">

Regarding `renderChatFooter` it needs to be disabled if the user decides to use the out of the box typing indicator I provide, right?

**Comment by shamilovtim** [comment]
@xcarpentier Just got done. Should have a PR sometime next week if it looks fine.

![Screen Recording 2019-12-28 at 7 42 30 PM](https://user-images.githubusercontent.com/3495974/71551054-ae619a80-29ab-11ea-829c-710fafff89cf.gif)

**Comment by m4ttheweric** [comment]
I am seeing this new prop in the example project, is this working in the main branch? The Accessory bar button in the example setup is supposed to toggle the status if I am understanding correctly, but I am not seeing it. Also, the TS processor believes that "isTyping" is not a <GiftedChat /> prop. I am wondering if there's something still to be finished with this feature...

**Comment by xcarpentier** [comment]
Because it’s not yet published

**Comment by dparrelli** [comment]
Hey @xcarpentier - when do you think you'll get a chance to publish this?

**Comment by naishe** [comment]
I'd love to see this feature out of the box. Currently, at v0.13.0, `isTyping={true}` does not render any animation.

**Comment by akhan118** [comment]
Hey Peeps, is this this feature released yet ??

**Comment by shamilovtim** [comment]
Looks like not yet

**Comment by Arjanvanmaren** [comment]
Hmm it would be nice if this got released soon :)

**Comment by AndreasOhlsson** [comment]
Yes, please release this soon!

**Comment by shamilovtim** [comment]
You can use my fork for now: 
https://github.com/shamilovtim/react-native-gifted-chat

You will need to compile the project:
cd node_modules/react-native-gifted-chat && yarn install && yarn build && yarn config:npm && rm -rf node_modules && cd ../.. && npx jetify

**Comment by NdaJunior** [comment]
@shamilovtim I see your fork requires expo? can you perhaps share the code that you added so that if we are not using expo, we can still get this functionality?

**Comment by akhan118** [comment]
@shamilovtim Thanks, do you know when it will be release ?

**Comment by shamilovtim** [comment]
It's not up to me unfortunately. I have no idea what's going on with the repo and no time to help maintain it.

**Comment by chichke** [comment]
Is it up ?

**Comment by xcarpentier** [comment]
yes

**Comment by Joshandrews43** [comment]
`isTyping` prop is not displaying any UI for me:

**Comment by shamilovtim** [comment]
Can't use it that way!

Set isTyping to true dynamically **after mount**

**Comment by Joshandrews43** [comment]
@shamilovtim Using it as state also shows nothing, and I've double checked that it is set to true while the opponent is actually typing. Can you share an example that is working for you?

**Comment by shamilovtim** [comment]
I'm using the latest version of the plugin. I simply have it set to a stateful variable coming from my Redux store. and my working example would simply be that. There's something you're doing wrong with how you manage state. I'd start out with make sure you're using this plugin inside of a function component because that's where I can confirm the typing indicator works. Not sure if it's broken in class components but those are legacy at this point so you might need to refactor.

```
   <GiftedChat
          ...
          ...
          isTyping={state.trackingBoardAndSchedule.isTyping}
/>
```

**Comment by Aryk** [comment]
Is there anyway to get the isTyping stuff under the renderChatFooter? Or maybe I should be adding the "seen" stuff a different way? I'm all ears.

![IMG_9286](https://user-images.githubusercontent.com/525212/89105318-c2311b80-d428-11ea-8b03-5387375be670.jpg)

**Comment by svm1** [comment]
Great stuff! Is there a way to customize the appearance of the typing indicator, just like how you can customize the message bubbles and text?

**Comment by shamilovtim** [comment]
You may supply your own typing indicator if you'd like by overriding one of the footer props (I forget which)

**Comment by ishaqashraf** [comment]
you can use `renderFooter` prop for rendering custom typing component

**Comment by fukemy** [comment]
> renderFooter

please provide more code thanks bro
