### ISSUE TITLE
Markdown support.

### ISSUE THREAD

**Issue by rohitpotato** [FaridSafi/react-native-gifted-chat#1571]
#### Issue Description
I propose adding **markdown** support. Right now, the only solution is to use external libraries. Markdown can be specified in the ```textInput``` field itself.

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by nick-massie** [comment]
Please add this!!

**Comment by moscchi** [comment]
I think with the IA is good add this, because some answers comes with markdown styles.

**Comment by tahsinhasem** [comment]
Good idea!

**Comment by tslater** [comment]
Could it be simpler to allow for a renderer for the the main text body?
