### ISSUE TITLE
Question: It is possible to customise message grouping and date header?

### ISSUE THREAD

**Issue by dinotrnka** [FaridSafi/react-native-gifted-chat#1575]
Hi all,

I was just wondering, is it currently possible to put  a custom header instead of the current one that shows the date in the format such as "OCT 14, 2019".

For example, I'd want to group all the messages from this week in headers such as "Monday", "Tuesday" and so on, or group them by months like "January" if they are older than 1 week.

Is that possible? Thanks in advance!

**Comment by dinotrnka** [comment]
Does anyone know the answer?

A simple yes/no is fine.

**Comment by dinotrnka** [comment]
Bumping this thread so someone can hopefully answer.

**Comment by frankyjuang** [comment]
@dinotrnka  checkout `renderDay`

**Comment by dinotrnka** [comment]
> @dinotrnka checkout `renderDay`

Thank you very much! That solved most of the problem!
