### ISSUE TITLE
Nested FlatList as a custom message in GiftedChat not scrolling

### ISSUE THREAD

**Issue by kevgrig** [FaridSafi/react-native-gifted-chat#1582]
#### Issue Description

Nested FlatList as a custom message in GiftedChat doesn't scroll on Android (even with `nestedScrollEnabled=true` on both the nested FlatList and GiftedChat with `listViewProps`).

Screenshot:
![demo](https://raw.githubusercontent.com/kevgrig/react-native-gifted-chat-nested-scrollview/master/demo.gif "Demo")

#### Steps to Reproduce / Code Snippets

Code: https://github.com/kevgrig/react-native-gifted-chat-nested-scrollview/blob/master/App.js
Snack: https://snack.expo.io/@kevg/github.com-kevgrig-react-native-gifted-chat-nested-scrollview

Relevant snippet:

```js
      <GiftedChat
        messages={[...Array(3).keys()].map(i => {
          return {
            _id: i,
            text: 'Hello World ' + i,
            createdAt: new Date(),
            user: {
              _id: 1,
              name: 'User1',
            },
          };
        })}
        user={{
          _id: 1,
        }}
        renderMessage={(props) => {
          return (
            <View>
              <Message {... props} />
              <FlatList
                style={{ borderWidth: 1, borderColor: "black", height: 200, margin: 30 }}
                nestedScrollEnabled={true}
                data={[...Array(10).keys()].map(i => {
                  return { id: '' + i, title: 'FlatList item ' + i };
                })}
                renderItem={({ item }) => <Item title={item.title} />}
              />
            </View>
          );
        }}
        listViewProps={{
          nestedScrollEnabled: true
        }}
      />
```

#### Expected Results

Each nested FlatList should be scrollable within the height boundary and show 10 items.

#### Additional Information

* Nodejs version:12.13.1
* React version: 16.9.0
* React Native version: 0.61.4
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): Android in particular, maybe iOS overflow issues too
* TypeScript version: 2.8.3

```
$ expo diagnostics

  Expo CLI 3.11.3 environment info:
    System:
      OS: Linux 5.3 Fedora 31 (Workstation Edition) 31 (Workstation Edition)
      Shell: 5.0.11 - /bin/bash
    Binaries:
      Node: 12.13.1 - /usr/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.12.1 - /usr/bin/npm
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.11.3
```

**Comment by nathanguigui** [comment]
is there any news ?
