### ISSUE TITLE
Keyboard offset on text input focus

### ISSUE THREAD

**Issue by oleprohon** [FaridSafi/react-native-gifted-chat#1585]
#### Issue Description

There is a problem with the keyboard offset when clicking on the text input. It's then fixed when starting to type.

#### Steps to Reproduce / Code Snippets

Using example code:

```
import React, { Component } from 'react';
import { View, Text, KeyboardAvoidingView } from 'react-native';
import { GiftedChat } from 'react-native-gifted-chat';

const imageName = require('../../assets/images/logo.png');

class ChatScreen extends Component {
  state = {
    messages: [],
  }

  componentDidMount() {
    this.setState({
      messages: [
        {
          _id: 1,
          text: 'Hello World',
          createdAt: new Date(),
          user: {
            _id: 2,
            name: 'INVI',
            avatar: imageName,
          },
        },
      ],
    })
  }

  onSend(messages = []) {
    this.setState(previousState => ({
      messages: GiftedChat.append(previousState.messages, messages),
    }))
  }

  render() {
    return (
      // <View>
      <View style={{flex: 1}}>
      <GiftedChat
      messages={this.state.messages}
      onSend={messages => this.onSend(messages)}
      user={{
        _id: 1,
      }}
      />
      </View>
      // <KeyboardAvoidingView />
      // </View>
    )
  }
}

export default ChatScreen;
```

1. Screen looks ok
![1](https://user-images.githubusercontent.com/5577518/71650548-990aaa00-2ce4-11ea-8a1f-83822ecc8c7f.PNG)

2. After clicking on text input
![2](https://user-images.githubusercontent.com/5577518/71650550-a162e500-2ce4-11ea-9305-d7ddf3181414.PNG)

3. Fixed after typing
![3](https://user-images.githubusercontent.com/5577518/71650554-a6c02f80-2ce4-11ea-8388-fcc39b23eabf.PNG)

#### Expected Results

The view should be rendered correctly without having to type.

#### Additional Information

* Nodejs version: 13.5.0
* React Native version: 0.61.5
* react-native-gifted-chat version:
0.13.0
* Platform(s) (iOS, Android, or both?): iOS
* TypeScript version: NONE

**Comment by ramonvermeulen** [comment]
I wrapped the gifted chat in a `react-native-keyboard-aware-scroll-view` which solves this issue for me.

https://github.com/APSL/react-native-keyboard-aware-scroll-view

**Comment by shamilovtim** [comment]
duplicate #1424. this is from your bottom tab navigator
