### ISSUE TITLE
Check Render Problems

### ISSUE THREAD

**Issue by mertbuldur** [FaridSafi/react-native-gifted-chat#1589]
Hi i am using gifted chat 0.13.0 but i have some problem.
<img width="355" alt="Ekran Resmi 2020-01-03 17 55 31" src="https://user-images.githubusercontent.com/8089725/71730116-6b437380-2e52-11ea-9b50-ebd8e76195a6.png">

**Comment by xcarpentier** [comment]
Please provide a part of your code where you call GiftedChat. Thanks.

**Comment by mertbuldur** [comment]
hi, i am import this code my page `import {GiftedChat, Message} from 'react-native-gifted-chat';` and than  i'm using your example GiftedChat component

**Comment by Tochukwuibe** [comment]
I am experiencing the exact same Issue, I updated to the latest 0.13.0 from 0.9.0 just a few minutes ago.

<img width="310" alt="Screen Shot 2020-01-03 at 11 15 18 AM" src="https://user-images.githubusercontent.com/28849147/71734669-6a8eeb00-2e1a-11ea-915c-fc0834507aa0.png">

**Comment by Tochukwuibe** [comment]
Here is where I am using the component and I am importing it just as it says in the docs, just like @mertbuldur 
<img width="850" alt="Screen Shot 2020-01-03 at 11 18 14 AM" src="https://user-images.githubusercontent.com/28849147/71734845-dc673480-2e1a-11ea-93bf-800685072f22.png">

**Comment by xcarpentier** [comment]
Please fill this template: [issue template](https://github.com/FaridSafi/react-native-gifted-chat/edit/master/ISSUE_TEMPLATE.md)from your initial message: https://github.com/FaridSafi/react-native-gifted-chat/issues/1589#issue-545028648

Please see here another example that works: [giftedchat-playground](https://snack.expo.io/@xcarpentier/giftedchat-playground)

**Comment by mertbuldur** [comment]
hi i am found problem , in use flex:1 this error showing

**Comment by mertbuldur** [comment]
remove flex:1 after this problems have . indicator starting .
<img width="355" alt="Ekran Resmi 2020-01-03 19 58 22" src="https://user-images.githubusercontent.com/8089725/71736945-6804b380-2e63-11ea-99e1-71bdd57ce6db.png">

` <SafeAreaView  style={{ flex:1}}>
                {this.state.loading ?
                    <View style={{justifyContent: 'center', alignItems: 'center', flex: 1}}>
                        <PulseIndicator color='#FD267D' size={70}/>
                    </View>
                    :

                    <View>
                        <UserInfoCard access_token={this.props.navigation.getParam('access_token')}
                                      name={this.props.navigation.getParam('name')}
                                      photo={this.props.navigation.getParam('photo')}
                                      permission={this.props.navigation.getParam('permission')}
                        />
                        {this.state.progressVisible &&
                        <View style={{ flexDirection: 'row', justifyContent: 'center', alignItems: 'center', paddingVertical: 10, borderBottomWidth:1, borderBottomColor:'#ccc' }}>
                            <Progress.Bar borderWidth={0} unfilledColor={"#DADADA"} color={"#EB344B"} progress={this.state.progressBarValue/100} width={200}/>
                            <Text style={{marginLeft: 5}}>%{this.state.progressBarValue}</Text>
                        </View>
                        }

                        <View style={{ flex:1}}>
                             <GiftedChat
                            isLoadingEarlier={this.state.isLoadingEarlier}
                            onLoadEarlier={this.loadMore}
                            loadEarlier={(this.state.next_page == null) ? false : true}
                            extraData={{isTyping:this.state.isTyping}}
                            onInputTextChanged={text => {
                                this.onInputTextChanged(text)
                            }}
                            renderFooter={this.renderFooter}
                            onLongPress={
                                (context,message)=>{
                                    (message.user._id == token) ? this.onLongPressMe(context,message) : this.onLongPressTarget(context,message);
                                }
                            }
                            keyboardShouldPersistTaps={"handled"}
                            renderLoading={() =>  <ActivityIndicator size="small" color="#DADADA" />}
                            bottomOffset = { (Platform.OS === 'ios') ? 45 : 0 }
                            messages={this.state.messages}
                            placeholder={LANG.something_write}
                            renderMessage={this.renderMessage}
                            onSend={messages => this.onSend(messages)}
                            user={{
                                _id: token
                            }}
                            renderActions={(props) =>{
                                return (
                                    <View style={{flexDirection:'row',paddingBottom:5}}>
                                        <Icon
                                            style={{ padding:10}}
                                            name="microphone"
                                            size={20}
                                            color={this.state.startAudio ? "red" : "black"}
                                            onPress={this.handleAudio}
                                        />
                                        <Icon
                                            style={{ padding:10}}
                                            name="image"
                                            size={20}
                                            color={"black"}
                                            onPress={this.onSelectImage}
                                        />

                                    </View>)
                            }}

                        />
                        </View>



                    </View>
                }
            </SafeAreaView>`

**Comment by mertbuldur** [comment]
i solved this problem but received:true bot not showing new message .
`const result =  this.state.messages.map((i,e)=>{
                if(i.user._id == this.props.AuthStore.token){
                   i.received = true;
                }
                console.log(i);
                return i;
            });
 this.setState({ messages:result,isTyping:false});
`

help me
