### ISSUE TITLE
Render Chat Footer background color cannot be transparent

### ISSUE THREAD

**Issue by vincegnzls** [FaridSafi/react-native-gifted-chat#1591]
#### Issue Description

I am trying to make the background color of the chat footer to transparent but it always turns out to be white.

#### Steps to Reproduce / Code Snippets

```
const renderChatFooter = chatFooterProps => {
    return {
          <View style={{ height: 50, width: '100%', backgroundColor: 'transparent' }} />
    }
}
```

#### Expected Results

Chat footer should have a transaprent background.

#### Additional Information
* React Native version: 0.61.5
* react-native-gifted-chat version: ^0.12.0
* Platform(s) (iOS, Android, or both?): both

**Comment by xkungfu** [comment]
strange.
same issue.
why added wontfix and closed?

**Comment by sjdezube** [comment]
Any update on this?
