### ISSUE TITLE
typings of usernameStyle on <Bubble {...props} />

### ISSUE THREAD

**Issue by ramonvermeulen** [FaridSafi/react-native-gifted-chat#1593]
#### Issue Description

The typings of usernameStyle on `<Bubble<IMessage> />` aren't correct.
The typings expect a `LeftRightStyle<ViewStyle>` while it actually should be a `TextStyle`. (I think)
I'm getting crashes when I put in a left: { styles ... } or right: { styles ... }.
![image](https://user-images.githubusercontent.com/18006244/71810844-9bb62800-3073-11ea-8847-e900d0243c5e.png)

#### Steps to Reproduce / Code Snippets

Try the usernameStyle prop on the `<Bubble />` with a `left` or `right` and the app will crash. However if you put styles directly into the props it works but you get a TS warning.

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: 12.8.1
* React version: 16.11.0
* React Native version: 0.61.5
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: 3.7.3

**Comment by xcarpentier** [comment]
Hi,
Thanks.
PRs are welcome :)

**Comment by ramonvermeulen** [comment]
https://github.com/FaridSafi/react-native-gifted-chat/pull/1594

**Comment by ramonvermeulen** [comment]
Awesome, issue can be closed I guess.

**Comment by AreebVohra** [comment]
need help with this
![Screenshot_1579865794](https://user-images.githubusercontent.com/34376767/73066654-6a898480-3ec8-11ea-9640-0fefed61f1d1.png)
![tempsnip](https://user-images.githubusercontent.com/34376767/73066656-6b221b00-3ec8-11ea-9617-4768c9b3bcef.png)

**Comment by razafarishta** [comment]
@AreebVohra Did you solve this issue?
