### ISSUE TITLE
Forward Message

### ISSUE THREAD

**Issue by leon2835** [FaridSafi/react-native-gifted-chat#1595]
Hi there, currently everythings look good, just wonder is this library support any Forward Message features as well? I can't find it from the document including "Copy to clipboard" features. Thank you.

**Comment by ramonvermeulen** [comment]
> Hi there, currently everythings look good, just wonder is this library support any Forward Message features as well? I can't find it from the document including "Copy to clipboard" features. Thank you.

I'm not sure, but I thought by default if you longpress on a message there will popup a bottom sheet with an option to copy the message.

**Comment by leon2835** [comment]
Hi Ramon and thanks for the reply,

Sorry for get you miss-understanding what i'm trying to say, I know there's a feature "Long Press" and it will show selection of "Copy text" and its working. But i'm trying to find something similar with WhatsApp "Reply Message/ Forward" options. Is there any api that i can use? Or maybe i can create some component and able to show inside the TextInput area? 
<img width="528" alt="Screenshot 2020-01-09 at 9 44 59 AM" src="https://user-images.githubusercontent.com/19604759/72030736-feeac900-32c4-11ea-8196-45c20b0a6bf9.png">

Thank You
