### ISSUE TITLE
Render custom message from rest call

### ISSUE THREAD

**Issue by rpalmese** [FaridSafi/react-native-gifted-chat#1596]
#### Issue Description

I need to render messages like this 
`{
            "_id": null,
            "text": "<Text> Hello <Text onPress=doSomething()> click here</Text></Text>",
            "createdAt": null,
            "system": null,
            "image": null,
            "video": null,
            "audio": null,
            "user": null,
            "quickReplies": {
                "type": "radio",
                "keepIt": "true",
                "values": []
            }
        }`

If I render it from the code it works well but I need to receive messages from a rest call, 
if I render the same message received from a rest call the result is a bubble with the Text component printed as a string: 

`<Text> Hello <Text onPress=doSomething()> click here</Text></Text>`

#### Expected Results

What can I do to get it work?

#### Additional Information

* Nodejs version: 10.16.0
* React: 16.9.0
* React Native version: 0.63
* react-native-gifted-chat version: 0.13.0

**Comment by xcarpentier** [comment]
Use `renderMessage` to implement what you want.

**Comment by rpalmese** [comment]
> Use `renderMessage` to implement what you want.

Has you got some examples of how to use renderMessage? I'm trying to use it
