### ISSUE TITLE
Keyboard hide first messages on Android.

### ISSUE THREAD

**Issue by MamyChow** [FaridSafi/react-native-gifted-chat#1597]
#### Issue Description

We can see on first screenshot i'm on the top of messages and i can see all messages. On the second screenshot the keyboard is open, i'm on the top of the scrollview but i can't see the first messages.
I think the keyboard push the scrollview and the top of the scrollview is not visible.
Do you have a solution ?

<img width="335" alt="Capture d’écran 2020-01-08 à 10 12 54" src="https://user-images.githubusercontent.com/31539767/71967231-4c066680-3203-11ea-96f1-6ff3d6890942.png">
<img width="324" alt="Capture d’écran 2020-01-08 à 10 13 15" src="https://user-images.githubusercontent.com/31539767/71967329-7b1cd800-3203-11ea-8344-a5ee7de48ea0.png">

#### Steps to Reproduce / Code Snippets

```
render() {
    return (
        <GiftedChat
            messages={this.state.messages}
            user={{_id: this.state.user.uid}}
            onSend={this.onSend}
        />
    )
}
```

#### Expected Results

I would like to see all messages even if the keyboard is open

#### Additional Information

* React version: 16.9.0
* React Native version: 0.61.1
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by shamilovtim** [comment]
This looks like it's working as intended. What space are you expecting the keyboard to take up if it doesn't move things out of its way?

**Comment by MamyChow** [comment]
i'm not sure it's working as intended because when the keyboard is open i can't scroll to the top to see the first message.

**Comment by shamilovtim** [comment]
@MamyChow Thank you it's possibly from the header chrome

**Comment by MamyChow** [comment]
What's the header chrome?

**Comment by MrNapcae** [comment]
This problem appeared when upgrading to version 2.6.2 from 2.4.0. Any solutions?
