### ISSUE TITLE
GiftedChat component is not visible in web when using nested components

### ISSUE THREAD

**Issue by kaxterzz** [FaridSafi/react-native-gifted-chat#1599]
I'm trying gifted chat for web and I have followed the  [sample project](https://github.com/xcarpentier/gifted-chat-web-demo) in the documentation that @xcarpentier  have created. I noticed that size of the current window size had been set to the `<View>` component so the `<GiftedChat>` will inherit that size 

I tried using it inside a grid (using material-ui component framework for react) without setting the width and height and GiftedChat isn't visible on the window but if I set width and height manually it's visible.

This is what I have tried in Content component

    `function Content() {
      return (
          <Container>
            <Grid item xs={12} sm={6}>
              <SocketContext.Consumer>
                {socket => <MainChatArea socket={socket} />}
              </SocketContext.Consumer>
            </Grid>
            <Grid item xs={12} sm={6}>
            </Grid>
          </Container>
      );
    }` 
And MainChatArea Component

    `<View>
        <GiftedChat
          messages={this.state.messages}
          onSend={messages => this.onSend(messages)}
          scrollToBottom={true}
          renderUsernameOnMessage={true}
          user={{
            _id: 1,
            name: "You"
          }}
        />
      </View>`
As I said if i set the width and height manually GiftedChat is gets visible. Is there a way to inherit the parent width and height ? Like I want GiftedChat to take the Grid size.

**Comment by xcarpentier** [comment]
Hi @kaxterzz,
Sorry for the latency.
Why did you close it?
Did you find a way to do it?
