### ISSUE TITLE
Avatar not rendering initials when avatar is null

### ISSUE THREAD

**Issue by lironsher** [FaridSafi/react-native-gifted-chat#1607]
#### Issue Description

When not supplying image, the avatar is not rendered as initials  

#### Steps to Reproduce / Code Snippets

user : { avatar:null }

#### Expected Results

Render as initials

#### Additional Information

the bug is in this line in message.tsx

  ```
renderAvatar() {
  [...]
        if (currentMessage && currentMessage.user && currentMessage.user.avatar === null) {
            return null;
        }
  [...]
    }
```
This should be removed to solve the issue.

ps: I've forked, fixed but cannot build...

**Comment by perrosnk** [comment]
Any updates?
