### ISSUE TITLE
Autoscroll to a specific message

### ISSUE THREAD

**Issue by Flouwrian** [FaridSafi/react-native-gifted-chat#1608]
#### Issue Description
We´re building a news distribution app, so the users gets alot of messages by the provider. When the Chat is opened the window scrolls to the bottom automatically. We would love to scroll to the first message that was not read yet by the customer. Is there a possibility to scroll to a specific message, by offset or maybe even id ? Important would be also that it scrolls to the beginning of the message since our news provider tends to send super long messages. Scrolling options could be by id of the messages or by a set offset or something.

#### Expected Results

The Chat scrolls to the beginning of a dedicated message.

#### Additional Information

* Nodejs version: 12.4.1
* React version: 16.12
* React Native version: 0.60
* react-native-gifted-chat version: 0.13
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: 3.4.7

**Comment by cesarve77** [comment]
Did you solve it?

**Comment by hupptechnologies** [comment]
Any solution for this? I also want to implement scroll to specific message and highlight unread messages.

**Comment by skizzo** [comment]
+1

**Comment by ryzhak** [comment]
You can try:
1. Create a ref to GiftedChat instance
```
<GiftedChat
    ref={c => {
        this.instance = c;
    }}
/>
```
2. On component mount run:
```
setTimeout(() => {
    this.instance._messageContainerRef.current.scrollToIndex({index: 10, viewOffset: 0, viewPosition: 1});
}, 3000);
```
where `index` is the message index counting from the bottom message to top

It works only when chat is initialized that is why we use `setTimeout` here which is very fragile. I didn't manage to figure out the moment when GiftedChat is initialized(where we should call `scrollToIndex()`).

**Comment by akhilsanker** [comment]
Hi,

Any idea before the GiftedChat is initialised. Its not good after the chats get view and then scrolled to an index even-tough scroll is working.

Thanks
