### ISSUE TITLE
Feature Request: Make chat background a touchable

### ISSUE THREAD

**Issue by akritskiy** [FaridSafi/react-native-gifted-chat#1611]
#### Issue Description

This feature would be beneficial since we often want message bubbles to respond to touch. For example, if you tap a message on Facebook Messenger, the sent/delivered/read status is displayed below and the sent date is shown above the message. Right now, I've been able to implement this with gifted chat except one minor detail. I would like to add a touchable to the background so when I tap off the message I can hide the date and message status. The closest I've gotten so far is by adding a TouchableWithoutFeedback to the chat footer and setting the z-index to position it behind the message bubbles, but I couldn't figure out the right z-indices to get the touchable above the background but below the message bubbles.

I think it would be a good feature and add some flexibility to gifted chat. I would be open to attempting to implement this myself, if I get some good feedback/guidance here.

**Comment by akritskiy** [comment]
@shamilovtim 
Can you provide a link to the package and explain?

**Comment by shamilovtim** [comment]
Sorry, I didn't read your issue specifically enough. My advice to you: the listview has a touchable which it uses to hide the keyboard. I assume you can go off that.
