### ISSUE TITLE
Web build fail with syntax error

### ISSUE THREAD

**Issue by from74** [FaridSafi/react-native-gifted-chat#1612]
#### Issue Description

Build fail with syntax error when I try to build on the web.
similar issue - https://github.com/FaridSafi/react-native-gifted-chat/issues/1083

#### Steps to Reproduce / Code Snippets

```
ERROR in ../node_modules/react-native-gifted-chat/lib/GiftedChat.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/devmac/workspace/server/node_modules/react-native-gifted-chat/lib/GiftedChat.js: Unexpected token (333:26)

  331 |     renderMessages() {
  332 |         const { messagesContainerStyle, ...messagesContainerProps } = this.props;
> 333 |         const fragment = (<View style={[
      |                           ^
  334 |             {
  335 |                 height: this.state.messagesContainerHeight,
  336 |             },
    at Parser.raise (/Users/devmac/workspace/server/node_modules/@babel/parser/lib/index.js:6344:17)

```

#### Expected Results

build succeeded

#### Additional Information

* Nodejs version: v10.15.3
* React version: ^16.8.4
* React Native Web version: ^0.12.0-rc.1
* react-native-gifted-chat version: ^0.13.0
* Platform(s) (iOS, Android, or both?): web
* TypeScript version: ^3.2.2

**Comment by adrianocola** [comment]
If you are using a custom webpack config, you must configure it like the [gifted chat documentation says ](https://github.com/FaridSafi/react-native-gifted-chat#with-create-react-app)
