### ISSUE TITLE
When keyboard shows on iOS, it does like a slide-animation of the entire screen on iOS

### ISSUE THREAD

**Issue by msqar** [FaridSafi/react-native-gifted-chat#1613]
#### Issue Description

So for the chat, i push to a new screen, this screen renders with all the messages and gifted-chat itself... without keyboard showing at first, but when the keyboard shows up, slides from right to left and kind of making an entire screen slide animation, so if I wrap my giftedChat with an ImageBackground, the ImageBackground also slides... and looks like a double screen push whenever I tap on a chat room.

How can I fix this undesirable effect?

**Comment by shamilovtim** [comment]
Are you using react-native-screens `useScreens()`?

**Comment by msqar** [comment]
@shamilovtim No, not using those hooks, although... I ended up not showing the keyboard automatically when I change to a new screen and that solved it... not the best thing but I prefer not having that double-slide. I had to modify the library to not open it. Thanks for replying though!

**Comment by Harshitha91** [comment]
This issue still exists.

**Comment by msqar** [comment]
@Harshitha91 Yes, i had to solve it personally on my local copy, by removing the keyboard showing automatically whenever the chat renders, it doesn't do any weird animation anymore. Hope they can come up with a real fix, tho.

**Comment by shamilovtim** [comment]
they keyboard doesn't show automatically when the chat renders. i think this is a consequence of a setting in your app.

**Comment by msqar** [comment]
@shamilovtim No, i actually read the entire code of GiftChat.js and there is a keyboardFocus during componentDidMount... it's there. I had to remove that logic and doesn't open the chat at start anymore
