### ISSUE TITLE
renderSend does not apply the onSend prop

### ISSUE THREAD

**Issue by prospkarl** [FaridSafi/react-native-gifted-chat#1616]
I tried to merge renderSend and onSend but unfortunately this two props does not completely work. So what I did is I added an onPress function on my renderSend. My question is: **How do I clear the field after sending a message**

#### Additional Information
![image](https://user-images.githubusercontent.com/54798409/72876086-a984d200-3d30-11ea-9949-de0336d7aa6e.png)

=< Sorry for the bad code.

* Nodejs version: 10.18
* React version: 16.8
* React Native version: 0.60.4
* react-native-gifted-chat version: "^0.13.0"
* Platform(s) (iOS, Android, or both?): Both

**Comment by iqbalfaisal** [comment]
@prospkarl Kindly try this code. Happy Coding

`renderSend={props =>`
`<Icon`
`              color={Colors.mainAppColor}`
`              size={40}`
`              type="simple-line-icon"`
`              name="bubbles"`
`onPress={() => { }}`
`            />`
`          )}`

**Comment by prospkarl** [comment]
> @prospkarl Kindly try this code. Happy Coding
> 
> `renderSend={props =>`
> `<Icon`
> ` color={Colors.mainAppColor}`
> ` size={40}`
> ` type="simple-line-icon"`
> ` name="bubbles"`
> `onPress={() => { }}`
> ` />`
> ` )}`

I tried the code. But it does not work. 

![image](https://user-images.githubusercontent.com/54798409/73151783-b5450f80-4107-11ea-91be-e24ccd7ac828.png)

**Comment by iqbalfaisal** [comment]
@prospkarl did you test it without `renderSend` ? if yes then which Icon lib you're using?

**Comment by prospkarl** [comment]
> @prospkarl did you test it without `renderSend` ? if yes then which Icon lib you're using?

It will work without renderSend, but instead of using the "send" text, I want to use the Send Icon.

Im using 'react-native-vector-icons' for the Icon

**Comment by Beaudinn** [comment]
He @prospkarl
I had the same problem, what does your icon component look like?
With me it was in a Button component that prevented to triggering the Send function.

**Comment by prospkarl** [comment]
Thank

> He @prospkarl
> I had the same problem, what does your icon component look like?
> With me it was in a Button component that prevented to triggering the Send function.
> 
> Ow and don't forget to give your icon as a child to the Send component. Like this.
> 
> ```
>   renderSend = (props) => {
>      //Add the extra styles via containerStyle
>     return (
>       <Send {...props}>
>             <Icon name="send" backgroundPrimary rounded />
>       </Send>
>     );
>   }
> ```

Thank You!!! It worked with '<Send />'. 

![image](https://user-images.githubusercontent.com/54798409/74719988-fc8a7000-526f-11ea-8fee-6e749e800c44.png)
