### ISSUE TITLE
Invariant Violation: Element type is invalid !

### ISSUE THREAD

**Issue by chassierPA** [FaridSafi/react-native-gifted-chat#1617]
#### Issue Description

I just update my project from react-native 0.59 to react-native 0.61.5

#### Expected Results

![photo_2020-01-22_22-04-43](https://user-images.githubusercontent.com/43825466/72934117-5f691400-3d63-11ea-9a67-90e9873ecc49.jpg)

#### Additional Information

* Nodejs version: 12.6.0
* React version: 16.12.0
* React Native version: 0.61.5
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: 3.4.2

**Comment by chassierPA** [comment]
I downgrade react-native-gifted-chat version to 0.9.11 and it's works.

Do you have any idea why gifted chat does't work on 0.13.0 ?

**Comment by xcarpentier** [comment]
Hi @chassierPA,
I'm using it without issues on RN `0.61.4` (i.e. Expo 36)
https://snack.expo.io/@xcarpentier/giftedchat-playground

**Comment by shamilovtim** [comment]
Using it fine on expo 36 with rn 61.x here

**Comment by esdotzed** [comment]
I had exactly the same issue. I just updated from 0.59.10 to 0.60.6. Super weird. @chassierPA Did you solve it?

**Comment by esdotzed** [comment]
well... it's actually because I haven't enable typescript in my project....
https://reactnative.dev/docs/typescript
This solved it for me. @chassierPA
