### ISSUE TITLE
isTyping missing/not working

### ISSUE THREAD

**Issue by theocikos** [FaridSafi/react-native-gifted-chat#1618]
#### Issue Description

isTyping is missing in methods on GiftedChat component

#### Steps to Reproduce / Code Snippets
```
<GiftedChat
        messages={this.state.messages}
        onSend={messages => this.onSend(messages)}
        isTyping={this.state.isTyping}
/>
```

this.state.isTyping is set to true
#### Expected Results

I dont see any indicator or any loader when waiting for a message!

**Comment by xcarpentier** [comment]
Hi
Sorry not yet publihed

**Comment by TheOmran** [comment]
You can add the following; replacing this.channel.typing with whatever function your chat service uses.

```
  typing() {
    this.channel.typing();
  }
```
// Gifted Chat Props
`onInputTextChanged= {this.onTyping}
`

**Comment by JForsaken** [comment]
Any updates on when this will be published? 👼 @xcarpentier

**Comment by ardyfeb** [comment]
> Hi
> Sorry not yet published

please remove that feature on readme if is not published yet

**Comment by dayaki** [comment]
Please is this implemented yet?

**Comment by glenvollmer** [comment]
it looks like the TypingIndicator.tsx file is included in the src for this project, yet I am unable to use the isTyping feature. Do you have an idea about when this might be usable?

**Comment by falcononrails** [comment]
I tried using isTyping={true} today on Android but it doesn't show up, any news on this?

**Comment by xcarpentier** [comment]
Hi,
This is by design: not shown on the mount.
Try to use a boolean state variable and change the value.
Just like here:

**Comment by falcononrails** [comment]
@xcarpentier thanks, manipulating state solved the issue.

**Comment by fukemy** [comment]
@falcononrails still not working to me with hook bro
