### ISSUE TITLE
[0.2.x] don't sort props directly

### ISSUE THREAD

**Issue by braco** [FaridSafi/react-native-gifted-chat#162]
This breaks under Immutable structures, which can't be modified:

https://github.com/FaridSafi/react-native-gifted-messenger/blob/v0.2.x/example/react-native-gifted-messenger/src/GiftedMessenger.js#L131

But why assume the structure needs to be sorted at all?

**Comment by FaridSafi** [comment]
Good catch. This sort is totally optional, I'll remove it
