### ISSUE TITLE
How to implement a Datepicker into Quick Replies? Is there an example?

### ISSUE THREAD

**Issue by itsDZhang** [FaridSafi/react-native-gifted-chat#1620]
#### Issue Description

Based on a button clicked within Quick-Replies, I want the chatbot to prompt a date picker. Once the user has scrolled to the right date/time, I would click a button to close that date picker.
Then the chatbot would continue on with the conversation flow.  

(I'm going to use react-native-date-picker as the third-party datepicker)

#### Expected Results

Is there an example of what I have described??

#### Additional Information

Additional Information
Nodejs version: 12.6.0
React version: 16.12.0
React Native version: 0.61.5
react-native-gifted-chat version: 0.11.3
Platform(s) (iOS, Android, or both?): both

**Comment by Beaudinn** [comment]
I am also interested in this
