### ISSUE TITLE
Custom Image view : "Touchable child must either be native or forward setNativeProps to a native component"

### ISSUE THREAD

**Issue by aymericbouzy** [FaridSafi/react-native-gifted-chat#163]
I get the following error when trying to use the `imageView` attribute for the message.
![simulator screen shot 22 jul 2016 10 00 05](https://cloud.githubusercontent.com/assets/8168981/17050434/175f3fa6-4ff3-11e6-8184-c7b56bb6d6f5.png)
I assume this is the fix : http://stackoverflow.com/questions/31741705/error-invariant-violation-touchable-child-must-either-be-native-or-forward-set
I will try on a forked branch and do a PR if it solves it.

**Comment by aymericbouzy** [comment]
So it looks like the fix is only on the users side. However, it doesn't seem to work which version 0.1.4, it is only fixed in version 0.1.5, but it is not available on npm. When will version 0.1.5 be released? I'm using my forked version of master for the time being, and closing this issue.

**Comment by aymericbouzy** [comment]
For future reference, this is how my custom image view code looks like : 
```
class ProfileImage extends Component {
  setNativeProps(native_props) {
    this._root.setNativeProps(native_props)
  }

  render() {
    return (
      <View ref={(root) => this._root = root} style={...}>
        {...}
      </View>
    )
  }
}
```
and then my messages look like:
```
let message = {
    imageView: ProfileImage,
    ...
  }
```

**Comment by aymericbouzy** [comment]
I was mistaken, it doesn't fix anything. Sorry for not testing well enough and posting wrong information.

I was not able to fix this completely, although simply adding a `View` component encapsulating the `ImageView` seems to be the simplest way to fix this. However, I then get another error I'm not able to fix at the moment:
```
Invalid css_position_type_t 'right'. should be one of: (
    absolute,
    relative
)
```
I also get this error when removing `onImagePress` prop in my code, which gets rid of the `TouchableHighlight` which is the cause of the problem. So I assume these are uncorrelated issues, and wrapping in `View` component really is a fix.

**Comment by kfiroo** [comment]
@aymericbouzy I think the problem started in this [commit](https://github.com/FaridSafi/react-native-gifted-messenger/commit/592a2db631b200bb0d6998ae6f3f31b330c67827).
Spreading the `rowData` into `ImageView` as props is really bad.
Something like this might be a better solution, making the `rowData` available to the custom `ImageView` as its own prop. (perhaps calling it `messageData` or `message` could be even better)
```javascript
<ImageView
    rowData={rowData}
    source={rowData.image}
    style={[styles.imagePosition, styles.image, (rowData.position === 'left' ? styles.imageLeft : styles.imageRight)]}
/>
```

**Comment by aymericbouzy** [comment]
wouldn't it be better still to have a "renderImage" method? that way the user can do whatever he wants.

**Comment by kfiroo** [comment]
@aymericbouzy It's a different approach, having a `renderImage` method will be called for each `message`, or `image message`, while having `imageView` is an override for a specific message.
That being said, I like the `renderImage` approach a lot better. :)

**Comment by aymericbouzy** [comment]
well `renderImage` could be a prop for each message ... but it would also make sense to lift it to the main component's props.

**Comment by kfiroo** [comment]
@aymericbouzy Could work :)  
But in general I don't think we should mix `data` and `view`.  
`message` data should be clean data without any regards to how it will be presented, besides maybe a field stating the type of message.

**Comment by aymericbouzy** [comment]
This issue was _not_ solved. We were simply getting closer on agreeing how to_best_ solve it.

**Comment by kfiroo** [comment]
@aymericbouzy Looks like @FaridSafi release a new version, maybe it is all resolved there :)

**Comment by aymericbouzy** [comment]
You're right, I hadn't seen that. Can't wait to test the new version! from the readme, it looks awesome :D

**Comment by kfiroo** [comment]
@aymericbouzy Same here :)
Thanks @FaridSafi 👍
