### ISSUE TITLE
Hi, where is the admin page or page manager ?

### ISSUE THREAD

**Issue by nirina87** [FaridSafi/react-native-gifted-chat#1630]
#### Issue Description

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by Usamaliaquat123** [comment]
@nirina87 , need more info... Thanks

**Comment by msqar** [comment]
??? care to explain or elaborate?
