### ISSUE TITLE
Stupid question... how do I get rid of the line above the Composer?

### ISSUE THREAD

**Issue by GollyJer** [FaridSafi/react-native-gifted-chat#1631]
Where does it live?
![image](https://user-images.githubusercontent.com/689204/73418328-ff78ed00-42cf-11ea-873e-977ed5185f38.png)

**Comment by emilisb** [comment]
It's right here: https://github.com/FaridSafi/react-native-gifted-chat/blob/6c17d5981beca4d7de4a812433c632895eab982b/src/InputToolbar.tsx#L20

You should be able to override it via `containerStyle` prop: 
```
containerStyle={{borderTopWidth: 0}}
```

**Comment by GollyJer** [comment]
That was it! Thanks @emilisb. 🎉
