### ISSUE TITLE
Scroll to top

### ISSUE THREAD

**Issue by sidequest-co** [FaridSafi/react-native-gifted-chat#1632]
Is there any way to scroll to the top like the scroll to bottom? I would like the default start position to be the top, as I inverted the order of the messages. Can I achieve it any way in the current version?

* Nodejs version: 13.0.1
* React version: 16.8.6
* React Native version: 0.60.5
* react-native-gifted-chat version: 0.11.3
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: none

**Comment by trin4ik** [comment]
always by default flatlist scroll to bottom:
https://github.com/FaridSafi/react-native-gifted-chat/blob/6c17d5981beca4d7de4a812433c632895eab982b/src/GiftedChat.tsx#L634-L646
and we doesnt have any options to disable this with props, only with hack. when gidted-chat is load and you set data, run this:
`chat.current._messageContainerRef.current.scrollToEnd = () => {};`
where chat is ref to giftedChat component.
mb i create PR for add special option 4 this.

**Comment by sidequest-co** [comment]
@trin4ik Thank you! I'll try this out and post the results. Is there any event when data is set?

**Comment by hupptechnologies** [comment]
Anyone who's struggling to get a scroll to top working I finally get it done with some changes.

```
<GiftedChat
  ref={(ref) => (this.chatRef = ref)}
/>
```

1. If you are using prop `listViewProps` then need to remove it because when you use this we didn't get ref of `_messageContainerRef` inside `this.chatRef`
2. Now to scroll top you have to use `this.chatRef._messageContainerRef.current.scrollToEnd();`

**Comment by 1vipulgupta** [comment]
`<GiftedChat
        messages={messages}
        messageContainerRef={giftedChatRef}....`
        
```const giftedChatRef = useRef<FlatList<IMessage>>(null);
  const handleScrollToTop = () => {
    if (giftedChatRef.current && giftedChatRef.current.scrollToIndex) {
      giftedChatRef.current.scrollToIndex({ index: 0, animated: true });
    }
  };```
