### ISSUE TITLE
Passing defaultValue to textInputProps in the Composer component does not work

### ISSUE THREAD

**Issue by JakyChen** [FaridSafi/react-native-gifted-chat#1634]
#### Issue Description

Passing defaultValue to textInputProps in the Composer component does not work as intended. The default value shows up as the default text prop passed to the Composer which is ''. I'm not sure but I'm guessing it's because if a value is passed to the TextInput component the value overrides the defaultText.

#### Steps to Reproduce / Code Snippets
<GiftedChat renderComposer={(props) =>
    <Composer {...props} textInputProps={{ defaultValue: 'test' }} />
} />

#### Expected Results
Composer should render with a default value of "test" in the TextInput component.

#### Additional Information

* Nodejs version: 6.9.0
* React version: 16.9.0
* React Native version: 0.61.4
* react-native-gifted-chat version: 0.7.3
* Platform(s) (iOS, Android, or both?): Both

**Comment by alburkerk** [comment]
For other people facing the same issue: `defaultValue` does not work when value is set.

To fix this issue :

```js
 textInputProps={{
    // ... Your other props
    value: undefined,
    defaultValue: 'test',
}}
     
```
