### ISSUE TITLE
GiftedChat not rendered when testing with Jest

### ISSUE THREAD

**Issue by sregg** [FaridSafi/react-native-gifted-chat#1637]
#### Issue Description

I'm using https://native-testing-library.com for unit and integration tests in my app.
When I render `GiftedChat` it gets stuck at the loading state and never renders the messages.
I tried to replace 

```
    render() {
        if (this.state.isInitialized === true) {
            return (<SafeAreaView style={styles.safeArea}>
          <ActionSheetProvider ref={(component) => (this._actionSheetRef = component)}>
            <View style={styles.container} onLayout={this.onMainViewLayout}>
              {this.renderMessages()}
              {this.renderInputToolbar()}
            </View>
          </ActionSheetProvider>
        </SafeAreaView>);
        }
        return (<View style={styles.container} onLayout={this.onInitialLayoutViewLayout}>
        {this.renderLoading()}
      </View>);
    }
``` 

with 

```
    render() {
      return (<SafeAreaView style={styles.safeArea}>
        <ActionSheetProvider ref={(component) => (this._actionSheetRef = component)}>
          <View style={styles.container} onLayout={this.onMainViewLayout}>
            {this.renderMessages()}
            {this.renderInputToolbar()}
          </View>
        </ActionSheetProvider>
      </SafeAreaView>);
    }
```

(basically removing the check `this.state.isInitialized === true`)

And the messages are rendered and the test passes!
For some reason the component doesn't re-render after `onInitialLayoutViewLayout`.

I also see that your own tests are failing to render the whole component:
https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/__tests__/__snapshots__/GiftedChat.test.tsx.snap
As you can see only the loading container is rendered...

#### Steps to Reproduce / Code Snippets

Here's my `native-testing-library` test:

```
import React from 'react';
import { render, wait } from '@testing-library/react-native';
import { GiftedChat } from 'react-native-gifted-chat';

const messages = [
  {
    _id: 2,
    text: 'Hello developer',
    createdAt: new Date(),
    user: {
      _id: 2,
      name: 'React Native',
    },
  },
];

describe('BWChat', () => {
  it('should render messages', async () => {
    const { getByText } = render(
      <GiftedChat
        messages={messages}
        onSend={() => {}}
        user={{
          _id: 1,
        }}
      />
    );

    // we should see the comments
    await wait(() => {
      expect(getByText(messages[0].text)).toBeTruthy();
    });
  });
});
```

#### Expected Results

`GiftedChat` is fully rendered with messages when rendered in Jest with `react-test-renderer` or `native-testing-library`

#### Additional Information

* Nodejs version: 10.16.3
* React version: 16.9.0
* React Native version: 0.61.2
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): Jest
* TypeScript version: 3.7.2

**Comment by hannojg** [comment]
Wow, how can this be closed? I have the exact same issue, and the removal of `this.state.isInitialized === true` let it also work for me. 
Please reopen @FaridSafi

**Comment by hannojg** [comment]
Figured out a hotfix, just call this before doing any other testing with gifted chat: 

```javascript
    await act(async () => {
      const instance = component.root;

      const chatView = instance.findByType(GiftedChat);

      chatView.children[0].props.onLayout({
        nativeEvent: {
          layout: {
            // iPhone 8 dimensions
            width: 375,
            height: 667,
          },
        },
      });
    });
```

**Comment by sregg** [comment]
Has anyone tried to do this with `react-native-testing-library`?
`onLayout` doesn't seem to be there...
![image](https://user-images.githubusercontent.com/1479283/88672272-45631200-d0b5-11ea-8aac-15667a7fa355.png)

**Comment by Doaa-Ismael** [comment]
@sregg I used waitForElement so I can find GiftedChat component and fire event on it
```
   const {getByTestId} = renderScreen(<ScreenThatrendersGiftedChat />, {mocks});
   const chat = await waitForElement(() => getByTestId('chat'));
```

**Comment by OliverAThunes** [comment]
I'm also having issues with the GiftedChatComponent not rendering, I'm using the react native testing library with jest.

**Comment by Andrerm124** [comment]
I'm also struggling to figure out how to actually test this component. I've set a 10 second timeout in hopes to allow any rerenders to occur, but it never actually attempts to layout the component
