### ISSUE TITLE
Is there a way to animate the Composer size change?

### ISSUE THREAD

**Issue by GollyJer** [FaridSafi/react-native-gifted-chat#1638]
I'd like to animate the Composer size change when the Send button shows.
Is there a way; instead of just immediately snapping in place?

Or, if it is already animated, is there a way to slow it down. Again, I'm having a hard time finding where the visibility of the Send button is even being set in the source code. 😕

![20200130_181645](https://user-images.githubusercontent.com/689204/73507455-d61e9680-438d-11ea-98bd-7b1085fe4b54.gif)

Thanks!

**Comment by ismdcf** [comment]
@GollyJer were u able to achieve this feature

**Comment by GollyJer** [comment]
No
