### ISSUE TITLE
Unable to create a private chat (one to one chat room)

### ISSUE THREAD

**Issue by Jeet989** [FaridSafi/react-native-gifted-chat#1649]
#### Issue Description

here i am unable to create a one to one chat room(private chat room). 

* Nodejs version: 12.13.1
* React Native version: 0.61.4
* react-native-gifted-chat version: 6.12.1
* Platform(s) (iOS, Android, or both?): both

**Comment by emilisb** [comment]
How is this related to this library? It is on you to implement the backend. This library is just a chat viewer, it does not provide any server-side functionality.

**Comment by Jeet989** [comment]
@emilisb Then what to do for this? Is there any other option to implement this feature??

**Comment by edoofx** [comment]
> @emilisb Then what to do for this? Is there any other option to implement this feature??

u can use socket at backend, then at mobile using this lib

if u dont know about that,

GO BACK WITH HTML CSS :))))))
