### ISSUE TITLE
Unable to style time stamp of chat bubbles

### ISSUE THREAD

**Issue by aravi365** [FaridSafi/react-native-gifted-chat#1655]
#### Issue Description

Unable to change the timestamp styling displayed in chat bubbles

#### Steps to Reproduce / Code Snippets

  
```
  renderBubble (props) {
    return (
      <Bubble
        {...props}
       
        textStyle={{
          right: {
            color: 'black',
            fontWeight:'400'
          },
          left:{
            color:'black',
            fontWeight:'400'

          }
        }}
        wrapperStyle={{
          right: {
            backgroundColor: '#ffd633'
          },
          left:{
            backgroundColor:'#fff0b3'
          }
        }}
      />
    )
  }
```
![Simulator Screen Shot - iPhone 8 - 2020-02-22 at 00 38 10](https://user-images.githubusercontent.com/15327129/75063791-a5083080-550b-11ea-8433-fc0eee9aafc7.png)

#### Expected Results

Styling for time stamps just like the message text in the bubble

#### Additional Information

* React version: 16.8.3
* React Native version: 0.59.10
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): Yes

**Comment by aravi365** [comment]
It may be marked as duplicate, but the thing is i found a thread with guide to style the chatbubbles - but not the timestamps.

**Comment by sichiu** [comment]
Have you tried using renderTime?

Below is what I do

`import { Time } from 'react-native-gifted-chat';
import Colors from '../../../constants/Colors';

const styles = StyleSheet.create({
	container: {
		flex: 1,
		justifyContent: 'flex-end'
	},
	chat: {
		color: Colors.grey,
		textAlign: 'right'
	}
});

const ChatTime = ({ currentMessage, timeFormat }) => {
	return (
		<Time
			currentMessage={currentMessage}
			timeFormat={timeFormat}
			containerStyle={{
				left: styles.container,
				right: styles.container
			}}
			timeTextStyle={{
				right: styles.chat,
				left: styles.chat
			}}
		/>
	);
};`

**Comment by judygab** [comment]
@sichiu do you just pass that ChatTime as a props to renderTime?

**Comment by judygab** [comment]
I don't think styling looks right, because I tried that and date overflows from the bubble.

**Comment by Gabsys** [comment]
Just use `timeTextStyle={{ left: { color: 'black' },right: { color:'black'} }}` props at GiftedChat tag

**Comment by varunb-kc** [comment]
I used
```
timeTextStyle={
                        left:{ ... },
                        right: {... }
                    }
```
 prop at Bubble Component.

**Comment by jairenee** [comment]
Is there no way to get more granular than "left" and "right"? If there's a multi-user chat with multiple different background colors going on on the left side, I want to be sure the timestamp is readable. If I'm limited to "left", then that can't happen. Yikes.
