### ISSUE TITLE
[Question] How to keep the navbar displayed on text input ? (react-native-router-flux)

### ISSUE THREAD

**Issue by Brokray** [FaridSafi/react-native-gifted-chat#166]
Hi everyone,

I apologize if the question have already been asked, but I couldn't find a thread specifically about this.
I've integrated GiftedMessenger to my application and when I start writing a message the all view goes up in order to give some space to the keyboard. The problem is that my navigation bar goes up too.

Does anyone have found a way to keep it at it's place while writing ? 
I tried with absolute style positionning but doesn't seem to work. Also tried to contain my `<GiftedMessenger /> `component in a `<ScrollView />`, unsuccessful.

I'm a bit of a newbie in react-native : maybe I'm missing something obvious. I apologize for my bad english.
Thanks you all.

### Version
- react-native-router-flux v3.31.2
- react-native v0.28.0
- react-native-gifted-messenger v0.1.4

**Comment by msafayasar** [comment]
@FaridSafi Is there any solution? I think you have the solution as you closed the issue. Can you explain how to solve this?
