### ISSUE TITLE
Keyboard hide textInput on Android

### ISSUE THREAD

**Issue by MamyChow** [FaridSafi/react-native-gifted-chat#1660]
#### Issue Description

Keyboard hide part of textInput if i try to modify a text :(

<img width="350" alt="Capture d’écran 2020-02-22 à 21 15 50" src="https://user-images.githubusercontent.com/31539767/75098664-51542080-55b9-11ea-8e3a-54bf96b24975.png">
<img width="338" alt="Capture d’écran 2020-02-22 à 21 16 08" src="https://user-images.githubusercontent.com/31539767/75098667-574a0180-55b9-11ea-9393-3db5c1e914da.png">

#### Steps to Reproduce / Code Snippets

Enter text in multi line then try to select your first text. All other text behind will be hide by keyboard.

#### Expected Results

I would like to be able to modify text without all text behind the selected one disapear.

#### Additional Information

* React version: 16.9.0
* React Native version: 0.61.1
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by graphee-gabriel** [comment]
Have you tried one of the solutions listed in this issue https://github.com/FaridSafi/react-native-gifted-chat/issues/435 ?
On my Pixel 3 it works using `react-native-keyboard-spacer`, but some users using different devices still reported this issue.
