### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'item._id')

### ISSUE THREAD

**Issue by kharlm** [FaridSafi/react-native-gifted-chat#1661]
I keep getting the error : TypeError: undefined is not an object (evaluating 'item._id')

this.props.dog.dogId prints a value when I console log it so I'm not sure what the error is. 

Here is my code: 

lass MatchesChat extends Component {
    state = {
        messages: [],
      }

      componentWillMount(){
        this.getMessages()
    
      }

      getMessages = async () => {
        console.log("in get  Matches chat")
        let dogs = []
        const query = await db.collection('dogs').where('dogId', '==', this.props.dog.dogId).get()
        
        query.forEach(function(response) {
          dogs.push(response.data())
          })
          let items=[]

          console.log("user id: "+ this.props.navigation.state.params.user.id)
          
          for(let i=0; i<dogs[0].chat.length;i++){

            if(dogs[0].chat[i].user.id===this.props.navigation.state.params.user.id){
            
              items.push(dogs[0].chat[i].messages)
            }
          }
          this.setState({ messages: items.reverse() });      
    }

    onSend = async (messages = []) => {
        //this.props.dispatch(sendNotification(this.props.navigation.state.params.user.id, messages[0].user.name, messages[0].text))
        this.setState(previousState => ({
          messages: GiftedChat.append(previousState.messages, messages),
        }))
     let mess = messages[0]
     console.log("message ZERO: "+mess)
        const query = await db.collection('dogs').where('dogId', '==', this.props.dog.dogId).get()
        
        query.forEach(function(response) {
          dogs.push(response.data())
          })

          for(let i=0; i<dogs[0].chat.length;i++){

            if(dogs[0].chat[i].user.id===this.props.navigation.state.params.user.id){
            
                db.collection('dogs').doc(this.props.dog.dogId).update({
                    ['chat[' + i +']'+ '.messages']:  firebase.firestore.FieldValue.arrayUnion({
                        mess
                       }
                       )
                    
                  })
            }
          }

        
      }
    
    render(){

       

        return(
            <GiftedChat
            messages={this.state.messages}
            onSend={messages => this.onSend(messages)}
            user={{
              _id: this.props.dog.dogId,
              name: this.props.dog.dogname,
              avatar: this.props.dog.photo
            }}
          />
        )
        }

    
}

const mapDispatchToProps = (dispatch) => {
    return bindActionCreators({getDog,getDogs}, dispatch)
  }
  
  const mapStateToProps = (state) => {
    return {
      
      dog: state.dog,
      cards: state.cards
    }
  }
  
  export default connect(mapStateToProps, mapDispatchToProps)(MatchesChat)

**Comment by mareebsiddiqui** [comment]
Did you find a fix? Still getting this issue

**Comment by Michael24884** [comment]
Bump. Im also having this problem on Typescript

**Comment by sanaarshed** [comment]
is this fixed or is there any solution @Michael24884  @mareebsiddiqui  @kharlm

**Comment by adarshUnico** [comment]
Have you got it fixed  @sanaarshed , as I m too getting same error.
