### ISSUE TITLE
Invariant Violation : Element type is invalid

### ISSUE THREAD

**Issue by pavanMude** [FaridSafi/react-native-gifted-chat#1666]
![Simulator Screen Shot - iPhone Xs Max - 2020-02-25 at 09 36 34](https://user-images.githubusercontent.com/58720583/75216436-081eef00-57ba-11ea-9419-e1ff1498086f.png)

#### Issue Description

I have upgraded to react-native-gifted-chat version 0.13.0 due to some issue with ListView. So When I integrated it, then it shows that expected a string (for build in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file its defined in, or you might have mixed up default and named imports.

Check the render method of DugongChat(Custom class)

return (
      <View style={{ flex: 1, backgroundColor: '#2e3032' }}>
        <ImageBackground source={bg} style={styles.background}>
          <DugongChat
            messages={messages}
            onSend={(message: ChatMessage) => sendMessage('chat', this.chatRoom, message,               this.props.privateKey)}
            loadEarlier={this.state.loadEarlier}
            onLoadEarlier={() => this.onLoadEarlier(this.chatRoom, messages)}
            isLoadingEarlier={this.state.isLoadingEarlier}
            user={{
              _id: this.myUid,
              name: firebase.auth().currentUser.displayName,
              avatar: firebase.auth().currentUser.photoURL
            }}
            onInputTextChanged={this.onTyping}
            onLongPress={(context, message) => this.onLongPress(message)}
            renderActions={this.renderCustomActions}
            renderAvatar={this.renderAvatar}
            renderBubble={this.renderBubble}
            renderCustomView={this.renderCustomView}
            renderFooter={this.renderFooter}
            renderMessageText={this.renderMessageText}
            renderMessageImage={this.renderMessageImage}
            renderInputToolbar={this.renderInputToolbar}
            renderComposer={this.renderComposer}
            renderSend={this.renderSend}
            renderMessage={this.renderMessage}
            renderLoadEarlier={this.renderLoadEarlier}
            onPressAvatar={this.onAvatarPressed}
            placeholder={!this.props.network.isConnected ? "You're in offline" : 'Type a message...'}
            listViewProps={{
              onEndReached: () => this.onLoadEarlier(this.chatRoom, messages),
              onEndReachedThreshold: 50
            }}
          />
        </ImageBackground>
      </View>
    );

#### Expected Results

Since version 0.13.0 has been replaced with Flatlist So I expect good performance.

#### Additional Information

React Native : [0.59.9]
* react-native-gifted-chat version: 0.13.0

**Comment by leoxiaoping** [comment]
+1

**Comment by hanishsharma31** [comment]
How did you fix this issue? @pavanMude

**Comment by usmanghani127** [comment]
The issue is with how you are importing gifted chat. 
[https://stackoverflow.com/a/44250317](url)
