### ISSUE TITLE
Wait for GiftedChat to initialize before calling focusTextInput()

### ISSUE THREAD

**Issue by swparkaust** [FaridSafi/react-native-gifted-chat#1674]
#### Issue Description

I'm hiding GiftedChat and showing it on button press.

When the button is pressed and GiftedChat is shown, I'd like its text input to be focused at the same time, so I'm calling `focusTextInput()` on the ref to GiftedChat in the button press handler.

However, I've run into an issue as `focusTextInput()` apparently does not wait for its `text input` to be initialized before calling `focus()` on it, but only ignore if not initialized.

I've confirmed the issue by logging `this.textInput` in the source `GiftedChat.js` -- I can see `this.textInput` is undefined at the time `focusTextInput()` is called thus it is being ignored.

The only way I could get around this is deferring the `focusTextInput()` call by wrapping it in a set timeout of a fixed amount of time, which does work but rather seems like hacky.

#### Steps to Reproduce / Code Snippets

```
  constructor(props) {
    super(props);
    this._focusOnUpdate = false;
  }

```

```
  componentDidUpdate(nextProps) {
    if (this._focusOnUpdate) {
      this.giftedChatRef.focusTextInput();
      this._focusOnUpdate = false;
    }
  }

```

```
  onPressButton = () => {
    store.openOverlay();
    this._focusOnUpdate = true;
  }

```

```
  render() {
    return (
      ...
            { store.overlayShow &&
              <View style={[styles.padding, {flex: 1, position: 'absolute', top: 0, left: 0, right: 0, bottom: 0}]}>
                <GiftedChat
                  messages={this.state.messages}
                  onSend={messages => this.onSend(messages)}
                  user={this.user}
                  locale={'ko'}
                  placeholder='채팅'
                  placeholderTextColor="#CCCCCC"
                  renderAvatar={this.renderAvatar}
                  renderUsernameOnMessage={true}
                  renderInputToolbar={this.renderInputToolbar}
                  renderSend={this.renderSend}
                  textInputStyle={styles.input}
                  ref={c => this.giftedChatRef = c}
                />
              </View>
            }
      ...
    );
  }

```
#### Expected Results

`focusTextInput()` should focus the text input.

#### Additional Information

* React version: 16.8.3
* React Native version: 0.59.8
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): both

**Comment by noway** [comment]
i'm using this + a patch witch makes isInitialized always true
```

  const gcRef = useCallback(node => {
    if (node !== null) {
      node.focusTextInput()
    }
  }, [])```

**Comment by swparkaust** [comment]
@noway Can I ask what is your use of `useCallback` for? Could you describe a bit more about the patch you are using? In my case, the underlying reason for failure is not `GiftedChat` ref itself, but the `textInput` attribute **inside** the ref, which is not being immediately set as the ref is initialized, causing `focusTextInput` to fail.

**Comment by noway** [comment]
my patches here: https://github.com/noway/react-native-gifted-chat/commits/master, specifically i overcame that with having isInitialized always being true

**Comment by swparkaust** [comment]
@noway Oh, right. I just discovered the check for `isInitialized` in the render function, preventing text input ref from being set if false. I wonder why they are doing this?
Thanks for your suggestion, I will try your patch soon. :)

**Comment by swparkaust** [comment]
Ideally, there should be a callback on `isInitialized=true` to make sure it's safe to call methods like `focusTextInput`.

**Comment by noway** [comment]
seems like some layout measurements are done initially, specifically measuring the height of box the chat is rendered in. I think it's needed for slide in/slide out keyboard animations to work perfectly. I find that not having those measurements doesn't break much
