### ISSUE TITLE
keyboard and layout change issues in nexus 5x android version: 6

### ISSUE THREAD

**Issue by ggsrivas** [FaridSafi/react-native-gifted-chat#168]
I have integrated react-native-gifted-messenger with a sample react-native app. Integration is exactly same as giftedMessengerExample. I have noticed few issues with layout when keyboard is open and when  layout is changed from portrait to landscape mode.
1. When we open keyboard, widget is pushed up in screen and there is gap between keyboard and input text field.
2. when layout is changed (from portrait to landscape), widget is not scrolled to bottom and widget is not scroll-able. I can't see input text field.

Please find attached images.

![portrait mode with keyboard](https://cloud.githubusercontent.com/assets/7676582/17230256/04c318b8-54d0-11e6-8c5a-c82979776325.png)
![landscape mode after rotation](https://cloud.githubusercontent.com/assets/7676582/17230269/11fea81c-54d0-11e6-8695-291a402b3a42.png)

Similar issues were seen on other android devices and versions as well. 

Edit: Keyboard issue was a configuration error and has been fixed. Orientation change issue still exists.

**Comment by edencakir** [comment]
same here.

**Comment by ggsrivas** [comment]
Thanks @edencakir .I missed "android:windowSoftInputMode="adjustResize" in for mainActivity. Adding it fixed the keyboard issue.

Now the only issue remaining is, ornamentation change issue.

**Comment by binzailani3136** [comment]
well, is there no way to solve this issue with out configure android:windowSoftInputMode="adjustResize"? 
The reason is if I configure this option, keyboard aware scroll view is not working...
So, my idea is, if I can make the textview height as fixed and make the single line instead of multiline text input.
Can I achieve my idea?

**Comment by ggsrivas** [comment]
@binzailani3136  if you are talking about multi-line text in input field and are expecting text area to resize and be scroll-able, then it's working out of box without any change. 
android:windowSoftInputMode="adjustResize" is required to resize widget when keyboard is open and this is not affecting Input text area height and scroll-ability.

**Comment by binzailani3136** [comment]
Thanks for your reply.
Is there any way to fix this issue #168, without setting android:windowSoftInputMode="adjustResize" this option?
I really don't have to put android:windowSoftInputMode="adjustResize" option on my Android app.
If I configure this option on manifest file, other functionalities are not working...
Such as react native keyboard aware scroll function is not working.

**Comment by mareebsiddiqui** [comment]
I cant seem to solve the problem using the softInputMode attribute any other suggesstion?
