### ISSUE TITLE
Can't Change the Color of Date on The Message

### ISSUE THREAD

**Issue by judygab** [FaridSafi/react-native-gifted-chat#1684]
I tried using both textStyle and textProps but none of them update the date of the message just the content of it. Is there a way I can change that, I want the date and the text to have same color. Attaching an example, I tried it in iOS

<img width="383" alt="Screen Shot 2020-03-17 at 12 08 28 AM" src="https://user-images.githubusercontent.com/50160672/76821281-d959ce80-67e3-11ea-968c-963a27cc0dd4.png">

**Comment by Gabsys** [comment]
use this props: `timeTextStyle={{ left: { color: 'red' }}}`

**Comment by hackrx** [comment]
Can you tell me how you have changed the text color of message box text?

**Comment by hackrx** [comment]
> 
> Can you tell me how you have changed the text color of message box text?

Solved this by using `textStyle` inside `<Bubble/>`
