### ISSUE TITLE
Chats are not in order by time/date. 

### ISSUE THREAD

**Issue by prospkarl** [FaridSafi/react-native-gifted-chat#1686]
![dateproblem](https://user-images.githubusercontent.com/54798409/76932163-3d37e080-6925-11ea-983a-9d62fa82289d.PNG)

I used "new Date()" to parse/send but i still got this problem. Please help.

#### Additional Information

**Comment by prospkarl** [comment]
![image](https://user-images.githubusercontent.com/54798409/77023982-4928ae80-69c8-11ea-8aab-1aeb2bfcddb2.png)

Still not woking

**Comment by angelxmoreno** [comment]
I am getting the same issue. I have a date string in this format `2021-10-02T18:06:56+00:00` and I am converting it to a date like so: `createdAt: Date.parse(message.modified)` but I suspect more formatting is required for GiftedChat to properly sort the messages. 

Can anyone shed some light on this?

**Comment by angelxmoreno** [comment]
looking at this comment, I suspected the issue really is that no sorting is applied to the messages: https://github.com/FaridSafi/react-native-gifted-chat/issues/1584#issuecomment-570522170

**Comment by angelxmoreno** [comment]
confirmed by contributor comment https://github.com/FaridSafi/react-native-gifted-chat/issues/238#issuecomment-247961489
