### ISSUE TITLE
How can I disable quickreply buttons after pressed

### ISSUE THREAD

**Issue by Arjanvanmaren** [FaridSafi/react-native-gifted-chat#1688]
How can somebody disable the quick reply buttons after being pressed? Currently they are not being disabled after a click
![image](https://user-images.githubusercontent.com/16067826/76950847-f6d58800-690a-11ea-854c-645a56c57b6a.png)

**Comment by basithrehman** [comment]
Is there any work around to disable query button after click?

**Comment by fukemy** [comment]
did u solved this?

**Comment by kumar-aakash86** [comment]
I have found a solution to hide them.
Whenever user is sending next message, before setting the state & calling **GiftedChat.append**, I am creating another object using the previous messages & removing the **quickreplies** from all previous messages.

Inside **onSend**, I am using this code
```
setMessages((previousMessages) => {
  const previos = previousMessages?.map((e) =>
    Object.assign(e, { quickReplies: undefined })
  );
  return GiftedChat.append(previos!, messages);
});
```
