### ISSUE TITLE
Keyboard height on iOS

### ISSUE THREAD

**Issue by TimBroddin** [FaridSafi/react-native-gifted-chat#169]
First: congrats on the release of the new component! Looks like a huge improvement over gifted-messenger!

I'm having trouble with the keyboard leaving a gap (same height as my navbar it seems):

<img width="374" alt="schermafbeelding 2016-07-31 om 15 24 17" src="https://cloud.githubusercontent.com/assets/528287/17276767/1b1764a6-5733-11e6-9536-b4a9fb7b49a5.png">

<img width="375" alt="schermafbeelding 2016-07-31 om 15 24 25" src="https://cloud.githubusercontent.com/assets/528287/17276770/1dad6684-5733-11e6-968a-5c8dd69a6c1c.png">

Any idea on how to fix this? (The navigation I'm using is react-native-navigation)

Thanks

**Comment by FaridSafi** [comment]
Hello @TimBroddin,
Does your GiftedChat container has a paddingBottom ? If yes try to switch to a marginBottom

**Comment by FaridSafi** [comment]
What if you wrap GiftedChat inside a `<View style={{flex: 1}} />` ?
I tried to set up the react-native-navigation but the example is in RN 0.25.1

I will need a code sample to help you more

**Comment by ssmlee04** [comment]
same here. Mine is RN 0.28.0. Keyboard size is about the same as the one above.

**Comment by FaridSafi** [comment]
@ssmlee04 do you use react-native-navigation?

Can you share part of your code guys?

**Comment by ssmlee04** [comment]
I used <TabBarIOS> and a <AdMobBanner>. And it seems the extra height equals to the sum of the two. I'll see if I can come up with something minimum.

**Comment by FaridSafi** [comment]
@ssmlee04 Did you try to wrap GiftedChat inside a <View style={{flex: 1}} /> ?

**Comment by TimBroddin** [comment]
@FaridSafi I'll try to make an example repo tonight

**Comment by FaridSafi** [comment]
@TimBroddin I can reproduce the issue, I will fix it

**Comment by TimBroddin** [comment]
Sorry it took so long @FaridSafi, I made an example repository: https://github.com/TimBroddin/gifted-chat-keyboard-bug

**Comment by FaridSafi** [comment]
I added `bottomOffset` prop in 0.0.5
You need to set the distance from the bottom of the screen

```js
<GiftedChat bottomOffset={56} />
```

**Comment by TimBroddin** [comment]
Works, thanks a lot @FaridSafi!

**Comment by ckuijjer** [comment]
Hi @FaridSafi , thanks for the component and for adding the bottomOffset property.

We were having the same issue as @TimBroddin and tried the fix using the bottomOffset property. As expected the bottomOffset is applied when opening the keyboard, and isn't applied when closing the keyboard. In my case it unfortunately is applied on the initial render with the keyboard closed, as the _onType_ method gets called. This leads to the text input being pushed below the tabbar.

See https://github.com/FaridSafi/react-native-gifted-chat/pull/187 for my pull request

Unfortunately I couldn't get the example repo at https://github.com/TimBroddin/gifted-chat-keyboard-bug to work, to validate that the same issue holds there.

**Comment by ssmlee04** [comment]
Thanks @FaridSafi. bottomOffset can work. was carried away doing something.

**Comment by prabhaav** [comment]
Hi @FaridSafi, the bottomOffset property doesn't help when the textbox is hidden initially.

I'm using RN 0.32.1, navigator experimental and TabBarIOS. The chat input box is being hidden by the tab bar.

My render method: 

  ```
render() {
    return (
      <View style={{flex: 1}}>
        <GiftedChat
          messages={this.state.messages}
          onSend={this.onSend}
          loadEarlier={this.state.loadEarlier}
          user={{
            _id: this.state.id,
            name: this.props.result.first_name,
            avatar: this.props.result.picture,
          }}
          renderBubble={this.renderBubble}
          renderFooter={this.renderFooter}
          bottomOffset={56} 
        />
      </View>
    )
  }
```

The output I see on my iPhone 6s+ simulator:

<img width="467" alt="screen shot 2016-09-11 at 2 16 28 pm" src="https://cloud.githubusercontent.com/assets/11723563/18420578/7fad9148-782a-11e6-82fe-e5f9443358da.png">

**Comment by prabhaav** [comment]
submitted a new issue: [232](https://github.com/FaridSafi/react-native-gifted-chat/issues/232)
