### ISSUE TITLE
renderUsernameOnMessage causes app to stop

### ISSUE THREAD

**Issue by iremlaya** [FaridSafi/react-native-gifted-chat#1696]
I'm trying to show username inside the bubble. I have tried with the props of `Bubble`, such as `usernameStyle, renderUsername` but I couldn't do it. I finally used `renderUsernameOnMessage`, but it forcibly makes my app quit.

#### Code Snippets

App.js:
```
render() {
    return (
      <>
        <GiftedChat
          messages={this.state.messages}
          onSend={(messages) => this.onSend(messages)}
          user={{
            _id: 1,
          }}
          renderUsernameOnMessage
          renderBubble={this.renderBubble}
        />
      </>
    );
  }
```

renderBubble function:
```
renderBubble = (props) => {
    if (isSameUser(props.currentMessage, props.previousMessage) && isSameDay(props.currentMessage, props.previousMessage)) {
      return (
        <Bubble
          usernameStyle={{ left: styles.right, right: styles.left}}
          wrapperStyle={{ left: [styles.left, styles.wrapper], right: [styles.right, styles.wrapper]}}
          {...props}
        />
      );
    }
 
  }

```

* React version: 16.9.0
* React Native version: 0.61.5
* react-native-gifted-chat version: ^0.13.0
* Platform(s) : Android

**Comment by fukemy** [comment]
him can u provide method: isSameUser?

**Comment by meliodev** [comment]
usernameStyle is displayed only on left side.

So use: 
usernameStyle={styles.usernameStyle}
