### ISSUE TITLE
parsePatterns: different styles/colors for left and right bubble

### ISSUE THREAD

**Issue by skizzo** [FaridSafi/react-native-gifted-chat#1705]
#### Issue Description

I can't find a way of using **different colors** for e.g. hashtags, depending on whether they are on the left or on the right, since the only parameter of the `parsePatterns` function is `linkStyle`.

#### Steps to Reproduce / Code Snippets

Follow the example for using `parsePatterns` in chat messages.

#### Expected Results

Maybe an additional parameter that returns the position of the parsed pattern?

#### Additional Information

* Nodejs version: 10.13.0
* React version: 16.9.0
* React Native version: 0.61.5
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: not using TypeScript

**Comment by latovicalmin** [comment]
@skizzo Did you resolve it? If not, there is my workaround solution:

```
parsePatterns={item => [{
  type: 'url',
  style: item && item[0].color === 'black' ? styles.blueLink : styles.whiteLink,
  onPress: this.handleUrlPress,
}, {
  type: 'email',
  style: item && item[0].color === 'black' ? styles.blueLink : styles.whiteLink,
  onPress: this.handleEmailPress,
}]}
```

I'm not sure what these values represent and don't have time to investigate it 😄

**Comment by nsdub** [comment]
You can do this out of the box...

```
import { GiftedChat, Message } from 'react-native-gifted-chat'

  renderMessage = (props) => {
    return (
      <Message
        {...props}
        linkStyle={{
          right: {
            color: 'pink'
          },
          left: {
            color: 'orange'
          }
        }}
      />
    )
  }

render() {
    return (
      <View style={{flex: 1}}>
        <GiftedChat
          ...props
          messages={messages}
          renderMessage={this.renderMessage}
        />
      </View>
    )
  }
