### ISSUE TITLE
MessageContainer.shouldComponentUpdate is preventing real updates

### ISSUE THREAD

**Issue by kfiroo** [FaridSafi/react-native-gifted-chat#171]
Hey,
Looks like the shouldComponentUpdate implementation is a bit off
```javascript
  shouldComponentUpdate(nextProps, nextState) {
    if (this.props.messagesHash === nextProps.messagesHash && this.props.loadEarlier === nextProps.loadEarlier && this.props.footer === nextProps.footer) {
      return false;
    }
    return true;
  }
```
`loadEarlier` and `footer` are functions so their reference is not so likely to change.
`messagesHash` is a nice trick to prevent unnecessary updates, but in this case I feel it might be better to have it per message and not only check id the `_id` changed there.

Any thoughts?

**Comment by FaridSafi** [comment]
Hello @kfiroo thank you for this remark

LoadEarlier is a boolean so it's ok.

Regarding messagesHash, I was thinking that the content of a message can be edited (like on skype or telegram). maybe we can implement a 'messages can be edited' option to enable messagesHash instead of just _id check

**Comment by FaridSafi** [comment]
Regarding footer, in the example/App.js I change the reference as you said to trigger an update. I could'nt find a better option yet. The reason is that invertible scrollview works only for direct children so I don't see how to sleep footer and messages components

**Comment by kfiroo** [comment]
My bad on the `loadEarlier` flag :)

`footer` is still a problem, so does 'renderLoadEarlier' and any other function we pass as a prop that may return a different result without changing the `messagesHash`.

I believe messages will support `status` at some point for **sent / delivered / read** indication, Also having custom data on a message is very useful for rendering "special" messages so I think having `hash` on each `message` object could be a good idea.

I can try to create a PR really quick to move the hash to the message object, which might cause a performance issue actually, but I think it's worth trying.

**Comment by kfiroo** [comment]
@FaridSafi as for the `react-native-invertible-scroll-view` only working with direct children, I think we can still use `ListView` with the `renderScrollComponent` like this:
```javascript
      <ListView
        renderScrollComponent={props => <InvertibleScrollView {...props} inverted />}
        dataSource={this.state.dataSource}
        renderRow={...}
        style={...}
      />
```

**Comment by FaridSafi** [comment]
Let's move renderFooter outside the scroll view as a static bottom view. 
And the status will be at the message level yes

**Comment by FaridSafi** [comment]
Feel free to submit a PR for message status @kfiroo

**Comment by kfiroo** [comment]
@FaridSafi moving the `renderFooter` outside the scroll view will mean it will always be there regardless of the scroll position, I don't think this is the desired behaviour 

I'll try to submit the PR today

**Comment by FaridSafi** [comment]
Yeah static renderFooter would be for "is typing message" like on Slack mobile app

**Comment by kfiroo** [comment]
@FaridSafi Cool :)
