### ISSUE TITLE
The dev env and npm workflow is broken and needs to be improved

### ISSUE THREAD

**Issue by shamilovtim** [FaridSafi/react-native-gifted-chat#1713]
Even though I've had several PRs that I've submitted successfully I still can't effectively work on this plugin without wasting 20 minutes every time I clone it. Please consider bringing the dev environment up to reasonable developer standards with no errors and predictable workflow.

In addition, tsc and tslint is allowed to sit with 30+ errors. There is no reason to keep tslint this strict if it's not maintainable.

**Comment by shamilovtim** [comment]
Current steps that need to happen to get a fork working:

cd node_modules/react-native-gifted-chat && yarn install && yarn lint && yarn build && yarn config:npm && rm -rf node_modules

**Comment by StagasaurusRex** [comment]
Thanks for this. I was trying to work on some issues but couldn't figure out how to test locally

**Comment by shamilovtim** [comment]
Try forking from my fork. It has Husky removed, my typing indicator and tsc will always compile successfully
