### ISSUE TITLE
Send button not clickable on Android

### ISSUE THREAD

**Issue by developer-appdam** [FaridSafi/react-native-gifted-chat#1718]
#### Issue Description

I implemented this component to support a chat in Firebase and it's working really nice but on Android, the send button is not working correctly. It seems that the clickable area is minimal and it's not actually over the word SEND.
On iOS the button it's working correctly.

#### Steps to Reproduce / Code Snippets

 <GiftedChat
                        placeholder={I18n.t('CHAT_TYPE_A_MESSAGE')}
                        messages={this.state.messages}
                        onSend={messages => this.onSend(messages)}
                        user={{
                            _id: user.id,
                        }}
                        textInputProps={{
                            autoCapitalize: 'sentences',
                            keyboardAppearance: 'light',
                            autoCorrect: false
                        }}
                        bottomOffset={Platform.OS === 'ios' ? 85 : 0}
                        keyboardShouldPersistTaps='always'
                        renderBubble={this.renderBubble}
                    />
{ Platform.OS ==='android' && <KeyboardSpacer/> }

#### Expected Results

The button should work on Android and iOS

#### Additional Information

* Nodejs version: 11.15.0
* React version: 2.0.1
* React Native version: 0.61.5
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: 0.60.31

**Comment by haydenbleasel** [comment]
@developer-appdam Did you find a workaround for this? Currently blocked by it.

**Comment by haydenbleasel** [comment]
@developer-appdam Update: I fixed this on Android using `enabledContentGestureInteraction={false}`. I guess my two scrollviews (bottom sheet + giftedchat) were overlapping and for some reason, not allowing the onPress event on the Send button.

**Comment by kalininilya** [comment]
Having the same problem, nothing helps. But for some reason when I use View instead of TextInput next to the send button, send button works (they do not overlap, doublechecked).
