### ISSUE TITLE
Can I do group chat and one to one chat?

### ISSUE THREAD

**Issue by devekoperiOS** [FaridSafi/react-native-gifted-chat#172]
I want to implement one-to-one and group messaging in my react-native app. With this gifted chat can I do group message. I also want to store messages on server. Any one has idea about back end platform?

**Comment by kfiroo** [comment]
@devekoperiOS all the following provide Chat as a Service:
* [Layer](https://layer.com) 
* [Sendbird](https://sendbird.com)
* [QuickBlox](https://quickblox.com)

There are many others, find one that suits your needs :)

**Comment by FaridSafi** [comment]
Sure you can do group chat. Received messages can have different user._id

**Comment by devekoperiOS** [comment]
Thank you @FaridSafi. I will check this one.

**Comment by devekoperiOS** [comment]
Thank you @kfiroo. I want to store chat data on my server. I am familiar with apache. Do you know any open source API that allow me to use my server?

**Comment by devekoperiOS** [comment]
@FaridSafi this is just user interface for chat. What about backend technology?

**Comment by FaridSafi** [comment]
Backend implementation is out of the scope of the component

**Comment by Afsarunnisa** [comment]
We have any possibility to show full name in group chat ? now in group name is starting with same letting its difficult to identify the user. 

How we can show entire name in chat box

**Comment by himanshukk81** [comment]
Hi,
I have implemented group chat in react native but I want to show username for particular user who have send message

**Comment by hanarahmati** [comment]
@himanshukk81 Hi, How do you did this?

**Comment by ashutoshshubam** [comment]
@himanshukk81 can you explain little more how you implement group chat

**Comment by FayyazAliKhan1** [comment]
himanshukk81 can you plz give idea of implementing group chat

**Comment by Durotemy** [comment]
How do i do a one to many and many to one chat.
