### ISSUE TITLE
GiftedChat render, but gives error

### ISSUE THREAD

**Issue by thiagoperesbr** [FaridSafi/react-native-gifted-chat#1720]
#### Issue Description

I'm using tabbar and header, when I click on the tabbar icon to open the chat, it renders, even so it gives an error in the application (according to print).

`export default function Dashboard() {
  const [messages, setMessages] = useState([]);

  useEffect(() => {
    setMessages({
      messages: [
        {
          _id: 1,
          text: 'Hello Developer',
          creatAd: new Date(),
          user: {
            _id: 2,
            name: 'WilsonBot',
            avatar: 'https://placeimg.com/140/140/any',
          },
        },
      ],
    });
  }, []);

  function onSend(messages = []) {
    setMessages(previousState => ({
      messages: GiftedChat.append(previousState.messages, messages),
    }));
  }

  return (
    <KeyboardAvoidingView
      behavior="padding"
      style={{ flex: 1 }}
      keyboardVerticalOffset={30}
    >
      <GiftedChat
        messages={messages}
        onSend={messages => onSend(messages)}
        user={{
          _id: 1,
          name: 'Thiago Peres',
          avatar: 'https://placeimg.com/140/140/any',
        }}
        showUserAvatar
      />
    </KeyboardAvoidingView>
  );
}`

#### Additional Information

* Nodejs version: v10.16.3
* React Native version: v0.61.5
* react-native-gifted-chat version: v0.13.0
* Platform(s) (iOS, Android, or both?): Android

![Screenshot_1585775835](https://user-images.githubusercontent.com/31230416/78188536-ca5f5700-7446-11ea-92b4-2bc2a1261e1e.png)

**Comment by thiagoperesbr** [comment]
Problem solved.

**Comment by fukemy** [comment]
how?
