### ISSUE TITLE
In Expo iOS, keyboard initially covers text input

### ISSUE THREAD

**Issue by bonafidehan** [FaridSafi/react-native-gifted-chat#1721]
#### Issue Description

In Expo iOS, when selecting the text input box the keyboard initially covers text input (left image below). Only when typing the first character, the text input box then appears above the keyboard (right image below). This only impacts iOS, *not* Android.

I've tried various alternatives listed in other bugs like KeySpacer and KeyboardAvoidingView. Also, those previous bugs mentioned Android as the problem, not iOS.

![out](https://user-images.githubusercontent.com/536523/78293937-4bb5f880-74de-11ea-9189-690df2c91c0a.jpeg)

#### Steps to Reproduce / Code Snippets

There are several Views surrounding my GiftedChat component.

```
      <ImageBackground
        source={require('...')}
        style={styles.background}
      >
        <View style={styles.board}>
          <View style={styles.chat}>
            <GiftedChat
              messages={this.state.messages}
              onSend={this.props.db.send.bind(null, 'messages')}
              user={this.user}
              renderMessage={this.renderMessage}
              renderAvatar={this.renderAvatar}
              renderInputToolbar={this.renderInputBar}
            />
          </View>
        </View>
      </ImageBackground>
```
Where `renderInputBar` is:
```
  renderInputBar(props) {
    return (
      <InputToolbar
        {...props}
        containerStyle={{
          backgroundColor: color.hummingWhite,
        }}
      />
    )
  }

```

#### Expected Results

On select of text input, show the text box.

#### Additional Information

* Nodejs version: v12.14.1
* React Native version: 0.61.4
* Expo SDK version: 36.0.0
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): iOS

**Comment by hirentech** [comment]
Yes i am facing same issue. Please suggest any solution.

**Comment by hirentech** [comment]
@bonafidehan i found the solution.

Problem is the tab bar in my case. I am using bottom tab bar from react navigation.

To resolve this issue, you have to hide tab bar for this chat screen. Please refer to following link to hide tab bar for specific screen inside stack navigator wrapped in tab navigator.

Ishttps://github.com/react-navigation/react-navigation/issues/4214

**Comment by bonafidehan** [comment]
@hirentech wow thanks so much! I have a tab bar as well. I'll read that other bug in more detail.

But I'm not clearly understanding the connection between this bug and hiding the tab. Does this mean that we need to add a Keyboard listener and hide the tab dynamically whenever there's a TextInput and the keyboard pops up (via onFocus)?
