### ISSUE TITLE
[Question] Disable inputToolbar by changing the state

### ISSUE THREAD

**Issue by cybermachvi** [FaridSafi/react-native-gifted-chat#1723]
#### Issue Description

I want to be able to hide/show inputToolbar from the click of the button
I have a state variable which is changing with the click of the button. How can I use this state variable to tell the GiftedChat to hide or show the inputToolbar?

**Comment by fractalmarc** [comment]
Like so:
`
const disableNewMessages = {
  minInputToolbarHeight: 0,
  renderInputToolbar: () => null,
};
const [isMessagingDisabled, setIsMessagingDisabled] = useState(false);
// insert some button that calls setIsMessagingDisabled
<GiftedChat {...yourUsualProps} {...(isMessagingDisabled && disableNewMessages)} />
`

**Comment by chmiiller** [comment]
Beautiful solution @fractalmarc. It works for me, I think we can close this issue
