### ISSUE TITLE
Chat Bubble shape is not same on all bubble

### ISSUE THREAD

**Issue by ramkumarb** [FaridSafi/react-native-gifted-chat#1725]
#### Issue Description
Chat Bubble style is not same on all bubble. I have used borderRadius: 30, For first message bubble shape is properly shown, from second message bubble shape of bubble is getting differed

#### Expected Results
I would like to get  all the chat bubble to be in same shape

#### Additional Information
 wrapperStyle={{
                        right: {
                            backgroundColor: colors.chatPurple,
                            borderRadius: 30,
                            borderBottomRightRadius: 30,
                            marginBottom: 10,
                            padding: 5,
                            right: 15,
                            justifyContent: "flex-end",
                            alignSelf: 'stretch',
                            marginLeft: 0,
                            alignSelf: "center"
                        },
                        left: {
                            backgroundColor: colors.lightGreen,
                            borderRadius: 30,
                            marginBottom: 20,
                            padding: 5,
                            left: -30
                        }
                    }}
![IMG_0001](https://user-images.githubusercontent.com/7746172/78499050-f68f1680-776b-11ea-9af0-51f2756875ef.PNG)

**Comment by kalyanijamunkar10** [comment]
getting same issue. @ramkumarb  any luck on this?

**Comment by amak07** [comment]
@ramkumarb @kalyanijamunkar10 same issue here. any chance on why inconsistent bubble spacing is occurring? 
![IMG_0911](https://user-images.githubusercontent.com/7268594/88617346-0bb1ed00-d05c-11ea-99eb-b26001392b6f.PNG)

**Comment by kalyanijamunkar10** [comment]
@amak07 you must have added margin or padding for bubble. I have not added any styles for bubble and its working for me. 
renderBubble(props) {
  return (
    <Bubble
      {...props}

      wrapperStyle={{
        left: {
           backgroundColor: '#ffffff',
        },
        right:{
          backgroundColor: '#6ac1fc',
        }
      }}
    />
  );
}

**Comment by kalyanijamunkar10** [comment]
hey @ramkumarb  try using renderCustomView props.
