### ISSUE TITLE
No audio player shown for audio message.

### ISSUE THREAD

**Issue by zholmes1** [FaridSafi/react-native-gifted-chat#1733]
#### Issue Description

I am trying to get audio clips to show in my chat, but they are only displaying as an empty bubble.

https://photos.app.goo.gl/hzrgAACxzTwuRhYL6

#### Steps to Reproduce / Code Snippets

This is the IMessage object that is in my IMessage[] messages prop for GiftedChat. audio is a string, and image/text are undefined.

`{
    "_id": 27,
    "audio": "https://s3.us-east-2.amazonaws.com/storage-app-dev/mp3/cb62d4ctnk8uibk1v.mp3",
    "createdAt": 2020-04-10T18:11:40.422Z,
    "image": undefined,
    "text": undefined,
    "user": Object {
      "_id": "2s6aggy7rtjtnp6a8c",
      "avatar": "https://s3.us-east-2.amazonaws.com/storage-app-dev/cb62d4exdk8t4gnhf/thumbnail-26170527_10214525576748161_8444045049145038093_o.jpg",
      "name": "Zach H",
}`

#### Expected Results

Bubble should have an audio player

#### Additional Information

* Nodejs version: 12.16.1
* React version: 16.9.0
* React Native version: 0.61.0
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: 3.7.2

**Comment by raazatul7** [comment]
@zholmes1 Can you help me with the audio thing, it's saying audio is not implemented by Gifted chat

**Comment by zholmes1** [comment]
Gifted chat doesn't have a built in module to play audio. You have to implement it yourself and add a renderMessageAudio prop

**Comment by raazatul7** [comment]
> Gifted chat doesn't have a built in module to play audio. You have to implement it yourself and add a renderMessageAudio prop

Gotcha!
Thanks for replying mate.

**Comment by 0mayur1** [comment]
@zholmes1 please send your code

**Comment by zholmes1** [comment]
@elviskankola1 Already answered this sufficiently. All you need to do is create an audio component and supply it as a render prop.to GiftedChat. I just made a play button, expo-av to start playing the sound clip, and change it to a pause button while the clip is playing. Once the clip is done, change it back to a play button. I didn't bother making a seek bar.

**Comment by Quaid5050** [comment]
```
import { Audio } from 'expo-av';

function AudioMessage(props) {
  const [isPlaying, setIsPlaying] = useState(false);
  const [sound, setSound] = useState(null);

  useEffect(() => {
    const loadAudio = async () => {
      const { sound: newSound } = await Audio.Sound.createAsync({ uri: props.currentMessage.audio });
      setSound(newSound);
    };
    loadAudio();

    return () => sound && sound.unloadAsync(); 
  }, [props.currentMessage.audio]);

  const handlePlayPause = async () => {
    if (isPlaying) {
      await sound.pauseAsync();
    } else {
      await sound.playAsync();
    }
    setIsPlaying(!isPlaying);
  };

  return (
    // Your audio message UI with a play/pause button
    <View style={styles.audioContainer}>
      <TouchableOpacity onPress={handlePlayPause}>
        <Icon name={isPlaying ? 'pause' : 'play'} size={30} />
      </TouchableOpacity>
    </View>
  );
}

```import { GiftedChat } from '@react-native-community/gifted-chat';

// ... other imports 

<GiftedChat
  messages={messages}
  onSend={messages => onSend(messages)}
  user={{ _id: 1 }}

  renderMessageAudio={(props) => <AudioMessage {...props} />}
  // ... other props
/>
