### ISSUE TITLE
Custom keyboard

### ISSUE THREAD

**Issue by samgermain** [FaridSafi/react-native-gifted-chat#1734]
I want to change the keyboard so that the default keyboard is a selection of stickers, but you could switch to the regular keyboard. Do you know the easiest way to do this? Would it be easy?

**Comment by samgermain** [comment]
I created a custom keyboard using react-native-keyboard-input . Is there a way to simply replace the keyboard in [react-native-gifted-chat](https://github.com/wix/react-native-keyboard-input) with a keyboard like this?

**Comment by yoolsylva** [comment]
you need set  renderInputToolbar={() => null} and place custom keyboard bottom:

`  <GiftedChat
      .... //other props
      renderInputToolbar={() => null}
   />
   {this.renderCustomKeyboard()}
`
