### ISSUE TITLE
keyboard hide as soon as the textinput show

### ISSUE THREAD

**Issue by cq0702** [FaridSafi/react-native-gifted-chat#1737]
#### Issue Description

keyboard shows and hides as soon as the textinput shows. I use the renderBubble and textinput is on the renderBubble.It happens only on Android.
#### Steps to Reproduce / Code Snippets

<GiftedChat
                        user={{
                            _id: '1',
                        }}
                        messagesContainerStyle={{paddingBottom: 40}}
                        inverted={false}
                        renderAvatarOnTop={true}
                        messages={this.state.messageData}
                        showUserAvatar={true}
                        renderBubble={(messages)=>this._renderBubble(messages)}
                        renderChatEmpty={this._renderChatEmpty}
                        renderAvatar={this._renderAvatar}
                    />
                    {
                        Platform.OS === 'android' && <KeyboardAvoidingView behavior="padding" keyboardVerticalOffset={80}/>
                    }

_renderBubble(messages) 
        return (
            <View>
                <TextInput
                        ref={t=>this.sendInputText=t}
                        style={styles.sendTextInput}
                        placeholder='enter your price...'
                        returnKeyType='done'
                        blurOnSubmit={true}
                        onChangeText={this._onChangeText}
                        placeholderTextColor={'#d5d5d5'}
                    />
            </View>
        )
    }

#### Expected Results

the textinput shows and I can enter the value.

#### Additional Information

* Nodejs version: [FILL THIS OUT]
v10.15.0
* React version: [FILL THIS OUT]
16.9.0
* React Native version: [FILL THIS OUT]
0.61.5
* react-native-gifted-chat version: [FILL THIS OUT]
0.13.0
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
android
* TypeScript version: [FILL THIS OUT]

**Comment by perrosnk** [comment]
I am having the same issue. Has anybody found a solution?
For me it only happens on Android real devices.

**Comment by perrosnk** [comment]
Could it be related to some internal function of GiftedChat which is related to this [issue](https://stackoverflow.com/questions/56180263/react-native-textinput-setstate-hides-keyboard)?

**Comment by perrosnk** [comment]
I removed `Platform.OS === 'android' && <KeyboardAvoidingView behavior="padding" keyboardVerticalOffset={180}/>` and the issue was solved
