### ISSUE TITLE
Is there a way to change the Avatar position?

### ISSUE THREAD

**Issue by flipps-dev** [FaridSafi/react-native-gifted-chat#1738]
#### Issue Description

Hello I'm just trying to move the avatar to the inner position

#### Expected Results

![pHGMD](https://user-images.githubusercontent.com/22148682/79074319-fc48a700-7ceb-11ea-8c08-b7d1402603e6.png)

#### Additional Information

* Nodejs version: 12.9.1
* React version: 16.9
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): Both
* TypeScript version: [FILL THIS OUT]

**Comment by flipps-dev** [comment]
Here is my personal solution:

https://stackoverflow.com/questions/61146939/edit-avatar-position-in-react-native-gifted-chat

**Comment by jaswant25** [comment]
We need this functionality

**Comment by baltagih2** [comment]
Hello all, a simple Avatar position prop that could represent "top", "center", "bottom" with "bottom" as default (as it currently displays at the bottom left end corner of a bubble) with maybe "left" and "right" too should be sufficient to close this issue and solve many avatar related problems.

Any other use-case, could go for the renderAvatar prop to customize what we need
