### ISSUE TITLE
textInputStyle does not affect whole input box

### ISSUE THREAD

**Issue by patrickjane** [FaridSafi/react-native-gifted-chat#1739]
#### Issue Description

I am trying to add support for dark mode in my app, but I am having issues with the input bar in gifted chat. I found the `textInputStyle` property, however it does not seem to cover the whole input bar.

See:     
![Screenshot](https://i.imgur.com/uGxTLvG.png)

How can I make the rest of the input bar with dark background color?

#### Steps to Reproduce / Code Snippets

Code I am using:

```
   return (
      <SafeAreaView style={ styles.container }>
         <GiftedChat
            inverted={true}
            placeholder="Nachricht"
            renderBubble={_renderBubble}
            renderTime={_renderTime}
            renderSend={_renderSend}
            messages={messages}
            onSend={_sendMessage}
            listViewProps={{ style: styles.contentContainer}}
            textInputStyle={styles.contentContainer}
            user={{
               _id: 1,
            }}
         />
      </SafeAreaView>
   );
```

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: 0.61.5
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): iOS (simulator)
* TypeScript version: [FILL THIS OUT]

**Comment by Trashpants** [comment]
I'm trying to theme this too. It seems to be kind of messy to me. For some reason the input on iOS is weirdly skewed and im struggling to align it 😢 

The way it seems to be is to override the `renderInputToolbar`

so you'd have

```
<GiftedChat
        messages={messages}
        onSend={(message) => {
          console.log(message);
        }}
        user={{
          _id: 1,
        }}
        renderInputToolbar={(props) => MessengerBarContainer(props)}
        renderComposer={(props) => MessengerBar(props)}
        renderSend={(props) => MessengerSend(props)}
 />
```
and then

```
import { Composer, InputToolbar, Send } from "react-native-gifted-chat";

const MessengerBarContainer = (props) => {
  return (
    <InputToolbar
      {...props}
      containerStyle={{
        backgroundColor: colors.grey200,
        alignContent: "center",
        justifyContent: "center",
        borderWidth: 0,
        paddingTop: 6,
        marginHorizontal: 6,
        borderRadius: 32,
        borderTopColor: "transparent",
      }}
    />
  );
};
```

**Comment by amloelxer** [comment]
@patrickjane, @Trashpants is correct. You need to provide a custom `renderInputToolbar` method and in there you can provide a custom container background color. The input box itself is called `Composer` and its parent container container is called the `InputToolbar`. That being said, I don't think this library is very intuitive and I wish it had better docs.

**Comment by mkhoussid** [comment]
Looking at the source code, this is the component to override.

You'd have,

```
<GiftedChat
  renderInputToolbar={(props) => <CustomInputToolbar {...props} />}
/>
```
And `CustomInputToolbar.js` would look like,
```
import React from 'react';
import { StyleSheet } from 'react-native';
import { InputToolbar } from 'react-native-gifted-chat';

const styles = StyleSheet.create({
  inputToolbarBackground: {
    backgroundColor: 'blue',
  },
});

export default = ({ messages, ...props }) => (
  <InputToolbar containerStyle={styles.inputToolbarBackground} {...props} />
);
```
![Screenshot 2020-05-16 at 18 39 23](https://user-images.githubusercontent.com/44326107/82123913-9e085b80-97a4-11ea-8b9d-9b3bb2a0abbc.png)
