### ISSUE TITLE
Error using custom inputToolBar

### ISSUE THREAD

**Issue by nabn** [FaridSafi/react-native-gifted-chat#174]
I don't know if this feature is ready yet, but I used it because I saw it on the sources. When I try to use `onSend` from the props on custom inputbox, I get this error: 
`One of the sources for assign has an enumerable key on the prototype chain. This is an edge case that we do not support. This error is a performance optimization and not spec compliant.`

On tracing a little, I think the error is coming from here: GiftedChat.js line 298:
```
   messages = messages.map((message) => {
      return {
        ...message,
        user: this.props.user,
        createdAt: new Date(),
        _id: 'temp-id-' + Math.round(Math.random() * 1000000),
      };
    });
```
Maybe it's an issue with `Object.assign` ? I think this is similar: (https://github.com/facebook/react-native/issues/5507)

Seems like I can't replace the es7 syntax with `Object.assign` because `message` is a `Proxy`

**Comment by FaridSafi** [comment]
Hello,
What are you passing to `onSend` ?
Can you share your custom inputToolbar ?

**Comment by nabn** [comment]
This is how it looks: 
rendering giftedchat: 
```
        <GiftedChat
          messages={this.state.messages}
          onSend={this.onSend}
          renderInputToolbar={this.renderInputToolbar}
          user={{
            _id: 1,
          }}
        />

```
renderInputToolBar:
`renderInputToolBar = props => <InputBox {...props} />`

render function for `InputBox`: 
```
<View style={styles.container}>
        <TouchableOpacity
          activeOpacity={0.6}
          style={styles.cameraButton}
          onPress={this.props.handleCameraPress} >
          <Icon name='md-camera' style={styles.cameraIcon} />
        </TouchableOpacity>
        <TextInput
          style={styles.textInput}
          placeholder={CHAT_INPUT_PLACEHOLDER}
          returnKeyType={'send'}
          onChangeText={message => this.setState({ message })}
          value={this.state.message}
          blurOnSubmit={false}
          ref={'chatInputRef'} />
        <Button
          onPress={this.props.onSend}
          containerStyle={styles.sendButtonContainer}
          style={styles.sendButton} >
          Send
        </Button>
      </View>
```

**Comment by FaridSafi** [comment]
I recommend you to copy `src/InputToolbar.js` and to customize it instead of starting from fresh component.

**Comment by FaridSafi** [comment]
InputToolbar receives `text` and `onChange` props which have to be used by the TextInput composer.

Regarding the send button, you can check `src/Send.js`
```js
  this.props.onSend({text: this.props.text.trim()}, true);
```

**Comment by nabn** [comment]
Thanks. will follow your instructions

**Comment by luisfuertes** [comment]
I am trying the same. 

I import to my code InputToolBar.js, Composer.js and Send.js.

Before y add this prop to GiftedMessenger:
`renderInputToolBar={this.renderInputToolbar}` 

And renderInputToolbar function:
```
  renderInputToolbar(){
    return(
      <InputToolbar />
    )
  }
```

But i think it continue use their own inputToolbar. What im doing wrong?
