### ISSUE TITLE
RN 0.62 and expo dependency

### ISSUE THREAD

**Issue by edgar0011** [FaridSafi/react-native-gifted-chat#1741]
#### Issue Description

useless dependency on expo action sheet

#### Steps to Reproduce / Code Snippets

update RN to  0.62.0

#### Expected Results

no Expo dependency

#### Additional Information
https://github.com/facebook/react-native/issues/28423

**Comment by juanjsebgarcia** [comment]
See Issue #1703

**Comment by xcarpentier** [comment]
Fix in 0.14.0
