### ISSUE TITLE
Grouping the messages by day

### ISSUE THREAD

**Issue by Bayramito** [FaridSafi/react-native-gifted-chat#1744]
Hello dear Devs,

Is anybody knows how to group messages per day?

I mean i won't write here long text just leaving the link of my discusion that i created on stackoverflow.

I gave all the information here. If you could help me to achieve this, i ll be happy thank you.

Becouse somehow i could not understand how you done this. :)

Here is the original topic
[Whatsapp style scrolling date](https://stackoverflow.com/questions/61237564/how-can-i-show-days-by-group-like-whatsapp-chat-screen)

**Comment by haydenbleasel** [comment]
@Bayramito you can just sort messages:

```
function sortByDate(a, b) {
    return a.createdAt < b.createdAt;
}

return (
    <GiftedChat messages={messages.sort(sortByDate)} ... />
);
```

**Comment by Bayramito** [comment]
Hi there,

The problem was not the sorting the elements from bottom to top, i
already do this before putting the data into the flatlist. + I can
already send them from DB sorted via query.

The problem was, in a inverted flatlist, how they do this kind a grouping,
to show day by day. If you noticed on whatsapp they only show once in a
day, if you scroll up to previous messages on your conversation you will
see that.

I can achieve a thing close to that also, but its not exactly the same.

You can read my stackoverflow question for more infoırmation here
https://stackoverflow.com/questions/61237564/how-can-i-show-days-by-group-like-whatsapp-chat-screen


Hayden Bleasel <notifications@github.com>, 26 Nis 2020 Paz, 13:20 tarihinde
şunu yazdı:
