### ISSUE TITLE
Composer Actions - How to send images in react native gifted chat?

### ISSUE THREAD

**Issue by tanakachamisa** [FaridSafi/react-native-gifted-chat#1745]
How can I make use of the composer actions such as attaching and sending images etc?

**Comment by andersoncscz** [comment]
You can use react-native-image-picker for pick an image from camera or gallery, implement a handlePickImage function for take one pic and also an onSend functionm which will send the image selected to your backend, example:

```
import {
  Actions,
  ActionsProps,
  ...
} from 'react-native-gifted-chat'
export default function ChatScreen() {
  ...
  function renderActions(props: Readonly<ActionsProps>) {
    return (
      <Actions
        {...props}
        options={{
          ['Send Image']: handlePickImage,
        }}
        icon={() => (
          <Icon name={'attachment'} size={28} color={AppTheme.colors.primary} />
        )}
        onSend={args => console.log(args)}
      />
    )
  }
  ...
  return (
      <GiftedChat
        ...
        renderActions={renderActions}
        ...
      />
  )
}
```

**Comment by HarshitMadhav** [comment]
@andersoncscz Hi I am doing the same as you have posted but I am unable to pass the uri of image picked. Can you help me on this issue?

**Comment by andersoncscz** [comment]
Hi @HarshitMadhav take a look at onSend method in this example: https://github.com/FaridSafi/react-native-gifted-chat/blob/master/App.tsx

Basically, you just have to save the uri picked by react-native-image-picker, and, in your onSend method take this uri from your state, put it in your message object, and send it to your backend, and after the message has been sent, clear the uri from the state. 
I'm not using this lib anymore, I built my own ChatScreen and components for a private project.

I'm using graphql, what I do is:

```
...
import {ReactNativeFile} from 'apollo-upload-client'
...
function GroupMessageInput({group}: IProps) {
  ...
  const {sendGroupMessage} = useMutationSendMessage(group.id)
  ...
  function handleSendMessage() {
    try {
      let attachedImage
      if (imageSource.uri.length > 0) {
        attachedImage = new ReactNativeFile({
          uri: imageSource.uri,
          name: 'messageImage.jpg',
          type: 'image/jpeg',
        })
      }

      const data: GroupMessageInput = {
        groupId: group.id,
        text: state.text,
        sentAt: new Date().toString(),
        attachedImage,
      }

      sendGroupMessage({
        variables: {
          data,
        },
        optimisticResponse: {
           ...
        },
      })

      setState(initialState)
    } catch (error) {
      ...
    }
  }
}

export default GroupMessageInput
```

Hope this help.

**Comment by HarshitMadhav** [comment]
@andersoncscz Thank you so much for the help!! Cheers!!

**Comment by HarshitMadhav** [comment]
@andersoncscz Lovely! I followed what you said and it worked. Thanks and Cheers!! :)

**Comment by djaoui** [comment]
Hi, I manage to upload an Image on Firebase and then I send a message in the form of:

`const message = {
timestamp: firebase.database.ServerValue.TIMESTAMP,
user: {
_id: item.user.uid,
avatar: item.user.photoURL,
name: item.user.displayName,
},
image: item.image,
}`

or

`const message = {
timestamp: firebase.database.ServerValue.TIMESTAMP,
user: {
_id: item.user.uid,
avatar: item.user.photoURL,
name: item.user.displayName,
},
image: item.image,
text:'',
}`

Which is the same than text messages.

I can see a new message in the GiftedChat feed but Image doesn't appear. I just can get the image to be displayed.

What am I doing wrong? Any idea ? I'm desperate.

Urls to Image in Firebase are like that https://firebasestorage.googleapis.com/v0/b/whatsappclone-5c0a6.appspot.com/o/avatar%2F5bf311ce-99bd-43ff-90d2-fd8294294bad?alt=media&token=44c2f107-adef-418d-9506-ac1fbe848c03

Avatars appear correctly in GiftedChat so there is no reason why Images wouldn't correct ?

Thanks

**Comment by JeaIousy** [comment]
i have same probblem

**Comment by d-taiwo** [comment]
Hi @andersoncscz can you please show the handlePickImage function? I am still confused here. I have something similar where I would like to send a word document/pdf file instead of an image. Can you please help here? Here is my code so far below:

    renderActions(props) {
           return(
                 <Actions
                     {...props}
                     options={{
                        ['Document']: (props) => {console.log("document")},
                        Cancel: (props) => {console.log("Cancel")}
                     }}
                     icon={() => (
                         <Ionicons
                              name={'add'}
                              size={28}
                              color={'#0077ff'}
                              style={{left:0, bottom:0}}                           
                           />
                        )}
                       onSend={args => console.log(args)}
                    />
                  )
               }

**Comment by hessaQongfu** [comment]
i have issue that the image dont appear in chat

**Comment by Thomasosho** [comment]
> image: item.image,

How do we render image in chat

**Comment by 1ashishkhanna** [comment]
import { View, Platform, KeyboardAvoidingView, TouchableOpacity } from "react-native";
import React, { useLayoutEffect, useEffect, useState, useCallback } from "react";
import { useNavigation } from "@react-navigation/native";
import { GiftedChat } from 'react-native-gifted-chat'
import * as ImagePicker from 'expo-image-picker';



import { PhoneIcon, PhotoIcon } from "react-native-heroicons/outline";

const ChatScreen = () => {
  const navigation = useNavigation();
  useLayoutEffect(() => {
    navigation.setOptions({
      headerTitle: "Chat With Us",
      // headerShown: false,
    });
  }, []);

  const [messages, setMessages] = useState([]);

  useEffect(() => {
    setMessages([
      {
        _id: 1,
        text: 'Hello developer',
        createdAt: new Date(),
        user: {
          _id: 2,
          name: 'React Native',
          avatar: 'https://placeimg.com/140/140/any',
        },
      },
    ])
  }, []);

  const handleChoosePhoto = () => {
    const options = {
      noData: true,
    };
    ImagePicker.launchImageLibraryAsync(options, response => {
      if (response.uri) {
        const image = {
          uri: response.uri,
          type: response.type,
          name: response.fileName,
        };
        const message = {
          _id: messages.length + 1,
          text: '',
          createdAt: new Date(),
          user: {
            _id: 1,
          },
          image: image,
        };
        setMessages(previousMessages => GiftedChat.append(previousMessages, [message]));
      }
    });
  };

  const onSend = useCallback((messages = []) => {
    setMessages(previousMessages => GiftedChat.append(previousMessages, messages))
  }, [])

  return (
    <View style={{ flex: 1, backgroundColor: '#fff' }}>
      <GiftedChat
        messages={messages}
        onSend={messages => onSend(messages)}
        user={{
          _id: 1,
        }}
        renderActions={() => (
          <TouchableOpacity onPress={handleChoosePhoto}>
            <PhotoIcon name="image" size={30} color="#588ac0" />
          </TouchableOpacity>
        )}
      />
      {Platform.OS === 'android' && <KeyboardAvoidingView behavior="padding" />}
    </View>
  );
};

export default ChatScreen;
