### ISSUE TITLE
onLongPress should pass the touch event

### ISSUE THREAD

**Issue by charles-goode** [FaridSafi/react-native-gifted-chat#1746]
#### Issue Description
The onLongPress prop passed to Bubble doesn't receive the native press event (in fact the default doesn't catch the parameter either). This could be fixed by adding 3 characters to the code ('e' in 2 places and a comma to pass another parameter to the custom onLongPress). This would be very helpful in my use case (render an action bar right where the long press occured). 

It is however possible to get around this by overwriting onLongPress for Bubble by passing an onLongPress through the touchableProps of the Bubble.

#### Additional Information

* Nodejs version: v12.14.0
* Expo SDK37
* react-native-gifted-chat version: 0.13
* Platform(s) (iOS, Android, or both?): Both

**Comment by Developer-Raman** [comment]
+1
