### ISSUE TITLE
error Couldn't find the binary git error while adding library to react native project

### ISSUE THREAD

**Issue by zahrat** [FaridSafi/react-native-gifted-chat#1752]
#### Issue Description

I want to use gifted-chat library but when i run the 'yarn add react-native-gifted-chat' i got the 
```
'error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.'
``` 
error.
I don't where is the problem. help please
#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: "10.13.0"
* React version:"16.11.0"
* React Native version: "^0.62.2"
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): "both"
* TypeScript version: [FILL THIS OUT]

**Comment by elaveinee** [comment]
did u solve the error??

**Comment by ChallengerDefier** [comment]
I encountered the same problem, how to solve it?

**Comment by hendrikrodriguezguillen** [comment]
any solution for this problem
