### ISSUE TITLE
Why no infinite scroll?

### ISSUE THREAD

**Issue by KDederichs** [FaridSafi/react-native-gifted-chat#1753]
Why isn't infinite scrolling through the chat supported out of the box?
It took me a good while to figure out that you can actually pass something like that into the `listViewProps` to enable an infinite and seamless loading of older messages without having to click that load earlier button over and over and over...
```
{
      inverted: true,
      onEndReached,
      onEndReachedThreshold: 0.8,
    }
```

I'm sure I'm not the only one that would have use for that feature....

**Comment by xcarpentier** [comment]
Done
