### ISSUE TITLE
Request: Documentation example change request to functional approach.

### ISSUE THREAD

**Issue by imAunAbbas** [FaridSafi/react-native-gifted-chat#1754]
Hi, please update the example given in the documentation of this package. I hope it will be useful for new developers as now mostly programming approach is shifted towards `react-hooks`. Kindly review this and update this in next release if possible.
Thanks

**Comment by Ryannnkl** [comment]
Também tô com problemas pra mudar de classe por hooks por causa desse prevState

**Comment by imAunAbbas** [comment]
@Ryannnkl I've found the solution, you can now use `hooks` like this:


```
const ChatScreen = () => {
    const [messages, setMessages] = useState([]);

    const sendMessage = (text) => {
        let temp = GiftedChat.append(messages, text[0]);
        setMessages(temp);
    }

    return (
        <GiftedChat
            messages={messages}
            onSend={text => sendMessage(text)}
        />
    );
}
```

This method worked for me.
