### ISSUE TITLE
How to configure gift-chat to send message when enter key is pressed?

### ISSUE THREAD

**Issue by iswetak** [FaridSafi/react-native-gifted-chat#1755]
how to solve this issue when 
i have to click on enter from system keyboard then message are not send 

is it possible to
when keypress enter = send message
When keypress shift + enter = new line message

* Nodejs version: latest
* React version: 0.1.0
* React Native version: latest
*  react-native-gifted-chat version: "0.10.0-beta.web.26
* TypeScript version: 3.6.3

**Comment by DaleWebb** [comment]
Here's what I did:
```tsx
export const ChatComposer = (
  props: ComposerProps & {
    // GiftedChat passes its props to all of its `render*()`
    onSend: SendProps<IMessage>['onSend'];
    text: SendProps<IMessage>['text'];
  },
) => (
  <Composer
    {...props}
    textInputStyle={{
      fontFamily: theme.textStyles.copyL.fontFamily,
      fontSize: theme.textStyles.copyL.fontSize,
      marginLeft: theme.space.onePointSix,
      marginRight: 0,
      marginTop: theme.space.onePointSix,
      marginBottom: 0,
    }}
    textInputProps={{
      ...props.textInputProps,
      // for enabling the Return key to send a message only on web
      blurOnSubmit: Platform.OS === 'web',
      onSubmitEditing:
        Platform.OS === 'web'
          ? () => {
              if (props.text && props.onSend) {
                props.onSend({text: props.text.trim()}, true);
              }
            }
          : undefined,
    }}
  />
);
```

**Comment by iswetak** [comment]
hii it didn't work

**Comment by iswetak** [comment]
Hii Dale Alexander Webb

It didn't work

I have  shared  my github iswetak/IEchat please one time check

**Comment by iswetak** [comment]
Hii

onSend: SendProps<IMessage>['onSend'];
      text: SendProps<IMessage>['text'];

I got error in IMessage. I had import IMessage but noy solved

When I have applied
onSend: SendProps['onSend'];
      text: SendProps['text'];
this code solve the error but onsend enter button didn't work

please help

**Comment by DaleWebb** [comment]
@iswetak - I think you've passed in the custom `ChatComposer` incorrectly. To correct it, you could do either:
```jsx
<GiftedChat renderComposer{ChatComposer} />
```
or rename `ChatComposer` to `renderComposer`

**Comment by iswetak** [comment]
hii

 it's working now thanks

**Comment by devjaw** [comment]
@DaleWebb i'mt trying this method in the android, it works fine but the issue is the keyboard is dismissed after sending the message.

**Comment by DaleWebb** [comment]
I probably didn’t test it on Android...
