### ISSUE TITLE
(0.13.0 vs 0.14.0)

### ISSUE THREAD

**Issue by glenvollmer** [FaridSafi/react-native-gifted-chat#1759]
#### Issue Description
The README says 0.13.0, but the package.json lists the project as being 0.14.0. I would like to install the 0.14.0 version of the project to use the isTyping functionality, but I am only able to install the 0.13.0 version with npm. I was just curious as to when 0.14.0 will be available via npm?

**Comment by shamilovtim** [comment]
Hi, 0.14.0 hasn't been released yet. If you want to play with it or use it you can use my fork under my Github profile.

**Comment by xcarpentier** [comment]
0.14.0 released!

**Comment by vinpro24** [comment]
> 0.14.0 released!

Not isTyping yet?

**Comment by xcarpentier** [comment]
@vinpro24 yes `isTyping` is in v0.14.0

**Comment by vinpro24** [comment]
> @vinpro24 yes `isTyping` is in v0.14.0

Nothing isTyping={true} I tried v0.14.0 and latest version 0.15.3

**Comment by xcarpentier** [comment]
Can you provide more informations like: environnement where you test, etc.
And then create a PR or issue.
