### ISSUE TITLE
renderChatEmpty is flipped

### ISSUE THREAD

**Issue by rptoma** [FaridSafi/react-native-gifted-chat#1761]
#### Issue Description
The empty chat view that is generated by renderChatEmpty is flipped.

#### Steps to Reproduce / Code Snippets
```
private renderChatEmpty() {
    return (
      <View
        style={{
          flex: 1,
          alignSelf: 'center',
          justifyContent: 'center'
        }}
      >
        <Text> Say hello to your buddy</Text>
      </View>
    );
  }

```

<img width="397" alt="Screenshot 2020-05-03 at 17 50 31" src="https://user-images.githubusercontent.com/19636974/80917308-97babe00-8d66-11ea-82ca-7de4bdffc60a.png">

[FILL THIS OUT]

#### Expected Results

To see the view as returned in the function 🙂 

#### Additional Information

A temporary "fix" is to add `transform: [{ scaleY: -1 }]` in the empty view style.

* React Native version: 0.61.5
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): iOS (at least)

**Comment by waelvilla** [comment]
Can you post your <GiftedChat /> component here?

**Comment by StagasaurusRex** [comment]
This is a bug with react-native, not gifted-chat. 
https://github.com/facebook/react-native/issues/21196

**Comment by amirduran** [comment]
There is a Bug with flat list. Use css to tranform (rotate) your chat for 180 deegres when messages.length == 0

**Comment by kiitos-smasri** [comment]
same issue am facing, any solutions?

**Comment by waelvilla** [comment]
haven't found anything yet

**Comment by JayantJoseph** [comment]
![image](https://user-images.githubusercontent.com/38125115/127860534-c9b169ad-5641-4724-aaf0-0ba951b633dc.png)

I think this `transform: [{ scaleY: -1 }]` is the reason for this issue. When removing it from `node_modules\react-native-gifted-chat\lib\MessageContainer.js`, this issue was fixed. Also, when giving `inverted={false}` prop this was not present.

**Comment by BLOCKMATERIAL** [comment]
Problem actually!

**Comment by alecdewitz** [comment]
This worked for me

```
renderChatEmpty={() => (
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
            <Text
              style={{
                transform: [{ scaleY: -1 }],
              }}>
              No messages yet
            </Text>
        </View>
      )}
```

**Comment by LaGregance** [comment]
Same problem, it's very weird.
Indeed using `transform: [{ scaleY: -1 }]` work but it's a dirty fix and the issue shouldn't be closed.

For now I prefer to use this method:
```tsx
<GiftedChat
      listViewProps={{
        ListEmptyComponent: (
          <View>
            <Text>List Empty</Text>
          </View>
        ),
      }}
      {...others}
    />
```

**Comment by xchwarze** [comment]
This case should be clarified in the documentation...
For me the correct solution would be this:
```
<GiftedChat
                messages={messages}
                onSend={(text) => onSend(text)}
                renderAvatar={renderAvatar}
                renderChatEmpty={renderChatEmpty}
                listViewProps={{
                    inverted: messages.length !== 0,
                }}
                user={{
                    _id: 1,
                }}
            />
```

**Comment by Code-Victor** [comment]
> listViewProps={{
>                     inverted: messages.length !== 0,
>                 }}

This worked perfectly for my use case.
Thanks @xchwarze
