### ISSUE TITLE
Can't get the simple example to work.

### ISSUE THREAD

**Issue by nbastoWM** [FaridSafi/react-native-gifted-chat#1762]
#### Issue Description

I just installed this package in a new project I just created with "react-native init" but I can't seem to show the chat from a simple example. 
I don't use Expo.

#### Steps to Reproduce / Code Snippets

This is the only code I added to a fresh App.

```
import React, {useState} from 'react';
import {SafeAreaView, ScrollView, StatusBar, Text} from 'react-native';
import {GiftedChat} from 'react-native-gifted-chat';

const App = () => {
  const [messages, setMessages] = useState([
    {
      _id: 1,
      text: 'Hello developer',
      createdAt: new Date(),
      user: {
        _id: 2,
        name: 'Name',
      },
    },
  ]);

  const onSend = (newMessage = []) => {
    setMessages(GiftedChat.append(messages, newMessage));
  };

  return (
    <>
      <SafeAreaView>
        <Text>xxx</Text>
        <GiftedChat
          messages={messages}
          onSend={newMessage => onSend(newMessage)}
          user={{
            _id: 1,
          }}
        />
        <Text>xxx</Text>
      </SafeAreaView>
    </>
  );
};

export default App;
```

#### Expected Results

I hoped to see a chat interface but with my code I just see xxx followed by xxx.

#### Additional Information

* Nodejs version: v8.12.0
* React version: 16.11.0
* React Native version: 0.62.2
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): iOS
* TypeScript version: -

**Comment by Gabsys** [comment]
Try applying style={{flex:1}} to your <SafeAreaView>
