### ISSUE TITLE
Keyboard overlaps chat messages and composer view

### ISSUE THREAD

**Issue by hubermat** [FaridSafi/react-native-gifted-chat#1766]
#### Issue Description

If GiftedChat is resized while keyboard is shown (e.g. because GiftedChat is embedded inside a container view, in which a dynamic header is resized or shown/hidden), the messagesContainerHeight is calculated without taking the open keyboard view into account. This leads to a situation, where the end of the messages container including the composer is covered by the opened keyboard.

![IMG_0176](https://user-images.githubusercontent.com/1336497/80984472-2e9e7d80-8e2e-11ea-8a58-6f626486b92b.PNG)

#### Steps to Reproduce / Code Snippets

Embed GiftedChat inside a container view, and add another view as sibling inside the container, which dynamically is resized/shown/hidden, so that GiftedChat itself is resized as well.

Show the keyboard, then resize/show/hide the sibling view => the chat messages container as well as the composer "jumps" down and is covered by the opened keyboard.

#### Expected Results

The Keyboard never overlaps the composer view and/or messages view.

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: 0.61.5
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): iOS
* TypeScript version: [FILL THIS OUT]

**Comment by akhilsanker** [comment]
Hi,
Facing the same issue in android and iOS.

Any solution.

Thanks

**Comment by xkungfu** [comment]
same issue!

**Comment by thanhdevapp** [comment]
same issue IP 11 - 13.6

**Comment by joewired** [comment]
I used the KeyboardAvoidingView component from react-native

import { KeyboardAvoidingView } from 'react-native'

<KeyboardAvoidingView
          style={styles.keyboardViewContainer}
          behavior="padding"
          enabled
        >
          <View flex bg-screenBG>
            <GiftedChat
              messages={messages}
              onSend={(newMessages) => onSend(newMessages)}
             />
          </View>
</KeyboardAvoidingView>

const styles = StyleSheet.create({
  keyboardViewContainer: {
    flex: 1,
  },
