### ISSUE TITLE
Is it possible to use react-native-snap-carousel inside custom gifted chat message

### ISSUE THREAD

**Issue by Egizas** [FaridSafi/react-native-gifted-chat#1768]
Is it possible to use react-native-snap-carousel component inside gifted-chat?

I am using:
    "react-native-gifted-chat": "^0.13.0",
    "react-native-snap-carousel": "^3.8.4",

If I try to place carousel inside a custom message bubble, I am getting these warnings:
1) "Warning: Failed prop type: The prop `renderItem` is marked as required in `Carousel`, but its value is `undefined`."
2) If I live reload/refresh the app, I get:
![image](https://user-images.githubusercontent.com/15939884/81025749-f02db080-8e77-11ea-8ecd-4a836e560b48.png)

Code:
```
<View style={{ flex: 1, flexDirection: 'row', justifyContent: 'center', }}>
  <Carousel
    ref={ref => this.carousel = ref}
    layout={'default'}
    data={[{title: "Item 1", text: "Text 1" }, { title: "Item 2",  text: "Text 2" }]}
    renderItem={this.renderCarCard}
    sliderWidth={WIDTH}
    itemWidth={WIDTH}
    slideStyle={{ paddingHorizontal: 20 }}
  />
</View>
```
```
  renderCarCard = ({ item, index }) => {
    return (
      <View>
        <Text style={{ color: 'white' }}>{item.text}</Text>
      </View>
    );
  }
```

p.s. If it helps, horizontal scrollView works inside of the giftedChat

**Comment by bkioshn** [comment]
I'm not sure whether  react-native-snap-carousel is working or not, but I did the carosel on Giftedchat by editing the Bubble component (renderBubble).
