### ISSUE TITLE
__DEV__ is not defined

### ISSUE THREAD

**Issue by MayeuldP** [FaridSafi/react-native-gifted-chat#177]
Hi, 
when I start the program, the very basic example of the readme (`react-native run-android`) I get this issue.... `node_modules\\react-native-gifted-chat\\index.js : __DEV__ is not defined`

![log](https://cloud.githubusercontent.com/assets/15033774/17328518/72280318-58be-11e6-8a41-a229c7c38a1d.PNG)

First I thought that it was because of my RN'version (0.30.0) so I install the project on a lower version : 0.25.1, but I still have this issue.... So i don't know where is the problem, and the others threads on internet about this subject didn't help me..... thank's !

**Comment by FaridSafi** [comment]
You can try to delete .babelrc in node_modules/react-native-gifted-chat as a temporary solution

**Comment by MayeuldP** [comment]
Ok, i haven't this erros anymore, but now i'm getting this issue (after deleting .babelrc) : 
`undefined is not a function (evaluating'_reactNative.Platform.select({ios: 6, android:0})')`<br> in `node_modules\react-native-gifted-chat\src\Composer.js:36`....

Any idea ? It's seems that's not a common error...

**Comment by FaridSafi** [comment]
If you are still on rn 25 you have to upgrade

**Comment by MayeuldP** [comment]
It works like a charm ! Thank's :)

**Comment by ssmlee04** [comment]
I have the same problem. Even after I deleted .babelrc the problem still exists.

**Comment by FaridSafi** [comment]
Hello, React Native minimum supported version is 0.29.0

**Comment by ssmlee04** [comment]
ok upgraded to RN 0.31.0 but the problem still exists.

**Comment by ssmlee04** [comment]
ok it is working after I restarted the packager. Thanks.
