### ISSUE TITLE
Last letter/word of the message were missing on smaller devices

### ISSUE THREAD

**Issue by firmanjml** [FaridSafi/react-native-gifted-chat#1774]
#### Issue Description

Tested this library on smaller devices and whenever I send or receive a message, every last character or word is not shown in the chat message.

[Youtube Demo](https://youtu.be/IHoF7y-RsUs)

#### Steps to Reproduce / Code Snippets

Using devices with smaller screen

#### Expected Results

Last character or words are missing

#### Additional Information

* Nodejs version: v13.12.0
* React version: 16.9.0
* React Native version: 0.62
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: 3.8.3

**Comment by xcarpentier** [comment]
Can you share a [small snippet of code](https://snack.expo.io/)?

**Comment by firmanjml** [comment]
Hello @xcarpentier 
Thank you for the response. I appreciate the hard work on this library. 

This is the snippet of the code on expo snack [example](https://snack.expo.io/@firmanjml/react-native-gifted-chat).

**Comment by xcarpentier** [comment]
Thanks
It missed `renderBubble` in your snippet, can you provide it?

**Comment by xcarpentier** [comment]
What is the screen size of your test?

**Comment by firmanjml** [comment]
Hi, i tested the example snack (without the renderBubble) and still have the same issue on my LG-H961N

**Comment by HapitatEric** [comment]
Any updates on this? We experience the same problem with Huawei/Google Nexus phones. So hard to debug :/
