### ISSUE TITLE
Can't import any types in 0.15.2 & 0.15.3

### ISSUE THREAD

**Issue by StagasaurusRex** [FaridSafi/react-native-gifted-chat#1776]
#### Issue Description

Can't import any types in 15.2 & 15.3.

#### Steps to Reproduce / Code Snippets

Try to import a type, i.e. SendProps, IMessage, User, ComposerProps

#### Expected Results

No error saying their is no exported member named {w/e} 

#### Additional Information

* Nodejs version: 10.19
* React version: 16.9.0
* React Native version: 0.61.5
* react-native-gifted-chat version: 0.15.3
* Platform(s) (iOS, Android, or both?): Both
* TypeScript version: 3.8.3

<img width="509" alt="Screen Shot 2020-05-08 at 4 50 02 PM" src="https://user-images.githubusercontent.com/4968936/81452234-fd82bd80-914b-11ea-997a-b83f035de7b5.png">

**Comment by michaelgmcd** [comment]
```
❯ cat node_modules/react-native-gifted-chat/lib/types.js
//# sourceMappingURL=types.js.map
```
type.js is empty, while types.js.flow has the correct ones

**Comment by efstathiosntonas** [comment]
Same here

**Comment by efstathiosntonas** [comment]
Confirmed fixed at  [v16](https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/v0.16.0)

@xcarpentier
