### ISSUE TITLE
[bug] renderX methods are not hooks friendly.

### ISSUE THREAD

**Issue by Johan-dutoit** [FaridSafi/react-native-gifted-chat#1777]
#### Issue Description

To override the styling and other functionality of GiftedChat using the renderX methods (i.e. `renderBubble={GiftedBubble}`), a redbox us thrown when using React Hooks.

![image](https://user-images.githubusercontent.com/1611055/81475051-df7b9280-9209-11ea-8478-ac2f4d14d892.png)

#### Expected Results

To be able to use hooks in renderX methods.

#### Additional Information

* Nodejs version: 13.9.0
* React version: 16.13.1
* React Native version: 0.63.0-rc.1
* react-native-gifted-chat version: 0.14.1
* Platform(s) (iOS, Android, or both?): Both
* TypeScript version: 3.8.3

**Comment by StagasaurusRex** [comment]
Replace `renderBubble={GiftedBubble}` w/ `renderBubble={() => <GiftedBubble />}`

**Comment by Johan-dutoit** [comment]
Thanks.  A bit of a hack? At least I can proceed.
