### ISSUE TITLE
Typing Indicator is positioned off screen with full page of messages

### ISSUE THREAD

**Issue by StagasaurusRex** [FaridSafi/react-native-gifted-chat#1778]
#### Issue Description

Typing indicator is positioned off screen with full screen of messages, and is positioned at the middle of the screen with one message.

#### Steps to Reproduce / Code Snippets

Set isTyping={true}

#### Expected Results

Typing indicator positioned  where the next chat bubble would be, or possibly at the bottom of the screen.

#### Additional Information

* Nodejs version: 10.19
* React version: 16.9.0
* React Native version: 0.61.5
* react-native-gifted-chat version: 0.14.1
* Platform(s) (iOS, Android, or both?): Both
* TypeScript version: 3.8.3

![typing](https://user-images.githubusercontent.com/4968936/81480928-59078680-91f2-11ea-91f7-1d4706f8dba0.gif)

![Simulator Screen Shot - iPhone 11 - 2020-05-09 at 12 41 18](https://user-images.githubusercontent.com/4968936/81480937-66247580-91f2-11ea-8f79-ad3e41ea4d08.png)

**Comment by xcarpentier** [comment]
Hi,
https://github.com/FaridSafi/react-native-gifted-chat/blob/70291e856c39c0881f0bc50ecfc9c012dc09f726/src/TypingIndicator.tsx#L31
Obviously the `height animation` not working as expected.
Then I will change the `height animation` by an `opacity animation`.

**Comment by mikkuuuu14** [comment]
@xcarpentier, just encountered this also, any news on your fix? Thanks!

**Comment by yashkataruka** [comment]
@xcarpentier Just encountered it again in 2 chat screen while not in the third one, kindly do let us know when the bug is fixed

**Comment by ahce** [comment]
I mentioned this bug in this PR #1592 
For now I don't use this feature.

You can remove the component:

```
      <GiftedChat
         renderFooter={() => null}
      />
```

**Comment by YahyaBagia** [comment]
How did you managed to get the typing indicator to work / render ? I'm having [this](https://github.com/FaridSafi/react-native-gifted-chat/issues/1618) issue.

**Comment by drbhol** [comment]
> Set isTyping={true}
@StagasaurusRex 

can you please guide me how to display the typing indicator .
