### ISSUE TITLE
Inbox messages rendering repeatedly!

### ISSUE THREAD

**Issue by rkobhi512** [FaridSafi/react-native-gifted-chat#1779]
#### Issue Description

Each message rendering one after one in inbox.  If I have sent or recieved new message it render entire inbox message one after one. 

#### Problem Screen
![problem]

#### Expected Results
![Expectation](https://user-images.githubusercontent.com/31918004/81506922-71bf8b80-931b-11ea-80b0-9b14d6755b05.gif)

#### Additional Information

* Nodejs version: v10.16.3
* React version: 16.13.1
* React Native version: 0.61.5
* react-native-gifted-chat version: ^0.13.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by paras-kc** [comment]
I am facing the same issue.
