### ISSUE TITLE
Add support for onPress bubble

### ISSUE THREAD

**Issue by TomaszNiedzielski** [FaridSafi/react-native-gifted-chat#1782]
It would be very helpfull, for example to show time.

**Comment by xcarpentier** [comment]
PR are welcome ;)

**Comment by hackrx** [comment]
@xcarpentier any luck for this?

**Comment by Aryk** [comment]
Am I understanding this right..there is onLongPress available and even programmed, but there is no way to do onPress at all for the bubble?

**Comment by nsdub** [comment]
I assume there's some reason this isn't formally supported, but I added an `onPress` event in `Bubble.js`. You can just copy all the same props that are used for `onLongPress`. I opted to apply the change with [Patch-Package](https://github.com/ds300/patch-package)
