### ISSUE TITLE
Using infiniteScroll prop in react native

### ISSUE THREAD

**Issue by mkuligowski** [FaridSafi/react-native-gifted-chat#1784]
#### Issue Description

I just want to change implementation for loading more messages from "load earlier button" to infinite scroll. According to docs, property **infiniteScroll** should work alongside with **onLoadEarlier**, but in my case it just doesn't work.

#### Steps to Reproduce / Code Snippets

```
 <GiftedChat
          ref={ref => (this.giftedChatRef = ref)}
          messages={messages}
          onSend={this.onSend}
          onLoadEarlier={this.loadEarlier}
          infiniteScroll={true}
          user={appUser}
          bottomOffset={-5}
          keyboardShouldPersistTaps={'never'}
          placeholder={t('write-here')}
          renderActions={this.renderCustomActions}
          renderDay={this.renderDay}
          renderBubble={this.renderBubble}
          renderAvatar={null}
          renderSend={this.renderSend}
          renderInputToolbar={this.renderInputToolbar}
 />
```

#### Expected Results

_this.loadEarlier()_ is invoked when reached top of the chat

#### Additional Information

* React version: 16.9.0
* React Native version: 0.61.5
* react-native-gifted-chat version: 0.16.0
* Platform(s) (iOS, Android, or both?): both

**Comment by xcarpentier** [comment]
Hi,

Can you please give us a [snack link](https://snack.expo.io/@xcarpentier/giftedchat-playground)? 

BTW you may have to follow this implementation: https://github.com/FaridSafi/react-native-gifted-chat/blob/master/App.tsx#L240-L265

**Comment by mkuligowski** [comment]
Hi,

@xcarpentier Thank you for a sample implementation. It seems that I missed **loadEarlier** property. I thought that is enough to provide **onLoadMore** alongside with **infiniteScroll** as it's described in README because  **loadEarlier** should just:

>  Enables the "load earlier messages" button

Maybe some small improvement to README? :man_shrugging:

**Comment by xcarpentier** [comment]
Done => https://github.com/FaridSafi/react-native-gifted-chat/commit/0b9ed5aa79f2e0f1d3da56fc2c508f19246b59b6

**Comment by mkuligowski** [comment]
Perfect! Thanks :smile:
