### ISSUE TITLE
threshold for infiniteScroll

### ISSUE THREAD

**Issue by kakajann** [FaridSafi/react-native-gifted-chat#1788]
Hello, this is not an issue.

Can you add infiniteScrollThreshold prop? UI doesn't feel native when i fetch oldest messages when scroll reaches the end. It would be nice to invoke onLoadEarlier function before some pixels left to scroll reaches the end.

**Comment by hugoh59** [comment]
@FaridSafi

**Comment by ezequiel88** [comment]
Please support in the issue

**Comment by abdi4** [comment]
+1
