### ISSUE TITLE
Customize MessageText help

### ISSUE THREAD

**Issue by devbriguy** [FaridSafi/react-native-gifted-chat#179]
I have been trying to change the font and color of the message's text. Here is my renderMessageText function.

```
  renderMessageText(props) {
    return (
      <MessageText textStyle={{fontSize: 18, fontWeight: 'bold', fontFamily: 'AvenirNext-Regular', color: 'lightgray'}} linkStyle={{fontSize: 18, color: 'green'}} />
    )
  },
```

It just has not been working. Am I missing something? Thanks.

**Comment by FaridSafi** [comment]
I will publish a fix in few minutes

**Comment by devbriguy** [comment]
Wow nice thanks.

**Comment by FaridSafi** [comment]
please test with 0.0.3

**Comment by devbriguy** [comment]
Tested if I keep my code the same. I get bubbles without text. But if I add ```{...props}``` I get the text back but no style change.

**Comment by FaridSafi** [comment]
can you share the content of MessageText ?

**Comment by devbriguy** [comment]
```
<MessageText {...props} textStyle={{
fontSize: 20, 
color: 'lightgray'}} linkStyle={{
fontSize: 18, 
color: 'green'}} />
```

**Comment by devbriguy** [comment]
That worked.

**Comment by psgganesh** [comment]
@FaridSafi ... Sorry this still gives me MessageText is undefined ...
