### ISSUE TITLE
Fails on hermes

### ISSUE THREAD

**Issue by djschilling** [FaridSafi/react-native-gifted-chat#1792]
Running this lib on the hermes js engine fails.
The reason is the lib https://github.com/nodeca/unhomoglyph.
See these issues for explanation: 

* https://github.com/nodeca/unhomoglyph/issues/7
* https://github.com/facebook/hermes/issues/235

There is a new release of unhomoglyph to fix the issue.
So please update the lib unhomoglyph to version 1.0.6

**Comment by djschilling** [comment]
has noone else this problem?

**Comment by sanborN93** [comment]
Having the same issue.

**Comment by da314pc** [comment]
Having this issue.

**Comment by Seanmclem** [comment]
is this the getRandomBase64String issue?
