### ISSUE TITLE
[Feature] Option to change avatar image component

### ISSUE THREAD

**Issue by Johan-dutoit** [FaridSafi/react-native-gifted-chat#1793]
#### Issue Description
Images rendered with the standard image component provides a bad UX.

#### Steps to Reproduce / Code Snippets
Render a long conversation and see how slow and erratic each image loads (and in random order).

#### Expected Results
All images to render the same time/not have separate requests to network images.  

This is easy to solve by overriding the entire `renderAvatar` just to add a better image component (i.e. react-native-fast-image), but would be great to just to provide an `ImageComponent`, as we currently need to copy all the styles from gifted chat, just to change the image component.

#### Additional Information

* Nodejs version: 13.9.0
* React version: 16.13.1
* React Native version: 0.63.0-rc.1
* react-native-gifted-chat version: 0.16.1
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: 3.9.2

**Comment by jon-caylent** [comment]
For anyone still running into this is appears there is an undocumented feature to support this by setting the avatar to a function which returns a JSX component. See example below.

`avatar: styles => <FastImage source={{ uri: chatUserData?.photoUrl }} style={styles} />`

**Comment by moeenchanna** [comment]
I've successfully addressed this issue and it's now functional. Please give it a go!

```
const renderAvatar = (props, avatarUrl) => {
  if (avatarUrl) {
    return (
      <Image
        source={{ uri: avatarUrl }}
        style={{
          width: 40,  // Set the desired width
          height: 40, // Set the desired height
          borderRadius: 7, // Adjust border radius as needed
          marginRight: 0,  // Add any additional styling here
        }}
      />
    );
  }
  return null;
};
```


```
 <GiftedChat
 renderAvatar={(props) => renderAvatar(props, messages[0].user.avatar)}
// Other props...
 />
```
  
  
<img width="386" alt="Screenshot 2023-09-29 at 6 10 53 PM" src="https://github.com/FaridSafi/react-native-gifted-chat/assets/106139952/6e546951-16d6-4f02-ad56-34c0f49f11f6">
