### ISSUE TITLE
Render date of message above message

### ISSUE THREAD

**Issue by jwellington58** [FaridSafi/react-native-gifted-chat#1794]
#### Issue Description

Hello! When I render the message in a custom way, I can't show the creation date above the messages. How do I display this date? Can anyone help? Pls

##### I use renderMessage method to render the custom message
~~~javascript
...
renderMessage(props) {
    return (
      <Bubble
        {...props}
        wrapperStyle={{
          left: {
            backgroundColor: 'white',
          },
          right: {
            backgroundColor: '#E8FAFF',
          }
        }}
      />
    );
  }
...
render() {
    return (
        <GiftedChat renderMessage={this.renderMessage.bind(this)}/>
     );
  }
...
~~~
#### Expected Results

![Sem título](https://user-images.githubusercontent.com/23315313/82223032-7924fd00-98f8-11ea-8852-aec13c3c6552.png)

#### Additional Information

* Nodejs version: 10.19.0
* React version: 16.9.0
* React Native version: 0.61.5
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by RuanSantos0** [comment]
I have the same issue
