### ISSUE TITLE
Unable to reolve module 'moment' from node_modules\react-native-gifted-chat\lib\GiftedChat.js

### ISSUE THREAD

**Issue by EhteshamAnwar** [FaridSafi/react-native-gifted-chat#1799]
#### Issue Description
![image](https://user-images.githubusercontent.com/16754151/82701604-f13d4b00-9c89-11ea-8d81-6c190908c28e.png)

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets
I simply did npm install react-native-gifted-chat and tried to run my application. 
I checked this file but there is not a single instance named 'moment', no imports whatsoever. 
package.json shows version 0.16.1 
[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by nihp** [comment]
Any solutions

**Comment by EhteshamAnwar** [comment]
@nihp first make sure no bundler is running. 
 
clear watchmen watches, 
delete node modules folder, 
remove gifted chat dependency from package.json , 
clean npm cache 
run: npm install, 
run: npm install   react-native-gifted-chat
