### ISSUE TITLE
How to using my local svg for render Avatar

### ISSUE THREAD

**Issue by manhncse02926** [FaridSafi/react-native-gifted-chat#1801]
#### Issue Description
I have a list message from my group chat. It's internal chat, and we have a list SVG avatar. I just wanna custom to show my SVG to using. Have anyone here can guide me this one? Thank you
My export avatar sample:

`
function ToucanSVG(props: any) {
  return (
    <Svg >
      <Path   />
    </Svg>
  );
}
export default ToucanSVG;
`

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by doublethefish** [comment]
What was your solution?

**Comment by manhncse02926** [comment]
> What was your solution?

it's been too long to remember everything, bro. I'm not sure if it still works or not

  `<GiftedChat
        .....
        renderAvatarOnTop={true}
        renderAvatar={this.renderAvatar}
      />

renderAvatar(props: any) {
    const username = _.get(props, 'currentMessage.user.name');
    let {currentMessage, previousMessage} = props;
    const isSameThread =
      currentMessage &&
      isSameUser(currentMessage, previousMessage) &&
      isSameDay(currentMessage, previousMessage);
    const isShow = username !== _.get(props, 'user.name');
    return (
      <View style={styles.avatar}>
        {isShow && !isSameThread && Avatar(currentMessage.user.avatar)}
      </View>
    );
  }
`

**Comment by doublethefish** [comment]
Ah I see, thanks.

On issue #409 they just used `require` to load the image into the `avatar` prop, which is also pretty straight forward. Although I'm not sure if that works for .svg.
