### ISSUE TITLE
GiftedChat component causes Detox E2E tests to hang

### ISSUE THREAD

**Issue by kadosa** [FaridSafi/react-native-gifted-chat#1804]
#### Issue Description

I'm trying to write E2E tests for my RN app that uses GiftedChat and found that Detox seems to hang on screens that render GiftedChat with the following message flooding the logs:
`[com.wix.Detox:EarlGreyStatistics] JavaScript Timers -> busy Javascript Timers`
I've created a test repo with a barebone RN app that renders GiftedChat from the example folder and added a simple detox test to reproduce the issue. 

#### Steps to Reproduce / Code Snippets
1. Clone the repo: https://github.com/kadosa/GiftedChatDetoxTest
2. Install deps
3. Build app (`yarn e2e:build`)
4. Run test (`yarn e2e:test`)

The test will fail with a timeout. 

#### Expected Results

Detox tests should finish normally.

#### Additional Information

* Nodejs version: 12.15.0
* React version: 16.11.0
* React Native version: 0.62.2
* react-native-gifted-chat version: 0.16.1
* Platform(s) (iOS, Android, or both?): iOS
* TypeScript version: N/A

**Comment by platenger** [comment]
Hi @kadosa my workaround for this was to disable synchronization ([await device.disableSynchronization()](https://github.com/wix/detox/blob/master/docs/Troubleshooting.Synchronization.md#switching-to-manual-synchronization-as-a-workaround)) before navigating to the screen that uses GiftedChat component, do all GiftedChat related stuff, unmounting this screen (i.e. go back) and then reenable synchronization again.
Hope this helps. Please let me know if you found another way to solve this. Good luck!

**Comment by rodolphefauquez** [comment]
Any news about this? This should not be closed.
Now e2e tests are not supported by GiftedChat.

@platenger workaround indeed makes the tests to start but in my case nothing works correctly when disabling synchronization.
