### ISSUE TITLE
react-native-gifted-chat typing indicator is not being displayed

### ISSUE THREAD

**Issue by drbhol** [FaridSafi/react-native-gifted-chat#1806]
@xcarpentier 
#### Issue Description

I am new to react native and trying to implement gifted chat. Can you please help how to display the typing status in the chat screen as well as in the chatroom list view?
However, I could not see the typing status in the chat

#### Steps to Reproduce / Code Snippets

this.state= {isTyping:false}

setIsTyping = () => {
this.setState({
isTyping: !this.state.isTyping,
})
}

<GiftedChat
messages={this.state.messages}
onSend={this.onSend.bind(this)}
user={{
_id: this.state.LoggedinuserID,
}}
onInputTextChanged={this.setIsTyping}
isTyping={this.state.isTyping}
/>

#### Expected Results

Chat screen should display the typing indicator

#### Additional Information

Please suggest what am I doing wrong

Nodejs version: [v10.16.3]
React version: ["react": "16.8.3",]
React Native version: [rreact-native-cli: 2.0.1, react-native: 0.59.8,
"react-native-web": "^0.11.7",]
*"expo": "^35.0.0",
react-native-gifted-chat version: ["react-native-gifted-chat": "^0.13.0",]
Platform(s) (iOS, Android, or both?): [expo, both]
TypeScript version: []

**Comment by eniga** [comment]
From your example seems you're trying to track when the user is typing but you can just set your prop as below
isTyping={true}

**Comment by drbhol** [comment]
> From your example seems you're trying to track when the user is typing but you can just set your prop as below
> isTyping={true}

@eniga , thanks for the suggestion.

Per your advice, I have 
<GiftedChat
messages={this.state.messages}
onSend={this.onSend.bind(this)}
user={{
_id: this.state.LoggedinuserID,
}}

isTyping={true}
/>

opened the app in two ios devices , logged in as two users and started chatting .
Neither of the screen displayed when users are typing.

Can you please help me ... what am I doing wrong?

**Comment by kadosa** [comment]
@eniga The isTyping prop only handles displaying the typing indicator, but the logic to define when that prop is true is up to you to implement. If you have a backend you could implement a websocket solution that would notify other chat members when someone starts typing and your app would listen to that event to turn that prop on and off.

**Comment by CanVeeD** [comment]
> @eniga The isTyping prop only handles displaying the typing indicator, but the logic to define when that prop is true is up to you to implement. If you have a backend you could implement a websocket solution that would notify other chat members when someone starts typing and your app would listen to that event to turn that prop on and off.

Looks like bug, faced with same problem, isTyping={true} not displaying typing animation.
^0.16.1

**Comment by eniga** [comment]
> > From your example seems you're trying to track when the user is typing but you can just set your prop as below
> > isTyping={true}
> 
> @eniga , thanks for the suggestion.
> 
> Per your advice, I have
> <GiftedChat
> messages={this.state.messages}
> onSend={this.onSend.bind(this)}
> user={{
> _id: this.state.LoggedinuserID,
> }}
> 
> isTyping={true}
> />
> 
> opened the app in two ios devices , logged in as two users and started chatting .
> Neither of the screen displayed when users are typing.
> 
> Can you please help me ... what am I doing wrong?

@drbhol 
A working sample is as below..... used renderFooter but you can use your same logic to render the footer only when the user is typing.

    renderFooter(){
        return (<Text>{this.user.name} is typing</Text>)
    }

    render(){
        return (
            <Block style={styles.container}>
                <GiftedChat
                    messages={this.state.messages}
                    isTyping={true}
                    onSend={firebaseSvc.send}
                    user={this.user}
                    renderFooter={this.renderFooter}
                />
                {Platform.OS === 'android' && <KeyboardAvoidingView behavior="padding" />}
            </Block>
        )
    }

**Comment by patrick-samy** [comment]
Same issue on 0.16.3, the typing indicator is not displayed when isTyping={true) even if renderFooter isn't used. Tested on iOS only.

**Comment by shamilovtim** [comment]
Hey yes as a separate contributor on here mentioned you can't just set it to true, it doesn't work during mount. You must update it to true *after screen mount*. 

If @xcarpentier is interested he can change this behavior but I know that I had specific reason for programming it this way when I built it

**Comment by xcarpentier** [comment]
@shamilovtim
We can keep it like this :)

**Comment by gaguirre** [comment]
So is this the expected behavior?
If it's not, I could take a look at it.

**Comment by shamilovtim** [comment]
It is working as expected. We set it up so that typing is a stateful variable, not a stateless prop on mount.

**Comment by xpsdeset** [comment]
For those who are struggling, just incase. 

`import TypingIndicator from "react-native-gifted-chat/lib/TypingIndicator"`

And add below prop, weird 

```
   renderFooter={ () => (
              <TypingIndicator
                isTyping={session.typing && session.typing[oppoRole]}
              />
            )}
```

**Comment by fukemy** [comment]
> For those who are struggling, just incase.
> 
> `import TypingIndicator from "react-native-gifted-chat/lib/TypingIndicator"`
> 
> And add below prop, weird
> 
> ```
>    renderFooter={ () => (
>               <TypingIndicator
>                 isTyping={session.typing && session.typing[oppoRole]}
>               />
>             )}
> ```

i tried to renderFooter and set isTyping = true with hook but TypingIndicator did not show, can u help?

**Comment by RobinW-Ripcord** [comment]
It does not work on React hook.

**Comment by HHip32** [comment]
how to custom renderFooter without covering gifted-chat's isTyping icon. I want my renderFooter to display a "user is typing" message next to the isTyping icon when set to true?
