### ISSUE TITLE
Remove unwanted bottom padding in InputToolbar when  Keyboard open 

### ISSUE THREAD

**Issue by Buwaneka-Sumanasekara** [FaridSafi/react-native-gifted-chat#1809]
#### Issue Description
I want to remove unwanted bottom padding in InputToolbar when keyboard opened. Its only happened in ios, In android it's working without any issue.

#### Steps to Reproduce / Code Snippets

Here is the code sample

![Picture1](https://user-images.githubusercontent.com/17542497/83020200-c6fedb00-a045-11ea-88e2-cd2bc6d3b78e.png)

````
 <GiftedChat
                        messages={ar_messages}
                        onSend={messages => this._onSendMessage(messages)}

                        user={{
                            _id: CurUser.user_id,
                            name: CurUser.display_name
                        }}
                        renderActions={this._renderLeftButton}
                        renderAccessory={this._renderSecondLine}
                        renderSend={this._renderSendButton}
                        text={this.state.txt_input_value}
                        onInputTextChanged={text => this.setCustomText(text)}
                        multiline={true}
                        alwaysShowSend={true}
                        keyboardShouldPersistTaps={'never'}
                        textInputProps={AppStyles.InputStyles.ChatInput.Props}
                        textInputStyle={AppStyles.InputStyles.ChatInput.Style}
                        renderBubble={this._renderBubble}
                        isTyping={false}
                        accessoryStyle={{ height: accessoryHeight }}
                        lightboxProps={{ springConfig: { tension: 90000, friction: 90000 } }}
                    />
```



#### Expected Results
Remove unwanted bottom padding


#### Additional Information

* Nodejs version: v12.14.0
* React version: 16.9.0
* React Native version:0.61.5
* react-native-gifted-chat version: 0.16.0
* Platform(s) (iOS, Android, or both?): iOS

**Comment by Hirbod** [comment]
You can play around with the `bottomOffset` prop.
For me, its like this: `bottomOffset={this.isIphoneX() ? 22 : -12}` 

You should of course use other values which fit to your application.

**Comment by hanayashiki** [comment]
I also find that adding `isKeyboardInternallyHandled` can solve this problem. Why?
My machine is iPhone 10

**Comment by Buwaneka-Sumanasekara** [comment]
@xcarpentier Is this update available after re-install package or will be available on next release?

**Comment by Hirbod** [comment]
@Buwaneka-Sumanasekara if you want it now, you need to install from master. Latest release is 0.16.1, which does not contain this fix

**Comment by Buwaneka-Sumanasekara** [comment]
Waiting for the next release.

**Comment by abdi4** [comment]
Any update on this?

**Comment by johnfrancisgit** [comment]
This is still an issue

**Comment by thanhdevapp** [comment]
bottomOffset={isIphoneX ? getBottomSpace() : -12}

https://prnt.sc/wcv0xr

**Comment by fukemy** [comment]
ok i found problem, when render accessoryview then

getMinInputToolbarHeight() {
        return this.props.renderAccessory
            ? this.props.minInputToolbarHeight * 2
            : this.props.minInputToolbarHeight;
    }

so need to calculate bottomoffset again by + inputtoolbarheight

**Comment by coderpr0grammer** [comment]
> ok i found problem, when render accessoryview then
> 
> getMinInputToolbarHeight() { return this.props.renderAccessory ? this.props.minInputToolbarHeight * 2 : this.props.minInputToolbarHeight; }
> 
> so need to calculate bottomoffset again by + inputtoolbarheight

how can this be used in a functional component? also did you get it working?
