### ISSUE TITLE
News shows that starts from the top

### ISSUE THREAD

**Issue by 289420843** [FaridSafi/react-native-gifted-chat#181]
A small amount of message height do not meet the container height. Now is displayed at the bottom. Hope to start from the top.How to do it?

**Comment by longsangstan** [comment]
Are you saying that when there are only a few messages, they are not sticking to the top?
I have the same question as well.

**Comment by 289420843** [comment]
@longsangstan That's right.

**Comment by longsangstan** [comment]
Why do you close it? You have fixed the issue?

**Comment by 289420843** [comment]
Open this issue, the gifted-chat to solve the issue.

**Comment by kfiroo** [comment]
@289420843 @longsangstan This is indeed an issue with `react-native-invertible-scroll-view` which is still open, hopefully a solid fix will come up soon :)

I tried to get it to work with `gifted-chat` but it messed up a few other things so I left it for now..

**Comment by satyagupta** [comment]
Do array.reverse and then load that as messages. 

And When adding a new message object using GiftedChat.append function to add new message object.

**Comment by hegelstad** [comment]
If somebody is stuck with `Inverted` prop not working, remember to refresh app/remount component.
