### ISSUE TITLE
Offset problem on Android keyboard with expo 37

### ISSUE THREAD

**Issue by saurus1993** [FaridSafi/react-native-gifted-chat#1812]
Hello everyone,

**PROBLEM**
I am currently on react native (Expo) and when I updated my app from expo 35 to expo 37, I started to have padding or margin problems on my application (only on Android).
These problems appear at the level of the keyboard, which creates an offset when it is opened. (The [GIF (link)](https://www.noemiemartin.fr/giftedchat.gif) show you the offsets in neon green).

**CODE**
`<KeyboardAvoidingView style={{ width:'100%', height:'100%' }} behavior={'padding'} keyboardVerticalOffset={40}>`
`<View style={{ width:'100%', height:'100%' }}>`
`<GiftedChat/>`
`</View>`
`</KeyboardAvoidingView>`

**SOLUTIONS (Not working)**
(I have tried SOOOOO MANY solutions in internet :
- eject expo and change the `android:windowSoftInputMode="adjustResize"`
- Tried so many things inside the style code
- Add 
`tabBarOptions: {
    ...
    keyboardHidesTabBar: true
  }`

**VERSIONS**
* Nodejs version: 14.3.0
* React version: 16.9.0
* React Native version: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz
* react-native-gifted-chat version: ^0.13.0
* Platform : Android

**Comment by Hirbod** [comment]
The issue is the StatusBar. Did you set it to translucent on android? If yes, thats prob. breaking it for you (as it did for me). SDK 38, which is around the corner, should finally fix it, Try to disable translucent and it should work fine

**Comment by saurus1993** [comment]
Yes, I set the status in two parts of my app, but nothing happen ...

About the android StatusBar, i choose two methods :

**1. FIRST METHOD**
 `<StatusBar translucent backgroundColor="transparent" />` inside my **app.js**

```
<Provider store={store}>
  <PersistGate loading={null} persistor={persistor}>
    <StatusBar translucent backgroundColor="transparent" />
    {this.state.fontLoaded ? (
      <Router />
    ) : (
      <View style={{ justifyContent: "flex-end", alignItems: "center", flex: 1, width: "100%" }}>
        <View style={{ width: '100%', height:'100%', alignItems:'center', justifyContent:'center' }}>
          <ActivityIndicator
            style={{height: 80}}
            color={color.yellow}
            size="large"
          />
        </View>
      </View>
    )}
  </PersistGate>
</Provider>
```

**2. SECOND METHOD**
Put androidStatusBar to translucent inside my **app.json**

```
{
  "expo": {
    ...
    "androidStatusBar": {
      "backgroundColor": "#FFFFFF",
      "translucent": false
    }
  }
}
```


But **NOTHING** works for me again ... :(

**Comment by Hirbod** [comment]
You have to fully disable (not use translucent) at all - at least for now. I didn't find a way without it.

**Comment by saurus1993** [comment]
How to fully disable the StatusBar ?

**Comment by Hirbod** [comment]
Don't disable the StatusBar, just set translucent to false in your app.json and don't use `<StatusBar translucent />` (because this will make it translucent again.

If you're using libs like native-base with Header, make sure that doesn't set translucent for your StatusBar, too.
