### ISSUE TITLE
undefined is not a object (evaluating 'promise.done.bind')

### ISSUE THREAD

**Issue by kennyzehn** [FaridSafi/react-native-gifted-chat#182]
Hey guys,

i dont know what goes wrong?! But the first request on the chat component failed with this message -> undefined is not a object (evaluating 'promise.done.bind')

```javascript
    constructor(props) {
        super(props);
        this.state = {messages: []};
      }

    componentDidMount() {
        this.setState({
            isTyping: true,
            messages: [{
                _id: 1,
                text: 'Hello developer',
                createdAt: new Date(Date.UTC(2016, 7, 30, 17, 20, 0)),
                user: {
                    _id: 2,
                    name: 'React Native',
                    avatar: 'https://facebook.github.io/react/img/logo_og.png',
                },
            },],
        });
    }

    onSend(messages = []) {
        this.setState((previousState) => {
          return {
            messages: GiftedChat.append(previousState.messages, messages),
          };
        });
    }

    render() {
        if(this.state.messages) {
            return (
                <View style={Settings.styles.pageView}>
                    <GiftedChat messages={this.state.messages} onSend={this.onSend.bind(this)} user={{_id: 1}}/>
                </View>
            )
        } else {
            return (
                <Loading />
            )
        }
    }
```

Any ideas?

**Comment by FaridSafi** [comment]
Hello,
is `Settings.styles.pageView` defined ?

**Comment by kennyzehn** [comment]
Yes it is.

**Comment by FaridSafi** [comment]
What RN version are you using?
Do you have more information in the log?

I created a project using your code and could'nt reproduce, can you prepare a code example?

**Comment by kennyzehn** [comment]
"react": "15.2.1",
"react-native": "^0.30.0"

and here the error screen -> https://monosnap.com/file/jnhre3Zbh5PsYZ41cqLYxkxv32rmJ2

**Comment by FaridSafi** [comment]
Can you test this workaround https://github.com/facebook/react-native/issues/8624#issuecomment-231040370 ?

**Comment by kfiroo** [comment]
@kennyzehn Are you using an external promise library?

**Comment by kennyzehn** [comment]
@kfiroo I use this one https://github.com/stefanpenner/es6-promise

**Comment by kfiroo** [comment]
@kennyzehn `react-native` ships with an implementation of an es6-compatible promise lib (with polyfills for `done`, `finally` etc.), so unless you need some special features that your lib offers I would suggest to remove it from your project and use the existing `Promise` object which is available as a global.

I think it might override the `Promise` impl with one that does not have `done` and this is why your app crash.

You would probably be able to reproduce it by using `InteractionManager.runAfterInteractions` without `react-native-gifted-chat`

**Comment by kennyzehn** [comment]
Thanks @kfiroo! Works much better. But there is also a other bug.
http://take.ms/0qshf

`render() {
        if(this.state.messages) {
            return (
                <View style={{flex: 1}}>
                    <GiftedChat messages={this.state.messages} onSend={this.onSend.bind(this)} user={{_id: 1}}/>
                </View>
            )
        } else {
            return (
                <Loading />
            )
        }
    }`

Any ideas?

**Comment by FaridSafi** [comment]
is the container of your component bigger than the screen ?

**Comment by kfiroo** [comment]
@kennyzehn Maybe open a new issue with a relevant title if the bug is real :)
Thanks!
