### ISSUE TITLE
GiftedChat crashing when mounting/re-mounting rapidly

### ISSUE THREAD

**Issue by thiagobrez** [FaridSafi/react-native-gifted-chat#1820]
#### Issue Description

When entering/re-entering multiples times (kind of in a fast way) my screen that contains GiftedChat, the app seems to crash trying to call `this.props.forwardRef.current.scrollToEnd` on the method `this.scrollToBottom` on **MessageContainer.js**.

If I got it right, this method is called upon mounting GiftedChat. I think the problem is that `this.props.forwardRef.current.scrollToEnd` doesn't check first if the ref is already set, unlike implementation for `scrollTo`, that checks first:

```
scrollTo(options) {
    if (this.props.forwardRef && this.props.forwardRef.current && options) {
        this.props.forwardRef.current.scrollToOffset(options);
    }
}
```

I was able to solve it locally by adding optional chaining to `scrollToBottom` call:

`this.props.forwardRef.current?.scrollToEnd`

Is this intentional in any way? I'd be happy to send a PR if wanted.

Thanks for the great package!

#### Steps to Reproduce / Code Snippets

Mount/re-mount Gifted Chat rapidly, multiple times with a great quantity of list items.

#### Expected Results

App shouldn't crash.

#### Additional Information

* Nodejs version: 12.11.1
* React version: 16.9.0
* React Native version: 0.61.5
* react-native-gifted-chat version: ^0.13.0
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: ^3.7.3

**Comment by Hirbod** [comment]
I think this is a rare case but you could provide a PR since it's not going to hurt

**Comment by thiagobrez** [comment]
Yeah I think it's an edge case too, probably because my screen isn't very well optimized. Anyway, wanted to let you guys know.

It caught my attention because it happened in production, I'll send the PR in a few minutes.

**Comment by thiagobrez** [comment]
Interesting.. when looking at the uncompiled code, the function looks like this:

```ts
  scrollToBottom = (animated: boolean = true) => {
    const { inverted } = this.props
    if (inverted) {
      this.scrollTo({ offset: 0, animated })
    } else if (this.props.forwardRef && this.props.forwardRef.current) {
      this.props.forwardRef!.current!.scrollToEnd({ animated })
    }
  }
```
Exclamation marks indicating the those values are asserted to be non-null.

Maybe I'm missing something? Is there any way I could have messed up this ref?
