### ISSUE TITLE
Animated: `useNativeDriver` was not specified

### ISSUE THREAD

**Issue by Gaurav453** [FaridSafi/react-native-gifted-chat#1825]
#### Issue Description

I am getting this warn in React-native-gifted-chat while rendring Image in the chat screen,that Animated: `useNativeDriver` was not specified and animations for opening and closing image are also not working as expected

#### Steps to Reproduce / Code Snippets
1. Just make a new project with given code in Readme.MD file of this repo
2. install dependencies and start project
3. try to reder image in chat screen by adding a img key in the message object
4. Run the project
#### Expected Results
Animations should run fine without any warn

#### Additional Information

* Nodejs version: 12.6.3
* React version: 16.11.0
* React Native version: 0.62.0
* react-native-gifted-chat version: 0.16.1
* Platform(s) (iOS, Android, or both?): Android

**Comment by rlems** [comment]
Actually this seems to be the correct fix: https://github.com/oblador/react-native-lightbox/pull/132

But react-native-lightbox doesn't seem to be maintained anymore, last Pull Request merged was in december. Might be good to upvote: https://github.com/oblador/react-native-lightbox/issues/129

**Comment by georgeMorales** [comment]
I also have the same problem, any solution for this?

**Comment by tanayuk** [comment]
+1

**Comment by rlems** [comment]
@georgeMorales What I did to solve this was copy the Lightbox and LightboxOverlay components from https://github.com/oblador/react-native-lightbox into my own project and add the useNativeDriver options like in https://github.com/oblador/react-native-lightbox/pull/132. 
After that I used the `renderMessageImage` property of GiftedChat to render my custom Lightbox implementation. You can use the GiftedChat code here to see how: https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/MessageImage.tsx

**Comment by cristiannietodev91** [comment]
I have the same warning in this moment. The app is not crashing but It's an annoying warning

**Comment by jeremycod** [comment]
+1

**Comment by antonioducs** [comment]
+1

**Comment by NikolasJody** [comment]
+1

**Comment by standreinmcp** [comment]
Having the same issue

**Comment by butterfly-valley** [comment]
Same issue

**Comment by butterfly-valley** [comment]
> @georgeMorales What I did to solve this was copy the Lightbox and LightboxOverlay components from https://github.com/oblador/react-native-lightbox into my own project and add the useNativeDriver options like in [oblador/react-native-lightbox#132](https://github.com/oblador/react-native-lightbox/pull/132).
> After that I used the `renderMessageImage` property of GiftedChat to render my custom Lightbox implementation. You can use the GiftedChat code here to see how: https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/MessageImage.tsx

Hey there, care to share the code please?

**Comment by Gapur** [comment]
I have the same issue
```Animated.event now requires a second argument for options```

**Comment by Gapur** [comment]
https://github.com/oblador/react-native-lightbox/issues/135

**Comment by hungvu193** [comment]
react-native-light-box can no longer be maintained, the best way to solve this problem is like @rlems answer

**Comment by mioppong** [comment]
Go into your npm packages, and search for 'react-native-lightbox', and in LightboxOverlay.js, follow the changes they made from the link below

https://github.com/oblador/react-native-lightbox/pull/132/commits/c80caf0f97eeb5cccb8363d3dfe0a6d62bbcfef9

**Comment by hungvu193** [comment]
So I resolved my issue:
1. Install patch-package: `npm install -g patch-package`
2. In your root of project create a folder name `patches` and inside `patches` folder create a file with name: `react-native-lightbox+8.8.1.patch` with the following content:
```javascript
diff --git a/node_modules/react-native-lightbox/LightboxOverlay.js b/LightboxOverlay.js
index 9e01f9a..d093b44 100644
--- a/node_modules/react-native-lightbox/LightboxOverlay.js
+++ b/node_modules/react-native-lightbox/LightboxOverlay.js
@@ -99,7 +99,7 @@ export default class LightboxOverlay extends Component {
       onPanResponderMove: Animated.event([
         null,
         { dy: this.state.pan }
-      ]),
+      ], { useNativeDriver: false }),
       onPanResponderTerminationRequest: (evt, gestureState) => true,
       onPanResponderRelease: (evt, gestureState) => {
         if(Math.abs(gestureState.dy) > DRAG_DISMISS_THRESHOLD) {
@@ -115,7 +115,7 @@ export default class LightboxOverlay extends Component {
         } else {
           Animated.spring(
             this.state.pan,
-            { toValue: 0, ...this.props.springConfig }
+            { toValue: 0, useNativeDriver: false, ...this.props.springConfig }
           ).start(() => { this.setState({ isPanning: false }); });
         }
       },
@@ -144,7 +144,7 @@ export default class LightboxOverlay extends Component {
 
     Animated.spring(
       this.state.openVal,
-      { toValue: 1, ...this.props.springConfig }
+      { toValue: 1, useNativeDriver: false, ...this.props.springConfig }
     ).start(() => {
       this.setState({ isAnimating: false });
       this.props.didOpen();
@@ -161,7 +161,7 @@ export default class LightboxOverlay extends Component {
     });
     Animated.spring(
       this.state.openVal,
-      { toValue: 0, ...this.props.springConfig }
+      { toValue: 0, useNativeDriver: false, ...this.props.springConfig }
     ).start(() => {
       this.setState({
         isAnimating: false,
```
4. After that run the command: `patch-package`.

You can also add it to postinstall insde package.json so that You dont have to be repeated every time node_modules is removed.
This is my favorite command:
```javascript
    "update:pods": "cd ios && pod install --repo-update && cd .. && patch-package",
    "postinstall": "yarn run update:pods"
```

**Comment by TomWallen** [comment]
> So I resolved my issue:
> 
> 1. Install patch-package: `npm install -g patch-package`
> 2. In your root of project create a folder name `patches` and inside `patches` folder create a file with name: `react-native-lightbox+0.8.1.patch` with the following content:
> 
> ```diff
> diff --git a/node_modules/react-native-lightbox/LightboxOverlay.js b/LightboxOverlay.js
> index 9e01f9a..d093b44 100644
> --- a/node_modules/react-native-lightbox/LightboxOverlay.js
> +++ b/node_modules/react-native-lightbox/LightboxOverlay.js
> @@ -99,7 +99,7 @@ export default class LightboxOverlay extends Component {
>        onPanResponderMove: Animated.event([
>          null,
>          { dy: this.state.pan }
> -      ]),
> +      ], { useNativeDriver: false }),
>        onPanResponderTerminationRequest: (evt, gestureState) => true,
>        onPanResponderRelease: (evt, gestureState) => {
>          if(Math.abs(gestureState.dy) > DRAG_DISMISS_THRESHOLD) {
> @@ -115,7 +115,7 @@ export default class LightboxOverlay extends Component {
>          } else {
>            Animated.spring(
>              this.state.pan,
> -            { toValue: 0, ...this.props.springConfig }
> +            { toValue: 0, useNativeDriver: false, ...this.props.springConfig }
>            ).start(() => { this.setState({ isPanning: false }); });
>          }
>        },
> @@ -144,7 +144,7 @@ export default class LightboxOverlay extends Component {
>  
>      Animated.spring(
>        this.state.openVal,
> -      { toValue: 1, ...this.props.springConfig }
> +      { toValue: 1, useNativeDriver: false, ...this.props.springConfig }
>      ).start(() => {
>        this.setState({ isAnimating: false });
>        this.props.didOpen();
> @@ -161,7 +161,7 @@ export default class LightboxOverlay extends Component {
>      });
>      Animated.spring(
>        this.state.openVal,
> -      { toValue: 0, ...this.props.springConfig }
> +      { toValue: 0, useNativeDriver: false, ...this.props.springConfig }
>      ).start(() => {
>        this.setState({
>          isAnimating: false,
> ```
> 
> 1. After that run the command: `patch-package`.
> 
> You can also add it to postinstall inside package.json so that You dont have to be repeated every time node_modules is removed.
> This is my favorite command:
> 
> ```js
>     "update:pods": "cd ios && pod install --repo-update && cd .. && patch-package",
>     "postinstall": "yarn run update:pods"
> ```
> 
> <img alt="Screen Shot 2020-10-29 at 15 15 28" width="412" src="https://user-images.githubusercontent.com/16502320/97542582-99093280-19f9-11eb-8672-38aa79003e3f.png">

Hi ! By trying to fix this with your solution, i have this message on the console :

patch-package 6.4.7
Applying patches...
Error: Patch file found for package lightbox which is not present at lightbox
---
patch-package finished with 1 error(s).

I do have lightbox in my node_module... and lightbox-v2. Do i make something wrong? 
Thanks !

**Comment by hungvu193** [comment]
@TomWallen react-native-lightbox+0.8.1.patch in this file 0.8.1 is your lightbox version, I use lightbox 0.8.1 btw. You need to change the file with your lightbox version.

**Comment by TomWallen** [comment]
> @TomWallen react-native-lightbox+0.8.1.patch in this file 0.8.1 is your lightbox version, I use lightbox 0.8.1 btw. You need to change the file with your lightbox version.

I just checked in my node_modules > react-native-lightbox. and my version is 0.8.1... ? maybe i check in the wrong place?
Also, in which folder do i make the cmd patch-package, in the root of the project, or in the patches folder? 

Very junior dev' here, i'm sorry if it seems a little bit clumsy!

**Comment by hungvu193** [comment]
@TomWallen you should run patch-packages at the root of project.

**Comment by TomWallen** [comment]
> @TomWallen you should run patch-packages at the root of project.

thanks for your reply ! unfortunately thats what i did the result is the same :/
