### ISSUE TITLE
Warning: Failed prop type: Invalid prop 'extraData' of type 'array' supplied to 'GiftedChat', expected 'object'.

### ISSUE THREAD

**Issue by LG1710** [FaridSafi/react-native-gifted-chat#1826]
#### Issue Description

Warning: Failed prop type: Invalid prop 'extraData' of type 'array' supplied to 'GiftedChat', expected 'object'.

Here is my extraData :
extraData={[this.dataChat, index]}

When i put an object like this :
extraData={{dataChat : this.dataChat, index : index}}
I get the reverse warning :
Warning: Failed prop type: Invalid prop 'extraData' of type 'object' supplied to 'GiftedChat', expected 'array'.

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: 16.8.3
* React Native version: 0.59.4
* react-native-gifted-chat version: 0.16.1
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: [FILL THIS OUT]

**Comment by LG1710** [comment]
Why did you change 
static propTypes = {
...
extraData: PropTypes.object 
...
}

to

static propTypes = {
...
 extraData: PropTypes.array 
...
}
in MessageContainer.tsx ?

**Comment by zhugy-yami** [comment]
same issue

**Comment by dabakovich** [comment]
Same issue.
I'll tell you more, guys. When passing array getting "expected 'object'" warning. When passing object getting "expected 'array'". LOL

**Comment by LG1710** [comment]
@xcarpentier could you look at this problem ?

**Comment by zhugy-yami** [comment]
> Same issue.
> I'll tell you more, guys. When passing array getting "expected 'object'" warning. When passing object getting "expected 'array'". LOL

LOL

**Comment by Aryk** [comment]
> Same issue.
> I'll tell you more, guys. When passing array getting "expected 'object'" warning. When passing object getting "expected 'array'". LOL

I'm getting the example same issue, it's driving me nuts lol

**Comment by apappas1129** [comment]
> Same issue.
> I'll tell you more, guys. When passing array getting "expected 'object'" warning. When passing object getting "expected 'array'". LOL

Why am I still getting this issue on `"react-native-gifted-chat": "^0.16.3"` ? Please help

**Comment by lukeramsden** [comment]
The fix has not been published to NPM yet as 0.16.3 predates the PR

**Comment by rndgrin** [comment]
will this be published to npm ? what is the proper way to silent this warning until then ?

**Comment by git-mwayz** [comment]
Is this issue has been resolved ?

**Comment by Feofilov** [comment]
please reopen this issue

**Comment by JEGardner** [comment]
Also experiencing this issue, I presume because there hasn't been a new release in over a year?

**Comment by c-goettert** [comment]
This console error has been with me for over a year now as well. If this is merged already, why is there no new release? :(

**Comment by fukemy** [comment]
any solution here? No confirm from gifted chat dev?? Why they avoid this problem?

**Comment by raahimkhan** [comment]
Getting same warning in 2024 as well
