### ISSUE TITLE
Render time on right and left side of bubble

### ISSUE THREAD

**Issue by usamaahm61** [FaridSafi/react-native-gifted-chat#1827]
#### Issue Description
I want to render the time on the bubble like shown in the picture on left and right side of the bubble
![crop](https://user-images.githubusercontent.com/52953543/84256381-448a1700-ab2d-11ea-8683-650eb73ac218.png)

**Comment by kalyanijamunkar10** [comment]
@usamaahm61  have you fixed it?  i am facing same issue
