### ISSUE TITLE
Is this compatible with react native 0.27

### ISSUE THREAD

**Issue by baso6706144011** [FaridSafi/react-native-gifted-chat#183]
i tried to use this component, but i had a problem 

> __DEV__ is not defined. 

i have deleted .babelrc in node_modules/react-native-gifted-chat/ (like the suggestion in other issue) but still the error not fixed yet. i'm wondering if my react native version is uncompatible with this latest component.

**Comment by FaridSafi** [comment]
I guess so, please test with 0.30.0 or 0.31.0
