### ISSUE TITLE
onSend does not trigger when empty text input

### ISSUE THREAD

**Issue by Marcados** [FaridSafi/react-native-gifted-chat#1835]
#### Issue Description

onSend does not trigger when the text input is empty.

#### Steps to Reproduce / Code Snippets

alwaysShowSend={true} then click on send button. onSend does not trigger.

#### Expected Results

Expected onSend to be triggered, in order to customise it, i.e. for sending image.

#### Additional Information

* Nodejs version: 12.14.1
* React version: 16.9.0
* React Native version: 0.61.4
* react-native-gifted-chat version: 0.16.1
* Platform(s) (iOS, Android, or both?): both

**Comment by danielmejiadev** [comment]
That's the current behaviour, the onSend callback should be avaialble if there is a text to send.

**Comment by Marcados** [comment]
That is the point. onSend should be triggered when clicking on it if we choose alwaysDisplay. That allows more customisation like sending images in some unique way.

**Comment by Akhileshkumar001** [comment]
fchgvjbhk jnm.,

**Comment by Akhileshkumar001** [comment]
fdgjhbjnm

**Comment by rahulkhairnarr** [comment]
@mb8z did you find any solution ?
