### ISSUE TITLE
renderUsername prop of Bubble does not work

### ISSUE THREAD

**Issue by stilllife00** [FaridSafi/react-native-gifted-chat#1836]
#### Issue Description

`renderUsername` prop of Bubble does not work

#### Steps to Reproduce / Code Snippets

Try to render a custom bubble with `renderBubble`. In that function return a `Bubble` passing to it `renderUsername` as a function that returns a JSX.Element. The default username is rendered.

#### Expected Results
The custom JSX.Element is rendered

#### Additional Information

* Nodejs version: 12.xx
* React version: 16.9
* React Native version: 0.61
* react-native-gifted-chat version: 0.16.1
* Platform(s) (iOS, Android, or both?): both

**Comment by stilllife00** [comment]
Bump

**Comment by stilllife00** [comment]
bump 2

**Comment by stilllife00** [comment]
Nothing is moving here, is there something I can do?

**Comment by darron1217** [comment]
Still not working on latest

**Comment by AdamLee321** [comment]
This is still not working, is this repo no longer maintained?

**Comment by dpark4574** [comment]
Still not working

**Comment by abylay-11** [comment]
Still not working?
