### ISSUE TITLE
"minHeight" is not a valid style property.

### ISSUE THREAD

**Issue by explorigin** [FaridSafi/react-native-gifted-chat#184]
https://github.com/FaridSafi/react-native-gifted-chat/commit/f79ee2d6975331aad5b47c14bbc3677a0172994a#diff-1c6726bb36b3f7b58a5e62aa8033c5a7R140

**Comment by FaridSafi** [comment]
Hello,  what RN version do you use ?

**Comment by explorigin** [comment]
0.28

**Comment by FaridSafi** [comment]
minHeight was implemented in RN 0.29.0

**Comment by explorigin** [comment]
OK, maybe it'd be helpful to specify a minimum version supported. (I'm stuck on 0.28 for a bit longer)

**Comment by FaridSafi** [comment]
I am adding it in the readme, thank you

**Comment by FaridSafi** [comment]
I think you can safely remove this line locally until you migrate to newer version
