### ISSUE TITLE
How can I change chat text color if sent mail-id as message

### ISSUE THREAD

**Issue by saurabh874** [FaridSafi/react-native-gifted-chat#1841]
Hi,
if i am text someone my mail-id its colour is coming white. even i change textstyle in customBubble.
my custom code like.
 <Bubble
        {...props}
        textStyle={{
            right: {
                color: '#000000',
                fontSize: 16,
                lineHeight: 24,
                letterSpacing: 0.44,
                fontFamily: theme.fonts.regular.fontFamily,
            },
            left: {
                color: '#000000',
                fontSize: 16,
                lineHeight: 24,
                letterSpacing: 0.44,
                fontFamily: theme.fonts.regular.fontFamily,
            },
        }}
        wrapperStyle={{
            right: {
                elevation: 1,
                shadowOpacity: 1,
                shadowColor: 'rgba(0,0,0,0.13)',
                shadowOffset: { width: 1, height: 5 },
                backgroundColor: theme.colors.chatBubble,
                marginTop: 10,
                borderRadius: 10,
                marginRight: 16,
            },
            left: {
                elevation: 1,
                paddingTop: 2,
                shadowOpacity: 1,
                shadowColor: 'rgba(0,0,0,0.13)',
                shadowOffset: { width: 1, height: 5 },
                marginTop: 10,
                borderRadius: 10,
                backgroundColor: theme.colors.textWithBG,
            },
        }}
        containerToNextStyle={{
            right: {
                borderBottomRightRadius: 10,
            },
            left: {
![Screenshot 2020-06-19 at 1 23 29 PM](https://user-images.githubusercontent.com/59818553/85110173-180e8300-b230-11ea-9732-98c20850b7a9.png)

                borderBottomLeftRadius: 10,
            },
        }}
        containerToPreviousStyle={{
            right: {
                borderTopRightRadius: 10,
            },
            left: {
                borderTopLeftRadius: 10,
            },
        }}
    />

**Comment by saurabh874** [comment]
Got the solution i used renderMessage function and define link style.

**Comment by gabcvit** [comment]
I was trying to reach a similar solution, all links in the Bubbles on the right wing were showing up white as default. My solution was a bit different though, I added the `linkStyle` as a propriety of my customised `renderBubble()` function. Maybe it's just a slightly different approach to reach the same goal. But worth sharing anyway in case anyone needs it. 

Here's the solution that worked for me:
```
renderBubble(props) {
    return (
      <Bubble
        {...props}
        textStyle={{
          left: {
            color: "#545454"
          },
          right: {
            color: "#545454"
          }
        }}
        linkStyle={{
          left: {
            color: "#545454"
          },
          right: {
            color: "#545454"
          }
        }}
      />
    )
  }
```
