### ISSUE TITLE
gifted-chat is not installing

### ISSUE THREAD

**Issue by maybeusama** [FaridSafi/react-native-gifted-chat#1843]
hello,
when i run this cmd "npm i react-native-gifted-chat" the following errors occur:
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/EvanBacon/react-native-parsed-text.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
kindly reslove this!

**Comment by samuk190** [comment]
can you please try using yarn?
do yarn add raect-native-gifted-chat

**Comment by maybeusama** [comment]
> can you please try using yarn?
> yarn add react-native-gifted-chat

not done with yarn 
firstly run this cmd 'npm install -g yarn'
then goto project directory and run
yarn add react-native-gifted-chat
it give the warnings and nolock file is found

**Comment by samuk190** [comment]
> > can you please try using yarn?
> > yarn add react-native-gifted-chat
> 
> not done with yarn
> firstly run this cmd 'npm install -g yarn'
> then goto project directory and run
> yarn add react-native-gifted-chat
> it give the warnings and nolock file is found

first you need get rid of your npm lock file, then you do 
yarn 
and it will automatically create a package.json file, then you do yarn add react-native-gifted-chat

**Comment by TheLonelyAstronaut** [comment]
Try npm cache clean --force, it helps me.

**Comment by maybeusama** [comment]
@samuk190  still I get this error 
![WhatsApp Image 2020-06-23 at 11 12 10 AM (1)](https://user-images.githubusercontent.com/67146191/85367437-a9d50380-b542-11ea-8416-8824d36ebc81.jpeg)

**Comment by EhteshamAnwar** [comment]
same problem here,  found any solution?

**Comment by xcarpentier** [comment]
This is because you haven’t git installed  maybe...

**Comment by maybeusama** [comment]
@xcarpentier git is installed in my pc and still not working!!

![](https://user-images.githubusercontent.com/67146191/85367437-a9d50380-b542-11ea-8416-8824d36ebc81.jpeg)
