### ISSUE TITLE
Element type is Invalid Error

### ISSUE THREAD

**Issue by swaroopa94** [FaridSafi/react-native-gifted-chat#186]
Hii,
I am using this module but when i am clicking on the  Choose From Library (clicking on '+' button)
got the following error
![simulator screen shot 12-aug-2016 4 54 06 pm](https://cloud.githubusercontent.com/assets/19324363/17622006/45f0bb38-60b5-11e6-97b1-839094a14d61.png)

Please suggest me how to solve this..

**Comment by FaridSafi** [comment]
Hello,
Can you provide your code example please?

**Comment by FaridSafi** [comment]
I think you are trying to render a non-react component

**Comment by swaroopa94** [comment]
The sending  Loaction option is working fine but sending images leads to this error
