### ISSUE TITLE
Why does onSend method accept array of messages, not single message, as parameter?

### ISSUE THREAD

**Issue by ziyaddin** [FaridSafi/react-native-gifted-chat#1863]
**References:**
https://github.com/FaridSafi/react-native-gifted-chat/blob/13a643ecaa1906817615019fb180de7cafc3aed0/src/GiftedChat.tsx#L146

https://github.com/FaridSafi/react-native-gifted-chat/blob/13a643ecaa1906817615019fb180de7cafc3aed0/src/GiftedChat.tsx#L707

**Comment by benjamin-daniel** [comment]
I don't really understand it but It gives more flexibility so if you were to add multiple message(from network request or message forwarding like that of WhatsApp), you can easily do it than do concatting of arrays yourself. I hope I answered your question😊
