### ISSUE TITLE
keyboardShouldPersistTaps does not have a default value, Breaking changes on Android RN 0.62.+? 

### ISSUE THREAD

**Issue by shamilovtim** [FaridSafi/react-native-gifted-chat#1869]
Android changes on RN 0.62+

1. Breaking: Tapping the scrollview at the top no longer minimizes the keyboard on Android. Need to pass keyboardShouldPersistTaps={'never'} even though this should be the default value?

**Comment by xcarpentier** [comment]
Yes it should be the default!

**Comment by shamilovtim** [comment]
I think its still actual

**Comment by xcarpentier** [comment]
Yes I think so

**Comment by shamilovtim** [comment]
Bump

**Comment by shamilovtim** [comment]
bump
