### ISSUE TITLE
Whatsapp chat Bubble

### ISSUE THREAD

**Issue by Uttu316** [FaridSafi/react-native-gifted-chat#1875]
#### Issue Description
How can I create a message Bubble like a Whatsapp Bubble? Time must be at the same line for a single line message otherwise below it. 
The bubble should have a minimum width and message text should be flex-start and time would be flex-end.

I tried to restyle the Bubble and Time component but nothing achieved so far.
#### Steps to Reproduce / Code Snippets

![Screenshot_1595278386](https://user-images.githubusercontent.com/34169292/87985684-a610ae80-caf9-11ea-9026-d295ea9b1d9a.png)

#### Expected Results

![image](https://user-images.githubusercontent.com/34169292/87985287-f2a7ba00-caf8-11ea-8098-4686c6c24367.png)

**Comment by Raphaelinyang** [comment]
how are you able to make foreign users chat appear on the left?

**Comment by Uttu316** [comment]
Check documentation.

**Comment by Raphaelinyang** [comment]
at where?

**Comment by Raphaelinyang** [comment]
`<GiftedChat
      messages={messages}
      onSend={handleSend}
      user={{ id: user.uid, name: user.displayName, avatar: user.photoURL }}
      renderBubble={renderBubble}
      placeholder='Type your message here...'
      isTyping= {true}
      renderSend={renderSend}
      alwaysShowSend
      scrollToBottom
      scrollToBottomComponent={scrollToBottomComponent}
      renderSystemMessage={renderSystemMessage}
    />`

`function renderBubble(props) {
        return (
          // Step 3: return the component
          <Bubble
            {...props}
            wrapperStyle={{
              right: {
                // Here is the color change
                backgroundColor: 'grey'
              },
              left: {
                backgroundColor: 'green'
              }
            }}
            textStyle={{
              right: {
                color: '#fff'
              }
            }}
          />
        );
      }`

please, where is the issue coming from?

**Comment by Raphaelinyang** [comment]
> Check documentation.

i have checked the npm documentation

**Comment by hackrx** [comment]
Hey @uttu316 can you please share the code for the text input UI you have made here,
also are you able to use onTextChanged property or onChangeText or onEndEditing (see  #1874)
 
![image](https://user-images.githubusercontent.com/54453778/88226468-bce60b00-cc89-11ea-9223-a298c0b56d8c.png)

**Comment by kalyanijamunkar10** [comment]
@Uttu316 , any luck on this. Facing same issue.

**Comment by Uttu316** [comment]
> 
> 
> Hey @Uttu316 can you please share the code for the text input UI you have made here,
> also are you able to use onTextChanged property or onChangeText or onEndEditing (see #1874)
> 
> ![image](https://user-images.githubusercontent.com/54453778/88226468-bce60b00-cc89-11ea-9223-a298c0b56d8c.png)

Use this prop 
 onInputTextChanged={e => {
        if (e === '') {
          setIsTyping(false);
        } else {
          setIsTyping(true);
        }
      }}
and this is how I did it. Hope it would help

**Comment by Uttu316** [comment]
> 
> 
> @Uttu316 , any luck on this? Facing same issue.



> 
> 
> @Uttu316 , any luck on this? Facing same issue.

No, Did you find anything? Please tell me something about it?

**Comment by Uttu316** [comment]
> 
> 
> > Check documentation.
> 
> i have checked the npm documentation

Pass messages array in messages prop. and give right side user id in user prop. Thats it!

**Comment by Raphaelinyang** [comment]
please, i will really appreciate it, if you can show me how you did yours, cos ive tried this method, and its not working

> > > Check documentation.
> > 
> > 
> > i have checked the npm documentation
> 
> Pass messages array in messages prop. and give right side user id in user prop. Thats it!

**Comment by mi2468** [comment]
i have a issue on message bubble . the issue is when i try to send long message for example 4 to 5 lines message the time on the right side going outside of the bubble. i need same like whatsapp if single line message show time in single line itself and if multiline message show it  below. how can i solve this  any one can help me
