### ISSUE TITLE
long press for copy popup occurs two times in android

### ISSUE THREAD

**Issue by horizon-myself** [FaridSafi/react-native-gifted-chat#1876]
#### Issue Description

I am using gifted chat. I like it. Thanks for the Gifted chat project 
Recently added popup function for delete (also copy).
It works well when keyboard input is not shown. However, it shows popup two times when keyboard input (keyboardavodingview) is shown.

If I select command (copy or delete) in the popup, it only dismiss keyboard input (without doing selected command) and shows popup again. Then, the second popup works properly.

I guess that the first popup event (user selects copy or delete command) is not passed properly to gifted chat. I am using KeyboardAvoidingView.

#### Steps to Reproduce / Code Snippets
Below are steps details.

1. show keyboard input (type message).
2. long press message to copy / delete.
3. popup shown.
4. select copy or delete.
5. keyboard dismiss.
6. popup shown again.
7. select copy or delete - it works.

[FILL THIS OUT]

Popup shown one time.

[FILL THIS OUT]

Below are my codes.
onLongPress = (context, pressed_message) =>
{
        if (this.props.onLongPress) {
                this.props.onLongPress(this.context, this.props.currentMessage);
        } else
        {
                if (pressed_message.text!=='')
                {
                        console.log(context, pressed_message);
                        const options = ['Copy', 'Delete', 'Cancel'];
                        const cancelButtonIndex = options.length;
                        context.actionSheet().showActionSheetWithOptions(
                        {options, cancelButtonIndex}, (buttonIndex) =>
                                {
                                switch (buttonIndex)
                                {
                                case 0:
                                        Clipboard.setString(pressed_message.text);
                                        break;
                                case 1:
                                        let result=fire.delete(pressed_message);
                                        break;
                               }})
};}}

**Comment by horizon-myself** [comment]
I found setting keyboardShouldPersistTaps={'always'} solves problem in ios.
However, keyboardShouldPersistTaps={'always'} does not work for android phone.

https://github.com/FaridSafi/react-native-gifted-chat/issues/405
   
<View style={styles.container}>
<KeyboardAvoidingView style={styles.KeyboardAvoidingView_container} behavior={ Platform.OS === 'android' ? "padding" : null } enabled >
<GiftedChat
          keyboardShouldPersistTaps={'always'}
//

**Comment by RashimNarayanTiku** [comment]
I am having the same issue, why is it not getting worked on? Is it too hard to solve ?
