### ISSUE TITLE
Message opens at beginning of message history and scrolls to bottom

### ISSUE THREAD

**Issue by craftmusic** [FaridSafi/react-native-gifted-chat#1879]
#### Issue Description

When I open a chat message, it is showing the very first message in the history and then automatically scrolling through all of the messages from top to bottom by itself. It's very annoying when there is a long chat history to see all of the messages scrolling before my eyes whenever I open the chat. I want it to just open already at the bottom of the page, showing the latest message in the chat history.

#### Steps to Reproduce / Code Snippets

Implemented GiftedChat according to the docs.

#### Expected Results

Open a message and immediately see the latest message at the bottom of the screen, instead of seeing the screen scrolling by itself from top to bottom.

#### Additional Information

* React Native version: 0.60.0
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): iOS

**Comment by ipekmuhammet** [comment]
same

**Comment by zees98** [comment]
2 years into the issue. The problem still persists.

**Comment by 2byrds** [comment]
> 2 years into the issue. The problem still persists.

Are you on the beta branch?  If so what version?

**Comment by zees98** [comment]
The version is 0.16.3

**Comment by 2byrds** [comment]
> The version is 0.16.3

Ah that is very old, and it looks like beta just got released!! Try https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/v1.0.0

**Comment by zees98** [comment]
Ooops, my bad. I'll try it out and get back to you. Thanks
