### ISSUE TITLE
Add extra option onholdpress to delete message

### ISSUE THREAD

**Issue by cherimo** [FaridSafi/react-native-gifted-chat#1882]
Hai,

I want the ability to remove a message item when I pressonhold.
I see diffrent implementations but can't find the right way to fix this.
Some code examples doesnt work on the recent version unfortunately.

Is there a link/post where the option to delete a message is available?

Please let me know.

**Comment by samuk190** [comment]
I think you need to override the options on the message and add "Delete message" function and send id of the message to delete to the server too , depends on what you are using

**Comment by leelandclay** [comment]
I just implemented it by overriding the onLongPress property. That event will send a context and a message object. Just look in the message object to get the _id, and delete it. I personally use firebase to store my messages, so I call out to the store to delete and then let the .on("child_removed") event handler remove the message from the chat once it's completed the delete.
