### ISSUE TITLE
All messages align to the right, either foreign or personal

### ISSUE THREAD

**Issue by Raphaelinyang** [FaridSafi/react-native-gifted-chat#1884]
#### Issue Description

All messages align to the right, please check the image below for more details

![Screenshot_20200727-154830](https://user-images.githubusercontent.com/45435635/88559345-9d056d00-d024-11ea-9420-3948784b2ff6.png)

#### Steps to Reproduce / Code Snippets

`<GiftedChat
      messages={messages.slice()}
      onSend={ handleSend}
      user={{id: user.uid, name: user.displayName, avatar: user.photoURL,}}
      renderBubble={renderBubble}
      placeholder='Type your message here...'
      isTyping= {true}
      renderSend={renderSend}
      alwaysShowSend
      loadEarlier={true}
      showAvatarForEveryMessage={true}
      scrollToBottom
      scrollToBottomComponent={scrollToBottomComponent}
      renderSystemMessage={renderSystemMessage}
      alignTop={true}
      renderLoading={renderLoading}
    />`

#### Expected Results

expect foreign messages to appear at the left, while the current user's message appears on the right

#### Additional Information

* Nodejs version: latest version
* React Native version: latest version
* react-native-gifted-chat version: latest version
* Platform(s) (iOS, Android, or both?): Android

**Comment by MshahzadRasheed** [comment]
@Raphaelinyang did u solved this problem ? i m also facing same issue .

**Comment by MshahzadRasheed** [comment]
hi @Raphaelinyang 


> #### Issue Description
> All messages align to the right, please check the image below for more details
> 
> ![Screenshot_20200727-154830](https://user-images.githubusercontent.com/45435635/88559345-9d056d00-d024-11ea-9420-3948784b2ff6.png)
> 
> #### Steps to Reproduce / Code Snippets
> `<GiftedChat messages={messages.slice()} onSend={ handleSend} user={{id: user.uid, name: user.displayName, avatar: user.photoURL,}} renderBubble={renderBubble} placeholder='Type your message here...' isTyping= {true} renderSend={renderSend} alwaysShowSend loadEarlier={true} showAvatarForEveryMessage={true} scrollToBottom scrollToBottomComponent={scrollToBottomComponent} renderSystemMessage={renderSystemMessage} alignTop={true} renderLoading={renderLoading} />`
> 
> #### Expected Results
> expect foreign messages to appear at the left, while the current user's message appears on the right
> 
> #### Additional Information
> * Nodejs version: latest version
> * React Native version: latest version
> * react-native-gifted-chat version: latest version
> * Platform(s) (iOS, Android, or both?): Android

you should maintain your chat data like this
        {_id:(userID)
        text:(chat messages)
        createdAt: formatted time
        user: {
          _id: senderID/receiver id
          name: sender/receiver name
        }
}
may be this will help you ..
