### ISSUE TITLE
Chat View not updating

### ISSUE THREAD

**Issue by Aashir-334** [FaridSafi/react-native-gifted-chat#1885]
Chat view not rendering for new chat still have previous user messages in the list

**Comment by skdev24** [comment]
Try Updating the `_id` of that message data, shared a small code snippets,

`const updateCountry = (updatedValue) => {

    const updatedMessages = messages.map((item) => {
      if (item._id === updatedValue._id) {
        return { ...updated, _id: uuidv1() };
      }
      return item;
    });

    setMessages(updatedMessages);
  };`

**Comment by skdev24** [comment]
Try Updating the `_id` of that message data, shared a small code snippets,

```
const updateCountry = (updatedValue) => {
    const updatedMessages = messages.map((item) => {
      if (item._id === updatedValue._id) {
        return { ...updated, _id: uuidv1() };
      }
      return item;
    });
    setMessages(updatedMessages);
  };
````

**Comment by sandeepg1220** [comment]
Even me also facing issue with images. If I clear messages object in state the text messages cleared but not the images.
this.setState({
      messages: emptyArr,
    },() => console.log("messages in state : ",this.state.messages))
