### ISSUE TITLE
How to add attach file button ? 

### ISSUE THREAD

**Issue by boypanjaitan16** [FaridSafi/react-native-gifted-chat#1886]
For default there is only input text, how to add file attachment button ? is it a custom view ? or any props to show that button?

**Comment by jjf21** [comment]
Hi,
You can use the `renderActions` props.
```jsx
<GiftedChat ... renderActions={(props) => {<CustomAction />}} />
```

**Comment by inacio0196** [comment]
props?

**Comment by inacio0196** [comment]
how to use props?

**Comment by walidvb** [comment]
@inacio0196 you'll want to understand how react works, first, i suppose. But here's a little preview of what you might want to be doing: https://github.com/FaridSafi/react-native-gifted-chat/blob/master/example-expo/AccessoryBar.tsx
