### ISSUE TITLE
TextInput is jumping up on iOS

### ISSUE THREAD

**Issue by patrinoua** [FaridSafi/react-native-gifted-chat#1888]
#### Issue Description

There is a space under the text Input - only on iOs.
This happened after I added Tab and Stack Navigators.
 
#### Additional Information

* Nodejs version: 10.15.3
* React version: 16.9.0
* React Native version: sdk-36.0.1
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): both. Issue only on iOS

<img src="https://user-images.githubusercontent.com/36475005/88945667-8f532000-d28e-11ea-860e-7d54000ada51.jpg" width="250"  />

**Comment by patrinoua** [comment]
<GiftedChat
    messages={messages}
    user={{ _id: 1 }}
    onSend={this.onSend}
    bottomOffset={Platform.OS === "ios" && 48.5}
/> 

This solved it for me  https://github.com/FaridSafi/react-native-gifted-chat/issues/278

**Comment by sami3898** [comment]
hey @patrinoua, it's not working in my case. do you have any other solution?

**Comment by patrinoua** [comment]
Check GiftedChat component and experiment around a bit with bottomOffset

**Comment by sami3898** [comment]
> Check GiftedChat component and experiment around a bit with bottomOffset

okay I'll let you know if I find any success or not ;)

**Comment by AND-GORNIY** [comment]
For me helped  bottomOffset={insets.bottom + 48} insets fro. react-native-safe-area-context, and hook from this library

**Comment by gabrielgambarra** [comment]
The @AND-GORNIY solution almost helped me 100%. I just removed "+ 48" and it worked to me.
