### ISSUE TITLE
What's the right way to trigger a re-render for renderLoadEarlier?

### ISSUE THREAD

**Issue by thekevinscott** [FaridSafi/react-native-gifted-chat#189]
Hi,

I have a custom `<Button />` I'm using for `renderLoadEarlier`. I'm using Redux, and this button's loading state is tied to an ajax call that fetches messages (and sets the current loading state).

What is the right way to trigger this render? Prop changes to the parent component don't seem to re-trigger a re-render.

As a point of reference, if I modify `MessageContainer`:

```
shouldComponentUpdate(nextProps, nextState) {
    if (this.props.messagesHash === nextProps.messagesHash && this.props.loadEarlier === nextProps.loadEarlier && this.props.isLoadingEarlier === nextProps.isLoadingEarlier) {
      return false;
    }
    return true;
  }
```

where `isLoadingEarlier` is tied to my redux store, then the load earlier button will update correctly.

What's the right way to implement this behavior without hacking the source?

Thanks!

**Comment by kfiroo** [comment]
@FaridSafi Didn't we remove the `messagesHash` for just that reason?

**Comment by kfiroo** [comment]
@thekevinscott Are you using the latest version?

**Comment by FaridSafi** [comment]
@kfiroo yes
@thekevinscott I am preparing a new version with `isLoadingEarlier` support

**Comment by FaridSafi** [comment]
v0.0.7 has been published with `isLoadingEarlier` support

**Comment by thekevinscott** [comment]
@FaridSafi Thanks, works like a charm!
