### ISSUE TITLE
Is it possible to change the pending icon?

### ISSUE THREAD

**Issue by brian-chung-dragon** [FaridSafi/react-native-gifted-chat#1893]
#### Issue Description

Hi, I wonder is it possible to change the pending icon inside the chat bubble?

#### Additional Information
* react-native-gifted-chat version: 0.16.3

**Comment by Aryk** [comment]
Right now it's a clock loader...but not sure how to overwrite it.

**Comment by brian-chung-dragon** [comment]
Hi @Aryk you can override it using the rednerTick function
