### ISSUE TITLE
While giving border radius at the corner of right side messages we are getting blue colour

### ISSUE THREAD

**Issue by Jayanth-123** [FaridSafi/react-native-gifted-chat#1894]
#### Issue Description

We customised the gifted chat messages using message container component.We want to add border radius to messages.For left side messages while we added border radius it is displaying correctly but when we add border radius above 4 to we are getting blue colour at the corner of the messages.

#### Steps to Reproduce / Code Snippets

export const renderMessageText = (props: any) => (
  <View style={{ minHeight: 20, alignItems: 'center' }}>
    <MessageText
      {...props}
      containerStyle={{
        left: {
        
          backgroundColor: '#f1f2f4',
          // width: 256,
          // height: 88,
        
          borderRadius: 6
        },
        right: {
        
          backgroundColor: '#ff2d55',
          borderRadius: 6,
          // width: 228,
          // height: 52
      
        }
      }}
      textStyle={{
        left: {
        
          color: '#242a37',
        
        //  fontSize: 14,
          // width: 237,
          // height: 66,
          // lineHeight: 20,
          // fontFamily: 'Sf_ui_display',
          textAlign: 'center'
        },
        right: {
          color: '#ffffff',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          fontSize: 14,
          fontWeight: '500'
          // lineHeight: 20
          // fontFamily: 'Sf_ui_display'
        }
      }}
      linkStyle={{
        left: { color: 'orange' },
        right: { color: 'orange' }
      }}
      // customTextStyle={{ fontSize: 24, lineHeight: 24 }}
    />
  </View>
);

#### Expected Results
![messageContainer](https://user-images.githubusercontent.com/54257987/89297440-775e1080-d681-11ea-977f-20e5318ec00b.png)

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: '16.13.1'
* React Native version: 'https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz'
* react-native-gifted-chat version: '^0.16.1'
* Platform(s) (iOS, Android, or both?): iOS
* TypeScript version:'~3.8.3'

**Comment by quyenlt1812** [comment]
It's the colour of bubble. Change the bubble wrapper babkground to transparent to remove blue colour
```
renderBubble={props => {
        return (
          <Bubble
            {...props}
            textStyle={{
              left: styles.textLeftStyle,
              right: styles.textRightStyle,
            }}
            wrapperStyle={{
              right: {
                backgroundColor: 'transparent'
              },
              right: {
                backgroundColor: 'transparent'
              },
            }}
          />
        )
      }}
```

**Comment by MohsinTariqK** [comment]
I am still seeing the blue background even after providing `backgroundColor: "transparent"` to wrapperStyle.right
