### ISSUE TITLE
Gap between text input and keyboard on iOS

### ISSUE THREAD

**Issue by patrinoua** [FaridSafi/react-native-gifted-chat#1895]
#### Issue Description
Gap between text input and keyboard on iOS

#### Steps to Reproduce / Code Snippets

This first appeared when I implemented Tab and Stack Navigation.
I upgraded to the latest version of gifted chat but it is still not solved.
Any ideas?

#### Additional Information

* Nodejs version: 10.15.3
* React version: 16.9.0
* React Native version: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz
* react-native-gifted-chat version: ^0.16.3
* Platform(s) (iOS, Android, or both?): iOs
![IMG_5700](https://user-images.githubusercontent.com/36475005/89401870-454abe00-d716-11ea-9430-b27e6d908195.PNG)

**Comment by patrinoua** [comment]
<GiftedChat
    messages={messages}
    user={{ _id: 1 }}
    onSend={this.onSend}
    bottomOffset={Platform.OS === "ios" && 48.5}
/> 

This solved it for me  https://github.com/FaridSafi/react-native-gifted-chat/issues/278

**Comment by theobouwman** [comment]
@patrinoua  thanks!
I use this so it takes the right offset:
```js
import { useBottomTabBarHeight } from '@react-navigation/bottom-tabs';

// ...

const tabBarHeight = useBottomTabBarHeight();
```
https://reactnavigation.org/docs/bottom-tab-navigator/#tabbarstyle
