### ISSUE TITLE
html tag and &nbshp; is showing inside chat message 

### ISSUE THREAD

**Issue by 026binit** [FaridSafi/react-native-gifted-chat#1896]
#### Issue Description

i want to handle html tags in my chat message. i don't want to display those html tags but don't know to handle html tags please help

<p>hello test message</p>
<a> test link </a>
test &nbsp;

expo-sdk : 38
react-native-gifted-chat : 0.16.3
platform : Android
[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets
```

<p>hello test message</p>
<a> test link </a>
test &nbsp;
```
i want to remove p tags a tags &nbsb; from my chat message

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): Android && IOS
* expo sdk-version : 38

**Comment by lewatt23** [comment]
@026binit  any solution pls ?

**Comment by kenkotch** [comment]
for those looking for a solution - this may help:

```
import HtmlView from 'react-native-htmlview';
...
const containsHtml = /<\/?[a-z][\s\S]*>/i.test(currentMessage.text);
if (containsHtml) {
    return (
        <HtmlView value={currentMessage.text} />
    )
}

return (
    <MessageText... />
)
```
