### ISSUE TITLE
Why not apply scrollToBottom when having new message while inverter = true?

### ISSUE THREAD

**Issue by quyenlt1812** [FaridSafi/react-native-gifted-chat#1899]
#### Issue Description
I wonder why don't you left the chat scroll to bottom when inverted is true?

#### Steps to Reproduce / Code Snippets

I saw those lines in your code 
```
  if (inverted === false &&
            messages &&
            prevProps.messages &&
            messages.length !== prevProps.messages.length) {
            setTimeout(() => this.scrollToBottom(false), 200);
        }
```

#### Expected Results

Should scroll to bottom when have a new message. Sometimes I expect when user is in the middle of the conversation. We can add something like `3 new messages` (or something like that) then press on it will scrollToBottom. Or you can expose the scrollToBottom function or the chat ref so we can control it easier

#### Additional Information

* Nodejs version: v10.19.0
* React version: 16.9.0
* React Native version: 0.61.4
* react-native-gifted-chat version:0.16.1
* Platform(s) (iOS, Android, or both?): both

**Comment by kevgrig** [comment]
> Or you can expose the scrollToBottom function or the chat ref so we can control it easier

```
<GiftedChat
  ref={(ref) => this._giftedChat = ref }
  ...
/>

...

somefunction = () => {
  this._giftedChat.scrollToBottom(true);
}

```
