### ISSUE TITLE
Maximum call stack size exceeded with custom avatar

### ISSUE THREAD

**Issue by bsiddiqui** [FaridSafi/react-native-gifted-chat#190]
```js
renderAvatar={props => <Avatar {...props} containerStyle={{ backgroundColor: 'white' }} />}
```
leads to a max call stack error

**Comment by FaridSafi** [comment]
You can try
```jsx
containerStyle={{
  left: {
    backgroundColor: 'white' 
  },
  right: {
    backgroundColor: 'white' 
  },
}}
```

**Comment by fengliu222** [comment]
Because the `Avatar` component will invoke `renderAvatar` function. if your `renderAvatar` function return a `Avatar` component, it will make retain cycle.
so you can try 

```
renderAvatar={props => {
  delete props.renderAvatar
  <Avatar {...props} containerStyle={{ backgroundColor: 'white' }} />
}}
```

**Comment by kfiroo** [comment]
shouldn't `Message` call `renderAvatar` if it exists, just as it does for `Bubble` and `Day`?

**Comment by bsiddiqui** [comment]
@fengliu222 got an issue that cannot delete that property so tried to use `lodash omit`. Combining that with @FaridSafi suggestion changed the style but it also messed up margin

<img width="77" alt="screenshot 2016-08-15 14 07 56" src="https://cloud.githubusercontent.com/assets/2721959/17679780/cd00ce0e-62f1-11e6-8161-7de4bbd4e45e.png">

**Comment by FaridSafi** [comment]
v0.0.8 has been published - custom avatar doesn't receive renderAvatar anymore

@bsiddiqui @fengliu222 you don't need to delete `props.renderAvatar` anymore, can you tell me if 0.0.8 fixes your issue please ?

**Comment by FaridSafi** [comment]
please re open if you still experience this issue
