### ISSUE TITLE
How can Support RTL?

### ISSUE THREAD

**Issue by anastely** [FaridSafi/react-native-gifted-chat#1900]
#### Issue Description
I have a fully RTL app, 
And I want to use this library,
but I have any issue with bubble And send button positions

![Screen Shot 2020-08-18 at 7 06 39 PM](https://user-images.githubusercontent.com/24620979/90537427-fc6b1e80-e185-11ea-8121-0a17ff38ec94.png)

#### Additional Information

* Nodejs version: [v14.5.0]
* React version: [16.13.1]
* React Native version: [0.63.0]
* react-native-gifted-chat version: [0.16.3]
* Platform(s) (iOS, Android, or both?): [both]

**Comment by mohammadrahmanian** [comment]
I have the same issue. Have you found any solution?

**Comment by AMoktar** [comment]
I hope rtl suppport is available
