### ISSUE TITLE
Message is sent only after pressing twice on the "Send" button

### ISSUE THREAD

**Issue by nabylb** [FaridSafi/react-native-gifted-chat#1905]
#### Issue Description

When the keyboard is displayed and the send button is pressed, the keyboard is dismissed but nothing is sent. The message is sent after pressing a second time on the button.

#### Steps to Reproduce / Code Snippets

```javascript
const QvInputToolBar = (props: any) => {
  const styles = useDynamicStyleSheet(dynamicStyles);

  return <InputToolbar {...props} containerStyle={styles.textInputContainer} />;
};

 <GiftedChat
   ...
   renderInputToolbar={props =>
      <QvInputToolBar {...props} />
   }
   ...
 />
...
```
#### Expected Results

Message is sent after pressing "Send" the first time.

#### Additional Information

* Nodejs version: 10.16.2
* React version:  16.13.1 
* React Native version: 0.62.2 
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: 4.0.2

**Comment by erFra17** [comment]
Hi there, I am having this same issue, I'm quite surprise not many people are having it as well..

I just got the basic working version following the example, and when pressing 'send' it actually only dismisses the keyboard, once the keyboard is hidden, then the 'send' button works.

Any insight on how to fix this behaviour?

**Comment by nabylb** [comment]
I never got this fixed. We just accepted the behavior as it wasn't too disruptive to users.

**Comment by erFra17** [comment]
Ok, thanks for your reply!

**Comment by omidbarcelona** [comment]
Set <ScrollView keyboardShouldPersistTaps='always'>
Read this link for more info
https://medium.com/react-native-training/todays-react-native-tip-keyboard-issues-in-scrollview-8cfbeb92995b
