### ISSUE TITLE
When opening chat auto-scrolling to bottom doesn't reach last message

### ISSUE THREAD

**Issue by sachinkaria** [FaridSafi/react-native-gifted-chat#1906]
#### Issue Description

When I open a conversation and there are messages, the auto scroll to the bottom of the chat doesn't always reach the last message. For example if there are 25 messages in the chat, the scrolling will scroll to message number 19. If there are 42 messages in the chat, the scrolling only reaches message 39. I've noticed the pattern where the scrolling reaches the last index of the previous 10th. e.g 19/25, 29/38, 39/42 etc. 

In my case most recent messages are shown at the bottom of the chat and older messages at the top. I expect the chat to scroll to the most recent message all the way down.

#### Steps to Reproduce / Code Snippets

Implemented GiftedChat according to the docs.

```
<GiftedChat
      alignTop
      inverted={false}
      messages={props.messages}
      onSend={messages => onSend(messages)}
      user={{_id: user.uid, name: user.firstName, avatar: user.displayPicture}}
      showUserAvatar
      renderBubble={(message) => renderMessageBubble(message)}
      shouldUpdateMessage={(message) => renderMessageBubble(message)}
      isAnimated
      audio={true}
      minComposerHeight={46}
      renderInputToolbar={renderChatInput}
    />
```

#### Expected Results

Chat should always scroll to the bottom of the messages with the last message rendering at the bottom.

#### Additional Information

* React Native version: 0.62.2
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by denny351** [comment]
You're missing the "scrollToBottom" prop in your "Steps to Reproduce / Code Snippets". But I have the same issue here

**Comment by vasuchawla** [comment]
Same issue. Can confirm this happens in android

**Comment by darron1217** [comment]
GiftedChat renders content twice, and on second render this bug appears. (on Android)

**Comment by ethanyuwang** [comment]
having the same problem on iOS

**Comment by sachinkaria** [comment]
This issue still isn't resolved, did anyone manage to fix?

**Comment by SNEAndy** [comment]
I also encountered this problem,it seems like you should change the inverted={false} to inverted={true} to make it work

**Comment by mariomurrent-softwaresolutions** [comment]
> 

Well thats not a good solution, since it changes the message display behaviour

**Comment by leonardo-weber** [comment]
any solutions?

**Comment by jessicazu** [comment]
I resolved this issue using the following simple method:

```jsx
<GiftedChat
  messages={messages.slice().reverse()}
  inverted={true}
  ...
/>
```

I referred to this:
https://stackoverflow.com/questions/48477500/react-native-flatlist-initial-scroll-to-bottom

(Although using reverse might raise concerns regarding performance, I didn't encounter any issues even when rendering up to 3,000 items.)
