### ISSUE TITLE
Rendering issue on OnePlus device

### ISSUE THREAD

**Issue by TommyLeong** [FaridSafi/react-native-gifted-chat#1908]
#### Issue Description
OnePlus device always give issue in rendering text if the text is **BOLD**. Most of the time, we provide extra width to to render the full text. Here in the image you may spot 2 rendering issues

1. Ausg 23,   **_Suppose to be Aug 23, 2020_**
2. Sen   **_Suppose to be Send_**

#### Steps to Reproduce / Code Snippets

1. Deploy a sample app with OnePlus device (I've tested with actual OnePlus 5T device)
2. Simply create a chatroom
3. Click on the text input (where you send text).. type something to render the word "Send"
![image](https://user-images.githubusercontent.com/9990179/90980797-25c5e900-e590-11ea-9bcb-63a7f3914c91.png)

#### Expected Results

Should have the entire text properly displayed.

#### Additional Information

Actual Device: OnePlus 5T (Android OS 9)
React Native version: 0.62.2 => 0.62.2
react-native-gifted-chat version: ^0.16.2"
Platform(s) (iOS, Android, or both?): Android

```
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 293.33 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_221 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by vaibhavhrt** [comment]
Adding one blank space after text should solve this, eg instead of `Send` use `Send `.
Using any custom font should solve this too, there is issue with the fonts One Plus provides by default.
