### ISSUE TITLE
how to use two property in different screens?

### ISSUE THREAD

**Issue by devekoperiOS** [FaridSafi/react-native-gifted-chat#191]
I am using tab bar in my application and I am also using messaging module. If I set windowSoftInputMode to adjustResize, then it pushes my tab bar along with messages. If I set windowSoftInputMode to adjustPan, then it keep a large gap between my text field and keyboard. Please let me know how to solve this issue.

**Comment by FaridSafi** [comment]
Maybe bottomOffset prop can solve your issue?

**Comment by devekoperiOS** [comment]
Thank you for quick response. I tried that one. It works. But I have only one instance of emulator which is nexus. I need to set this base on different height of different devices. Do you have any idea will that work?

**Comment by FaridSafi** [comment]
Then you need to find a way to retrieve the height of your tab bar component

**Comment by devekoperiOS** [comment]
Yes that right. Thank you for solution.

**Comment by radelcom** [comment]
@devekoperiOS would you mind sharing your solution? I am in the same situation right now. Which bottomOffset prop did you change?

**Comment by devekoperiOS** [comment]
I have used react-native-gifted-chat.

Following is my code.
import { GiftedChat, Actions, Bubble } from 'react-native-gifted-chat';

 <GiftedChat
          messages={this.state.messages}
          onSend={this.onSend}
          loadEarlier={this.state.loadEarlier}
          onLoadEarlier={this.onLoadEarlier}

          user={{
            _id: 1, // sent messages should have same user._id
          }}

          renderActions={this.renderCustomActions}
          renderBubble={this.renderBubble}
          renderCustomView={this.renderCustomView}
          renderFooter={this.renderFooter}
          bottomOffset={290}
/>
