### ISSUE TITLE
Allow multiple images to show in a bubble

### ISSUE THREAD

**Issue by Buwaneka-Sumanasekara** [FaridSafi/react-native-gifted-chat#1913]
#### Issue Description

I need to show multiple images in the bubble 

#### Additional Information

* Nodejs version: 14.6.0
* React version:16.9.0
* React Native version: 0.61.5
* react-native-gifted-chat version:0.16.3
* Platform(s) (iOS, Android, or both?): both

**Comment by Hook-Da** [comment]
Any news?

**Comment by luatnd** [comment]
Image sometimes displayed!! I found this issue on iPhone 12 Pro simulator
