### ISSUE TITLE
Unexpected token error with React Native Web

### ISSUE THREAD

**Issue by deepankar1994** [FaridSafi/react-native-gifted-chat#1915]
#### Issue Description

```
node_modules/react-native-gifted-chat/lib/GiftedChat.js: Unexpected token (337:26)

  335 |     renderMessages() {
  336 |         const { messagesContainerStyle, ...messagesContainerProps } = this.props;
> 337 |         const fragment = (<View style={[
      |                           ^
  338 |             {
  339 |                 height: this.state.messagesContainerHeight,
  340 |             },
```

#### Steps to Reproduce / Code Snippets
Trying to run on Web with React Native Web. 
Have added `config-overrides.js` as given in the instructions. 
```
import { GiftedChat } from "react-native-gifted-chat";

function ChatUI() {
  const [messages, setMessages] = useState([]);

  useEffect(() => {
    setMessages([
      {
        _id: 1,
        text: "Hello developer",
        createdAt: new Date(),
        user: {
          _id: 2,
          name: "React Native",
          avatar: "https://placeimg.com/140/140/any",
        },
      },
    ]);
  }, []);

  const onSend = useCallback((messages = []) => {
    setMessages((previousMessages) =>
      GiftedChat.append(previousMessages, messages)
    );
  }, []);

  return (
    <GiftedChat
      messages={messages}
      onSend={(messages) => onSend(messages)}
      user={{
        _id: 1,
      }}
    />
  );
}
```

#### Additional Information
   
 "react": "^16.13.1",
   "react-dom": "^16.13.1",
    "react-native": "^0.63.2",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-web": "^0.13.9",
* Platform(s) (iOS, Android, or both?): Web
* TypeScript version: Using JS

**Comment by Raphaelinyang** [comment]
I'm having the same problem

and the react-web-gifted-chat by @johniak isn't working for me

**Comment by hanayashiki** [comment]
same problem for me

**Comment by okwast** [comment]
I keep running into the same issue.
Was able to make it work in the end, but that broke a few other things with our app.

I'm not perfectly sure why this needs so much additional setup to work beyond the react-native-web setup.
Has anyone found out why it is necessary in the first place?
