### ISSUE TITLE
Message object undefined when using onLongPress within lightboxProps

### ISSUE THREAD

**Issue by leelandclay** [FaridSafi/react-native-gifted-chat#1917]
#### Issue Description

When I attempt to setup the onLongPress event for MessageImage objects, the method is called however the message object is undefined.

#### Steps to Reproduce / Code Snippets

Add
```
lightboxProps={{ onLongPress: (context: any, message: any) => this.handleLongPress(context, message) }}
```
to the GiftedChat component. Then create the handleLongPress method. Within the method, observe the message object and it will be undefined.

#### Expected Results

The message object should contain information about the message that was long pressed, same as when using the onLongPress prop of the GiftedChat component.

#### Additional Information

* React version: 16.13.1
* React Native version: 0.63.2
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: 4.0.2

**Comment by obendevski** [comment]
Hey @leelandclay, did you have any luck with this? I encountered the same.

**Comment by leelandclay** [comment]
@obendevski I discovered that it's an issue with the lightbox that is used within react-native-gifted-chat. Sadly, the lightbox package that is being used is no longer maintained so it probably won't be fixed.
Until I get a chance to roll my own lightbox, I'm just telling people to long press on the name/time section below the picture. Not a great workaround, but all I was using long press for on images was to add reacts :/. There's also other issues with the lightbox that need to be fixed as well like the useNativeDriver flag that isn't being set.
