### ISSUE TITLE
Swipe down to close keyboard

### ISSUE THREAD

**Issue by Aryk** [FaridSafi/react-native-gifted-chat#1919]
Is there a way to make the keyboard slide down in response to a user gesture on the chat window? This is the behavior on many apps like Instagram for example.

Just curious if it was possible to do it at all with this library or if someone else has done it.

* react-native-gifted-chat version: 0.16.1

**Comment by kamarmack** [comment]
listViewProps={{
                    keyboardDismissMode: "on-drag"
                }}

**Comment by Aryk** [comment]
Not quite, I meant more like this https://github.com/APSL/react-native-keyboard-aware-scroll-view.

Anyways for us to use an HOC with the FlatList in GiftedChat? I didn't see an interface to it...there is no way to swap the FlatList component AFAIK.

Is there anyway to do that with this library?

**Comment by Aryk** [comment]
The on-drag is not keyboard aware. The second it senses the drag it completely closes instead of being in sync with the swipe action like you find on different social media apps.

**Comment by quiringk** [comment]
The ability to add react-native-keyboard-aware-scroll-view would be a great addition!

**Comment by rnz269** [comment]
@Aryk did you figure out a way to make this work? Otherwise, I may give it a shot.

**Comment by hotaryuzaki** [comment]
> listViewProps={{ keyboardDismissMode: "on-drag" }}

not works, i try in android

**Comment by sirusbaladi** [comment]
any update?

**Comment by sirusbaladi** [comment]
I figure out how to do this. 

You need to change the MessageContainer.js in node_modules in react-native-gifted-chat add as prop of the Flatlist the following: keyboardDismissMode={'interactive'}. 


I recommend then to create a patch file.

**Comment by nodir-js** [comment]
This worked for me:
```jsx
listViewProps={{
  keyboardShouldPersistTaps: 'handled',
  keyboardDismissMode: Platform.OS === 'ios' ? 'interactive' : 'on-drag',
}}
```
