### ISSUE TITLE
Animated.event now requires a second argument for options

### ISSUE THREAD

**Issue by Gapur** [FaridSafi/react-native-gifted-chat#1924]
#### Issue Description

When We need to display a message with an image, the app shows a warning about the issue.

`Animated.event now requires a second argument for options`

I guess, `react-native-gifted-chat` uses  this `react-native-lightbox` lib. Now UseNativeDriver is a required prop for Animated
Unfortunately, the original library seems to be out of maintenance.

#### Steps to Reproduce / Code Snippets

![Simulator Screen Shot - iPhone 11 - 2020-09-22 at 16 11 58](https://user-images.githubusercontent.com/10502684/93870706-6e87d380-fcef-11ea-8f86-75f47988693d.png)

#### Additional Information

* Nodejs version: v13.5.0
* React version: 16.13.1
* React Native version: 0.63.2
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): Both
* TypeScript version: 3.8.3

**Comment by AbhiShrek** [comment]
I am also getting this warning. It is safe to ignore it ?

**Comment by hasansna** [comment]
same

**Comment by H4ck3r-x0** [comment]
Anyone fixed this?

**Comment by Gapur** [comment]
hi guys and @FaridSafi, I guess,  the original library seems to be out of maintenance so it will be great, if the react-native-gifted-chat team fork and modify react-native-lightbox with animated: { useNativeDriver: false }.  I just ignore the warning.

**Comment by H4ck3r-x0** [comment]
Hi guys and @FaridSafi, i worked this around. I implemented my own component, i used this package
``` react-native-image-modal```

and the component look like this.

```
 const renderMessageImage = (props) => {
    return (
      <View
        style={{
          borderRadius: 15,
          padding: 2,
        }}
      >
        <ImageModal
          resizeMode="contain"
          style={{
            width: 200,
            height: 200,
            padding: 6,
            borderRadius: 15,
            resizeMode: "cover",
          }}
          source={{ uri: props.currentMessage.image }}
        />
      </View>
    );
  };
```

hope this would be helpfual.

**Comment by Gapur** [comment]
> Hi guys and @FaridSafi, i worked this around. I implemented my own component, i used this package
> ` react-native-image-modal`
> 
> and the component look like this.
> 
> ```
>  const renderMessageImage = (props) => {
>     return (
>       <View
>         style={{
>           borderRadius: 15,
>           padding: 2,
>         }}
>       >
>         <ImageModal
>           resizeMode="contain"
>           style={{
>             width: 200,
>             height: 200,
>             padding: 6,
>             borderRadius: 15,
>             resizeMode: "cover",
>           }}
>           source={{ uri: props.currentMessage.image }}
>         />
>       </View>
>     );
>   };
> ```
> 
> hope this would be helpful.

**Comment by hungvu193** [comment]
I use patch-pakage to resolve the problem:
https://github.com/FaridSafi/react-native-gifted-chat/issues/1825#issuecomment-718463680

**Comment by AMoktar** [comment]
same issue

**Comment by AMoktar** [comment]
@H4ck3r-x0 plase can you provice more info plz, about the new component and how to use it

**Comment by irzan2010** [comment]
> 
> 
> Hi guys and @FaridSafi, i worked this around. I implemented my own component, i used this package
> ` react-native-image-modal`
> 
> and the component look like this.
> 
> ```
>  const renderMessageImage = (props) => {
>     return (
>       <View
>         style={{
>           borderRadius: 15,
>           padding: 2,
>         }}
>       >
>         <ImageModal
>           resizeMode="contain"
>           style={{
>             width: 200,
>             height: 200,
>             padding: 6,
>             borderRadius: 15,
>             resizeMode: "cover",
>           }}
>           source={{ uri: props.currentMessage.image }}
>         />
>       </View>
>     );
>   };
> ```
> 
> hope this would be helpful.

Hi, thanks. This is work for me.

**Comment by edwinckc** [comment]
> Hi guys and @FaridSafi, i worked this around. I implemented my own component, i used this package
> ` react-native-image-modal`
> 
> and the component look like this.
> 
> ```
>  const renderMessageImage = (props) => {
>     return (
>       <View
>         style={{
>           borderRadius: 15,
>           padding: 2,
>         }}
>       >
>         <ImageModal
>           resizeMode="contain"
>           style={{
>             width: 200,
>             height: 200,
>             padding: 6,
>             borderRadius: 15,
>             resizeMode: "cover",
>           }}
>           source={{ uri: props.currentMessage.image }}
>         />
>       </View>
>     );
>   };
> ```
> 
> hope this would be helpful.

Thanks for this! The latest version of `react-native-image-modal` does not work with Expo managed flow, and the recommended (deprecated) version that does work with Expo crashes in Android (malformed calls).

I used `ImageView` from [react-native-image-modal](https://github.com/jobtoday/react-native-image-viewing) instead.

```
return (
    <View>
        <TouchableOpacity onPress={showImageModal}>
             <Image source={'your-image-uri'}/>
             <ImageView images={[{uri: 'your-image-uri'}]} onRequestClose={hideImageModal} />
        </TouchableOpacity>
    </View>
)
```

**Comment by qadir007** [comment]
Hey guys
to solve this issue you just need to replace 
react-native-lightbox with react-native-lightbox-v2
in the MessageImage.js file in node_modules/ react-native-gifted-chat /lib/MessageImage.js 
file
Note first install react-native-lightbox-v2

**Comment by jaureguio** [comment]
> Hey guys
> to solve this issue you just need to replace
> react-native-lightbox with react-native-lightbox-v2
> in the MessageImage.js file in node_modules/ react-native-gifted-chat /lib/MessageImage.js
> file
> Note first install react-native-lightbox-v2

Worked for me, no more warning shown. You should make a pull request with those changes made.

**Comment by niallotuathail** [comment]
Works for me too. Definitely worth a pull request.

**Comment by nganbph10804** [comment]
> Hey guys to solve this issue you just need to replace react-native-lightbox with react-native-lightbox-v2 in the MessageImage.js file in node_modules/ react-native-gifted-chat /lib/MessageImage.js file Note first install react-native-lightbox-v2

its work for me. thanks bro

**Comment by ombogdan** [comment]
same

**Comment by shoaibbadshah** [comment]
WARN  Animated.event now requires a second argument for options
   <Box flex={1} backgroundColor={'black'}>
                <CustomCrop
                  updateImage={updateImage}
                  // rectangleCoordinates={initialImage.rectangleCoordinates}
                  initialImage={initialImage.croppedImage}
                  height={height_screen * 0.842}
                  width={width_screen}
                  ref={customCrop}
                  overlayColor="rgba(18,190,210, 1)"
                  overlayStrokeColor="rgba(20,190,210, 1)"
                  handlerColor="rgba(20,150,160, 1)"
                  enablePanStrict={true}
                />
              </Box>
