### ISSUE TITLE
How to add loader while upload image? 

### ISSUE THREAD

**Issue by nbvora** [FaridSafi/react-native-gifted-chat#1927]
#### Issue Description

While sending image in chat, I want to show image uploading along with Progress status. Is there any inbuilt mechanism available to achieve this?

#### Steps to Reproduce / Code Snippets

Send any image to other user

#### Expected Results

Sender can't see image sending progress, so there should be a thumbnail of image with loader. Once image upload complete loader should stop and image should display. It should also work for multiple images upload.

#### Additional Information

* Nodejs version: 10.17.0
* React version:  16.13.1
* React Native version: 0.63.2
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: N/A

**Comment by walidvb** [comment]
What about displaying the local image instead of the remote one, until it is sent? Would that not be a better option?

**Comment by nbvora** [comment]
How to achieve that local image display because i have no idea on it

It you have idea then let me know

**Comment by hungvu193** [comment]
The idea 's when your image 's uploading, you will create a local message with image in your message id is your local image and status pending. 
After your image uploaded, you update that message with the url from response.

**Comment by xkungfu** [comment]
what are you talking about?
how to upload an image?
why I didn't find the feature, and not find any  button about send image.

please tell me how you set up a send image button, thanks!

**Comment by kenkotch** [comment]
you can use `renderAccessory` or `renderActions` to add the button

**Comment by Shivam-Pathak1** [comment]
Hi @xkungfu, Could you solve this problem?
