### ISSUE TITLE
Android composer not rezise after send multiline message

### ISSUE THREAD

**Issue by WilsonPrado** [FaridSafi/react-native-gifted-chat#1929]
#### Issue Description

After sending a multiline message the composer remains in the multiline size, this only resizes to normal size after inserting a key inside.

Writing a multiline message:
![image](https://user-images.githubusercontent.com/39269397/94168145-b596d580-fe63-11ea-9276-66c384c7cccf.png)

After send:
![image](https://user-images.githubusercontent.com/39269397/94168261-d3fcd100-fe63-11ea-8b5c-db76d40072a0.png)

#### Steps to Reproduce / Code Snippets

Write a multiline text inside de composer.

Here is my Composer code:

```
import React, { memo } from 'react'
import { Composer } from 'react-native-gifted-chat'
import { withTheme } from 'styled-components'
import { Platform } from 'react-native'

const RenderComposer = ({ props, theme: { color, chat: { screen: { textInputStyle } } } }) => (
  <Composer
    {...props}
    textInputStyle={{
      fontSize: textInputStyle.fontSize,
      color: textInputStyle.color,
      backgroundColor: color.white,
      borderRadius: textInputStyle.borderRadius,
      width: textInputStyle.width,
      height: textInputStyle.height,
      borderColor: color.neutral300,
      paddingTop: textInputStyle.paddingTop,
      paddingHorizontal: textInputStyle.paddingHorizontal,
      marginRight: textInputStyle.marginRight,
      shadowColor: color.shadowColor,
      shadowOffset: {
        width: textInputStyle.shadowOffset.width,
        height: textInputStyle.shadowOffset.height
      },
      shadowOpacity: textInputStyle.shadowOpacity,
      shadowRadius: textInputStyle.shadowRadius,
      elevation: textInputStyle.elevation,
      marginBottom: Platform.OS === 'ios' ? 4 : 0
    }}
  />
)
export default withTheme(memo(RenderComposer))
```

#### Expected Results

After send the message, the composer returns to the normal size.

#### Additional Information

* Nodejs version: 12.13.0
* React version: 16.9.0
* React Native version: 0.61.5
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): Android

**Comment by henriquecorraro** [comment]
Same here :/

**Comment by WilsonPrado** [comment]
Up

**Comment by shashi-kiwi** [comment]
Any update on this
