### ISSUE TITLE
iOS 14 - input toolbar moving up on click send

### ISSUE THREAD

**Issue by seeocon** [FaridSafi/react-native-gifted-chat#1930]
#### Issue Description

After updating to iOS 14, for some reason the keyboardavoidingview handler seems to be malfunctioning. When I press send the toolbar is misplaced roughly by ~20 px, if I dismiss the keyboard and click on the input again, it goes back into place. This seems to only happen when I click send for some reason. 

I have also noticed that if I set the 'isKeyboardInternallyHandled' prop to false, then I don't get this problem. However, the keyboard is internally handled, so I can't do that.

![Screen Shot 2020-09-24 at 5 37 22 PM](https://user-images.githubusercontent.com/9501899/94203203-f9520500-fe8c-11ea-9439-1b8e2968e451.png)

#### Steps to Reproduce / Code Snippets

I tested this with any example, and it seems to be happening, so code snippets won't be of much help.

#### Expected Results

The inputToolbar shouldn't be moving up when I press send.

#### Additional Information

* Nodejs version: 12.16.1
* React version: 16.13.1
* React Native version: 0.63.2
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): iOS 14
* TypeScript version: 4.0

**Comment by lsps9150414** [comment]
having the same issue and for me, the extra space appears & disappears on typing:
![image](https://user-images.githubusercontent.com/5022617/94275393-7c508980-ff79-11ea-8043-1160530ad847.png)

**Comment by JLucasCAmorim** [comment]
Any solution to this?

**Comment by JLucasCAmorim** [comment]
Never mind, I was able to sort this out.

**Comment by timvandijck** [comment]
@JLucasCAmorim Could you please share your solution?

**Comment by art1373** [comment]
may I know how? I have the same problem

**Comment by JLucasCAmorim** [comment]
@timvandijck @art1373 you need to set the isKeyboardInternallyHandled as false, and then you can put a KeyBoardAvoidView as the father of GiftedChat. Something like that:
```
<KeyBoardView>
        <GiftedChat
          messages={messages}
          onSend={handleSend}
          alwaysShowSend
          wrapInSafeArea
         ../>
      </KeyBoardView>
```

**Comment by seeocon** [comment]
> @timvandijck @art1373 you need to set the isKeyboardInternallyHandled as false, and then you can put a KeyBoardAvoidView as the father of GiftedChat. Something like that:
> 
> ```
> <KeyBoardView>
>         <GiftedChat
>           messages={messages}
>           onSend={handleSend}
>           alwaysShowSend
>           wrapInSafeArea
>           isKeyboardInternallyHandled={false}
>          ../>
> </KeyBoardView>
> ```

Can confirm. This is exactly what I ended up doing.

**Comment by art1373** [comment]
my Version 

```
        <KeyboardAvoidingView
          behavior={isIos ? "padding" : undefined}
          style={{ flex: 1 }}
        >
          <GiftedChat
            // alignTop
            isKeyboardInternallyHandled={false}
            alwaysShowSend
            infiniteScroll
            messages={messages}
            renderBubble={(props) => <ChatBubble {...props} theme={theme} />}
            renderAvatar={() => null}
            placeholder="Messeage..."
            renderActions={(props) => <ButtonAttach {...props} />}
            renderSend={renderSend}
            renderInputToolbar={renderInputToolbar}
            textInputStyle={[
              styles.chatInput,
              {
                backgroundColor: darkTheme ? Colors.primaryDark : Colors.white,
              },
            ]}
            messagesContainerStyle={{
              backgroundColor: darkTheme ? Colors.primary : Colors.white,
            }}
            onSend={(messages) => onSend(messages)}
            user={{
              _id: 1,
            }}
          />
        </KeyboardAvoidingView>

```

**Comment by manilabui** [comment]
@lsps9150414 did you ever get that fixed? i'm having the exact same issue. keyboardavoidingview didn't work for me for this case.

**Comment by hungvu193** [comment]
This worked for me: (xcode 12, ios 14.1)
```javascript
<KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
        style={[styles.body, { backgroundColor: 'white' }]}>
        <GiftedChat
          isTyping
          alwaysShowSend
          lightboxProps={{ useNativeDriver: true }}
          onLoadEarlier={onLoadEarlierMessages}
          isLoadingEarlier={isLoadingEarlier}
          loadEarlier={messages.length >= 15 && messagePage <= messageLastPage}
          infiniteScroll
          messages={messages}
          onSend={currentMessage => onSend(currentMessage)}
          user={{
            _id: userId,
          }}
          isCustomViewBottom
          renderActions={renderActions}
          renderComposer={renderComposer}
          renderInputToolbar={renderInputToolbar}
          renderSend={renderSend}
          isKeyboardInternallyHandled={false}
        />
 </KeyboardAvoidingView>
```

**Comment by Joshandrews43** [comment]
I am getting this issue on a physical phone as well

**Comment by mcousillas6** [comment]
Just fixed this by adding `bottomOffset` using react-native-safe-area-context:

```jsx
const insets = useSafeAreaInsets();

<GiftedChat
// all your code
bottomOffset={insets.bottom}
/>
```

**Comment by rajendersha** [comment]
Not working

**Comment by AngelTrinidad** [comment]
For me, using useSafeAreaInsets its a better way to fix this, with KeyboardAvoidingView you will lose the smooth animation on Chat when keyboard showed

**Comment by fukemy** [comment]
no solution working for me, sadly
