### ISSUE TITLE
Header gets pushed up on Android when keyboard first appears

### ISSUE THREAD

**Issue by ethanyuwang** [FaridSafi/react-native-gifted-chat#1931]
#### Issue Description

I'm using [react-native-keyboard-aware-scroll-view](https://github.com/APSL/react-native-keyboard-aware-scroll-view) so have to set `windowSoftInputMode` to `adjustPan`. So I adopted the method of using KeyboardAvoidingView as described in the readme. Here is my code for the screen:

```
      <View style={styles.container}>
        <Header
          title={selectedConversation.conversation_name}
          onGoBack={this.onGoBack}
        />
        <GiftedChat
          messages={this.getMappedMessages()}
          onSend={this.onSend}
          user={this.getUser()}
          inverted={false}
          loadEarlier={!isFetchCompleted(conversationsFetchState)}
          isLoadingEarlier={!isFetchCompleted(conversationsFetchState)}
          renderLoadEarlier={() => (
            <View style={styles.activityIndicatorContainer}>
              <ActivityIndicator size="large" color={colors.gray} />
            </View>
          )}
        />
        {Platform.OS === 'android' && (
          <KeyboardAvoidingView behavior="padding" />
        )}
      </View>

```
However, the header gets pushed up when the keyboard first appears, but as soon as I type it displays normally again. 

Here is a screen recording: 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/17556945/94319675-0f6ccd80-ff40-11ea-9cef-591d182f98d5.gif)

How can I fix this?

**Comment by Duya3fithou** [comment]
Same me

**Comment by JuulCrooymans** [comment]
For people that are using expo. I fixed it by changing `"softwareKeyboardLayoutMode": "pan"` to `"softwareKeyboardLayoutMode": "resize"` in app.json

**Comment by mehimanshupatil** [comment]
Has any one found fix for this

**Comment by jackywxd** [comment]
@mehimanshupatil 
I found a workaround for this issue using KeyboardSpacer to detect the state of keyboard, and whenever the state of keyboard change, setState to force a render. The input bar still will be pushed up then dropped to the normal position quickly.

It is not perfect but that's all I got so far. 

```
{Platform.OS === 'android' && (
          <View>
            <KeyboardSpacer
              onToggle={(state, space) => {
                if (state) {
                  setHeight(Math.floor(space))
                } else {
                  setHeight(0)
                }
              }}
            />
          </View>
        ) }
```

**Comment by rohank45** [comment]
I'm having the same issue does anyone have any idea how to solve this?

**Comment by novirusallowed** [comment]
Still having the problem and still can't find a solution

**Comment by me-ibad** [comment]
anyone fix it? in expo

**Comment by Anyamborogass** [comment]
Anyone found a solution?
