### ISSUE TITLE
Customising Message' containerStyle property leads to Day throwing an error

### ISSUE THREAD

**Issue by ckuijjer** [FaridSafi/react-native-gifted-chat#194]
Giving the _Message_ component a custom _containerStyle_ property leads to _Day_ throwing an error.

    renderMessage = (props) => {
        const containerStyle = {
            left: {
                marginLeft: 0,
            },
        };

        return <Message { ...props} containerStyle={containerStyle} />;
    }

This error occurs as properties as passed to the children components in Gifted Chat, and both _Message_ and _Day_ use the containerStyle property. _Day_ uses containerStyle as an object of css properties, whereas _Message_ adds an additional level in order to have distinct styling for its _left_ and _right_ positioning. This leads to _Day_ having an invalid style property. See below:

![screen shot 2016-08-15 at 10 36 17](https://cloud.githubusercontent.com/assets/36165/17659801/3fb1878a-62d5-11e6-8e9a-2b6a13bc18d1.png)

![screen shot 2016-08-15 at 10 37 00](https://cloud.githubusercontent.com/assets/36165/17659803/451ae3a6-62d5-11e6-8aff-ddc43b520a0b.png)

As a workaround I have added a customer _renderDay_ function that simply passes all properties except for the containerStyle property to the _Day_ component

    renderDay = ({ containerStyle, ...props }) => {
        return <Day {...props} />;
    }

This doesn't feel like a proper solution. However, I'm also not sure how this can be properly solved by Gifted Chat. For example should it not pass properties to children, should a component without distinctive left/right positioning, like _Day_, exclude those props from their styling properties?

**Comment by kfiroo** [comment]
I think `Message` should not pass `containerStyle` to its children.
It is the style for the container of the Message not Day or anything else.

If the user want to override the Day container styles he should pass `renderDay` and set its own `containerStyle`

**Comment by ckuijjer** [comment]
That's also my initial feeling, a component should not pass any styling related property to it's children. This will however be a breaking change.

**Comment by ckuijjer** [comment]
@FaridSafi You're awesome! Thanks
