### ISSUE TITLE
Full Screen preview of images do not cover the whole screen when running as web.

### ISSUE THREAD

**Issue by apappas1129** [FaridSafi/react-native-gifted-chat#1940]
#### Issue Description
When running an application as a web app. The full-screen preview of image is anchored at the bottom-left corner of it's corresponding message bubble.

![preview](https://lh3.googleusercontent.com/fife/ABSRlIpeUAWdvW4GOlcbChgETLZlvSnrrL0FvV4qZbWp_veAZHOZ2SaH5Xt3HBBIPhgk7D0TFcgMqqYMXJFE8iP0aY9jmFlzzTMneTwEU7mGC8bI4VGuJ6Y6rqtd0lz078QJGXwTaOA10ACQcZOJrXa0D8VpUV8-1o_fYZp-fTdlICSyZJFSDSb44gLOj5pcmLjX_YznlwS3axRsner9npkEn6H9dafBN-cgjp1FJlpNA0xSDOklhmdPomhfDDqRMNOybpvTpD_hMGkN4kR2R9SDsce5dv1QQHonrnPKs27NaNkAZuq6ZhTOEa6du_ZxmWdKt0q6ffbkUmnVel6mmPucgktvIpXQOYKoH92QpR3pq_99kxbFMVvORFKLAf6IpvYdpgghWZ_zKRxOUChAKNdmsxC0SRRneOXWdeFxO_7O0Ho5xZ_6d2_fALOgjQrRcJyAj9xObeqGu6N2K2-sVp3y3TGgEwnKx7h26r3t2W4yvlm_GE4GiN9WfS5W3NyvGx1eoi5A4MBCkGLDqYg6ICNKyuDnL4apVD9mIG8IWD7Pw1CPQPOcFeD6F4gzX0X74eaX62-7MmyafyoBqQxybtqG1jIv6lZJfi5AQ5LaYK-Y297iSXxkvACNtlLQiwlGZ_HNsa6Ey7pDtlYo_Gb1rd8EFOBplR_UEjwpHbMPxYJIF20iMJZtdYjEgCgi2JSbUZPNoX_CWyzVDkddM4nkDd63RdCgpuBtYdE4rLM=w1920-h902-ft)

#### Steps to Reproduce / Code Snippets
* Create a react native project using Expo
* Integrate react-native-gifted-chat and some dummy data to display messages with photos.
* Run your project as web
* Tap the message bubble with an image and observe the behavior

#### Expected Results

The full-screen image preview should cover the whole screen when running as web.

#### Additional Information

"react-native": "https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz",
"react-native-gifted-chat": "^0.16.3",

**Comment by walidvb** [comment]
I think this is due to using `scale` around gifted chat, which in turn creates rendering contexts, preventing `position: fixed` from exiting that context. I've had several issues with this approach already.. I would say your best bet is to use a `<Portal />`.. 
I will need to implement this in a short time, will try to update with my solution here!
