### ISSUE TITLE
Attachment Option in Gifted Chat

### ISSUE THREAD

**Issue by Palwisha77** [FaridSafi/react-native-gifted-chat#1942]
Hi, I want to add an attachment option in my chat app. I am using the Gifted Chat package which only give option for video and audio. How can I add an option for attachments?. Is there anyone who can help me with this? 

****Expected** Results*

![wt](https://user-images.githubusercontent.com/25461981/96078432-ba333480-0ecb-11eb-97d9-091e22409b4f.png)

**Additional Information**

* Nodejs version: 10.15.3
* React version: 16.13.1
* React Native version: 0.63.2
* react-native-gifted-chat version:0.16.3

**Comment by efstathiosntonas** [comment]
I think you need to use systemMessage and render your custom component, something like:

```
renderSystemMessage={(systemMessage) => {
          // @ts-ignore
          const feed: Doc<Feed> = systemMessage.currentMessage.feed;
          if (feed != null) {
            return <FeedInChat feed={feed} time={time} date={date} />;
          }
          return <SystemMessage {...systemMessage} />;
        }}
