### ISSUE TITLE
The entire screen moves up when keyboard opened.

### ISSUE THREAD

**Issue by FreshWebCoder** [FaridSafi/react-native-gifted-chat#1943]
When I tap the input and opens the keyboard, the screen moves up and the header and some messages are hidden due to this behavior.

![image](https://user-images.githubusercontent.com/42607055/96183694-d4bbeb00-0f69-11eb-99a4-22ef22d58f0d.png)
![image](https://user-images.githubusercontent.com/42607055/96183712-dedde980-0f69-11eb-8cc9-b0906baf7126.png)

Code:
```
<View style={{ paddingTop: 5, paddingBottom: 10, flex: 1 }}>
    <GiftedChat
          bottomOffset={10}
          keyboardShouldPersistTaps="never"
          text={sendMessageText}
          onInputTextChanged={setSendMessageText}
          messages={chatMessages}
          renderAvatar={props.isGroup ? undefined : null}
          alwaysShowSend
          onSend={onSend}
          onLongPress={onLongPress}
          renderSend={renderSendAction}
          textInputStyle={styles.textInputStyle}
          listViewProps={{
            showsHorizontalScrollIndicator: false,
            showsVerticalScrollIndicator: false,
            scrollEventThrottle: 400,
            onScroll: ({ nativeEvent }) => {
              if (isCloseToTop(nativeEvent)) {
                loadMore();
              }
            }
          }}
          renderBubble={(prop) =>
            renderBubble({
              ...prop,
              theme,
            })
          }
          renderMessage={renderMessage}
          renderCustomView={renderCustomView}
          renderActions={renderActionPlus}
          renderInputToolbar={renderInputToolbar}
          renderDay={renderDay}
          renderTime={() => {}}
          user={{
            _id: content.chatRoomReducer.authUser._id
          }}
    />
</View>
```

**Comment by NishargShah** [comment]
Change `Pan` to `Resize`

https://stackoverflow.com/questions/17410499/difference-between-adjustresize-and-adjustpan-in-android

**Comment by Duya3fithou** [comment]
> Change `Pan` to `Resize`
> 
> https://stackoverflow.com/questions/17410499/difference-between-adjustresize-and-adjustpan-in-android

another solution?

**Comment by kalpeshchavda9896** [comment]
I think you have to Just add 

listViewProps={{
              style: {
                flexGrow: 1,
              },
            }}

**Comment by lieberscott** [comment]
@Duya3fithou @FreshWebCoder Currently facing this issue on Android (works on iOS). Is there any other solution? I'm using Expo managed so don't have access to the native code files. Have tried adding `<KeyboardAvoidingView/>` below `<GiftedChat/>` but still getting the problem behavior you described.

**Comment by MayankSingh173** [comment]
Is your issue resolved?

**Comment by MayankSingh173** [comment]
@FreshWebCoder Do the following change in AndroidManifest.xml

```
<application>
  <activity
      ...
      android:windowSoftInputMode="adjustResize" >
      ...
  </activity>
</application>
```

**Comment by Darex1991** [comment]
Hi, the same problem with ios. Any ideas? I'm using react-navigation

**Comment by novirusallowed** [comment]
Same problem on Android

**Comment by jesushd103** [comment]
sama problem for me! did someone find a solution?
