### ISSUE TITLE
textStyle right and left color does not work, right textColor overrides left.

### ISSUE THREAD

**Issue by hugoh59** [FaridSafi/react-native-gifted-chat#1948]
```
renderBubble={(props) => {
          return (
            <Bubble
              {...props}
              textStyle={{
                right: {
                  color: Colors.BLUE,
                },
                left: {
                  color: Colors.BLACK,
                },
              }}
```
...

Unable to set a diffirent text color for right and left text bulle.

**Comment by eleviven** [comment]
Just you need reload screen after change colors.

**Comment by hugoh59** [comment]
It does not work i've tried that.

**Comment by eleviven** [comment]
I do like this. Its working
```js
        renderBubble={(props) => (
          <Bubble
            wrapperStyle={{
              right: {
                backgroundColor: variables.green,
              },
              left: {
                backgroundColor: variables.secondary,
              },
            }}
            textStyle={{
              left: {
                color: variables.secondaryDark,
              },
              right: {
                color: variables.textSecondary,
              },
            }}
            {...props}
          />
        )}
```

**Comment by hugoh59** [comment]
That,s exactly what I have, the bgcolor for the wrapper works but I can't get it to work for the messages
`renderBubble={(props) => (
            <Bubble
              textStyle={{
                left: {
                  color: Colors.BLACK,
                },
                right: {
                  color: Colors.BLUE,
                },
              }}
              wrapperStyle={{
                left: {
                  backgroundColor: Colors.GRAY_LIGHT,
                  borderBottomLeftRadius: 0,
                  marginBottom: props.currentMessage._id === messages[0].id ? 30 : 0,
                  padding: 8
                },
                right: {
                  backgroundColor: Colors.BLUE_LIGHT,
                  borderBottomRightRadius: 0,
                  padding: 8,
                  marginBottom: props.currentMessage._id === messages[0].id ? 30 : 0,
                }
              }}
              {...props}
            />
        )}`
