### ISSUE TITLE
Unnecessary padding added to bottom when renderAccessory added

### ISSUE THREAD

**Issue by Buwaneka-Sumanasekara** [FaridSafi/react-native-gifted-chat#1949]
#### Issue Description

When I'm added some render method for `renderAccessory` , additional bottom padding added to the input. thats weird  

#### Steps to Reproduce / Code Snippets

- Added render method to renderAccessory
- comment line (after comment that line input field looks normal)

#### Expected Results

- remove unwanted bottom padding.

#### Additional Information

* Nodejs version: 14.6.0
* React version: 16.9.0.
* React Native version: 0.61.5
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): only on iOS

Here is with `renderAccessory` method
![with_renderAccessory](https://user-images.githubusercontent.com/17542497/97833378-3a92cb80-1cfb-11eb-9935-43f05f850b66.JPG)

Here is without `renderAccessory` method
![without_renderAccessory](https://user-images.githubusercontent.com/17542497/97833430-56966d00-1cfb-11eb-9ca7-9e45b3ce2da8.JPG)

**Comment by MattAgn** [comment]
What are the accessories that you render here? The padding might be to leave room for them

**Comment by fukemy** [comment]
hi, did u solved this? I got same problem

**Comment by Jankaz2** [comment]
HI, any solution for that?
