### ISSUE TITLE
error during launch app

### ISSUE THREAD

**Issue by bionimic** [FaridSafi/react-native-gifted-chat#195]
![error gifted](https://cloud.githubusercontent.com/assets/9911699/17661144/f401c260-630f-11e6-9e53-33373dd614a1.JPG)

I've successfully installed React Native 0.29.0, latest google play services, latest firebase messaging plugins etc2. but after I built the dependencies, install APK, I cant open the app due to this error. please help me. thanks

**Comment by FaridSafi** [comment]
Are you sure this error is related to Gifted Chat import ?

**Comment by kfiroo** [comment]
@bionimic might be related:
[http://stackoverflow.com/a/36021546/220483](http://stackoverflow.com/a/36021546/220483)
[https://github.com/facebook/react-native/issues/6753](https://github.com/facebook/react-native/issues/6753)

Definitely not related to `gifted-chat`.
