### ISSUE TITLE
onLongPress doesnt work on MessageImage

### ISSUE THREAD

**Issue by obendevski** [FaridSafi/react-native-gifted-chat#1950]
#### Issue Description

I have a chat where a user can send images and text. I added the `onLongPress` handler on GiftedChat, it works great for text, but doesnt work for images.

#### Steps to Reproduce / Code Snippets
Add an image in the chat. Hold long on the image, the `onLongPress` wont be called.

#### Expected Results

`onLongPress` handler will be called for `MessageImage` same as it is called for `MessageText`

#### Additional Information

* Nodejs version: 14.11.0
* React version: 16.9.0
* React Native version: 0.61.5
* react-native-gifted-chat version: 0.11.3
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: 3.9.3

**Comment by efstathiosntonas** [comment]
You will have to write your own renderImage component if you want support for images. 

Example: 
```
const renderMessageImage = (pr: any) => {
    const images = [
      {
        url: pr.currentMessage.image
      }
    ];
    return (
      <TouchableOpacity
        onPress={() => pr.imageProps.openImageViewer(images)}
        onLongPress={() => {
          if (pr.user._id === currentUser().uid) {
            actionSheetRef?.current?.setModalVisible(true);
            setSelectedMessage(pr.currentMessage);
            setIsImage(true);
          }
        }}
        style={{ backgroundColor: "transparent" }}
      >
        <FastImage
          style={{
            borderRadius: 14,
            height: 150,
            width: 200,
            marginBottom: -5
          }}
          source={{
            // @ts-ignore
            uri: pr.currentMessage.image,
            priority: FastImage.priority.normal
          }}
          resizeMode={FastImage.resizeMode.cover}
        />
      </TouchableOpacity>
    );
  };
```

**Comment by obendevski** [comment]
Hey @efstathiosntonas , thanks for the reply ! I dont see `openImageViewer` function on `imageProps`. Maybe i'm doing something wrong?

**Comment by efstathiosntonas** [comment]
You can pass `imageProps` like:

```
    imageProps={{ openImageViewer: openModalAndSetImages }}
```

in my case i have a custom image modal viewer (no built in LightBox) `react-native-image-zoom-viewer` :

```
  const openModalAndSetImages = useCallback((images) => {
    setImageUrls(images);
    setImageViewer(true);
  }, []);
```
and outside of `<GiftedChat>...</GiftedChat>` i present the modal:

```
 <ChatImageModal
        showImageViewer={showImageViewer}
        imageUrls={imageUrls}
        setImageUrls={setImageUrls}
        setImageViewer={setImageViewer}
      />
```

**Comment by obendevski** [comment]
@efstathiosntonas Thanks a ton ! U saved me!

**Comment by efstathiosntonas** [comment]
You’re welcome!!

**Comment by efstathiosntonas** [comment]
Hey @obendevski, don't forget to close the issue 😉

**Comment by obendevski** [comment]
You are right. 
Closing as it is fixed by @efstathiosntonas code.
