### ISSUE TITLE
How to send a message by typing 'Enter' on web?

### ISSUE THREAD

**Issue by Insullone** [FaridSafi/react-native-gifted-chat#1951]
#### Issue Description

It is conventional to send a message by typing 'Enter' on web, but it seems not supported. Can we configure it? In addition we can configure multi-line as typing 'Shift + Enter', for example.

#### Steps to Reproduce / Code Snippets
None.

#### Expected Results

Send a message by typing 'Enter' on web.

#### Additional Information

* React version: 16.13.1
* React Native version: sdk 39.0.4
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): Web

**Comment by MattAgn** [comment]
Totally agree, it would be nice to have that feature! I'd be glad to help with the implementation :)

**Comment by beweinreich** [comment]
As a workaround, here's what I did:

```
renderComposer(props) {
    return (
      <Composer
        {...props}
        textInputProps={{
          multiline: true,
          onKeyPress: (event) => {
            if (Platform.OS === "web" && event.keyCode === 13) {
              const message = event.target.value;
              this.onSend([{ text: message }], true);
              const target = event.nativeEvent.target;
              setTimeout(() => target.focus(), 200);
            }
          },
        }}
      />
    );
  }
```

**Comment by xpsdeset** [comment]
> As a workaround, here's what I did:
> 
> ```
> renderComposer(props) {
>     return (
>       <Composer
>         {...props}
>         textInputProps={{
>           multiline: true,
>           onKeyPress: (event) => {
>             if (Platform.OS === "web" && event.keyCode === 13) {
>               const message = event.target.value;
>               this.onSend([{ text: message }], true);
>               const target = event.nativeEvent.target;
>               setTimeout(() => target.focus(), 200);
>             }
>           },
>         }}
>       />
>     );
>   }
> ```

Actually this didn't clear the text had to modify it.


` <Composer
      {...props}
      textInputProps={{
        multiline: true,
        onKeyPress: (event) => {
          if (Platform.OS === "web" && event.keyCode === 13) {
            let message = event.target.value
            props.onSend([{ text: message }], true)
            event.target.value = ""
            const target = event.nativeEvent.target
            setTimeout(() => {
              props.onInputTextChanged("")
              target.focus()
            }, 200)
          }
        },
      }}
    />`
