### ISSUE TITLE
iOS: When opening the keyboard, a warning about animation appears

### ISSUE THREAD

**Issue by nadav2051** [FaridSafi/react-native-gifted-chat#1955]
#### Issue Description

When opening the keyboard by focusing the text input, a iOS warning of

`
[native] Warning: Overriding previous layout animation with new one before the first began:
<RCTLayoutAnimationGroup: 0x600001de6940; creatingLayoutAnimation: (null); updatingLayoutAnimation: <RCTLayoutAnimation: 0x6000007ebec0; duration: 0.250000; delay: 0.000000; property: (null); springDamping: 0.000000; initialVelocity: 0.000000; animationType: 5;>; deletingLayoutAnimation: (null)> -> <RCTLayoutAnimationGroup: 0x600001d8e280; creatingLayoutAnimation: <RCTLayoutAnimation: 0x600000712140; duration: 0.300000; delay: 0.000000; property: opacity; springDamping: 0.000000; initialVelocity: 0.000000; animationType: 4;>; updatingLayoutAnimation: <RCTLayoutAnimation: 0x600000712040; duration: 0.300000; delay: 0.000000; property: (null); springDamping: 0.000000; initialVelocity: 0.000000; animationType: 4;>; deletingLayoutAnimation: <RCTLayoutAnimation: 0x600000711a40; duration: 0.300000; delay: 0.000000; property: opacity; springDamping: 0.000000; initialVelocity: 0.000000; animationType: 4;>>.
2020-11-11 17:05:24.237901+0200 MobiLesson.temp_caseinsensitive_rename[71686:10966817] [javascript] Warning: Overriding previous layout animation with new one before the first began:
<RCTLayoutAnimationGroup: 0x600001de6940; creatingLayoutAnimation: (null); updatingLayoutAnimation: <RCTLayoutAnimation: 0x6000007ebec0; duration: 0.250000; delay: 0.000000; property: (null); springDamping: 0.000000; initialVelocity: 0.000000; animationType: 5;>; deletingLayoutAnimation: (null)> -> <RCTLayoutAnimationGroup: 0x600001d8e280; creatingLayoutAnimation: <RCTLayoutAnimation: 0x600000712140; duration: 0.300000; delay: 0.000000; property: opacity; springDamping: 0.000000; initialVelocity: 0.000000; animationType: 4;>; updatingLayoutAnimation: <RCTLayoutAnimation: 0x600000712040; duration: 0.300000; delay: 0.000000; property: (null); springDamping: 0.000000; initialVelocity: 0.000000; animationType: 4;>; deletingLayoutAnimation: <RCTLayoutAnimation: 0x600000711a40; duration: 0.300000; delay: 0.000000; property: opacity; springDamping: 0.000000; initialVelocity: 0.000000; animationType: 4;>>.
`

#### Steps to Reproduce / Code Snippets

`                
    <GiftedChat
                        ref={(ref) => {
                            this.giftedChatRef = ref;
                        }}
                        messages={[]}
     />
`
#### Expected Results

To open without a warning.

#### Additional Information

* React version: 16.13.1
* React Native version: 0.63.3
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by BrightDev1110** [comment]
+1

**Comment by johnrevs** [comment]
+1
