### ISSUE TITLE
keyboardShouldPersistTaps="never" doesn't work on the whole page when alignTop enabled

### ISSUE THREAD

**Issue by dommangetnicolas** [FaridSafi/react-native-gifted-chat#1964]
#### Issue Description

keyboardShouldPersistTaps="never" doesn't work on the whole page when alignTop enabled

#### Steps to Reproduce / Code Snippets

````
<GiftedChat
        messages={messages}
        onSend={(newMessages) => onSend(newMessages)}
        keyboardShouldPersistTaps="never"
        alignTop
      />
`````

#### Expected Results

Make keyboardShouldPersistTaps on the whole page. FlatList doesn't fill all the container

#### Additional Information

* Nodejs version: v12.18.3
* React version: 16.13.1
* React Native version: 0.63.2
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: 3.8.3

**Comment by mrcustodio** [comment]
Any news on this?
