### ISSUE TITLE
How can I render accessory above the composer?

### ISSUE THREAD

**Issue by darron1217** [FaridSafi/react-native-gifted-chat#1965]
#### Issue Description
I tried it on `renderComposer` but the composer overlaps the last message.

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by kenkotch** [comment]
you can user renderInputToolbar: 
```
<View style={...someStyles}>
  <RenderActions />
  <InputToolbar
    renderActions={() => null}
    renderComposer={() => renderComposer(props)}
    renderSend={() => <RenderSend props={props} isSendActive={isSendActive} />}
    containerStyle={...containerStyles}
  />
</View>
```

this way you can style so RenderActions is wherever you want it

**Comment by darron1217** [comment]
I solved it by giving `flexDirection: column-reverse` to InputToolbar
```
        renderInputToolbar={(props: InputToolbarProps) => {
          if (replyingMessage) {
            props.accessoryStyle = {
              height: replyingMessage ? replyingHeight : 0,
            };
            props.containerStyle = {flexDirection: 'column-reverse'};
            props.renderAccessory = renderAccessory;
            props.renderActions = renderActions;
          }
          return <InputToolbar {...props} />;
        }}
```

Anyway, thank you for the feedback 👍

**Comment by fukemy** [comment]
hi @darron1217 , u want to make renderAccessory for replyView? Can i ask a question, what next component u want to use as customkeyboard, such as stickerkeyboard, emoji...?
