### ISSUE TITLE
 position of image view not on top in lightbox

### ISSUE THREAD

**Issue by xkungfu** [FaridSafi/react-native-gifted-chat#1968]
#### Issue Description

when press an image, the image zoomed.
but other messages cover this image.

![before](https://user-images.githubusercontent.com/26067653/101132939-cffae580-3642-11eb-98af-bb2bc42f3713.png)

![after](https://user-images.githubusercontent.com/26067653/101132999-e608a600-3642-11eb-8f17-2f87abada0ca.png)

#### Steps to Reproduce / Code Snippets

upload v0.16.3.tar.gz to directory.
then "yarn install".
then "expo start -w" or "expo start -w --dev"

#### Expected Results

how to resolve? why the image not on top level?

#### Additional Information

Nodejs version: v12.18.3
React version: 16.9.0
React Native version: 1.1.0
react-native-gifted-chat version: 0.16.3
Platform(s) (iOS, Android, or both?): web
TypeScript version: 3.8.3

**Comment by xkungfu** [comment]
I tried lots of ways.
but all not work!
this is caused by flatlist, 

In a flatlist, position of next item always at upper level to previours one, but  in this flatlist, there is no way to update the style of item, such as adding 'z-index:999' or 'position: fixed'...

so the solution is: remove lightbox, or remove flatlist.

**Comment by efstathiosntonas** [comment]
@xkungfu you can use your own image viewer instead of lightbox, for more info check: https://github.com/FaridSafi/react-native-gifted-chat/issues/1950
