### ISSUE TITLE
The future of react-native-gifted-chat

### ISSUE THREAD

**Issue by DerekFei** [FaridSafi/react-native-gifted-chat#1973]
I think react-native-gifted-chat is an awesome lib for speeding up the chat development process. However, I see many unsolved issues from this library and no pull request merged for the past several months. It's abnormal compared to the rapid development of this library before.

To use react-native-gifted-chat for a production app, I have concerns about the future support of this library. It would be much appreciated if anyone from the contributor team could kindly share the future roadmap on the development.

**Comment by ProBeta1** [comment]
Yes please do !

**Comment by Zeusmist** [comment]
@xcarpentier Could you please give a word here?
I love the purpose of RNGC and it's ability to be customized to taste.
But recently I noticed there's a lot of lags, I'm guessing because it's still using expo sdk 37.

I'm willing to upgrade expo but might need some support if anything crashes due to upgrade.

@xcarpentier What do you say?

**Comment by rafetkhallaf** [comment]
I actually was planning to implement this on a production environment and I was looking around the list of bugs and updates to the library.

It is a very great effort I can see, but not sure if it's suitable for production especially considering the fact that ReactNative is rapidly releasing new updates. @xcarpentier did great to establish this library but his time is not free, I think the community should commit to carrying this project and maintaining it.

For the time being I think I'll pass on this, but I'm very interested in this project and will keep following it's development. Great work!

**Comment by DerekFei** [comment]
> I actually was planning to implement this on a production environment and I was looking around the list of bugs and updates to the library.
> 
> It is a very great effort I can see, but not sure if it's suitable for production especially considering the fact that ReactNative is rapidly releasing new updates. @xcarpentier did great to establish this library but his time is not free, I think the community should commit to carrying this project and maintaining it.
> 
> For the time being I think I'll pass on this, but I'm very interested in this project and will keep following it's development. Great work!

Yea, I also give up using this lib for production. Would love to follow its development as well.

**Comment by Zeusmist** [comment]
> > I actually was planning to implement this on a production environment and I was looking around the list of bugs and updates to the library.
> > It is a very great effort I can see, but not sure if it's suitable for production especially considering the fact that ReactNative is rapidly releasing new updates. @xcarpentier did great to establish this library but his time is not free, I think the community should commit to carrying this project and maintaining it.
> > For the time being I think I'll pass on this, but I'm very interested in this project and will keep following it's development. Great work!
> 
> Yea, I also give up using this lib for production. Would love to follow its development as well.

Do you have any other library in mind? Or you're gonna build yours?

**Comment by rafetkhallaf** [comment]
> 
> 
> > > I actually was planning to implement this on a production environment and I was looking around the list of bugs and updates to the library.
> > > It is a very great effort I can see, but not sure if it's suitable for production especially considering the fact that ReactNative is rapidly releasing new updates. @xcarpentier did great to establish this library but his time is not free, I think the community should commit to carrying this project and maintaining it.
> > > For the time being I think I'll pass on this, but I'm very interested in this project and will keep following it's development. Great work!
> > 
> > 
> > Yea, I also give up using this lib for production. Would love to follow its development as well.
> 
> Do you have any other library in mind? Or you're gonna build yours?

My coworker @niteshcoder263 and I are working on something for the company internal use for our projects and client's projects, and we are are almost done with it. We are thinking of making it public including the back-end.

It's built specifically to work with the back-end we built based on NodeJS, and the library is using WebSocket (that project is called PEIT), but the UI itself can be used separately of course. At the moment it doesn't have stuff like read status feature or the typing indication but I'm sure it will be added later on.

we are trying to use only react native components except for the library for uploading / viewing images, and the library for recording voice notes to make sure the library can stand the updates and releases to react native and we are trying to keep it as simple as possible so it's easy to customize for projects separately if needed. The chat also support group messaging.

Also the library and backend only store UUID as a refrenec to the users, developer will need to have an API call that can retrieve the user card/information from whatever system they plan to integrate the chat with.

We are planning to make the backend fully support all the features of modern messaging systems as we go along. If anybody want to contribute they are of course welcome once we change the repo to public as i'm sure this could be helpful to other developers.

![image](https://user-images.githubusercontent.com/26126456/103320269-8a370000-49e9-11eb-81c5-e36b02065979.png)

**Comment by Return-1** [comment]
Makes me go hmm.. not very encouraging.

**Comment by xcarpentier** [comment]
already done

**Comment by Return-1** [comment]
@xcarpentier Could you elaborate on what you mean by this? Thank you for your response.
