### ISSUE TITLE
Navigation Header not rendering in properly

### ISSUE THREAD

**Issue by hadihassan09** [FaridSafi/react-native-gifted-chat#1977]
#### Issue Description

When rendering the navigation header, 2 headers are rendered over each other.

#### Steps to Reproduce / Code Snippets

Navigation Component:
```
                <StudntsChatStack.Screen
                    name="ChatGroup"
                    component={ChatScreen}
                    options={{
                        title: 'Chat Group',
                        headerTitleAlign: 'center',
                        headerTitleStyle: {
                            color: '#2e64e5',
                            fontFamily: 'Kufam-SemiBoldItalic',
                            fontSize: 18
                        },
                        headerStyle: {
                            backgroundColor: '#2e64e515',
                            shadowColor: '#fff',
                            elevation: 0,
                        },
                        headerBackTitleVisible: true,
                        headerBackImage: () => (
                            <View style={{ marginLeft: 15 }}>
                                <Ionicons name="arrow-back" size={25} color="#2e64e5" />
                            </View>
                        ),
                    }} />
````
Chat Component:
```
    render() {
        return (
            <GiftedChat
                alignTop
                keyboardVerticalOffset={true}
                renderUsernameOnMessage={true}
                messages={this.state.messages}
                onSend={this.db.send}
                user={this.user}
            />
        );
    }
```

[Example Image](https://pasteboard.co/JGjma7W.png)

#### Additional Information

* Nodejs version: v14.10.1
* React version: 16.13.1
* React Native version: 0.63.4
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: [FILL THIS OUT]

**Comment by smit-luvani** [comment]
@hadihassan09 Could you please share your solution? I am facing the similar issue. Attached screenshot (https://i.imgur.com/qe5uOFe.png).
![image](https://github.com/user-attachments/assets/390de5e9-05cf-4c9c-b1b3-6cc577caa7e8)

**Comment by smit-luvani** [comment]
I tried but did not work. and so downgraded version. 

https://github.com/FaridSafi/react-native-gifted-chat/issues/2558#issuecomment-2506760585

**Comment by MarkKewley** [comment]
The isStatusBarTranslucentAndroid={true} did work for me

**Comment by astrahov** [comment]
This is still a thing

```
"react-native": "0.78.2",
"react-native-gifted-chat": "2.8.1",
```

But... There was no problem on the previous version of ReactNative

```
"react-native": "0.77.2",
"react-native-gifted-chat": "2.8.1",
```
