### ISSUE TITLE
renderMessageVideo is not a defined prop (TypeScript)

### ISSUE THREAD

**Issue by Joshandrews43** [FaridSafi/react-native-gifted-chat#1978]
#### Issue Description

When I try to use the renderMessageVideo prop, it tells me it does not exist.

#### Steps to Reproduce / Code Snippets

try to use the renderMessageVideo prop

#### Expected Results

No typescript error

#### Additional Information

* Nodejs version: 14
* React version: latest
* React Native version: latest
* react-native-gifted-chat version: latest
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: 4.0.0

**Comment by darron1217** [comment]
Why this is closed?
I'm experiencing same issue
