### ISSUE TITLE
List Not Updating

### ISSUE THREAD

**Issue by swaroopa94** [FaridSafi/react-native-gifted-chat#198]
Hiii,

I just have a small issue in this when i am sending my message the list view is not updating and my message is not appending to the list.
Can you please tell me how to solve this..?

**Comment by FaridSafi** [comment]
Hello, please check how `this.state.messages` is used in https://github.com/FaridSafi/react-native-gifted-chat/blob/master/example/App.js

**Comment by swaroopa94** [comment]
I used same as in the example but it did not work for me..
Here is my onSend function:
 onSend(messages = []) {
    var chatMessage=messages[0].text
    var fromUserId=this.props.fromUserId
    var toUserId=this.props.toUserId
    var array=[];
    var record={"chatMessage":chatMessage,"fromUserId":fromUserId,"toUserId":toUserId,"chatDate":new Date()}
    array.push(record)
    var toUserId=this.props.toUserId
    var string = "mutation m {addChatMessage(fromUserId:\""+fromUserId+"\",toUserId:\""+toUserId+"\",chatMessage:\""+chatMessage+"\"){ _id,chatMessage,chatDate}}"
   console.log(string);
    addChatMessage(string).then((responseData)=>{
     // var record={"chatMessage":chatMessage,"fromUserId":fromUserId,"toUserId":toUserId,"chatDate":new Date()}
      //this.state.messages.push(record);
      
      //  Alert.alert(JSON.stringify(responseData.data.addChatMessage))
        
    }).catch((err)=>{
      Alert.alert('SportsFans','Server Stoped');
    }).done()
   this.setState((previousState) => {
      return {
        messages: GiftedChat.append(previousState.messages, array),
      }
    });
}

Please check once and tell me where i was wrong

**Comment by FaridSafi** [comment]
Messages that you append using `GiftedChat.append(previousState.messages, array)` should have the following structure :

```
{
  _id: 1,
  text: 'My message',
  createdAt: new Date(Date.UTC(2016, 5, 11, 17, 20, 0)),
  user: {
    _id: 2,
    name: 'React Native',
    avatar: 'https://facebook.github.io/react/img/logo_og.png',
  },
  image: 'https://facebook.github.io/react/img/logo_og.png',
  // additional custom parameters
}
```

**Comment by swaroopa94** [comment]
I have changed the structure 
The message is appending to the previous messages array and is being send but, it is displaying after reloading the app only..

**Comment by swaroopa94** [comment]
Hii,
 In this if i  change like GiftedChat.prepend(previousState.messages, array) then the message is appending but if i use append its not working.
can You please tell me how to solve it..

**Comment by xero88** [comment]
same issue for me

**Comment by avdept** [comment]
You can do like

this.setState((previousState) => {
      return {
        messages: GiftedChat.append([], array_of_all_messages),
      }
    });
