### ISSUE TITLE
Can we add more then one action icon ?

### ISSUE THREAD

**Issue by codemonster91** [FaridSafi/react-native-gifted-chat#1980]
#### Issue Description

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by thanhdevapp** [comment]
Like that ? 

https://prnt.sc/wctix4

`const renderActions = (props: Readonly<ActionsProps>) => {
    return (
      <>
        <Actions
          {...props}
          icon={() => (
            <Icon name={'plus-circle-outline'} size={24} color={color.dim} />
          )}
          onPressActionButton={onActionPlus}
        />
        <Actions
          {...props}
          icon={() => (
            <Icon name={'image-area'} size={24} color={color.dim} />
          )}
          onPressActionButton={onActionPlus}
        />
        <Actions
          {...props}
          icon={() => (
            <Icon name={'camera-outline'} size={24} color={color.dim} />
          )}
          onPressActionButton={onActionPlus}
        />
      </>
    )
  }`

` const renderInputToolbar = props => {
    return (
      <InputToolbar
        {...props}
        renderComposer={renderComposer}
        renderActions={renderActions}
        renderSend={renderSend}
        accessoryStyle={{ height: 302 }}
        containerStyle={{
          backgroundColor: '#fff',
          borderTopColor: '#E8E8E8',
          borderTopWidth: 1,
        }}
      />
    )
  }`
