### ISSUE TITLE
React gifted chat message alignment

### ISSUE THREAD

**Issue by srivassid** [FaridSafi/react-native-gifted-chat#1982]
#### Issue Description

I cannot get messages from two users to align on the left and right side, while pulling them from state. They all go on the left side. If i try to post a new message, that message goes on the right side as expected, but not while pulling them from state.

#### Steps to Reproduce / Code Snippets

```
import { StatusBar } from 'expo-status-bar';
import React, { useState } from 'react';
import { GiftedChat } from 'react-native-gifted-chat';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  const [messages, setMessages] = useState([
    {
    _id: 1,
    text: 'This is a quick reply. Do you love Gifted Chat? (radio) KEEP IT',
    createdAt: new Date(),
    user: {
      _id: 2,
      name: 'React Native',
    },
  },
  {
    _id: 2,
    text: 'This is a quick reply. Do you love Gifted Chat? (checkbox)',
    createdAt: new Date(),
    user: {
      _id: 3,
      name: 'React',
    },
  }
  ]);

  const onSend = (newMessage = []) => {
    setMessages(GiftedChat.append(messages, newMessage));
  };
  
  return (
    <GiftedChat
      messages={messages}
      onSend={newMessage => onSend(newMessage)}
      user={{
        _id: 1,
      }}
    />
  );
}

```
#### Expected Results

The messages should be left and right aligned, but they are just left aligned. Posting a new message is not a problem, pulling them from state is.

#### Additional Information

* Nodejs version: 12.18.4
* React version: 17.0.0
* React Native version: 0.63.4
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): Web
* TypeScript version: 4.1.3

**Comment by InovaXion** [comment]
The user id of  `<GiftedChat
      messages={messages}
      onSend={newMessage => onSend(newMessage)}
      user={{
        _id: 1,
      }}
    />` have to be the same as the user id message.
    If you want ReactNative to be the user at right juste change the id to 2. If you want React, change it to 3...
    If it still not working try with quotes, for me when i have `user={{
              _id: 10
            }}` it's not working but '`user={{
              _id: '10'
            }}`' works fine

**Comment by jonnyn** [comment]
Same issue here. Did you find the solution?

**Comment by srivassid** [comment]
i did. Check this out https://stackoverflow.com/questions/65590802/react-gifted-chat-message-alignment
