### ISSUE TITLE
How to change the color of hyperlink

### ISSUE THREAD

**Issue by YeonjuSeo** [FaridSafi/react-native-gifted-chat#1986]
#### Issue Description

I've got to know that react-native-gifted-chat automatically makes a series of numbers(over 10) as hyperlinks with underline and specific color(white for right, black for left). So I want to change the color and remove the underline of it. How can I change it?

#### Steps to Reproduce / Code Snippets
```
renderBubble(props) {
    return (
      <Bubble
        {...props}
        textStyle={{
          right: {
            color: 'white',
            textDecorationLine: 'none',
            textDecorationStyle: 'solid',
          },
          left: {
            color: 'white',
            textDecorationLine: 'none',
            textDecorationStyle: 'solid',
          },
        }}
        wrapperStyle={{
          left: {
            backgroundColor: 'green',
            marginHorizontal: 10,
            marginVertical: 5,
            paddingVertical: 10,
            paddingHorizontal: 10,
            borderRadius: 20,
            shadowColor: '#000',
            shadowOffset: {
              width: 0,
              height: 2,
            },
            shadowOpacity: 0.25,
            shadowRadius: 3.84,
            elevation: 5,
            textDecorationLine: 'none',
            textDecorationStyle: 'solid',
          },
          right: {
            backgroundColor: 'green',
            marginHorizontal: 10,
            marginVertical: 5,
            borderRadius: 20,
            paddingHorizontal: 10,
            paddingVertical: 10,
            shadowColor: '#000',
            shadowOffset: {
              width: 0,
              height: 2,
            },
            shadowOpacity: 0.25,
            shadowRadius: 3.84,
            elevation: 5,
            textDecorationLine: 'none',
            textDecorationStyle: 'solid',
          },
        }}
      />
    );
  }
```

#### Expected Results
![image](https://user-images.githubusercontent.com/56028436/104836595-481b2300-58f2-11eb-995d-ab1542d9df18.png)

**Comment by efstathiosntonas** [comment]
You should pass `parsePatterns`:

```
parsePatterns={(item: any) => [
          {
            type: "url",
            style: {
              textDecorationLine: "underline",
              color:
                item && item[0].color === "black"
                  ? themeContext.chatScreen.linksColorLeft
                  : themeContext.chatScreen.linksColorRight
            },
            onPress: async (text: string) => {
              await handleLink(text, navigation);
            }
          },
          {
            type: "phone",
            style: {
              color:
                // @ts-ignore
                item && item[0].color === "black"
                  ? themeContext.chatScreen.linksColorLeft
                  : themeContext.chatScreen.linksColorRight
            },
            onPress: callNumber
          },
          {
            type: "email",
            style: {
              color:
                // @ts-ignore
                item && item[0].color === "black"
                  ? themeContext.chatScreen.emailColorLeft
                  : themeContext.chatScreen.emailColorRight
            },
            onPress: sendEmailTo
          }
        ]}

```

note that ` item && item[0].color === "black"` is the styling of the left bubble if i remember correct.

**Comment by YeonjuSeo** [comment]
I'm really happy to know this thx!

**Comment by nsdub** [comment]
This is less disruptive if you just pass in `linkStyles` to the Message component. If you use `parsePatterns` you have to recreate the other prop behavior, like `onPress`

Example:
```
import { GiftedChat, Message } from 'react-native-gifted-chat'

  renderMessage = (props) => {
    return (
      <Message
        {...props}
        linkStyle={{
          right: {
            color: 'pink'
          },
          left: {
            color: 'orange'
          }
        }}
      />
    )
  }

render() {
    return (
      <View style={{flex: 1}}>
        <GiftedChat
          ...props
          messages={messages}
          renderMessage={this.renderMessage}
        />
      </View>
    )
  }

**Comment by azhararmar** [comment]
> You should pass `parsePatterns`:
> 
> ```
> parsePatterns={(item: any) => [
>           {
>             type: "url",
>             style: {
>               textDecorationLine: "underline",
>               color:
>                 item && item[0].color === "black"
>                   ? themeContext.chatScreen.linksColorLeft
>                   : themeContext.chatScreen.linksColorRight
>             },
>             onPress: async (text: string) => {
>               await handleLink(text, navigation);
>             }
>           },
>           {
>             type: "phone",
>             style: {
>               color:
>                 // @ts-ignore
>                 item && item[0].color === "black"
>                   ? themeContext.chatScreen.linksColorLeft
>                   : themeContext.chatScreen.linksColorRight
>             },
>             onPress: callNumber
>           },
>           {
>             type: "email",
>             style: {
>               color:
>                 // @ts-ignore
>                 item && item[0].color === "black"
>                   ? themeContext.chatScreen.emailColorLeft
>                   : themeContext.chatScreen.emailColorRight
>             },
>             onPress: sendEmailTo
>           }
>         ]}
> ```
> 
> note that ` item && item[0].color === "black"` refers to the left bubble.
> 
> internally it uses https://github.com/taskrabbit/react-native-parsed-text

This is the right way to go about it, and it works. Thanks

**Comment by xdumaine** [comment]
For typescript @nsdub's solution works, but does not type check. Instead, use `MessageText` and `renderMessageText`

```tsx
import { GiftedChat, MessageText, MessageTextProps, IMessage } from 'react-native-gifted-chat'

const CustomMessageText: React.FC<MessageTextProps<IMessage>> = (props) => {
    <MessageText
      {...props}
      linkStyle={{
        right: {
          color: 'pink'
        },
        left: {
          color: 'orange'
        }
      }}
    />
  )
}

render() {
    return (
      <View style={{flex: 1}}>
        <GiftedChat
          ...props
          messages={messages}
          renderMessageText={CustomMessageText}
        />
      </View>
    )
  }
```
