### ISSUE TITLE
GiftedChat.d.ts does not have the correct typing for renderAvatar

### ISSUE THREAD

**Issue by jkepps** [FaridSafi/react-native-gifted-chat#1990]
#### Issue Description
The type definition file for GiftedChat does not have the correct typing for the `renderAvatar` prop.
```ts
renderAvatar?(props: Avatar<TMessage>['props']): React.ReactNode;
```
`null` is not allowed, and as a result, a typescript error is thrown when passing `null` as the value.

#### Steps to Reproduce / Code Snippets
```jsx 
<GiftedChat renderAvatar={null} />
```

#### Expected Results
There is no typescript error.

#### Additional Information

* Nodejs version: 14.6.0
* React version: 16.13.1
* React Native version: 0.63.4
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: 4.0.2

**Comment by efstathiosntonas** [comment]
Fixed at https://github.com/FaridSafi/react-native-gifted-chat/pull/2023
