### ISSUE TITLE
Module AppRegistry is not a registered callable module

### ISSUE THREAD

**Issue by jamesdmurphy51** [FaridSafi/react-native-gifted-chat#1991]
#### Issue Description

When upgrade to react-native 0.63.x, error is "Module AppRegistry is not a registered callable module" when run react-native run-android
This error can be removed by either:
Downgrade react native
Remove any import statements from react-native-gifted-chat

#### Steps to Reproduce / Code Snippets

Upgrade to RN 0.63.3 (most recent version)
Add import such as "import {GiftedChat, Bubble} from 'react-native-gifted-chat';"

#### Expected Results

Build with no issues

#### Additional Information

* Nodejs version: 10.16.0
* React version: 16.13.1
* React Native version: 0.63.3
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: N/A
![Capture](https://user-images.githubusercontent.com/13387219/105798257-9c538200-5f46-11eb-9439-16adc1e13499.PNG)

**Comment by efstathiosntonas** [comment]
Have you tried deleting `node_modules` and `package/yarn.lock` and reinstall them?

clearing npm cache could help too:
`npm cache clean --force` or `yarn cache clean` before reinstalling  

try to also clearing watchman and cache:
`watchman watch-del-all && rm -rf $TMPDIRreact-native-packager-cache-* && rm -rf $TMPDIRmetro-bundler-cache-*`

start with `npm start --reset-cache`

**Comment by RajPratim21** [comment]
Still facing similar issue
