### ISSUE TITLE
[Android] gifted chat scroll sometimes doesn't works 

### ISSUE THREAD

**Issue by jangys** [FaridSafi/react-native-gifted-chat#1993]
#### Issue Description
gifted chat's scroll sometimes doesn't works only in the Android platform. I found that if I use TouchableWithoutFeedback, scroll doesn't work properly. 
It is weird that if I starts scrolling at message bubble or avatar profile(I think it is touchable component), scroll works well.
How can I fix it?

I use TouchableWithoutFeedback and KeyboardAvoidingView for chat view adjust keyboard's size. 

#### Steps to Reproduce / Code Snippets

```
<TouchableWithoutFeedback onPress={Keyboard.dismiss} accessible={false}>
        <KeyboardAvoidingView
          behavior="padding"
          onStartShouldSetResponder={() => true}
          keyboardVerticalOffset={
            Platform.OS === "ios" ? 0 : -Dimensions.get("window").height
          }
          style={{ flex: 1, backgroundColor: "#000" }}
        >
          <OtherComponents/>
          <GiftedChat
            ref="giftedChat"
            style={{ flex: 9 }}
            messages={this.state.messages}
            onSend={(messages) => this.onSend(messages)}
            renderBubble={this._renderBubble}
            renderTime={this._renderTime}
            renderMessage={this._renderMessage}
            renderSend={this._renderSend}
            renderInputToolbar={this._renderInputToolbar}
            textInputStyle={styles.chatTextInput}
            placeholder="Your messages..."
            isKeyboardInternallyHandled={false}
            scrollToBottom={true}
            onPressAvatar={() =>
              this._openPartnerProfileModal(
                this.props.navigation.getParam("partnerProfildId")
              )
            }
            user={{
              _id: this.state.loginUserId,
              name: "me",
              avatar: "",
            }}
          />
          <OtherComponents/>
        </KeyboardAvoidingView>
      </TouchableWithoutFeedback>
```

#### Expected Results

I hope scroll works well in the android platform.

#### Additional Information

* Nodejs version: v12.16.1
* React version: 16.13.1
* React Native version: 0.63.3
* react-native-gifted-chat version: ^0.16.3
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by guigralho** [comment]
Hi,

I'm having the same issue here but also on iOS.
The screen only scrolls if I start scrolling at message bubble

**Comment by evucis98** [comment]
I'm also having the same issue, it's because of `TouchableWithoutFeedback `, I have no idea how to resolve this :(

**Comment by sepandy** [comment]
Removing TouchableWithoutFeedback fixed the problem and I am still able to dismiss the keyboard by tapping on the screen so I am guessing gifted chat has TouchableWithoutFeedback built in and we don't need to do it manually.

**Comment by vamshigroupin** [comment]
@sepandy even after removing TouchableWithoutFeedback still facing same problem...any other solution?

**Comment by rohank45** [comment]
> #### Issue Description
> gifted chat's scroll sometimes doesn't works only in the Android platform. I found that if I use TouchableWithoutFeedback, scroll doesn't work properly. It is weird that if I starts scrolling at message bubble or avatar profile(I think it is touchable component), scroll works well. How can I fix it?
> 
> I use TouchableWithoutFeedback and KeyboardAvoidingView for chat view adjust keyboard's size.
> 
> #### Steps to Reproduce / Code Snippets
> ```
> <TouchableWithoutFeedback onPress={Keyboard.dismiss} accessible={false}>
>         <KeyboardAvoidingView
>           behavior="padding"
>           onStartShouldSetResponder={() => true}
>           keyboardVerticalOffset={
>             Platform.OS === "ios" ? 0 : -Dimensions.get("window").height
>           }
>           style={{ flex: 1, backgroundColor: "#000" }}
>         >
>           �<OtherComponents/>
>           <GiftedChat
>             ref="giftedChat"
>             style={{ flex: 9 }}
>             messages={this.state.messages}
>             onSend={(messages) => this.onSend(messages)}
>             renderBubble={this._renderBubble}
>             renderTime={this._renderTime}
>             renderMessage={this._renderMessage}
>             renderSend={this._renderSend}
>             renderInputToolbar={this._renderInputToolbar}
>             textInputStyle={styles.chatTextInput}
>             placeholder="Your messages..."
>             isKeyboardInternallyHandled={false}
>             scrollToBottom={true}
>             onPressAvatar={() =>
>               this._openPartnerProfileModal(
>                 this.props.navigation.getParam("partnerProfildId")
>               )
>             }
>             user={{
>               _id: this.state.loginUserId,
>               name: "me",
>               avatar: "",
>             }}
>           />
>           �<OtherComponents/>
>         </KeyboardAvoidingView>
>       </TouchableWithoutFeedback>
> ```
> 
> #### Expected Results
> I hope scroll works well in the android platform.
> 
> #### Additional Information
> * Nodejs version: v12.16.1
> * React version: 16.13.1
> * React Native version: 0.63.3
> * react-native-gifted-chat version: ^0.16.3
> * Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
> * TypeScript version: [FILL THIS OUT]

I'm having the same issue does anyone have any idea how to solve this?

**Comment by rohank45** [comment]
I'm having the same issue does anyone have any idea how to solve this?

**Comment by rohank45** [comment]
> #### Issue Description
> gifted chat's scroll sometimes doesn't works only in the Android platform. I found that if I use TouchableWithoutFeedback, scroll doesn't work properly. It is weird that if I starts scrolling at message bubble or avatar profile(I think it is touchable component), scroll works well. How can I fix it?
> 
> I use TouchableWithoutFeedback and KeyboardAvoidingView for chat view adjust keyboard's size.
> 
> #### Steps to Reproduce / Code Snippets
> ```
> <TouchableWithoutFeedback onPress={Keyboard.dismiss} accessible={false}>
>         <KeyboardAvoidingView
>           behavior="padding"
>           onStartShouldSetResponder={() => true}
>           keyboardVerticalOffset={
>             Platform.OS === "ios" ? 0 : -Dimensions.get("window").height
>           }
>           style={{ flex: 1, backgroundColor: "#000" }}
>         >
>           �<OtherComponents/>
>           <GiftedChat
>             ref="giftedChat"
>             style={{ flex: 9 }}
>             messages={this.state.messages}
>             onSend={(messages) => this.onSend(messages)}
>             renderBubble={this._renderBubble}
>             renderTime={this._renderTime}
>             renderMessage={this._renderMessage}
>             renderSend={this._renderSend}
>             renderInputToolbar={this._renderInputToolbar}
>             textInputStyle={styles.chatTextInput}
>             placeholder="Your messages..."
>             isKeyboardInternallyHandled={false}
>             scrollToBottom={true}
>             onPressAvatar={() =>
>               this._openPartnerProfileModal(
>                 this.props.navigation.getParam("partnerProfildId")
>               )
>             }
>             user={{
>               _id: this.state.loginUserId,
>               name: "me",
>               avatar: "",
>             }}
>           />
>           �<OtherComponents/>
>         </KeyboardAvoidingView>
>       </TouchableWithoutFeedback>
> ```
> 
> #### Expected Results
> I hope scroll works well in the android platform.
> 
> #### Additional Information
> * Nodejs version: v12.16.1
> * React version: 16.13.1
> * React Native version: 0.63.3
> * react-native-gifted-chat version: ^0.16.3
> * Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
> * TypeScript version: [FILL THIS OUT]

removed flex:1 it will fix the scrolling issues.

**Comment by SaloniThinksys** [comment]
i'm also having scroll stuck issue but able to reproduce it rarely and mainly on boundaries (top-bottom)
below is my implemented code:

<GestureRecognizer
        onSwipeLeft={isFooterScroll ? onSwipeLeft : undefined}
        onSwipeRight={isFooterScroll ? onSwipeRight : undefined}
        config={config}
        style={{ flex: 1 }}
      >
        <SafeAreaView style={styles.mainView}>
          <TapGestureHandler
            onHandlerStateChange={({ nativeEvent }) => {
              if (nativeEvent.state === State.END) {
                Keyboard.dismiss();
              }
            }}
            shouldCancelWhenOutside={false}
          >
              <GiftedChat
                alignTop
                messages={messages}
                messageContainerRef={messageContainerRef}
                onSend={(newMessages: any) => handleSend(newMessages)}
                user={{ _id: 1 }}
                text={photoUri ? (text.length === 0 ? '\u200B' : text) : text}
                bottomOffset={-insets.bottom + 14}
                showUserAvatar
                alwaysShowSend={
                  text.length > 0 || (photoUri !== null && photoUri !== '')
                }
                placeholder={CHAT_PLACEHOLDER}
                renderAvatar={() => null}
                keyboardShouldPersistTaps="handled"
                listViewProps={{
                  onScroll: (e: any) => {
                    const offsetY = e.nativeEvent.contentOffset.y;
                    if (offsetY > 80) {
                      setShowScrollButton(true);
                    } else {
                      setShowScrollButton(false);
                    }
                  },
                  // @ts-ignore
                  renderScrollComponent: (prop: any) => (
                    <KeyboardAwareScrollView
                    ref={scrollRef}
                      extraKeyboardSpace={Platform.OS === 'android' ? 0 : -20}
                      {...prop}
                    />
                  ),
                  bounces: false,
                  // Adding margin from top for first bubble as using alignTop we need to pass reverse values
                  contentContainerStyle: {
                    paddingBottom: 35,
                  },
                }}
                // renderDay={dayProps => <ChatRenderDay {...dayProps} />}
                renderDay={() => null}
    --------further code------
}

}
