### ISSUE TITLE
renderMessageText not updating when state changes

### ISSUE THREAD

**Issue by adriaandebolle** [FaridSafi/react-native-gifted-chat#1995]
#### Issue Description

renderMessageText does not update according to state changes

![Simulator Screen Shot - iPhone 8 - 2021-02-05 at 21 14 44](https://user-images.githubusercontent.com/14223265/107084682-a8b5c580-67f7-11eb-8392-76991ea3be93.png)

When writing a new message it is the updated value, but the messages rendered earlier are not updated.

#### Steps to Reproduce / Code Snippets

Include
`<Text>{this.state.array.length}</Text>`
within renderMessageText and for example renderMessageContainer

When the array length dynamically changes the text value changes within renderMessageContainer, but not within renderMessageText.

#### Expected Results

State changes should also be reflected within renderMessageText

#### Additional Information

* Nodejs version: v14.9.0
* React version: 16.13.1
* React Native version: 0.63.4
* react-native-gifted-chat version: ^0.16.3
* Platform(s) (iOS, Android, or both?): Both
* TypeScript version: command not found: tsc

**Comment by Syntbeheer** [comment]
This is a fix, but seems like the ugliest fix ever:

`let messages = this.state.messages;
            this.setState((previousState) => ({
              messages: [],
            }));
            this.setState((previousState) => ({
              messages: messages,
            }));`

After the state (array) changes to call the above lines of code to force rerendering the messages...

**Comment by adriaandebolle** [comment]
This is a fix, but seems like the ugliest fix ever:

```
let messages = this.state.messages; 
this.setState((previousState) => ({ messages: [], })); 
this.setState((previousState) => ({ messages: messages, }));
```

After the state (array) changes to call the above lines of code to force rerendering the messages...

**Comment by ttnghia195** [comment]
> This is a fix, but seems like the ugliest fix ever:
> 
> ```
> let messages = this.state.messages; 
> this.setState((previousState) => ({ messages: [], })); 
> this.setState((previousState) => ({ messages: messages, }));
> ```
> 
> After the state (array) changes to call the above lines of code to force rerendering the messages...

Are there any other solutions?

**Comment by QaimSiddiqui** [comment]
I had this same issue , the problem was with javascript actually . 
We have to make a deep copy of our message list & then update it like this
`const msgCopy = JSON.parse(JSON.stringify(messages));

//update message copy and then update state
setMessages(msgCopy);
`

**Comment by TaylorFoster-Informulate** [comment]
Yikes, same issue. The above stringify solution didn't work for me. What did work is the other solution with clearing the state and then setting it back again. It causes nasty issues on the frontend tho for that split second.

**Comment by aliwaqar981** [comment]
Do we have any optimal solution for this?
