### ISSUE TITLE
Default prop makes it impossible to disable avatar press

### ISSUE THREAD

**Issue by doelgonzo** [FaridSafi/react-native-gifted-chat#1996]
This line in Avatar.tsx makes it so passing it into GiftedAvatar.tsx never allows for a disabled button. Explicitly passing `onPressAvatar={null}` gets overridden by the noop function in the default props here.
https://github.com/FaridSafi/react-native-gifted-chat/blob/5ba0c245d1a0e647c44a5c00d28a0497faadf6c0/src/Avatar.tsx#L74

Passing an explicit null should override it, or allow us to disable it manually via a different prop.

**Comment by joaosouz4dev** [comment]
Hi, did you manage to do any solution? I want to remove this and remove the active opacity of the component
