### ISSUE TITLE
How to expand the touchable area of SEND inside inputtoolbar for android. 

### ISSUE THREAD

**Issue by Mystic1008** [FaridSafi/react-native-gifted-chat#1997]
#### Issue Description

I have replaced the send button by an icon which represents send, and have pulled the icon out of the input toolbar to the left.
In IPAD and IOS, I am able to click on the send icon, but in android the send icon is not clickable. But when I click inside the input toolbar, the send icon outside is clicked.

How can I expand the touchable area of send inside the inputtoolbar to expand to the icon outside toolbar. 
Any other solution apart from this is also welcome

![Screenshot_1612972708](https://user-images.githubusercontent.com/78585275/107537010-72f25180-6be8-11eb-9874-8130756df4fa.png)

**Comment by efstathiosntonas** [comment]
Have you tried importing `TouchableOpacity` from `react-native-gesture-handler`? If the button has `position: “absolute”` then it might not work as expected on Android, search on google for this issue and you might find another workaround, ie wrap the button with a View and make the View `position: “absolute”`
