### ISSUE TITLE
How to persist Taps inside the ChatFooter? Custom Toolbar above the Input 

### ISSUE THREAD

**Issue by leonzuendel** [FaridSafi/react-native-gifted-chat#1998]
#### Issue Description

I'm trying to implement a custom Toobar to send GIFS etc (see image). Right now it's placed inside the renderChatFooter Prop, so it's visible ABOVE the input, not under it like the Accessory. But every time i tap on the Toolbar with opened keyboard it's just closing the keyboard and my Toolbar is only tappable with closed keyboard afterwards. I DONT want the keyboard to close at all when someone taps inside the Toolbar. I already copied the project locally because of a lot other issues with it, but I can't find anything in the code to make it behave like i desire...

#### Steps to Reproduce / Code Snippets / Screenshots

![simulator_screenshot_366E835D-E751-4599-ADC0-5608AD079DD3](https://user-images.githubusercontent.com/44927479/107891220-61c57f80-6f1d-11eb-948f-e4a835ce6eda.png)

![simulator_screenshot_9FA953EA-9607-45DC-B53A-9B3A9C612DBA](https://user-images.githubusercontent.com/44927479/107891224-6ee26e80-6f1d-11eb-8d23-ced2401dc4e9.png)

Add something tappable inside of renderChatFooter, sit back and watch it not being tappable.

#### Expected Results

Toolbar reacts to taps and keyboard only closes when someone taps on the scrollview component with the messages inside.

#### Additional Information

* Nodejs version: 12.16.3
* React version: 16.13.1
* React Native version: 40.0.1 with Expo
* react-native-gifted-chat version: 0.16.3 with some local changes
* Platform(s) (iOS, Android, or both?): both, but currently I'm only testing on iOS
* TypeScript version: I'm just using TypeScript inside the copied module, but not elsewhere in my project

**Comment by evan-klemen-cleo** [comment]
@leonzuendel Did you have any luck with this. I am trying to accomplish a similar functionality.

**Comment by fukemy** [comment]
any solution here @leonzuendel, plz share your solution plzz
