### ISSUE TITLE
Android: Issue when displayed in Modal

### ISSUE THREAD

**Issue by pfeiffer** [FaridSafi/react-native-gifted-chat#200]
There is an issue with the keyboard/height adjustments when displaying the component in a `Modal`.

It can be reproduced with the following simple render code:

```
<Image source={{ uri: 'http://cdn.pcwallart.com/images/dark-gradient-tumblr-wallpaper-1.jpg'}} style={{ flex: 1 }}>
  <GiftedChat />
</Image>
```

This renders the following:
<img src="https://cloud.githubusercontent.com/assets/195925/17701288/993da406-63c9-11e6-8db1-33e936a73155.png" width="200">

When focusing the TextInput, the component correctly resizes and positiones the input bar:

<img src="https://cloud.githubusercontent.com/assets/195925/17701306/ab0b1e66-63c9-11e6-8b48-b5b8e6105d40.png" width="200">

**However** when the code above is wrapped in a `<Modal> .. </Modal>` the following happens when focusing the TextInput:

<img src="https://cloud.githubusercontent.com/assets/195925/17701330/bce88772-63c9-11e6-82cc-72cd07558a02.png" width="200">

There are no issues on iOS.

**Comment by FaridSafi** [comment]
Can't test right now but I suggest to try to set a height to the Chat container
```jsx
<Image style={{
  height: Dimensions.get('window').height,
}} />
```

**Comment by pfeiffer** [comment]
Yeah, I tried that earlier, but with the same results (calculating for the status bar etc.)

**Comment by pfeiffer** [comment]
I suspect that the whole view is "pushed" up, ie. the modal has full device height and that the `GiftedChat` component is resized, but that the `windowSoftInputMode=adjustResize` doesn't apply to Modals on Android.

**Comment by pfeiffer** [comment]
Actually, digging through the react-native code I see that `Modal` on Android is implemented as `Dialog`.

The issue is that `adjustResize` isn't being applied to the `Dialog` that displays the modal. This can be fixed by adding the following to `res/values/styles.xml`:

```
<style name="Theme.FullScreenDialog">
     <item name="android:windowSoftInputMode">adjustResize</item>
</style>
```

Might be worth adding to the README :-)

**Comment by FaridSafi** [comment]
Good catch @pfeiffer!
Where is located `res/values/styles.xml` exactly ?

**Comment by pfeiffer** [comment]
Thanks! It's located at `android/app/src/main/res/values/styles.xml` :-)

**Comment by FaridSafi** [comment]
Thank you

**Comment by RealAmissio** [comment]
I tried, but after modifying style.xml, it still doesn't work, but at 0.14 I can use it directly. When I upgrade to 0.27, the keyboard is blocked，please help me

**Comment by RealAmissio** [comment]
the same in the modal

**Comment by l1br3** [comment]
@RealAmissio I just had an issue by trying to put the chat component in a ScrollView.
I succeded in making it works without the modification, @pfeiffer do you think React Native team could have change it ? I still don't see the style applied for modal [here](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/res/views/modal/values/themes.xml) but it works ...

**Comment by iswetak** [comment]
Hi @FaridSafi  please help
How to configure gift-chat to send message when enter key is pressed?
is it possible to
when keypress enter = send message

**Comment by fukemy** [comment]
did you tried to implement Facebook messenger gradient?
