### ISSUE TITLE
Is there any way to send stickers in chat??

### ISSUE THREAD

**Issue by AzadKshitij** [FaridSafi/react-native-gifted-chat#2000]
#### Issue Description

How can I send stickers in chat?

**Comment by iamnino** [comment]
You can use [GIPHY API](https://developers.giphy.com/docs/sdk/) it's free. 
You can send GIFs and stickers as images. 
Check out 
https://medium.com/just-ship-it-coding/integrating-giphy-api-in-react-native-8dc55dc172c8

**Comment by apappas1129** [comment]
You will have to use GiftedChat's `renderCustomView` prop.

**Comment by sharpDeveloper10** [comment]
@apappas1129  can you please share the example code here.
