### ISSUE TITLE
How can I reload messages to get new messages?

### ISSUE THREAD

**Issue by AMoktar** [FaridSafi/react-native-gifted-chat#2002]
#### Issue Description
I'm having gifted chat with mysql
Loading messages happens with useEffect as in componentDidMount
How can I reload if new message was sent from the other client ?
Thanks

**Comment by efstathiosntonas** [comment]
You'll need sockets and listen for new messages

**Comment by AMoktar** [comment]
Thanks @efstathiosntonas , is it ok if I used some functions like setInterval instead of using sockets?

**Comment by efstathiosntonas** [comment]
Then your users will hammer your server, if 100 users are requesting every 2 seconds messages from your server for no reason (ie not all users will have new messages) then you’re utilizing server resources, imagine this * 1000 users etc.
