### ISSUE TITLE
 Failed prop type: Invalid prop `currentMessage` of type `array` supplied to `Bubble`, expected `object`.

### ISSUE THREAD

**Issue by DhananjayPurohit** [FaridSafi/react-native-gifted-chat#2003]
Getting "Failed prop type: Invalid prop `currentMessage` of type `array` supplied to `Bubble`, expected `object`." when trying to send message.

* Nodejs version: 14.15.4
* React version: 16.13.1
* React Native version: 0.63.3
* react-native-gifted-chat version: ^0.16.3
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: 4.1.5

**Comment by yochevedAv** [comment]
Did you resolve this issue?
