### ISSUE TITLE
Problems with chat offset relative to the input field

### ISSUE THREAD

**Issue by Deodes** [FaridSafi/react-native-gifted-chat#2004]
#### Issue Description

Tried to implement a custom input field with autogrow, but ran into a problem when the height of the input field grows, chat messages go under it and you can see them only if you forcefully scroll the chat

#### Steps to Reproduce / Code Snippets

```
<InputToolbar
      {...props}
      containerStyle={styles.inputToolbar}
      renderActions={() => (
        <ImageFadeIn
          style={[styles.composerAvatar, { backgroundColor: 'gray'}]}
          source={{ uri: userLogo }}
        />
      )}
      renderComposer={(props) => <TextInput placeholderTextColor={'gray'} multiline={true} {...props} style={styles.composerTextInput} />}
      renderSend={(props) => (
        <Send
          {...props}
          label='send'
          containerStyle={styles.composerSendWrapper}
          textStyle={[
            styles.composerSend,
            { color: isChatBlocked ? 'gray' : 'white' },
          ]}
        />
      )}
    />
```

#### Additional Information

* Nodejs version: 14.11.0
* React version: 16.13.1
* React Native version: 0.64
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: 3.9.2

<img width="244" alt="Снимок экрана 2021-02-22 в 4 53 36 PM" src="https://user-images.githubusercontent.com/46958937/108724904-824d9500-752e-11eb-9966-28f0d73154e4.png">

**Comment by julian-hecker** [comment]
I too am having this issue.
