### ISSUE TITLE
TextInput multiline unresponsive when setting cursor with finger on specific position 

### ISSUE THREAD

**Issue by amirduran** [FaridSafi/react-native-gifted-chat#2012]
#### Issue Description

Problem with multiline TextInput on android platform

#### Steps to Reproduce / Code Snippets

If you enable multiline TextInput and then the TextInput is very unresponsive if you try to scroll the text or if you want to set cursor on the specific place to for example correct spelling or something. The input box just doesn't react to finger touch events and coursor just stays on the last position where it is.

#### Expected Results
Normal behavior would be that when you click with your finger on specific word, that text cursor is positioned on that specific position. Also, when you try to scroll the text using your finger, scroll should work.

#### Additional Information

* React Native version: 0.63.4
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): Android only
* TypeScript version: 4.0.0

**Comment by efstathiosntonas** [comment]
If i understand correctly the issue you're facing, it's a react-native bug with multiline TextInput, there are 2 bugs submitted: https://github.com/facebook/react-native/issues/30207 & https://github.com/facebook/react-native/issues/30748 

i have provided a temp solution until react-native devs fix it but it's not perfect and I do not know what side effects this might cause.

**Comment by amirduran** [comment]
The problem is that I'm experiencing this issue only on the chat's input field and that is why I'm wondering whether this is chat related bug or not.

**Comment by efstathiosntonas** [comment]
@amirduran I think this happens only when height is fixed or variable. If the multiline text input does not have height then it's ok.

**Comment by amirduran** [comment]
@efstathiosntonas any ideas how to handle than this problem? Currently, when user types, then input field's height is expanding until some point (max height is reached) but obviously this is then a problem with cursor.

**Comment by efstathiosntonas** [comment]
@amirduran follow the 2 links I provided above. You could modify the react-native source code in your node modules folder and then run `patch-package react-native`

In case you’re not familiar with `patch-package`, it’s an npm module you should install globally or as a dev dependency and then add a `”postinstall”:”patch-package”` in your `package.json` file (you need this so the next time you install a package or when you clone the repo, the patch will be applied automatically)

**Comment by amirduran** [comment]
Ok, great! Thank you for your help.

**Comment by Oleh-pryma** [comment]
I fixed this. Find file Composer.js in node_modules/react-native-gifted-chat/lib. Replace TextInput from react native, to TextInput  from  react-native-gesture-handler. Save updates with npx patch-package react-native-gifted-chat or other way.
