### ISSUE TITLE
Anchor top of a large custom message to the top of the screen

### ISSUE THREAD

**Issue by markwindsorr** [FaridSafi/react-native-gifted-chat#2013]
#### Issue Description

Not really an issue but I have these custom messages whose height is greater than the screen. When I request one of these messages I cant find a way to start the top of the message with the top of the screen. 

The top of the message is always above and I have to scroll up to see the top.

**Comment by efstathiosntonas** [comment]
Hey @markwindsorr if you found a solution it would be great if you post a comment with it instead of just closing the issue as another dev might encounter the same. Thanks

**Comment by markwindsorr** [comment]
Thought I found a solution but I did not.
