### ISSUE TITLE
No option to add styles for chat text.

### ISSUE THREAD

**Issue by sunnychevli** [FaridSafi/react-native-gifted-chat#2015]
If I just wanted to add text style for text inside bubble. I didn't find any props for that. Basically I want to change font of text. 

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by efstathiosntonas** [comment]
you can style your text as follows:

```
<Bubble
textStyle={{
          left: {
            color: "white",
            fontWeight: "500",
            paddingLeft: 8,
            paddingRight: 8,
            paddingTop: 8,
            fontSize:  18
          },
          right: {
            color: "black",
            fontWeight: "500",
            paddingLeft: 8,
            paddingRight: 8,
            paddingTop: 8,
            fontSize:  18
          }
        }}
/>
```

**Comment by sunnychevli** [comment]
Thank you. This works.

**Comment by efstathiosntonas** [comment]
You’re welcome @sunnychevli, please don’t forget to close the issue!
