### ISSUE TITLE
Does bottomOffset do anything?

### ISSUE THREAD

**Issue by jascination** [FaridSafi/react-native-gifted-chat#2016]
#### Issue Description

Using the latest gifted chat, I'm rendering a custom composer (I'm making a chatbot that doesn't allow text input, just canned button responses).

My composer height will be anywhere from 100 - 300px, and I want to push the chat 'up' so it's all visible above the composer window.

I'm trying to use the `bottomOffset` param, like:

```
    <GiftedChat
      messages={messages}
      onSend={(messages) => onSend(messages)}
      user={currentUser}
      renderComposer={Composer}
      bottomOffset={300}
    />
```

Yet no matter what I change `bottomOffset` to, it does nothing. I've also tried doing this without a custom composer, and it still yields no results

I could just be dumb, but I've looked in the RN Gifted Chat repo and I can see `bottomOffset` defined in typescript, but can't see it actually being called anywhere. 

So: What's the correct way to change the height of the chat stream in which the message bubbles appear? I basically just want a dynamically larger composer and to be able to make the chat stream sit neatly above it.

**Comment by mariomurrent-softwaresolutions** [comment]
On which platform are you testing? Android or iOS?

**Comment by jascination** [comment]
IOS

**Comment by mariomurrent-softwaresolutions** [comment]
Have you tried negative values as well? This works fine for me

**Comment by jascination** [comment]
Nope, it literally does nothing no matter what value I put in.

Maybe I'm expecting it to do something than it's meant to do?

**Comment by mariomurrent-softwaresolutions** [comment]
https://snack.expo.io/80dgP2nmO

The bottom offset will only be taken into account, when the keyboard is open.

**Comment by jascination** [comment]
Got it. Maybe we need to update the readme documentation, as this is very unclear:

`bottomOffset (Integer) - Distance of the chat from the bottom of the screen (e.g. useful if you display a tab bar)`


I read this as... literally as written, "Distance of the chat from the bottom of the screen". Nothing here states that the keyboard must be open. Cheers for your help!

**Comment by mariomurrent-softwaresolutions** [comment]
I had the same issue. Yeah maybe the documentation needs to be updated, or the implementation of this is not meant to be only working when the keyboard is open.
