### ISSUE TITLE
Keyboard's Inbuilt Emoji List Not Opening

### ISSUE THREAD

**Issue by thevijaysoni** [FaridSafi/react-native-gifted-chat#2018]
#### Issue Description

I am adding gifted chat to a project and when i press on emoji icon of keyboard then it opens the emoji list but in few moment its closes.

#### Expected Results

Emoji list should remain and let user select emojis

#### Additional Information

* React version: 16.9.0
* React Native version: 0.61.5
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): Android

https://user-images.githubusercontent.com/53553383/111617583-4fcf4900-8809-11eb-92d5-a912e10bc25f.mp4

**Comment by Xubaer** [comment]
I am still facing this issue, is there any solution?

**Comment by brunodias28** [comment]
same issue here.
hey @thevijaysoni, did you find any workaround ?
