### ISSUE TITLE
On Load Earlier messages, the list auto scroll to bottom

### ISSUE THREAD

**Issue by msulaiman119** [FaridSafi/react-native-gifted-chat#2019]
#### Issue Description

Disable auto scroll
I want to disable auto scroll to bottom when user click on load earlier messages.

#### Steps to Reproduce / Code Snippets

Scroll up and when you see load earlier messages
Click on LoadEarlier messages

#### Expected Results

List Should not scroll to bottom on scroll earlier messages.

#### Additional Information

* React version: 16.13.1
* React Native version: 0.63.3
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): Both

**Comment by lingxiao-Zhu** [comment]
I solved this problem by hack:

- Delete node_modules react-native-gifted-chat code

![image](https://user-images.githubusercontent.com/22609330/112726692-bd8e1a00-8f59-11eb-8e48-884a6ca48742.png)

- Call scrollToBottom by myself

```javascript
useEffect(() => {
    setTimeout(() => {
      msgContainerRef.current.scrollToBottom(false);
    }, 200);
  }, [chats]);

// when chats array changed, excute scrollToBottom method
```

**Comment by leonardo-weber** [comment]
I've managed to solve this problem by adding lines 251 and 252 on GiftedChat.js

It does not appear to have affected any other behaviors other than the one i wished to change 

![Screenshot 2023-11-17 at 11 35 18](https://github.com/FaridSafi/react-native-gifted-chat/assets/89230082/9223c7a0-13b1-4cff-998c-3f3da5ca3bdc)
