### ISSUE TITLE
Add callback when GiftChat is initialized

### ISSUE THREAD

**Issue by slamacchia** [FaridSafi/react-native-gifted-chat#2020]
#### Issue Description

Add callback function when GiftChat is initialized.

If there is already a mechanism for this, please let me know?

Problem: I want to set the 'isTyping' state to 'true', once GiftChat initialized, to show the TypingIndicator animation for the user. Basically I want the user to see something is happening, while messages are fetched from a server.

#### Steps to Reproduce / Code Snippets

Example code to demonstrate problem:
```typescript
const Chat = () => {
   const [isTyping, setIsTyping] = useState<boolean>(false);

   // Callback on focus (react navigation hook. Work the same as listening for 'focus' event in useEffect())
   useFocusEffect(
     useCallback(() => {
       // this is being called before GiftedChat is initialized and is being ignored
       setIsTyping(true);

       }, []),
    );

....

  // Hack override for web. TypingIndicator returns null for web?
  // see: https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/MessageContainer.tsx#L149
  const renderFooter = (props) => {
    return <TypingIndicator isTyping={isTyping} />;
  };

  return (
      <GiftedChat
        messages={messages}
        user={user}
        isTyping={isTyping}
        renderFooter={renderFooter}
      />
  );
};
export default Chat;
```

#### Expected Results

Ideally 'isTyping' would take affect on GiftChat initialization. Otherwise adding a callback so I can do my custom logic would be the next best thing.

#### Additional Information

* Nodejs version: 14.15.5
* React version: 16.13.1
* React Native version: 0.63
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): web (react native web)
* TypeScript version: 4.0.0

**Comment by fukemy** [comment]
hi did u solved this?
