### ISSUE TITLE
Copy picture from chat

### ISSUE THREAD

**Issue by matthieup240** [FaridSafi/react-native-gifted-chat#2022]
#### Issue Description

Hi,

I'm trying to copy a picture from a chat. Is it possible ?
The main objectif is to share a picture from a chat to an another chat.

Actually, when I'm using the "onLongPress" function on the picture, nothing append. And if I using "onLongPress" on the bubble, get the web url (message.image).
Maybe it's better to get the local path ?
Do you have some ideas ? 

Thanks

**Comment by efstathiosntonas** [comment]
You could use `react-native-file-access`, it supports fetching images from url for both Android & iOS. 

You should use a custom `renderImage` component and handle the `onLongPress` inside there, ie present a bottom sheet with the option to download the image (so then user can upload it to another room) or display a bottom sheet with a flatlist with all the available chat rooms of the user, user should be able to select the room he wants to share with and a “forward image” button. When user taps the button, download the image in the background and then create a new message with that image for the selected chat room.

Don’t forget to delete the image after you download it if you need to

**Comment by tux240** [comment]
That's cool !! Thanks.

Is it not possible to copy the fetched image and past it to an another room instead of using a bottom sheet with the full list of available rooms ?

**Comment by efstathiosntonas** [comment]
You could use `react-native-share`, it provides a `Copy` option, at least on iOS
