### ISSUE TITLE
is there a method to do text to speech (TTS) for bot's response? 

### ISSUE THREAD

**Issue by tao-bi** [FaridSafi/react-native-gifted-chat#2024]
#### Issue Description

[Does this library have a function to do text to speech (TTS) when a bot sending response? ]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by Sravansuhas** [comment]
You can achieve this by externally adding TTS liberty. Look at this [https://github.com/ak1394/react-native-tts](url)
