### ISSUE TITLE
how to implement reply message for particular message?

### ISSUE THREAD

**Issue by devHybrid0306** [FaridSafi/react-native-gifted-chat#2028]
#### Issue Description

Replying message is one of main feature in implementing.
But I was stuck on journey for implementing reply message.

I know there are tons of parameters to customize message.
is there way to implement reply message using current parameters?

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

I want to see reply input by click particular message or swiping particular message.
And, after replying, I want to see replying message component

**Comment by apappas1129** [comment]
No current reply functionality in this component library.

**Comment by efstathiosntonas** [comment]
Here’s a gist: https://gist.github.com/myckhel/d88af0d6a328f61b8023b48fe25639fe

reference: https://github.com/FaridSafi/react-native-gifted-chat/pull/1775#issuecomment-806882431

**Comment by myckhel** [comment]
I got a message from someone asking to implement the reply.
so i have done that using expo's snack
here is the link: https://snack.expo.io/@myckhel/react-native-gifted-chat-reply

i hope it helps
