### ISSUE TITLE
How to remove background Container in case of Only Image Message

### ISSUE THREAD

**Issue by SubhashisPK** [FaridSafi/react-native-gifted-chat#2036]
#### Issue Description

How to remove background Container in case of Only Image Message

![Screenshot 2021-04-15 at 12 07 53 PM](https://user-images.githubusercontent.com/30040224/114824944-365af600-9de3-11eb-9c96-c5df9fc934de.png)

I just want to remove background Container of Image, it should show the just image, please help

**Comment by efstathiosntonas** [comment]
You will have to use a custom Bubble:

```


  const BubbleChat = (bubble: any) => {
    return (
      <Bubble
        {...bubble}
                 wrapperStyle={{
          left: {
            backgroundColor: bubble?.currentMessage?.audio
              ? themeContext.chatScreen.audioPlayer.left.leftBubble
              : !bubble?.currentMessage?.image || !bubble?.currentMessage.messageImage
              ? themeContext.chatScreen.leftBubble
              : "transparent",
            borderWidth: bubble?.currentMessage?.image ? 2 : 0,
            borderColor:
              theme.mode === "dark"
                ? themeContext.chatScreen.chatInputBackground
                : "transparent",
            borderBottomLeftRadius: bubble?.position === "left" ? 0 : 10,
            borderBottomRightRadius: bubble?.position === "right" ? 0 : 10,
            borderTopLeftRadius: 10,
            borderTopRightRadius: 10,
            marginBottom: 10
          },
          right: {
            backgroundColor: bubble?.currentMessage?.audio
              ? themeContext.chatScreen.audioPlayer.right.rightBubble
              : !bubble?.currentMessage?.image || !bubble?.currentMessage?.messageImage
              ? themeContext.chatScreen.rightBubble
              : "transparent",
            borderWidth: bubble?.currentMessage?.image ? 2 : 0,
            borderColor:
              theme.mode === "dark"
                ? themeContext.chatScreen.chatInputBackground
                : "transparent",
            borderBottomLeftRadius: bubble?.position === "left" ? 0 : 10,
            borderBottomRightRadius: bubble?.position === "right" ? 0 : 10,
            borderTopLeftRadius: 10,
            borderTopRightRadius: 10,
            marginBottom: 30,
            padding: 0
          }
          
// rest of the props like renderTime etc
/>

<GiftedChat
 renderBubble={BubbleChat}
 />
```

Play around with margins etc to suit your needs. You also might pass a custom Image component so you can also play with margins.  If you need further info let me know. I ll post a complete solution tomorrow

this is what you’ll get:
![EAD71BB0-7960-4EE3-8B8C-885E4D2D860E](https://user-images.githubusercontent.com/717975/114918036-4c8ea380-9e2f-11eb-8226-7f3e37d08c97.png)

**Comment by SubhashisPK** [comment]
@efstathiosntonas thanks you very much for reply, your solution worked fine but it lead me to another problem. 
![Screenshot 2021-04-16 at 3 41 08 PM](https://user-images.githubusercontent.com/30040224/115009685-2a962f00-9eca-11eb-8b89-d4a618de33c8.png)
This is exactly, what I needed, thanks.

here is my code;
``

**Comment by efstathiosntonas** [comment]
Add one more ternary operator, but you’ll need to discriminate the Image + Text message from the other types of messages somehow (like you’re doing with images)

**Comment by SubhashisPK** [comment]
Thanks you Very musch @efstathiosntonas, added more ternary operator and its worked fine, closing the Issue.
