### ISSUE TITLE
TextInput jumps when keyboard is opened

### ISSUE THREAD

**Issue by g1un** [FaridSafi/react-native-gifted-chat#2037]
#### Issue Description

TextInput jumps when keyboard is opened

#### Steps to Reproduce / Code Snippets

Just use example (https://github.com/FaridSafi/react-native-gifted-chat#example) in iPhone 12 Pro Max - iOS 14.4 Simulator

#### Expected Results

TextInput does not jump

#### Additional Information

Video

https://user-images.githubusercontent.com/13907881/114887490-2bb75580-9e11-11eb-89d2-827d5f73f960.mov

**Comment by efstathiosntonas** [comment]
Duplicate of https://github.com/FaridSafi/react-native-gifted-chat/issues/1888

**Comment by efstathiosntonas** [comment]
@g1un if the issue is resolved, don't forget to close it.

**Comment by g1un** [comment]
@efstathiosntonas Thank you for link.
I can't say that it is entirely solved, but playing with `bottomOffset` for iOS platform is enough good workaround. So ok.
