### ISSUE TITLE
Discussion with multi users 

### ISSUE THREAD

**Issue by Wendy-M** [FaridSafi/react-native-gifted-chat#2041]
#### Issue Description

I wondering if with his module we can create a chat with more than 2 people ? 

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by fdub-ii** [comment]
Sure,
as long as you fill the user prop with the current user info, every message will be displayed either left or right with proper avatar/initials.
