### ISSUE TITLE
[iOS] If you scroll fast to the top onLoadEarlier is not invoked

### ISSUE THREAD

**Issue by kalek** [FaridSafi/react-native-gifted-chat#2048]
#### Issue Description

If you scroll to the top slowly all works good but if you scroll very fast then onLoadEarlier is not invoked

#### Steps to Reproduce / Code Snippets

`        <GiftedChat
          messages={mapMessages(messages)}
          loadEarlier
          onLoadEarlier={loadMoreMessages}
          renderLoadEarlier={() => {
            return isLoadingEarlier ? (
              <View style={{ marginBottom: 20, marginTop: 10 }}>
                <ActivityIndicator />
              </View>
            ) : null;
          }}
          infiniteScroll`

#### Expected Results

onLoadEarlier should be invoked

#### Additional Information

* Nodejs version: v14.15.4
* React version: 16.13.1
* React Native version: 0.63.3
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): iOS 14.4.2
* TypeScript version: no typescript

**Comment by raymondpebble** [comment]
Commenting to say I'm also still seeing this issue

**Comment by phamthang03** [comment]
same issue here
