### ISSUE TITLE
App crashes when Key slides open

### ISSUE THREAD

**Issue by satyagupta** [FaridSafi/react-native-gifted-chat#205]
Hello @FaridSafi, Thanks for this great component. We are making and app and this component has been of a great help for us. 

We are facing a problem: 

When keyboard is open i get this error: http://grab.by/S9ZO

I had a similar problem with one of my other project and doing this solved the problem

`keyboardWillShow: function (e) {`
`    if(!e.endCoordinates) return; //THIS LINE FIXED THE PROBLEM `
`    var newSize = SCREEN_HEIGHT - 69 - e.endCoordinates.height;`
`    this.setState({visibleHeight: newSize})`
`  }`

If i add the same thing in GifteChat.js in function onKeyboardWillShow in line 191
`if(!e.endCoordinates) return;`
It would works fine.

But else it crashes the app, Any idea why its happening?

**Comment by FaridSafi** [comment]
Hello @satyagupta
can you try this please

```js
this.setKeyboardHeight(e.endCoordinates ? e.endCoordinates.height : e.end.height);
```

**Comment by satyagupta** [comment]
This would be inside the GiftedChat.js file right?

**Comment by FaridSafi** [comment]
yes

**Comment by satyagupta** [comment]
That fixed the issue Thanks 👍  :)

One more thing how can we style the message bubble color? I tried a lot but gives error every time :(

**Comment by FaridSafi** [comment]
You can check https://github.com/FaridSafi/react-native-gifted-chat/blob/master/example/App.js#L161

**Comment by satyagupta** [comment]
Thanks can you update the change and push or should i change in local file?

**Comment by FaridSafi** [comment]
you can change locally until I publish 0.0.9

**Comment by satyagupta** [comment]
No problem. Closing this for now 👍
