### ISSUE TITLE
How can I hide the input Field?

### ISSUE THREAD

**Issue by AkashSarkar** [FaridSafi/react-native-gifted-chat#2056]
I need to hide the Input filed for blocked members and other use cases. Is there any way to hide the input field?

**Comment by ZiggerZZ** [comment]
for future readers: `renderInputToolbar={null}` doesn't work but `renderInputToolbar={() => null}` does the job

**Comment by doublethefish** [comment]
I found the following worked:

```
        renderComposer={()=>null}
        minInputToolbarHeight={0}
```
