### ISSUE TITLE
how to scroll to any message index

### ISSUE THREAD

**Issue by AymanAlqoqa** [FaridSafi/react-native-gifted-chat#2057]
#### Issue Description

need to scroll to any message index in the Chat...  how can I pass onScrollToIndexFailed Flatlist prop into Gifted Chat???!!!!

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [v14.13.0]
* React version: [16.13.1]
* React Native version: [ 0.63]
* react-native-gifted-chat version: [^0.16.3]
* Platform(s) (iOS, Android, or both?): [both]
* TypeScript version:

**Comment by rjacoby15** [comment]
Hi, this is what is working for me: 

my gifted chat ref: 

 <GiftedChat
ref={(component) => (this.chatListView = component)}
.........
/>

my onPress to scroll to my message index:

this.chatListView._messageContainerRef.current.flatListRef.current.scrollToIndex({index: index, animated: true})

**Comment by gagansh7171** [comment]
this.chatListView.current._messageContainerRef.current.scrollToIndex({index: i, animated: true});

Worked for me

**Comment by Hermanyo** [comment]
How about highlighting message after scroll to ?

**Comment by djamper103** [comment]
> Hi, this is what is working for me:
> 
> my gifted chat ref:
> 
> <GiftedChat ref={(component) => (this.chatListView = component)} ......... />
> 
> my onPress to scroll to my message index:
> 
> this.chatListView._messageContainerRef.current.flatListRef.current.scrollToIndex({index: index, animated: true})

Hi, can you tell us a little more about this, onPress doesn’t work for me in the chat?It is not clear what to hang the event
