### ISSUE TITLE
Bubble message text color does not dynamically change

### ISSUE THREAD

**Issue by husam-qb** [FaridSafi/react-native-gifted-chat#2060]
#### Issue Description
 
MessageText color does not dynamically change when changing the color property on the Bubble component.

#### Steps to Reproduce / Code Snippets

```javascript

const renderBubble = (props) => {
    // theme is a hook that updates the colors based on the device's colorScheme value ('light' or 'dark'). 
    const { theme } = useTheme();
    
    return (
      <Bubble
        {...props}
        wrapperStyle={{
          left: { backgroundColor: theme.colors.bubble }, // Changes dynamically 
          right: { backgroundColor: theme.colors.bubble }, // Changes dynamically
        }}
        renderMessageText={(props) => {
          return (
            <MessageText
              {...props}
              textStyle={{
                left: { color: theme.colors.white }, // Does not change dynamically
                right: { color: theme.colors.white },
              }}
            />
          );
        }}
      />
    );
  };
```

#### Expected Results

The text should change its color (re-render the component). For example, `theme.colors.white` is white when the colorScheme is 'light' and black when the colorScheme is 'dark'. 

Testing this with the background color property for the Bubble component and it works fine if we provide `shouldUpdateMessage={() => true}`. However, no matter what we tried (e.g. adding `theme` property to `extraData` prop) the color property of MessageText does not change.

#### Additional Information

* Nodejs version: v15.14.0
* React version: 16.13.1
* React Native version: Expo's latest for SDK 41
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: N/A

**Comment by husam-qb** [comment]
Solved this issue by implementing our own MessageText component as a hook. The problem seems to be with the `componentShouldUpdate` function does not get executed when `shouldUpdateMessage` returns true. It only propagates down to the Bubble component. 

We prefer that this is fixed in the library so we don't have to maintain our own custom component.

**Comment by 345ml** [comment]
Same issue with renderComposer

**Comment by fukemy** [comment]
hi can u provide some codes?

**Comment by visaals** [comment]
Just ran into the same issue when trying to implement dark mode. Did you create a custom implementation of the `MessageText`?

**Comment by mvolonnino** [comment]
also running into this issue, only the first message changes color, the rest do not dynamic change when the theme updates

**Comment by sachinbarupal** [comment]
Need to change bubble dynamically, like if a like a message it should re render...Does anyone know how to achieve this ?
