### ISSUE TITLE
Add images to composer for preview before sending

### ISSUE THREAD

**Issue by ayesha-we-over-i** [FaridSafi/react-native-gifted-chat#2064]
#### Expected Results

<img width="688" alt="Screenshot 2021-06-14 at 1 46 58 PM" src="https://user-images.githubusercontent.com/80894781/121865088-ffd42580-cd16-11eb-81d3-6baba266da26.png">

I know how to display them from URI in a message once they are sent, but I would like to give users this option too.

**Comment by kane-toomer** [comment]
Hello,

Did you ever figure this out?

**Comment by MeesterMarcus** [comment]
Interested in this as well

**Comment by christopher-caldwell** [comment]
@ayesha-we-over-i Did you ever implement this?

**Comment by humayunkabir** [comment]
@Johan-dutoit Is there any way to preview the image before sending in this library?
