### ISSUE TITLE
Actions Button Location

### ISSUE THREAD

**Issue by ddikodroid** [FaridSafi/react-native-gifted-chat#2068]
#### Issue Description

I've successfully create the input toolbar, but I need a little more step to make it the same as the design. How to move the actions button to the left of send button?

Right now it looks like this
<img width="440" alt="Screen Shot 2021-07-02 at 12 42 49" src="https://user-images.githubusercontent.com/4207774/124226443-51601b00-db33-11eb-8bb9-e3729a380811.png">

#### Steps to Reproduce / Code Snippets

```
  const renderSend = (props) => (
    <Send {...props} containerStyle={styles.sendBtn}>
      <Image
        source={image.sendButton}
        style={styles.sendBtnImg}
        resizeMode='contain'
      />
    </Send>
  )
  const renderInputToolbar = (props) => (
    <InputToolbar
      {...props}
      containerStyle={styles.inputToolbarCont}
    />
  )
  const renderComposer = (props) => (
    <Composer {...props} textInputStyle={styles.textInput} />
  )
  const renderActions = (props) => (
    <>
      <Actions
        {...props}
        icon={() =>
          <Image
            source={image.sendDoc}
            style={styles.actionBtn}
            resizeMode='contain'
          />}
        onPressActionButton={() => console.log('Doc')}
      />
      <Actions
        {...props}
        icon={() =>
          <Image
            source={image.sendImage}
            style={styles.actionBtn}
            resizeMode='contain'
          />}
        onPressActionButton={() => console.log('Image')}
      />
    </>
  )
 ...
    <GiftedChat
      messages={messages}
      onSend={messages => onSend(messages)}
      renderSend={renderSend}
      renderInputToolbar={renderInputToolbar}
      renderComposer={renderComposer}
      renderActions={renderActions}
      renderChatFooter={renderChatFooter}
      alwaysShowSend
      bottomOffset={insets.bottom}
      placeholder='Send a message...'
      isKeyboardInternallyHandled={false}
      user={{
        _id: 1
      }}
    />
```

#### Expected Results

<img width="459" alt="Screen Shot 2021-07-02 at 12 42 37" src="https://user-images.githubusercontent.com/4207774/124226544-81a7b980-db33-11eb-8b12-4ab58f965f32.png">

#### Additional Information

* Nodejs version: 14.15.4
* React version: 17.0.1
* React Native version: 0.64
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: -

**Comment by jackwullems** [comment]
There is my solution below.
    const renderInputToolbar = (props: InputToolbarProps)=>{
        return (
            <View
                style={{
                    position: 'absolute',
                    bottom: 0,
                    left: 0, 
                    right: 0,
                    backgroundColor: colors.lightGrayContour,
                    // borderColor: 'red',
                    // borderWidth: 1,
                    flexDirection: 'row',
                    alignItems: 'center',
                    justifyContent: 'center',
                    paddingVertical: HEIGHT(8),
                    paddingHorizontal: WIDTH(16)}}>
                <Send
                    {...props}
                    containerStyle={{justifyContent: 'center', marginBottom: 0}}
                    >
                    <Image source={images.send} style={{height: WIDTH(32), width: WIDTH(32)}}/>
                </Send>
                <Composer {...props}
                    textInputProps={{textAlign: 'right'}}
                    textInputStyle={{backgroundColor: 'white', paddingHorizontal: WIDTH(10), borderRadius: WIDTH(20)}}
                />
                <Actions
                    containerStyle={{marginBottom: 0, justifyContent: 'center',
                    //  borderWidth: 1, borderColor: 'red'
                    }}
                    icon={()=><Icon name='add' color={colors.eegudMainColor}/>}
                />
            </View>
        )
    }

            <GiftedChat
                messages={messages}
                alwaysShowSend={true}
                renderInputToolbar={renderInputToolbar}
             />

**Comment by ddikodroid** [comment]
> There is my solution below.
> 
> ```
>     const renderInputToolbar = (props: InputToolbarProps)=>{
>         return (
>             <View
>                 style={{
>                     position: 'absolute',
>                     bottom: 0,
>                     left: 0, 
>                     right: 0,
>                     backgroundColor: colors.lightGrayContour,
>                     // borderColor: 'red',
>                     // borderWidth: 1,
>                     flexDirection: 'row',
>                     alignItems: 'center',
>                     justifyContent: 'center',
>                     paddingVertical: HEIGHT(8),
>                     paddingHorizontal: WIDTH(16)}}>
>                 <Send
>                     {...props}
>                     containerStyle={{justifyContent: 'center', marginBottom: 0}}
>                     >
>                     <Image source={images.send} style={{height: WIDTH(32), width: WIDTH(32)}}/>
>                 </Send>
>                 <Composer {...props}
>                     textInputStyle={{backgroundColor: 'white', paddingHorizontal: WIDTH(10), borderRadius: WIDTH(20)}}
>                 />
>                 <Actions
>                     containerStyle={{marginBottom: 0, justifyContent: 'center',
>                     //  borderWidth: 1, borderColor: 'red'
>                     }}
>                     icon={()=><Icon name='add' color={colors.eegudMainColor}/>}
>                 />
>             </View>
>         )
>     }
> 
>             <GiftedChat
>                 messages={messages}
>                 alwaysShowSend={true}
>                 renderInputToolbar={renderInputToolbar}
>              />
> ```

Thank you😁
