### ISSUE TITLE
Using ActionSheet with react-native-gifted-chat example.

### ISSUE THREAD

**Issue by juandaserni** [FaridSafi/react-native-gifted-chat#208]
Hi, react-native-gifted-chat example works fine on iOS and Android.

I am trying to use gifted messenger example with react-native-router-flux.
It works fine on iOS. But on Android I get this follow error when I push renderActions button:

![screen shot 2016-08-17 at 10 01 43 am](https://cloud.githubusercontent.com/assets/3142824/17741728/ed7b586c-6462-11e6-9b32-ad4aedb63930.png)

![screen shot 2016-08-17 at 9 53 35 am](https://cloud.githubusercontent.com/assets/3142824/17741729/f0cf8d8a-6462-11e6-960e-d568ebfb5dea.png)

Any tips to solve this?

**Comment by FaridSafi** [comment]
are you using gifted-chat 0.0.8 ?

**Comment by FaridSafi** [comment]
be sure that you installed last version of `@exponent/react-native-action-sheet` package

**Comment by juandaserni** [comment]
Yes! I'm using gifted-chat 0.0.8 and I have installed latest version of @exponent/react-native-action-sheet package. I feel that's it is something wrong with react-native-router-flux navigation but I'm not sure. The error is not that helpful. 

Kind of a conflict between actionsheets and  react-native-router-flux I guess : (

**Comment by FaridSafi** [comment]
I experienced a similar issue in the past,
I had to pass `{useNativeDriver: false}` to `Animated.timing()` calls as second param

Hope this helps

**Comment by juandaserni** [comment]
It worked!!! Thx a lot!  👍  

:D

**Comment by FaridSafi** [comment]
you modified in what package?

**Comment by juandaserni** [comment]
@exponent/react-native-action-sheet. ActionSheet.android.js file.

Just like you said. I set "useNativeDriver: false" in Animated.timing().

**Comment by FaridSafi** [comment]
this issue should be fixed in `@exponent/react-native-action-sheet` version `0.2.1`

**Comment by FaridSafi** [comment]
@juandaserni you can upgrade GiftedChat to 0.0.10 to fix this issue

**Comment by kfiroo** [comment]
This issue is still open with `@exponent/react-native-action-sheet` https://github.com/exponentjs/react-native-action-sheet/issues/15
