### ISSUE TITLE
NPM need new publish to get latest code

### ISSUE THREAD

**Issue by joartola** [FaridSafi/react-native-gifted-chat#2080]
#### Issue Description

NPM last publish is one year ago
There are commits 6 months ago.

#### Steps to Reproduce / Code Snippets

Try to use render message audio and render message video.
               
#### Expected Results

Unable to use these methods since there is no new npm publish.

**Comment by rf1804** [comment]
@FaridSafi Please release with new code

**Comment by ajp8164** [comment]
Are there steps I can take to create a release locally (without having to publish to npm)?

**Comment by rf1804** [comment]
> Are there steps I can take to create a release locally (without having to publish to npm)?

@ajp8164 
Just replace version to github link in the package.json file

Like this

"r̶e̶a̶c̶t̶-̶n̶a̶t̶i̶v̶e̶-̶g̶i̶f̶t̶e̶d̶-̶c̶h̶a̶t̶":̶ "^̶0̶.1̶6̶.3̶"
`"react-native-gifted-chat": "https://github.com/rf1804/react-native-gifted-chat"`
