### ISSUE TITLE
Text Formatting and Styling

### ISSUE THREAD

**Issue by Datathecodie** [FaridSafi/react-native-gifted-chat#2083]
#### Issue Description

Based on the documentation, I'm unable to find a text formatting option for chat. (Ex. for **bold**, _italics_, strikethrough)

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by thecookieorg** [comment]
Any suggestions here?
