### ISSUE TITLE
Keyboard.removeListener is not a function

### ISSUE THREAD

**Issue by mustafauyysl** [FaridSafi/react-native-gifted-chat#2090]
![Simulator Screen Shot - iPhone 12 - 2021-08-19 at 12 55 38](https://user-images.githubusercontent.com/41873800/130048825-9abf6a6b-b51d-4f5d-9061-4e4f880e0684.png)

Hello I started getting this error after the last update of react native because the removeListener function was removed in the last update.

**Comment by mustafauyysl** [comment]
I updated package and done

**Comment by horo42** [comment]
in MessageContainer.js constructor

```diff
this.attachKeyboardListeners = () => {
    const { invertibleScrollViewProps: invertibleProps } = this.props;
    if (invertibleProps) {
-        Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
-        Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
-        Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
-        Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
    }
};
this.detachKeyboardListeners = () => {
    const { invertibleScrollViewProps: invertibleProps } = this.props;
-    Keyboard.removeListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
-    Keyboard.removeListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
-    Keyboard.removeListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
-    Keyboard.removeListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
};
```

you can apply this fix with https://github.com/ds300/patch-package until the maintainers fix this

**Comment by kundankarna1994** [comment]
![Screenshot_20210824-121457_SwissBot](https://user-images.githubusercontent.com/52775829/130567458-48c4c893-4645-4c0d-b3dc-846f1fb16f0f.jpg)

I tried the above code and its throwing above error

**Comment by horo42** [comment]
I updated my answer, adding optional chaining operators to the remove() method calls. That should fix your issue.

**Comment by marister** [comment]
Anyone knows whats the status of this?
Is there a PR open for this?
can someone merge it please? 😄 👯 💘

**Comment by adhip94** [comment]
@xcarpentier Is it possible to do a quick release with a fix as this issue is affecting all users on RN 0.65 and above?

**Comment by mrcustodio** [comment]
Yep, I'm on the same boat... Every time having to manually change the listener to remove the errors...

**Comment by morphytron** [comment]
Receiving same issue on latest release.

**Comment by mrshahzeb7** [comment]
facing this issue when logout from chat screen (after upgrading all libraries)

**Comment by intechsol143** [comment]
> ![image](https://user-images.githubusercontent.com/19627226/130924359-caf4d094-0876-41b3-aaaa-3be8f20a6666.png)
> Changer to

Thank you very much

**Comment by anwersolangi** [comment]
@horo42 after updating the MessageContainer file, i get the error node_modules\react-native-gifted-chat\lib\messagecontainer.js: cannot find module 'metro-react-native-babel-preset' I tried to update the package.json file and also tried to add metro-react-natiev-babel-preset in the package and comment out the transform in package json, cleared the npm cache, clean android project but nothing helped....

**Comment by PointlessSpike** [comment]
I've just tried Gifted Chat and come across this issue. Simplest possible implementation and I've only just installed it.
Any idea when it'll get resolved?

**Comment by adhip94** [comment]
I've already emailed @xcarpentier, he replied back acknowledging he would do a release. Not sure when though...

**Comment by 77TecShaeer** [comment]
can any one make fork of Repo ?  and make that edit

**Comment by Ludolapert** [comment]
Thank you for the follow up @adhip94!

Could we have an estimation of a release date for this fix @xcarpentier ?

**Comment by yasimoha** [comment]
hi has there been any progress? becuase im still facing this isssue.

**Comment by habovh** [comment]
@yasimoha and anyone needing a quick fix for production apps, you may apply the patch described by @horo42 here: https://github.com/FaridSafi/react-native-gifted-chat/issues/2090#issuecomment-901812607

**Comment by horo42** [comment]
> ![image](https://user-images.githubusercontent.com/19627226/130924359-caf4d094-0876-41b3-aaaa-3be8f20a6666.png)
> Changer to

This workaround **probably** pushes the same callback references to the listener callbacks array, and then instantly removes them, leaving the originals (from `attachKeyboardListeners`) attached. Which is **probably** fine, but you don't have to settle, you're already patching into node_modules anyway.



> @horo42 after updating the MessageContainer file, i get the error node_modules\react-native-gifted-chat\lib\messagecontainer.js: cannot find module 'metro-react-native-babel-preset' I tried to update the package.json file and also tried to add metro-react-natiev-babel-preset in the package and comment out the transform in package json, cleared the npm cache, clean android project but nothing helped....

Most likely an issue with the optional chaining operator. You can try to fix your config, fall back to if statements, or even `this.willShowSub && this.willShowSub.remove();`

**Comment by emendel** [comment]
Will this be fixed soon?

**Comment by emendel** [comment]
> in MessageContainer.js constructor
> 
> ```diff
> this.attachKeyboardListeners = () => {
>     const { invertibleScrollViewProps: invertibleProps } = this.props;
>     if (invertibleProps) {
> -        Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
> -        Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
> -        Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
> -        Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
> +        this.willShowSub = Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
> +        this.didShowSub = Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
> +        this.willHideSub = Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
> +        this.didHideSub = Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
>     }
> };
> this.detachKeyboardListeners = () => {
>     const { invertibleScrollViewProps: invertibleProps } = this.props;
> -    Keyboard.removeListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
> -    Keyboard.removeListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
> -    Keyboard.removeListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
> -    Keyboard.removeListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
> +    this.willShowSub?.remove();
> +    this.didShowSub?.remove();
> +    this.willHideSub?.remove();
> +    this.didHideSub?.remove();
> };
> ```
> 
> you can apply this fix with https://github.com/ds300/patch-package until the maintainers fix this

Could you make a PR with this change so they can merge it?

**Comment by calcazar** [comment]
Any updates on this?

**Comment by Biplovkumar** [comment]
Any update?

**Comment by Biplovkumar** [comment]
```
        this.attachKeyboardListeners = () => {
            const { invertibleScrollViewProps: invertibleProps } = this.props;
            if (invertibleProps) {
                this.willShowSub = Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
                this.didShowSub = Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
                this.willHideSub = Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
                this.didHideSub = Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
            }
        };
        this.detachKeyboardListeners = () => {
            const { invertibleScrollViewProps: invertibleProps } = this.props;
            this.willShowSub?.remove();
            this.didShowSub?.remove();
            this.willHideSub?.remove();
            this.didHideSub?.remove();
        };
        
```


just need to update these lines in **node_modules/react-native-gifted-chat/lib/MessageContainer.js**this file.
It is temporary solution.

**Comment by sheggietyn** [comment]
update

**Comment by mehdinourollah** [comment]
I still have this issue ...any update on patch?!
React Native version = 0.66.0

**Comment by meirav-s** [comment]
also me, Im waiting to the fix to be published.
any update on it?
its urgent...

**Comment by habovh** [comment]
I'm not sure a fix has been issued, so please remove the Stale label unless the event listeners have actually been updated.

**Comment by Johan-dutoit** [comment]
Closing as this is fixed in latest beta.

**Comment by DiegoFawr** [comment]
Fixed? No way.
