### ISSUE TITLE
onLoadEarlier doesn't call with momentum scroll iOS

### ISSUE THREAD

**Issue by iway1** [FaridSafi/react-native-gifted-chat#2091]
#### Issue Description

If you have an onLoadEarlier function set, it will only be called if there is an active drag gesture controlling the scroll view. If the user swipes upwards and the momentum of the scroll causes a scroll to the top of the screen, onLoadEarlier will not be called.

#### Steps to Reproduce / Code Snippets

Just set an onLoadEarlier function and do as I described.

#### Expected Results

onLoadEarlier should be called when top is reached regardless of whether it was a momentum scroll or not.

**Comment by endlesstech** [comment]
Same issue. not calling onLoadEarlier function when scrolling reach to top.

**Comment by ezequiel88** [comment]
Same issue. not calling onLoadEarlier function when scrolling to top
