### ISSUE TITLE
Disable avatar issue 

### ISSUE THREAD

**Issue by AntonBorovoi** [FaridSafi/react-native-gifted-chat#2093]
#### Issue Description

Avatar component is still rendering and taking space for upcoming messages even `renderAvatar={() => null}`

Is there a way to hide it?

![image](https://user-images.githubusercontent.com/23105330/130965445-c0da03d2-4469-48e7-aa24-20edb45bdd7d.png)

#### Additional Information
* React Native version: 0.64.2
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): both

**Comment by jgable** [comment]
I was able to subclass the default `Message` component to overcome the display of the empty avatar;

```typescript
import {
  GiftedChat,
  Message as GiftedChatMessage,
  MessageProps,
  Composer,
  ComposerProps,
  InputToolbar,
  InputToolbarProps,
  IMessage,
} from "react-native-gifted-chat";

// Subclass the existing Message
class NoAvatarMessage extends GiftedChatMessage {
  // This fixes an issue where blank avatars are rendered;
  // https://github.com/FaridSafi/react-native-gifted-chat/issues/2093
  renderAvatar() {
    return null;
  }
}

// Render custom blank avatar messages
const CustomMessage = (props: MessageProps<IMessage>): JSX.Element => (
  <SurveyMessagingNoAvatarMessage
    {...props}
  />
);

<GiftedChat
  messages={displayedMessages}
  onSend={onMessageSend}
  renderMessage={CustomMessage}
  user={user}
/>
```

Hope that helps someone else.

**Comment by mckim0408** [comment]
found something works on this issue.

`
showAvatarForEveryMessage={true}
renderAvatar={() => null}
`

this worked for me

**Comment by Bhavya0101** [comment]
I solved this issue by adding 

renderAvatar={() => null}

but it had a few glitches in the UI. So, it was solved by adding 

showAvatarForEveryMessage={true}

So that it renders avatar for every message and all of them are set to null.
