### ISSUE TITLE
Library not Compatible with React Native 0.65.1

### ISSUE THREAD

**Issue by Priiyam** [FaridSafi/react-native-gifted-chat#2094]
#### Issue Description

- react-native-gifted-chat library is not compatible with React Native 0.65.1

#### Steps to Reproduce / Code Snippets

- Upgrade react native project to 0.65.1 to reproduce the following error:

    TypeError: _reactNative.Keyboard.removeListener is not a function. (In '_reactNative.Keyboard.removeListener('keyboardWillShow', invertibleProps.onKeyboardWillShow)', '_reactNative.Keyboard.removeListener' is undefined)
    
    This error is located at:
          in MessageContainer (at GiftedChat.js:343)
          in RCTView (at View.js:32)
          in View (at GiftedChat.js:337)
          in RCTView (at View.js:32)
          in View (at GiftedChat.js:408)
          in RCTView (at View.js:32)
          in View (at ActionSheet/index.tsx:72)
          in RCTView (at View.js:32)
          in View (at ActionSheet/index.tsx:80)
          in ActionSheet (at ActionSheetProvider.tsx:31)
          in ActionSheetProvider (at GiftedChat.js:407)
          in RCTView (at View.js:32)
          in View (at SafeAreaView.js:41)
          in SafeAreaView (at GiftedChat.js:406)
        ...

#### Expected Results

- Should work normally with react native 0.65.1

#### Additional Information

* Nodejs version: v14.15.1
* React version: 17.0.2
* React Native version: 0.65.1
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): Both
* TypeScript version: NA

**Comment by rusakovic** [comment]
confirm

**Comment by java-james** [comment]
+1 
Looks like master doesn't include the listeners causing the issue. 
Only remainder is replaced with non deprecated API and looks like some were removed here:

https://github.com/FaridSafi/react-native-gifted-chat/commit/d76af9ff4eaddb5292f1c48dd89d983f1eaac7e6

Need a new release sometime after this?

**Comment by FaisalKhawaj** [comment]
I have tried react native gifted chat in react native 0.65 . but it is giving me the error. It was working fine in previous version . Can someone please tell me how to fix this ?

**Comment by rayhk6** [comment]
> I have tried react native gifted chat in react native 0.65 . but it is giving me the error. It was working fine in previous version . Can someone please tell me how to fix this ?

https://github.com/FaridSafi/react-native-gifted-chat/issues/2090 Please check if this helps

**Comment by FaisalKhawaj** [comment]
Yes, It worked now. 
This file was in nodemodules-giftedchat-messageContainer.js . 
Thank you so much
