### ISSUE TITLE
last message hidden by input

### ISSUE THREAD

**Issue by amanuell2** [FaridSafi/react-native-gifted-chat#2095]
![photo5857490383154559249](https://user-images.githubusercontent.com/23053777/131125615-d2850265-5238-410c-8819-d1519993d5fd.jpg)
#### Issue Description

when I try to type the last message will be hidden and it is happening on the Android device

#### Steps to Reproduce / Code Snippets

   export function Chat() {
  const [text, setText] = useState('');
  const [messages, setMessages] = useState([]);

  useEffect(() => {
    setMessages(initialMessages.reverse());
  }, []);

  const onSend = (newMessages = []) => {
    setMessages((prevMessages) => GiftedChat.append(prevMessages, newMessages));
  };

  return (
    <GiftedChat
      messages={messages}
      text={text}
      onInputTextChanged={setText}
      onSend={onSend}
      user={{
        _id: 1,
        name: 'Aaron',
        avatar: 'https://placeimg.com/150/150/any',
      }}
      alignTop
      alwaysShowSend
      scrollToBottom
      // showUserAvatar
      renderAvatarOnTop
      renderUsernameOnMessage
      bottomOffset={26}
      onPressAvatar={console.log}
      renderInputToolbar={renderInputToolbar}
      renderActions={renderActions}
      renderComposer={renderComposer}
      renderSend={renderSend}
      renderAvatar={renderAvatar}
      renderBubble={renderBubble}
      renderMessage={renderMessage}
      renderMessageText={renderMessageText}
      renderCustomView={renderCustomView}
      isCustomViewBottom
      forceGetKeyboardHeight={false}
      messagesContainerStyle={{ backgroundColor: 'transparent' }}
      parsePatterns={(linkStyle) => [
        {
          pattern: /#(\w+)/,
          style: linkStyle,
          onPress: (tag) => console.log(`Pressed on hashtag: ${tag}`),
        },
      ]}
    />
  );
};

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [v16.6.1]
* React version: [16.9.0]
* React Native version: [0.62.2]
* react-native-gifted-chat version: [^0.16.3]
* Platform(s) (iOS, Android, or both?): [android]
* TypeScript version: [FILL THIS OUT]

**Comment by shafna96** [comment]
<GiftedChat containerStyle={{position: "absolute", marginTop:15}} />

worked for me

**Comment by l2aelba** [comment]
Do something like…

```js
const renderMessage = (props) => {
    const isLastMessage = props.nextMessage && !props.nextMessage._id
    return (
      <Message
        {...props}
        containerStyle={{
          left: {
            marginBottom: !isLastMessage ? 0 : 20,
          },
          right: {
            marginBottom: !isLastMessage ? 0 : 20,
          },
        }}
      />
    )
  }
```

```html
<GiftedChat renderMessage={renderMessage} ... />
```

**Comment by Awais-khalid06** [comment]
Do this

<GiftedChat  minInputToolbarHeight={40}  />

**Comment by Awais-khalid06** [comment]
<GiftedChat minInputToolbarHeight={40} />

**Comment by Awais-khalid06** [comment]
<GiftedChat minInputToolbarHeight={40} />
