### ISSUE TITLE
Attachments and Send Buttons bellow input

### ISSUE THREAD

**Issue by BLOCKMATERIAL** [FaridSafi/react-native-gifted-chat#2104]
#### Attachments and Send Buttons bellow input!
Hi all, ran into this problem, thanks in advance for your help!

I want to add a button to add media and a button to send a message under the input, but I don't know how to do it properly, I didn't find the answer how to do it.

In the picture I showed how I want to display the elements.

### Example
[image link CLICK](https://user-images.githubusercontent.com/46076319/133109365-756b1973-6a44-44d8-828e-47070cf4bc72.png)

**Comment by jotilohana** [comment]
@BLOCKMATERIAL  how did you add attachment button in message input field?

**Comment by BLOCKMATERIAL** [comment]
@jotilohana 

```
        renderAccessory={props => {
          return (
            <CustomToolBar
              {...props}
              handleSendMes={handleSendMes}
            />
          );
        }}
```
