### ISSUE TITLE
 renderCustomView  shows unnecessary default msg, in addition to my custom view. 

### ISSUE THREAD

**Issue by rosnk** [FaridSafi/react-native-gifted-chat#2106]
i am trying to discard default msg shown by gifted chat on each messages, and show my custom view based on the props i have passed.

Problem: have managed to display my custom view but somehow, default msg is hanging at the bottom of the bubble.... how can i remove default msg and only show what i have in my custom view?

![Screen Shot 2021-09-14 at 20 03 35](https://user-images.githubusercontent.com/4213653/133277149-b36601a3-d04c-4662-8a1b-f9cdaf1ef7f6.png)

#### Expected Results
want to show only things i have in renderCustomView inside bubble. At present i have everything with extra default msg.

**Comment by ZuzooVn** [comment]
Did you try to set `text: ''` for this message?

**Comment by yslai95** [comment]
Don't think it is possible to do so without modify the library. The custom view is to add extra view on top or bottom of a Bubble. 
<img width="634" alt="image" src="https://user-images.githubusercontent.com/8406528/150814276-a603be01-544c-4a25-a1f6-1f4ff8c5f431.png">
