### ISSUE TITLE
Automatically scroll to the first unread message while listing

### ISSUE THREAD

**Issue by akhilsanker** [FaridSafi/react-native-gifted-chat#2107]
#### Issue Description

How to load the messages with a banner showing unread counts and showing the first unread message, if any, just like other chat UIs.

Also getting the following error while using `ref.current?._messageContainerRef?.current?.scrollToIndex({})`:

![Screenshot_1631795108](https://user-images.githubusercontent.com/32122016/133611752-a006a504-6395-40d2-a223-d09e16f8b948.png)

Tried `onScrollToIndexFailed`, but no effect.

Just need the same as in whatsapp or any other chat application does:

![whatsapp unread messages](https://user-images.githubusercontent.com/32122016/133612055-00c35c0b-37e6-451b-b849-04091592603e.png)

Is there any prop that I am missing to implement this functionality?

#### Steps to Reproduce / Code Snippets

Getting the crash while navigating and scroll to the first unread message index.

      const unreadMsgIndex = fetchMessages.findIndex((msg) => msg._id === unreadMessage._id);
      setTimeout(() => {
        scrollref.current?._messageContainerRef?.current?.scrollToIndex({
          animated: true,
          index: unreadMsgIndex
        });
      }, 1000);

Using firebase Cloud Firestore. 

#### Expected Results

To work like same in other message app, to show the unread messages first if any.

#### Additional Information

* Nodejs version: 15.14.0
* React version: 17.0.1
* React Native version: 0.64.0
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): 
   iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
* TypeScript version: 3.8.3

**Comment by eisodev** [comment]
> If you still haven't fixed it, this is how I did it
> 
> `listViewProps={{ onScrollToIndexFailed: scrollToIndexFailed }}`
> 
> and
> 
> `const scrollToIndexFailed = (info) => { const offset = info.averageItemLength * info.index; chatlistRef.current._messageContainerRef.current.scrollToOffset({ offset }); setTimeout(() => { chatlistRef.current._messageContainerRef.current.scrollToIndex({ index: info.index, animated: true, viewPosition: 0.5, }); }, 100); };`
> 
> What it does is in case of scrolling to a offscreen index, it recursively scrolls closer to the index until the item is finally rendered and scrollToIndex succeeds thus the fail methods is not called again

https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/MessageContainer.tsx
https://reactnative.dev/docs/flatlist#onviewableitemschanged

That prop doesn't exist on FlatList. So this won't do anything unfortunately!
