### ISSUE TITLE
That is the point. onSend should be triggered when clicking on it if we choose alwaysDisplay. That allows more customisation like sending images in some unique way.

### ISSUE THREAD

**Issue by jackwullems** [FaridSafi/react-native-gifted-chat#2108]
That is the point. onSend should be triggered when clicking on it if we choose alwaysDisplay. That allows more customisation like sending images in some unique way.

_Originally posted by @Marcados in https://github.com/FaridSafi/react-native-gifted-chat/issues/1835#issuecomment-648644694_

**Comment by jackwullems** [comment]
![image](https://user-images.githubusercontent.com/51687189/133736688-90f553aa-7969-4b84-84da-1884ecfacd39.png)
I have some customization to send image or video on chatting. but onSend doesn't work when click on the send button with empty string.

**Comment by Marcados** [comment]
@jackwullems I agree, this should work even with empty string. Anyway, the solution I have is to set the string as ' ' to enable onSend to be triggered. It will not send an empty message though.

**Comment by jackwullems** [comment]
The solution would be overriding send button.

> renderSend={props=>
>                     <Send
>                         {...props}
>                         containerStyle={{justifyContent: 'center', marginBottom: 0}}
>                         >
>                         {
>                             !props.text && attachedFiles.length>0?
>                             <Pressable
>                                 onPress={async ()=>{
>                                     if (loading) {
>                                         return
>                                     }
>                                 }}
>                             >
>                                 <Image source={images.send} style={{height: WIDTH(32), width: WIDTH(32)}}/>
>                             </Pressable>
>                             :
>                             <Image source={images.send} style={{height: WIDTH(32), width: WIDTH(32)}}/>
>                         }
>                     </Send>
>
