### ISSUE TITLE
`alignTop` messes up keyboard dismissing on empty space 

### ISSUE THREAD

**Issue by sutefan1** [FaridSafi/react-native-gifted-chat#2115]
#### Issue Description

When `alignTop` is `true` the keyboard dismiss only works for the area where a message is. If there are no or only a few messages and you tap on the empty space between the keyboard and the first message nothing happens.

#### Steps to Reproduce / Code Snippets

Use the example code with the one message only and add the flag `alignTop` to `<GiftedChat .... />`.

#### Expected Results

The keyboard should close on any tap outside of the keyboard area (besides the input field) as it does with `alignTop = {false}`.

#### Additional Information

* Nodejs version: v12.16.1
* React version: 16.13.1 
* React Native version: 0.63.4 
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): only tested on iOS
* TypeScript version: 3.9.7

**Comment by bneigher** [comment]
It also causes a weird UX when scrolling a chat with very little content in it.

**Comment by bneigher** [comment]
https://user-images.githubusercontent.com/4627728/137436685-20c00da1-4bd5-4477-8ee3-694dbf1dd076.mov

**Comment by HrideyReact** [comment]
> listViewProps={{ contentContainerStyle: { flexGrow: 1, justifyContent: "flex-end" } }}

Only working when keyboard is up, does not work when it is dismissed. Screen does not scroll

**Comment by Chryogenic** [comment]
This is still an issue :(
