### ISSUE TITLE
Is this repo maintained actively? 

### ISSUE THREAD

**Issue by cesarve77** [FaridSafi/react-native-gifted-chat#2116]
There are some important pull request.
There is not activity since 7 month ago.

**Comment by c-goettert** [comment]
I guess there is no news on this yet?

**Comment by c-goettert** [comment]
@FaridSafi could you maybe give a quick update on the maintenance status of this repo?

**Comment by c-goettert** [comment]
Almost half a year now but still no answer. @xcarpentier maybe you have some info about the maintenance status of this repo? If it its not actively maintained anymore, I think there should be at least a clear statement about it on top of the Readme file. Maybe this way you will find someone who would like to continue this project or create a maintained fork.

**Comment by JoniVR** [comment]
Related to #2118

**Comment by Johan-dutoit** [comment]
yes
