### ISSUE TITLE
input text color is white

### ISSUE THREAD

**Issue by ginxx009** [FaridSafi/react-native-gifted-chat#2117]
#### Issue Description

When I type on the a fresh gifted chat layout on emulator it's good I can see my text because it's color black
but when I tried to build it the text color is white

I am not talking about the bubbles after you send the message but I am talking about when you type on the text input.

#### Steps to Reproduce / Code Snippets
`
<SafeAreaView style={{flex:1}}>
            <View style={{flexDirection:'row', justifyContent:'space-between', padding: 20}}>
                <TouchableOpacity onPress={() => navigation.goBack()}>
                    <Antd name={"left"} size={25}/>
                </TouchableOpacity>
                <Text>{client_name}</Text>
                <TouchableOpacity onPress={() => CallDriver()}>
                    <Ionicons name={"call-outline"} size={25}/>
                </TouchableOpacity>
            </View>
            <View style={{flex:1, backgroundColor:'#fff'}}>
                {/* <GiftedChat messages={messages} onSend={(messages) => onSendMessage(messages)} user={{_id: id}}/> */}
                <GiftedChat
                    messages={messages}
                    onSend={messages => onSendMessage(messages)}
                    user={{
                        _id: '2',
                    }}
                    style={{color:'#000'}}
                />
            </View>
</SafeAreaView>
`
tried to put a style inside the Gifted Chat but didn't work

#### Expected Results

When typing the color of the text must be black

#### Additional Information

* React version: *"react": "17.0.1",
* React Native version: *"react-native": "0.64.2",
* react-native-gifted-chat version: *"react-native-gifted-chat": "^0.16.3",
* Platform(s) : Android,

**Comment by ginxx009** [comment]
yup actually i forgot to close this question . but I solved it already. My bad .

**Comment by VanessaCarpes** [comment]
@ginxx009 can you share how you solved it?

**Comment by ginxx009** [comment]
Sorry if I have not posted my solution here's what I did .

```
<View style={{flex:1, backgroundColor:'#fff'}}>
                <GiftedChat
                    messages={messages}
                    onSend={messages => onSendMessage(messages)}
                    user={{
                        _id: '1',
                    }}
                    renderBubble={(props) => {
                        return <Bubble {...props} 
                        wrapperStyle={{
                            right: {
                                backgroundColor:'blue'
                            }
                        }}
                        />
                    }}

                    renderInputToolbar={(props) => {
                        return <InputToolbar {...props} 
                        containerStyle={{borderTopWidth: 2, borderTopColor:'#aaabac'}}
                        textInputStyle={{color:'black'}}
                        />
                    }}

                 />
            </View>
```
