### ISSUE TITLE
Please consider adding maintainers/collaborators

### ISSUE THREAD

**Issue by JoniVR** [FaridSafi/react-native-gifted-chat#2118]
Dear maintainers, 

I understand that sometimes, personal lives or interests shift away from Open Source projects.

This should not mean that a beautiful project such as this one becomes abandoned. There's plenty of initiative from the community to fix/help maintain it. 

Please, be responsible maintainers and add some other maintainers/collaborators to the project if you do not intend on maintaining it any longer or do not have the time to dedicate to it.

I'm sure people like @myckhel are very eager to help. I'd be happy to dedicate some time in getting this project back on track myself.

If no action is taken, I'm afraid the best path forward for the community will be a fork, which is not a path that's very good for anyone.

**Comment by shamilovtim** [comment]
Wish I had more time to devote to this. It's used heavily in a project I worked on. Maybe I could chip in every once in a while.
