### ISSUE TITLE
Message footer (for message status and such)

### ISSUE THREAD

**Issue by hhravn** [FaridSafi/react-native-gifted-chat#212]
Hi. I would really like to be able to render a custom footer below the individual messages. I know you have previously mentioned rendering the state (sending/sent/received), but i could not find any related code.

What are you thoughts about how this should be done? A simple call to an empty, overridable         Message.renderMessageFooter() in [Message.render(](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/Message.js#L91)) would suffice for my purposes..

**Comment by kfiroo** [comment]
@hhravn You could override `renderMessage` like this:
```javascript

const MyComp = React.createClass({
    renderMessage(props) {
        return (
            <View>
                <Message {...props} /> // this is GiftedChat.Message
                <MessageFooter /> // this is your custom footer
            </View>
        );
    },
    render() {
        const messages = [...]; // your messages array
        const user = {...}; // your user identifier
        return (
            <View>
                <GiftedChat
                    messages={messages}
                    user={user}
                    renderMessage={this.renderMessage}
                />
            </View>
        );
    }
});
```

**Comment by hhravn** [comment]
@kfiroo Feeling kindda silly now.. Thanks ;)
