### ISSUE TITLE
onPress backhandler getting the following error in android device

### ISSUE THREAD

**Issue by vsmshaik** [FaridSafi/react-native-gifted-chat#2120]
TypeError: _reactNative.Keyboard.removeListener is not a function. (In '_reactNative.Keyboard.removeListener('keyboardWillShow', invertibleProps.onKeyboardWillShow)', '_reactNative.Keyboard.removeListener' is undefined)

**Comment by aanikid** [comment]
same issue here :(

**Comment by vietanhdtd** [comment]
> But why this is suddenly occurring, I have the version installed on another app, there I've got no issues.

`removeListener` has been Deprecated from RN 0.65

https://reactnative.dev/docs/keyboard#removelistener

**Comment by tutov** [comment]
For users who use [patch-package](https://www.npmjs.com/package/patch-package), I attach change file `react-native-gifted-chat+0.16.3.patch`

```diff --git a/node_modules/react-native-gifted-chat/lib/MessageContainer.js b/node_modules/react-native-gifted-chat/lib/MessageContainer.js
index 193772a..2e3d7a1 100644
--- a/node_modules/react-native-gifted-chat/lib/MessageContainer.js
+++ b/node_modules/react-native-gifted-chat/lib/MessageContainer.js
@@ -55,18 +55,18 @@ export default class MessageContainer extends React.PureComponent {
         this.attachKeyboardListeners = () => {
             const { invertibleScrollViewProps: invertibleProps } = this.props;
             if (invertibleProps) {
-                Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
-                Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
-                Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
-                Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
+                this.keyboardWillShowListner = Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
+                this.keyboardDidShowListner = Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
+                this.keyboardWillHideListner = Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
+                this.keyboardDidHideListner = Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
             }
         };
         this.detachKeyboardListeners = () => {
             const { invertibleScrollViewProps: invertibleProps } = this.props;
-            Keyboard.removeListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
-            Keyboard.removeListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
-            Keyboard.removeListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
-            Keyboard.removeListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
+            this.keyboardWillShowListner.remove();
+            this.keyboardDidShowListner.remove();
+            this.keyboardWillHideListner.remove();
+            this.keyboardDidHideListner.remove();
         };
         this.renderTypingIndicator = () => {
             if (Platform.OS === 'web') {
```

**Comment by oshri-humanz** [comment]
We did a fork with a fix to this specific issue:
https://github.com/oshri-humanz/react-native-gifted-chat/releases/tag/v0.16.3.2

on package.json just replace the library to:
`"react-native-gifted-chat": "git+https://github.com/oshri-humanz/react-native-gifted-chat#v0.16.3.2"`

**Comment by Joshmatjjen** [comment]
> For users who use [patch-package](https://www.npmjs.com/package/patch-package), I attach change file `react-native-gifted-chat+0.16.3.patch`
> 
> ```diff
> index 193772a..053ba82 100644
> --- a/node_modules/react-native-gifted-chat/lib/MessageContainer.js
> +++ b/node_modules/react-native-gifted-chat/lib/MessageContainer.js
> @@ -55,18 +55,22 @@ export default class MessageContainer extends React.PureComponent {
>          this.attachKeyboardListeners = () => {
>              const { invertibleScrollViewProps: invertibleProps } = this.props;
>              if (invertibleProps) {
> -                Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
> -                Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
> -                Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
> -                Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
> +                this.keyboardWillShowListner = Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
> +                this.keyboardDidShowListner = Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
> +                this.keyboardWillHideListner = Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
> +                this.keyboardDidHideListner = Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
>              }
>          };
>          this.detachKeyboardListeners = () => {
>              const { invertibleScrollViewProps: invertibleProps } = this.props;
> -            Keyboard.removeListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
> -            Keyboard.removeListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
> -            Keyboard.removeListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
> -            Keyboard.removeListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
> +            if (Platform.OS === 'ios') {
> +                this.keyboardWillHideListner.remove();
> +                this.keyboardDidShowListner.remove();
> +                this.keyboardDidHideListner.remove();
> +            } else {
> +                this.keyboardDidShowListner.remove();
> +                this.keyboardDidHideListner.remove();
> +            }
>          };
>          this.renderTypingIndicator = () => {
>              if (Platform.OS === 'web') {
> ```
> 
> ```
> diff --git a/node_modules/react-native-gifted-chat/lib/MessageContainer.js b/node_modules/react-native-gifted-chat/lib/MessageContainer.js
> index 193772a..053ba82 100644
> --- a/node_modules/react-native-gifted-chat/lib/MessageContainer.js
> +++ b/node_modules/react-native-gifted-chat/lib/MessageContainer.js
> @@ -55,18 +55,22 @@ export default class MessageContainer extends React.PureComponent {
>          this.attachKeyboardListeners = () => {
>              const { invertibleScrollViewProps: invertibleProps } = this.props;
>              if (invertibleProps) {
> -                Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
> -                Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
> -                Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
> -                Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
> +                this.keyboardWillShowListner = Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
> +                this.keyboardDidShowListner = Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
> +                this.keyboardWillHideListner = Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
> +                this.keyboardDidHideListner = Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
>              }
>          };
>          this.detachKeyboardListeners = () => {
>              const { invertibleScrollViewProps: invertibleProps } = this.props;
> -            Keyboard.removeListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
> -            Keyboard.removeListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
> -            Keyboard.removeListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
> -            Keyboard.removeListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
> +            if (Platform.OS === 'ios') {
> +                this.keyboardWillHideListner.remove();
> +                this.keyboardDidShowListner.remove();
> +                this.keyboardDidHideListner.remove();
> +            } else {
> +                this.keyboardDidShowListner.remove();
> +                this.keyboardDidHideListner.remove();
> +            }
>          };
>          this.renderTypingIndicator = () => {
>              if (Platform.OS === 'web') {
> ```

@tutov ... Thank for this ... But i encountered an error, saying remove is not a funtion
But this below resolved it, adding the ? sign for conditioning 

```
 if (Platform.OS === 'ios') {
                this.keyboardWillHideListner?.remove();
                this.keyboardDidShowListner?.remove();
                this.keyboardDidHideListner?.remove();
            } else {
                this.keyboardDidShowListner?.remove();
                this.keyboardDidHideListner?.remove();
            }
```
