### ISSUE TITLE
Input field resizing on iOS on every other message

### ISSUE THREAD

**Issue by t-kaufmann** [FaridSafi/react-native-gifted-chat#2123]
#### Issue Description

On iOS (iPhone XR), the message input field resizes on its height on every other message. In the attached video the issue can be seen after the second "hi" message.

#### Steps to Reproduce / Code Snippets

Install and use the gifted chat minimal setup as instructed in the repository readme.

#### Expected Results

The input field should not resize in its height.

#### Additional Information

* Nodejs version: 12.19.0
* React version: 16.13.1
* React Native version: 0.63.2 (Expo)
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?):  only on iOS
* TypeScript version: 4.0.0

https://user-images.githubusercontent.com/34220946/136958654-5df283cc-8634-4622-b747-1df8c6654c47.mp4

**Comment by vietanhdtd** [comment]
It's a little late but anyone still facing this issue. This is a workaround solution, set `isKeyboardInternallyHandled` to false. And wrap your grifted-chat with `KeyboardAvoidingView`. in my case with heavily custom input tool bar, there's no problem.

**Comment by HunainHumail** [comment]
Also having this issue @FaridSafi ? Any solutions? Any fixes??

**Comment by krvajal** [comment]
Can confirm

**Comment by riku99** [comment]
I faced the same problem.
It seems that bottomOffset is causing the problem.
In my case, I solved the problem by using react-native-safe-area-context to get the bottom and passing it to bottomOffset.

```
import {useSafeAreaInsets} from 'react-native-safe-area-context';

const Foo = () => {
  const {bottom} = useSafeAreaInsets();
  
  <GiftedChat bottomOffset={bottom} ... />
}
```

**Comment by phen0menon** [comment]
@riku99 works for me, thx!

**Comment by findjassi** [comment]
Tried setting up as @riku99 suggested. Didn't fixed up the issue. :(
Anyone else, facing this issue got it fixed ?

**Comment by riku99** [comment]
@findjassi 
If you can, please show me the code.
