### ISSUE TITLE
Animated.event now requires a second argument for options

### ISSUE THREAD

**Issue by 3stbn** [FaridSafi/react-native-gifted-chat#2124]
#### Issue Description

"Animated.event now requires a second argument for options" warning pops up when you have a message that contains an image

#### Steps to Reproduce / Code Snippets

Render a message with an image

#### Expected Results

Not warning to be shown. 

#### Additional Information

* Nodejs version:  14.17.0
* React version: 17.0.1
* React Native version: 0.64.2
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): Tested on Android Emulator

**Comment by hkn-tr** [comment]
onScroll={Animated.event(  [
              {
                nativeEvent: {
                  contentOffset: {
                    x: scrollX,
                  },
                },
              },
            ],{useNativeDriver: false}  )
