### ISSUE TITLE
Getting "No handler for URL" error when pressing an URL in Android devices

### ISSUE THREAD

**Issue by jignesh-comxr** [FaridSafi/react-native-gifted-chat#2128]
#### Issue Description

When a message contains an URL, pressing on it throws an error "No handler for URL". This issue only occurs on Android devices.

#### Steps to Reproduce / Code Snippets

1. Send an URL in chat.
2. Click on that URL on an Android device

#### Expected Results

The URL should open in a browser.

#### Additional Information

* Nodejs version: v16.6.1
* React version: 17.0.1
* React Native version: 0.64.0
* react-native-gifted-chat version: ^0.16.3
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: -

**Comment by jamesholcomb** [comment]
Also started getting this recently for Android devices (emulator API 29 works as expected).

Device is Samsung s10.  The only change that comes to mind is I now target API 30 as it is required for Play Store uploads.

**Comment by jamesholcomb** [comment]
This fixed it for me

https://stackoverflow.com/questions/64699801/linking-canopenurl-returning-false-when-targeting-android-30-sdk-on-react-native

**Comment by jignesh-comxr** [comment]
@jamesholcomb This worked for me as well! Thanks a lot!
