### ISSUE TITLE
renderMessageVideo and renderMessageAudio doesn't work on expo ~42.0.1.

### ISSUE THREAD

**Issue by rahuld600** [FaridSafi/react-native-gifted-chat#2129]
I had to make changes to the library on the node_modules itself in order to implement audio and video messages functionality, I at first after looking at the messages that said, "You need to provide your own implementation by using renderMessageVideo/renderMessageAudio prop," I thought I had some sign of hope, but later found out they don't work . Later I checked on the main component, and found out that, these two functions don't exist.

#### Steps to Reproduce / Code Snippets

```
<GiftedChat
            renderMessageVideo={yourRenderedComponentVideo}
            renderMessageAudio={yourRenderedComponentAudio}
/>
```

and they don't work, we see some blank messages or the text message as written before...

#### Expected Results

Expected results are pretty simple that, the renderMessageVideo and renderMessageAudio props are supposed to be working, and by sending the _props, we could render the message.

#### Additional Information

* Nodejs version: v14.17.3
* React version: 16.13.1
* expo version: ~42.0.1
* react-native-gifted-chat version: ^0.16.3
* Platform(s) (iOS, Android, or both?): both

**Comment by DaanOolbekkink** [comment]
I have the same problem, any solution?

**Comment by DaanOolbekkink** [comment]
For anyone else running into this problem the prop should be added to the `<Bubble/>`
Example:
`renderBubble={renderBubble}`
on the `<GiftedChat>`

```
const renderBubble = (props: any) => {
    return <Bubble {...props}
      renderMessageVideo={() => <View style={{ width: '100%', aspectRatio: 16 / 9 }}><Vimeo
        videoId={props.currentMessage.video}
        loop={false}
        autoPlay={false}
        controls
      />
      </View>}
    />
  }
```

Get the video url or something via `props.currentMessage`

**Comment by aamiryameen** [comment]
Does this support youtube iframe player?

**Comment by DaanOolbekkink** [comment]
> Does this support youtube iframe player?

I have used it with react native vimeo player so I would think yes it does. My recommendation however is to load a thumbnail as an image in the bubble and then clicking the image would open a modal or new screen with the actual player. 😄

**Comment by aamiryameen** [comment]
> 

Thanks for replying however i am a little confused about how this prop works I have written function for this but the function never executes and so there are not videos displayed 

**This is my <Bubble/> component**
  <Bubble
            renderMessageVideo={renderVideoLink} 
            />
            
   **And this is my renderVideoLInk function**

  const renderVideoLink  = (props : any) => {
    console.log('-------------------------------------Function Executed--------------------')
    let codeMessage;
    var regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
    var matchURL = props.cu.data.substring(5);
    var match = matchURL.match(regExp);
    console.log(match)
    if (match && match[2].length == 11) {
       codeMessage = match[2];
       return(  

     <YoutubePlayer
     height={300}
     play={true}
     videoId={codeMessage}
    />
     
     )
    } else {
      console.log('Invalid URL')
    }

  }


Can you please explain a little do i have to use some extra types of message for videos ?

**Comment by DaanOolbekkink** [comment]
Hi, 
Please use tripple back quotes to properly format the code and make it readable for everyone.

The problem I can see is that in my experience a function to load items in a list always have to return a jsx element. So in your example you should have at least a `return (<View></View>)` in your else. Maybe that will fix your problem?

**Comment by aamiryameen** [comment]
I have already tried that and  I have tried it with hard coded video Id for the player as well 

` <Bubble
            renderMessageVideo={() =>  <View style={{height : 100 , width :100}}>

        
            <YoutubePlayer
            height={300}
            play={true}
            videoId={'47eXVRJKdkU'}
           />
            </View>}`

**Comment by DaanOolbekkink** [comment]
Okay so I don't know why that is not working. This is my renderMessageVideo...

```
const renderBubble = (props: any) => {
    return <Bubble {...props}
      renderMessageVideo={() =>
        <Pressable onPress={openVideo} style={styles.video}>
          {props.currentMessage?.video &&
            <Vimeo
              videoId={'76979871'}
              loop={false}
              autoPlay={false}
              controls={false}
              speed={false}
              time={'0m0s'}
            />
          }
        </Pressable>
      }
    />
  }

<GiftedChat `renderBubble={renderBubble}` />
```
I am using functional components so you might need to change some things to fit it in your code

**Comment by aamiryameen** [comment]
> 

Thanks a lot

**Comment by rahuld600** [comment]
@aamiryameen @DaanOolbekkink Thank you so much guys for co-operating, but a some time ago, I could successfully implement it using only `renderMessageVideo ` and  `renderMessageAudio ` functions with the `expo-av ` package of expo, 
Link to it is here : https://docs.expo.dev/versions/latest/sdk/av/
I created separate audio video components to render, and used those same function as props in the same <GiftedChat/>  tag, and it works!!!
Something like this for video (you can figure out the audio part ; ) ):
`
import React from 'react';
import { StyleSheet, Dimensions } from 'react-native';
import { Video } from 'expo-av';

const MessageVideo = ({ props }) => {
    const video = React.useRef(null);

    return (
        <Video
            ref={video}
            style={styles.video}
            source={{
                uri: props.currentMessage.video,
            }}
            useNativeControls
            resizeMode='cover'
            isLooping
        />
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        backgroundColor: '#ecf0f1',
    },
    video: {
        alignSelf: 'center',
        width: Dimensions.get('window').width / 1.4,
        height: Dimensions.get('window').width / 1.4,
        borderRadius: 15,
        marginBottom: 5,
    },
});

export default MessageVideo;

`
And then :
```
<GiftedChat
    {...props}
    renderMessageVideo={(props) => <MessageVideo props={props} />}
/>

```

And same for audio! Thank you guys, once again : ), If you need any more help regarding this, let me know!

**Comment by DaanOolbekkink** [comment]
No problem and thanks for the response, I understand what you are saying but the implementation with renderMessageVideo as a prop in GiftedChat does not work for some reason. Maybe it's deprecated or something. I am just trying to save some time for others reading this.

**Comment by rahuld600** [comment]
> No problem and thanks for the response, I understand what you are saying but the implementation with renderMessageVideo as a prop in GiftedChat does not work for some reason. Maybe it's deprecated or something. I am just trying to save some time for others reading this.

It does work @DaanOolbekkink , try it yourself once as I wrote!

**Comment by rahuld600** [comment]
Guys, make sure you restart the whole server after you implement anything with it! Thanks! Hope it helps!

**Comment by DaanOolbekkink** [comment]
Are you using typescript? Because when I go to the defaultProp types I do see renderMessageImage but I do not see renderMessageVideo. This is on version 0.16.3
```
static defaultProps: {
        messages: never[];
        messagesContainerStyle: undefined;
        text: undefined;
        placeholder: string;
        disableComposer: boolean;
        messageIdGenerator: () => string;
        user: {};
        onSend: () => void;
        locale: null;
        timeFormat: string;
        dateFormat: string;
        loadEarlier: boolean;
        onLoadEarlier: () => void;
        isLoadingEarlier: boolean;
        renderLoading: null;
        renderLoadEarlier: null;
        renderAvatar: undefined;
        showUserAvatar: boolean;
        actionSheet: null;
        onPressAvatar: null;
        onLongPressAvatar: null;
        renderUsernameOnMessage: boolean;
        renderAvatarOnTop: boolean;
        renderBubble: null;
        renderSystemMessage: null;
        onLongPress: null;
        renderMessage: null;
        renderMessageText: null;
        renderMessageImage: null;
        imageProps: {};
        videoProps: {};
        audioProps: {};
        lightboxProps: {};
        textInputProps: {};
        listViewProps: {};
        renderCustomView: null;
        isCustomViewBottom: boolean;
        renderDay: null;
        renderTime: null;
        renderFooter: null;
        renderChatEmpty: null;
        renderChatFooter: null;
        renderInputToolbar: null;
        renderComposer: null;
        renderActions: null;
        renderSend: null;
        renderAccessory: null;
        isKeyboardInternallyHandled: boolean;
        onPressActionButton: null;
        bottomOffset: number;
        minInputToolbarHeight: number;
        keyboardShouldPersistTaps: string;
        onInputTextChanged: null;
        maxInputLength: null;
        forceGetKeyboardHeight: boolean;
        inverted: boolean;
        extraData: null;
        minComposerHeight: number | undefined;
        maxComposerHeight: number;
        wrapInSafeArea: boolean;
    };
```

**Comment by rahuld600** [comment]
No, I am not using typescript, I couldn't also see it, but It worked somehow! Why don't you try it, restart the server and see yourself without making excuses and debating and wasting everyone's time? @DaanOolbekkink
