### ISSUE TITLE
Bubble Chat Alignment Issue

### ISSUE THREAD

**Issue by bhaktitud** [FaridSafi/react-native-gifted-chat#2136]
#### Issue Description

i have problem to fix this bubble chat alignment issue

#### Steps to Reproduce / Code Snippets
i already provide chat id and user id
![Screenshot_2021-11-28-18-19-37-749_com panorama](https://user-images.githubusercontent.com/21971013/143765636-449463c7-42da-4061-b4a3-ed0f10997629.jpg)

#### Expected Results

left bubble chat align correctly

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: 
* React Native version: 0.63
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: [FILL THIS OUT]

**Comment by ArietNyshanbaev** [comment]
gifted chat assumes that you provided avatar as well so renderAvatar={null} will fix it.
renderAvatar={null}
