### ISSUE TITLE
Messages aren't rendered until scroll

### ISSUE THREAD

**Issue by siemya** [FaridSafi/react-native-gifted-chat#214]
I have a view which is hidden from screen and it appears as i drag it. When i use react-native-gifted-chat inside my view, it doesn't get rendered until i scroll the listView.

It is obviously related with this [issue](https://github.com/facebook/react-native/issues/1831). But i dont want to set removeClippedSubviews to true, which might cause performance issues.

**Comment by FaridSafi** [comment]
Well, it's a `ListView` bug then

Maybe you can try to replace https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/MessageContainer.js#L145 by 
```jsx
initialListSize={this.props.messages.length}
```
Or test different values for `initialListSize` and `pageSize`

Please let me know if you can fix it

**Comment by kfiroo** [comment]
First, we should all upvote this issue in product pains https://productpains.com/post/react-native/listview-doesnt-render-rows-until-scroll  :)

Second, there are 2 suggested solutions there:

1. setting `removeClippedSubviews={false}` - which is a very bad idea, as it will cause the entire list to be rendered always and cause poor performance.
2. faking `scrollTo` when list becomes visible as suggested in this comment https://github.com/facebook/react-native/issues/1831#issuecomment-231069668 - which seems to be a better solution.

@siemya Can you try the second one and see if that works for you?

**Comment by jaspervanbrian** [comment]
Has this been fixed? My use case is when I receive a new message from the websockets, I trigger an action that will fire to Redux, and will append to the messages array, but you need to scroll it first before appearing. It is frustrating, really.
