### ISSUE TITLE
Playing youtube videos in a message bubble

### ISSUE THREAD

**Issue by aamiryameen** [FaridSafi/react-native-gifted-chat#2140]
#### Issue Description

is there a feature to play youtube videos using iframe in message ?

#### Steps to Reproduce / Code Snippets

I tried playing this with renderMessageVideo() but no luck 

#### Expected Results

A youtube player should embed in a message bubble

#### Additional Information

* Nodejs version: 14.18.1.
* React version: "17.0.2",
* React Native version: "0.65.0"
* react-native-gifted-chat version: "^0.16.3",
* Platform(s) (iOS, Android, or both?): both

**Comment by aamirpadder** [comment]
Please use the prop **renderMessageVideo**
Example:
`<GiftedChat
                        bottomOffset={50}
                        
                        renderMessageImage={this.renderMessageImage}
                        renderMessageVideo={this.renderMessageVideo}
                        renderMessageText={this.renderMessageText}
/>`

Then your **renderMessageVideo** will be like this
` renderMessageVideo = (props) => {
    return (
      <View style={{ paddingTop: 20, marginTop: 40 }}>
        <View style={{ flexDirection: 'column' }}>
         
          <VideoPlayer
            video={{ uri: props.currentMessage.video }}
            autoplay={false}
            defaultMuted={true}
            disableFullscreen={false}
            pauseOnPress={true}
            fullScreenOnLongPress={true}
            // customStyles={customStyles.mediaPlayer}
            resizeMode={'stretch'}
            videoWidth={width / 2.8}
            videoHeight={120}
            thumbnail={{
              uri: 'https://www.xyz.com/computer-icons-video-display-resolution-others.jpg',
            }}
          />
          <Text style={{ color: '#fff' }}>{`Play Video on Full Screen`}</Text>
   
        </View>
      </View>
    );
  };`

**Happy Codding**
