### ISSUE TITLE
onLongPress on message background and all messages blur only that message is focus like whatsapp

### ISSUE THREAD

**Issue by abdulrehmankfueit** [FaridSafi/react-native-gifted-chat#2146]
I am working on a chat messenger app with React native gifted chat  package
when the user long press on message background and all messages blur only that message is focused like WhatsApp  if anyone work on this feature then share the right way 
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): [Both]

**Comment by BLOCKMATERIAL** [comment]
@abdulrehmankfueit You can use the[ react-navtive-context-menu](https://www.npmjs.com/package/react-native-context-menu-view) library, but blur on android does not work everywhere .

**Comment by RichyTech01** [comment]
> I am working on a chat messenger app with React native gifted chat package when the user long press on message background and all messages blur only that message is focused like WhatsApp if anyone work on this feature then share the right way
> 
> * react-native-gifted-chat version: 0.16.3
> * Platform(s) (iOS, Android, or both?): [Both]

> I am working on a chat messenger app with React native gifted chat package when the user long press on message background and all messages blur only that message is focused like WhatsApp if anyone work on this feature then share the right way
> 
> * react-native-gifted-chat version: 0.16.3
> * Platform(s) (iOS, Android, or both?): [Both]

have you solved it?

**Comment by topgun100** [comment]
Sorry, this is a bit vague, but it should give you a high-level idea of what to do.

1. Define a `ContextMenuOverlay` component with these props.

```
interface ContextMenuOverlayProps {
  selectedBubble: {
    position: { x: number; y: number; width: number; height: number } | null;
    bubbleProps: BubbleProps<IMessage>;
  } | null;
  onClose: () => void;
 // whatever else you need 
}
```

`ContextMenuOverlay` should render a `Modal` with `BlurView` and  re-draw your floating bubble over the underlying one (or wherever you want it). Something like this.

```
        const isRightSide = bubbleProps.position === 'right';

        <Animated.View
          style={[{
            position: 'absolute',
            left: position.x,
            top: position.y,
            shadowColor: '#222',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.3,
            shadowRadius: 4,
            elevation: 5,
            transformOrigin: isRightSide ? 'bottom right' : 'bottom left',
          }, animatedStyle]}
        >
          <Bubble {...bubbleProps}/>
        </Animated.View>
        <Animated.View>
           // your context menu
        <Animated.View>
```


2. In your chat component, create a custom bubble renderer so you can measure its position

```
    const renderBubble = useCallback((props: any) => {
      const bubbleRef = useRef<View>(null);
      
      return (
        <View
          ref={bubbleRef} 
        >
          <Bubble
             onLongPress={() => handleBubbleLongPress(bubbleRef, props)}
            {...props}
          />
          </Bubble>
        </View>
      );
    }, [handleBubbleLongPress]);
```

```
    const [selectedBubble, setSelectedBubble] = useState<{
      position: { x: number; y: number; width: number; height: number } | null;
      bubbleProps: BubbleProps<IMessage>;
    } | null>(null);

    const handleBubbleLongPress = useCallback((ref: RefObject<View | null>, bubbleProps: BubbleProps<IMessage>) => {
      ref.current?.measureInWindow((x: number, y: number, width: number, height: number) => {
        setSelectedBubble({
          position: { x, y, width, height },
          bubbleProps,
        });
        setShowContextMenu(true);
        Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
      });
    }, []);
```

![Image](https://github.com/user-attachments/assets/13f6ca29-4934-4ebe-83f9-d1e2c1f45e79)
