### ISSUE TITLE
Gap between Keyboard & text input component when using createBottomTabNavigator

### ISSUE THREAD

**Issue by sohailmadan** [FaridSafi/react-native-gifted-chat#2147]
Issue Description

I used createBottomTabNavigator from react-navigation to create a bottom tab bar.
One of the tabs is messages tab, where I added the example chat code (given in readme)
When running this ios simulator, as soon as the keyboard shows up, there is a big gap between the keyboard and the text input component.

When no keyboard, its fine :
It's clone of this issue https://github.com/FaridSafi/react-native-gifted-chat/issues/1202

**Comment by ELECTRO-2006** [comment]
DISABLE THE BOTTOM TAB IN THE CHATSCREEN PAGE

**Comment by wernst** [comment]
If you are using react-navigation you should be able to use `BottomTabBarHeightContext` (see: https://reactnavigation.org/docs/bottom-tab-navigator/) and use the `tabBarHeight` value to set the `bottomOffset` prop on your GiftedChat component

**Comment by aualdrich** [comment]
@wernst OMG! You're a genius--I was pulling my hair out over this one. That did the trick. Thanks a million.
