### ISSUE TITLE
no prop renderMessageVideo on version 0.16.3

### ISSUE THREAD

**Issue by dev-sekhmet** [FaridSafi/react-native-gifted-chat#2148]
#### Issue Description
using the latest version as of today v0.16.3 there is no prop renderMessageVideo in the lib

[FILL THIS OUT]
![image](https://user-images.githubusercontent.com/95574384/148683931-76824195-c194-4b79-bb77-978224af23fa.png)

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by ELECTRO-2006** [comment]
### WELL IN ORDER TO GET THAT  PROP YOU NEED TO MAKE YOUR CUSTOM BUBBLE WHERE YOU'LL GET THAT PROP 
FOR INSTANCE SEE THIS EXAMPLE 


```
function renderBubble(props) {
  return <Bubble
      {...props}
      renderMessageVideo = {renderMessageVideo}
    />
}


```


```
function renderMessageVideo(props){
    const { currentMessage } = props;
    return (
      <Lightbox  activeProps = {{ flex: 1,
        resizeMode: 'contain',}}>
        <View style={{ padding: 80 }}>
        <Video
          resizeMode="cover"
          useNativeControls
          shouldPlay={false}
          controls={true}
          source={{ uri: currentMessage.video }}
          style={{position:"absolute",top:0,left:0,bottom:0,right:0}}
        />
        </View>
      </Lightbox>
    );
  };

```

```
 <GiftedChat
            messages={messages}
            onSend={messages => onSend(messages)}
            user={{
                _id:"jjj",
            }}
           renderSend={renderSend}
           renderComposer ={renderComposer} 
           renderInputToolbar ={customtInputToolbar}
          //  inverted = {true}
           onLongPress = {(context,message)=>{
             setRenderHeaderBar(false)
             setMessageProperties(message)
             Keyboard.dismiss()
           }}
           renderBubble = {renderBubble} 
          
          
          
            />
```

**Comment by fukemy** [comment]
@Johan-dutoit hi, can u help me to know Lightbox and Video package, where did u get it?

**Comment by Yogesh-Dubey-Ayesavi** [comment]
@fukemy  npm bro
