### ISSUE TITLE
maxHeight incorrect

### ISSUE THREAD

**Issue by maxs15** [FaridSafi/react-native-gifted-chat#215]
Hey @FaridSafi !

Awesome job on this chat ! 👏 

I'm having an issue with the size of the chat, the Input is taking most of the screen sometimes (Screenshot below).

After investigating it looks like the height returned by onLayout is 0 [here](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/GiftedChat.js#L440).
The correct height is returned on a second call of onLayout, I've managed to fix the issue just by adding `if (layout.height <= 0) return;` that way the correct height will be used on the next call.

Are you aware of this issue ? Does it seem like the right way to fix it ?
I can push you a PR with the fix if you want to 👍 

Thanks

[![IMG_2184.jpg](https://s14.postimg.org/nmnyblmld/IMG_2184.jpg)](https://postimg.org/image/s8k2jy84d/)

**Comment by FaridSafi** [comment]
Hello, did you wrap the Chat inside a `flex: 1` container ?

**Comment by maxs15** [comment]
Yes I did (Using RN 0.30)

**Comment by FaridSafi** [comment]
Can you try to remove this condition please https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/GiftedChat.js#L414

**Comment by maxs15** [comment]
It works but the screen is kind of flickering..
Better get the height before the initialization in my opinion

**Comment by FaridSafi** [comment]
I will try to find another workaround for the next release
Can I ask you a code example to reproduce this issue ?

**Comment by maxs15** [comment]
There is just a basic ```<GiftedChat user={this.props.user} locale={locale} messages={this.props.messages}/>``` in my view.
But I'm using [react-native-navigation](https://github.com/wix/react-native-navigation) to manage navigation between my views.
It may be the cause of the layout recalculation.. but I think it's a good thing to handle the case where the layout would change because the chat becomes unusable otherwise

**Comment by emirdeliz** [comment]
+1

**Comment by FaridSafi** [comment]
@emirdeliz are you using react-native-navigation?

**Comment by emirdeliz** [comment]
@FaridSafi I'm using emulador (iphone 4s)

**Comment by emirdeliz** [comment]
I'm using nativebase too.  

My code is

```
import React, { Component, PropTypes } from 'react'
import { Container, Content, Header, Title, Button, Icon,
    Text, List, ListItem, View } from 'native-base'

import { GiftedChat } from 'react-native-gifted-chat'

export default class Home extends Component {

    constructor(props) {
        super(props)

        this.state = { messages: [] };
        this.onSend = this.onSend.bind(this);
    }
    componentWillMount() {
        this.setState({
            messages: [
                {
                    _id: 1,
                    text: 'Hello developer',
                    createdAt: new Date(Date.UTC(2016, 7, 30, 17, 20, 0)),
                    user: {
                        _id: 2,
                        name: 'React Native',
                        avatar: 'https://facebook.github.io/react/img/logo_og.png',
                    },
                },
            ],
        });
    }
    onSend(messages = []) {
        this.setState((previousState) => {
            return {
                messages: GiftedChat.append(previousState.messages, messages),
            };
        });
    }

    render() {
        return (
            <Container>
                <Header>
                    <Button transparent onPress={ () => this.props.navigate.pop() }>
                         <Icon name="ios-arrow-back" />
                    </Button>
                    <Title>{ this.props.professional.name }</Title>
                </Header>
                <Content>
                    <GiftedChat  messages={this.state.messages}
                        onSend={this.onSend}
                        user={{
                          _id: 1,
                        }}
                      />
                </Content>
            </Container>
        );
    }
}
```

**Comment by emirdeliz** [comment]
I fix my problem with this

```
<Container>
    <Header>
        <Button transparent onPress={ () => this.props.navigate.pop() }>
             <Icon name="ios-arrow-back" />
        </Button>
        <Title>{ this.props.professional.name }</Title>
    </Header>
    <View>
        <GiftedChat messages={ this.state.messages } renderActions={ this.buildCustomActions }
            onSend={ this.onSend } user={{ _id: 1}} />
    </View>
</Container>
```
The cause of problem is tag <Content>

**Comment by zhouanbo** [comment]
I had the exact same issue as @maxs15, fixed the issue by following his suggestions. Thanks!
