### ISSUE TITLE
how to make my image clickable?

### ISSUE THREAD

**Issue by bionimic** [FaridSafi/react-native-gifted-chat#216]
1) how to make my image clickable
2) im using latest RN. but im getting this error: "Unsupported node type: transform" when i try to copy text.

**Comment by bionimic** [comment]
basically i want to change the onLongPress function in bubble component. how can I do that? can you give me an example?

**Comment by FaridSafi** [comment]
Hello,
1) https://github.com/FaridSafi/react-native-gifted-chat/pull/202#issuecomment-240364964
2) Please upgrade to 0.0.10 to fix this issue

**Comment by bionimic** [comment]
thank you!
