### ISSUE TITLE
Is there any way I can add a sticky header bar?

### ISSUE THREAD

**Issue by VanessaCarpes** [FaridSafi/react-native-gifted-chat#2166]
Issue Description
I'm looking to add a header bar that part of it remains sticky on scroll, any help would be appreciated, please.
I've already tried to use "react-native-collapsible-tab-view" but the answer box scroll with the chat too :/

Current:
![image](https://user-images.githubusercontent.com/56100002/156766420-871a56d4-0959-416d-bbd5-d4f8315fb802.png)

Expected on scroll:
![image](https://user-images.githubusercontent.com/56100002/156766666-4f03129c-2d77-4982-a252-93c815a38102.png)

**Comment by Yogesh-Dubey-0804** [comment]
Well im not getting what you wanted to stick with the header bar please kindly provide more description

**Comment by VanessaCarpes** [comment]
Hi, thank you for the answer..
What I meant was if you add this component to a page, the scroll will work inside it to view the messages, right? so the rest of the components that are added before will fill the page.
So I'm trying to scroll the components added before but the last one (the title "Chat") to allow the messages to fill the whole screen.
I don't know if it is possible, I tried to add another component to control the sticky header as I mentioned before, but the answer box just appears after hitting the bottom.

**Comment by ELECTRO-2006** [comment]
**You have to wrap the component in ScrollView only the other stuffs then you need to 
Add thier props like**
### OnScroll
Well this function returns a callback in the form the content scrolled in x axis or y axis 


```
<ScrollView>
     onScroll={Animated.event([{ nativeEvent: { contentOffset: { x: 
     scrollX } } }], {listener: (event) => handleScroll(event)})}
     scrollEventThrottle={16}
>
   ...some content
</ScrollView>

```
### handle scroll function
```
const handleScroll = (event) => {
    const positionX = event.nativeEvent.contentOffset.x;
    const positionY = event.nativeEvent.contentOffset.y;
  };
```
you can make use of handle function to manage height state prop
Well im answering from phone im outside right now so in case any error comes out sorry for that...

**Comment by VanessaCarpes** [comment]
Using ScrollView the messages are not rendering, but I think its behavior will be similar to the component I tried before, it will scroll the answer box too :/
It would be nice if the scroll event could be called from the gifted chat component.

**Comment by ELECTRO-2006** [comment]
Send me the code

**Comment by VanessaCarpes** [comment]
Thank you so much for your help, I've talked to our design team and they added an expand button 😄

**Comment by ELECTRO-2006** [comment]
Kindly close the issue !
