### ISSUE TITLE
Change time render position for chat screen

### ISSUE THREAD

**Issue by YiqianDeng** [FaridSafi/react-native-gifted-chat#2168]
#### Issue Description

Hi, I'm trying to modify the position of the time display for all left chat. By default, the time for the right chat aligns to right, and for the left chat aligns to left. I tried both textAlign and position for timeTextStyle, none of them work as expected.

#### Steps to Reproduce / Code Snippets

```
const renderTime = props => {
    return (
      <Time
        {...props}
        timeTextStyle={{
          left: {
            color: '#3c3c434d',
            fontSize: 10,
            fontFamily: 'Rubik',
            textAlign: 'right', // or position: 'right'
          },
          right: {color: '#3c3c434d', fontSize: 10, fontFamily: 'Rubik'},
        }}
      />
    );
  };

return (
    <GiftedChat
      messages={messages}
      onSend={messages => onSend(messages)}
      user={{
        _id: 1,
      }}
      renderBubble={renderBubble}
      renderTime={renderTime}
    />
  );
```

#### Expected Results

The left chat time is displayed on right as well.

#### Additional Information

* Nodejs version: [16.13.2]
* React version: [FILL THIS OUT]
* React Native version: [0.67.2]
* react-native-gifted-chat version: [^0.16.3]
* Platform(s) (iOS, Android, or both?): [Android]
* TypeScript version: [FILL THIS OUT]

**Comment by venxik** [comment]
`    <Time
        {...props}
        containerStyle={{
          left: {
            alignSelf: 'flex-end',
            flex: 1,
          },
        }}
        timeTextStyle={{
          left: {
            color: '#3c3c434d',
            fontSize: 10,
            fontFamily: 'Rubik',
            textAlign: 'right', // or position: 'right'
          },
          right: {color: '#3c3c434d', fontSize: 10, fontFamily: 'Rubik'},
        }}
      />`

try to add this style, hope it can help

**Comment by YiqianDeng** [comment]
Oh, btw there is another question that after I change left side alignSelf to 'flex-end' and flex to 1, the time text automatically wrapped when I sent short text. What will be a good way to make the time text not wrapped?

The Hello bubble's time is wrapped.
It is expected to be the time display for the long sentence.

![image](https://user-images.githubusercontent.com/20446393/158839010-d5922f3b-448d-45d8-b93c-7242b53ca600.png)

**Comment by YiqianDeng** [comment]
solved. just limit maxWidth is good.

**Comment by Naveen854** [comment]
> solved. just limit maxWidth is good.

At Where bro?

**Comment by shkibrahim** [comment]
my all msgs show single date in center the today's current date not message date , how can i fix that?
