### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Etelligens-design** [FaridSafi/react-native-gifted-chat#2174]
#### Issue Description

TypeError: undefined is not a function

#### Steps to Reproduce / Code Snippets

![Capture](https://user-images.githubusercontent.com/59085763/162394797-a76f1fba-da75-4665-bc8c-cdb59a1792cd.PNG)

#### Expected Results

[ not crash]

#### Additional Information

* Nodejs version: [v14.17.3]
* React version: [17.0.2]
* React Native version: [0.66.1]
* react-native-gifted-chat version: [^0.16.3]
* Platform(s) (iOS, Android, or both?): [both]
* TypeScript version: [7.16.7]

**Comment by Johan-dutoit** [comment]
Please try installing the latest version (currently v1.0.0-beta-2) and let me know if the issue persists (it's still in beta).

**Comment by afaqabid** [comment]
> #### Issue Description
> TypeError: undefined is not a function
> 
> #### Steps to Reproduce / Code Snippets
> ![Capture](https://user-images.githubusercontent.com/59085763/162394797-a76f1fba-da75-4665-bc8c-cdb59a1792cd.PNG)
> 
> #### Expected Results
> [ not crash]
> 
> #### Additional Information
> * Nodejs version: [v14.17.3]
> * React version: [17.0.2]
> * React Native version: [0.66.1]
> * react-native-gifted-chat version: [^0.16.3]
> * Platform(s) (iOS, Android, or both?): [both]
> * TypeScript version: [7.16.7]

Did this issue resolve?

**Comment by yamikani56** [comment]
had the same problem now resolved after reinstall to latest version of gifted chat, thanks

**Comment by TommyLeong** [comment]
Same issue reoccured using `v2.1.0` with `"react-native": "0.71.7"`.

Any face the same?
![issue](https://user-images.githubusercontent.com/9990179/236657234-392e3fce-9b90-4f69-8cf4-1f3654a255b1.png)
