### ISSUE TITLE
Changing the orientation of messages

### ISSUE THREAD

**Issue by ghprud** [FaridSafi/react-native-gifted-chat#218]
Hey FraidSafi

I really love the gifted chat. Firstly, 👏. I was wondering if there you support orientation change in the message container. I am trying to show the first message on the top of the container. I passed in a custom style, but it is not working. I was wondering if you can help me how to flex the container. 

Thanks in advance.

**Comment by FaridSafi** [comment]
Hello @ghprud, this feature is not supported yet.
Feel free to submit a pull request if you manage to implement it

**Comment by psrustik** [comment]
pull request #280
