### ISSUE TITLE
newest version of library still get space between keyboard and inputaccessoryView

### ISSUE THREAD

**Issue by fukemy** [FaridSafi/react-native-gifted-chat#2183]
Hi, i tried everything answer from all related i issues but nothing work to me:

As you can see video here

https://user-images.githubusercontent.com/8202437/163737611-6317226c-3859-4ed1-b41a-425f7fa57d74.MOV

i tried using forgetKeyboardHeight, KeyboardAvoidingView,KeyboardSpacer.. but nothing worked, can u give me some advices? Thanks in advance 

* Nodejs version: lasted
* React version: lasted
* React Native version: lasted
* react-native-gifted-chat version:0.16.3
* Platform(s) (iOS, Android, or both?): IOS
* TypeScript version: npm

**Comment by Johan-dutoit** [comment]
Please attach the image/videos directly onto GH.

**Comment by fukemy** [comment]
https://user-images.githubusercontent.com/8202437/163737582-844a3b2a-c1b3-42d4-95ee-a5185b9ebf55.MOV

Hi bro i updated video

**Comment by hazymnc** [comment]
+1 same issue

**Comment by H4ris** [comment]
+1 Here too

**Comment by Johan-dutoit** [comment]
I know the title says latest version, however your details mention 0.16.3.  Can you test the latest 1.0.0.beta-x and confirm if it's still present

**Comment by camcelroy** [comment]
Same behavior confirmed with 1.0.0-beta-3 as well.

**Comment by fukemy** [comment]
i found the problem is based on SafeAreaView from safeareacontext, remove it then all work normally

addition:
```
const insets = useSafeAreaInsets()
bottomOffset={insets.bottom}

```

**Comment by Johan-dutoit** [comment]
Assuming that's in your code base?

**Comment by Johan-dutoit** [comment]
If I'm understanding this properly, the safe area only needs to be present when the keyboard is not open?

> i found the problem is based on SafeAreaView from safeareacontext, remove it then all work normally
> 
> addition:
> 
> ```
> const insets = useSafeAreaInsets()
> bottomOffset={insets.bottom}
> ```

**Comment by Johan-dutoit** [comment]
You could also pass in `wrapInSafeArea={false}`

**Comment by k-lpmg** [comment]
> i found the problem is based on SafeAreaView from safeareacontext, remove it then all work normally
> 
> addition:
> 
> ```
> const insets = useSafeAreaInsets()
> bottomOffset={insets.bottom}
> ```

@fukemy 
It works thanks!!!

**Comment by ericchen0121** [comment]
Confirmed. Solution is to: 

```
// import 
import { useSafeAreaInsets } from 'react-native-safe-area-context'

// use hook inside functional component
const insets = useSafeAreaInsets()

// add prop to GiftedChat
return (
<GiftedChat
...
bottomOffset={insets.bottom}
/>
```

Note, adding `wrapInSafeArea={false}` prop to GiftedChat removed the offending space, but now the TextInput was hidden, and adding bottomOffset of any value didn't fix the issue, since wrapInSafeArea seems to set a default bottomOffset which is overridden by passing in the prop. Thus, this was NOT a solution for me.

**Comment by alextbogdanov** [comment]
This did it for me:
https://medium.com/@islamrustamov/one-of-the-many-react-natives-textinput-problem-on-android-e4c9915acbc6
