### ISSUE TITLE
Message not scroll smoothly when Keyboard open and close

### ISSUE THREAD

**Issue by zeeshan-shabbir** [FaridSafi/react-native-gifted-chat#2191]
#### Issue Description
when keyboard open messages did not goes smoothly with keyboard rather take time .

#### Expected Results

Should move smoothly when keyboard open  or close

#### Additional Information

* React version: [17.0.2]
* React Native version: [0.67.3]
* react-native-gifted-chat version: [(https://github.com/FaridSafi/react-native-gifted-chat)]
* Platform(s) (iOS, Android, or both?): [Android]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/80969033/164405984-6cf8b0bb-a1e2-4f01-8edd-31906e7e245d.gif)

**Comment by ghoudi01** [comment]
Same here

**Comment by fukemy** [comment]
just build in release mode

**Comment by fukemy** [comment]
i tested in release mode, still problem with android, ios work good

**Comment by arshnk-deloitte** [comment]
same here

**Comment by fukemy** [comment]
I tested with m1 mac simulator,build in release mode, and the layout took about ~500-800 milliseconds to resize after keyboard showed

**Comment by zeeshan-shabbir** [comment]
> I tested with m1 mac simulator,build in release mode, and the layout took about ~500-800 milliseconds to resize after keyboard showed

What should we do?

**Comment by fukemy** [comment]
i see the log of metro and I see the screen re-render 4 times when keyboard show, i think better we need to use wix keyboard input

**Comment by fukemy** [comment]
test the demo with android simulator( not m1), it's took delay when press to show keyboard first time, but very smooth animation

**Comment by VladislavTemriuk** [comment]
Any solutions?

**Comment by hotaryuzaki** [comment]
any solution gaesss??
i search everywhere for days but i dont find any solution

**Comment by VladislavTemriuk** [comment]
@hotaryuzaki unfortunately, I also did not find solutions to this problem, so I had to abandon the use of this library, but it did not turn out to be a big problem, since all the components were already custom (text, images, time, send/read tick marks, etc.). So I just use FlatList and it works fine

**Comment by hotaryuzaki** [comment]
> @hotaryuzaki unfortunately, I also did not find solutions to this problem, so I had to abandon the use of this library, but it did not turn out to be a big problem, since all the components were already custom (text, images, time, send/read tick marks, etc.). So I just use FlatList and it works fine

Yes maybe it is better to create the UI by ourselves.

I tried tricky fix with keyboard event but sadly android didn't have keyboardWillShow and keyboardWillHide.
I think we can use keyboardWillHide to change windowSoftInputMode to adjustPan.
But for temporary solution I create animation using scheduleLayoutAnimation in keyboardDidHide, it feels more convenient.

For more investigation, what I found this problem just occurred in Android 10 and below.
Maybe it's [android limitation](https://developer.android.com/develop/ui/views/layout/sw-keyboard#synchronize-animation) 
I create temporary solution only for that versions.

And maybe next week I will create touch/scroll event outside the keyboard, for this I think I can set windowSoftInputMode to adjustPan then hide the keyboard by using keyboard.dismiss().
(I made backhandler event to do this trick but the event didn't called when keyboard is open)

**Comment by danyzor** [comment]
Any solutions? :(

**Comment by fukemy** [comment]
the solution is `useAnimatedKeyboard`

**Comment by BuqiLiao** [comment]
@fukemy  Could you be more specific?

**Comment by hummingbird1602** [comment]
i just use reanimated for smooth animation. but flatlist reload everytime when scroll and it make performance problem

**Comment by sirusbaladi** [comment]
big issue for me too.

**Comment by kesha-antonov** [comment]
Hi

Please try my PR : `"react-native-gifted-chat": "kesha-antonov/react-native-gifted-chat#b5cb72376505e78a1f03a0cb6937bf6ff01b6c23"`
