### ISSUE TITLE
Attempted to remove more RCTKeyboardObserver listeners than added

### ISSUE THREAD

**Issue by anmoljain10** [FaridSafi/react-native-gifted-chat#2199]
#### 

Hi, I have a chat application for which I'm using this package. I am getting this error when a person leaves the chat.

#### Steps to Reproduce / Code Snippets

As soon as the gifted chat screen was unmounted/we went to the previous screen (chats screen), the above error popped up.

<img width="454" alt="Screenshot 2022-05-06 at 1 10 01 PM" src="https://user-images.githubusercontent.com/43952573/167089903-bd5ddbb1-3ccd-489d-a6d5-9c78a730650e.png">

#### Expected Results

It should not throw an error.

#### Additional Information

* React version: 17.0.2
* React Native version: v0.68.1
* react-native-gifted-chat version: v0.16.3
* Platform(s) (iOS, Android, or both?): Both

**Comment by juergengunz** [comment]
same, any idea how to fix?

**Comment by anmoljain10** [comment]
I found this: https://stackoverflow.com/questions/70579490/react-native-randomly-crashes-with-error-attempted-to-remove-more-rctkeyboardob

**Comment by juergengunz** [comment]
@anmoljain10 thx man, works

**Comment by Johan-dutoit** [comment]
@anmoljain10 @juergengunz  I'd suggest bumping to the latest bet and try again.  Should be okay.

**Comment by mostafahazim** [comment]
for anyone having this issue with the latest version this is the needed diff
`diff --git a/node_modules/react-native-gifted-chat/lib/InputToolbar.js b/node_modules/react-native-gifted-chat/lib/InputToolbar.js
index 2ff651d..12b7cfc 100644
--- a/node_modules/react-native-gifted-chat/lib/InputToolbar.js
+++ b/node_modules/react-native-gifted-chat/lib/InputToolbar.js
@@ -26,11 +26,11 @@ const styles = StyleSheet.create({
 export function InputToolbar(props) {
     const [position, setPosition] = useState('absolute');
     useEffect(() => {
-        const keyboardWillShowListener = Keyboard.addListener('keyboardWillShow', () => setPosition('relative'));
-        const keyboardWillHideListener = Keyboard.addListener('keyboardWillHide', () => setPosition('absolute'));
+        Keyboard.addListener('keyboardWillShow', () => setPosition('relative'));
+        Keyboard.addListener('keyboardWillHide',  () => setPosition('absolute'));
         return () => {
-            keyboardWillShowListener === null || keyboardWillShowListener === void 0 ? void 0 : keyboardWillShowListener.remove();
-            keyboardWillHideListener === null || keyboardWillHideListener === void 0 ? void 0 : keyboardWillHideListener.remove();
+            Keyboard.removeAllListeners('keyboardDidHide');
+            Keyboard.removeAllListeners('keyboardDidShow');
         };
     }, []);
     const { containerStyle, ...rest } = props;
`
