### ISSUE TITLE
react-native-keyboard-aware-scroll-view broken on latest iOS sdk and updated reactnative version

### ISSUE THREAD

**Issue by masudhossain** [FaridSafi/react-native-gifted-chat#2202]
#### Issue Description
Gifted chat uses https://github.com/APSL/react-native-keyboard-aware-scroll-view which hasn't been updated since 2021 and has issues with the latest IOS sdk. You'll get error below. So i recommend giftedchat use a different solution for the keyboard scroll. 

![image](https://user-images.githubusercontent.com/16615124/167271706-4ee5f9a0-1dd8-453a-b934-9a7ab6e2e39d.png)

#### Steps to Reproduce / Code Snippets
Install latest ios SDK and xcode. Try to chat using giftedchat. 

#### Expected Results
To work 

#### Additional Information

* Nodejs version: v14.16.1
* React version: `"react": "17.0.2",`
* React Native version: `"react-native": "0.68.1",`
* react-native-gifted-chat version: `"react-native-gifted-chat": "^0.16.3",`
* Platform(s) (iOS, Android, or both?): `iOS`
* TypeScript version: `"typescript": "~4.3.5"`

**Comment by Johan-dutoit** [comment]
@masudhossain it isn't being used in the beta, if you'd like to transition to that.
