### ISSUE TITLE
Question: Any way to hide completely the input view area?

### ISSUE THREAD

**Issue by bvelasquez** [FaridSafi/react-native-gifted-chat#2204]
#### Issue Description

I'd like to set renderInputToolbar to null and have the entire space taken up by messages. However, it seems to leave an area with the same height as the input controls. I'd like to have that area have a height of zero so that the user can only read messages, not send any messages. Any ideas?
 
#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

![2022-05-20_13-55-56](https://user-images.githubusercontent.com/2302210/169609409-a15361b2-ec58-431d-b6b5-6a5695f5d89b.png)

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by fukemy** [comment]
as u can see in. source code, if props.input... == null it's return defaultInputToolbar

**Comment by bvelasquez** [comment]
I'm not following. I want to completely remove the InputToolbar area. Basically, hide it completely because of a permissions setting in the application. The user can view the messages, but cannot enter a new message.

**Comment by bvelasquez** [comment]
nvm, figured something out. Thanks.

**Comment by doublethefish** [comment]
what did you figure out?

**Comment by ScreamZ** [comment]
@bvelasquez Interested in your solution

**Comment by Hatko** [comment]
If anyone comes across this issue, setting `minInputToolbarHeight` to `0` hides it
