### ISSUE TITLE
Android enhancement: Keyboard smooth animation

### ISSUE THREAD

**Issue by fukemy** [FaridSafi/react-native-gifted-chat#2205]
Hi, i found this lib and topic explain how to get smoother when keyboard show, can it's apply for GiftedChat?

https://saket.me/smoothly-reacting-to-keyboard/

 https://github.com/saket/FluidKeyboardResize

**Comment by kesha-antonov** [comment]
I think it's possible with https://github.com/software-mansion/react-native-reanimated

**Comment by fukemy** [comment]
i done it, thanks

**Comment by devartwa** [comment]
@fukemy how did you do that? could you share? I'm trying to do a smooth animation on android and it's not working.
