### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNCSafeAreaProvider

### ISSUE THREAD

**Issue by peterjskaltsis** [FaridSafi/react-native-gifted-chat#2223]
#### Issue Description

👋  Wondering if anyone has come across the error when working in a project with both **this package** and `react-native-safe-area-context` installed:

```
[Invariant Violation: Tried to register two views with the same name RNCSafeAreaProvider, js engine: hermes
``` 

I've kept the issue description minimal because there's a detailed post and solution posted in **[this StackOverflow post](https://stackoverflow.com/questions/72469920/invariant-violation-tried-to-register-two-views-with-the-same-name-rncsafeareap)**.

#### Additional Information

React Native version: "0.63.4"
react-native-gifted-chat version: "^1.0.1"

**Comment by Hamza-Shafiq-ess** [comment]
Got the same error with expo.

expo version:45.0.0,

**Comment by Bhavesh1236** [comment]
`react-native-safe-area-context` This library is deprecated you can try [react-native-safe-area-view](https://github.com/react-navigation/react-native-safe-area-view).

**Comment by peterjskaltsis** [comment]
Hey @Bhavesh1236, I think you might have this around the other way around 🤔

[`react-native-safe-area-view`](https://github.com/react-navigation/react-native-safe-area-view) is deprecated in favour of [`react-native-safe-area-context`](https://github.com/th3rdwave/react-native-safe-area-context).

<img width="926" alt="Screen Shot 2022-06-27 at 3 12 26 pm" src="https://user-images.githubusercontent.com/4243672/175864603-2ac3fd1e-549c-4ec7-be3e-c8db6502cbef.png">

**Comment by cbridges1** [comment]
This is due to an issue with duplicate packages in the latest release. User Javier has found a solution. https://stackoverflow.com/questions/72469920/invariant-violation-tried-to-register-two-views-with-the-same-name-rncsafeareap/72470161#72470161

**Comment by 000xuandu** [comment]
Pls fix it!

**Comment by monahans** [comment]
Submitted a PR here: https://github.com/FaridSafi/react-native-gifted-chat/pull/2234

**Comment by Johan-dutoit** [comment]
Closing this issue, as the PR was released as 1.0.3.   Do reopen if you're still experiencing the issue.

**Comment by parnekov** [comment]
https://github.com/FaridSafi/react-native-gifted-chat/issues/2251#issuecomment-1211718197

**Comment by julioxus** [comment]
**Important note** if you are building the project in **Expo EAS**: You need to create a hook before compiling the APK to get rid of duplicate libraries, which is causing this error. This is accomplished by adding the following line in the "scripts" section of the package.json:

"eas-build-pre-install: "npm dedupe".

I hope it might help someone who has been frustrated with this problem as much as I have.
