### ISSUE TITLE
can not update message bubble without change this _id

### ISSUE THREAD

**Issue by fukemy** [FaridSafi/react-native-gifted-chat#2226]
Hi, it's just a question, not a bug
I want to edit a message, but it's only updated when i changed this message _id. Can u provide me how to do it, here is my code:
```
const onSend = useCallback((messagesToSend = []) => {
        if(editMessage != null){
            setEditMessage()
            const m = messagesToSend[0]
            const newMessages = [...messages]
            const index = newMessages.findIndex(mes => mes._id === editMessage._id);
            console.log('index: ', index)
            if(index > -1){
                newMessages[index].text = m.text => ***i only edit the text***
                //newMessages[index]._id = uuid.v4() => ***this working if changed _id***
                console.log('newMessages', newMessages[index]) => ***new message changed it's text but the bubble not change when re-render***
                LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut)
                setMessage(newMessages)
            }
        }else{
            setReplyMessage()
            appendMessage(messagesToSend)
        }
    })
```

**Comment by fukemy** [comment]
@FaridSafi hi, can u help?

**Comment by waelvilla** [comment]
have you tried removing the `useCallback` ? I tried doing what you're describing and it seems to work here https://snack.expo.dev/4acFsrqjk 
Is there any more relevant code we can look at?

**Comment by waelvilla** [comment]
I removed the `useCallback` again from the `onSend` on the snack you last posted and it still works. https://snack.expo.dev/UyrcQELU8
Can you elaborate on why you need it?

**Comment by fukemy** [comment]
> I removed the `useCallback` again from the `onSend` on the snack you last posted and it still works. https://snack.expo.dev/UyrcQELU8 Can you elaborate on why you need it?

thanks for your help, im know the problem now, because im using version 0.16.3, switch to 1.0.2 and it's work fine
