### ISSUE TITLE
Please Help when i run npx react-native start this error will show

### ISSUE THREAD

**Issue by mamonaabdullah122** [FaridSafi/react-native-gifted-chat#2237]
WARN  The "EXNativeModulesProxy" native module is not exported through NativeModules; verify that expo-modules-core's native code is linked properly
 WARN  No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?

**Comment by suyashvash** [comment]
Try deleting the `node_modules` folder and run `npm install` again. 
It usually happens due to improper module installation.

**Comment by mamonaabdullah122** [comment]
when i  deleting the node_modules folder and run npm install this error will show:

 WARN  expo-app-loading is deprecated in favor of expo-splash-screen: use SplashScreen.preventAutoHideAsync() and SplashScren.hideAsync() instead.

**Comment by suyashvash** [comment]
> 

Well that's because it is depreciated now. Read this doc - https://docs.expo.dev/versions/latest/sdk/app-loading/

**Comment by suyashvash** [comment]
> Please help this error sorry WARN The "EXNativeModulesProxy" native module is not exported through NativeModules; verify that expo-modules-core's native code is linked properly WARN No native ExponentConstants module found, are you sure the expo-constants's module is linked properly? WARN The "EXNativeModulesProxy" native module is not exported through NativeModules; verify that expo-modules-core's native code is linked properly WARN Require cycle: node_modules/expo-google-app-auth/node_modules/expo-modules-core/build/index.js -> node_modules/expo-google-app-auth/node_modules/expo-modules-core/build/sweet/setUpErrorManager.fx.js -> node_modules/expo-google-app-auth/node_modules/expo-modules-core/build/sweet/NativeErrorManager.js -> node_modules/expo-google-app-auth/node_modules/expo-modules-core/build/index.js
> 
> Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle. WARN No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?

Try running this command `expo install expo-constants`

**Comment by mamonaabdullah122** [comment]
I run this command expo install expo-constants but this is not work for me. This warning is show:
Please help I want to remove this warning
 WARN  The "EXNativeModulesProxy" native module is not exported through NativeModules; verify that expo-modules-core's native code is linked properly

**Comment by ARJ-enapsys** [comment]
Hi, I have a similar error and 'expo install expo-constants' doesn't work for me, this is my error:

WARN  No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?
 ERROR  Error: Expo native runtime is not available: something went wrong and we aren't sure what it was. Please post more information and get support at https://forums.expo.dev.  
 ERROR  Invariant Violation: Module AppRegistry is not a reghat the application entry file path is incorrect.orrect.                                   dle is corrupt or 
      This can also happen when the JS bunn loading React Nadle is corrupt or there is an early initialization error when loading React Native. istry is not a reg
 ERROR  Invariant Violation: Module AppRegation). A frequentistry is not a registered callable module n entry file path 
(calling runApplication). A frequent cause of the error is that the application entrdle is corrupt or y file path is incorrect.                 n loading React Na
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Comment by Holes70** [comment]
Maybe this will help some of you. [](https://stackoverflow.com/a/75596783/16545223)
