### ISSUE TITLE
GiftedChat has not been registered. This is either due to a required() error during initialization or failure to call AppRegistry.registerComponent

### ISSUE THREAD

**Issue by suryaiiit** [FaridSafi/react-native-gifted-chat#224]
Hi,

This is what I get when I'm trying to run the example as given in the README:

GiftedChat has not been registered. This is either due to a required() error during initialization or failure to call AppRegistry.registerComponent

& in the xcode console I see this:-

[tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: Application GiftedChat has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.
2016-09-03 16:39:10.654 [error][tid:com.facebook.react.RCTNetworkingQueue][RCTEventEmitter.m:77] `didReceiveNetworkIncrementalData` is not a supported event type for RCTNetworking. Supported events are: `didCompleteNetworkResponse`, `didReceiveNetworkResponse`, `didSendNetworkData`, `didReceiveNetworkData`
2016-09-03 16:39:10.660 [error][tid:com.facebook.react.RCTNetworkingQueue][RCTEventEmitter.m:77] `didReceiveNetworkDataProgress` is not a supported event type for RCTNetworking. Supported events are: `didCompleteNetworkResponse`, `didReceiveNetworkResponse`, `didSendNetworkData`, `didReceiveNetworkData`

Any help would be appreciated, thanks.

**Comment by alexanderniebuhr** [comment]
Same err for me.

Any fix or workaround?

**Comment by devbriguy** [comment]
Can you post code of your implementation of the module?

**Comment by alexanderniebuhr** [comment]
`import { GiftedChat } from 'react-native-gifted-chat';

class Example extends React.Component {
  constructor(props) {
    super(props);
    this.state = {messages: []};
    this.onSend = this.onSend.bind(this);
  }
  componentWillMount() {
    this.setState({
      messages: [
        {
          _id: 1,
          text: 'Hello developer',
          createdAt: new Date(Date.UTC(2016, 7, 30, 17, 20, 0)),
          user: {
            _id: 2,
            name: 'React Native',
            avatar: 'https://facebook.github.io/react/img/logo_og.png',
          },
        },
      ],
    });
  }
  onSend(messages = []) {
    this.setState((previousState) => {
      return {
        messages: GiftedChat.append(previousState.messages, messages),
      };
    });
  }
  render() {
    return (
      <GiftedChat
        messages={this.state.messages}
        onSend={this.onSend}
        user={{
          _id: 1,
        }}
      />
    );
  }
}`

I used your example. I had installed the Gifted Messenger before. Deleted it and installed the Gifted Chat. Changed the state and methods as you said in the Example, and hoped it works. But it does not.

I really don't want to rewrite the whole class (1800 lines) :/

**Comment by FaridSafi** [comment]
Hello
If you are talking about the example code of the README, be sure to use `AppRegistry.registerComponent` properly in your project.
You can see the [Example](https://github.com/FaridSafi/react-native-gifted-chat/tree/master/example)  for a working example project.

**Comment by alexanderniebuhr** [comment]
I talk about following Example:

<img width="1007" alt="screencapture_1" src="https://cloud.githubusercontent.com/assets/15894713/18378007/8f690f7a-766a-11e6-836c-b600f74df3da.png">

**Comment by suryaiiit** [comment]
I just downloaded the zip file and went to the Example folder and followed the instructions:

git clone https://github.com/FaridSafi/react-native-gifted-chat
cd react-native-gifted-chat/example
npm install
react-native run-ios

This is giving the error.

**Comment by FaridSafi** [comment]
@suryaiiit are you running the packager of the example project and not other project?

**Comment by alexanderniebuhr** [comment]
For the downloaded 'example' folder i don't get the error. I get the error when implementing the react-native-gifted-chat to my own project

**Comment by FaridSafi** [comment]
@alexanderniebuhr Be sure to `export default class` and `AppRegistry.registerComponent ` properly like in the example project

**Comment by alexanderniebuhr** [comment]
@FaridSafi this is my index.ios.js. It Is linked to the Navigator.js and from that I have different pages, one including the gifted chat: 
![screencapture-2](https://cloud.githubusercontent.com/assets/15894713/18378179/b1773ea6-766b-11e6-8b8c-7d55b85068fb.png)

**Comment by suryaiiit** [comment]
yes, packer of the example. Just the code from this project.

**Comment by alexanderniebuhr** [comment]
Any suggestions for My Problem?

**Comment by FaridSafi** [comment]
@alexanderniebuhr you can try to use `import` instead of `require`

**Comment by alexanderniebuhr** [comment]
@FaridSafi ok. And do i have to put the "Export default class" in My navigator.js or where?

**Comment by FaridSafi** [comment]
`export default` should be used with `import`

**Comment by alexanderniebuhr** [comment]
@FaridSafi so in every Class???

**Comment by FaridSafi** [comment]
yes, this issue is not related to GiftedChat so I close this thread.

**Comment by alexanderniebuhr** [comment]
Ok thanks. Go ahead closing it :) I ll test it later and open new Issues if nessecary

**Comment by alexanderniebuhr** [comment]
Hello friend, 


I  just wanted to share with you some pics of my favourite place,  it;s so awesome! Here is  the link  for  the  pics <http://compare.farrelljchiles.com/e8kewx>

Warm regards, Alexander

**Comment by alexanderniebuhr** [comment]
Hello friend, 


My friends have made a  nice surprise to me, just take a look, it's awesome <http://reach.pinkelephantsdesigns.com/e8nonu>

Alexander

**Comment by alexanderniebuhr** [comment]
Hello, 


I found some extremely useful  stuff and it  was  a real  discovery for  me,  just give  it  a try! You may  find  more information here <http://valentino.pitslre.com/e8cbg/4>

Alexander Niebuhr

**Comment by kfiroo** [comment]
Anyone knows how to report spam to github?
