### ISSUE TITLE
Send button still showing even when text input is set to ' ' after sending a message

### ISSUE THREAD

**Issue by SectionTN** [FaridSafi/react-native-gifted-chat#2262]
#### Issue Description

Send button still showing even when text input is set to ' ' after sending a message

#### Steps to Reproduce / Code Snippets

```
<GiftedChat
          text={mMessageText}
....
 onSend={messages => {
            sendMessage(messages);
            setMessageText('');
          }}
....
/>
```

#### Expected Results

send button should be not showing after `setMessageText('')` 

#### Additional Information

* Nodejs version: 18/stable
* React version: 18.2.0
* React Native version: 0.69.4
* react-native-gifted-chat version: 1.0.4
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: JS project

**Comment by fukemy** [comment]
them how did you render send button based on ***mMessageText***??

**Comment by SectionTN** [comment]
@fukemy 
it's here please see the code snippet
https://github.com/MoonMeet/MoonMeet-CrossPlatform/blob/main/src/screens/ChatScreen.js#L529-L544

**Comment by fukemy** [comment]
U need render Send button if props.text is not empty

**Comment by SectionTN** [comment]
got you, thanks
