### ISSUE TITLE
Tried to register two views with same name in RNCsafeareaview

### ISSUE THREAD

**Issue by Jauhar97** [FaridSafi/react-native-gifted-chat#2267]
#### Issue Description

when I install gifted chat in my react native project It shows an error tried to register two views with the same name RNCsafeareavie

#### Steps to Reproduce / Code Snippets

import { StyleSheet, Text, View } from 'react-native'
import React, {useState, useEffect, useCallback} from 'react'
import LinearGradient from 'react-native-linear-gradient'
import AntDesign from 'react-native-vector-icons/AntDesign'
import { GiftedChat } from 'react-native-gifted-chat'
export default function ChatScreen() {
  const [messages, setMessages] = useState([]);

  useEffect(() => {
    setMessages([
      {
        _id: 1,
        text: 'Hello developer',
        createdAt: new Date(),
        user: {
          _id: 2,
          name: 'React Native',
          avatar: 'https://placeimg.com/140/140/any',
        },
      },
    ])
  }, [])

  const onSend = useCallback((messages = []) => {
    setMessages(previousMessages => GiftedChat.append(previousMessages, messages))
  }, [])
  return (
   
        <GiftedChat
      messages={messages}
      onSend={messages => onSend(messages)}
      user={{
        _id: 1,
      }}
    />
    
  )
}

const styles = StyleSheet.create({
 
  
})

#### Expected Results

stuck over this some kindly anyone solves this

#### Additional Information

* Nodejs version: 16.16.0
* React version:18.0.0
* React Native version: 0.69.4
* react-native-gifted-chat version: ^1.0.4
* Platform(s) (iOS, Android, or both?):android 

![Capturertt](https://user-images.githubusercontent.com/50345582/185757292-1cbae7e2-c8db-4d65-93df-8c354693dabf.JPG)

**Comment by harmochiky** [comment]
The problem happens because the react-native-safe-area-context in your project is different from the react-native-safe-area-context used by the gifted chat. Normally the problem appears after you upgrade the gifted chat to a newer version

To fix this try the 2 solutions below. 
1. run `npm dedupe`
2. Go to the package.json for  react-native-gifted-chat in the nodemodules then check the react-native-safe-area-context version then install that in your project then run npm dedupe

cheers :)

**Comment by fregayeg** [comment]
Hello! I've got same issue here! Following the suggestion of @harmochiky , I tried to update the ``react-native-safe-area-context`` version to a recent version. But, this makes me face an issue with Expo sdk 45 (managed). Now I face this warning each time I run the server, and I feel unsafe : 
```
 - react-native-safe-area-context - expected version: 4.2.4 - actual version installed: 4.3.4
```
What should I do in this case ? :(

**Comment by Johan-dutoit** [comment]
Should be fixed with https://github.com/FaridSafi/react-native-gifted-chat/pull/2353 and https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/v2.0.0
