### ISSUE TITLE
Allow QuickReplies component container styles to be customised

### ISSUE THREAD

**Issue by rajatkantinandi** [FaridSafi/react-native-gifted-chat#2270]
#### Issue Description

Currently QuickReplies component container styles are hard-coded here: https://github.com/FaridSafi/react-native-gifted-chat/blob/04845b02e88365b18385adab7450fb4a1a515a18/src/QuickReplies.tsx#L135
So, it is impossible to customize it.

Some use cases are:
- Rendering quick replies on the right side rather than left side by default.
- Making the quick replies wider if needed (e.g. on web).
- Making quick replies render vertically always rather than rendering in one row by default & wrapping.

#### Expected Results

QuickReplies component container should be customizable.

#### Additional Information

* Nodejs version: 16.15.0
* React version: 17.0.2
* React Native version: 0.64.3
* react-native-gifted-chat version: 1.0.4
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: 4.7.2

**Comment by arunpugahz** [comment]
Please merge this

**Comment by rajatkantinandi** [comment]
Hi, I don't have merge permissions. Can you do it from your end? Thanks.
![Screenshot 2024-02-05 at 2 02 03 PM](https://github.com/FaridSafi/react-native-gifted-chat/assets/17743895/51a12dbd-71ca-498b-b83f-431f341785bb)
