### ISSUE TITLE
Getting extra space on left side chat messages.

### ISSUE THREAD

**Issue by rohank45** [FaridSafi/react-native-gifted-chat#2274]
![image](https://user-images.githubusercontent.com/77183753/186664302-76f7c14b-4808-46b3-8685-cac5ba8663ad.png)

**Comment by rohankurane45** [comment]
> did u modified the example? It's seem the render avatar cause problem

<GiftedChat
            // alwaysShowSend
            isAnimated
            scrollToBottom={true}
            inverted={false}
            // infiniteScroll={true}
            // isKeyboardInternallyHandled={false}
            // keyboardShouldPersistTaps="never"
            // bottomOffset={0}
            user={{
              _id: senderId,
            }}
            textInputProps={{
              autoCorrect: false,
            }}
            listViewProps={{
              // nestedScrollEnabled: true,
              contentContainerStyle: {
                flex: 1,
                justifyContent: 'flex-end',
                marginBottom: 10,
              },
            }}
            text={allocated_sellers?.toString().replace(/,/g, '')}
            messages={messages.sort(
              (a, b) => Date.parse(a.createdAt) - Date.parse(b.createdAt),
            )}
            onLongPress={onLongPress}
            onSend={messages => handleSendMsg(messages)}
            onDelete={messages => handleDeleteMsg(messages)}
            renderAvatar={() => null}
            renderBubble={renderBubble}
            renderSend={renderSend}
            renderInputToolbar={props => customtInputToolbar(props)}
          />

**Comment by rohankurane45** [comment]
> did u modified the example? It's seem the render avatar cause problem

<GiftedChat
// alwaysShowSend
isAnimated
scrollToBottom={true}
inverted={false}
// infiniteScroll={true}
// isKeyboardInternallyHandled={false}
// keyboardShouldPersistTaps="never"
// bottomOffset={0}
user={{
_id: senderId,
}}
textInputProps={{
autoCorrect: false,
}}
listViewProps={{
// nestedScrollEnabled: true,
contentContainerStyle: {
flex: 1,
justifyContent: 'flex-end',
marginBottom: 10,
},
}}
text={allocated_sellers?.toString().replace(/,/g, '')}
messages={messages.sort(
(a, b) => Date.parse(a.createdAt) - Date.parse(b.createdAt),
)}
onLongPress={onLongPress}
onSend={messages => handleSendMsg(messages)}
onDelete={messages => handleDeleteMsg(messages)}
renderAvatar={() => null}
renderBubble={renderBubble}
renderSend={renderSend}
renderInputToolbar={props => customtInputToolbar(props)}
/>

in my case there is no avatar images

**Comment by rohank45** [comment]
> did u modified the example? It's seem the render avatar cause problem

In my case there is no avatar.

**Comment by fukemy** [comment]
post some pieces of code, u only add some picture without code, that make other people do not know the reason, but i guess it's is avatar padding problem

**Comment by rohank45** [comment]
> post some pieces of code, u only add some picture without code, that make other people do not know the reason, but i guess it's is avatar padding problem

The issue is solved now, I was using this line,
 // renderAvatar={() => null}
instead of this,
renderAvatar={null}.
