### ISSUE TITLE
TextInput has different defaults for iphone 12 and iphone 6s

### ISSUE THREAD

**Issue by kelechionyeama** [FaridSafi/react-native-gifted-chat#2275]
Hello, before I say anything, I just want to say thank you to the whole team for working and provinf this amazing package to us all.
Here is the default i get viewing the text input on 2 devices. iphone 12 and iphone 6s. iphone 12 by default has its text input way above the keyboard while the 6s is okay on default. on adjust bottom inset, iphone 12 is good and 6s is bad. please help
![iphone 6s regular](https://user-images.githubusercontent.com/95096241/187055261-455d3131-664e-47a0-84a5-29f7f313ddb9.PNG)
![iphone 12 regular](https://user-images.githubusercontent.com/95096241/187055265-8fa9e4af-12f9-462f-a057-1cbea27332eb.PNG)
![iphone 6s on adjust](https://user-images.githubusercontent.com/95096241/187055266-0ff922c5-e08a-47c0-b7b7-5dbbe8568d99.JPEG)
![iphone 12 on adjust](https://user-images.githubusercontent.com/95096241/187055268-b4fac52d-6018-4aad-a24f-af934fc9ae24.PNG)

**Comment by Yogesh-Dubey-Ayesavi** [comment]
Can you provide some code just screenshots are not enough ?

**Comment by kelechionyeama** [comment]
const renderBubble = (props) => {
        return (
            <Bubble 
                {...props}
                wrapperStyle={{ 
                    right: {
                        backgroundColor: "#1D92D7",
                        
                    },
                    left: {
                        backgroundColor: "#E3E3E3"
                    }
                }}
                textStyle={{
                    right: {
                        fontFamily: "LeagueSpartan_Regular",
                        fontSize: 18
                    },
                    left: {
                        fontFamily: "LeagueSpartan_Regular",
                        fontSize: 18
                    }
            }}
            />
        )
    }

    const renderSend = (props) => {
        return (
            <Send {...props}>
                <Ionicons name="md-send" size={24} style={{ marginBottom: 6 }} color="black" />
            </Send>
        )
    }

    const renderActions = (props) => {
        return (
            <Actions
                {...props}
                onPressActionButton={() => console.log("pressed")}
                icon={() => (
                    <MaterialIcons name="photo-library" size={24} color="black" />
                )}
            />
        )
    }

    const scrollToBottomComponent = () => {
        return (
            <MaterialCommunityIcons name="chevron-double-down" size={36} color="black" />
        )
    }

    
    return (

        <View style={{ flex: 1, backgroundColor: "white" }}>
    
            <GiftedChat
                
                messages={messages}
                onSend={messages => onSend(messages)}
                user={{
                _id: 1,
                }}            
                renderBubble={renderBubble}
                renderSend={renderSend}
                scrollToBottom
                scrollToBottomComponent={scrollToBottomComponent}
                renderActions={renderActions}
                textInputStyle={{
                    backgroundColor: '#fff',
                    borderRadius: 20,
                  }}
            />
        </View>
    )

this is the default code that thats ok for the 6s but way to high for iphone 12 and below is the edited code, its the same, only difference is the bottomoffset



        <View style={{ flex: 1, backgroundColor: "white" }}>
    
            <GiftedChat
                
                messages={messages}
                onSend={messages => onSend(messages)}
                user={{
                _id: 1,
                }}  
                bottomOffset={30}          
                renderBubble={renderBubble}
                renderSend={renderSend}
                scrollToBottom
                scrollToBottomComponent={scrollToBottomComponent}
                renderActions={renderActions}
                textInputStyle={{
                    backgroundColor: '#fff',
                    borderRadius: 20,
                  }}
            />
        </View>

**Comment by Yogesh-Dubey-Ayesavi** [comment]
Instead of this wrapping it in another giving it a margin at bottom works for me fine have you tried that ?

**Comment by fukemy** [comment]
use SafeAreaContext like this:

const inset = useSafeAreaInsets()
=> bottomOffset={inset.bottom}

**Comment by kelechionyeama** [comment]
> 
Solved using this, thanks so much!

**Comment by fukemy** [comment]
u need to check in Android too
