### ISSUE TITLE
Bubble height issue on Android

### ISSUE THREAD

**Issue by alxndr777** [FaridSafi/react-native-gifted-chat#2280]
Hi, Can you help me to solve this bubble height issue on Android. Works fine on ios.

<img width="699" alt="Screen Shot 2022-09-09 at 4 16 48 AM" src="https://user-images.githubusercontent.com/15268716/189304993-98f9de57-4db9-4bfa-ab8b-74ec43e6fb42.png">

**Comment by fukemy** [comment]
strange problem, could u reproduce it's in snack?

**Comment by alxndr777** [comment]
Was able to resolve it by using CustomView property. Thank you

**Comment by fukemy** [comment]
Hi, can u explain more, im got same problem now

**Comment by fukemy** [comment]
I got this problem because LayoutAnimation, when screen animated I navigate to other screen => Animation cause this problem. I can not find anyway to solve this
