### ISSUE TITLE
lineHeight in MessageText cause emojis to cut

### ISSUE THREAD

**Issue by kfiroo** [FaridSafi/react-native-gifted-chat#229]
#### Issue Description

Looks like the `lineHeight` here https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/MessageText.js#L71 causes emojis in the top row to cut.

Removing this line seems to fix it btw.

@FaridSafi can we safely remove it or does it have a purpose?
#### Steps to Reproduce / Code Snippets

![image](https://cloud.githubusercontent.com/assets/284636/18368834/152208f4-75f0-11e6-8bc1-ff954a65368c.png)
#### Expected Results

Not to cut :)
#### Additional Information
- Platform: iOS

**Comment by FaridSafi** [comment]
@kfiroo maybe we can increase a little lineHeight value ?

**Comment by kfiroo** [comment]
@FaridSafi Do we need it?
Without it, it looks like every line sets it's own line height

**Comment by ChristianTucker** [comment]
@kfiroo  Removing the lineHeight causes the bottom of emojis to cut off, when only a single line of text is present. Increasing the Line-height to `(fontSize + 8)` seems to solve all Emoji issues I've run into with React native's text component. 

For example, here setting the lineHeight to 24 (16+8) solves the problem of cutting emojis on the top and bottom. 

![simulator screen shot sep 21 2016 11 26 20 pm](https://cloud.githubusercontent.com/assets/21312394/18737072/f9ec1300-8052-11e6-9866-03f0e5a5d630.png)

```
const textStyle = {
  fontSize: 16,
  lineHeight: 24,
  marginTop: 5,
  marginBottom: 5,
  marginLeft: 10,
  marginRight: 10,
};
```

**Comment by booboothefool** [comment]
Would be great if this was merged. 👍

**Comment by booboothefool** [comment]
Please merge this. 👍

**Comment by snsekar** [comment]
@kfiroo @FaridSafi Can you please help me to add emoji in message text.  I couldn't find any documentation. Is emojis bundled in this package? Or should i use external emoji icons? Which renderXXX method i should use?

Thanks in advance

**Comment by kfiroo** [comment]
AFAIK emojis are just text, you don't have to do anything to get it to work

**Comment by snsekar** [comment]
@kfiroo Sorry i couldn't get you. I am trying in Android 4.2.2. Still I am not getting emojis. What text i should use to get emojis on chat message?

![screenshot_2016-12-26-21-03-56](https://cloud.githubusercontent.com/assets/5658203/21483872/93df2874-cbaf-11e6-8a5b-924b27413693.png)

**Comment by kfiroo** [comment]
@snsekar If you type in an emoji char then it should be an emoji ⛄️. if you type in ":-)" it shouldn't be an emoji

**Comment by snsekar** [comment]
Ok thanks @kfiroo . But i am not getting emoji char in keyboard. It is just normal standard keyboard.

**Comment by snsekar** [comment]
@kfiroo Sorry, that was my mistake. Emojis supported from Android 4.4 only. It is working fine. Thanks for your time.

**Comment by kfiroo** [comment]
@snsekar no problem, good luck!

**Comment by neilsarkar** [comment]
Increasing the line height messes with the readability of longer messages. We changed

```js
  marginTop: 5,
  marginBottom: 5,
```

to 

```js
  marginTop: 1,
  marginBottom: 1,
  paddingTop: 4,
  paddingBottom: 4
```

and are satisfied with the results:

![image_uploaded_from_ios_720](https://cloud.githubusercontent.com/assets/83109/22407536/368909f8-e660-11e6-8d39-5f784cec02ab.jpg)

**Comment by kfiroo** [comment]
@neilsarkar Thanks! can you post images of the same messages using the old `margin` style for comparison?
Thanks :)

**Comment by neilsarkar** [comment]
Sure, here they are. I just discovered that this is only an issue on iOS 9. The screenshot from last night is iOS 9 with `margin` changed to `padding`. Here's what the current styles look like on iOS 9.

![image_uploaded_from_ios_1024](https://cloud.githubusercontent.com/assets/83109/22431087/3262723a-e708-11e6-9b44-5db54a713233.jpg)

**Comment by xcarpentier** [comment]
@kfiroo did it fixed?
