### ISSUE TITLE
Display messages from the top

### ISSUE THREAD

**Issue by maxs15** [FaridSafi/react-native-gifted-chat#230]
Most of the messaging apps display the messages from the top.
So I was wondering, why is this component doing the opposite ? (If you send a message it will appear near the Input instead of the topbar)
It could be a property to implement, what do you think @FaridSafi.

Thanks

**Comment by FaridSafi** [comment]
Hello, please see https://github.com/FaridSafi/react-native-gifted-chat/issues/181

**Comment by maxs15** [comment]
Ohh, thanks for such a quick answer 👍
