### ISSUE TITLE
Chat scroll super laggy on Android, works great on iOS

### ISSUE THREAD

**Issue by swaroopbutala** [FaridSafi/react-native-gifted-chat#2302]
#### Issue Description

I am using gifted chat, and I am seeing very laggy scroll for android Pixel 6. It works flawlessly on iOS. 

I tried following steps suggested in here to create a patch for react native 
https://github.com/FaridSafi/react-native-gifted-chat/issues/2127 
https://github.com/facebook/react-native/issues/30034#issuecomment-806396274 

What worked was the lag went away. But now I see a weird behavior for the chat messages w.r.t ordering as shown in the video here. 

When I create the new message it shows up at the top of the screen, rather than bottom of the screen. 

https://user-images.githubusercontent.com/5388679/203915337-781c0b18-c8ac-4d46-88cf-24517da69475.mp4

#### Additional Information

* Nodejs version: v14.15.3
* React version: "18.1.0"
* React Native version: 0.70.5
* react-native-gifted-chat version: 1.0.4
* Platform(s) (iOS, Android, or both?): Android, works great on iOS.

**Comment by DanStevensonDev** [comment]
@swaroopbutala - I saw your issue which seems possibly related to mine. 

I've raised my issue/fix here: https://github.com/FaridSafi/react-native-gifted-chat/issues/2306

Hope this helps you fix your Android 13 lag issue — would be interested to hear if it does.

**Comment by swaroopbutala** [comment]
Thanks @DanStevensonDev I found the fix, turned out scaleY was deprecated from ReactNative 0.70 which was causing my list to be inverted. 

https://github.com/facebook/react-native/issues/30034#issuecomment-1374355184 This fixed my issue.
