### ISSUE TITLE
TypeError: Cannot read property 'SafeAreaView' of undefined

### ISSUE THREAD

**Issue by ahmedfouad01099** [FaridSafi/react-native-gifted-chat#2304]
#### Issue Description

TypeError: Cannot read property 'SafeAreaView' of undefined

This error is located at:
    in GiftedChat (at ChatThread/index.js:85)
    in ChatThread (at CustomerSupportChat/index.js:9)
    in RCTView (at View.js:32)
    in View (at CustomerSupportChat/index.js:8)
    in CustomerSupportChat (at ContactUsDetailChat/index.js:12)
    in ContactUsDetailChat (at SceneView.tsx:132)

#### Steps to Reproduce / Code Snippets

yarn add react-native-gifted-chat
then try to open screen which contain gifted-chat error occurs

#### Expected Results

just work fine

#### Additional Information

* Nodejs version: 16.13.0
* React version: 17.0.2
* React Native version: 0.68.2
* react-native-gifted-chat version: ^1.0.4
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: 4.6.4
![simulator_screenshot_6A9F8954-C636-41EA-94AE-146D0CADC428](https://user-images.githubusercontent.com/63275575/204235183-8367d672-e520-4561-9213-420cf5e768f3.png)

**Comment by levepic** [comment]
npm rm react-native-safe-area-context
npm i react-native-safe-area-context
solved it for me!

**Comment by ahmedfouad01099** [comment]
I fixed it on this Fork:
https://www.npmjs.com/package/@ahmedfouad2255/react-native-gifted-chat

**Comment by sadia-onyxtec** [comment]
https://stackoverflow.com/questions/72469920/invariant-violation-tried-to-register-two-views-with-the-same-name-rncsafeareap
