### ISSUE TITLE
too much space on InputToolBar 

### ISSUE THREAD

**Issue by patrinoua** [FaridSafi/react-native-gifted-chat#2307]
#### Issue Description

Too much space on InputToolBar

The code
![Screenshot 2022-11-30 at 11 17 58 PM](https://user-images.githubusercontent.com/36475005/204920246-341a7520-7446-4d1e-8ef1-df542aa6fc89.png)

The result
![Screenshot 2022-11-30 at 11 14 13 PM](https://user-images.githubusercontent.com/36475005/204919698-c4d48762-b6c5-4350-aa67-b4677eb867c7.png)
![Screenshot 2022-11-30 at 11 14 24 PM](https://user-images.githubusercontent.com/36475005/204919704-9345beea-0b86-4e6a-9c11-ca18580d9f7f.png)

https://user-images.githubusercontent.com/36475005/204920076-29f879bd-41b8-481b-a522-46812e81f77c.MP4

#### Steps to Reproduce / Code Snippets

Just importing Gifted Chat in a component with no other styles except Flex 1
#### Expected Results

- One liner when not selected / empty
- As many lines as required when user is typing

#### Additional Information

* Nodejs version: 16.0.0
* React version: 18.1.0
* React Native version: 0.70.5
* react-native-gifted-chat version: 1.0.4

* Platform(s) (iOS, Android, or both?): ios

**Comment by dawidzawadzki** [comment]
Hey, just set wrapInSafeArea={false}.

**Comment by BlackNightFury** [comment]
@dawidzawadzki Adding `wrapInSafeArea={false}` still does not work

**Comment by red-made** [comment]
bottomOffset has stopped working, someone know how to remove that space?

**Comment by dawidzawadzki** [comment]
@red-made bottomOffset still working for me, weird

**Comment by red-made** [comment]
It worked before that I've updated to the last version due to some incompatibility with newest reactNative version.

**Comment by tianxiaotouyuna** [comment]
the keyboard animate is delay, who has this problem?

**Comment by yslai95** [comment]
This fix the issue so far

1. wrap the screen with <SafeAreaView> 
2.  wrap <KeyboardAvoidingView> and <SafeAreaView style={{ height: '100%' }} edges={['left', 'right']}> right next to the <GiftedChat>
3. Set the following props to GiftedChat


          const insets = useSafeAreaInsets()

          minInputToolbarHeight={isKeyboardShown ? 0 : undefined} // to fix ios to have white space between input and keyboard
          bottomOffset={insets.bottom + 2} // to fix white space for iphone 8 above
          wrapInSafeArea={false}

**Comment by amerikan** [comment]
Update to v2.0.0, SafeArea is no longer included by default.
