### ISSUE TITLE
Why doesnt my footer touch the end

### ISSUE THREAD

**Issue by shop-fluencer** [FaridSafi/react-native-gifted-chat#2319]
#### Issue Description

[FILL THIS OUT]

```
  return (
    <GiftedChat
      messages={messages}
      onSend={messages => onSend(messages)}
      onPressAvatar={handleNavigateToUser}
      user={{
        _id: 1,
      }}
    />
  )

```
[FILL THIS OUT]

Why my footer is not touching the end on iOS ? Look at image bottom

[FILL THIS OUT]

#### Additional Information

* Nodejs version: 16
* React version: expo 47
* React Native version: 0.70
* react-native-gifted-chat version: 1.1.0
* Platform(s) (iOS, Android, or both?): iOS
* TypeScript version: xxx

![WhatsApp Image 2022-12-22 at 15 51 35](https://user-images.githubusercontent.com/101994056/209161057-eb97e8c8-d4a0-4ad9-993a-98151047c6c7.jpeg)

**Comment by fukemy** [comment]
try wrapInSafeArea={false}

**Comment by visaals** [comment]
> try wrapInSafeArea={false}

That works in the simulator on a iPhone SE (thanks!), but not on an iPhone 12 still. Know any other workarounds we could try? Is it to adjust the `bottomOffset={22}` based on the device?

**Comment by fukemy** [comment]
better use like this
const insets = useSafeAreaInset()

bottomInset= insets.bottom

**Comment by Johan-dutoit** [comment]
Should be fixed with https://github.com/FaridSafi/react-native-gifted-chat/pull/2353 and https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/v2.0.0
