### ISSUE TITLE
bottomOffset property doesn't help when using Navigator Header and TabBarIOS

### ISSUE THREAD

**Issue by prabhaav** [FaridSafi/react-native-gifted-chat#232]
#### Issue Description

The chat input box is being hidden by the tab bar.

#### Steps to Reproduce / Code Snippets

My render method:

```
render() {
    return (
      <View style={{flex: 1}}>
        <GiftedChat
          messages={this.state.messages}
          onSend={this.onSend}
          loadEarlier={this.state.loadEarlier}
          user={{
            _id: this.state.id,
            name: this.props.result.first_name,
            avatar: this.props.result.picture,
          }}
          renderBubble={this.renderBubble}
          renderFooter={this.renderFooter}
          bottomOffset={56} 
        />
      </View>
    )
  }
```

<img width="467" alt="screen shot 2016-09-11 at 2 16 28 pm" src="https://cloud.githubusercontent.com/assets/11723563/18462184/f1b5b206-7934-11e6-8e85-d47405fb4e96.png">

#### Expected Results

Text input box should show up above tab bar.

#### Additional Information

* React Native version: 0.32.1
* react-native-gifted-chat version: 0.0.10
* Platform(s) (iOS, Android, or both?): iOS

**Comment by java99** [comment]
+1 

same with

            <GiftedChat
              handleSend={this.handleSend.bind(this)}
              renderAccessory={false}
              bottomOffset={270}
              renderBubble={this.renderBubble}
              renderMessageText={this.renderMessageText}
              renderFooter={this.renderFooter}
              messages={this.state.messages}
              onSend={this.onSend}
              user={{
                _id: Meteor.userId(),
                name: Meteor.user().profile.name,
              }}
            />

**Comment by prabhaav** [comment]
@java99 You just have to add a view block around it like so:

<View style={{flex: 1}}>
        <View style={{flex: 10}}/>
        <View style={{flex: 83}}>
          <GiftedChat
            messages={this.state.messages}
            onSend={this.onSend.bind(this)}
            loadEarlier={this.state.loadEarlier}
            user={{
              _id: this.state.id,
              name: this.props.name,
            }}
            renderBubble={this.renderBubble.bind(this)}
            renderFooter={this.renderFooter.bind(this)}
          />
        </View>
        <View style={{flex: 7}}/>
      </View>
