### ISSUE TITLE
Username on top of message bubble?

### ISSUE THREAD

**Issue by rickling** [FaridSafi/react-native-gifted-chat#233]
Hey there,

I think older versions of the Gifted Chat had a way to have usernames show up on top of message bubbles (See below React-Bot) Is this still available in the new Gifted Chat? If not, I'm guessing the best way to go about implementing is just overriding renderMessage.

![giftedmessenger 1](https://cloud.githubusercontent.com/assets/4711616/18491237/4bb20676-79ba-11e6-893a-9e6538d10595.gif)

Thanks, appreciate the help.

**Comment by rickling** [comment]
Forked and edited Message rendering. Thanks!

**Comment by kfiroo** [comment]
@rickling I don't think a fork is needed, you could simply set `renderMessage` prop and render what you need

**Comment by benjaminb10** [comment]
@kfiroo Is there a way of showing the name only on top of the first bubble of a sequence of bubbles from the same sender?

**Comment by rebirthtobi** [comment]
@kfiroo i support the showing of name inside bubble not above the bubbles

**Comment by rajvirkaurlumino** [comment]
> 
Can you please provide code for this?
