### ISSUE TITLE
Unable to edit text within input as keyboard closes on blur

### ISSUE THREAD

**Issue by jtparrett** [FaridSafi/react-native-gifted-chat#2333]
#### Issue Description

On ios (and probably android), if you type a message into the input, then attempt to select a piece of text to edit, the keyboard immediately closes. It seems to fire the blur event for the input which closes the keyboard, it will then re-focus the input as it's where you've just tapped to edit, which will make the keyboard re-open. However you wont be editing the text you've attempted to edit as it's like a new focus for the input. 

Video here: https://drive.google.com/file/d/17Ob1r3sB-0MMG_GM2SKi0H7XYmbGUHm0/view?usp=sharing

#### Additional Information
Using latest gifted chat version

**Comment by OmanFerrer** [comment]
@jtparrett did u solve this?
