### ISSUE TITLE
When used in a Modalize component, the keyboard closes directly only on android

### ISSUE THREAD

**Issue by elie-chaaban** [FaridSafi/react-native-gifted-chat#2342]
https://user-images.githubusercontent.com/29852821/220158647-84159e0a-daa1-4dd8-8437-92414ef2e09c.MOV

**Comment by fukemy** [comment]
When modal show, please using keyboard state = KEYBOARD_NONE, then set it back after close modal

**Comment by elie-chaaban** [comment]
How can I set this keyboard state and where

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
