### ISSUE TITLE
Giftedchat react-native-safe-area-context breaks expo SDK 48

### ISSUE THREAD

**Issue by baltagih2** [FaridSafi/react-native-gifted-chat#2349]
#### Issue Description

On expo SDK 48, react-native-safe-area-context is upgraded to version 4.5.0, while gifted chat uses 4.4.1 as a peer dependency which leads to the registration of two views:

`Invariant Violation: Tried to register two views with the same name RNCSafeAreaProvider, js engine: hermes`

#### Steps to Reproduce / Code Snippets

- Upgrade expo to SDK 48
- Use latest version of react-native-gifted-chat (currently 1.1.1)
- App will crash with the following error:
<img width="966" alt="Screenshot 2023-02-27 at 12 13 10 PM" src="https://user-images.githubusercontent.com/62379853/221535984-a07b6dc2-923a-45e3-aa6e-a2189ad5dc14.png">

Running `npm ls react-native-safe-area-context` gives the following:

<img width="408" alt="Screenshot 2023-02-27 at 12 14 07 PM" src="https://user-images.githubusercontent.com/62379853/221536187-9aecd9b9-06c9-46c9-9998-48c0d7b30c14.png">

Running `npm dedupe` does not help with the issue since `"react-native-safe-area-context": "4.4.1"` is a dependency and not a peer dependency of react-native-gifted-chat 

#### Expected Results

- App should not crash
- GiftedChat should not force a specific version of the dependency

#### Additional Information

* Nodejs version: 16.15.0
* React version: 18.2.0
* React Native version: 0.71.3
* react-native-gifted-chat version: 1.1.1
* Platform(s) (iOS, Android, or both?): tested on iOS
* TypeScript version: 4.9.4

**Comment by hramos** [comment]
Same here. I'm working around this, for the moment, with an override in my `package.json`:

```
  "overrides": {
    "react-native-safe-area-context": "4.5.0"
  },
```

**Comment by baltagih2** [comment]
@hramos Thank you for your answer. I have tried that and also tried:

```
"overrides": {
    "react-native-gifted-chat": {
      "react-native-safe-area-context": "4.5.0"
    }
  },
```

but it doesn't fix the issue either

**Comment by Tchaikovsky1114** [comment]
On expo SDK 48, i got same issue.
overrides isn't fix my issue..

**Comment by hramos** [comment]
@baltagih2 what does `npm list react-native-safe-area-context` show? Here's my output, as you can see there's a single 4.5.0 version in use.

```
├─┬ @react-navigation/native-stack@6.9.9
│ ├─┬ @react-navigation/elements@1.3.17
│ │ └── react-native-safe-area-context@4.5.0 deduped
│ └── react-native-safe-area-context@4.5.0 deduped
├─┬ native-base@3.4.26
│ └── react-native-safe-area-context@4.5.0 deduped
├─┬ react-native-gifted-chat@1.1.1
│ └── react-native-safe-area-context@4.5.0 deduped
└── react-native-safe-area-context@4.5.0 overridden
```

**Comment by flavitsky** [comment]
I installed the same react-native-safe-area-context version in my app as in gifted chat dependencies to avoid doubling
For me this workaround is ok for a while

**Comment by baltagih2** [comment]
@hramos mine showed the same tree as posted in the issue description on top. I thought it might be a caching issue so I `rm -rf node_modules package-lock.json` and re-installed everything with the override set in place (both your version and mine of the override) and I still got the same tree for some reason. Also, overrides are not autocompleting in my package.json which makes me think they could be deprecated or not supported on my node version (16.15.0)

**Comment by amerikan** [comment]
I just ensured to install 4.4.1. `npm i react-native-safe-area-context@4.4.1` to force to install that version which GiftedChat supports. If you run expo doctor it will complain about that version, but that's the only way I could get it to work in Expo 48.

**Comment by Johan-dutoit** [comment]
Should be fixed with https://github.com/FaridSafi/react-native-gifted-chat/pull/2353 and https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/v2.0.0
