### ISSUE TITLE
A lot of spaces in IOS.

### ISSUE THREAD

**Issue by giannis21** [FaridSafi/react-native-gifted-chat#2352]
#### Issue Description

<img width="347" alt="image" src="https://user-images.githubusercontent.com/48606335/223135957-3cca81a5-21c6-4ea6-abeb-a48cef25050d.png">

There is a lot of space in the top of messages in ios only. I use SafeAreaview. Also in the bottom i hide the bottom tab and i have put bottomOffset =(safeAreaInsets.bottom) ..I cannot remove these spaces..

#### Additional Information

* Nodejs version: v18.9.0
* React version: 17.0.2
* React Native version: 0.68.0
* react-native-gifted-chat version: 1.1.1
* Platform(s) (iOS, Android, or both?): IOS
* TypeScript version: 4.8.3

**Comment by amerikan** [comment]
https://github.com/FaridSafi/react-native-gifted-chat/issues/2220#issuecomment-1153338844

**Comment by Johan-dutoit** [comment]
Should be fixed with https://github.com/FaridSafi/react-native-gifted-chat/pull/2353 and https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/v2.0.0
