### ISSUE TITLE
Space between the right side of screen and user when showUserAvatar is false

### ISSUE THREAD

**Issue by tapasya27** [FaridSafi/react-native-gifted-chat#2354]
#### Issue Description

There is space between the right side of screen and user when showUserAvatar is false

#### Steps to Reproduce / Code Snippets

![image](https://user-images.githubusercontent.com/45207318/223923061-42dd6764-e3c0-4ad1-a153-bbe4b4ab3017.png)

![image](https://user-images.githubusercontent.com/45207318/223925061-b43bf713-cb34-45f5-a26d-65a054bcdcfe.png)

No additional rendering has been done. 

#### Expected Results

There should be no space between the bubble and the screen. 

#### Additional Information

* Nodejs version: 16.17.0
* React version: 18.1.0
* React Native version: 0.70.5
* react-native-gifted-chat version: 1.1.1
* Platform(s) (iOS, Android, or both?): iOS
* Coding language: JS

**Comment by amerikan** [comment]
Instead of `false` try setting it to `null`.

**Comment by tapasya27** [comment]
Thanks! I will try that out too but I was able to figure it out by customizing it to` showAvatarForEveryMessage={true} `and `showUserAvatar={false}`
