### ISSUE TITLE
how to remove spacing at the top of message container?

### ISSUE THREAD

**Issue by SDS2016** [FaridSafi/react-native-gifted-chat#2356]

**Comment by SDS2016** [comment]
![image](https://user-images.githubusercontent.com/34169381/224246197-fa177d03-1c09-4d8b-811e-b96bc3a51182.jpeg)

**Comment by IbrahimKhanLughmani** [comment]
same

**Comment by IbrahimKhanLughmani** [comment]
same, this issue is just on ios not on android.

**Comment by IbrahimKhanLughmani** [comment]
<GiftedChat wrapInSafeArea={false}

**Comment by SDS2016** [comment]
I figured it out shortly after the post. I just wrapped the gifted chat component in a view then set the background color to what a wanted.

**Comment by amerikan** [comment]
Upgrade to v2.0.0 if you can, SafeArea has been removed from the package so should no longer be an issue.
