### ISSUE TITLE
Messages are blinking

### ISSUE THREAD

**Issue by swaroopa94** [FaridSafi/react-native-gifted-chat#236]
Him I am using Gifted Messenger for my chat.
In that i am running my service in the backgroung for every second but when click on send button my message blinking (i.e.,appearing and disappearing and again appearing).
Could not find what is the reason.
Can You tell me how to solve this.

**Comment by kfiroo** [comment]
@swaroopa94 Hey
Messages blinking means that they are re-rendered when you send a message.
The messages list uses a `ListView` to render the messages which uses a `ListView.DataSource` as you can see in [MessageContainer.js#L23](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/MessageContainer.js#L23).
A single message will get rendered again only if this expression returns true.
``` javascript
rowHasChanged: (r1, r2) => {
    return r1.hash !== r2.hash;
}
```
You can try to debug this and see why this happens in your code.

**Comment by Thorbenandresen** [comment]
@kfiroo what is the purpose of the hash? Does it prevent re-renders or/and to improve perf? 

I don't get re-renders with the following code either

```js
  const ds = new ListView.DataSource({
      rowHasChanged: (r1, r2) => {
        return r1 !== r2;
      }
    });

```
[...]

```js
  prepareMessages(messages) {
    return {
      keys: messages.map(m => m.key).reverse(),
      blob: messages.reduce((o, m, i) => {
        o[m.key] = {...m};
        return o;
      }, {})
    };
  }

``

**Comment by Faolain** [comment]
Can this issue be closed? Gifted chat uses FlatList instead of ListView now no? 

cc: @swaroopa94 @cooperka

**Comment by vladimir-vovk** [comment]
For the old version of Gifted Chat with the `ListView` component, we can add some custom property to the `message` object. The `hash` will change and `ListView` will rerender this `message`.

```
const { messages } = this.state
const message = messages[0] // message you would like to re-render
message.rerender = !message.rerender // any custom property
this.setState({ messages: [ …messages ] })
```
