### ISSUE TITLE
How to get GiftedMessengerExample in a given version to run on Xcode?

### ISSUE THREAD

**Issue by beccax** [FaridSafi/react-native-gifted-chat#237]
#### Issue Description

Sorry if this question is really basic, as I'm a newbie.  I just want to be able to run your GiftedMessengerExample from version 0.1.0.  The problem is I'm using a package that uses an older version of yours, before 0.1.0, but I found it buggy.  I'd like to run your 0.1.0 example to see if that fixes the problem.  I've checked out your code, done npm install, but can't get it to run on Xcode using the provided GiftedMessengerExample.xcodeproj. 
#### Steps to Reproduce / Code Snippets

Try 1. git clone your code
I tried use the example as is, and run the xcodeproj directly, then get message like can't find RTCRootView not found, React not found.  

Try 2. new react native project
I tried "react-native init" a new project, then copy react-native-gifted-chat/  from you into node_module, then copy the code for the example to the new project directory.  Then I get errors like can't find @exponent/react-native-navigator, or can't find react-native-gifted-messenger. 

Try 3. I've also tried to install 0.1.0 over old version, just skip the example, but 
   npm install react-native-gifted-chat@0.1.0 
gives: "version not found: react-native-gifted-chat@0.1.0"
#### Expected Results

I'd expect the example to just work, but seems difficult.  What am I doing wrong?
#### Additional Information
- React Native version: 0.20-0.21
- react-native-gifted-chat version: 0.1.0
- Platform(s) (iOS, Android, or both?): iOS

**Comment by devbriguy** [comment]
Hi @beccax Try 1 is the valid approach but you need to `cd /path/to/example/project/` and run `npm install --save` this will install all modules associated with the project. Then do `react-native run-ios`
