### ISSUE TITLE
Excessive rerenders because of context changes

### ISSUE THREAD

**Issue by mdkwock** [FaridSafi/react-native-gifted-chat#2370]
Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-gifted-chat@2.0.1` for the project I'm working on.

Because GiftedChat uses an object as the context value it causes every component that listens to context to rerender whenever GiftedChat rerenders.  This causes all the message bubbles, message texts and many other components to rerender.  By saving the context values to state it prevents these context changes from happening. This probably helps some of the performance issues that #2366, #2335, #2336 are facing.

Using the example on the old react documentation for the workaround.
https://legacy.reactjs.org/docs/context.html#caveats

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-gifted-chat/lib/GiftedChat.js b/node_modules/react-native-gifted-chat/lib/GiftedChat.js
index a91d004..4d03071 100644
--- a/node_modules/react-native-gifted-chat/lib/GiftedChat.js
+++ b/node_modules/react-native-gifted-chat/lib/GiftedChat.js
@@ -44,6 +44,7 @@ class GiftedChat extends React.Component {
             typingDisabled: false,
             text: undefined,
             messages: undefined,
+            contextValues:{},
         };
         this.getLocale = () => this._locale;
         this.onKeyboardWillShow = (e) => {
@@ -193,6 +194,11 @@ class GiftedChat extends React.Component {
         this.initLocale();
         this.setMessages(messages || []);
         this.setTextFromProp(text);
+        this.setState({contextValues: {
+            actionSheet: this.props.actionSheet ||
+                (() => { var _a; return (_a = this._actionSheetRef.current) === null || _a === void 0 ? void 0 : _a.getContext(); }),
+                getLocale: this.getLocale,
+        }})
     }
     componentWillUnmount() {
         this.setIsMounted(false);
@@ -416,13 +422,7 @@ class GiftedChat extends React.Component {
     }
     render() {
         if (this.state.isInitialized === true) {
-            const actionSheet = this.props.actionSheet ||
-                (() => { var _a; return (_a = this._actionSheetRef.current) === null || _a === void 0 ? void 0 : _a.getContext(); });
-            const { getLocale } = this;
-            return (<GiftedChatContext.Provider value={{
-                    actionSheet,
-                    getLocale,
-                }}>
+            return (<GiftedChatContext.Provider value={this.state.contextValues}>
           <View testID={TEST_ID.WRAPPER} style={styles.wrapper}>
             <ActionSheetProvider ref={this._actionSheetRef}>
               <View style={styles.container} onLayout={this.onMainViewLayout}>
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by hassant4** [comment]
@mdkwock  Thank you for sharing this, it solves my issue that you mentioned [#2366 ](https://github.com/FaridSafi/react-native-gifted-chat/issues/2366) (unresponsive send button when message history > 5). Great work!

**Comment by hassant4** [comment]
@mdkwock Thank you for sharing this, it solves my issue that you mentioned #2366 (unresponsive send button when message history > 5) . Great work!

**Comment by fukemy** [comment]
great job, it's really avoid item changed when context changed everytime giftedchat rerender

**Comment by laithalshabi** [comment]
thanks my app was so laggy <3

**Comment by jamesholcomb** [comment]
Huge kudos for this 👍

**Comment by hstaudacher** [comment]
Thx! Without this the library is not usable right now.

**Comment by tbergeron** [comment]
That's amazing but why not make the patch for the actual TypeScript source? Patching the compiled JavaScript isn't the right approach. Also why not just make a pull request?

**Comment by mdkwock** [comment]
@tbergeron you can patch the javascript without waiting for the authors to approve a PR + release. but yeah I can make a PR for it as well.

**Comment by FrenchMajesty** [comment]
This PR also resolves many issues that have been around since ~2018 (  #840, #850 )

Would be nice if this PR was merged in

**Comment by fukemy** [comment]
everyone will get complain from user with low end Android's device, too laggy, too terriable... too many state to make screen re-render while chating with a lot of bubble message, how to solve this?

**Comment by levepic** [comment]
Users have been complaining since upgrading to v2 of lags anrs, trying this solution if it doesnt work will downgrade to v1...

**Comment by fukemy** [comment]
I saw gifted chat re-render it's self for every text changed? Any solution for this?

**Comment by aguidad** [comment]
> I saw gifted chat re-render it's self for every text changed? Any solution for this?

try `shouldUpdateMessage` prop maybe help you, it prevents unnecessary re-render.
shouldUpdateMessage={(props, nextProps) =>
    props.extraData !== nextProps.extraData
}

**Comment by fukemy** [comment]
> 

shouldUpdateMessage used for Message class only

**Comment by FromSunNews** [comment]
> 

This helped me so much!

**Comment by FromSunNews** [comment]
> > Tôi thấy cuộc trò chuyện có chức năng tự động hiển thị lại cho mọi văn bản đã được thay đổi? Bất kỳ giải pháp nào cho điều này?
> 
> try `shouldUpdateMessage`prop can help you, it stop output not need.
> 
> ```
> shouldUpdateMessage={(props, nextProps) =>
>     props.extraData !== nextProps.extraData
> }
> ```

This helped me so much <3

**Comment by johnalalade** [comment]
This solution works so well I can almost cry. Thanks a bunch

**Comment by mkhoussid** [comment]
> you dont need to use context provider while it's seem totally useless. I removed this context in my library

Are you suggesting the following?

```diff
// node_modules/react-native-gifted-chat/lib/GiftedChat.js:332

const _renderLoading = () => {
    if (renderLoading) {
        return renderLoading();
    }
    return null;
};
- const contextValues = useMemo(() => ({
-     actionSheet: actionSheet || (() => { var _a; return (_a = actionSheetRef.current) === null || _a === void 0 ? void 0 : _a.getContext(); }),
-     getLocale: () => locale,
- }), [actionSheet, locale]);
if (state.isInitialized === true) {
-     return (<GiftedChatContext.Provider value={contextValues}>
+     return (<View testID={TEST_ID.WRAPPER} style={styles.wrapper}>
-    <View testID={TEST_ID.WRAPPER} style={styles.wrapper}>
        <ActionSheetProvider ref={actionSheetRef}>
        <View style={styles.container} onLayout={onMainViewLayout}>
            {renderMessages()}
            {_renderInputToolbar()}
        </View>
        </ActionSheetProvider>
-    </View>
+    </View>);
-    </GiftedChatContext.Provider>);
}
return (<View testID={TEST_ID.LOADING_WRAPPER} style={styles.container} onLayout={onInitialLayoutViewLayout}>
    {_renderLoading()}
</View>);
```

**Comment by mkhoussid** [comment]
> the next quest is [optimizing-flatlist-configuration](https://reactnative.dev/docs/optimizing-flatlist-configuration)

Is this for `listViewProps`? Honestly, seems to me as though it'd be more simple to just come up with a Chat component from scratch

**Comment by henryteng07** [comment]
Is this still an issue in the latest version of gifted chat? I'm still seeing excessive rerenders plus Send button becomes laggy with more messages

**Comment by sagarsq** [comment]
+1
