### ISSUE TITLE
When append new message, will scroll up a little position.

### ISSUE THREAD

**Issue by lvshuchengyin** [FaridSafi/react-native-gifted-chat#2376]
#### Issue Description
**This is the screen show, has 9 messages and we can see No. 3-7 messages:** 
msg1
msg2
msg3 -- screen top
msg4
msg5
msg6
msg7 -- screen bottom
msg8
msg9

**When I append a new message to it, the screen will scroll up:**
msg1
msg2
msg3 
msg4 -- screen top
msg5
msg6
msg7 
msg8 -- screen bottom
msg9
msg10

#### Steps to Reproduce / Code Snippets
The code is like this:
```
return (
    <GiftedChat
        messages={uiMessages}
        //   onSend={messages => onSend(messages)}
        user={{
            _id: 1,
        }}
    />
)
```
I will append message to the end:
```
setUIMessages((previousMessages) => {
      let newMsg = {
          _id: groupMessageObj.message_id,
          text: groupMessageObj.message_id,
          createdAt: new Date(),
          user: {
              _id: 2,
              name: 'React Native',
              avatar: 'https://placeimg.com/140/140/any',
          },
      }

      return GiftedChat.append(previousMessages, newMsg);
  });
```
#### Additional Information

* Nodejs version: v19.7.0
* React version: 18.2.0
* React Native version: 0.71.7
* react-native-gifted-chat version: 1.0.4
* Platform(s) (iOS, Android, or both?): mac android simulator
* TypeScript version: 4.9.4
* expo version: 48.0.10

**Comment by fukemy** [comment]
I think that's normally actions, but you can see some advices here https://stackoverflow.com/a/63229229/1308590

**Comment by lvshuchengyin** [comment]
```
listViewProps={{
    maintainVisibleContentPosition: {
        minIndexForVisible: 0,
        autoscrollToTopThreshold: 30,
    }
}}
```
Add these code can fix it.
