### ISSUE TITLE
Send button not appearing after using onChangeText in the Composer

### ISSUE THREAD

**Issue by devjaw** [FaridSafi/react-native-gifted-chat#2377]
When using React Native Gifted Chat, The send button is not appear after using the onChangeText function in the custom composer. 

here is the sample of the custom composer code :

`<Composer {...props}
        textInputProps={{
          ...props.textInputProps,
          maxLength:200,
          contextMenuHidden:true,
          value : ChatText,
          onChangeText(text) {
           // console.log(text)
            textc(text);
          }
        }}
      />`

* React Native version: 0.71.6
* react-native-gifted-chat version: 2.0.1
* Platform(s) (iOS, Android, or both?): android

**Comment by fukemy** [comment]
Giftedchat automatically handle text itself, u need to call props.onTextChanged(newText) somewhere
