### ISSUE TITLE
Messages are completely disorganized | Not ordered.

### ISSUE THREAD

**Issue by qualifyapp** [FaridSafi/react-native-gifted-chat#238]
#### Issue Description

I'm attempting to use GiftedChat in the react-native port of our application and we're running into problems with the order in which messages are displayed, shown in a screenshot below. All of our dates are stored in MIlliseconds since UTC on the Server, porting our messages over looks like so:

```
var altered = {
                _id: message.key,
                text: message.data,
                createdAt: new Date(message.created_at), // Also tried just message.created_at
                user: {
                    _id: message.sender,
                    name: match.other_user.first_name,
                    avatar: match.other_user.photo
                }
            }

            giftedMessages.push(altered)
```

The result is this jumbled mess, it doesn't seem to follow any type of organization. This is a real conversation pulled from our database between two users, one being a test account of ours. We use Firebase, so the timestamp is stored in MIlliseconds since epoch. 

![gifted-confusion](https://cloud.githubusercontent.com/assets/19787444/18614247/cd4338c4-7d50-11e6-903e-5d46e82d3727.png)
#### Steps to Reproduce / Code Snippets

Just use the example and any dates formed using milliseconds. (IE: Date.now())
#### Expected Results

Proper ordering of messages. 
#### Additional Information
- React Native version: 0.33.0
- react-native-gifted-chat version: 0.0.10
- Platform(s) (iOS, Android, or both?): iOS (Don't have android)

**Comment by qualifyapp** [comment]
We tried using ES6 Sets to determine the difference between a cached and current object containing all of our messages mapped to the key stored in our database, then using `GiftedChat.append(previousState.messages, newMessages)` to counteract this problem instead of rebuilding the whole array. This did not work, here's an example:

```
filterNewMessages(updatedMessages) {
        const oldKeys = Object.keys(this.cachedMessages)
        const oldSet = new Set(oldKeys)
        const newKeys = Object.keys(updatedMessages)

        const difference = [...new Set([...newKeys].filter(x => !oldSet.has(x)))]
        console.warn(difference)
        return difference
    }

    convertMessagesToGifted(props, added) {
        props = props || this.props
        const { selected, messages, matches } = props
        const match = matches[selected]
        if(messages == null) return
        const messagesToAppend = this.filterNewMessages(messages)

        var giftedMessages = []
        for(var i = 0; i < messagesToAppend.length; i++) {
            const messageToAppend = messages[messagesToAppend[i]]
            if(messageToAppend == null) continue

            var giftedMessage = {
                _id: messageToAppend.key,
                text: messageToAppend.data,
                createdAt: new Date(messageToAppend.created_at),
                user: {
                    _id: messageToAppend.sender,
                    name: match.other_user.first_name,
                    avatar: match.other_user.photo
                }
            }

            giftedMessages.push(giftedMessage)
        }

        // Note: May need to add the messages in order..? 😢
        this.setState((previousState) => {
            return {
                messages: GiftedChat.append(previousState.messages, giftedMessages)
            }
        })

        this.cachedMessages = messages
    }
```

Where once again `message.created_at` is a millisecond value, similar to that of `Date.now()` Considering the examples wrap `Date.UTC` which returns a millisecond value, passing `new Date(millis)` should work fine, however ordering is still really jank.

**Comment by kfiroo** [comment]
@qualifyapp GiftedChat will not sort the message for you, it will preserve the order of message as it was in the `messages` prop
Hope that helps

**Comment by dcurletti** [comment]
I really appreciate this library being open sourced, but the fact that there isn't some sort of default sorting should be advertised on the readme.  That is a crucial and integral part of any messaging template.  Again, not saying that there needs to be a PR for this, but for the sake of users it would be nice to specify this lack of functionality more clearly upfront.

**Comment by jayshah123** [comment]
The order seems to be preserved from the array passed, 
but they are laid out in opposite direction? 
With addition of every message I should prepend to the original array passsed 
or append to the original array passed ?

**Comment by jayshah123** [comment]
@kfiroo  Is the reverse rendering of items due to invertible scrollview? 
Gifted messenger (Earlier version of gifted chat) rendered in order supplied i.e. top to bottom.
Anyways I have reversed the input array and appending order to take care of the problem.

**Comment by kfiroo** [comment]
@jayshah123 Yes, `GiftedChat` uses `InvertibleScrollView` to render the messages from the bottom to the top, and also to keep the scroll at the bottom.
@dcurletti You are right, I'll make sure to add that to the readme

**Comment by calclavia** [comment]
I seem to get the same issue but only on Android. The message ordering on iOS works fine.

**Comment by fredbt** [comment]
same here. Inverted on android. Not sure about iOS yet.

**Comment by januszdotnl** [comment]
And why don't you order the list at firebase? E.g.
'''Firebase.database().ref(`chats/${key}`).orderByKey().limitToLast(20);'''
Keys at firebase are based of the Unix epoch so this way you'll pull the array in the correct order.

**Comment by humbertovaz** [comment]
`messages={messages.sort((a, b) => Date.parse(b.createdAt) - Date.parse(a.createdAt))}`

This helped me

**Comment by mihocsaszilard** [comment]
@humbertovaz saved my day! Thank You
