### ISSUE TITLE
Clearing TextInput when in the middle of a message

### ISSUE THREAD

**Issue by bsiddiqui** [FaridSafi/react-native-gifted-chat#239]
#### Issue Description

When sending multiple messages sometimes the TextInput is cleared when you're in the middle of a message.
#### Steps to Reproduce / Code Snippets

Type multiple messages and keep hitting send. When the app finishes sending a message it will clear the TextInput even if you're in the middle of a message
#### Expected Results

After clicking send, clear TextInput once but don't clear again when the message finishes sending 
#### Additional Information
- React Native version: 0.31.0
- react-native-gifted-chat version: 0.0.10
- Platform(s) (iOS, Android, or both?): iOS

**Comment by bsiddiqui** [comment]
Why is this setTimeout necessary? 

https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/GiftedChat.js#L326

Removing it seems to help with the message being input being cleared when you're in the middle of typing a message

**Comment by kfiroo** [comment]
I have a PR that fixes that and improves the overall performance of sending a message but looks like my branch got too messy, I'll clean it up and try to push it again

**Comment by bsiddiqui** [comment]
@kfiroo awesome. Will subscribe to that PR.
