### ISSUE TITLE
Why don't you show the name

### ISSUE THREAD

**Issue by iamdurui** [FaridSafi/react-native-gifted-chat#241]
Thank you for your components
But I want to show you the names of both parties.What should I do?
#### Additional Information
- React Native version: 0.33
- react-native-gifted-chat version: 0.0.10
- Platform(s) (iOS, Android, or both?): [both]

**Comment by JaxGit** [comment]
Just inherit from Bubble and render customised bubble component with name in renderBubble prop of <GiftedChat/>

**Comment by benjaminb10** [comment]
Is there a way to show the name only on the first bubble of a sequence of bubbles of the same user?

**Comment by peteroid** [comment]
for those we still need any help, you could do something like below.

```javascript
import { GiftedChat, Bubble } from 'react-native-gifted-chat'

renderName = (props) => {
  const { user: self } = this.state
  const { user = {} } = props.currentMessage
  const { user: pUser = {} } = props.previousMessage
  const isSameUser = pUser._id === user._id
  const isSelf = user._id === self._id
  const shouldNotRenderName = isSameUser

  return shouldNotRenderName ? (
    <View />
  ) : (
    <Text
      style={[ isSelf ? styles.selfUser : styles.otherUser ]}>
      {user.name}
    </Text>
  )
}

renderBubble = (props) => {
  return (
      <View>
        {this.renderName(props)}
        <Bubble {...props} />
      </View>
    )
  }
}

render () {
  return (
    <GiftedChat
      renderBubble={this.renderBubble}
      />
  )
}
```

**Comment by fukemy** [comment]
> ```js
> ew>
>         {this.renderName(props)}
> ```

Hi, can u provide sample for functional component: 
I have defined:

```
const userSample = {
  _id: 1,
  name: 'Aaron',
  avatar: 'https://placeimg.com/150/150/any',
}


const [user, setUser] = useState();

const renderName = (props) => {
    const { user: self } = user
 ....

```
then i got this error:
![Screen Shot 2022-04-18 at 16 10 09](https://user-images.githubusercontent.com/8202437/163785912-1b943bd0-3f1a-4ef6-8e19-e362744534ac.png)
