### ISSUE TITLE
Tab Nav Bar and Keyboard dismiss Input glitch

### ISSUE THREAD

**Issue by albert-carreras** [FaridSafi/react-native-gifted-chat#2414]
#### Issue Description

On Keyboard Dismiss the input toolbar has a tiny glitch and "repositions" itself

https://github.com/FaridSafi/react-native-gifted-chat/assets/23164723/75ae207a-1bd0-466e-8183-6e90b071d503

I tried all the options that come from the props, like bottomOffset, setting all different styles and changing the components, but I can't seem to be able to fix that one. Changes to the available props in the package might change the positioning of the input, but in the end when the keyboard closes, the glitch is always there.

I'm using a Tab Navigator from Expo-router. My Expo router implementation is nothing special.

#### Steps to Reproduce / Code Snippets

```
    <SafeAreaView
      style={{ flex: 1 }}
      edges={["left", "right", "top"]}
    >
      <GiftedChat
        messageContainerRef={chatRef}
        loadEarlier
        minComposerHeight={40}
        maxComposerHeight={180}
        scrollToBottomComponent={scrollToBottomComponent}
        textInputStyle={{
          color: "#000000",
          borderRadius: 20,
          paddingTop: 12,
          paddingBottom: 6,
          paddingRight: 8,
          marginBottom: 0,
          paddingLeft: 12,
          justifyContent: "center",
          alignItems: "center",
          alignSelf: "center",
          backgroundColor: primaryWhite
        }}
        isLoadingEarlier={isLoading}
        onLoadEarlier={handleOnLoadEarlier}
        scrollToBottom
        messages={messages}
        renderSend={renderSend}
        alwaysShowSend
        bottomOffset={-20}
        renderInputToolbar={renderToolbar}
        renderAvatar={null}
        isTyping={typing}
        onSend={onSend}
        renderChatEmpty={renderChatEmpty}
        maxInputLength={300}
        renderBubble={renderBubble}
        listViewProps={{
          paddingHorizontal: 12,
          marginBottom: 20,
          maintainVisibleContentPosition: {
            minIndexForVisible: 0,
            autoscrollToTopThreshold: 30
          }
        }}
        user={{
          _id: 1
        }}
      />
    </SafeAreaView>    
```

#### Expected Results

No bounce on keyboard dismiss

#### Additional Information

Expo Router 1.5.3
Expo 48, with all the proper dependencies.
Gifted-chat 2.4.0

**Comment by fukemy** [comment]
I have this issues when learning React Native, then I decided to write a room list screen in tabBar item, after click into item I navigate to ChatScreen, it's fully solved this problem

**Comment by albert-carreras** [comment]
I fixed it.

I use `tabBarHideOnKeyboard: false` on the specific Chat view and then compensate with bottomOffset.

**Comment by Neeraj-WebNeuron** [comment]
Same issue..Bounce chat list on keyboard open and close
