### ISSUE TITLE
Issue with InputToolbar position for Android

### ISSUE THREAD

**Issue by karimK3** [FaridSafi/react-native-gifted-chat#2430]
I would like to know how to fix correctly the position of the InputToolbar when the keyboard is visible.

If I add a marginBottom, the textInput position change. And if I change the position of textInput, the position of InputToolbar change and when the keyboard closes and open again every marginBottom are ignored.

On an iOS everything is fine, the issue is only for Android.

![Screenshot_1690794519](https://github.com/FaridSafi/react-native-gifted-chat/assets/17828866/6ff80dac-2f96-4c28-b761-b91227ae4621)
![Screenshot_1690794964](https://github.com/FaridSafi/react-native-gifted-chat/assets/17828866/1b1d5281-07fa-411b-9b7b-d247d35bfbcf)

```
<View style={{backgroundColor: backgroundColor, flex: 1}}>
      <GiftedChat
        messages={messages}
        onSend={handleSend}
        renderSend={renderSend}
        user={mapUser(auth.currentUser)}
        loadEarlier={loadEarlier}
        isLoadingEarlier={isLoadingEarlier}
        isTyping={typing != null} 
        onLoadEarlier={handleLoadEarlier}
        onInputTextChanged={handleInputTextChanged}
        renderBubble={renderBubble}
        bottomOffset={-10}
        listViewProps={{
          keyboardDismissMode: "on-drag"
          }}
        style={{backgroundColor: backgroundColor}}
        renderFooter={renderFooter}
        list
        renderInputToolbar={(props) => (
          <InputToolbar
            {...props}
            containerStyle={{
              backgroundColor: '#F4F4F4',
              marginLeft: 15,
              marginRight: 15,
              marginBottom: isKeyboardVisible ? (Platform.OS === 'android' ? 0 : 35) : (Platform.OS === 'android' ? 10 : 35),
              borderColor: 'grey',
              height:44,
              borderRadius: 25
            }}
            textInputStyle={{
              color: '#333333',
              marginBottom: isKeyboardVisible ? (Platform.OS === 'android' ? 0 : 40) : 40,
              fontSize: 14,
              fontFamily: 'Roboto-medium',
            }}
            placeholder="Votre message ..."
          />
        )}
        renderChatFooter={() => (
          <View style={{marginVertical: isKeyboardVisible ? (Platform.OS === 'android' ? 0 : 0) : (Platform.OS === 'android' ? 5 : 20)}}/> // 20
        )}
      />
    </View>
```

* React Native version: 0.71.8
* react-native-gifted-chat version:  2.4.0
* Platform(s) Android
* Expo 48.0.0

**Comment by ishmaelmoreno** [comment]
By chance are you using expo?

**Comment by karimK3** [comment]
Yes Expo 48.0.0 why ?

**Comment by ishmaelmoreno** [comment]
I had the same issue. In my app.json i had the softwareKeyboardLayoutMode set to pan which would cause the issue and regardless of what you changed in the stylesheet it would still overlap. I removed it and it fixed the issue
![image](https://github.com/FaridSafi/react-native-gifted-chat/assets/13882823/5c0f7b52-4936-4b8a-a37f-c3b0ed8f9d67)

**Comment by karimK3** [comment]
It's exactly the same issue, thank you so much it's solved !
