### ISSUE TITLE
Error while updating property 'src' of a view managed by: RCTImageView

### ISSUE THREAD

**Issue by manjeet-dobble** [FaridSafi/react-native-gifted-chat#245]
#### Issue Description

when I tried to upload image using react-native -gifted-chat, I got red red screen saying that "Error while updating property 'src' of a view managed by: RCTImageView"

**Comment by oliversisson** [comment]
Me too. In the message I provide 
image: require('../images/a.jpg')

I wasn't getting this issue under react-native-gifted-messenger v0.1.2

**Comment by jeftarmascarenhas** [comment]
I resolve with
`<Image
      style={styles.backgroundImage}
      source={require('./bg-user.jpg')}
  />`
image local not use  property 'uri';
