### ISSUE TITLE
bottomOffset not working

### ISSUE THREAD

**Issue by anya-ji** [FaridSafi/react-native-gifted-chat#2453]
#### Issue Description

I can't seem to get rid of the extra top and bottom paddings in the GiftedChat component. The bottom one is unclear in the screenshot, but there's extra padding under the inputToolBar (not in the inputToolBar, but outside).
Setting `wrapInSafeArea` or `bottomOffset` doesn't change anything. Advice?

![image](https://github.com/FaridSafi/react-native-gifted-chat/assets/61763411/517192e3-6d7c-405e-807b-5930da0b4d50)

#### Steps to Reproduce / Code Snippets
```
 <TouchableWithoutFeedback onPress={Keyboard.dismiss} accessible={false}>
      <View style={{
           backgroundColor: "white",
           flex: 1,
       }}>
        <Header
          title={
            <Text style={[styles.title]}>
              {date} <GetIcon sportType={sport} size={32} /> {time}
            </Text>
          }
          subtitle={"Ready up by:"}
          subtitleEmphasized={countdown}
          subtitleEmphasizedOnPress={() => {}}
          goBack
          headerStyle={{ width: "100%" }}
        />
        <View
          style={{
              flex:1,
              marginBottom: isKeyboardVisible
                ? resize(-25)
                : bottomTabBarHeight,
              marginTop: resize(-30),
            }}>
          <GiftedChat
            messages={messages}
            onSend={(messages) => onSend(messages)}
            user={currentUser}
            showUserAvatar
            alignTop
            alwaysShowSend
            scrollToBottom
            renderBubble={renderBubble}
            renderAvatar={renderAvatar}
            renderMessageText={renderMessageText}
            renderInputToolbar={renderInputToolbar}
            renderComposer={renderComposer}
            renderSend={renderSend}
            wrapInSafeArea
            bottomOffset={0}
          />
        </View>
      </View>
    </TouchableWithoutFeedback>
```
#### Expected Results

Remove the top and bottom paddings.

#### Additional Information

* Nodejs version: v18.17.0
* React version: 18.1.0
* React Native version: 0.70.8
* react-native-gifted-chat version: ^1.0.4
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: ^4.6.3

**Comment by lsps9150414** [comment]
@anya-ji hey could you share why you completed this issue? I'm also trying to figure this out
