### ISSUE TITLE
Question - How to use renderAvatar? 

### ISSUE THREAD

**Issue by ghost** [FaridSafi/react-native-gifted-chat#247]
#### Question

I find the documentation fairly difficult to go on, as `renderAvatar` seems like it would require arguments in order to pass the source of the avatar into the component.

Currently we are trying to make the Avatar buttons on our application intractable. By going through the Source i see that `onPress` is supported in `GiftedAvatar` but I see no way to call it. This leads me to believe that we must use `renderAvatar` and pass a `<GiftedAvatar` component in there manually, while supplying the `onPress` prop. My question is, how would I go about getting the `avatar` link for the current user to pass it in to the `<GiftedAvatar>` Component. 

As per the "documentation" on the ReadME, all that is shown is that there is a `renderAvatar` function. 

How do we go about getting the `avatar` for the displayed message to pass to the component.

**Comment by kfiroo** [comment]
@ChristianTucker See in the example [App.js#L155](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/example/App.js#L155) how to override the default rendering of components in GiftedChat.

**Comment by ashneyderman** [comment]
you can not over ride avatar due to how its redering is coded in Message.js:

`  renderAvatar() {
    if (this.props.user._id !== this.props.currentMessage.user._id) {
      const {containerStyle, ...other} = this.props;
      const avatarProps = {
        ...other,
        isSameUser: this.isSameUser,
        isSameDay: this.isSameDay,
      };

      return <Avatar {...avatarProps}/>;
    }
    return null;
  }`

there is no way to override it with a property. Whereas bubble can be overwritten.

**Comment by kfiroo** [comment]
@ashneyderman see [here](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/Avatar.js#L12)

**Comment by ashneyderman** [comment]
@kfiroo - there is no way to display avatar that is self (i.e. on the 'right'). I guess I should have been clearer in my comment on what exactly is not overridable.

**Comment by lishuanghe0902** [comment]
how can I Set on the right side of the avatar？it's too difficult

**Comment by sastred** [comment]
The problem I see/suffer is that despite you pass renderAvatar prop [it is not always used](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/Avatar.js#L24:L39).

**Comment by MrGurns** [comment]
For anyone still confused as how to use this:
```
var newItem = {
  text: item.text,
  user: {
    _id: item.user_id,
    name: user.name,
    avatar: true,
  },
  avatarProps: {
    name: user.name,
    icon: user.icon,
  },
  createdAt: item.created_date,
   _id: item._id,
};

renderAvatar={(props) => {
  const { avatarProps } = props.currentMessage;
  if (avatarProps.name) {
    return(
      <UserAvatar size="40" name={avatarProps.name} src={avatarProps.icon} />
    );
  }
  return(null);
}}
```
Passing true to the avatar was key for me, cause if it is null, then it won't render the avatar, nor call the renderAvatar prop.

**Comment by jamesdmurphy51** [comment]
Where does UserAvatar component come from in that last example?

**Comment by hunter547** [comment]
@jamesdmurphy51  I'm sure you already found a workaround/solution for this but it's the UserAvatar component from this [library](https://github.com/wbinnssmith/react-user-avatar). Gives a little more control over the avatar and the creator of gifted-chat was inspired by this library, giving credit in lib/GiftedAvatar.js:

`setAvatarColor() {
        const userName = (this.props.user && this.props.user.name) || '';
        const name = userName.toUpperCase().split(' ');
        if (name.length === 1) {
            this.avatarName = `${name[0].charAt(0)}`;
        }
        else if (name.length > 1) {
            this.avatarName = `${name[0].charAt(0)}${name[1].charAt(0)}`;
        }
        else {
            this.avatarName = '';
        }
        let sumChars = 0;
        for (let i = 0; i < userName.length; i += 1) {
            sumChars += userName.charCodeAt(i);
        }
        **_// inspired by https://github.com/wbinnssmith/react-user-avatar_**
        // colors from https://flatuicolors.com/
        const colors = [
            carrot,
            emerald,
            peterRiver,
            wisteria,
            alizarin,
            turquoise,
            midnightBlue,
        ];
        this.avatarColor = colors[sumChars % colors.length];
    }`
