### ISSUE TITLE
How to stream response

### ISSUE THREAD

**Issue by Judy0406-CJ** [FaridSafi/react-native-gifted-chat#2472]
#### Issue Description

The response is from Generative API based on SSE protocol. How to stream the response?

#### Expected Results

ChatGPT like

**Comment by Judy0406-CJ** [comment]
figured out by just updating the first message, closing ticket.

**Comment by tao-qian** [comment]
I was also looking into this. Here is a quick example for anyone else trying to do this: https://github.com/tao-qian/react-native-chat-streaming-example
