### ISSUE TITLE
Can We Achieve React-Native-Keyboard-Aware-Scroll-View Behavior in React-Native-Gifted-Chat?

### ISSUE THREAD

**Issue by geoffcfchen** [FaridSafi/react-native-gifted-chat#2482]
Hello,

Thank you very much for all your hard work! I am in the process of enhancing the user experience in a chat application built with react-native-gifted-chat. A specific feature I aim to implement is akin to the behavior observed in react-native-keyboard-aware-scroll-view. I would like to know if the keyboard in react-native-gifted-chat can automatically dismiss when the user starts scrolling through the chat messages?

Thank you very much!

**Comment by geoffcfchen** [comment]
@fukemy thank you very much for pointing it out. 

 If I understand correctly, I need to modify the MessageContainer.js file in node_modules which is part of the react-native-gifted-chat library. Am I correct? 
 
 Thanks.

**Comment by dembeEdward** [comment]
> listViewProps={{keyboardDismissMode: 'on-drag'}}

I Was struggling with this, thank you! Works beautifully!!

**Comment by geoffcfchen** [comment]
Still want to achieve exactly the React-Native-Keyboard-Aware-Scroll-View Behavior, can this be fixed?

> [@fukemy](https://github.com/fukemy) thank you very much for pointing it out.
> 
> After modifying the library, it works! Thank you! But I also noticed that when the keyboard was closed by following the gesture, the renderInputToolbar did not go down together with the keyboard. It remained at the same location while the keyboard was moving down. Is there any way to fix it?
> 
> Thanks.
