### ISSUE TITLE
Hide keyboard on scrolling to top

### ISSUE THREAD

**Issue by jonathanglasmeyer** [FaridSafi/react-native-gifted-chat#250]
First of all: awesome library! Thanks so much for doing this! 

I'd like to have the WhatsApp/fb Messenger behaviour of hiding the keyboard when scrolling to top. I'd like to help but have no clue how to accomplish it. 

In the meantime, is there another way of hiding the keyboard at all?

**Comment by ggsrivas** [comment]
whatsApp and fb don't close there keyboard on scrolling to top in Android devices, So, I don't know if this library should support this by default. If you want to close keyboard based on any action then you can call 'dismissKeyboard()' which is supported out of box in react-native.

**Comment by jonathanewerner** [comment]
This pattern is only common on iOS, you are right. It'd be enough to use `keyboardDismissMode='interactive'` on the given ScrollView. This implements the behaviour I described but doesn't do anything on android. The problem now just is that the ScrollView your library uses is not configurable, is that correct?

**Comment by mackenziemance** [comment]
@jonathanglasmeyer Did you ever find a workaround ?

**Comment by stueynet** [comment]
Can we hook into the scrolling action of gifted chat. The keyboard should really dismiss on any scrolling of the messages window. Its weird to have it sit there.

**Comment by RSSfeed** [comment]
It was configurable back in 2016 I guess (https://github.com/FaridSafi/react-native-gifted-chat/issues/45), can't find the reason why it has been removed.

As far as I can see (correct me if I'm wrong), there is no reason on why removing this prop. There's already a prop called `keyboardShouldPersistTaps` which is giving down to `react-native-invertible-scroll-view` which is adding props like `{...props}` and including all `scrollView.propTypes`. 

Maybe it has been removed due to incompatibility to the logic of GiftedChat? Would love to see this prop coming back.

**Comment by shaneosullivan** [comment]
It should still be possible to do this in a similar manner to how it often occurs on iOS.  That is, the keyboard doesn't immediately respond to the scroll pixel-by-pixel, but once the user hits a threshold number of pixels that they have scrolled, the keyboard dismisses immediately.

This could be achieved by either:
1 - GiftedChat supporting a new boolean at the top level to enable this or
2 - GiftedChat supporting a new `onMessagesScroll` prop that is called from `MessageContainer.js`, and allow others in user land to do whatever they want with it, including this behavior.

Would option 2 be feasible?  If so, I'm happy to send a PR

**Comment by xcarpentier** [comment]
@shaneosullivan I guess everything is possible but I have to see it in real app ;)

If you have time and energy to do it, please create a PR, it would be nice ;)

**Comment by Hirbod** [comment]
could anybody fix this? Really missing the "pan to close" feature and I didn't find a proper way doing it.

**Comment by scdev1025** [comment]
Please use following props
```
listViewProps={{keyboardDismissMode: 'on-drag'}}
```

**Comment by ankhzet** [comment]
@scdev1025 AFAIK, `keyboardDismissMode: 'on-drag'` works only on iOS, on Android it's a noop.

**Comment by gatherheart** [comment]
```
export const renderComposer = (props) => (
  <Composer
    {...props}
    textInputProps={{
      autoCorrect: false,
      autoCapitalize: "none",
      autoGrow: true,
      autoFocus: false,
    }}
    placeholder={""}
  />
);
```

After using this (autoFocus: false) option, I solved the problem.

**Comment by hotaryuzaki** [comment]
> onMessagesScroll



> Please use following props
> 
> ```
> listViewProps={{keyboardDismissMode: 'on-drag'}}
> ```

its not work for me in android, is it iOS only?
