### ISSUE TITLE
Left side style issue

### ISSUE THREAD

**Issue by virendrasingh-tech** [FaridSafi/react-native-gifted-chat#2511]
#### Issue Description
If there is an image and subsequent message then there is some style issue

#### Steps to Reproduce / Code Snippets
Just simple two subsequent message from other side, like in example "Hi" and "dfdfss" with an image
![Screenshot_1724135105](https://github.com/user-attachments/assets/d2af7256-a38a-4375-a111-aedcd8f5adbd)

#### Expected Results
Container should be left aligned.

#### Additional Information

* Nodejs version: 18.20.4
* React version: 18.2.0
* React Native version: 0.74.5
* react-native-gifted-chat version: 2.4.1
* Platform(s) (iOS, Android, or both?): checked Android only
* TypeScript version: 5.3.3

**Comment by Neeraj-WebNeuron** [comment]
Same issue here..On left side no style are visible

**Comment by virendrasingh-tech** [comment]
> Same issue here..On left side no style are visible

It's working fine in the latest version(2.6.2).
