### ISSUE TITLE
Avatar doesn't work since 2.4.1

### ISSUE THREAD

**Issue by Yoni-Deserbaix** [FaridSafi/react-native-gifted-chat#2515]
Issue Description
Avatar is broken since 2.4.1 (worked in 2.4.0)

Additional Information
Nodejs version: 20.16.0
React version: 18.2.0
React Native version: 0.74.3
react-native-gifted-chat version: 2.4.1
Platform(s) (iOS, Android, or both?): Android
TypeScript version: 5.5.3

**Comment by kesha-antonov** [comment]
Hi
Please try version from `master`
It should work

Or if it doesn't specify the details what specifically doesn't work


![simulator_screenshot_63C760C9-83A6-4B20-9CC9-D3B511F3E52A](https://github.com/user-attachments/assets/bcdf10dd-1f46-4b9d-a957-5b565d311670)

**Comment by Hatko** [comment]
I can't reproduce this problem on 2.5.1 anymore

@kesha-antonov off-topic - how do you render messages on opposite sides? :D
