### ISSUE TITLE
Error: [Reanimated] Mismatch between JavaScript part and native part of Reanimated (3.15.0 vs 3.10.1)

### ISSUE THREAD

**Issue by HaythamT95** [FaridSafi/react-native-gifted-chat#2518]
#### Issue Description

After upgrading to latest version 2.5.1 in my expo poject, when I try to run the project both on android and ios I get:
Error: [Reanimated] Mismatch between JavaScript part and native part of Reanimated (3.15.0 vs 3.10.1).

#### Additional Information
I didn't have react-native-reanimated installed in other versions.
Version 2.4.1 doesn't produce this error, but avatar doesn't appear.

* Nodejs version: 20.4.0
* React version: 18.2.0
* React Native version: 0.74.5
* react-native-gifted-chat version: 2.5.1
* Platform(s) (iOS, Android, or both?): both

![simulator_screenshot_90897614-C718-4DFA-BEB8-8E8B95D6F50D](https://github.com/user-attachments/assets/14939334-fcc1-4110-9bbd-1d8348ea6df4)

**Comment by kesha-antonov** [comment]
Hi

Please try latest commit from master & also follow installation step: https://github.com/FaridSafi/react-native-gifted-chat?tab=readme-ov-file#installation

**Comment by Hatko** [comment]
This is indeed a problem for Expo users - latest Expo relies on `"react-native-reanimated": "~3.10.1",` being installed, and installing `react-native-gifted-chat` results in 2 versions of reanimated being installed and app crashing on start

**Comment by kesha-antonov** [comment]
Fixed

Please try version from master

**Comment by HaythamT95** [comment]
For me it is still bugged, when I ran `npx expo install react-native-gifted-chat react-native-reanimated react-native-safe-area-context` I got these versions:

"react-native-gifted-chat": "^2.5.1"
"react-native-reanimated": "~3.10.1"
"react-native-safe-area-context": "4.10.5"

but when I navigate to node_modules/react-native-gifted-chat/node_modules/react-native-reanimated/package.json:
the version is 3.15.0

**Comment by ck88ger** [comment]
It does not fix the problem with the answers.

**Comment by kesha-antonov** [comment]
Should be fixed in 2.6.0
