### ISSUE TITLE
Native module not found

### ISSUE THREAD

**Issue by HenrikZabel** [FaridSafi/react-native-gifted-chat#2519]
#### Issue Description

Whenever I click on "Send" following error occurrs

```ERROR  Error: Native module not found, js engine: hermes```

There are no more details logged.

#### Steps to Reproduce / Code Snippets

https://github.com/FaridSafi/react-native-gifted-chat?tab=readme-ov-file#example

I've used the official example

#### Expected Results

The message should be appended

#### Additional Information

* Nodejs version: v21.5.0
* React version: 18.2.0
* React Native version: 0.74.3
* react-native-gifted-chat version: ^2.6.0
* Platform(s) (iOS, Android, or both?): Android (Couldn't test iOS)
* TypeScript version: ~5.3.3

**Comment by Nicholas1K** [comment]
I also get the same error, error received on both Android and iOS

**Comment by HaythamT95** [comment]
For me it's even before the send, it's when i run  `npx expo run:ios/android`.
And also in 2.6.0 the property `renderUsernameOnMessage: PropTypes.Requireable<boolean>;` was removed so messages doesn't have username rendering.

**Comment by kesha-antonov** [comment]
> #### Issue Description
> Whenever I click on "Send" following error occurrs
> 
> `ERROR Error: Native module not found, js engine: hermes`
> 
> There are no more details logged.
> 
> #### Steps to Reproduce / Code Snippets
> https://github.com/FaridSafi/react-native-gifted-chat?tab=readme-ov-file#example
> 
> I've used the official example
> 
> #### Expected Results
> The message should be appended
> 
> #### Additional Information
> * Nodejs version: v21.5.0
> * React version: 18.2.0
> * React Native version: 0.74.3
> * react-native-gifted-chat version: ^2.6.0
> * Platform(s) (iOS, Android, or both?): Android (Couldn't test iOS)
> * TypeScript version: ~5.3.3

Hi
Can you share full error?
Also please try to run code from ./example

**Comment by kesha-antonov** [comment]
> And also in 2.6.0 the property `renderUsernameOnMessage: PropTypes.Requireable<boolean>;` was removed so messages doesn't have username rendering.

What do you mean?

https://github.com/search?q=repo%3AFaridSafi%2Freact-native-gifted-chat%20renderUsernameOnMessage&type=code

**Comment by HenrikZabel** [comment]
C:\Projects\Henrik\test\react-native-gifted-chat\example>npx expo start --android
node:internal/modules/cjs/loader:1146
  throw err;
  ^

Error: Cannot find module 'C:\Projects\Henrik\test\react-native-gifted-chat\example\node_modules\expo\bin\cli'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v21.5.0

**Comment by HenrikZabel** [comment]
@kesha-antonov I don't really get an error except `ERROR  Error: Native module not found, js engine: hermes`. The example will not even install

**Comment by HaythamT95** [comment]
> > And also in 2.6.0 the property `renderUsernameOnMessage: PropTypes.Requireable<boolean>;` was removed so messages doesn't have username rendering.
> 
> What do you mean?
> 
> https://github.com/search?q=repo%3AFaridSafi%2Freact-native-gifted-chat%20renderUsernameOnMessage&type=code


**Note**: when the project is JS there is no problem with this error, but when it's typescript there is an error.

<img width="787" alt="Screenshot 2024-08-28 at 13 05 18" src="https://github.com/user-attachments/assets/d5e876b3-43bb-4b43-8fea-b9270026c6f0">

When I go to giftedchat component the property is not present their.
<img width="540" alt="Screenshot 2024-08-28 at 13 03 17" src="https://github.com/user-attachments/assets/e8f005a7-a60e-40fc-94b3-6cc22dadad9b">

It's present in Bubble component though, but even if I put the property into the Bubble component the username still does not appear.

<img width="636" alt="Screenshot 2024-08-28 at 13 12 46" src="https://github.com/user-attachments/assets/c472f50e-db4f-420c-b117-758ccd86df41">
<img width="324" alt="Screenshot 2024-08-28 at 13 14 35" src="https://github.com/user-attachments/assets/b0b64cd3-d0db-4892-915d-a28f0524bf0a">
<img width="346" alt="Screenshot 2024-08-28 at 13 16 54" src="https://github.com/user-attachments/assets/fba10784-08ed-4283-9b9f-ab508bb516f9">

**Comment by sukarn-dsb** [comment]
I am getting the same issue. whenever I press the send button it throws an error, Native module not found, js engine: hermes

**Comment by kesha-antonov** [comment]
Did you also install reanimated?

https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/

**Comment by HenrikZabel** [comment]
Yes. Everything is installed as documented. Is the example working on your machine?

**Comment by kesha-antonov** [comment]
Looks like issue with this lib

https://github.com/uuidjs/uuid/issues/570

I'll make a fix

**Comment by jamesholcomb** [comment]
I resolved this error by adding a dep in my package.json to `react-native-get-random-values`, then `npx pod-install` for iOS.  You'll need to rebuild for android.

**Comment by mirsahib** [comment]
![gifted](https://github.com/user-attachments/assets/4893fc73-dc19-4904-a2bb-2fad5b101df3)
I have the above issue but fixed with @jamesholcomb suggestion

**Comment by kesha-antonov** [comment]
Released fixed in 2.6.1 https://www.npmjs.com/package/react-native-gifted-chat/v/2.6.1

Follow installation guide once again https://github.com/FaridSafi/react-native-gifted-chat?tab=readme-ov-file#installation

**Comment by MGS-DEV** [comment]
Compared to the previous version that did not open, now with 2.6.1 the "Native module not found" error is triggered at onSend.

**Comment by kesha-antonov** [comment]
Please try https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/2.6.2

**Comment by MGS-DEV** [comment]
It works now, thank you very much!

**Comment by 121-vip** [comment]
Got this issue in 2.6.3 but also resolved the same way @jamesholcomb did it in

https://github.com/FaridSafi/react-native-gifted-chat/issues/2519#issuecomment-2315623637
