### ISSUE TITLE
Statusbar color changes to black

### ISSUE THREAD

**Issue by HenrikZabel** [FaridSafi/react-native-gifted-chat#2522]
#### Issue Description

When navigating to a screen with the GiftedChat component following is happening:

[untitled.webm](https://github.com/user-attachments/assets/81ce972d-84ff-4f28-b3bd-d95d7639be8c)

#### Steps to Reproduce / Code Snippets

https://github.com/FaridSafi/react-native-gifted-chat?tab=readme-ov-file#example

I've used the official example

#### Expected Results

Not changing the statusbar color to black

#### Additional Information

* Nodejs version: v21.5.0
* React version: 18.2.0
* React Native version: 0.74.3
* react-native-gifted-chat version: ^2.6.0
* Platform(s) (iOS, Android, or both?): Android (Couldn't test iOS)
* TypeScript version: ~5.3.3

I am using Expo with the expo router.

```tsx
// app/(main)/_layout.tsx
import { color } from '@/constants/Colors';
import { Stack } from 'expo-router';
import React from 'react';
import { Text, View } from 'react-native';

export default function AppLayout() {
  return (
    <Stack
      screenOptions={{
        headerStyle: {
          backgroundColor: color.white,
        },
        headerShadowVisible: false,
      }}>
      <Stack.Screen name="(tabs)" options={{ headerShown: false }} />
      <Stack.Screen
        name="chat"
        options={{
          title: '',
          headerBackTitleVisible: false,
          headerTitle: () => (
            <View
              style={{
                flexDirection: 'row',
                width: 220,
                alignItems: 'center',
                gap: 10,
                paddingBottom: 4,
              }}>
              <View
                style={{
                  width: 40,
                  height: 40,
                  borderRadius: 20,
                  backgroundColor: color.gray,
                }}
              />
              <Text style={{ fontSize: 16, fontWeight: '500' }}>@henrik</Text>
            </View>
          ),
        }}
      />
    </Stack>
  );
}
```

```tsx
// app/(main)/chat.tsx
import React, { useCallback, useEffect, useState } from 'react';
import { GiftedChat, IMessage } from 'react-native-gifted-chat';

export default function ChatScreen() {
  const [messages, setMessages] = useState<IMessage[]>([]);

  useEffect(() => {
    setMessages([
      {
        _id: 1,
        text: 'Hello developer',
        createdAt: new Date(),
        user: {
          _id: 2,
          name: 'React Native',
          avatar: 'https://placeimg.com/140/140/any',
        },
      },
    ]);
  }, []);

  const onSend = useCallback((messages: IMessage[] = []) => {
    setMessages(previousMessages =>
      GiftedChat.append(previousMessages, messages),
    );
  }, []);

  return (
    <GiftedChat
      messages={messages}
      onSend={messages => onSend(messages)}
      user={{
        _id: 1,
      }}
    />
  );
}
```

**Comment by Inzenith** [comment]
@HenrikZabel Hi, I had this issue too. You have to edit "react-native-gifted-chat/lib/GiftedChat.js" and add "{isStatusBarTranslucentAndroid:true}" prop to "useAnimatedKeyboard()" command. You can use patch-package and patch this file.

**Comment by pnthach95** [comment]
> @HenrikZabel Hi, I had this issue too. You have to edit "react-native-gifted-chat/lib/GiftedChat.js" and add "{isStatusBarTranslucentAndroid:true}" prop to "useAnimatedKeyboard()" command. You can use patch-package and patch this file.

Thank you, it worked. And if you enable edge to edge mode, you have to wait for this PR https://github.com/software-mansion/react-native-reanimated/pull/6431 to be merged and released

**Comment by maxwellwachira** [comment]
> > [@HenrikZabel](https://github.com/HenrikZabel) Hi, I had this issue too. You have to edit "react-native-gifted-chat/lib/GiftedChat.js" and add "{isStatusBarTranslucentAndroid:true}" prop to "useAnimatedKeyboard()" command. You can use patch-package and patch this file.
> 
> Thank you so much for this! Did you happen to have a tab navigator? My tabs are somehow being "pushed" down off the screen so that only the tops of them are visible. Any idea what might be causing that?

Did you find a solution? i am experiencing the same issue. My tab navigator is being pushed down

**Comment by jgritten** [comment]
> [@HenrikZabel](https://github.com/HenrikZabel) Hi, I had this issue too. You have to edit "react-native-gifted-chat/lib/GiftedChat.js" and add "{isStatusBarTranslucentAndroid:true}" prop to "useAnimatedKeyboard()" command. You can use patch-package and patch this file.

This worked. I hope the devs see this and it can be resolved in the future. seems simple enough

**Comment by jvegax** [comment]
Im not using react-native-gifted-chat but Im having the same problem... only on android my status bar goes full black

**Comment by shubham-ghanghotia** [comment]
In the latest version, the file `"react-native-gifted-chat/lib/GiftedChat.js"` is not present, and the prop `isStatusBarTranslucentAndroid` is also missing. How should I handle this?

**Comment by MuhammadAliShoaib** [comment]
In the latest version, the file "react-native-gifted-chat/lib/GiftedChat.js" is not present, and the prop isStatusBarTranslucentAndroid is also missing. How should I handle this?

Any Update on this?

**Comment by adirsation** [comment]
While using version 2.8.1, we're missing the `isStatusBarTranslucentAndroid` property.
Adding this:
```
useFocusEffect(
    useCallback(() => {
      if (Platform.OS === 'android') {
        setTimeout(() => {
          StatusBar.setBackgroundColor('transparent')
          StatusBar.setTranslucent(true)
        }, 100)
      }
    }, [])
  )
```

To the component which imports the GiftedChat helped, until they will release a fix.

**Comment by MianIbrarHussain** [comment]
> In the latest version, the file "react-native-gifted-chat/lib/GiftedChat.js" is not present, and the prop isStatusBarTranslucentAndroid is also missing. How should I handle this?
> 
> Any Update on this?

Add this property statusBarTranslucent={true} to KeyboardProvider in "react-native-gifted-chat/lib/GiftedChat/index.js"

**Comment by bahblesson** [comment]
> > Dans la dernière version, le fichier « react-native-gifted-chat/lib/GiftedChat.js » est manquant, ainsi que la propriété isStatusBarTranslucentAndroid. Comment gérer ce problème ?
> > Des nouvelles à ce sujet ?
> 
> Ajoutez cette propriété statusBarTranslucent={true} à KeyboardProvider dans « react-native-gifted-chat/lib/GiftedChat/index.js »

Ça a fonctionné pour moi, merci.

**Comment by MuNitCat** [comment]
如果用的版本是2.8.1， 需要修改 node_modules/react-native-gifted-chat/lib/GiftedChat/index.js 
建议直接使用patch-package，  文件 patches /  `react-native-gifted-chat+2.8.1.patch`
```
diff --git a/node_modules/react-native-gifted-chat/lib/GiftedChat/index.js b/node_modules/react-native-gifted-chat/lib/GiftedChat/index.js
index 4fc42d2..11888c9 100644
--- a/node_modules/react-native-gifted-chat/lib/GiftedChat/index.js
+++ b/node_modules/react-native-gifted-chat/lib/GiftedChat/index.js
@@ -279,7 +279,7 @@ function GiftedChat(props) {
     </GiftedChatContext.Provider>);
 }
 function GiftedChatWrapper(props) {
-    return (<KeyboardProvider>
+    return (<KeyboardProvider statusBarTranslucent={true}>
       <GiftedChat {...props}/>
     </KeyboardProvider>);
 }
diff --git a/node_modules/react-native-gifted-chat/src/GiftedChat/index.tsx b/node_modules/react-native-gifted-chat/src/GiftedChat/index.tsx
index 3e0bcd0..21c3f02 100644
--- a/node_modules/react-native-gifted-chat/src/GiftedChat/index.tsx
+++ b/node_modules/react-native-gifted-chat/src/GiftedChat/index.tsx
@@ -449,7 +449,7 @@ function GiftedChat<TMessage extends IMessage = IMessage> (
 
 function GiftedChatWrapper<TMessage extends IMessage = IMessage> (props: GiftedChatProps<TMessage>) {
   return (
-    <KeyboardProvider>
+    <KeyboardProvider statusBarTranslucent={true}>
       <GiftedChat<TMessage> {...props} />
     </KeyboardProvider>
   )

```

**Comment by raja-ditinus** [comment]
<GiftedChat
          bottomOffset={0}
          // Must match translucent Android status bar, otherwise keyboard
          // height is wrong by ~StatusBar height (composer gap / overlap).
          isStatusBarTranslucentAndroid={Platform.OS === 'android'}
/>
