### ISSUE TITLE
renderUsernameOnMessage prop error on Typescript project

### ISSUE THREAD

**Issue by HaythamT95** [FaridSafi/react-native-gifted-chat#2525]
#### Issue Description

renderUsernameOnMessage prop shows error on an Expo Typescript project

#### Additional Information

<img width="460" alt="Screenshot 2024-09-02 at 13 15 52" src="https://github.com/user-attachments/assets/53811f25-6a0f-4ff1-93f7-63e6a6cfcd2f">

<img width="740" alt="Screenshot 2024-09-02 at 13 19 44" src="https://github.com/user-attachments/assets/d17f3f18-9ad3-41d9-9ce1-ef285883a2cc">

* Nodejs version: 20.4.0
* React version: 18.2.0
* React Native version: 0.74.5
* react-native-gifted-chat version: ^2.6.2
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: ~5.3.3

**Comment by zkteco-home** [comment]
same issue

**Comment by zkteco-home** [comment]
![image](https://github.com/user-attachments/assets/8ac98396-9a28-4ca7-9e5d-e3518b166a58)
property is there in Doc,but it is removed

**Comment by kesha-antonov** [comment]
Added in https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/2.6.3
