### ISSUE TITLE
Can't adjust `bottomOffset` prop to remove padding between Input Field and navigation bottom bar

### ISSUE THREAD

**Issue by devHybrid0306** [FaridSafi/react-native-gifted-chat#2526]
#### Issue Description
Seems like `bottomOffset` prop is removed from `GiftedChat` component.

#### Steps to Reproduce / Code Snippets
`<GiftedChat bottomOffset={70}  ... />`

#### Expected Results
Want to remove padding between ReactNativeGiftedChat input field and app navigation bottom bar.
In previous versions, adding `bottomOffset` worked, but recent versions doesn't work.

#### Additional Information

* Nodejs version: 18.19.0
* React version:
* React Native version: 0.74.5
* react-native-gifted-chat version: 2.6.2
* Platform(s) (iOS, Android, or both?): React Native Expo Android and iOS
* TypeScript version: 2.0.4

**Comment by danilvalov** [comment]
No more `bottomOffset` option after merging [this PR](https://github.com/FaridSafi/react-native-gifted-chat/pull/2493/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L388)

**Comment by kesha-antonov** [comment]
https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/2.6.3
