### ISSUE TITLE
Expose GiftedChat

### ISSUE THREAD

**Issue by jeromegrosse** [FaridSafi/react-native-gifted-chat#253]
I would like to use the GiftedAvatar component without all the logic of Avatar. GiftedAvatar includes a pretty nice logic such as displaying an image or created an avatar with a background color based on the name of the user. 

Is there any particular reason why this module is not exposed?

**Comment by jeromegrosse** [comment]
Merge request: #254

**Comment by Faolain** [comment]
@jeromegrosse can you please close this issue?
