### ISSUE TITLE
bottomOffset not working in updated version 

### ISSUE THREAD

**Issue by suniltiwarisharecare** [FaridSafi/react-native-gifted-chat#2531]
#### Issue Description

After update version 2.4 to 2.6 many issue has started now.
bottomOffset is not working in the current version and showing space between keyboard and textbox.

#### Steps to Reproduce / Code Snippets

Once you click on focus on the textbox, you can see space has started between the keyboard and the textbox.

#### Expected Results

need bottomOffset to handle such issues.

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by sizuf** [comment]
According my tests the issue seems to be starting with v2.5.0

**Comment by danilvalov** [comment]
@suniltiwarisharecare I hope I fixed this issue in this PR: https://github.com/FaridSafi/react-native-gifted-chat/pull/2530

You can try to use a code from this repo directly with my changes to be sure this option works correctly

**Comment by kesha-antonov** [comment]
Released https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/2.6.3

**Comment by melyux** [comment]
I'm on 2.6.4, it still doesn't work.
