### ISSUE TITLE
Feature Request - Empty container style with input box 

### ISSUE THREAD

**Issue by MrFarhan** [FaridSafi/react-native-gifted-chat#2535]
First of all, thank you for this beautiful library.

I am using react native gifted chat for my chat feature in react native.

Currently, I come across the feature to show something like the below along with the text input:

![image](https://github.com/user-attachments/assets/c86eb50f-adaa-4732-927b-2de1b7b0c6cf)

It would be great if this feature is implemented in this library similarly to flat list, developer can customize it with listEmptyContainer prop in gifted chat.

Also in general the empty chat screen looks weird (when any of the party is initiating the conversation).

**Comment by Randall71** [comment]
Are you tested with `renderChatEmpty` ?

**Comment by MrFarhan** [comment]
I tried but the text inside that is flipped, and the issue for that is already created, with temporary work around.

**Comment by MrFarhan** [comment]
Closing this as renderChatEmpty can be used for empty container.
