### ISSUE TITLE
"methods.ForEach is not a function" in example project

### ISSUE THREAD

**Issue by jasonwcfan** [FaridSafi/react-native-gifted-chat#255]
#### Issue Description

When running the xample project (npm install -> react-native run-ios), the app launches but immediately crashes with the error:
#### Steps to Reproduce / Code Snippets

Run example app as usual, get this error:
`Unhandled JS Exception: TypeError: methods.forEach is not a function. (In 'methods.forEach', 'methods.forEach' is undefined)`
#### Additional Information
- React Native version: 0.34
- react-native-gifted-chat version: current master branch example project
- Platform(s) (iOS, Android, or both?): iOS, haven't tested on android

Also, I am able to build the project successfully in Xcode, but still get this error immediately after the app actually launches. A quick search through both the Xcode project and the JS files reveals no references to "methods.forEach" that I could find. Also, I should add that I was able to add gifted chat to my own project with no issues, so it only happens with the example project. Any idea why this is happening?

**Comment by wangdetong** [comment]
I also encountered this problem, 
before: use xcode run directly
now：First use terminal ："npm start"，then use xcode run，that is ok!

**Comment by jimmyhmiller** [comment]
Google translate of @wangdetong's comment because it helped me.

>I have encountered this problem, and later resolved:
You may run a number of projects, run the current project to ensure that the last project npm start is closed

I had another project on a later version of react-native whose packager was still running. Killing that and re-running the project fiexd this problem for me.

**Comment by dubiao** [comment]
@wangdetong Comments in English helps more people. Thanks. Your comment helped me, too.
