### ISSUE TITLE
Native module not found

### ISSUE THREAD

**Issue by henrymartison** [FaridSafi/react-native-gifted-chat#2554]
https://github.com/user-attachments/assets/2d451d62-1e04-41b4-9883-e35f128733a4

#### Issue Description

hello guys, when trying to send a message, I keep getting this error: "Native module not found"

#### Steps to Reproduce / Code Snippets
null

#### Expected Results

be able to send message

#### Additional Information

* Nodejs version: 20.10.0
* React version: 18.2.0
* React Native version: 0.74.5
* react-native-gifted-chat version: 2.6.4
* Platform(s) (iOS, Android, or both?): iOS
* TypeScript version: 5.3.3

**Comment by henrymartison** [comment]
> install expo-random first

**Comment by khandanial419** [comment]
Create build again it will resolve the issue.. i got also this error than i create build again it will solve that issue
