### ISSUE TITLE
Any ideas to use GiftedChat inside a ScrollView?

### ISSUE THREAD

**Issue by marcusfelix** [FaridSafi/react-native-gifted-chat#258]
When i put the GiftedChat  inside a ScrollView the height is setted automatically and we have this lame experience. I know this isnt the right use of GiftedChat but there is any possibility to create a workaround to render a flexible height View instead ListView to render the messages?

```
<ScrollView style={{ flex: 1 }}>
/* More layout objects */
<GiftedChat/>
</ScrollView>
```

I need to render the chat right below some stuff to contextualize the subject but the GiftedChat is setted to work full screen.

Any thoughts?

React Native version: 0.30
react-native-gifted-chat version: 0.0.10
Platform(s) (iOS, Android, or both?): Android

**Comment by shivekkhurana** [comment]
Did you try giving ScrollView a height prop ?

**Comment by latimesmike** [comment]
This is what I ended up using:

```
 <View style={{flex: 1}}>
      <ScrollableTabView
        style={{marginTop: 20}}
        initialPage={0}
        renderTabBar={() => <ScrollableTabBar />}
      >
        <View 
          style={{flex: 1}}
          tabLabel='Conversation'
        >
          <GiftedChat
            bottomOffset={0}
            messages={this.state.messages}
            onSend={this.onSend}
            user={{
              _id: 1,
            }}
          />
        </View>
      </ScrollableTabView>
    </View>
```

**Comment by brzonsea** [comment]
I've tried that... But it doesn't seem to work. Other layout objects are rendered, but I do not see any trace of the <GiftedChat> component.

**Comment by bhtruong93** [comment]
Anyone have any luck on this? I'm having the same issue, here's what my render function basically looks like:
```
    render() {
        return (
            <Container>
                <Header>
                    <Left>
                        <BackButton onPress={() => this.props.navigation.goBack()} />
                    </Left>
                </Header>
                
                <View style={{ flex: 1, backgroundColor: 'white' }}>
                    <View style={{ width: 400, height: 270 }}>
                        { this.getImage() }
                    </View>
                    <GiftedChat
                        messages={this.state.filteredMessages}
                    />
                </View>
            </Container>
        );
    }
```


So far the closest I've been able to get it is this:
![test1](https://user-images.githubusercontent.com/13461241/37112909-b2e4074e-21f8-11e8-930a-8abe002db1f5.gif)

But the final would hopefully look more like FB's:
![img_0131 trim 2](https://user-images.githubusercontent.com/13461241/37113180-765e9e0a-21f9-11e8-9e43-159f4bb76e81.gif)

**Comment by robertvorthman** [comment]
I have a solution, a little hacky, but the result is pleasing continuous scroll from content to comments beneath, like Facebook.

![gifted chat post comments 2019-11-16 19_54_16](https://user-images.githubusercontent.com/4665046/69001365-e8b72280-08aa-11ea-8acd-c64b5e05a3ce.gif)

Setting the `loadEarlier` prop to true shows a header above GiftedChat's ListView.  You can put your own custom component into that header with the `renderLoadEarlier` prop.  Edit GiftedChat's source code file, MessageContainer.js, to return the ListView even when the messages array is empty, and change a style rule.  patch-package makes it easy to saves changes you make to node_modules.  Once you edit MessageContainer.js, you'll see that GiftedChat's source code is well-structured, I was able to easily edit Message.js to customize this library for my needs.

```jsx
<GiftedChat
    {...theUsualProps}
    loadEarlier={true}
    renderLoadEarlier={() => <View style={{ flex: 1 }}>{myScreenContent}</View>}
    alignTop={true}
    listViewProps={{
        contentContainerStyle: {
            flexGrow: 1,
            justifyContent: 'flex-end'
        }
    }}
/>
```

**Edit the source code** in /node_modules/react-native-gifted-chat/lib/MessageContainer.js

At the top of the file, add `flex:1` to the `containerAlignTop` style.
```js
containerAlignTop: {
  flexDirection: 'row',
  alignItems: 'flex-start',
  flex: 1, //add this
}
```

At the bottom of the file, in the render function, I changed it to always return the content even if the messages array is empty.

```js
render() {
        /* if (!this.props.messages ||
            (this.props.messages && this.props.messages.length === 0)) {
            return <View style={styles.container}/>;
        } */
        return (<View style={this.props.alignTop ? styles.containerAlignTop : styles.container}>
        {this.state.showScrollBottom && this.props.scrollToBottom
            ? this.renderScrollToBottomWrapper()
            : null}
        <FlatList ref={this.flatListRef} extraData={this.props.extraData} keyExtractor={this.keyExtractor} enableEmptySections automaticallyAdjustContentInsets={false} inverted={this.props.inverted} data={this.props.messages} style={styles.listStyle} contentContainerStyle={styles.contentContainerStyle} renderItem={this.renderRow} {...this.props.invertibleScrollViewProps} ListFooterComponent={this.renderHeaderWrapper} ListHeaderComponent={this.renderFooter} onScroll={this.handleOnScroll} scrollEventThrottle={100} {...this.props.listViewProps}/>
      </View>);
    }
```

**Comment by robertvorthman** [comment]
Here is an updated solution.  My last post is flawed in that the list always loads showing the bottom message/comment, not the main content.  I'm using a boolean flag to control whether the bottom or the top of the scrollable content is initially visible.

```jsx
<GiftedChat
    {...theUsualProps}
    loadEarlier={true}
    renderLoadEarlier={() => <View>{myScreenContent}</View>}
    inverted={false}
    alignTop={true}
    initialOffsetBottom={false} //needs to be added to MessageContainer.js source code
    listViewProps={{
        contentContainerStyle: {
            flexGrow: 1,
        }
    }}
/>
```

Here is my patch file for the necessary source code changes to MessageContainer.js.  Add the flex style rule, add the reference to the initialOffsetBottom prop, and lastly comment out the if block so content is returned even with zero messages.

```diff
diff --git a/node_modules/react-native-gifted-chat/lib/MessageContainer.js b/node_modules/react-native-gifted-chat/lib/MessageContainer.js
index fc93241..94a722d 100644
--- a/node_modules/react-native-gifted-chat/lib/MessageContainer.js
+++ b/node_modules/react-native-gifted-chat/lib/MessageContainer.js
@@ -12,6 +12,7 @@ const styles = StyleSheet.create({
     containerAlignTop: {
         flexDirection: 'row',
         alignItems: 'flex-start',
+        flex: 1
     },
     contentContainerStyle: {
         justifyContent: 'flex-end',
@@ -146,7 +147,8 @@ export default class MessageContainer extends React.PureComponent {
         };
         this.renderHeaderWrapper = () => (<View style={styles.headerWrapper}>{this.renderLoadEarlier()}</View>);
         this.onLayoutList = () => {
-            if (!this.props.inverted &&
+            if (this.props.initialOffsetBottom &&
+                !this.props.inverted &&
                 !!this.props.messages &&
                 this.props.messages.length) {
                 setTimeout(() => this.scrollToBottom(false), 15 * this.props.messages.length);
@@ -197,10 +199,10 @@ export default class MessageContainer extends React.PureComponent {
       </View>);
     }
     render() {
-        if (!this.props.messages ||
+        /* if (!this.props.messages ||
             (this.props.messages && this.props.messages.length === 0)) {
             return <View style={styles.container}/>;
-        }
+        } */
         const { inverted } = this.props;
         return (<View style={this.props.alignTop ? styles.containerAlignTop : styles.container}>
         {this.state.showScrollBottom && this.props.scrollToBottom
```

**Comment by nxnam1102** [comment]
try this https://github.com/FaridSafi/react-native-gifted-chat/issues/1898#issuecomment-876897856
