### ISSUE TITLE
How can I add image as message? Default textbox not showing the "+" icon

### ISSUE THREAD

**Issue by mdrajib001** [FaridSafi/react-native-gifted-chat#262]
I am using latest react native and gifted chat. No plus icon is showing in my textbox to upload image. Do I need additional code to get this feature? Please help

**Comment by dgdavid** [comment]
Yes, you need to add additional code.

You can take a look to the [example app](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/example) It has implemented a [CustomActions](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/example/CustomActions.js) for the [iOS platform](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/example/App.js#L131).
