### ISSUE TITLE
Example Package.json for iOS 10

### ISSUE THREAD

**Issue by sean-connor** [FaridSafi/react-native-gifted-chat#263]
#### Issue Description

Unhandled JS Exception: SyntaxError: JSON Parse error: Unexpected identified "RCTWebSocketModule"
#### Steps to Reproduce / Code Snippets

Running example on an iOS 10 simulator.
#### Fix

Upgrade React Native to 0.34.0 and React to 15.3.1.
#### Additional Information
- React Native version: 0.34.0
- react-native-gifted-chat version: 0.0.10
- Platform(s) (iOS, Android, or both?): iOS

**Comment by devbriguy** [comment]
Sounds like an Xcode 8 issue. I followed Tim in https://github.com/facebook/react-native/issues/8584
