### ISSUE TITLE
Custom Modal Isssue

### ISSUE THREAD

**Issue by pardeepbeniwal** [FaridSafi/react-native-gifted-chat#267]
How can I add custom modal to gifted chat?
I  have created new function render modal below code:
renderModal(props) {  
      return (
             <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
            <TouchableOpacity onPress={() => this.setState({open: true})}>
               <Text>Open modal</Text>
            </TouchableOpacity>
            <Modal
               offset={this.state.offset}
               open={this.state.open}
               modalDidOpen={() => console.log('modal did open')}
               modalDidClose={() => this.setState({open: false})}
               style={{alignItems: 'center'}}>
               <View>
                  <Text style={{fontSize: 20, marginBottom: 10}}>Hello world!</Text>
                  <TouchableOpacity
                     style={{margin: 5}}
                     onPress={() => this.setState({offset: -100})}>
                     <Text>Move modal up</Text>
                  </TouchableOpacity>
                  <TouchableOpacity
                     style={{margin: 5}}
                     onPress={() => this.setState({offset: 0})}>
                     <Text>Reset modal position</Text>
                  </TouchableOpacity>
                  <TouchableOpacity
                     style={{margin: 5}}
                     onPress={() => this.setState({open: false})}>
                     <Text>Close modal</Text>
                  </TouchableOpacity>
               </View>
            </Modal>
         </View>
      );

  }

then use in render function
render() {
      return (
            <GiftedChat
            messages={this.state.messages}
            messagesPopUp={this.state.messagesPopUp}
            onSend={this.onSend}
            loadEarlier={this.state.loadEarlier}
            onLoadEarlier={this.onLoadEarlier}
            isLoadingEarlier={this.state.isLoadingEarlier}
            user={{
              _id: 1, // sent messages should have same user._id
            }}
            renderActions={this.renderCustomActions}
            renderBubble={this.renderBubble}
            renderCustomView={this.renderCustomView}     
            renderFooter={this.renderFooter}
            renderModal={this.renderModal}
            />

```
  );
```

   }

but this is not working.

**Comment by edcalderin** [comment]
I am having the same issue.

**Comment by vahid13666** [comment]
actually there is no place for renderModal, you can play the function of renderAction

**Comment by saumil-palm** [comment]
hello any update how to disaply modal when you are using gifted chat ?
