### ISSUE TITLE
How change background in messages container ?

### ISSUE THREAD

**Issue by noris666** [FaridSafi/react-native-gifted-chat#268]
#### Issue Description

I dont find any solution to change background in messages container. How i can do this ? 
#### Steps to Reproduce / Code Snippets

I try this code:

`   renderMessages(props) {
        const stl = StyleSheet.create({ chatStyle: { backgroundColor: '#ff0000'} })

```
    return (
        <MessageContainer style={stl.chatStyle}  {...props} />
    );
}`
```

with renderMessages={this.renderMessageText}
It is does not work ! I again look white background in the container of messages.
And i get effect when i change this line: 
https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/MessageContainer.js#L140
I add after flex: 1, backgroundColor: '#ff0000' to test and it is works !
#### Expected Results

Changing background in messages container.
#### Additional Information
- React Native version: 0.35.0
- react-native-gifted-chat version: 0.0.10
- Platform(s) (iOS, Android, or both?): iOS 10

**Comment by noris666** [comment]
Recipe to solve that so simple.

```
<View style={{backgroundColor: '#yourcolor'}}>
  <GiftedChat ...props />
</View>
```

**Comment by faisalzahid** [comment]
@noris666 Where do I do this? Is it in the render() function or renderMessage() function. 

After adding it in renderMessage() my chat functionality stopped working i.e i was unable to reference the GiftedChat object and append to it. Any idea what i'm doing wrong? 

![image](https://user-images.githubusercontent.com/25720059/26987606-a43b1290-4d65-11e7-87a9-d9206eaea5fa.png)

![image](https://user-images.githubusercontent.com/25720059/26987630-ba923f46-4d65-11e7-9164-6669fd49e4e2.png)

**Comment by noris666** [comment]
@faisalzahid place View before GiftedChat component :-) inside render function :-) look attentively
 my example 👍

**Comment by faisalzahid** [comment]
@noris666 Feel very dumb right now. Pardon my confusion. I just started to use react.

Here is my render function now.

`  render(props) {
    var user = { _id: this.state.userId || -1, name: nickname };

    return (
      <View style={{ backgroundColor: "#000000" }}>
        <GiftedChat
          {...props}
          messages={this.state.messages}
          onSend={this.onSend}
          user={user}
          onInputTextChanged={this.onInputTextChanged}
          renderBubble={this.renderBubble}
          renderActions={this.renderCustomActions}
          renderFooter={this.renderFooter}
        />
      </View>
    );
  }`

But it shows the same problem. It stopped the GiftedChat component to work, neither it changed the background color.

**Comment by faisalzahid** [comment]
Ok, figured it out. The wrapping view was not given any dimensions. Hence it wasn't showing. This works.

`    return (
      <View style={{ backgroundColor: "#000000", flex: 1 }}>
        <GiftedChat
          {...props}
          messages={this.state.messages}
          onSend={this.onSend}
          user={user}
          onInputTextChanged={this.onInputTextChanged}
          renderBubble={this.renderBubble}
          renderActions={this.renderCustomActions}
          renderFooter={this.renderFooter}
        />
      </View>
    );`

**Comment by nandiniparimi1107** [comment]
is there a way to add background image on the bubble?

**Comment by NicWickman** [comment]
I would also like to add an image as the background. Maybe using React's BackgroundImage component?

**Comment by formaldehydeson** [comment]
ImageBackground component works fine here as well

`
<ImageBackground
    source={...}
    style={{flex: 1}}
>
    <GiftedChat
      ...props
    />
</ImageBackground>
`

**Comment by mkhoussid** [comment]
If you want just a certain color, you could use the `listViewProps`:
```
  <GiftedChat
      listViewProps={{
        style: {
          backgroundColor: 'purple',
        },
      }}
    . . .
/>
```
If you want a custom image, you can add it as in this comment:

```
<ImageBackground
   source={{ uri: 'https://i.pinimg.com/564x/d8/3f/3e/d83f3e30ff0a2ebe5e61021a3270aeb0.jpg' }}
   style={{ flex: 1 }}
>
  <GiftedChat
      listViewProps={{
        style: {
          backgroundColor: 'purple',
        },
      }}
    . . .
  />
</ImageBackground>
```
Make sure you get rid of `listViewProps` in the `<GiftedChat {...props} />` component if you want a custom image background, otherwise it will override your `<ImageBackground />`.

**Comment by ahmadtech199** [comment]
<View 
            style={{flex:1, backgroundColor: '#e8eaed' }}>
            <GiftedChat
                messages={messages}
                onSend={messages => onSend(messages)}
                user={{
                    _id: 1,
                }}
            />
        </View>

**Comment by adhip94** [comment]
I have done the above and it works fine, except on notched devices, the bottom part looks weird
<img width="326" alt="Screenshot 2021-06-26 at 10 28 24 PM" src="https://user-images.githubusercontent.com/20703483/123520332-d54a7b00-d6cd-11eb-9fc6-f28ad1f604b3.png">

I want the bottom to be completely white, something similar to WhatsApp. Any ideas?
