### ISSUE TITLE
softInputMode issue

### ISSUE THREAD

**Issue by Ocherednyara** [FaridSafi/react-native-gifted-chat#269]
Is it possible to use giftedchat with softInputModes that aren't adjustResize, such as adjustPan/Unspecified? If not is there any way to dynamically change softInputMode when there is a giftedchat component onscreen?
- React Native version: 0.34
- react-native-gifted-chat version: Latest
- Platform(s) (iOS, Android, or both?): Android

**Comment by kelset** [comment]
Did you find a solution to your problem in the end?
I'm interested in knowing those answers too.

**Comment by kelset** [comment]
Thanks, I'm looking at it right now.
Seems quite outdated, did you managed to make it work with RN > 0.30?
