### ISSUE TITLE
Using with react-native-navigation

### ISSUE THREAD

**Issue by indivisable** [FaridSafi/react-native-gifted-chat#270]
#### Issue Description

Hello trying to use Gifted Chat inside a Tabs or Modal and it seems to get reset each time. What is best way to integrate into a Navigation library like react-native-navigation? I think it has to do with it being unmounted but should not have problem re-initializing. 

#### Steps to Reproduce / Code Snippets

1) Download and run the react-native-navigation example (https://github.com/wix/react-native-navigation)
2) Install react-native-gifted-chat into the project 
3) Use the example code for gifted-chat and try to put inside a Tab or Modal
4) Try to test with Tabs (does not work at all) or a Modal (works once then not after)

**Comment by kfiroo** [comment]
@indivisable see if this has any useful info https://github.com/FaridSafi/react-native-gifted-chat/issues/244

**Comment by indivisable** [comment]
Thanks @kfiroo this fixed it for me! 

@shivekkhurana

```
import Dimensions from 'Dimensions';
Update 1 - October 9, 2016

It wasn't react-native-navigation or flex:1, what fixed the issue for me was wrapping GiftedChat in

 <View style={{height: Dimensions.get('window').height - 65}}></View>
```
