### ISSUE TITLE
Scrolling to a particular message ?

### ISSUE THREAD

**Issue by AshishGogna** [FaridSafi/react-native-gifted-chat#272]
#### Issue Description

Is there a way to scroll to a particular message's position ?
Or, is there a way to search for a message ?
Please help out.

**Comment by kfiroo** [comment]
@AshishGogna Hey, `GiftedChat` doesn't have this functionality afaik.
Note that the messages are rendered into a `ListView` which renders them in batches so the message you are trying to scroll to might not be rendered yet.

I'd love to help if you have questions

**Comment by itcurves** [comment]
Once list populated can we move it to last? also how I can make it to load previous messages with by default loading last 30 messages?

**Comment by kfiroo** [comment]
Check out how `ListView` works [here](https://facebook.github.io/react-native/docs/listview.html).
It will not render all rows if not needed, for performance reasons, but it's all configurable.
Take a look at `initialListSize`, `pageSize` and `onEndReachedThreshold`

**Comment by AshishGogna** [comment]
@kfiroo Okay, thank you for your help !

**Comment by itcurves** [comment]
@kfiroo thank you  I will check but how to move it to the latest message? Also on a side note can you please recommend how to show a small bubble for new messages, and how to keep checking for the new messages?

**Comment by kfiroo** [comment]
@itcurves 
I don't understand the question, what do you mean "move it to the latest message"?

You can override the render method of almost any component in `GiftedChat` so you can change the way "new" messages are rendered.

Keep checking for new messages depends on your backend I guess.

**Comment by Jonovono** [comment]
+1 Is this possible? it seems do able in a listview component?

http://stackoverflow.com/questions/5856427/how-to-scroll-uitableview-to-specific-position
