### ISSUE TITLE
Major performance issue around InvertableScrollview

### ISSUE THREAD

**Issue by olofd** [FaridSafi/react-native-gifted-chat#276]
#### Issue Description

InvertibleScrollview is used by this project. But in my environment this component makes rendering of the ListView very slow. If I use a standard ScrollView the issue goes away.
I do nothing special here and I render 25 messages on the JSC.
With normal ScrollView rendering takes < 50ms

[![1.jpg](https://s12.postimg.org/qcg3pn5yl/image.jpg)](https://postimg.org/image/wq56swauh/)

[![2.jpg](https://s17.postimg.org/t5rf1aw33/image.jpg)](https://postimg.org/image/76l0e3f8r/)

**Comment by kfiroo** [comment]
@olofd I have tested the component with ~500 messages and rendering was pretty fast.
Could there be any other cause for the slow rendering?
I guess measurements are in DEV mode, can you try it in release mode?

**Comment by olofd** [comment]
This was something RN related. closing.
