### ISSUE TITLE
Using bottomOffset with Tabs

### ISSUE THREAD

**Issue by indivisable** [FaridSafi/react-native-gifted-chat#278]
Hello I am using the Gifted chat with react-native-navigation and cannot seem to get it working with when using Tabs and a fixed bottom offset. I have tried a bunch of things and cannot seem to fix it. Here is exact issue:

https://github.com/FaridSafi/react-native-gifted-chat/issues/169

And some related issues:

https://github.com/FaridSafi/react-native-gifted-chat/issues/232
https://github.com/FaridSafi/react-native-gifted-chat/issues/219

Anyone have know a workaround for this?

**Comment by RobAWilkinson** [comment]
@indivisable I too am experiencing this same problem, did you ever find a solution?

**Comment by RSSfeed** [comment]
Had the same issue and setting `bottomOffset={48.5}` (in my case, tabbar has the height of 48.5) fixed it for me. Maybe this helps

**Comment by LouisJS** [comment]
WIth a TabNavigator i'm actually using

```
<GiftedChat
    messages={messages}
    user={{ _id: 1 }}
    onSend={this.onSend}
    bottomOffset={Platform.OS === "ios" && 48.5}
/>
{Platform.OS === "android" && (
 <KeyboardAvoidingView behavior="padding" />
)}
```

**Comment by MuhammadUmairMoosani** [comment]
<View style={ { flex: 1, marginBottom:8 } }> // add margin bottom
                <GiftedChat
                    messages={ shouts }
                    onSend={ this.onSend }
                  />
</View>

**Comment by rajendersha** [comment]
Its still not working
