### ISSUE TITLE
Pre-populate text input

### ISSUE THREAD

**Issue by hoolymama** [FaridSafi/react-native-gifted-chat#281]
#### Issue Description

I'd like to pre-populate the textInput when the chat is first mounted.
Is there a simple way, or should I implement an alternative composer? 

#### Steps to Reproduce / Code Snippets

I tried to set the prop

    renderComposer={() => <Composer textInputProps={{defaultValue: "Hello, wanna chat?"}}/>}

#### Expected Results

Expected "Hello, wanna chat?" in the textInput - but nothing there

If I instead set `{{value: "Hello, wanna chat?"}}`  it appears, but it is not editable

Thanks

#### Additional Information

* React Native version: 0.36
* react-native-gifted-chat version: 0.0.10
* Platform(s) (iOS, Android, or both?): Android

**Comment by kfiroo** [comment]
@hoolymama I don't think this behaviour is implemented, you could probably hack it in somehow, or implement it and submit your PR.
I'll be happy to assist you if you need

**Comment by hoolymama** [comment]
@kfiroo Thanks for the info! - I'll have a go at implementing it after my deadline in a couple of weeks.

**Comment by cooperka** [comment]
This is now possible in [v0.2.4](https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/v0.2.4) with a custom `text` prop.
