### ISSUE TITLE
Chat component not filling out screen when used with NativeBase

### ISSUE THREAD

**Issue by riazkarim** [FaridSafi/react-native-gifted-chat#284]
#### Issue Description

Chat component not filling out screen when used with NativeBase

#### Steps to Reproduce / Code Snippets

<Container theme={theme}>
                <Header>
                    <Button transparent onPress={() => this.props.navigator.pop()}>
                        <Icon name="chevron-left"/>
                    </Button>
                    <Title>
                        Chat with User
                    </Title>
                </Header>
                <Content>
                    <GiftedChat messages={this.state.messages}
                                onSend={this.onSend}
                                user={{_id: 1,}}
                                bottomOffset={0}
                    />
                </Content>
            </Container>

#### Expected Results

Chat component should fill out entire screen. Instead, it appears to take the top third of the screen.

<img width="541" alt="chat" src="https://cloud.githubusercontent.com/assets/15179855/20410159/b2687c92-ad13-11e6-8c26-38396ee66814.png">

#### Additional Information

* React Native version: 0.37
* react-native-gifted-chat version: latest on npm
* Platform(s) (iOS, Android, or both?): Android

**Comment by riazkarim** [comment]
Code in render() is:

`<Container theme={theme}>
                <Header>
                    <Button transparent onPress={() => this.props.navigator.pop()}>
                        <Icon name="chevron-left"/>
                    </Button>
                    <Title>
                        Chat with User
                    </Title>
                </Header>
                <Content>
                    <GiftedChat messages={this.state.messages}
                                onSend={this.onSend}
                                user={{_id: 1,}}
                                bottomOffset={0}
                    />
                </Content>
            </Container>`

**Comment by dgdavid** [comment]
It seems your problems is caused by `Content` tag [see https://github.com/FaridSafi/react-native-gifted-chat/issues/215#issuecomment-242563478].

You can to add `flex: 1` to its styles or replace with `View`.

**Comment by riazkarim** [comment]
That fixed it. I removed the Content and replaced with a native-base View.

Thanks!

**Comment by rubanraj54** [comment]
I also had the similar problem.

Adding `style={{flex: 1}} contentContainerStyle={{flex: 1}}` to Content solve my problem.

```jsx
<Content style={{flex: 1}} contentContainerStyle={{flex: 1}}>
    <GiftedChat
        messages={this.state.messages}
        onSend={messages => this.onSend(messages)}
        user={{
        _id: 1
        }}
    />
</Content>
```

Cheers,
Ruby.

**Comment by markwindsorr** [comment]
how did you set up the webpack and babel config to get gifted chat working with native base @arrkaye
