### ISSUE TITLE
Change the input placeholder

### ISSUE THREAD

**Issue by joaqtor** [FaridSafi/react-native-gifted-chat#285]
#### Issue Description

I want to change the placeholder text in the TextInput, and only the placeholder. How would you do this without losing the rest of the default props?

**Comment by dgdavid** [comment]
Simply pass the `placeholder` prop to `GiftedChat` component.

Something like

```js
<GiftedChat placeholder='Your custom placeholder'>
```

**Comment by joaqtor** [comment]
Oh, didn't see that. Thank you!!
