### ISSUE TITLE
Strange behavior with onChange in overridden Composer for typing indicator for that user

### ISSUE THREAD

**Issue by devbriguy** [FaridSafi/react-native-gifted-chat#286]
#### Issue Description

By using the`renderComposer` to access the onChange prop it will disable inherited props like `renderSend` and `this.props.text` and the growing height of the TextInput.

#### Steps to Reproduce / Code Snippets
```javascript
  renderComposer(props) {
    return (
      <Composer {...props} onChange={() => this.handleChangeText()} />
    )
  }
```

#### Expected Results

Composer remains intact and onChange sends back event information to be able to fire off that the user is typing.

#### Additional Information

* React Native version: 0.36.0
* react-native-gifted-chat version: 0.0.6
* Platform(s) (iOS, Android, or both?): iOS

**Comment by jayshah123** [comment]
This is because GiftedChat.js uses onType method 
which presumably calculates height of input toolbar.
It would be useful to have a onInputTextChanged sort of thing on GiftedChat API.

**Comment by jayshah123** [comment]
giving our own onChange to Composer probably overrides onType I guess.

**Comment by devbriguy** [comment]
If you are stuck, I fixed this by adding the library locally and then adding onChangeText to Composer: 
```javascript
        onChangeText={(text) => {
           this.props.onChangeText(text)
        }}
```

**Comment by bhavyata9** [comment]
What are the props passed to renderComposer?
