### ISSUE TITLE
Issue when keyboard appears.

### ISSUE THREAD

**Issue by kelvinaliyanto** [FaridSafi/react-native-gifted-chat#288]
Hi, I have an issue regarding the keyboard. It also happens when I tried with your example. Before the keyboard appears:

![whatsapp image 2016-11-21 at 3 02 48 pm](https://cloud.githubusercontent.com/assets/15681219/20473458/d09a4bd8-affb-11e6-97d4-f7459a38e5bd.jpeg)

After the keyboard appears:

![whatsapp image 2016-11-21 at 3 02 49 pm](https://cloud.githubusercontent.com/assets/15681219/20473464/d79b9248-affb-11e6-959a-88ce810dd256.jpeg)

It pushes the view too much. Does anyone have the same issue?

**Comment by dgdavid** [comment]
Please, take a look to https://github.com/FaridSafi/react-native-gifted-chat/issues/118

**Comment by kfiroo** [comment]
Probably need to add `android:windowSoftInputMode="adjustResize"` on your main activity.
Note that it might affect other parts of your app.

**Comment by kelvinaliyanto** [comment]
@dgdavid @kfiroo thanks a lot. Missed the android installation part.

**Comment by kelvinaliyanto** [comment]
@dgdavid @kfiroo thanks a lot. Missed the android installation part.

**Comment by kelvinaliyanto** [comment]
@dgdavid @kfiroo thanks a lot. Missed the android installation part.
