### ISSUE TITLE
Send Button not working while Keyboard is open

### ISSUE THREAD

**Issue by jonas-hrw** [FaridSafi/react-native-gifted-chat#290]
On my iOS version of the App, when the keyboard is open it is not possible to hit the send button. When I try to press it it will close the keyboard instead of sending the message. On Android this works just fine. Once the Keyboard is closed I am able to press the send Button. 

Do you have any Idea how to fix this ? 

* React Native version: 0.36
* react-native-gifted-chat version: v0.0.7
* Platform(s) (iOS, Android, or both?): iOS

**Comment by Micjoyce** [comment]
I also have this problen! Have any idea to fix it?

**Comment by peterkruty** [comment]
Same here

**Comment by PuppyYuan** [comment]
textinpu blur first(keyborad close), then send button can be pressed, but I don't  know how to resolve it

**Comment by morelazers** [comment]
I have this problem on Android too. RN 0.40

**Comment by kfiroo** [comment]
This PR should fix it https://github.com/FaridSafi/react-native-gifted-chat/pull/332
Can you please use master and let me know if this is resolved?

**Comment by morelazers** [comment]
@kfiroo doesn't fix, I tried manually before it was merged.

Also have tried #327 to no avail

**Comment by kfiroo** [comment]
@morelazers try setting `keyboardShouldPersistTaps='always'` in `contentProps` prop of your `react-native-scrollable-tab-view`

**Comment by morelazers** [comment]
@kfiroo that got it, thank you so much!!

**Comment by PuppyYuan** [comment]
thanks , I got it, too

**Comment by ankymtan** [comment]
Wrap your GiftedChat with KeyboardAvoidingView. Will fix.

I struggle the whole day. Turn out I wrap my Gifted chat in a Modal, some one wrap it in a Listview (cmt above), that wraper cause the proplem.

**Comment by GautierCo** [comment]
Thanks @kfiroo this working for me
