### ISSUE TITLE
Feature Request: Make isSameDay and isSameUser functions available inside renderMessage

### ISSUE THREAD

**Issue by scarmuega** [FaridSafi/react-native-gifted-chat#291]
It seems that these 2 funcs are available inside props in every renderXXX func, except inside renderMessage. Would be nice to have them also available there.

Furthermore, I notice that they stateless functions. Maybe they can be refactored as functions directly exported by the module, so that they don't have to be propagated through props.

If you're interested in a PR, I could give it a try.

**Comment by kfiroo** [comment]
@scarmuega sounds good, maybe there are others methods that can be extracted.
PR would be great!

**Comment by benjaminb10** [comment]
@scarmuega how did you manage to use isSameUser in renderBubble for instance?

**Comment by scarmuega** [comment]
@benjaminb10 if you need `isSameUser` inside `renderBubble(props)` you should be able to call `props.isSameUser` directly.

If you need it elsewhere, please check the PR #292 where I propose to expose that logic as a stand-alone function so that it can be imported ad-hoc anywhere.

**Comment by benjaminb10** [comment]
Yes I've just managed to do it cf. https://github.com/FaridSafi/react-native-gifted-chat/issues/299
Thanks for this PR ;)
