### ISSUE TITLE
MessageContainer not shown at all on RN 0.38

### ISSUE THREAD

**Issue by mbardauskas** [FaridSafi/react-native-gifted-chat#293]
#### Issue Description

MessageContainer not shown at all on RN 0.38 when re-rendering GiftedChat multiple times.

#### Steps to Reproduce / Code Snippets

1. Create a view of two different chats
2. Click on one of the chats to open GiftedChat
3. Go back
4. Click on other chat to open GiftedChat with different data

#### Expected Results

Fully rendered chat with new messages.

#### Actual result

MessageContainer not shown (height 0), only TextInput is visible.

#### Additional Information

PR #277 seems to help

* React Native version: 0.38
* react-native-gifted-chat version: 0.0.10
* Platform(s) (iOS, Android, or both?): iOS (tested only iOS)

**Comment by semiautomatix** [comment]
Seems to be an issue. Clicking on the TextInput reveals the messages.
