### ISSUE TITLE
how to pass a callback function which will be called when user types? I can make a pull request, but is anyone reviewing them? 

### ISSUE THREAD

**Issue by yernandus** [FaridSafi/react-native-gifted-chat#294]
#### Issue Description

no callback for typing event, I can not find it on documentation.

**Comment by kfiroo** [comment]
@yernandus You could try to use `renderComposer` and listen to the TextInput events.
I think handling this internally might be out of scope for this project

**Comment by yernandus** [comment]
thanks for the answer, I just wander you have a code to show that someone is typing, but no code to get that event.  In the example it is changed with a timer. I found some methods onChange and onType, and I made it work, should I make a pull request?

**Comment by mxmtsk** [comment]
@yernandus I'd love to see how you implemented this

**Comment by yernandus** [comment]
@mxmtsk actually they already inplement it. Checking documentation. I think it is called onInpuchange

**Comment by rtman** [comment]
@yernandus Could you elaborate with some code as to how you implemented this? I'm not seeing an example in the repo.
