### ISSUE TITLE
Show user name on top of the first message from the user

### ISSUE THREAD

**Issue by benjaminb10** [FaridSafi/react-native-gifted-chat#299]
Hi, is there a way to show user name of the sender of a message on top of the first message from this user.

Something like that:

![screenshot_2016-12-06 13 52 06_drcwjw](https://cloud.githubusercontent.com/assets/2952678/20926137/371322d4-bbbb-11e6-8a63-42ef35cf730d.png)

**Comment by benjaminb10** [comment]
I manage to do it. Add renderBubble attribute to GiftedChat:

```
  render() {
    return (
        <GiftedChat
          messages={messagesList}
          onSend={this.onSend}
          renderBubble={this.renderBubble}
        />
    );
  }
```

Edit a renderBubble function and use utils function like isSameUser and isSameDay
```
  renderBubble(props) {
    if (props.isSameUser(props.currentMessage, props.previousMessage) && props.isSameDay(props.currentMessage, props.previousMessage)) {
      return (
        <Bubble
          {...props}
        />
      );
    }
    return (
      <View>
        <Text style={styles.name}>{props.currentMessage.user.name}</Text>
        <Bubble
          {...props}
        />
      </View>
    );
  }

```

the result give something like that:

![screenshot_2016-12-14 16 34 32_zgx5nd](https://cloud.githubusercontent.com/assets/2952678/21188299/3c91cdee-c21b-11e6-943e-b2ccc56661d4.png)

**Comment by azcodia** [comment]
excuse me, I want to ask, how do you do the validation, here my case is
there is a user and admin, how do I handle it?
