### ISSUE TITLE
Feature request: show bigger emoji when a message contains only an emoji

### ISSUE THREAD

**Issue by benjaminb10** [FaridSafi/react-native-gifted-chat#309]
Just like in whatsapp app, when a message contains only one emoji and no text, we can display the emoji bigger.

**Comment by kfiroo** [comment]
@benjaminb10 override the appropriate `renderXXX` method and implement it :)
This is a specific product spec and should not be part of this package, imho

**Comment by benjaminb10** [comment]
You're right.
