### ISSUE TITLE
Example build fails

### ISSUE THREAD

**Issue by brandondrew** [FaridSafi/react-native-gifted-chat#310]
#### Issue Description

Running .... fails to build the iOS version of the example app.

```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/brandon/Code/Elixir/x.react-native-gifted-chat/example/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTSRWebSocket.o RCTSRWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/brandon/Code/Elixir/x.react-native-gifted-chat/example/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: xcodebuild process exited with code 65
    at ChildProcess.<anonymous> (/Users/brandon/Code/Elixir/x.react-native-gifted-chat/example/node_modules/react-native/local-cli/runIOS/runIOS.js:102:14)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

#### Steps to Reproduce / Code Snippets

```
git clone https://github.com/FaridSafi/react-native-gifted-chat
cd react-native-gifted-chat/example
npm install
react-native run-ios
```

#### Expected Results

I expected to see the iOS simulator open with an example app.

#### Additional Information

* React Native version:  0.30.0  (cli: 1.2.0)
* react-native-gifted-chat version: Latest commit 91312c1  on Sep 8
* Platform(s) (iOS, Android, or both?): iOS
* `xcode-select -print-path`: `/Applications/Xcode.app/Contents/Developer`
* Xcode Version: 8.1

**Comment by hw2008** [comment]
i don't know why it build fails.
but after i change the version to 
    "react": "15.3.2",
    "react-native": "0.37.0",
the Example build succeeded

**Comment by vgorte** [comment]
When receiving this error, the following works for me:

1. Open the project via **XCode**

2. Start it and you should get a *RCTWebsocket* error

3. Doubleclick the RCTWebSocket and remove the value (-werror - wall) within other warning flags
( See solution by TimBroddin @ https://github.com/facebook/react-native/issues/8584)

I think this error occurs because of the way react-natives uses "use strict" in its files.
