### ISSUE TITLE
[Possible regression] It seems that there's a bug when using View in renderBubble

### ISSUE THREAD

**Issue by benjaminb10** [FaridSafi/react-native-gifted-chat#313]
When I use renderBubble and use a parent View for my Bubble (for example to add a Text component on top of the Bubble) I have this graphic bug:

```
  renderBubble(props) {
    return (
      <View>
        <Bubble
          {...props}
        />
      </View>
    );
  }

```

![screenshot_2016-12-19 15 12 59_4sfwk8](https://cloud.githubusercontent.com/assets/2952678/21315696/b4aa6800-c5fd-11e6-80e5-2ea2d7356764.png)

When I remove the View component, I don't have the bug:

```
  renderBubble(props) {
    return (
        <Bubble
          {...props}
        />
    );
  }

```

![screenshot_2016-12-19 15 13 13_be0kqy](https://cloud.githubusercontent.com/assets/2952678/21315703/b92092b0-c5fd-11e6-80c1-13d89e3f7493.png)

I think it's a regression since I've just pull the last master branch and my design have broken.

**Comment by benjaminb10** [comment]
Hi, am I the only one who have thig graphic bug?

**Comment by benjaminb10** [comment]
I manage to fix my graphic bug using renderMessage instead of renderBubble.
I let the issue opened since I don't know if my solution is the good pattern to add a View wrapper on Bubble (or Message).

**Comment by luisfuertes** [comment]
I habe the same problem

**Comment by kfiroo** [comment]
Any leads on what's going on here?

**Comment by luisfuertes** [comment]
I solved it using renderCustomView instead of renderBubble
