### ISSUE TITLE
Keyboard always not appeared

### ISSUE THREAD

**Issue by lidapeng365** [FaridSafi/react-native-gifted-chat#323]
#### Issue Description

I run this control in ios emulator, but keyboard always not show.

#### Steps to Reproduce / Code Snippets

Add this control to my app or run the example in the project.

#### Expected Results

1. Keyboard should be shown, when I click in the text input, 
2. Also I want it always shown there.

#### Additional Information

* React Native version:0.39.2
* react-native-gifted-chat version: 0.0.10
* Platform(s) (iOS, Android, or both?): iOS, not tried on Android.

**Comment by kfiroo** [comment]
Try this
http://stackoverflow.com/questions/24420873/xcode-6-keyboard-does-not-show-up-in-simulator
