### ISSUE TITLE
Choose from Library

### ISSUE THREAD

**Issue by vgorte** [FaridSafi/react-native-gifted-chat#324]
When clicking on "choose from Library" from the example, the app crashes.

Geolocation works fine.

**Comment by lidapeng365** [comment]
I have the same problem.

**Comment by tafelito** [comment]
Make sure node_modules/react-native/Libraries/CameraRoll/RCTCameraRoll.xcodeproj has been imported to project libraries by following the [libraries linking instructions](https://facebook.github.io/react-native/docs/linking-libraries-ios.html).

**Comment by vgorte** [comment]
Thank you for your response @tafelito. I did as you recommended. I also had to work on my privacy settings in my info.plist file and ask for permission for accessing the gallery.  
This [site](http://useyourloaf.com/blog/privacy-settings-in-ios-10) helped me with that.

**Comment by kfiroo** [comment]
@vgorte @tafelito a PR for the required changes to the example project would be great :)

**Comment by vgorte** [comment]
@kfiroo will do once I get home

**Comment by tafelito** [comment]
@vgorte Yes you have to do that for iOS 10 if you build for release or run it on the phone. But I think that shouldn't be included in this project, that apply to every iOS project. So I guess no PR be needed.

**Comment by vgorte** [comment]
@tafelito But the example is not working correctly. The "choose from Library" feature is not working and is causing the example to crash.

**Comment by tafelito** [comment]
@vgorte So I guess that if @kfiroo agrees he might wants to add it

**Comment by kfiroo** [comment]
I think we should keep the example working out of the box all the time, this is the entry point for new users of this project and it should be as frictionless as possible.

**Comment by tafelito** [comment]
Yes I agreee. So a mention in the readme would be good too then, so if someone use the example then they know they have to change that later on. I mean change the description
