### ISSUE TITLE
Cannot toggle accessory bar

### ISSUE THREAD

**Issue by viettranme** [FaridSafi/react-native-gifted-chat#341]
#### Issue Description

I'm using 'react-native-gifted-chat' to make a custom chat view. There's an action button to toggle the accessory bar below the message composer. 

When I click on that button, the accessory bar content is toggled, but the height of the input bar is not collapsed/expanded accordingly (its height always equals 88)

#### Steps to Reproduce / Code Snippets

The code is briefly as following:

```
    this.state = {
      ...
      showAccessory: false,
    };

  onPressActionButtonAccessory = () => {
    this.setState({showAccessory: !this.state.showAccessory});
  }

  renderAccessory(props) {
    if (!this.state.showAccessory) {
      return null;  
    }
    
    return (
      <View>
        <Text>
          Accessory bar content
        </Text>
      </View>
    );
  }

...
  render() {
    return (
      <GiftedChat
        ....
        renderAccessory={this.renderAccessory}         
        ....
      />
    );
  } 

```

I have checked the code of GiftedChat.js and saw the following function:

```
  getMinInputToolbarHeight() {
    if (this.props.renderAccessory) {
      return MIN_INPUT_TOOLBAR_HEIGHT * 2;
    }
    return MIN_INPUT_TOOLBAR_HEIGHT;
  }
```

I have changed it to:

```
  getMinInputToolbarHeight() {
    if (this.props.renderAccessory && this.props.renderAccessory() !== null) {
      return MIN_INPUT_TOOLBAR_HEIGHT * 2;
    }
    return MIN_INPUT_TOOLBAR_HEIGHT;
  }
```
and run 'react-native run-android' again, but now the accessory bar is not shown anymore.

I also tried with the following option but it still doesn't work:

```
 <GiftedChat
        ....
        renderAccessory={this.state.showAccessory? this.renderAccessory : null}         
        ....
      />
```

#### Expected Results

Should be able to toggle the accessory bar, and the input bar (which includes composer bar + accessory bar) should expand/collapse its height accordingly.

#### Additional Information

* React Native version: 0.40
* react-native-gifted-chat version: 0.0.10
* Platform(s) (iOS, Android, or both?): Android

**Comment by fants** [comment]
edit GiftedChat.js



## **1. add propTypes and add**

`minInputToolbarHeight:React.PropTypes.number,`

## **2. add defaultProps**

`  minInputToolbarHeight:44,`

## **3. edit "getMinInputToolbarHeight()"**

```
  getMinInputToolbarHeight() {
    if (this.props.renderAccessory) {
      return this.props.minInputToolbarHeight * 2;
    }
    return this.props.minInputToolbarHeight;
  }
```

## **4. edit componentWillReceiveProps**

```
  componentWillReceiveProps(nextProps = {}) {
    this.initMessages(nextProps.messages);

    //new
    if(this.props.minInputToolbarHeight !== nextProps.minInputToolbarHeight) {
        let inputToolbarHeight = this.state.composerHeight + (nextProps.minInputToolbarHeight - MIN_COMPOSER_HEIGHT);

        const newMessagesContainerHeight = this.getMaxHeight() - inputToolbarHeight - this.getKeyboardHeight() + this.getBottomOffset();
        this.setState({
            messagesContainerHeight: this.prepareMessagesContainerHeight(newMessagesContainerHeight),
        });
    }
  }
```

now, you can use it as GiftedChat's props

```
<GiftedChat
    renderInputToolbar={this.renderInputToolbar.bind(this)}
    renderAccessory={this.renderAccessory.bind(this)} 
    minInputToolbarHeight={this.state.minInputToolbarHeight}
    user={{
         _id: 1,
}}
 />

```

```
self.setState({
     minInputToolbarHeight:this.state.isActionPanelOpen ? 200, 44
})
```

**Comment by kfiroo** [comment]
If you think this is useful for other people consider creating a PR for this :)

**Comment by grin** [comment]
That was useful for me. There was a similar PR merged recently: https://github.com/FaridSafi/react-native-gifted-chat/pull/386 but it misses the 4th step from @fants changes...

**Comment by kfiroo** [comment]
@grin Hey, good catch! 
Want to create a quick PR for that? :)

**Comment by peteroid** [comment]
I created a PR #498 for this issue according to the step 4 of @fants.

**Comment by fukemy** [comment]
hi, any update using hook?

**Comment by fukemy** [comment]
i didnt finy anything related to componentWillReceiveProps function inside GiftedChat.js. Can anyone help me?
