### ISSUE TITLE
Set static resource for image in chat 

### ISSUE THREAD

**Issue by plkt1792** [FaridSafi/react-native-gifted-chat#342]
#### Issue Description
I need to set a static resource from my assets in chat message image. Currently only the uri can get set and there is no way to use require method in source. Please suggest something. 

* React Native version: 0.38.0
* react-native-gifted-chat version: ^0.0.10
* Platform(s) (iOS, Android, or both?): Android

**Comment by kfiroo** [comment]
@plkt1792 You can override almost any inner component in `gifted-chat`.
Which images are you trying to set?

**Comment by plkt1792** [comment]
@kfiroo 

https://github.com/FaridSafi/react-native-gifted-chat/blob/9d7ca0bcff1d821590b74e89d3279593632f6927/src/MessageImage.js

`
 <Image
     {...this.props.imageProps}
     style={[styles.image, this.props.imageStyle]} 
     source={{uri: this.props.currentMessage.image}}/>
`

**Comment by kfiroo** [comment]
You could try use `renderBubble` / `renderMessage` / `renderMessageImage` or whatever works for you.
Take a look at the example to see how it used `renderCustomView`

**Comment by kelvinaliyanto** [comment]
@kfiroo I have similar issues with this, following your suggestion to use custom renderMessageImage in my GiftedChat, I add `renderMessageImage(props) {
    return (
      <MessageImage
        style={styles.image}
        source={require(props.currentMessage.image)}
      />
    )
  }`

The message object's image prop is './assets/01.gif'. So it should actually take the image from assets folder under the root folder. But it always throw me the error "Unknown named module: ". Meaning the require cannot find my image. Please suggest on what is causing the error.

**Comment by kfiroo** [comment]
@kelvinaliyanto sounds like an import issue, did you import `MessageImage` from `react-native-gifted-chat`?
Also, it's usually a good idea to pass the props to the component, i.e.
```jsx
renderMessageImage(props) {
    return (
      <MessageImage
        {...props} // <-- this
        style={styles.image}
        source={require(props.currentMessage.image)}
      />
    )
  }
```

**Comment by kelvinaliyanto** [comment]
@kfiroo I have imported the MessageImage from react-native-gifted-chat. The unknown named module is actually referring to the image prop, './assets/01.gif', not the module of MessageImage. Anyway thanks for the feedback for passing the props to the component.

**Comment by plkt1792** [comment]
@kelvinaliyanto Is the path to your asset file is correct? Also, what is your react-native version?

**Comment by kelvinaliyanto** [comment]
@plkt1792 currently RN 0.40. Yes it is correct, as I tried to render the image in the same component, but not in MessageImage component and it does show the image. But when I try to require it inside MessageImage component, it throws the error "Unknown named module: './assets/01.gif'".

**Comment by plkt1792** [comment]
Try directly putting the resource in source as -
```
renderMessageImage(props) {
    return (
      <MessageImage
        style={styles.image}
        source={require('./assets/01.gif')}
      />
    )
  }
```
If this works then you need to pass source as  - ``source={props.currentMessage.image}`` and set image as - ``image: require('./assets/01.gif')``

Also refer to the release notes - 
https://github.com/facebook/react-native/releases?after=v0.41.0-rc.0
It says that ``require('image!...') no longer supported.``

**Comment by kelvinaliyanto** [comment]
@plkt1792 even by putting it directly in resource it still give the unknown named module. Does it work in your copy?

**Comment by plkt1792** [comment]
My case was different. I had to make CustomMessageImage because I needed some other functionalities. But it worked.

Try versioning down react-native from 0.40 to 0.38.

**Comment by kfiroo** [comment]
@kelvinaliyanto In your code snippet I see you render `MessageImage` with `source` prop.
This prop is completely ignored by `MessageImage` as you can see here: https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/MessageImage.js#L25

I don't think rendering static images is supported like this, you would need to return your own implementation of `MessageImage` and render an `Image` with your source
