### ISSUE TITLE
Message Bubble twice full screen

### ISSUE THREAD

**Issue by macasas** [FaridSafi/react-native-gifted-chat#344]
#### Issue Description

Apologies if this is already listed here but I cannot find it.  Just had a few days of module hell and ended up with a new project, originally from gifted-chat example, so now have react-native=0.40.0 

Installing via npm install --save react-native-gifted-chat

#### Steps to Reproduce / Code Snippets

Run the app in ios simulator

#### Expected Results
Message Bubble received is twice as high as screen.
When I enter a new message, the grey message disappears and new blue bubble is twice as high as screen.

This is what I had before the upgrade. Nice!
![simulator screen shot 18 jan 2017 20 18 35](https://cloud.githubusercontent.com/assets/910082/22173785/cb19ae80-dfc4-11e6-84e9-3631ad64ac84.png)

This is what I get on starting simulator now.
![screen shot 2017-01-21 at 10 26 23](https://cloud.githubusercontent.com/assets/910082/22173788/e9dcf534-dfc4-11e6-972c-c54dcadc6fff.png)

This is after adding a new message. Scrolling up the grey message has gone.
![screen shot 2017-01-21 at 10 26 43](https://cloud.githubusercontent.com/assets/910082/22173793/feb7879e-dfc4-11e6-95a5-29b62288815a.png)

#### Additional Information

* React Native version: 0.40.0
* react-native-gifted-chat version:0.0.10
* Platform(s) (iOS, Android, or both?): iOS

**Comment by itinance** [comment]
This PR seems to fix it: https://github.com/FaridSafi/react-native-gifted-chat/pull/322
Just remove the flex: 1 in bubble-styles as long as this PR isn't merged.

**Comment by macasas** [comment]
Thanks, I also realised this was caused by me adding a renderCustomView and I was working my way towards the styles, but you saved me the trouble, much appreciated!
