### ISSUE TITLE
keyboardShouldPersistTaps={true/false} is deprecated

### ISSUE THREAD

**Issue by Maxwell2022** [FaridSafi/react-native-gifted-chat#345]
#### Issue Description

![image](https://cloud.githubusercontent.com/assets/670701/22187755/15a06344-e160-11e6-965b-aaa0c2e41cab.png)

#### Steps to Reproduce / Code Snippets

Load a basic app with GiftedChat and react-native `0.40+`

#### Expected Results

no warning

#### Additional Information

* React Native version: ^0.40.0
* react-native-gifted-chat version: ^0.0.10
* Platform(s) (iOS, Android, or both?): iOS

**Comment by kfiroo** [comment]
@Maxwell2022 @mjsolidarios 
React Native introduced some changes with v0.40.0 and we still haven't deployed a version that supports that to npm.
You shouldn't worry, RN is backwards compatible and this is only a warning that will not show on production

**Comment by Maxwell2022** [comment]
fixed in `0.1.0`
