### ISSUE TITLE
[Question] ListView jumps while reading old messages

### ISSUE THREAD

**Issue by bennygenel** [FaridSafi/react-native-gifted-chat#346]
#### Issue Description

While reading old messages if a new message appends, messages list jumps up which makes reading messages hard in fast growing chats.

#### Expected Results

New messages should make ListView grow downwards instead of pushing messages upwards while scrollview is not at the end.

#### Additional Information

Does anybody have any suggestions to achieve this functionality?

* React Native version: 0.40
* react-native-gifted-chat version: 0.0.10
* Platform: iOS

**Comment by kfiroo** [comment]
@bennygenel How does `whatsapp` / `messenger` handles this?

I think this is the desired behaviour:
When the scroll is 0 - at the bottom - the new messages push the chat - the scroll stays 0.
When the scroll is not 0 - user scrolled up - the user's view should not change when new messages arrive.

PRs / suggestions are welcome! :)

**Comment by bennygenel** [comment]
@kfiroo whatsapp does a half message line bump regardless of the new message height. I think its just for notifying user for new message arrival.

After your suggestion I did try couple of things but so far nothing really usable in production.
What I understood so far is that inverted scrollview converts listview start position to the bottom of view and when a new row appends to the list, makes the list grow upwards. ScrollView stores its offset and stays at the same offset but the messages which were in view are not at the same offset. So I added onLayout prop to the Message component and get the height of new message. Then stored current offset in state. If offset in state is greater than 0 I scrolledTo current offset + the height of new message.

Because I scroll after the layout complete, messages bumps up and then scrolls back. This causes a flicker and sometimes makes scroll to jump around.

Do you have any suggestions on what to do next?

```
   onListViewScroll(event) {
        let nativeoffsetY = event.nativeEvent.contentOffset.y;
        this.setState({
            scrolled: nativeoffsetY > 0,
            contentOffset: nativeoffsetY,
        });
    }

    onMessageLayout(event) {
        let _nativeEvent = event.nativeEvent;
        if (this.state.scrolled) {
            this._listView.scrollTo({
                 x: 0,
                 y: (this.state.contentOffset + _nativeEvent.layout.height),
                 animated: true
             });
        }
    }

    render() { 
        return (
            <GiftedChat
                messages={this.state.messages}
                onSend={this.onSend}
                user={{_id: 1,}}
                listViewProps={{
                    onScroll:this.onListViewScroll.bind(this),
                    ref:(ref)=>{this._listView = ref},
                }}
                onMessageLayout={this.onMessageLayout.bind(this)}
            />
        )
    }

```

```
    // react-native-gifted-chat/src/Message.js

    render() {
        return (
            <View onLayout={this.props.onMessageLayout.bind(this)} style={this.props.messageContainerStyle}>
                {this.renderDay()}
                <View style={[styles[this.props.position].container, {
          marginBottom: isSameUser(this.props.currentMessage, this.props.nextMessage) ? 2 : 2,
        }, this.props.containerStyle[this.props.position]]}>
                    {this.props.position === 'left' ? this.renderAvatar() : null}
                    {this.renderBubble()}
                    {this.props.position === 'right' ? this.renderAvatar() : null}
                </View>
            </View>
        );
    }
```

**Comment by kfiroo** [comment]
@bennygenel That's exactly what I was worried about.. We can't determine the height of a message until after it has been rendered.
We can look to the `inverted-list-view` as a normal list view where we **prepend** items, and would encounter the same issue.
I'm afraid I can't think of any solution off the top of my head.. :(

**Comment by bennygenel** [comment]
I tried to do that either. This time same issue occurs when loading more
older messages.

I am not experienced on native apps but do you think there could be any
solution with doing some native coding?
