### ISSUE TITLE
How to recover the image objet from a message ?

### ISSUE THREAD

**Issue by Balderious** [FaridSafi/react-native-gifted-chat#347]
#### Issue Description

I send a image message and i recover this: 
message=  
Object
   _id: "temp-id-885574"
   createdAt: Tue Jan 24 2017 16:40:41 GMT+0100 (Paris, Madrid)
   **image:"content://media/external/images/media/11271"**
   user: Object

**I need to recover a image objet to save it in firebase. How to recover it ?**

**Comment by Frexuz** [comment]
I wanna know too! :)
