### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by jjdp** [FaridSafi/react-native-gifted-chat#348]
Version bump to reflect changes? currently when i npm install. it still uses old files.
so RN 0.4.0 is giving the warning `keyboardShouldPersistTaps={true}` an error, even when setting it in the gifted chat props

**Comment by kfiroo** [comment]
@jjdp a new version will be released to npm soon.
If you need the latest code you could use `master`

In you `package.json`:
`"react-native-gifted-chat": "git+https://github.com/FaridSafi/react-native-gifted-chat.git#<latest commit hash>"`
