### ISSUE TITLE
 Top margin

### ISSUE THREAD

**Issue by vgorte** [FaridSafi/react-native-gifted-chat#349]
Hey guys, 
I was wondering, where can I change the top margin of the app to not overlap with the time/batterie bar? I basically don't want my messages to slide behind the top bar. Would that be the case on a real device? And is there a way to change that?
![simulator screen shot 26 01 2017 00 10 32](https://cloud.githubusercontent.com/assets/17333517/22313222/f5b9782e-e35b-11e6-8d4b-7fb5693b72e9.png)

Thanks in advance!

**Comment by kfiroo** [comment]
@vgorte Hey,
This is not related to `gifted-chat`, you just need to add a view with the status-bar height at the top of your app
