### ISSUE TITLE
Can we render a link in the messages

### ISSUE THREAD

**Issue by Jaafar-abusair** [FaridSafi/react-native-gifted-chat#352]
#### Issue Description

Can we render a link that invoking a local method in js?

#### Additional Information

* React Native version: 0.39.0
* react-native-gifted-chat version: last version
* Platform(s) (iOS, Android, or both?): both

**Comment by kfiroo** [comment]
@Jaafar-abusair take a look at `renderMessageText` prop

**Comment by duyphambhtech** [comment]
Hi @kfiroo , @Jaafar-abusair do you have any example of using renderMessageText ? :D
