### ISSUE TITLE
keyboardShouldPersistTaps={false} doesn't work RN 0.39.2 / package 0.0.10

### ISSUE THREAD

**Issue by balibou** [FaridSafi/react-native-gifted-chat#353]
#### Issue Description

When I implement keyboardShouldPersistTaps={false} in the simple example, it doesn't work.

#### Steps to Reproduce / Code Snippets

Just copy the simple example and add `keyboardShouldPersistTaps={false}` like:
```
constructor(props) {
    super(props);
    this.state = {messages: []};
    this.onSend = this.onSend.bind(this);
  }
  componentWillMount() {
    this.setState({
      messages: [
        {
          _id: 1,
          text: 'Hello developer',
          createdAt: new Date(Date.UTC(2016, 7, 30, 17, 20, 0)),
          user: {
            _id: 2,
            name: 'React Native',
            avatar: 'https://facebook.github.io/react/img/logo_og.png',
          },
        },
      ],
    });
  }
  onSend(messages = []) {
    this.setState((previousState) => {
      return {
        messages: GiftedChat.append(previousState.messages, messages),
      };
    });
  }
  render() {
    return (
      <GiftedChat
        messages={this.state.messages}
        onSend={this.onSend}
        user={{
          _id: 1,
        }}
        keyboardShouldPersistTaps={false}
      />
    );
  }
```
#### Expected Results

When clicking outside the input (double click I presume), the keyboard should disappear.

#### Additional Information

* React Native version: 0.39.2
* react-native-gifted-chat version: 0.0.10
* Platform(s) (iOS, Android, or both?): iOS

**Comment by kfiroo** [comment]
Hey @balibou, 
Unfortunately, v0.0.10 doesn't support this prop.
If you can upgrade to RN 0.40.0 I suggest you upgrade to v0.1.0

**Comment by balibou** [comment]
@kfiroo ok thanks for the feedback !
