### ISSUE TITLE
Change send label and Type a message placeholder

### ISSUE THREAD

**Issue by sabativi** [FaridSafi/react-native-gifted-chat#356]
#### Issue Description

How to change send label and Type a message placeholder.

I manage to do so by writing this : 

```
import { Send, Composer } from 'react-native-gifted-chat';

  renderComposer() {
    return <Composer placeholder={'My placeholder'} />;
  }

  renderSend() {
    return <Send label={'My send label'} />;
  }
```

But then when i type a message it is removed just after and the send button never appear...

#### Additional Information

* React Native version: 0.37
* react-native-gifted-chat version: latest
* Platform(s) (iOS, Android, or both?): BOTH

**Comment by luco** [comment]
+1 on this.

Also, my composer never shows anything that I input.

**Comment by kfiroo** [comment]
Hey,
All `renderXXX` methods receive `props` as the only parameter, you should pass that to the component you render.

See example https://github.com/FaridSafi/react-native-gifted-chat/blob/master/example/App.js#L156

**Comment by zengkm** [comment]
@kfiroo Thanks for your answer, I solved it.
I write renderComposer method like this:
`renderComposer(props){
    return (
      <Composer
        {...props}
         placeholder={'my placeholder'}
      />
    );
  }`
