### ISSUE TITLE
How do I get the text input value of the keyboard?

### ISSUE THREAD

**Issue by ghost** [FaridSafi/react-native-gifted-chat#359]
#### Issue Description

How do I access the gifted chat's text input once the keyboard comes up?

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* React Native version: 0.35.0
* react-native-gifted-chat version: 0.0.10
* Platform(s) (iOS, Android, or both?): Android

**Comment by mostafiz93** [comment]
You can find the textInput in `messages[0].text` in `onSend(messages = [])` method
