### ISSUE TITLE
Avatar not displaying

### ISSUE THREAD

**Issue by radvc** [FaridSafi/react-native-gifted-chat#361]
Hi, I change the default avatar url in the example this one
**https://facebook.github.io/react/img/logo_og.png** to this one **http://gazettereview.com/wp-content/uploads/2016/03/facebook-avatar.jpg**

but the new avatar is not displaying. Did i miss something?

**Comment by kfiroo** [comment]
I can see only `http` vs `https` maybe related?

**Comment by radvc** [comment]
@kfiroo thank you so much!

**Comment by trinadhkoya9** [comment]
I am sending suffix URL of the avatar in the user object, In order to see the whole image , I need to prefix my assets base path to my suffix . How to do this?
