### ISSUE TITLE
keyboardShouldPersistTaps  of type 'string'

### ISSUE THREAD

**Issue by radvc** [FaridSafi/react-native-gifted-chat#363]
Anyone here encouter this? The whole message is **keyboardShouldPersistTaps  of type `string` supplied to `InvertibleScrollView`, expected `boolean`**.

**Comment by kfiroo** [comment]
@radvc `react-native` changed the `keyboardShouldPersistTaps` prop from `boolean` to `enum/string` with v0.40.0
If you are using RN < 0.40.0 you should use `gifted-chat` 0.0.10

**Comment by radvc** [comment]
@kfiroo thanks!
