### ISSUE TITLE
How can I change chat text color. 

### ISSUE THREAD

**Issue by polodev** [FaridSafi/react-native-gifted-chat#364]
default text color is white. But I need black text. How can I make black color chat text

**Comment by alxmllr** [comment]
Add a textStyle property to your GiftedChat component:

`<GiftedChat 
   ...
   textStyle={{
								left: {
									color:'black',
								}
right: {
									color:'black',
								}
							}} />`

**Comment by alxmllr** [comment]
Add a renderBubble property to your GiftedChat component:

`
<GiftedChat
...
							renderBubble={this.renderBubble.bind(this)}
						/>
`

And implement renderBubble this way:

`renderBubble(props) {
		return (
			<Bubble
				{...props}
				textStyle={{
				right: {
					color: 'black',
				}
			}}
			/>
		);
	}`

**Comment by kaberibasu** [comment]
@alxmllr it gives warning Invalid props.right key `color` supplied to `Bubble`.

**Comment by davidsneal** [comment]
@alxmllr works for me, thanks!

**Comment by phillbaker** [comment]
And based on the comment by @MehdiAlouafi, if you want to do separate text styles for left/right, putting it all together:
```
renderBubble = props => (
    <Bubble
      {...props}
      wrapperStyle={{
        left: {
          backgroundColor: '#000',
        },
        right: {
          backgroundColor: '#fff',
        },
      }}
      textProps={{
        style: {
          color: props.position === 'left' ? '#fff' : '#000',
        },
      }}
      textStyle={{
        left: {
          color: '#fff',
        },
        right: {
          color: '#000',
        },
      }}
      style={styles.container}
    />
  )
```

**Comment by ashikhp** [comment]
> In my case the example above changed only the date text color.
> However, this, worked for me instead :
> 
> `textProps={{ style: { color: 'red' } }}`
> 
> Catched it here : https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/MessageText.js#L155

mariginleft not working
