### ISSUE TITLE
wrapperStyle used in LoadEarlier and Bubble

### ISSUE THREAD

**Issue by jeromegrosse** [FaridSafi/react-native-gifted-chat#365]
#### Issue Description

The prop `wrapperStyle` is both used in LoadEaerlier's `renderLoading` and Bubble's ` render.
This is a problem because once might want to modify one wrapperStyle but not the other.

#### Steps to Reproduce / Code Snippets

Pass a style with wrapperStyle and `loadEarlier={true}` to GiftedChat. It will affect both the bubbles of the messages and the loadEarlier's message. Those two wrapperStyle are incompatible since the Bubble objects expects a `left` and `right` within the styling but LoadEarlier doesn't.

#### Additional Information

* React Native version: 0.39.2
* react-native-gifted-chat version: 0.0.9
* Platform(s) (iOS, Android, or both?): both

**Comment by kfiroo** [comment]
@jeromegrosse You could use `renderLoadEarlier` and provide it with the desired props

**Comment by jeromegrosse** [comment]
@kfiroo I totally could indeed. However, I am not really sure that having a props modifying more than one thing is semantically correct. If I pass a prop that modifies a component style, I should have to worry whether another a component uses the same prop name.

Anyways, I am not totally sure how to implement what you suggested while keeping all the property that belong to `MessageContainer`.

Let's take for example (the imports and some methods are missing):
```javascript
class MessengerView extends React.Component {

    renderLoadEarlier() {
        return (
          <LoadEarlier {...loadEarlierProps}/>
        );
    }

    render() {
        return (
            <GiftedChat
                messages={this.state.messages}
                onSend={this.onSend}
                user={{_id: user.id}}
                renderLoading={this.renderLoading}
                loadEarlier={true}
                onLoadEarlier={() => this.onLoadEarlier}
                renderLoadEarlier={this.renderLoadEarlier}
            />
        );
    }
}
```

How can I get the MessageContainer's props (such as `isLoadingEarlier`, etc.) ?

**Comment by kfiroo** [comment]
@jeromegrosse You are 100% right!
This is legacy code that I really want to remove when I have some time so spare.
I strongly believe customizations for internal components should not be exposed on the root level component, it clutters the code and error-prone, as we see in the issue you describe.

**Comment by jeromegrosse** [comment]
Nice to know, thanks a lot for your answer! Please let me know if I can be of any help.

Do know how I can override `renderLoadEarlier`, use `LoadEarlier` and access the state of `MessageContainer` within that overriding method?

**Comment by kfiroo** [comment]
@jeromegrosse `GiftedChat` exposes `LoadEarlier` so you could use it in the `renderLoadEarlier` function, just don't forget to pass the props to the comp [see here](https://github.com/FaridSafi/react-native-gifted-chat/issues/356#issuecomment-277559631)

Why would you need to use your `MessageContainer` state? it is an internal component that should be out of scope for you code, the state should be help by the component that renders the `GiftedChat` if that makes any sense. :)
