### ISSUE TITLE
Rendering Custom Responses (Like a Bot)

### ISSUE THREAD

**Issue by indivisable** [FaridSafi/react-native-gifted-chat#367]
It would be a great feature to have this feature build into at library level, as this library could be used to create not just messenger apps but bot interfaces. Any ideas on a best practices for implementing such dynamic responses, with buttons and other basic input types?

![feb-08-2017 12-50-47](https://cloud.githubusercontent.com/assets/22860891/22752242/6c76b2c8-edfd-11e6-8138-0c7e1e9c5724.gif)

**Comment by kfiroo** [comment]
@indivisable Hey! This sounds like a great feature, but I think it's out of scope for this library.
We are trying to keep this project as simple as possible while providing developers with as much freedom and customizability as possible.

I think you should have all you need to implement this sort of behaviour on your on, but if you need any help feel free to ask here and I'm sure you'll get an answer :)

**Comment by indivisable** [comment]
@kfiroo could you give some ideas on how to start? Would you just override the message bubble renderer and inject buttons?

**Comment by kfiroo** [comment]
@indivisable I would start investigating the custom keyboard control I see in your gif.
This can be done outside the scope of `gifted-chat` you can start with an empty page with only a `TextInput` and when focusing it, render the custom keyboard control.
Then, you could use `gifted-chat` and render your custom-keyboard in the `renderComposer` method to get the chat to use it
