### ISSUE TITLE
Space between Text Input and Keyboard that I can't get rid of

### ISSUE THREAD

**Issue by davidfloegel** [FaridSafi/react-native-gifted-chat#368]
Hi,

I love the plugin but I somehow have a weird space between the TextInput and the Keyboard that I can not get rid of. I'm using react-native 0.39.2 (can't upgrade for some reason).

Have a look:
![interface](https://cloud.githubusercontent.com/assets/13220692/22781504/a3fd829a-eeba-11e6-9ef2-7a56b7a5a707.png)

#### Steps to Reproduce / Code Snippets
Just plug in the react-native gifted chat.

#### Additional Information

* React Native version: 0.39.2
* react-native-gifted-chat version: 0.0.10
* Platform(s) (iOS, Android, or both?): iOS (haven't tested android yet)

**Comment by qq573725206** [comment]
@davidfloegel  renderAccessory  Check whether the component is open?

**Comment by davidfloegel** [comment]
@qq573725206 I think I already tried that and also simply removed an empty View. But will try again later!

**Comment by kfiroo** [comment]
@davidfloegel try sharing some code, might help someone spot an issue

**Comment by davidfloegel** [comment]
@kfiroo 
That's all!
`
render( <View style={ { flex: 1 } }>
                <GiftedChat
                    messages={ shouts }
                    onSend={ this.onSend }
                  />
</View> )`

**Comment by davidfloegel** [comment]
Tried a couple of things now. Including upgrading to the latest RN version and latest version of this component.
I also tried to hack the component to see what's going on but no progress..

**Comment by indivisable** [comment]
Might be related: https://github.com/FaridSafi/react-native-gifted-chat/issues/219

**Comment by davidfloegel** [comment]
Yes fhat fixed it! Thanks :)

**Comment by yakirbu** [comment]
I have the same issue, and btw, can't see how #219 fixed it?

**Comment by davidfloegel** [comment]
@yakirbu did you try setting `bottomOffset` to the height of your tabbar?

**Comment by yakirbu** [comment]
Hi, it seems that the gifted-chat component was wrapped inside a view and that's what made the gap between the text input. 
Thanks.

**Comment by Tom29** [comment]
Have this error been fixed? I've tried many ways like setting `bottomOffset` = 0, but didn't work.
still see the gap after keyboard shown up.

**Comment by Clowning** [comment]
I've the same issue... :/

**Comment by Tom29** [comment]
@Clowning set bottomOffset != 0, you would see the difference.

**Comment by shukerullah** [comment]
I have same issue, setting bottomOffset to 0 did not work for me.

**Comment by simjoh** [comment]
For others arriving here bottomOffset should be equal to bottom TabBar. bottomOffset={48} worked for me on iPhone SE.

**Comment by nandiniparimi1107** [comment]
@simjoh but adding bottomOffset is applying the offset in iphone 7 as well.
Is there a way to apply the bottomOffset only in case of iphone X?

**Comment by phil-flyclops** [comment]
You can use the getBottomSpace function from this library and feed it into bottomOffset to get the correct spacing, it'll automatically account for iPhone X vs other phones https://github.com/ptelad/react-native-iphone-x-helper/

**Comment by MuhammadUmairMoosani** [comment]
<View style={ { flex: 1, marginBottom:8 } }> // add marginbottom
                <GiftedChat
                    messages={ shouts }
                    onSend={ this.onSend }
                  />
</View>

**Comment by santirodriguezaffonso** [comment]
It worked on my case
```
import { useSafeAreaInsets } from "react-native-safe-area-context";

function App() {
  const insets = useSafeAreaInsets();
  
  return (
    <GiftedChat
       // ...
       bottomOffset={insets.bottom}
    />
  )
}
```
