### ISSUE TITLE
[ANDROID]  Input display bug

### ISSUE THREAD

**Issue by Fantasim** [FaridSafi/react-native-gifted-chat#372]
Hi,

I'm trying to implement react-native-gifted-chat on my android app (I had already set up on the iOS version) but on android i get this bug : 

http://www.giphy.com/gifs/26xBzmEQj97yxBFio

How can i put input to the top of the keyboard ?

* React Native version: 0.40
* react-native-gifted-chat version: 0.1.3
* Platform(s) (iOS, Android, or both?): Android

**Comment by dgdavid** [comment]
Hi @Fantasim 

Did you follow the [Android Installation](https://github.com/FaridSafi/react-native-gifted-chat#android-installation) steps? Your bug is commonly related with `android:windowSoftInputMode="adjustResize"`. Ensure that you added it on `android/app/src/main/AndroidManifest.xml`.

**Comment by Fantasim** [comment]
Thanks i've put `android:windowSoftInputMode="adjustResize"` in application tag and not in activity tag.
