### ISSUE TITLE
How to show all messages on the left?

### ISSUE THREAD

**Issue by chatras** [FaridSafi/react-native-gifted-chat#373]
I need all the messages to be on the left and need to show everyones avatar. Is this possible without changing the library? 

Any help is much appreciated. 

Thanks :)

**Comment by kfiroo** [comment]
@chatras Hey, messages are rendered on the right only if the chat `user._id` prop is the same as the 'message.user._id'.
If you make sure they are always different all messages will be rendered on the left.

As for the avatars, that might be a bit trickier, take a look at `renderAvatar` or `renderMessage`
