### ISSUE TITLE
When will onSend have more then one message?

### ISSUE THREAD

**Issue by mxmtsk** [FaridSafi/react-native-gifted-chat#374]
Hi,

this is more of a question: I wanted to know under what circumstances the onSend-Method get's called with more than one message in the messages array parameter? Will this happen at all?

I'm currently just passing messages[0] to my API but I'm curious if I'm missing something or if that's just in place for a more advanced usage.

Thanks

**Comment by kfiroo** [comment]
@mxmtsk Hey, when the user wants to send multiple images at once, for example.

**Comment by yernandus** [comment]
@kfiroo, ya that is the case when the array is useful

**Comment by mxmtsk** [comment]
Thanks guys, makes sense :)
