### ISSUE TITLE
anyone tried to use this with pusher?

### ISSUE THREAD

**Issue by vesper8** [FaridSafi/react-native-gifted-chat#375]
I know and fully understand that the backend implementation is outside the scope of this project.

However truth be told anyone planning to use this also has to tackle the backend and some kind of realtime web socket solution. I'm personally planning to use this package with a laravel-driven rest api and would like to use pusher for my sockets and broadcasting.

Found a very nice example of using this with firebase here https://github.com/drmas/FireChat

And found this pusher package for react-native https://github.com/gijoehosaphat/react-native-realtime-pusher

Before I get started and try to take away from those two solutions to build my own I was wondering if anyone had any thoughts or experience on using this with pusher?

Any feedback is much appreciated! Thanks!

**Comment by kfiroo** [comment]
@vesper8 We're using `sendbird` as the chat service, `redux` as a client store and `gifted-chat` as the view.

[sendbird](https://sendbird.com) has a [javascript sdk](https://docs.sendbird.com/javascript) that works with react-native.

**Comment by parijatsahai** [comment]
@kfiroo Is an example for what you're using available on github? I suspect that's what @vesper8 is asking about for guidance.

**Comment by kfiroo** [comment]
Unfortunately, our code is not public :(
If you have any specific questions I'll be more then happy to help

**Comment by nonotest** [comment]
I am using this with Redux, and a rethinkdb-golang websocket implementation. works very nicely.

**Comment by radko93** [comment]
Not sure if someone is still interested, but I made it working smoothly using Pusher. I've used `redux-pusher`, simple configuration.

**Comment by vesper8** [comment]
@radko93 nice to hear and encouraging for sure!

don't suppose you have some code we could look at somewhere? would be much appreciated :)

**Comment by radko93** [comment]
@vesper8 `redux-pusher` is straightforward, you just need to handle actions that it sends to your reducer and you're good to go. Then display the data using `react-native-gifted-chat`.
