### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by tjsaini007** [FaridSafi/react-native-gifted-chat#379]
When I am using this module in command prompt it is giving me error  "Git Not Found error"

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

**Comment by kfiroo** [comment]
This is not related to this project, probably something with your setup.

If you give us more details we might be able to help you

**Comment by devjaw** [comment]
same here !

**Comment by devjaw** [comment]
finally

you have to install git : https://git-scm.com/download/win
