### ISSUE TITLE
Image options should support ImageSourcePropType

### ISSUE THREAD

**Issue by iclems** [FaridSafi/react-native-gifted-chat#381]
Currently, images in options are expected to be URL strings. Ideally, this should be either a string (for backward compatibility) or a source ImageSourcePropType object which enables to pass local images, manage cache, etc.

**Comment by kfiroo** [comment]
Hey @iclems PRs are welcome :)

**Comment by xstable** [comment]
I'd like to add an Icon if a message in a chat is a file (pdf, audio, video).
Would love if "image"-property would be able to handle local images.
