### ISSUE TITLE
Error when using with react-native-web

### ISSUE THREAD

**Issue by karaxuna** [FaridSafi/react-native-gifted-chat#383]
#### Issue Description

Throws error when using with [react-native-web](https://github.com/necolas/react-native-web):

    Error: Cannot find module "./ActionSheet"

#### Additional Information

* React Native version: 0.33.0
* react-native-gifted-chat version: 0.1.3
* Platform(s) (iOS, Android, or both?): web

**Comment by kfiroo** [comment]
@karaxuna is this related to this project?

**Comment by abrichr** [comment]
Solved by adding this to `webpack.config.js`:
```
    resolve: {
        alias: {
            "react-native": "react-native-web",
            "./ActionSheet": "./ActionSheet.ios.js"
        },  
    },
```

**Comment by slorber** [comment]
@abrichr does it mean you successfully run this project on the web platform thanks to react-native-web ?

As I'm exploring using this chat lib as a replacement of Intercom, I wonder if I can build the "intercom chat admin" with it.

If this project is compatible with react-native-web with just a little bit of conf it would be nice to add this to README

**Comment by xcarpentier** [comment]
@slorber are you using GC? ;)

**Comment by slorber** [comment]
Only with you :)
It was actually simpler to eject instead of reimplementing intercom UI on web+rn for my project
