### ISSUE TITLE
Gifted-chat doesn't work when messages subscribe on props

### ISSUE THREAD

**Issue by sainath13** [FaridSafi/react-native-gifted-chat#384]
#### Issue Description

Gifted chat works perfectly fine when messages are subscribed to state changes like
`          <GiftedChat
            messages={this.state.messages}
            onSend={this.handleSend}
            user={{
              _id: 1,
            }}
          />
`
but when I subscribe it to props like
`          <GiftedChat
            messages={this.props.messagesOBJ[1]}
            onSend={this.handleSend}
            user={{
              _id: 1,
            }}
          />
`
It works for retrieving messages already in messagesOBJ[1], gives warnings if anything in wrong in messagesOBJ[1]'s new messages, but if everything is alright, then it just doesn't render the new messages.
#### Steps to Reproduce / Code Snippets

1. Create a redux state for storing messages
2. write server implementation for sending and receiving messages.
3. Subscrive to the redux state in Gifted-chat 
4. send a new message from giftedchat to server (state updates and we recieve message on server)
5. send a new message from server to mobile device (state updates that is we recieve message on mobile)
in step 4 and 5 , new messages are not rendered 
#### Expected Results
new messages should be rendered

#### Additional Information

* React Native version: [ "0.39.2"]
* react-native-gifted-chat version: ["react-native-gifted-chat": "0.0.10"]
* Platform(s) (iOS, Android, or both?): [ios only tested.]

**Comment by kfiroo** [comment]
@sainath13 Hey
You are passing your messages array as a reference to `GiftedChat`, the implementation doesn't care if it is on the `props` or `state`.
The problem is probably with your component lifecycle.

You can try to post some code and we may be able to help

**Comment by sainath13** [comment]
closing this issue. achieved the functionality using states.

**Comment by hahahatrick** [comment]
Facing the same issue, unable to figure out where the problem is.

**Comment by sainath13** [comment]
from the looks of it previousMessage is empty object having no message id.
