### ISSUE TITLE
How to show the message ticks symbol?

### ISSUE THREAD

**Issue by herpiko** [FaridSafi/react-native-gifted-chat#390]
#### Issue Description

I need to update the ticks symbol that represent wether the message has been sent / has been read by the opponent.

#### Steps to Reproduce / Code Snippets

According to the source code,  there is a function to render tick symbol after time string on message bubble. then I try to add `sent` and `received`, both as true (snippet from README.md)

```
{
  _id: 1,
  text: 'My message',
  createdAt: new Date(Date.UTC(2016, 5, 11, 17, 20, 0)),
  user: {
    _id: 2,
    name: 'React Native',
    avatar: 'https://facebook.github.io/react/img/logo_og.png',
  },
  image: 'https://facebook.github.io/react/img/logo_og.png',
  // additional custom parameters
  sent : true,
  received : true,
}
```

#### Expected Results

The ticks symbol didn't show up.

#### Additional Information

* React Native version: 0.41.2
* react-native-gifted-chat version: 0.1.3
* Platform(s) (iOS, Android, or both?): Android 6.x

**Comment by kfiroo** [comment]
@jeromegrosse can you assist here?

**Comment by jeromegrosse** [comment]
So, I've tried the example project and the ticks appeared.
Out of curiosity, are you expecting to see ticks on sent messages or on received messages? I tried your snippet, and the message appeared on the left side (a received message).

I updated your snippet (pasted below) and it worked for me (i.e. The received message had both the sent and received tick):
```
module.exports = [
  {
    _id: 1,
    text: 'My received message',
    createdAt: new Date(Date.UTC(2016, 5, 11, 17, 20, 0)),
    user: {
      _id: 2,
      name: 'React Native',
      avatar: 'https://facebook.github.io/react/img/logo_og.png',
    },
    image: 'https://facebook.github.io/react/img/logo_og.png',
    // additional custom parameters
    sent : true,
    received : true,
  },
  {
    _id: 2,
    text: 'My sent message',
    createdAt: new Date(Date.UTC(2016, 5, 11, 17, 21, 0)),
    user: {
      _id: 1,
      name: 'React Native',
      avatar: 'https://facebook.github.io/react/img/logo_og.png',
    },
    image: 'https://facebook.github.io/react/img/logo_og.png',
    // additional custom parameters
    sent : true,
    received : true,
  }
];
```

**Comment by herpiko** [comment]
I just tried the example project and the thicks appeared as well. Then there is something within my code, I'll find it. Thank you for your answer @jeromegrosse.

**Comment by mafiusu** [comment]
I also added a sent and received to the message object but no message ticks symbol are showing up. I've also tried with the preset messages like @jeromegrosse but no message ticks are appearing.

**Comment by SamiChab** [comment]
Same for me here... Any idea on how to solve this?

**Comment by rabindrachhachan** [comment]
Hi , how to change the color for ticks mark. I have seen there is props tickStyle in renderTicks method, but I am not able to figured out how to pass . I tried to add tickStyle in render bubble but it didn't work. Any suggestions will be helpful.

**Comment by leonyhenn** [comment]
I just found an easy fix. Fork this repo, and in GiftedChat.js, instead of using this._messages and this.getMessages() to update messages to MessageContainer, you set a state (like this.state_messages) and call setState in componentDidMount(and comment out this.setMessages())

the bug of tick not rerendering on receive is due to this._messages and this.getMessages() do not rerender the GiftedChat component, but setState does the job.

**Comment by RayyanNafees** [comment]
@leonyhenn 
> 
> I just found an easy fix. Fork this repo, and in GiftedChat.js, instead of using this._messages and this.getMessages() to update messages to MessageContainer, you set a state (like this.state_messages) and call setState in componentDidMount(and comment out this.setMessages())
> 
> the bug of tick not rerendering on receive is due to this._messages and this.getMessages() do not rerender the GiftedChat component, but setState does the job.

There is no this._messages in the package as i see, can u plz provide the link to the repository where u applied this fix ?
