### ISSUE TITLE
How to render custom view below message body?

### ISSUE THREAD

**Issue by dfischer** [FaridSafi/react-native-gifted-chat#391]
#### Issue Description

I want to insert custom views based on the message props on the bottom of the message. if I use a custom view, it renders on top of the message body inside the bubble. Is there a way to get it to pin to the bottom of the message instead?

I tried to use "order" but apparently that's not available in react native as a flex box directive.

<img width="260" alt="screen shot 2017-03-07 at 12 08 52 am" src="https://cloud.githubusercontent.com/assets/2424/23647354/456427d8-02ca-11e7-848d-4e47318a6176.png">

I want `is interactable...` at the bottom of the bubble instead of the top.

#### Steps to Reproduce / Code Snippets

1. Use the renderCustomView as a prop
2. Render a simple `<Text>` element

#### Expected Results

Instead of "is interactable..." at the top of the bubble, put it at the bottom.

#### Additional Information

* React Native version: 0.42.0
* react-native-gifted-chat version: 0.1.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by kfiroo** [comment]
@dfischer Hey,
There isn't a dedicated prop for that right now, you can create a PR for it if you like :)

Otherwise you could use `renderMessageText` to render a custom view with `MessageText` and your custom footer

**Comment by vidhyalakshmirbt** [comment]
@dfischer  you can go to Render() of Bubble.js and change the order of rendercustomview() method.
You can call the rendercustomview method after render time if you need it in bottom.

**Comment by dfischer** [comment]
Thanks
