### ISSUE TITLE
Programmatically setFocus to textInput using ref

### ISSUE THREAD

**Issue by rengasahusoft** [FaridSafi/react-native-gifted-chat#393]
I use RN 0.41
And Latest gifted chat

I want to focus textInput programmatically using `ref`. is it possible ? How can i do it ?

**Comment by pewh** [comment]
Hello,
I have same issue with you, and would you mind to post the solution? Thanks

**Comment by shimatai** [comment]
I need to append a text to default Composer (TextInput). Anyone got a solution?

**Comment by renganatha10** [comment]
Usage Of ref as `ref={c => this.textinput = c}` instead of `ref={this.textinput}` solved the the issue !

**Comment by hnrqsss** [comment]
> Usage Of ref as `ref={c => this.textinput = c}` instead of `ref={this.textinput}` solved the the issue !

Where you put his in giftedchat?
