### ISSUE TITLE
Compatibility with RN < 40.0

### ISSUE THREAD

**Issue by Jeanmsilva89** [FaridSafi/react-native-gifted-chat#394]
#### Issue Description

I'm still working on a RN project that is on 0.35.0. I've tested this project on that version and the only issue I've noticed and was able to resolve was the property **keyboardShouldPersistTaps** where it needs to be a boolean only and not a enum or string. 

I was wondering if there are any other known compatibility issues known to the community that I may be missing? 

* React Native version: 0.35.0
* react-native-gifted-chat version: 0.1.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by booboothefool** [comment]
Also wondering the same thing. 

I'm running the latest version of this lib 0.1.3 on RN 0.37 and it seems to be working great as far as I can tell...

**Comment by kfiroo** [comment]
@Jeanmsilva89 @booboothefool Hey, as the [docs](https://github.com/FaridSafi/react-native-gifted-chat#dependency) say, use `0.0.10` for RN < 40
