### ISSUE TITLE
undefined is not an object(evaluating '_Backend.Backend.getUid')

### ISSUE THREAD

**Issue by zohaibkathwari** [FaridSafi/react-native-gifted-chat#395]
i'm getting this 'undefined is not an object(evaluating '_Backend.Backend.getUid')'

This is my Chat.js file:

```jsx
import React, {Component} from 'react';

import {GiftedChat} from 'react-native-gifted-chat';
import {Backend} from '../Backend'

export class Chat extends React.Component {
    state = {
          messages: []
    }

    componentWillMount () {
        alert(Backend);
    }

    render () {
        return (
            <GiftedChat
                messages={this.state.messages}
                onSend={(message) => {
                    //send message to backend
                    Backend.sendMessage(message);
                }}
                user={{
                    _id: Backend.getUid(),
                    name: this.props.name,
                }}
            />
        );
    }

    componentDidMount () {
        Backend.loadMessages((message) => {
                this.setState((previousState) => {
                    return {
                        messages: GiftedChat.append(previousState.messages, message),
                    };
                });
        });
    }

    componentWillUnmount () {
        Backend.closeChat();
    }
}

Chat.defaultProps = {
    name: 'Anonymous',
};

Chat.propTypes = {
    name: React.PropTypes.string,
};
```

[FILL THIS OUT]

undefined is not an object (evaluating '_Backend.Backend.getUid')
render
    C:\PROJECTS\ReactNative\chatter\src\components\Chat.js:24:33
<unknown>
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:1045:14
measureLifeCyclePerf
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:85:11
_renderValidatedComponentWithoutOwnerOrContext
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:1045:8
_renderValidatedComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:1075:10
performInitialMount
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:484:24
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
mountChildren
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactMultiChild.js:264:10
initializeChildren
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\native\ReactNativeBaseComponent.js:74:41
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\native\ReactNativeBaseComponent.js:212:6
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
mountChildren
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactMultiChild.js:264:10
initializeChildren
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\native\ReactNativeBaseComponent.js:74:41
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\native\ReactNativeBaseComponent.js:212:6
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
updateChildren
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactChildReconciler.js:157:10
_reconcilerUpdateChildren
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactMultiChild.js:212:10
_updateChildren
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactMultiChild.js:345:6
updateChildren
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactMultiChild.js:331:25
receiveComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\native\ReactNativeBaseComponent.js:130:24
receiveComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:163:38
_updateRenderedComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:982:8
_performComponentUpdate
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:944:34
updateComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:847:8
receiveComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:710:6
receiveComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:163:38
updateChildren
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactChildReconciler.js:143:10
_reconcilerUpdateChildren
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactMultiChild.js:212:10
_updateChildren
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactMultiChild.js:345:6
updateChildren
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactMultiChild.js:331:25
receiveComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\native\ReactNativeBaseComponent.js:130:24
receiveComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:163:38
_updateRenderedComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:982:8
_performComponentUpdate
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:944:34
updateComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:847:8
receiveComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:710:6
receiveComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:163:38
_updateRenderedComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:982:8
_performComponentUpdate
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:944:34
updateComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:847:8
receiveComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:710:6
receiveComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:163:38
_updateRenderedComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:982:8
_performComponentUpdate
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:944:34
updateComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:847:8
receiveComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:710:6
receiveComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:163:38
_updateRenderedComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:982:8
_performComponentUpdate
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:944:34
updateComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:847:8
receiveComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:710:6
receiveComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:163:38
_updateRenderedComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:982:8
_performComponentUpdate
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:944:34
updateComponent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:847:8
performUpdateIfNecessary
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:735:8
performUpdateIfNecessary
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:213:46
runBatchedUpdates
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactUpdates.js:171:6
perform
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\utils\Transaction.js:149:24
perform
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\utils\Transaction.js:149:24
perform
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactUpdates.js:96:8
flushBatchedUpdates
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactUpdates.js:199:26
closeAll
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\utils\Transaction.js:222:29
perform
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\utils\Transaction.js:163:24
batchedUpdates
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactDefaultBatchingStrategy.js:65:33
batchedUpdates
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactUpdates.js:111:41
_receiveRootNodeIDEvent
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\native\ReactNativeEventEmitter.js:126:32
receiveTouches
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\Renderer\src\renderers\native\ReactNativeEventEmitter.js:213:8
__callFunction
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:242:47
<unknown>
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:108:26
guard
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:46:4
callFunctionReturnFlushedQueue
    C:\PROJECTS\ReactNative\chatter\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:107:10

[FILL THIS OUT]

#### Additional Information

* React Native version: 0.42.0
* react-native-gifted-chat version: 0.1.3
* Platform(s) (iOS, Android, or both?): Android

**Comment by kfiroo** [comment]
The error is coming from `Backend` not `GiftedChat`, isn't it?

**Comment by davista123** [comment]
Could you post a picture of the file structure and preferably the code contained in Backend? The problem may stem from either importing the file from the wrong place or some incorrect definition in the Backend file.
