### ISSUE TITLE
Message UI render position modification

### ISSUE THREAD

**Issue by vidhyalakshmirbt** [FaridSafi/react-native-gifted-chat#397]
I want to display the message of particular user in center of the screen,  not on right or left
Can this be done?
I have tried changing the messageProps - position in messageContainer.js
Still no success. Can anyone help me with the same?

react-native-cli: 1.2.0
react-native: 0.41.2
react-native-gifted-chat: ^0.1.3
* Platform(s) (iOS, Android, or both?): Both

**Comment by kfiroo** [comment]
@vidhyalakshmirbt try using `renderMessage` or `renderBubble` to provide a custom view for you messages

**Comment by vidhyalakshmirbt** [comment]
thanks @kfiroo
