### ISSUE TITLE
Does someone encounter the same issue? Sometimes textinput doesn't appear

### ISSUE THREAD

**Issue by yakirbu** [FaridSafi/react-native-gifted-chat#399]
Hi,

I have this weird behaviour,
Most of the time the chat works great,
and there are few times, can't really tell what causing it, if you enter a chat it would appear blank without a textinput.

Has anyone else encountered the same issue?

**Comment by nathan-charles** [comment]
I'm also encountering this same issue on iOS and Android right now

**Comment by kfiroo** [comment]
Some people have encountered issues with `InteractionManager.runAfterInteractions` not calling the callback, it might be related.
See here: https://github.com/FaridSafi/react-native-gifted-chat/pull/355

I merged this PR, hopefully will get a new npm version later today
