### ISSUE TITLE
How to add status of message as  'Sent', 'Seen',...

### ISSUE THREAD

**Issue by hungdev** [FaridSafi/react-native-gifted-chat#401]
could you tell me how to add status of message as 'Sent', 'Seen',.. like image below?
Thank you so much.

![messenger-1](https://cloud.githubusercontent.com/assets/12009276/24034529/30bd1c24-0b24-11e7-960f-d0a2f5daff92.png)

**Comment by Maxwell2022** [comment]
https://github.com/FaridSafi/react-native-gifted-chat/pull/226

**Comment by hindsricardo** [comment]
This shouldn't be closed.

**Comment by RayyanNafees** [comment]
Twalle oo

**Comment by jackimatin** [comment]
is there any solution
?
