### ISSUE TITLE
Keyboard won't dismiss when area outside of keyboard is tapped

### ISSUE THREAD

**Issue by JacobSiegel35** [FaridSafi/react-native-gifted-chat#405]
#### Issue Description

I would like the keyboard to be dismissed after a user taps outside of it, although I have not been able to get anything to work.

#### Steps to Reproduce / Code Snippets
```javascript
<GiftedChat
  keyboardShouldPersistTaps={false}
  messages={messages}
  onSend={this.onSend}
   isAnimated={true}
   user={{
      _id: 1
   }}
/>
```

#### Additional Information

* React Native version: 0.39.2
* react-native-gifted-chat version: 0.0.10
* Platform(s) (iOS, Android, or both?): iOS

**Comment by JacobSiegel35** [comment]
I found a workaround, although it is quite ugly.  Anything I can do to improve this?
```javascript
<TouchableWithoutFeedback onPress={() => {Keyboard.dismiss()}}>
  <View style={{ flex: 1, paddingTop: 75 }}>
    <GiftedChat
        keyboardShouldPersistTaps={'never'}
        messages={messages}
        onSend={this.onSend}
        isAnimated={true}
        user={{
          _id: 1
        }}
      />
  </View>
</TouchableWithoutFeedback>
```

**Comment by fxhereng** [comment]
Try this `keyboardShouldPersistTaps={'handled'}`

It works for me. Strangely `true` or `always` values doesn't work.

Cheers

**Comment by MaxInMoon** [comment]
@JacobSiegel35 

`<TouchableWithoutFeedback onPress={Keyboard.dismiss}>`

is better to avoid useless re-rendering than:

`<TouchableWithoutFeedback onPress={() => {Keyboard.dismiss()}}>`

**Comment by adolffre** [comment]
If you have a flat List inside the TouchableWithoutFeedback would be not possible to scroll it if the keyboard is not showing!

**Comment by sagarguhe** [comment]
I am also facing the same issue, @JacobSiegel35's workaround worked for me.

**Comment by torabian** [comment]
Also I had to use the workaround, Feedback > View > GiftedChat

**Comment by moulie415** [comment]
> I found a workaround, although it is quite ugly. Anything I can do to improve this?
> 
> ```js
> <TouchableWithoutFeedback onPress={() => {Keyboard.dismiss()}}>
>   <View style={{ flex: 1, paddingTop: 75 }}>
>     <GiftedChat
>         keyboardShouldPersistTaps={'never'}
>         messages={messages}
>         onSend={this.onSend}
>         isAnimated={true}
>         user={{
>           _id: 1
>         }}
>       />
>   </View>
> </TouchableWithoutFeedback>
> ```

This solution is not great for accessibility with regards to users with voice over on, I worked on a global app that uses Gifted Chat and we had a user with voice over on say that they couldn't use our chat. The ```keyboardShouldPersistTaps={'handled'}``` seems to work great though!!
