### ISSUE TITLE
Avatar for sending user(primary user in the chat)

### ISSUE THREAD

**Issue by prithsharma** [FaridSafi/react-native-gifted-chat#406]
I looked at the code and [this line](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/Message.js#L44) makes it difficult to customize the behavior(even absence/presence) of avatar of the sending user. The prop `renderAvatar` passed comes into picture in the `Avatar` component. Please tell me if I am missing something.

If there a way to let avatar be visible for the sending user too?

**Comment by prithsharma** [comment]
@FaridSafi any comment about this?

**Comment by kfiroo** [comment]
@prithsharma Hey, I think this is related https://github.com/FaridSafi/react-native-gifted-chat/issues/247
Currently there is no way to do it, you can try to create a PR that will enable it and I would merge it

**Comment by kfiroo** [comment]
@prithsharma maybe related as well https://github.com/FaridSafi/react-native-gifted-chat/pull/297

**Comment by kfiroo** [comment]
@prithsharma What you want to do isn't as straight forward as I thought, we need to change [this condition](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/Message.js#L44) to allow rendering the avatar for messages sent by the current user, but also change some styles as the default style assumes sent messages have no avatar..
There might also be some cases I didn't think of..

**Comment by prithsharma** [comment]
Exactly, that's the link I quoted in my issue description too.
I think the primary problem is that the component's `renderAvatar` prop comes into picture in the `Avatar` component. However, I think it should be used in the `Message` component's `renderAvatar` method(the same one that you and me gave the link to above). If the `renderAvatar` method in `Message.js` can be changed to something like
```
if (this.props.renderAvatar) { return this.props.renderAvatar(avatarProps); }
else { <Avatar {...avatarProps} /> }
```
then the issue should be easy to handle.
In fact, I tried to test this by just removing the if condition you are talking about and without any additional styling changes, the avatar for the sending user is rendered well.
Anyway, I'll look at this and see if I can create a PR and you can guide me forward. Do you think it should be a separate prop to configure this behavior or a custom `renderAvatar` should be able to do this?

**Comment by kfiroo** [comment]
@prithsharma My concern is not with the `Avatar` styles, rather with the styles of its message.
We need to make sure `image messages` / `long text message` / `location message` etc. works well with the avatar visible.

**Comment by prithsharma** [comment]
Ah ok. Let me see this one.
Don't you think the `renderAvatar` component being passed should be used earlier in the hierarchy(e.g. [here](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/Message.js#L44)) than where it is currently([here](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/Avatar.js#L8))?

**Comment by kfiroo** [comment]
When you provide `renderAvatar` you are actually replacing the inner `GiftedAvatar` not the `Avatar` component, so we can't just move the call to `renderAvatar` there..

What I think should happen is to have a prop that would indicate we want to show avatars for current user as well and change the code in `Message.renderAvatar` to something like this:

```jsx
  renderAvatar() {
    if (this.props.showAvatarForCurrentUser || this.props.user._id !== this.props.currentMessage.user._id) {
      const avatarProps = this.getInnerComponentProps();
      return <Avatar {...avatarProps}/>;
    }
    return null;
  }
```

**Comment by kfiroo** [comment]
`renderAvatar` is not meant to override the logic of when to show the avatar, but to override **how** we render the avatar

**Comment by nonotest** [comment]
I agree with @prithsharma .

Note that if you want a quick solution you can always do something like this:

```
renderBubble = (props) => {
    if (props.user._id === props.currentMessage.user._id) {
      return (
        <View style={bubbleStyles['right'].container}>
          {this.renderAvatar(props)}
          {this._renderBubble(props)}
        </View>
      )
    }
    return this._renderBubble(props);
  }
```

**Comment by gameboyVito** [comment]
Hi, I have implemented this perfectly and figure out how to use the `onPress` props in the Avatar. You can reference my code.
```
import {GiftedChat, Send, Composer, Bubble, Message, MessageText, GiftedAvatar, utils} from "react-native-gifted-chat";

renderBubble = (props) => {
        //right avatar
        const renderAvatarOnTop = props.renderAvatarOnTop;
        const messageToCompare = renderAvatarOnTop ? props.previousMessage : props.nextMessage;
        if (props.user._id === props.currentMessage.user._id) {
            return (
                <View style={styles.bubbleViewRight}>
                    <Bubble
                        {...props}
                        onLongPress={() => {}}
                        containerStyle={styles.bubbleContainer}
                        wrapperStyle={styles.bubbleWrapper}
                    />
                    {utils.isSameUser(props.currentMessage, messageToCompare) && utils.isSameDay(props.currentMessage, messageToCompare) ?
                        <GiftedAvatar avatarStyle={styles.avatar.dummy}/> :
                        <GiftedAvatar
                            {...props}
                            user={props.currentMessage.user}
                            avatarStyle={styles.avatar.right}
                            onPress={() => this.handlePress('avatar')}/>
                    }
                </View>
            );
        }

        //default bubble
        return (
            <View style={styles.bubbleView}>
                <Bubble
                    {...props}
                    onLongPress={() => {}}
                    containerStyle={styles.bubbleContainer}
                    wrapperStyle={styles.bubbleWrapper}
                />
            </View>
        );
    };
```

**Comment by samybob1** [comment]
@gameboyVito nice, can you give us your `styles` var?

**Comment by samybob1** [comment]
Here is my solution:

```js
import { GiftedChat, Message, Avatar } from 'react-native-gifted-chat';

// Extend Message class
class CustomMessage extends Message {
  renderAvatar() {
    return (
      <Avatar {...this.getInnerComponentProps()}/>
    );
  }
}

// Render the chat in your component
class YourComponent extends PureComponent {
  // your stuff here...

  render() {
    <GiftedChat
      messages={this.props.messages}
      onSend={this.props.onSendMessages}
      user={this.props.user}
      renderMessage={props => <CustomMessage {...props}/>} // Here we use our CustomMessage class
    />
  }
}
```

The `renderAvatar` implementation is [the same than the original](https://github.com/FaridSafi/react-native-gifted-chat/blob/7de1c1c8eb3e5305b3746487a1ed68fbb681fa27/src/Message.js#L43), without the `if (this.props.user._id !== this.props.currentMessage.user._id)` test.

Result:
<img width="377" alt="capture d ecran 2017-05-28 a 20 16 37" src="https://cloud.githubusercontent.com/assets/2417752/26531120/b0598f84-43e2-11e7-91ce-5f59f7d38310.png">
