### ISSUE TITLE
Question: How to use local images?

### ISSUE THREAD

**Issue by sagax85** [FaridSafi/react-native-gifted-chat#409]
sorry, it's probably a stupid question, but is there any example or description how to use avatars or images in messages with **local** images? All the examples always use a web url and e.g.
```
require("./imgs/1.png")
```
as param doesn't seem to do anything :)

**Comment by sagax85** [comment]
has been answered at other places already.

**Comment by HelloEdit** [comment]
@sagax85 How did you do ? I can not integrate the local images for the photos and the avatar 😭

So if you could help me, I would be grateful 😀

**Comment by wrightmk** [comment]
In the componentWillMount of the demo code provided on the main page, try adding a relative path:

```
  componentWillMount() {
    this.setState({
      messages: [
        {
          _id: 1,
          text: 'Hello User',
          createdAt: new Date(),
          user: {
            _id: 2,
            name: 'User',
            avatar: require('./my_picture.png'),
          },
        },
      ],
    });
  }           

```

**Comment by devjaw** [comment]
@wrightmk it is not working with me

**Comment by hegelstad** [comment]
This isn't working for me either.

It works if I add the relative path to the user prop of GiftedChat, but if i try adding a local picture with relative path to a message in onSend it will get the wrong image number. It is seemingly picking a random number.

**Comment by rajat-np** [comment]
requiring an image from a local folder and adding as an avatar is working.
