### ISSUE TITLE
Long message > Rotate screen > Send button gone offscreen

### ISSUE THREAD

**Issue by cooperka** [FaridSafi/react-native-gifted-chat#413]
#### Issue Description

Send button goes off-screen after typing long message then dismissing keyboard [Android only] or rotating to change orientation [Android and iOS] as of latest master.

Send button would normally be on the right in this screenshot, but now it's pushed down below the screen because the text is actually more than just 2 lines:

![screen shot 2017-03-30 at 11 52 07](https://cloud.githubusercontent.com/assets/2047062/24513633/b048223e-153f-11e7-9f78-517d6096236e.png)

#### Steps to Reproduce

(You can use the example app)

1. Type a long sentence with 3+ lines of text
2. Everything should be fine, it works great
3. Dismiss the keyboard or rotate to change device orientation
4. Now you can't see the wrapped text and the send button is off-screen

#### Additional Information

* React Native version: 0.42
* react-native-gifted-chat version: latest master [[April 12](https://github.com/FaridSafi/react-native-gifted-chat/commits/master@%7B2017-04-12%7D)]
* Platform(s): Android

I'm happy to make a PR eventually but that might not happen for a few weeks.

**Comment by kfiroo** [comment]
@cooperka Any idea what's going on there?

**Comment by cooperka** [comment]
@kfiroo I think the Send button is just centering vertically within the very tall view, but the view is getting clipped because some state is lost ("current number of lines" is probably stored somewhere and gets reset on orientation change). If you have around 2-3 lines of text, you can see the button peeking up at the very bottom of the screen. It's centering properly, the view just doesn't have enough room to show everything.

**Comment by kfiroo** [comment]
@cooperka Haven't tested it, but I think I found our criminal: https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/InputToolbar.js#L73
If we change it to `flex-start` if should solve this issue.

**Comment by cooperka** [comment]
(Fixed by #425)
