### ISSUE TITLE
Keyboard issue for iOS

### ISSUE THREAD

**Issue by vidhyalakshmirbt** [FaridSafi/react-native-gifted-chat#414]
#### Issue Description

i am using two gifted chat in one screen. first one doesn't have text input and second one has textinput .
 When keyboard moves up, i cannot see the text input , this happens only for **iOS**.

**Example code..**

          <View style={{flex:1}>
            <View style={{flex:0.7}}>
              <GiftedChat
             renderInputToolbar={this.renderInput}
            />
            </View>
            <View style={{flex:0.3}}>

              <Text >text</Text>
               <GiftedChat
     
               />
            </View>

       </View>
renderInput()
{
return null;
} 

react-native-cli: 1.2.0
react-native: 0.41.2
react-native-gifted-chat: ^0.1.3

@kfiroo @FaridSafi if you can help

**Comment by kfiroo** [comment]
@vidhyalakshmirbt Hey! Sorry, I haven't tried having 2 instances on the same page! :)
What is the expected behaviour?
Can you post some images?

**Comment by vidhyalakshmirbt** [comment]
i need normal behaviour like when you type a message , (click on text input) the keyboard to move up ..
I have different datasources for both gifted chat , so everything works fine except for this keyboard handling. 

the text input gets hidden while the keyboard is clicked. 
@kfiroo

**Comment by vidhyalakshmirbt** [comment]
![mobile screens_1artboard 7 copy](https://cloud.githubusercontent.com/assets/20920834/24608664/29c9ad96-1895-11e7-843b-040e3eec412c.png)

**Comment by vidhyalakshmirbt** [comment]
screen looks somehting like this @kfiroo

**Comment by kfiroo** [comment]
Let me try to recap:
* You have 2 instances of `GiftedChat`
* Only the bottom instance has a text input
* Focusing the text input should push the whole screen up
* Sending a message should only send the message to the bottom instance
Did I get it right?

**Comment by vidhyalakshmirbt** [comment]
Sending a message should only send the message to the bottom instance - This point is not correct. Sending a message send to either UI depending on some conditions which i have already implemented.
I just need help with Focusing the text input should push the whole screen up
And ya first two points are correct @kfiroo

**Comment by kfiroo** [comment]
@vidhyalakshmirbt Got it!
I'll try to play around with it later today
No promises! :)

**Comment by vidhyalakshmirbt** [comment]
@kfiroo  Thanks for the help :)

**Comment by andrewmarushko** [comment]
Hi @vidhyalakshmirbt @kfiroo .
I have the same issue in IOS.
Did you find some solution?
