### ISSUE TITLE
onInputTextChanged not available on 0.0.1

### ISSUE THREAD

**Issue by Spence-S** [FaridSafi/react-native-gifted-chat#417]
#### Issue Description

This prop (onInputTextChanged) is not available on version 0.0.10

#### Additional Information

* React Native version: [0.39.2]
* react-native-gifted-chat version: [0.0.10]
* Platform(s) (iOS, Android, or both?): both

**Comment by kfiroo** [comment]
This feature was added in a later release, sorry.
