### ISSUE TITLE
Example fails on RN > 0.40.0

### ISSUE THREAD

**Issue by yatagan** [FaridSafi/react-native-gifted-chat#419]
#### Issue Description

![screen shot 2017-04-08 at 2 05 46 pm](https://cloud.githubusercontent.com/assets/724577/24828386/a3e0b390-1c64-11e7-80f2-60dbdd0d6e7f.png)

#### Steps to Reproduce / Code Snippets

Change RN version in example/package.json:
  "dependencies": {
    "react-native": "**0.40**"
    ...
  }

to something > 0.40

#### Expected Results

Working example

#### Additional Information

* React Native version: 0.42
* react-native-gifted-chat version: 1d675aa81409294a2bd657c1c5255baaf4ec6b56
* Platform(s) (iOS, Android, or both?): ios

**Comment by vgorte** [comment]
working for me. Whats is your RN version ?
