### ISSUE TITLE
Some of my Android users report messages being cut off

### ISSUE THREAD

**Issue by booboothefool** [FaridSafi/react-native-gifted-chat#420]
![screen shot 2017-04-09 at 2 21 58 pm](https://cloud.githubusercontent.com/assets/13257645/24839852/f4047020-1d2f-11e7-9abc-d63733ff2326.png)

Personally, I test this library on an iPhone 5, 6, 7, Plus + Samsung Galaxy S6 and it seems to work/look great, so I can't reproduce this issue.

I've gotten this report on more than one occasion and it's always with some Android phone that I've never heard of.

Any ideas?

**Comment by kfiroo** [comment]
@booboothefool Can you say which phones is this happening on?
Also, what versions are you using?
Thanks

**Comment by afloury** [comment]
I think, I have the same problem with my physical device :
![screenshot_2017-08-30-19-04-20](https://user-images.githubusercontent.com/18677074/29885356-c3d43960-8db6-11e7-94b9-4c60d2953854.png)

The first message is 'Hello developer' like the example, but it's not displaying correctly, sometimes it's good, sometimes the last word is missing, or the last letter of the last word, weird.

The problem doesn't appear in the simulator, but on my real device :
LG G3 (LG-D855) 2560 x 1440 pixels
Android 6.0
react 16.0.0-alpha.12
react-native 0.47.2
react-native-gifted-chat 0.2.7

If someone has an idea.

**Comment by brunocascio** [comment]
@afloury Did you resolve this?

**Comment by afloury** [comment]
I'm close to  :point_right: #559
