### ISSUE TITLE
Attempted to assign to readonly property

### ISSUE THREAD

**Issue by N1XUS** [FaridSafi/react-native-gifted-chat#422]
#### Issue Description

When I'm trying to change Composer placeholder, send button text

#### Steps to Reproduce / Code Snippets

```
renderComposer(props) {
    props.placeholder = 'Напишите сообщение';
  }

<GiftedChat renderComposer={this.renderComposer}...
```

#### Expected Results

To change placeholder/button text

#### Additional Information

* React Native version: 0.42.3
* react-native-gifted-chat version: 0.1.3
* Platform(s) (iOS, Android, or both?): tested on iOS, but I guess on Android will be the same

**Comment by kfiroo** [comment]
@N1XUS Hey, in `react` the `props` are read only and you should never change them. See here https://facebook.github.io/react/docs/components-and-props.html#props-are-read-only

You should do something like this instead:
```jsx
import {GiftedChat, Composer} from 'react-native-gifted-chat';
...
renderComposer(props) {
    return (
        <Composer {...props} placeholder='Напишите сообщение' />
    );
  }

<GiftedChat renderComposer={this.renderComposer}...
```

**Comment by N1XUS** [comment]
Oh, sorry. My bad (new to all this React stuff)
