### ISSUE TITLE
[jest] Identifier 'exports' has already been declared

### ISSUE THREAD

**Issue by Maxwell2022** [FaridSafi/react-native-gifted-chat#423]
#### Issue Description
Jest tests is throwing error in projects as soon as you import `react-native-gifted-chat`.
This is related to https://github.com/expo/react-native-action-sheet/issues/26

`react-native-gifted-chat` is using an outdated version (`0.3.0`) of `@expo/react-native-action-sheet` (latest: `0.3.1`)

#### Steps to Reproduce / Code Snippets

Add a jest test file in your project that is testing a basic component. Add an import to this component: 
`import Chat from 'react-native-gifted-chat';`

#### Expected Results
No errors from jest

#### Additional Information

* React Native version: 0.42.3
* react-native-gifted-chat version: ^0.1.4
* Platform(s) (iOS, Android, or both?): any

![image](https://cloud.githubusercontent.com/assets/670701/24986548/38539eb6-203e-11e7-9bb3-2e82a4fdbf02.png)

**Comment by kfiroo** [comment]
@Maxwell2022 Thanks! want to create a quick PR to fix that? :)

**Comment by brunsy** [comment]
created the PR for this: https://github.com/FaridSafi/react-native-gifted-chat/pull/454

**Comment by bitsal** [comment]
When is it going to be released?

**Comment by Maxwell2022** [comment]
PR has been merged, I'm closing this issue. No idea about the release @bitsal
