### ISSUE TITLE
Custom Message component

### ISSUE THREAD

**Issue by pdubey84** [FaridSafi/react-native-gifted-chat#424]
Well first of all thanks a lot for this amazing component.

This isnt really an issue but more of a help request.

What am trying to do is:

- Have a custom message type... something like a post with title, description, etc.
- once it gets created and saved it shows up in the chat list.
- How can it be achieved?

I want to pass an obj with type:POST and then display message accordingly.
The regular messages will have type:TEXT

Thanks a lot in advance for the help.

**Comment by Blacktoviche** [comment]
It's easy to implement you can use CustomView to render any type of message you want
I used it to implement progress circle component in my project

**Comment by pdubey84** [comment]
By any chance would you mind sharing a code snippet? or an example?

**Comment by Blacktoviche** [comment]
Sure, here is my custom message
[ProgressMessage.js](https://github.com/Blacktoviche/RNChat/blob/master/src/compos/ProgressMessage.js)

**Comment by pdubey84** [comment]
Thanks a ton @Blacktoviche. Exactly what I was looking for.

**Comment by Blacktoviche** [comment]
You are welcome, glad to help

**Comment by stlemon** [comment]
@Blacktoviche can you give me the ProgressMessage.js again?this one is missed!Thanks very much!

**Comment by Blacktoviche** [comment]
@stlemon Yeah sure 
Here is a gist
https://gist.github.com/Blacktoviche/1acfe564071b76d01b0e8b11d1bf05de

**Comment by stlemon** [comment]
@Blacktoviche Thank you very much, but I can't open this in China, like  "https://gist.github.com/" .

**Comment by stlemon** [comment]
@Blacktoviche I want to display a sub component as a message on the chat page, but I don't know how to do it. 
Can you give me some advice？

**Comment by stlemon** [comment]
@Blacktoviche I have done this , still thank you very much！
