### ISSUE TITLE
[Question] Is it possible to know when at the beginning of chat list?

### ISSUE THREAD

**Issue by testshallpasswork** [FaridSafi/react-native-gifted-chat#428]
#### Issue Description

My use case is to know when user scrolls to the beginning of chat list. Since gifted chat uses an inverted ScrollView this is considered beginning list vs. end of list as it normally would be known. 

#### Expected Results

A callback to indicate onStartReached. Basically opposite of onEndReached.

#### Additional Information

* React Native version: 0.39.0
* react-native-gifted-chat version: custom fork from master.
* Platform(s) (iOS, Android, or both?): both

**Comment by n-sviridenko** [comment]
Any news on this?
