### ISSUE TITLE
Audio and Video option

### ISSUE THREAD

**Issue by rishiankush** [FaridSafi/react-native-gifted-chat#429]
Hi, I used this package several times and It is very helpful always.
This time I am in need to add the audio and video options too.
How can I add those options? Or do you provide those options in this package?

According to my learning I did not find any such option for audio recording and video recording
 till now I was able to add this: 
![screen shot 2017-04-15 at 12 07 18 pm](https://cloud.githubusercontent.com/assets/25289937/25061441/2415f344-21d4-11e7-8416-ae821a0de57f.png)

For audio recording I am using third party package.

**Comment by lzj89566062** [comment]
@rishiankush could u share your repo?  [https://github.com/rishiankush/Goopso](url) that's ur react-native-gifted-chat 4 Voice&Video ?

**Comment by lzj89566062** [comment]
@FaridSafi I've been looking for chat components that implement audio&video features, but so far I have no results
I would like to be based on gifted-chat extension, do you have a good suggestion?

**Comment by rishiankush** [comment]
I have used these two packages for audio and video recording:
@lzj89566062 https://github.com/jsierles/react-native-audio
https://www.npmjs.com/package/react-native-video-recorder

Hope this helps

**Comment by bgbraga** [comment]
Any plans to integrate Gifted with https://github.com/jsierles/react-native-audio ?

**Comment by wayne1203** [comment]
Sounds good, I would like to try it.
But.. How can I add Audio message UI?

**Comment by WwoeSsi** [comment]
@wayne1203  did you integrate it yet?

**Comment by wayne1203** [comment]
Implementing with react-native-sounds
Like this:
<img width="366" alt="2017-07-29 12 10 27" src="https://user-images.githubusercontent.com/8578341/28726096-6916c304-73f2-11e7-8719-e41e9382f8d7.png">

**Comment by WwoeSsi** [comment]
Awesome, I need that too

**Comment by WwoeSsi** [comment]
I wanna make WhatsApp, what are you making

**Comment by wayne1203** [comment]
I'm developing a chatting app like WhatsApp.
And investigating how to edit the InputToolbar for adding a voice record button like WhatsApp

**Comment by WwoeSsi** [comment]
Ah, interesting! I think our work is really similar then.

**Comment by WwoeSsi** [comment]
I don't know how to contact you other than this, but let's connect maybe we can share some work or something. karsens@outlook.com

**Comment by WwoeSsi** [comment]
@wayne1203

**Comment by wayne1203** [comment]
@WwoeSsi Sure, here is my email wayne1203658@gmail.com

**Comment by sidd123456** [comment]
@wayne1203 @WwoeSsi how can i simply send an image can anyone help?

**Comment by wayne1203** [comment]
@sidd123456 Do you mean how to upload the image for your issue?
Just drag & drop into the text area, Github will handle it

**Comment by sidd123456** [comment]
@wayne1203 means while chating Onsend function sends only text if i want to send an image then?

**Comment by wayne1203** [comment]
@sidd123456 Just add "image" parameter into the message and you will get ImageView by default.
No any code change needed.
Text will show on the bottom of the message bubble if "text" parameter exist. (If my memory serves well)

**Comment by sidd123456** [comment]
@wayne1203 getting this error:
"json value null cannot be converted to nsstring "

**Comment by liplylie** [comment]
For those that want to see a code sample to handle audio recordings, here is a link to a medium article that I posted: https://medium.com/@decentpianist/react-native-chat-with-image-and-audio-c09054ca2204

**Comment by dkpapo** [comment]
> Implementing with react-native-sounds
> Like this:
> <img alt="2017-07-29 12 10 27" width="366" src="https://user-images.githubusercontent.com/8578341/28726096-6916c304-73f2-11e7-8719-e41e9382f8d7.png">

this dont work because react native sound only play in raw route any can help me pls

**Comment by ajaytheone1994** [comment]
@wayne1203 i want to add record icon into Input Toolbar, please help me if you can,
Thank in advanced..

**Comment by wayne1203** [comment]
> @wayne1203 i want to add record icon into Input Toolbar, please help me if you can,
> Thank in advanced..

Hi, I'm sorry to tell you that I'm not developing chat room apps long time ago.
But you can try to use renderInputToolbar for custom toolbar.

**Comment by Muhsin-Abbas** [comment]
> I'm developing a chatting app like WhatsApp. And investigating how to edit the InputToolbar for adding a voice record button like WhatsApp

hi can you help me issue on voice recording

**Comment by Yogesh-Dubey-0804** [comment]
Well in order to add button like Whatsapp does you do need make use of composer that you can get from the library first of all all do this thing 


             import { GiftedChat ,InputToolbar,Bubble, Composer, Send } from 'react-native-gifted-chat';


your render composer should like 

              const renderComposer = (props) => {
                return(
                  <View style = {styles.TextInputContainer}>
                    { rendering == true?
                        <>
                        <TouchableOpacity activeOpacity={0.5} >
                           <MaterialCommunityIcon name="folder-image" color={"rgba(74,144,226,1)"} size ={25} style ={{marginLeft:2,marginTop:10}} ></MaterialCommunityIcon>
                        </TouchableOpacity>
                      <TouchableOpacity activeOpacity={0.5}>
                          <FontAwesome name="microphone" size = {25} color={"rgba(74,144,226,1)"} style = {{marginLeft:8,marginRight:10,marginTop:10}}></FontAwesome>
                      </TouchableOpacity>
                      </>:null}
                      <View style ={{flexDirection:"row",
                                      color: 'white',
                                      borderColor:"grey",
                                      borderWidth:0.5,
                                      width:rendering == true?DeviceDimensions.Width-121:DeviceDimensions.Width-60,
                                      borderRadius:10
                    }}>
                      <TouchableOpacity  onPress= {()=>{ProbeContacts()}}>
                      <Entypo name ="emoji-flirt" size = {25} color = {"rgba(74,144,226,1)" } style = {{marginLeft:5,marginTop:10}}></Entypo> 
                      </TouchableOpacity>
                      <Composer
                            {...props}
                            textInputStyle={{
                              color: 'white',
                        }}
                            placeholder="Aye! 🙂"
                            textInputProps={{
                                onChange:((e)=>{e.nativeEvent.text.trim() == 0?Setrendering(true):Setrendering(false);
                                }),
                              }}
                          >
                          </Composer>
                      </View>
                      
                  </View>
   


while Calling Gifted chat 

          <GiftedChat
            messages={messages}
            onSend={messages => onSend(messages)}
            user={{
                _id:1,
            }}
            renderSend={renderSend}
           renderComposer ={renderComposer}
           renderInputToolbar ={customtInputToolbar}
           inverted = {true}
           onLongPress = {(context,message)=>{
             setRenderHeaderBar(false)
             setMessageProperties(message)
             Keyboard.dismiss()
           }}
           renderBubble = {renderBubble}
           
           
         // onPress={(context,message)=>{console.log(message.text)}}
            />



You might be wondering of that what is the use of  composer and the inputToolBar well the right answer is composer is the container which contains the the inputtext and the inputToolBar is the way through which you can modify the textinput or can add extra props. 


For more details and preview you can mailme at yogesh08099@gmail.com
