### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by nickkapoor** [FaridSafi/react-native-gifted-chat#434]
#### Issue Description

Attempting to install gifted-chat.  Did  npm install react-native-gifted-chat --save as per the instructions.  I am getting the error 

npm ERR! unpack Could not read data for @expo/react-native-action-sheet@0.3.0
AwesomeProject@0.0.1 /Users/xxx/development/AwesomeProject
├── md5@2.2.1  extraneous
├── react-native-invertible-scroll-view@1.0.0  extraneous
├── react-native-lightbox@0.6.0  extraneous (git://github.com/oblador/react-native-lightbox.git#c84a8543d4511fe6a44c3d7820747c9c1bddd875)
├── react-native-parsed-text@0.0.16  extraneous
└── shallowequal@0.2.2  extraneous

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-native-gifted-chat" "--save"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@expo/react-native-action-sheet"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/XXXXX/development/AwesomeProject/npm-debug.log

#### Steps to Reproduce / Code Snippets

Existing application. Do the npm install and am getting this error.  

#### Expected Results

Was expecting to install and run this component.

#### Additional Information

* React Native version: [0.4]
* react-native-gifted-chat version: [Installing the current one]
* Platform(s) (iOS, Android, or both?): [ios]

**Comment by brunocascio** [comment]
Since se cannot reproduce the issue, I assume that was a problem with your environment.

Feel free to reopen if not.
