### ISSUE TITLE
onLongPress is not work

### ISSUE THREAD

**Issue by hhtu** [FaridSafi/react-native-gifted-chat#436]
#### Issue Description

onLongPress is not work

In your instructions, we get returned context and message according to this

`onLongPress (Function(context, message))`

but I only get context without message

and I checked in Bubble.js 

the code in onLongPress function which shows

`    if (this.props.onLongPress) {
      this.props.onLongPress(this.context);`

It does not return this.props.currentMessage.text like the rest of codes

so how can I get the pressed message?

#### Steps to Reproduce / Code Snippets

just use in 

```
<GiftedChat 
onLongPressMsg={(context, message) => {
    console.log(context) // I got actionSheet
    console.log(message) // I got undefined
}}
/>
```

#### Expected Results

return pressed message

#### Additional Information

* React Native version: 0.42.0
* react-native-gifted-chat version: 0.1.4
* Platform(s) (iOS, Android, or both?): both

**Comment by DiegoGallegos4** [comment]
NPM Repo is not updated to github repo

**Comment by ycpatel813** [comment]
Any update?

**Comment by DiegoGallegos4** [comment]
You'll have to change it manually on the repo.

**Comment by thedmeyer** [comment]
This is not functioning properly in the github repo either.

**Comment by emmyduruc** [comment]
> onLongPressMsg={(context, message) => {
>     console.log(context) // I got actionSheet
>     console.log(message) // I got undefined
> }}

did you find a solution?
