### ISSUE TITLE
Render emojis in message

### ISSUE THREAD

**Issue by jwilbert** [FaridSafi/react-native-gifted-chat#439]
This might be an easy one, but I haven't found anything on emojis in the documentation yet.

What would be the best way do I include emojis in messages?
So for example how would I print "Hello Developer &#128518;"?

This of course does not work: 
`  componentWillMount() {
    this.setState({
      messages: [
        {
          _id: 1,
          text: 'Hello developer &#128518;',
          createdAt: new Date(Date.UTC(2016, 7, 30, 17, 20, 0)),
          user: {
            _id: 2,
            name: 'React Native',
            avatar: 'https://facebook.github.io/react/img/logo_og.png',
          },
        },
      ],
    });
  }`

Thanks!

**Comment by kfiroo** [comment]
Emojis are just text, you don't need anything special for it :)

**Comment by jwilbert** [comment]
Occam's razor...
Thanks @kfiroo
