### ISSUE TITLE
How to complete hide avatar?

### ISSUE THREAD

**Issue by dfischer** [FaridSafi/react-native-gifted-chat#440]
#### Issue Description

Trying to completely hide the avatar but still get ghost spacing... See attached.

![screen shot 2017-04-27 at 1 12 29 am](https://cloud.githubusercontent.com/assets/2424/25474040/9747b4b8-2ae6-11e7-9e8e-5f0d31758c54.png)

#### Steps to Reproduce / Code Snippets

```
renderAvatar(props) {
  return null;
}
```

Figured this would hide the component but it only completely hides it on the bottom most received message, the other ones still render a blank avatar.

#### Expected Results

No avatar (flush left margin)

#### Additional Information

* React Native version: 0.43.4
* react-native-gifted-chat version: 0.1.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by LEEY19** [comment]
@dfischer any solution to this?

**Comment by ArtemKosiakevych** [comment]
... just do
renderAvatar(props) {
  return <View/>;
}

**Comment by varungupta85** [comment]
you will need to specify `renderAvatar={null}` to get rid of the ghost spacing. I have recently committed this fix. Not sure if it has been released on npm yet. So you may have to install from the repo directly.

**Comment by dfischer** [comment]
I can confirm latest from repo worked but I think recently npm worked too but I don't recall offhand. Thanks @varungupta85

**Comment by andrisLaduzans** [comment]
```
renderAvatar={() => null}
showAvatarForEveryMessage={true}
```
will render null for all messages.

**Comment by Ibrar-Khatri** [comment]
just to renderAvatar={null}

**Comment by minawalphonce** [comment]
renderAvatar={null} works fine but complains about typing, i m using typescript 
`Warning: Failed prop type: Invalid prop `renderAvatar` of type `boolean` supplied to `GiftedChat`, expected `function`.`

**Comment by iAppTechGary** [comment]
> ... just do
> 
> ```
> renderAvatar(props) {
>   return <View/>;
> }
> ```

leaves space on avatars place
