### ISSUE TITLE
[Question] Some localization question

### ISSUE THREAD

**Issue by cyclops24** [FaridSafi/react-native-gifted-chat#444]
Hi @FaridSafi ,
First thanks for this useful project. You done a great work man 😉 
Is this awesome gift support RTL or not?
How we can localize it to other language (for example Persian)?

**Comment by cyclops24** [comment]
**/CC:** @cooperka

**Comment by cooperka** [comment]
Hi @cyclops24, to my knowledge there's not really any localization built in yet. We'd love to support it though, so if you or anyone else in the community would like to send a PR, that would be fantastic.

I'll close this issue now, but please feel free to continue following up here if you have more thoughts.
