### ISSUE TITLE
Allow the date of the first message visible on the screen to stick on the top

### ISSUE THREAD

**Issue by varungupta85** [FaridSafi/react-native-gifted-chat#446]
#### Issue Description
Currently, the date rolls out of the visible area while scrolling messages. Sticking the date for the first message visible on screen would provide a much better experience to the user which is a common practice in many other chat applications now.

#### Additional Information

* React Native version: 0.42.0
* react-native-gifted-chat version: 0.1.4
* Platform(s) (iOS, Android, or both?): Both

**Comment by korgara** [comment]
+1
