### ISSUE TITLE
Adding a top message

### ISSUE THREAD

**Issue by RWOverdijk** [FaridSafi/react-native-gifted-chat#451]
#### Issue Description

No issue. I'm just curious if it's possible to add a top message at the beginning of a chat somehow. I'm looking into using this for support, but I'd like to show some sort of bubble saying "Someone will answer you shortly". Any arbitrary message. I couldn't find it in the docs.

**Update**: In the same breath, I'd like to ask if it's possible to add some sort of "Person is typing..." kind of thing.

**Update**: Seeing how I'm already asking too many questions... :p what's the best way to change the color of a bubble? I like the default styling, I don't want to change it. I just want to change the color.

#### Steps to Reproduce / Code Snippets

N/A

#### Expected Results

N/A

#### Additional Information

N/A

**Comment by cooperka** [comment]
Hi @RWOverdijk, one way to add an intro message would be to simply hard-code a message that will be used if the real array of messages is empty. You can have it say whatever you want and come from a custom avatar.

For "Person is typing..." indicators, you can use [`renderFooter`](https://github.com/FaridSafi/react-native-gifted-chat/#props).

To change the color of a bubble, check out [Bubble.js](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/Bubble.js). I believe you can use:

```js
containerStyle: {
  left: { backgroundColor: 'red' },
  right: { backgroundColor: 'blue' },
}
```

**Comment by cooperka** [comment]
If any of those methods don't work, feel free to submit a PR! Closing this issue now but feel free to reply below.
