### ISSUE TITLE
[QUESTION] Image above messages in messagecontainer

### ISSUE THREAD

**Issue by vgorte** [FaridSafi/react-native-gifted-chat#452]
I want to have an image inside the message container. This image should move up with incoming messages. 
How can I display anything, that is not inside a bubble, inside the message container ?

**Comment by kfiroo** [comment]
@vgorte Not sure I understand what you want to do here exactly

**Comment by vgorte** [comment]
I'm sorry for beeing too vague. 

I want to have something like this:

<img width="175" alt="bildschirmfoto 2017-04-12 um 17 38 35" src="https://cloud.githubusercontent.com/assets/17333517/26033942/0aa4b63c-38b5-11e7-980d-f7db76ed2139.png">

So I created the component with an image and text, etc. but here is my problem:

How can I add this component to the message container without it beeing in a bubble. 
The component should also move upwards with incoming messages.

I would really appreciate advice.

**Comment by kfiroo** [comment]
@vgorte An easy solution would be to prepend you data with a stub message and use `renderMessage` to render whatever you want there.
