### ISSUE TITLE
android:windowSoftInputMode="adjustResize" doesn't fix the text box. it is going out of view.

### ISSUE THREAD

**Issue by AkshayKomarla** [FaridSafi/react-native-gifted-chat#458]
#### Issue Description
I'm a newbie in this. please correct me if i'm wrong

in Android the **chat box** goes out of view but works well in IOS.  It works fine when connected to a remote debugger  but after disconnecting the issue persists.

Please check the screenshot.

![screenshot_20170511-120049](https://cloud.githubusercontent.com/assets/15768487/25935859/bdfa5400-3642-11e7-83bb-4e3d976446b8.png)

#### Steps to Reproduce / Code Snippets

Followed the normal installation procedure from Readme.md guide 

#### Additional Information

* React Native version: 0.44.0
* react-native-gifted-chat version: ^0.1.4
* Platform(s) (iOS, Android, or both?): Android

**Comment by TriangleIL** [comment]
we've had the same issue and haven't been able to track a solution yet.  Seems it is cut exactly in half...

**Comment by AkshayKomarla** [comment]
i added a temporary fix. I'm not sure if this is the solution .
I added **minInputToolbarHeight={75}** to increase the chat box height.

**Comment by jpahalwani** [comment]
I am facing the same issue. Tried the solution mentioned above. The issue still persists. @FaridSafi Could you please help?
