### ISSUE TITLE
onPressAvatar not implemented in latest 

### ISSUE THREAD

**Issue by mypark** [FaridSafi/react-native-gifted-chat#460]
Looking through the docs there is documentation for onPressAvatar, but I don't see it implemented in version 0.1.4 from npm.  Is it not in the current release version?

**Comment by mypark** [comment]
Ok I pulled from master rather than npm and that works

**Comment by mypark** [comment]
Is there a way to get it to work on the currently published version on npm?

**Comment by mypark** [comment]
Looks like the version from npm is missing the line  

`onPress={() => this.props.onPressAvatar && this.props.onPressAvatar(this.props.currentMessage.user)}`

in Avatar.js

**Comment by devjaw** [comment]
i just add that line to avatar.js but it doesn't work 
`<GiftedChat
        messages={this.props.message.messages}
        onSend={this.onSend}
        user={{
          _id:this.props.user.userid,
          name:this.props.user.username,
          
        }}
        image ={this.props.user.image}
        renderAvatar={this.renderAvatar.bind(this)}
        onPressAvatar ={this.onPressAvatar.bind(this)}
        renderBubble={this.renderBubble}
      />`
`onPressAvatar(props){
    console.log(props)
    this.setState({modalInfo:{userId : props.user._id,username:props.user.name}})
    this.setState({showModal:true});
  }`
>

**Comment by Bundas** [comment]
Does the `onPressAvatar` method work in **0.1.3**?
