### ISSUE TITLE
How to recover <TextInput data when no internet ?

### ISSUE THREAD

**Issue by ronakamlani** [FaridSafi/react-native-gifted-chat#462]
#### Issue Description
Hello, Thank you so much for such beautiful product.

I am stuck with one of small problem, I can not figure out how can I keep textbox value once no internet ?

Please please please give me solution.

Thanks in advance,
Ronak Amlani,
Techacorn

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by brunocascio** [comment]
Since this Is not an issue of gifted chat, I'll close.

However, you should persist in some way your non-sent messages and try again at some point.
