### ISSUE TITLE
renderbubble does not show text on iphone

### ISSUE THREAD

**Issue by gurkirat1** [FaridSafi/react-native-gifted-chat#463]
#### Issue Description

Giftedchat renderbubble does not show text when app installed on iphone.
It works on simulator connected to xcode.

```
<GiftedChat
     
          messages={this.state.messages}
                onSend={this.onSend}
                loadEarlier={this.state.loadEarlier}
                onLoadEarlier={this.onLoadEarlier}
                isLoadingEarlier={this.state.isLoadingEarlier}
                user={{
          _id: this.props.user.id, // sent messages should have same user._id
          name: this.props.user.first_name,
          avatar: this.props.user.image_url,
        }}

                renderActions={this.renderCustomActions}
                renderBubble={this.renderBubble}
                renderCustomView={this.renderCustomView}
                renderFooter={this.renderFooter}
            />
```
#### Steps to Reproduce / Code Snippets

build app from xcode and install on iphone, then renderbubble does not show text when app installed on iphone

#### Expected Results

renderbubbles should show text messages.

#### Additional Information

* React Native version: 0.44
* react-native-gifted-chat version: 0.1.4
* Platform(s) (iOS, Android, or both?): iOs
![chat](https://cloud.githubusercontent.com/assets/11369272/26181562/18f6ea16-3b3f-11e7-93d0-d8c2bd20f2c0.jpg)

**Comment by varungupta85** [comment]
How does the `this.state.messages` look?

**Comment by nickkapoor** [comment]
The messages show up in the simulator but not on the device.

**Comment by nickkapoor** [comment]
If we modify the render method and take the text out of the ParsedText then it renders correctly on the device.  There is no issue on the simulator.  But for the device, had to make a change to the render method in MessageText.js

Wondering if the 0.44 version of RN is clashing with ParsedText for 0.44


  render() {
    return (
      <View style={[styles[this.props.position].container, this.props.containerStyle[this.props.position]]}>
        <ParsedText
          style={[styles[this.props.position].text, this.props.textStyle[this.props.position]]}
          parse={[
            {type: 'url', style: StyleSheet.flatten([styles[this.props.position].link, this.props.linkStyle[this.props.position]]), onPress: this.onUrlPress},
            {type: 'phone', style: StyleSheet.flatten([styles[this.props.position].link, this.props.linkStyle[this.props.position]]), onPress: this.onPhonePress},
            {type: 'email', style: StyleSheet.flatten([styles[this.props.position].link, this.props.linkStyle[this.props.position]]), onPress: this.onEmailPress},
          ]}
        >

        </ParsedText>
        <Text style={[styles[this.props.position].text, this.props.textStyle[this.props.position]]} >  {this.props.currentMessage.text} </Text>
      </View>
    );
  }
