### ISSUE TITLE
Unable to copy messages using the native copy interface on Android instead of the custom long press option

### ISSUE THREAD

**Issue by varungupta85** [FaridSafi/react-native-gifted-chat#465]
#### Issue Description
I am having a pretty strange issue. I want to allow user to copy messages using the native way instead of the bundled action sheet way. So, I removed the `onLongPress` handler and added the `selectable={true}` prop to the `MessageText`. It is working as expected in iOS. When I long press any text chat message, I get the native `Copy` popover. In case of Android, however, the text selection activity doesn't show up. The strange part is that if I were to show the inspector, select a text and then disable `Inspect` in the `Inspector`, the text selection activity shows up just fine. I have attached a screenshot that shows the text selection activity when the Inspector is visible.

![screen shot 2017-05-23 at 3 22 14 pm](https://cloud.githubusercontent.com/assets/7475133/26348885/dc6c1116-3fcb-11e7-9930-a606ac38395d.png)

#### Steps to Reproduce / Code Snippets
1. Disable the `onLongPress` for the bubble
2. Add `selectable={true}` to the test message props
3. Observe that the text selection activity doesn't show up
4. Toggle the inspector, select a box and then disable `Inspect` by clicking on it in the Inspector
5. Long press or double click on any text message and observe that the text selection activity shows up

#### Expected Results

View the native copy text interface for Android

#### Additional Information

* React Native version: 0.42
* react-native-gifted-chat version: Own fork with latest code
* Platform(s) (iOS, Android, or both?): Android

**Comment by varungupta85** [comment]
Hi, has anybody else using this package tried to use the native interface to copy messages in Android. I feel that having a custom interface to copy messages just in the chat screen is not a good UX as it separates it from the rest of the app unless a user uses similar interface elsewhere in the app as well and it will anyway be a digression from what people are used-to to copy text in an app.

**Comment by xvonabur** [comment]
+1 with the same problem. @varungupta85 do you manage to solve it?

**Comment by xvonabur** [comment]
I've managed to solve it by modifying `Bubble` component. You can just remove `TouchableWithoutFeedback` in `render` method and override `onLongPress` (maybe not required). I prefer native copy/paste controls, so it was enough for me.

**Comment by xvonabur** [comment]
1 year later and still no progress...

**Comment by xvonabur** [comment]
I don't think it's fixed on latest version.

**Comment by varungupta85** [comment]
@xvonabur I don't know what is wrong with the text selection. So, I haven't been able to fix it. The issue still exists.

**Comment by Gardeniaxch** [comment]
请问怎样使用onLongPress方法弹出一个Popover？

**Comment by curest0x1021** [comment]
This issue hasn't been fixed yet. I upgraded the React Native version from 0.58.5 to 0.61.2 and got this issue on Android.
Please reopen this issue and fix it as soon as possible.

**Comment by usmahm** [comment]
@varungupta85 Please has this been fixed?

Or do you know how I can achieve this now, I'm having issues copying text when it's a mail

**Comment by hellohejinyu** [comment]
You need to fork this repository and modify the source code.

```tsx
// MessageText.tsx

<ParsedText
    style={[
      styles[position].text,
      textStyle && textStyle[position],
      customTextStyle,
    ]}
    parse={[
      ...parsePatterns!(linkStyle as TextStyle),
      { type: 'url', style: linkStyle, onPress: onUrlPress },
      { type: 'phone', style: linkStyle, onPress: onPhonePress },
      { type: 'email', style: linkStyle, onPress: onEmailPress },
    ]}
    childrenProps={{ ...textProps }}
    {...parsedTextProps} // add parsedTextProps, it's type is Omit<ParsedTextProps, 'style' | 'parse' | 'childrenProps'>
  >
    {currentMessage!.text}
</ParsedText>
```

then you can use it like below 

```tsx
<GiftedChat
    onLongPress={() => {}}
    isTyping={askRequest.loading}
    renderBubble={(props) => {
      // Disable external touch events to avoid conflicts
      return <Bubble {...props} touchableProps={{ disabled: true }} />
    }}
    renderMessageText={(props) => {
      return (
       // Add selectable attribute to inner text
        <MessageText {...props} parsedTextProps={{ selectable: true }} />
      )
    }}
/>
```
