### ISSUE TITLE
Custom action when clicking url

### ISSUE THREAD

**Issue by kevinNgws** [FaridSafi/react-native-gifted-chat#466]
Is it possible to have a call back when clicking a url in the message so that it will not trigger to launch the url page in an external phone browser? I want to launch the url page within the app.

The current MessageText object does not have a prop to do that:
`onUrlPress(url) {
    Linking.openURL(url);
  }`

Please advise. Thank you!

**Comment by varungupta85** [comment]
You can pass in your own `renderMessageText` that renders something similar to what `MessageText` renders right now but with the modified url handler.

**Comment by kevinNgws** [comment]
ahh... got it! thanks for pointing me to the right direction!

**Comment by Mohsinraza880** [comment]
I want open message link inside app.

**Comment by IrfanKMT** [comment]
[react-native-gifted-chat+2.1.0.patch](https://github.com/FaridSafi/react-native-gifted-chat/files/11663325/react-native-gifted-chat%2B2.1.0.patch)
