### ISSUE TITLE
Couldn't find a React Native project

### ISSUE THREAD

**Issue by ketankulkarni** [FaridSafi/react-native-gifted-chat#470]
#### following steps had been followed to run gifted chat  
1 git clone https://github.com/FaridSafi/react-native-gifted-chat
2 cd react-native-gifted-chat/example
3 npm install
4 react-native run-ios

actual output -
Couldn't find a React Native project
Make sure that your current working root (or its ancestor) contains a "node_modules" directory with react-native installed, or a .buckconfig file with a "[react-native]" section that has a "server" key.

* React Native version: [~15.4.0-rc.4]
* Platform(s) : [Android]

**Comment by kevintseng** [comment]
Same here.

**Comment by kevintseng** [comment]
@cooperka I have the same problem.

**Comment by cooperka** [comment]
Hmm, I cleared out everything and tried fresh on master with these same steps and it all works for me. I'll need more info to be able to debug this, unfortunately.

If anyone else has this issue or if either of you could provide more information that would be helpful. I'd also recommend searching for this error online to see if anyone else has it. You're not running the `sync` script, are you? That shouldn't be needed.

**Comment by cooperka** [comment]
I just added c2e8df36dd1572601720e8e20966e3c164d4645b to fix iOS builds in general, but it doesn't seem relevant to the error you describe here. I recommend clearing out all build caches, watchman, etc. and trying again. Here are some commands to clean things up:

```console
git pull
rm -rf node_modules
rm -rf example/node_modules
rm -rf example/ios && git checkout HEAD example/ios
watchman watch-del-all
yarn cache clean
yarn install
yarn start -- --reset-cache
```

**Comment by brunocascio** [comment]
@ketankulkarni Did you resolve this issue?

**Comment by ketankulkarni** [comment]
@brunocascio have seen this https://www.youtube.com/watch?v=VTnFDc3IFag

**Comment by ketankulkarni** [comment]
@brunocascio was it helpful??? plz write problem with solution in detail
