### ISSUE TITLE
message show too slow when I open a chat at the first time

### ISSUE THREAD

**Issue by cielu** [FaridSafi/react-native-gifted-chat#473]
#### Issue Description

when I open a chat page the message show too slow , and if there are many messages .

the messages show even more slow

#### Steps to Reproduce / Code Snippets

go into a chat stack

#### Additional Information

* React Native version: [0.44.2]
* react-native-gifted-chat version: ^0.1.4
* Platform(s) (iOS, Android, or both?): both

**Comment by TGNC** [comment]
Me too.

**Comment by luco** [comment]
+1 on this.

**Comment by brunocascio** [comment]
Try the latest versión instead of 0.1.4.

**Comment by aalkz** [comment]
I'm having issues with this too, I wonder if it's the same as https://github.com/FaridSafi/react-native-gifted-chat/issues/606, I can see the response from the server immediately in the logs so I don't think it's a network issue, but the component takes like 4 seconds to load if it has more than 20 messages or so. In a new conversation or with only 2 messages it still takes time but it's not so noticeable.
