### ISSUE TITLE
Slow performance on update messages

### ISSUE THREAD

**Issue by kesha-antonov** [FaridSafi/react-native-gifted-chat#476]
Hello everyone and @kfiroo @FaridSafi 

#### Issue Description

Use case:

Every message has an additional info. It shows up when user taps any message (Bubble).
Other "opened" messages should be "closed".
Hence I update all messages with ```map``` (all unchanged messages return the same).

It works fine with 10-20 messages. But with 40-70 (not so many, right?) it becomes slow. It takes 3-4 seconds in dev-mode to show additional info of message.

Maybe ```FlatList``` will resolve this issue? Or some clever ```shouldComponentUpdate``` ?

How to pass new ```messages``` and make the GiftedChat render them FAST?

#### Additional Information

* React Native version: 0.45.rc-2
* react-native-gifted-chat version: latest
* Platforms: both

**Comment by 3210jr** [comment]
+1

**Comment by pewh** [comment]
+1

**Comment by verzil** [comment]
+1

**Comment by brunocascio** [comment]
Here, an updated issue: https://github.com/FaridSafi/react-native-gifted-chat/issues/411

**Comment by redwind** [comment]
i've removed prepareMessages and pass data direct to ListView (FlatList). Cause prepareMessage called every time new message update, it cause slow performance. 
previousMessage, nextMessage data pass to props in renderRow function instead in prepareMessage
