### ISSUE TITLE
Change deprecated View.propTypes to ViewPropTypes

### ISSUE THREAD

**Issue by mgustin12** [FaridSafi/react-native-gifted-chat#477]
#### Issue Description
When building project I get this warning:
Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.

#### Steps to Reproduce / Code Snippets

Build project

#### Expected Results

Expect to not see warning about View.propTypes

#### Additional Information

* React Native version: 0.44
* react-native-gifted-chat version: 0.1.4
* Platform(s) (iOS, Android, or both?): both

**Comment by cooperka** [comment]
Fixed via https://github.com/FaridSafi/react-native-gifted-chat/pull/478.
