### ISSUE TITLE
custom renderSend not clear input after send

### ISSUE THREAD

**Issue by itelo** [FaridSafi/react-native-gifted-chat#480]
#### Issue Description

I want to use a custom send button, after reading the documentation, I discover renderSend, it works nice, but when i press SEND the message is sent but not clear the input text. 

#### Steps to Reproduce / Code Snippets

main component
```js
<GiftedChat
  renderSend={this.renderSend}
  onSend={this.Send}
  messages={this.state.messages}
  user={this.props.user}
/>
```
custom send button
```js
renderSend(props) {
  return (
    <TouchableOpacity onPress={() => props.onSend({text: props.text})}>
      <Text>SEND</Text>
    </TouchableOpacity>
  );
}
```

custom send methon
```js
Send(messages) {
  messages.map(message => {
    this.socket.emit('chatMessage', message);
  });
}
```

#### Additional Information

* React Native version: 0.44.2
* react-native-gifted-chat version: 0.1.4
* Platform(s) (iOS, Android, or both?): both

**Comment by peteroid** [comment]
seems adding second argument as `true` could fix this issue, like `onSend({ text: props.text }, true)`

ref: https://github.com/FaridSafi/react-native-gifted-chat/blob/270de9b5f52f692220f3f953bba96ed5f7e22531/src/Send.js#L22

**Comment by shekharskamble** [comment]
@peteroid I tried addind second argument in send.js but doesnt work :(

**Comment by peteroid** [comment]
@shekharskamble how do you implement the `onSend` ? For my case, I need to render my own send button, so I do the followings.

```jsx
  _onSend = (props) => {
    props.onSend({ text: props.text.trim() }, true)
  }

  renderSend = (props) => {
    return (
      <Component
        onPress={() => this._onSend(props)}
      />
    )
  }
```
