### ISSUE TITLE
Scroll to top on component mount.

### ISSUE THREAD

**Issue by karthiknrbt** [FaridSafi/react-native-gifted-chat#483]
#### Issue Description

My objective is to load the chat history from the conversation start on component mount and no necessity for invertible scroll.

#### Steps to Reproduce / Code Snippets

Scroll up.

#### Expected Results
invertible scroll as a prop.

#### Additional Information

* React Native version:0.41
* react-native-gifted-chat version:0.1.3
* Platform(s) (iOS, Android, or both?): both

**Comment by brzonsea** [comment]
Did anyone solve this yet? I am also trying to achieve the same thing. 
`
listViewProps={{
          contentContainerStyle: { 'flexGrow': 1, 'justifyContent': 'flex-end' }
 }}
`
I tried adding the above prop to GiftedChat but it doesn't seem to start from the top.
