### ISSUE TITLE
onChange function not working,  When use 0.1.3 but its work fine 0.0.10

### ISSUE THREAD

**Issue by ycpatel813** [FaridSafi/react-native-gifted-chat#485]
#### Issue Description
Hello, I found this is a very important library but when I use 0.0.10 on change function work perfectly. I found some misbehavior when I use 0.1.3 version. I have to use 0.1.3 for lightbox support.

#### Steps to Reproduce / Code Snippets
First install, 0.0.10 version and create custom renderer
     

    renderInputToolbar(props) {
        return (
            <View style={styles.mainViewRow}>
                <TouchableWithoutFeedback
                    onPress={this.selectPhotoTapped.bind(this)}>
                    <View style={{flex:1}}>
                        <Text><Icon name='camera' size={40}/></Text>
                    </View>
                </TouchableWithoutFeedback>

                <View
                    style={{flex:9,flexDirection:'row',margin:1, alignItems:'center', justifyContent:'center', borderWidth:1, borderColor:'#888', borderRadius:20, backgroundColor:'#fff'}}>
                    {this.renderComposer(props)}
                    {this.renderSend(props)}
                </View>
            </View>
        );
    };

    renderComposer(props) {
        return (
            <TextInput
                underlineColorAndroid='transparent'
                placeholder={'Type a message...'}
                value={props.text}
                onChange = {(e)=>props.onChange(e)}
                multiline={true}
                style={{backgroundColor:'transparent',flex:9}}
            />

        )
    };

#### Expected Results

It does not work when I use 0.1.3.
Sorry, but I can't understand why this code added in composer rendered.
 
        onChange(e) {
                   const contentSize = e.nativeEvent.contentSize;
                   if (!this.contentSize) {
                            this.contentSize = contentSize;
                            this.props.onInputSizeChanged(this.contentSize);
                    } 
                   else if (this.contentSize.width !== contentSize.width || this.contentSize.height !== contentSize.height) {
                  this.contentSize = contentSize;
                  this.props.onInputSizeChanged(this.contentSize);
                 }
       }
       onChangeText(text) {
               this.props.onTextChanged(text);
      }

 
#### Additional Information

* React Native version: 0.42.3
* react-native-gifted-chat version: 0.0.10, 0.1.3
* Platform(s) (iOS, Android, or both?): both

**Comment by controversialUser** [comment]
check if you have `this.setIsTypingDisabled(false);` in onKeyboardDidShow, onKeyboardDidHide, onKeyboardWillHide, onKeyboardWillShow in GiftedChat.js

**Comment by devjaw** [comment]
replace it with onContentSizeChange

**Comment by cooperka** [comment]
Please see https://github.com/FaridSafi/react-native-gifted-chat/issues/501. You may need to upgrade your React Native version to get it working; this will be fixed in an upcoming commit.
