### ISSUE TITLE
Emoji integration

### ISSUE THREAD

**Issue by volkovpishet** [FaridSafi/react-native-gifted-chat#490]
#### Issue Description
First of all, thank you for this great component. It's very handy.
It's not really an issue, but.. I am trying to integrate emojis in gifted chat and would really appreciate any help to do that or ideas. May be there is some good practice or so? Candidate for integration is https://www.npmjs.com/package/react-native-emoticons

#### Expected Results
Emoji picker is integrated in giftedchat input and and chosen smiles go right after text pointer.

#### Additional Information
* React Native version: 0.44
* react-native-gifted-chat version: 0.1.4
* Platform(s) (iOS, Android, or both?): both

**Comment by jjdp** [comment]
you could try https://github.com/makemoji/Makemoji-React-Native
