### ISSUE TITLE
Change background bubble color 

### ISSUE THREAD

**Issue by Sh1n1x** [FaridSafi/react-native-gifted-chat#493]
hi i have tried to change background (default blue) of the bubble but i don't now how make that. I have tried on >
`    renderBubble(props) {
      return (
        <Bubble
          {...props}
          textStyle={{
            right: {
                color: 'white',
            }
          }}
         />
      );
    }`

**Comment by varungupta85** [comment]
Specify the color in `wrapperStyle` instead of `textStyle`.

```javascript
renderBubble(props) { return ( <Bubble {...props} 
      wrapperStyle={{
          left: {
            backgroundColor: 'white',
          },
          right: {
            backgroundColor: '#ECEFF1'
          }
        }} />
```

**Comment by xero88** [comment]
@varungupta85 thx, it's working, but not for the borders
