### ISSUE TITLE
Will add audio support?

### ISSUE THREAD

**Issue by wayne1203** [FaridSafi/react-native-gifted-chat#494]
Will it add support for audio message? (Or is it supported?)
Otherwise, how can I add a layout for new type of message? That's mean how can I create support for audio message?

Thanks.

**Comment by cooperka** [comment]
Hi @wayne1203, you're welcome to override [`renderMessage`](https://github.com/FaridSafi/react-native-gifted-chat#props) to create your own message types.

For example, you can check for the type of message and either return your own custom view, or fall back to the default `<Message {...messageProps} />` if it's not an audio message.

**Comment by rahulraman** [comment]
Can we use firebase to store audio messages.

I can check above you have mentioned render option to support audio message in the view using gifted chat.

Thanks
