### ISSUE TITLE
Avatar for user is not working

### ISSUE THREAD

**Issue by kwnccc** [FaridSafi/react-native-gifted-chat#495]
When passing down messages based on Message Object defined in the documentation, avatar cannot be set for user. The same message object works fine for bot avatar, but I'd like to be able to add an avatar also for the user.

Example bot message object: 
```
{
  _id: generateMessageID(),
  text: talk.response,
  createdAt: new Date(),
  user: {
    _id: 2,
    name: botName,
    avatar: botAvatar
  },
  metadata: talk,
}
```

Example bot message object: 
```
{
  _id: generateMessageID(),
  text: data.response_text,
  createdAt: new Date(),
  user: {
    _id: 1,
    name: userName,
    avatar: userAvatar
  },
  metadata: data
}
```

* React Native version: 0.45.1
* react-native-gifted-chat version: 0.1.4

**Comment by kwnccc** [comment]
After a fast digging into the code I assume this (extra?) check is causing second avatar not to appear. Is this check happening on purpose? Git history shows that it mostly is because of some backwards compatibility. Is this still the case? If not I can open a PR about it.

https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/Message.js#L44

**Comment by jeaye** [comment]
I'd also like to show an avatar for the user; @kwnccc did you end up making a change which you could turn into a PR? Thanks!

**Comment by kwnccc** [comment]
@jeaye not yet, I was hoping for a response from maintainers, in case my assumption is not correct. I can open a PR and further discuss the proposed change there, I'm not sure how it will impact the rest of the implementation.

**Comment by cooperka** [comment]
Hi @kwnccc, please try again on latest. This was likely fixed in https://github.com/FaridSafi/react-native-gifted-chat/pull/479.

**Comment by cooperka** [comment]
Closing for now, please let me know if you're still having issues.

**Comment by kwnccc** [comment]
@cooperka after a trying out the latest version `0.2.2` this issue doesn't seems resolved unfortunately. I'm trying with 2 different ways, either initialising user object on GiftedChat component with an avatar or adding it as a parameter to the messages user object, but none of this worked. 

To better illustrate the needed result I'm attaching 2 screenshots, the first one with the current behaviour, and the second with the needed one.
[](http://imgur.com/a/GIgTQ)

**Comment by cooperka** [comment]
Ah, I misunderstood the original issue, I see what you're trying to do now. I think a new prop `showUserAvatar` would be ideal here. It should default to `false` (the current behavior) but if set to `true`, you would see the behavior you're looking for.

**Comment by cooperka** [comment]
Scratch that ^ I think you're right that this is just a bug. It makes intuitive sense that if you provide an avatar for the current user, it should be rendered.

**Comment by cooperka** [comment]
Fixed in https://github.com/FaridSafi/react-native-gifted-chat/pull/511

**Comment by FarruxNosirov** [comment]
<img width="397" alt="Screenshot 2024-04-12 at 17 15 16" src="https://github.com/FaridSafi/react-native-gifted-chat/assets/98707246/4cba806b-dc91-40bc-8a8d-3f7c33ec3c13">
