### ISSUE TITLE
on iOS, can't type text for several seconds, right after sending a message

### ISSUE THREAD

**Issue by wenbinf** [FaridSafi/react-native-gifted-chat#497]
### Issue Description

on iOS, can't type text for several seconds, right after sending a message

![jul-07-2017 14-08-09](https://user-images.githubusercontent.com/1719237/27977015-be82f758-631d-11e7-82af-11de369fcb58.gif)

#### Steps to Reproduce / Code Snippets

0. on iOS
1. Type something and then send.
2. ==> Can't type anything for several seconds.
3. Able to type after several seconds

#### Expected Results

Able to type texts right after sending a message

#### Additional Information

* React Native version: 0.45.1
* react-native-gifted-chat version: 0.14
* Platform(s) (iOS, Android, or both?): iOS 10 & iOS 11

**Comment by devjaw** [comment]
try to disable debug mode

**Comment by wenbinf** [comment]
It happens in production build as well. I suspect that it's because there are some compute-intensive events happening after sending messages. I'll dig more

**Comment by brunocascio** [comment]
Hi @wenbinf 

> Native TextInput(Dddddddddddd) is 12 events ahead of JS - try to make your JS faster.

That's is a react-native warning when you call `setState` a lot of times, for example, writing faster in an input.

Feel free to reopen if it does not work.

**Comment by lutchobandeira** [comment]
Hey @wenbinf, I am getting the same behavior. I was wondering how did you solve this issue, it can help me to save a lot of time.

**Comment by tehwayne** [comment]
I have the same issue using the simulator, however it seems more performant on actual release, however something with onSend seems to be slowing down?

**Comment by meridj** [comment]
Hi,
i got same issue.
Could someone solve this ?

**Comment by hwatanabe9393** [comment]
did anyone solve this issue?

**Comment by henokweldemicael** [comment]
Save issue. Any update?

**Comment by abdi4** [comment]
This issue still exists in newer versions of the library

**Comment by therbta** [comment]
still same issues.
