### ISSUE TITLE
Is there any way to render a custom view when there are no messages?

### ISSUE THREAD

**Issue by lsps9150414** [FaridSafi/react-native-gifted-chat#499]
### What I want to achieve

Display a custom view for new conversations (like the left image).
![image](https://user-images.githubusercontent.com/5022617/27986205-a83e7938-642e-11e7-8518-adfe7bc8ed04.png)

### What I've tried

I tried to achieve that by adding an overlay on top of the `GiftedChat` component but it will also cover the touchable stuffs in the composer area. I know I can use `bottom: 44` to avoid the area but then I will need to manage the absolute value when the keyboard opens which is not ideal.

**Comment by zkrige** [comment]
something like 

```    if this.state.messages === undefined {
       return (
       	<MyCustomView>
       )
    } else {
      return <GiftedChat....>
    }```

**Comment by paulohenriquesg** [comment]
I'm thinking about something similar. But I'm considering the approach of 'facking' one message of an specific type that would be replaced as soon as a real message arrives. 

Did you got some solution for this?

**Comment by lsps9150414** [comment]
After digging into the code I found I can use `renderChatFooter` to do it with the following style given to the component you rendered with it.

```
newConversationOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
```

**Comment by brunocascio** [comment]
I mark this issue as `enhancement`.
