### ISSUE TITLE
Composer onChange not working with react-native 0.46.1

### ISSUE THREAD

**Issue by RobertWSaunders** [FaridSafi/react-native-gifted-chat#501]
#### Issue Description

In react-native version 0.46.1 the GiftedChat composer onChange method no longer works and results in an error. 

`e.nativeEvent.contentSize` results in undefined, it appears that contentSize is no longer a attribute of `nativeEvent`.

```
onChange(e) {
    const contentSize = e.nativeEvent.contentSize;
    if (!this.contentSize) {
      this.contentSize = contentSize;
      this.props.onInputSizeChanged(this.contentSize);
    } else if (this.contentSize.width !== contentSize.width || this.contentSize.height !== contentSize.height) {
      this.contentSize = contentSize;
      this.props.onInputSizeChanged(this.contentSize);
    }
  }
```

* React Native version: 0.46.1
* react-native-gifted-chat version: latest
* Platform(s) (iOS, Android, or both?): Both

**Comment by unexge** [comment]
using `onContentSizeChange` instead of `onChange` should fix it.

https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/Composer.js#L31

**Comment by cooperka** [comment]
Fixed in https://github.com/FaridSafi/react-native-gifted-chat/pull/500.
