### ISSUE TITLE
App crashes upon typing on text-input, "Cannot read property 'height' of undefined"

### ISSUE THREAD

**Issue by purrado** [FaridSafi/react-native-gifted-chat#503]
#### Issue Description

As soon as I type something on `react-native-gifted-chat`'s text-input, the app crashes and this error is thrown:

```
Cannot read property 'height' of undefined

GiftedChat.onInputSizeChanged
    GiftedChat.js:353:95
Composer.onChange
    Composer.js:13:17
Object.onChange
    Composer.js:31:30
Object._onChange
    TextInput.js:785:38
Object.invokeGuardedCallback
    ReactNativeStack-dev.js:134:13
Object.invokeGuardedCallback
    ReactNativeStack-dev.js:170:37
Object.invokeGuardedCallbackAndCatchFirstError
    ReactNativeStack-dev.js:173:58
executeDispatch
    ReactNativeStack-dev.js:206:88
Object.executeDispatchesInOrder
    ReactNativeStack-dev.js:212:263
executeDispatchesAndRelease
    ReactNativeStack-dev.js:276:33
```

Adding the `messages` and/or the `onSend` props doesn't make a difference.

#### Steps to Reproduce / Code Snippets

```js
import React from 'react'
import GiftedChat from 'react-native-gifted-chat'

const Component = () => (
  <View style={{ flex: 1 }}>
    <GiftedChat />
  </View>
)
```

#### Expected Results

Should be able to type in input on the included text-input

#### Additional Information

* React Native version: 0.46.1
* react-native-gifted-chat version: 0.1.5
* Platform(s) (iOS, Android, or both?): Both

**Comment by devjaw** [comment]
this problem was solved ! wait for the next version [https://github.com/FaridSafi/react-native-gifted-chat/pull/500](https://github.com/FaridSafi/react-native-gifted-chat/pull/500)

**Comment by purrado** [comment]
Yeah. Snuffed around and saw that this is related to Issue #501, and seems to be fixed in PR #500. Hopefully the next version gets published soon. Will close the issue for now. Thanks a lot! @devjaw

**Comment by sivaganga** [comment]
change this version 
"react": "16.0.0-alpha.6",
"react-native": "0.44.0",
 "react-native-gifted-chat": "^0.1.4",

**Comment by markmiller21** [comment]
Are there any plans to fix this?  I am currently on 

"expo": "^20.0.0",
"react-native-gifted-chat": "^0.1.4",

expo 20 yeilds the following React / React Native Versions:
"react-native": "0.47.0",
"react": "16.0.0-alpha.12"

I'd rather not downgrade versions if possible
