### ISSUE TITLE
How to show avatars in every messages?

### ISSUE THREAD

**Issue by IotFrontEnd** [FaridSafi/react-native-gifted-chat#507]
Hi, I want to render avatars in every messages. Any ideas?

**Comment by devjaw** [comment]
use `renderActions ` function

**Comment by Mr7Cat** [comment]
See Message.js  function "isSameUser", make sure return false.

**Comment by verzil** [comment]
does that mean we have to override the source code within our node_modules ?  i'd prefer not having to do that, is there a way to do this without actually override the source?

**Comment by jzhw0130** [comment]
Need the feature

**Comment by jzhw0130** [comment]
@IotFrontEnd @verzil 
A small magic trick to use(Promise every message have a different user id : _id: user.id+ uuid()):
```javascript
        _id: messageID,
        createdAt: new Date(),
        user: {
          _id: user.id+ uuid(),
          name: user.name,
          avatar:  'http://www.hidoctor.ir/wp-content/uploads/2014/02/Model-lebas-parastar-24.jpg',
        },
    }
```
