### ISSUE TITLE
How to add Camera button

### ISSUE THREAD

**Issue by riteshvish** [FaridSafi/react-native-gifted-chat#510]
I want to use camera to send photos like other chat app does.

* React Native version: 0.39.2
* react-native-gifted-chat version: 0.0.10
* Platform(s) (iOS, Android, or both?): both

**Comment by riteshvish** [comment]
after a little  workaround, I found a solution;

Thanks @FaridSafi for a great module

**Comment by barjas** [comment]
please share your solution so others can get the benfits

**Comment by riteshvish** [comment]
Added 3rd option in CustomActions
const options = ['Choose From Library', 'Send Location',**'Camera'** ,'Cancel'];

I used another module.
var ImagePicker = require('react-native-image-picker');


added 3rd Case in Switch statement
case  2:
            ImagePicker.launchCamera({title:"Please click photo"}, (response)  => {           
            this.props.onSend([{
              image: response.uri,
            }]);
            this.setImages([]);
          });
 break;
**ImagePicker.launchCamera** with not work in simulator

**Comment by sachinsinghh** [comment]
@riteshvish  How did you call "CustomActions.js" from "App.js" file. Can you show your "App.js" file?

**Comment by riteshvish** [comment]
@sachinsinghh 
import CustomActions from './chat/CustomActions'; (your file path);
  renderCustomActions(props) {
    return (
      <CustomActions
        {...props}
      />
    );
  }

<GiftedChat
...
        renderActions={this.renderCustomActions}
...
      />

**Comment by sachinsinghh** [comment]
@riteshvish Thanx
