### ISSUE TITLE
How to update existing message?

### ISSUE THREAD

**Issue by wayne1203** [FaridSafi/react-native-gifted-chat#513]
#### Issue Description
The view not change when using setState to update messages
I saw that "render()" in view will be called every times I update with setState but not constructor() so the view doesn't get the new props.
How can I update the message?

#### Steps to Reproduce / Code Snippets

Update messages with setState

#### Expected Results

Message will updated

#### Additional Information

* React Native version: 0.46
* react-native-gifted-chat version: 0.2.2
* Platform(s) (iOS, Android, or both?): iOS

**Comment by vgorte** [comment]
Can you provide us with a little bit of code? 

I would not advice you to do this but you could force a rerender of your component with 
`this.forceUpdate()`

But in general you should use the state to rerender components.

**Comment by wayne1203** [comment]
I found the solution, just add "componentWillReceiveProps" to update the props in custom view.
Render will run every times when I update "messages []" but props are not update. So I do this to update the props in custom view.
But I don't know is it a good solution or not. 
I tried using forceUpdate, but I won't work due to props are not update to date.
Maybe I close the issue first, please tell me if there have better solution.

**Comment by vgorte** [comment]
I think your solution is reasonable. I think you can leave it like that.  👍
