### ISSUE TITLE
Cache Avatar Images [enhancement]

### ISSUE THREAD

**Issue by nonotest** [FaridSafi/react-native-gifted-chat#514]
#### Issue Description

It would make sense that the image avatars are cached by default with something like
`https://github.com/kfiroo/react-native-cached-image`

In most used case they are displayed super often..

**Comment by bexoss** [comment]
+1

**Comment by nonotest** [comment]
@cooperka I am happy to submit a PR with what I have later if you want.
I think caching of images is also beneficial in the message image bit.

Let me know otherwise ill just close this

**Comment by cooperka** [comment]
Hi @nonotest, PRs are always welcome! However, it should be done in a way that's **optional** so people aren't required to `link` this library unless they specifically want that functionality. I'm not sure the added complexity is worth it. I'm willing to consider it though.

**Comment by pvsong** [comment]
+1

**Comment by tjkang** [comment]
+1

**Comment by gabrieldonadel** [comment]
+1
