### ISSUE TITLE
View doesn't show until I scroll

### ISSUE THREAD

**Issue by luco** [FaridSafi/react-native-gifted-chat#519]
#### Issue Description

When I enter my view, the `gifted-chat` view doesn't show until I scroll it. But once I scroll, then it shows and appear correctly.

#### Steps to Reproduce / Code Snippets

I'm using the example code provided. Also, I'm using `react-native-router-flux`.

#### Additional Information

* React Native version: `0.44.3`
* react-native-gifted-chat version: `0.2.5`
* Platform(s) (iOS, Android, or both?): iOS

**Comment by Mindaugas-Jacionis** [comment]
I am having the same issue, except I am using React Native 0.46.3

**Comment by luco** [comment]
@FaridSafi Any tips?

**Comment by brunocascio** [comment]
@luco, Could you try with the latest version? (v0.2.8)

**Comment by tvmaasjazz** [comment]
Same issue with React Native 0.49.3 and Gifted Chat 0.2.9

**Comment by diegocouto** [comment]
I don't think it is an issue with `react-native-gifted-chat` itself, but a known problem on react-native ([as you can see here](https://github.com/facebook/react-native/issues/1831)). It seems that a fix is available on RN v0.50.

I'd recommend you to set `lazy` as true on your tabs and this is going to work as expected if you are not planning to upgrade right now.
