### ISSUE TITLE
Text and Call actions are turned around

### ISSUE THREAD

**Issue by urska19** [FaridSafi/react-native-gifted-chat#526]
#### Issue Description
It looks like Text and Call actions, when pressing the telephone number in the message, are turned around: 
- If you press Text, the option to call the number shows up
- If you press Call, the option to send the message to the the number shows up

#### Additional Information

* React Native version: 0.44.0
* react-native-gifted-chat version: 0.2.5
* Platform(s) (iOS, Android, or both?): both

**Comment by urska19** [comment]
I see there is already a pull request  #521 about this issue.

**Comment by cooperka** [comment]
Merged https://github.com/FaridSafi/react-native-gifted-chat/pull/521, thanks for the report!
