### ISSUE TITLE
Different Uploading options

### ISSUE THREAD

**Issue by amitbravo** [FaridSafi/react-native-gifted-chat#530]
#### Issue Description

I am using react-native-crop-picker , react-native-document-picker, react-native-file-picker to upload images, direct camera photos, documents(cloud and local) on both android and iphone devices. can I use them by changing action sheet options , they are different for iphone and android plus, I need a switch near send button to allow if users can allow comments or not for a particular chat/news , is this possible ?

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by abeltje1** [comment]
Yes, it's quite easy actually. You can use renderActions to render all your needed custom actions. There's an example of it in the example code, but for your actionsheet example, you could simply do something like:

```
<GiftedChat renderActions={this.renderActions}/> // and other props
  
 renderActions() {
    return(
         <TouchableOpacity onPress={this.showActionSheet)}>
            <Image style={{width:22, height:22, resizeMode:'contain', marginLeft:9, marginBottom:12}} 
                   source={require('../../../../img/chat_camera.png')}/>
         </TouchableOpacity>)
  }

```
this is my code to render a camera upload button. As you see you can just call showActionSheet in the onPress and voilà.

Good luck!

**Comment by Pushpi1992** [comment]
after write this nothing is happing

**Comment by Pushpi1992** [comment]
no any action performed

**Comment by chunkydonut21** [comment]
@Pushpi1992  you also have to bind the function in constructor for it to work.

**Comment by Singh-Aish** [comment]
I have defined it in constructor still no action is performed.
