### ISSUE TITLE
Android cutting off bottom half of characters like 'g' or 'y' if 3+ lines

### ISSUE THREAD

**Issue by therealchuckliu** [FaridSafi/react-native-gifted-chat#531]
#### Issue Description

<img width="307" alt="screenshot 2017-08-04 09 11 01" src="https://user-images.githubusercontent.com/5594307/28970052-0e9a7b52-78f5-11e7-8cc3-65a1e7576705.png">

As you can see from the image characters with a loop that cross below the line like g or y are cut off from text input

#### Steps to Reproduce / Code Snippets

Write text that's at least 3 lines long on Android. Adding some offset in onInputSizeChanged fixes it but wondering if there's something a little better than this hack

#### Expected Results

You see the full character

#### Additional Information

* React Native version: 0.45
* react-native-gifted-chat version: 0.2.5
* Platform(s) (iOS, Android, or both?): Android

**Comment by tmadeira** [comment]
Same problem here. Have you found any other solution?

[Also, if you type 5+ lines the input field stop expanding (as reported in #553)]

**Comment by brunocascio** [comment]
Duplicated issue: https://github.com/FaridSafi/react-native-gifted-chat/issues/553 (same behavior)

**Comment by RayyanNafees** [comment]
Despacito
gas pass kari thi abhi to
hme pyar kr lo kbhi to
redi pe chal ke khayenge papito
