### ISSUE TITLE
Icon as Avatar?

### ISSUE THREAD

**Issue by llanginger** [FaridSafi/react-native-gifted-chat#533]
#### Issue Description

I would like to use an icon (ideally a react component from `react-native-vector-icons`) as my chat bot's avatar, I am unsure from the docs if this is supported behavior.

If this is "easy", I would appreciate being pointed in the right direction. If it is not "easy" I'll find an image that'll work for now and then maybe poke at the source in my spare time :)

Any help would be greatly appreciated!

#### Additional Information

* React Native version: 0.44.2 (at the moment)
* react-native-gifted-chat version: 0.2.5
* Platform(s) (iOS, Android, or both?): iOS for now but both eventually

**Comment by tmc** [comment]
See https://github.com/FaridSafi/react-native-gifted-chat/blob/b6e98c40b8274ec1804168c5d27006291e776b33/src/GiftedAvatar.js#L49
