### ISSUE TITLE
How make send button with icon?

### ISSUE THREAD

**Issue by lossen** [FaridSafi/react-native-gifted-chat#535]
Hello 
How can I make send button with icon?

There is pull request https://github.com/FaridSafi/react-native-gifted-chat/pull/487 that resolve my problem, but its not merged yet :(

**Comment by varungupta85** [comment]
You can define a `renderSend` method and set it in the `GiftedChat` component as shown below

```javascript
renderSend = (sendProps) => {
    if (sendProps.text.trim().length > 0) {
      return (
        <TouchableOpacity>
          <Image source={require('../../img/ic_send.png')} />
        </TouchableOpacity>
      );
    }
    return null;
  }

<GiftedChat renderSend={this.renderSend} />
```

This is just to give you an idea on how to set a custom icon for the send. You will probably need to add some styling and an `onPress` handler.

**Comment by cooperka** [comment]
@lossen you can do this now via https://github.com/FaridSafi/react-native-gifted-chat/pull/487 :)
