### ISSUE TITLE
[Question] How to remove TextInput?

### ISSUE THREAD

**Issue by SelfnessAid** [FaridSafi/react-native-gifted-chat#538]
How can I remove or hide TextInput ?
[
![image](https://user-images.githubusercontent.com/20356023/29287549-839dbe68-813e-11e7-9991-94f2cb9598e0.png)
](url)

**Comment by SelfnessAid** [comment]
find solution.
`renderInputToolbar = null` will remove textinput, but there is offset between scrollview and botton
[
![image](https://user-images.githubusercontent.com/20356023/29312329-7c8645e4-81bd-11e7-9390-a18451722e9e.png)
](url)

not sure how to display messages from top of scrollview and remove the space of scrollview and bottom

**Comment by ianlin** [comment]
Try #410 for removing the space of the bottom.
