### ISSUE TITLE
How to remove text input, then replace with 2 buttons, then still receive response from these 2 buttons?

### ISSUE THREAD

**Issue by thiennhank9** [FaridSafi/react-native-gifted-chat#540]
How to the above thing, please show me. I'm newbie!

**Comment by vgorte** [comment]
It's pretty simple actually. As documented in the **Readme.md**  there is a function called `renderInputToolbar`. You should be able to achieve everything you want with this function. 

Essentially you render your own inputToolbar and therefore it's your choice what you want RN to render. For example 2 Buttons. 

I would do something like : 

```
  renderInputToolbar(){
    return(
      <View style={{flex: 1, flexDirection: 'row'}}>
        <Button
          onPress={null}
          title="Button 1"
          color="#841584"
        />
        <Button
          onPress={null}
          title="Button 2"
          color="#841584"
        />
      </View>
    )
  }
```

and add the following line to your `<GiftedChat> `   : 
   `renderInputToolbar = {this.renderInputToolbar}`


What you get should look like : 

![12](https://user-images.githubusercontent.com/17333517/29791349-e129f796-8c3c-11e7-8bf9-4f33b8f64bf9.png)


And after that you just need to fill the `onPress` methods of both buttons in any way you like.
