### ISSUE TITLE
How to send Image to chat (both left and right)

### ISSUE THREAD

**Issue by thiennhank9** [FaridSafi/react-native-gifted-chat#542]
I simply want to do the above thing, how can do that, guys?

**Comment by wayne1203** [comment]
Just add "image" parameter into the message and you will get MessageImage by default.
The "image" parameter is the image URI
No any code change needed.
Text will show on the bottom of the message bubble if "text" parameter exist. (If my memory serves well)

**Comment by CandyOgre** [comment]
@thiennhank9 is it works for you? Close issue if resolved

**Comment by ifalldev** [comment]
hello fellows!

I read all the issues found here about sending images but i don't quite understand how may I put a button to the user send an image and how i send this image to a storage or database.

I would appreciate some help =)

**Comment by wayne1203** [comment]
@ifalldev There have a accessory button on the bottom left. You may use it to add future actions such as call Gallery or Camera.

I'm using my custom message view so I'm not sure is it work or not
Just add "image" to the message array and it will work
```
{
          _id: Math.round(Math.random() * 1000000),
          text: text,
          createdAt: new Date(),
          user: {
                    _id: 2,
                    name: 'React Native',
          },
          image: (url)
}
```

**Comment by ifalldev** [comment]
Thank you @wayne1203!

I haven't attempting myself to the accessory button =)

**Comment by snehadange** [comment]
> Just add "image" parameter into the message and you will get MessageImage by default.
> The "image" parameter is the image URI
> No any code change needed.
> Text will show on the bottom of the message bubble if "text" parameter exist. (If my memory serves well)

hi but if want send image by  onsend click as like message

**Comment by snehadange** [comment]
> @ifalldev There have a accessory button on the bottom left. You may use it to add future actions such as call Gallery or Camera.
> 
> I'm using my custom message view so I'm not sure is it work or not
> Just add "image" to the message array and it will work
> 
> ```
> {
>           _id: Math.round(Math.random() * 1000000),
>           text: text,
>           createdAt: new Date(),
>           user: {
>                     _id: 2,
>                     name: 'React Native',
>           },
>           image: (url)
> }
> ```

no its not working
