### ISSUE TITLE
How to i send an image while chatting ?

### ISSUE THREAD

**Issue by sidd123456** [FaridSafi/react-native-gifted-chat#543]
#### Issue Description

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by wayne1203** [comment]
Maybe same as #542 ?

**Comment by wayne1203** [comment]
#429 
I think we discuss the issue here will be better because it's out of topic.
Can you provide your message array?

**Comment by sidd123456** [comment]
here is the code:
 k=[
    {
        _id:1,
        text:'hii',
        createdAt: new Date(),

image:require('Pipay/src/assets/images/recieve-pink-transparent.png'),
        user: {
                 _id: 2,
                 name: 'React Native',
                 avatar: 'https://facebook.github.io/react/img/logo_og.png',
               },
    },
    {
        _id:2,
        text:'jii',
        createdAt: new Date(),
        user: {
                 _id: 2,
                 name: 'React Native',
                 avatar: 'https://facebook.github.io/react/img/logo_og.png',
               },
    },
    {
        _id:3,
        text:'hello',
        createdAt: new Date(),
        user: {
                 _id: 2,
                 name: 'React Native',
                 avatar: 'https://facebook.github.io/react/img/logo_og.png',
               },
    }

]

**Comment by sidd123456** [comment]
with  'https://facebook.github.io/react/img/logo_og.png' also getting the
same error

**Comment by wayne1203** [comment]
So it's run fine if removed "image" parameter?
Or typo in the json?

**Comment by sidd123456** [comment]
yes it runs fine if image parameter is removed

**Comment by wayne1203** [comment]
Um....  Is it some special word included in the json?
Such as "new line"

**Comment by sidd123456** [comment]
no nothing the error just says react native json value <null> of type
NSnull cannot be converted to nsstring

**Comment by wayne1203** [comment]
I didn't found any null value in your json.... 
The red screen will show you where is the problem, maybe there is the debug stating point

**Comment by wayne1203** [comment]
Is the example work normal?
You can try to send image using left bottom corner button in iOS

**Comment by sidd123456** [comment]
how do i customize my input area of textinput i want to add a + icon in my
place holder
