### ISSUE TITLE
Images in chat thread slow down interactions (scroll, keyboard expanding) and dont expand

### ISSUE THREAD

**Issue by 3210jr** [FaridSafi/react-native-gifted-chat#544]
Hey,

#### Issue Description

1. Everything is good and well except when there is an image within the visible screen. The scroll works so smoothly until you scroll into a part of the thread with an image, it gets worse with more images.
2. In fact, if there is more than one image then only one image is visible. (the first one to appear)
3. When an image is clicked on, I get a blank black screen (supposedly where the image should appear)

#### Steps to Reproduce / Code Snippets

All I did, was literally just install the plugin, and hook it up to the firebase backend

#### Expected Results

It is expected that all images render when clicked on and expanded
It is also expected that when there are more than one images sent, they can all be seen in the current view.
Lastly, but this could be due to many other reasons such as image size, but the scroll performance when an image is in the current view could be faster (?)

#### Additional Information

* React Native version: 0.46.4
* react-native-gifted-chat version: 0.2.5
* Platform(s) (iOS, Android, or both?): Android

This is a great project, one of a kind! 
![screenshot_20170820-112631](https://user-images.githubusercontent.com/11012023/29493194-9da9475e-859a-11e7-92b3-140bc94578ae.png)
Thanks again.

**Comment by vgorte** [comment]
Did you change anything int the gifted-chat? 
Did you try to hook it up with the example, just to see if it works? 
Because the example is working fine; You don't have any scroll "lag" with multiple images and the images enlarge on click. Also, multiple images render just fine.

It's pretty hard to say what's your explicit problem. If possible, can you show us some code? Like your gifted-chat component or what you changed?

**Comment by 3210jr** [comment]
Hey, thanks for the response.

Here is the code I have used for the GiftedChat component:

<img width="884" alt="screen shot 2017-08-25 at 11 19 26 am" src="https://user-images.githubusercontent.com/11012023/29705629-9bc28806-8987-11e7-858f-6c8a28d246c7.png">

I have not changed anything in the library itself. Currently my only problems are that: 
1. the chat thread doesnt render all the images within a given view, 
2. when an image is present in the view it affects the scroll performance (I can see the javascript thread drop significantly)
3. When an image is clicked on, it only renders a blank black screen.

**Comment by vgorte** [comment]
Kind of strange... 
Do you have the same problems on iOS?

**Comment by 3210jr** [comment]
I havent built for iOS yet

**Comment by vgorte** [comment]
You get your photos via the android gallery right? 
Can you show us some code for that?

**Comment by 3210jr** [comment]
HA! I figured it out...

The problem is that the photos from my camera are too high quality (very large - over 1mb each) and i had to compress the images before sending the images to the server. Everything works just fine... I think i just needed a break from it all to figure it out.

Thanks a lot guys.
