### ISSUE TITLE
why <GiftedChat> component cannot be enclosed by <View>

### ISSUE THREAD

**Issue by Sunjiawei58** [FaridSafi/react-native-gifted-chat#545]
#### Issue Description

why <GiftedChat> component cannot be enclosed by <View>

in the render function:
I was trying add some component on the top of the giftedChat, but when I wrote code like this, the gifted chat cannot be displayed normally
<View>
<GiftedChat />
</View>
[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* React Native version: 0.46
* react-native-gifted-chat version: 0.2.5
* Platform(s) (iOS, Android, or both?): Android

**Comment by MarschHuynh** [comment]
It is possible but you must style the View with flex: 1

**Comment by brunocascio** [comment]
Hi!

As mentioned @MarschHuynh. You have to add `flex: 1` in your wrapper view.
