### ISSUE TITLE
How to make the SendButton always show?

### ISSUE THREAD

**Issue by huanghaodong** [FaridSafi/react-native-gifted-chat#546]
#### Issue Description

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by ngocnvn** [comment]
Please check file Send.js in nodemodules
render() {
    // if (this.props.text.trim().length > 0) {
      return (
        <TouchableOpacity
          style={[styles.container, this.props.containerStyle]}
          onPress={() => {
            this.props.onSend({text: this.props.text.trim()}, true);
          }}
          accessibilityTraits="button"
        >
          <Image
            style={styles.image}
            source={require('../../../assets/images/send.png')}
          />
        </TouchableOpacity>
      );
    // }
    return <View/>;
  }
}

**Comment by huanghaodong** [comment]
thanks

**Comment by CandyOgre** [comment]
@huanghaodong close this issue if resolved
