### ISSUE TITLE
Hi,I would like to ask you under the advice.Can you give me some ideas?

### ISSUE THREAD

**Issue by cloudsafe** [FaridSafi/react-native-gifted-chat#547]
I‘m writing my chatting component.socket server, send message by text,emoji,audio,video,map marker,redpackage all of them is ok.But , when i send multiple pictures at the same time,receiver 's chatroom  page will first become blank for some time, and then display the picture and picture.Even including the message that has been received, will become blank and then reload.This happens only when multiple pictures are sent at the same time.I'm using the tools by flatList ,set  inverted true and scaleY =-1.when it receive message,this code was
 `if (key === this.currentChatKey) {
           let payloads2 = payloads.sort(function(a, b) {
                return a.timestamp - b.timestamp;
            });
          
           for(var i=0;i<payloads.length;i++){
               this.currentChatRoomHistory.unshift(payloads[i]);
           }
           console.log(this.currentChatRoomHistory)
        }`
I tried all my methods can not solve this problem.Can you give me some ideas?
ps: english is so poor.Hope you can understand

**Comment by brunocascio** [comment]
Did you test to send multiple images with the react-native-gifted-chat example?

Please, feel free to reopen if the issue persists. However, today we've pushed a new release. Could you test it with the newest release? (v0.2.8)
