### ISSUE TITLE
How to run the react-native-gifted-chat in mac

### ISSUE THREAD

**Issue by kumareshsaran** [FaridSafi/react-native-gifted-chat#548]
#### Issue Description

I tried in a different way but I'm new to react native so I did not know how to install in Mac. if any one knows please ping me

#### Steps to Reproduce / Code Snippets
 I tried below comment in terminal

 1.react-native init iOS
2.react-native run-iOS

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by vgorte** [comment]
Do you have trouble running the Awesome-Project from react ?
