### ISSUE TITLE
Text Input doesn't behave properly after 5 lines (Android)

### ISSUE THREAD

**Issue by gavin-gmlab** [FaridSafi/react-native-gifted-chat#553]
#### Issue Description

Clone the latest version of Gifted Chat and run example app.
In the text input box, keep typing your message. First 4+ lines it is ok and the input field expands. Past the 5th line the input box just shows the first 5 lines even though you can still carry on typing. You can manually scroll to the end of the text, but the moment you carry on to the next line, same thing happens again

#### Steps to Reproduce / Code Snippets

In the text input box, keep typing your message. First 4+ lines it is ok and the input field expands. Past the 5th line the input box just shows the first 5 lines even though you can still carry on typing. You can manually scroll to the end of the text, but the moment you carry on to the next line, same thing happens again.
Happens both on device and simulator(Nexus 5)

#### Expected Results

Focus should remain where you are typing

#### Additional Information

* React Native version: 46.1, 45.x
* react-native-gifted-chat version: 0.2.7
* Platform(s) (iOS, Android, or both?): Seems to be OK on iOS, but not on Android

**Comment by tmadeira** [comment]
Same issue here. Did you manage to fix it?

**Comment by zachrnolan** [comment]
Also seeing this issue, let me know if you guys were able to resolve this.

**Comment by adrianchinghc** [comment]
https://github.com/facebook/react-native/issues/12799
