### ISSUE TITLE
Functionality : Can we send PDF file?

### ISSUE THREAD

**Issue by samcomashish** [FaridSafi/react-native-gifted-chat#554]
Hi, this is an awesome library, need pdf upload. Is it possible?

Thank you.

**Comment by afloury** [comment]
Hi,
I think that you can implement it with the `renderActions` property and using another library like this : https://github.com/cnjon/react-native-pdf-view
To display the pdf icon in the bubble, you can use `renderCustomView`.

Hope it help you.

**Comment by brunocascio** [comment]
Close for now.

**Comment by alexbowers** [comment]
@brunocascio Did you ever get this figured out?

**Comment by ronastlelobo** [comment]
yeah, did you figure it out ? @brunocascio

**Comment by alexbowers** [comment]
I figured this out by using a Custom View copied from the Image View, and having the PDF have a preview of an image for them to click. When clicking I opened the link on Google Docs with their PDF preview link.

**Comment by ronastlelobo** [comment]
Could you please share the code.

**Comment by alexbowers** [comment]
I have this:

```
<GiftedChat
            messages={this.state.messages}
            renderInputToolbar={() => null}
            minInputToolbarHeight={0}
            renderCustomView={this.renderCustomView}
            renderBubble={this.renderBubble.bind(this)}
          />
```

and then `renderCustomView` is defined as 

```
import CustomView from './CustomView';

renderCustomView(props) {
    return (
      <CustomView
        {...props}
      />
    );
  };
```

Then in the CustomView I have:

```
import PropTypes from 'prop-types';
import React from 'react';
import {
  View,
  WebView,
  Image,
  Linking,
  Platform,
  StyleSheet,
  TouchableOpacity,
  ViewPropTypes
} from 'react-native';
import { Actions } from 'react-native-router-flux';
import apiConfig from '../../config/client.js';
import Lightbox from 'react-native-lightbox';

export default class CustomView extends React.Component {
  renderPdf() {
    return (
      <TouchableOpacity style={[styles.container, this.props.containerStyle]} onPress={() => {
        
          Linking.openURL(`https://docs.google.com/viewerng/viewer?url=${this.props.currentMessage.pdf}`)
      
      }}>
      <Image
          {...this.props.imageProps}
          style={[styles.image, this.props.imageStyle]}
          source={{uri: `${apiConfig.url}/images/messages/${this.props.currentMessage._id}/preview.jpg`}}
        />
      </TouchableOpacity>
    );
  }

  renderHtml() {
    return ( 
      <TouchableOpacity style={[styles.container, this.props.containerStyle]} onPress={() => {
        Actions.chat_html({properties: this.props.currentMessage});
      }}>
      <Image
          {...this.props.imageProps}
          style={[styles.image, this.props.imageStyle]}
          source={{ uri: this.props.currentMessage.template_image }}
        />
      </TouchableOpacity>
    );
  }

  render() {
    if (this.props.currentMessage.file_type == 'pdf') {
      return this.renderPdf();
    } else if (this.props.currentMessage.template && this.props.currentMessage.template != 'none') {
      return this.renderHtml();
    }
    return null;
  }
}

const styles = StyleSheet.create({
  container: {
  },
  mapView: {
    width: 150,
    height: 100,
    borderRadius: 13,
    margin: 3,
  },
  image: {
    width: 150,
    height: 100,
    borderRadius: 13,
    margin: 3,
    resizeMode: 'cover'
  },
  webview: {
    flex: 1,
  },
  imageActive: {
    flex: 1,
    resizeMode: 'contain',
  },
});

CustomView.defaultProps = {
  mapViewStyle: {},
  currentMessage: {
    image: null,
    file_type: null,
    template: null,
    template_html: null,
  },
  containerStyle: {},
  imageStyle: {},
};

CustomView.propTypes = {
  currentMessage: PropTypes.object,
  containerStyle: ViewPropTypes.style,
  mapViewStyle: ViewPropTypes.style,
  imageStyle: Image.propTypes.style,
  imageProps: PropTypes.object,
};

```

**Comment by pacheco7** [comment]
> I have this:
> 
> ```
> <GiftedChat
>             messages={this.state.messages}
>             renderInputToolbar={() => null}
>             minInputToolbarHeight={0}
>             renderCustomView={this.renderCustomView}
>             renderBubble={this.renderBubble.bind(this)}
>           />
> ```
> 
> and then `renderCustomView` is defined as
> 
> ```
> import CustomView from './CustomView';
> 
> renderCustomView(props) {
>     return (
>       <CustomView
>         {...props}
>       />
>     );
>   };
> ```
> 
> Then in the CustomView I have:
> 
> ```
> import PropTypes from 'prop-types';
> import React from 'react';
> import {
>   View,
>   WebView,
>   Image,
>   Linking,
>   Platform,
>   StyleSheet,
>   TouchableOpacity,
>   ViewPropTypes
> } from 'react-native';
> import { Actions } from 'react-native-router-flux';
> import apiConfig from '../../config/client.js';
> import Lightbox from 'react-native-lightbox';
> 
> export default class CustomView extends React.Component {
>   renderPdf() {
>     return (
>       <TouchableOpacity style={[styles.container, this.props.containerStyle]} onPress={() => {
>         
>           Linking.openURL(`https://docs.google.com/viewerng/viewer?url=${this.props.currentMessage.pdf}`)
>       
>       }}>
>       <Image
>           {...this.props.imageProps}
>           style={[styles.image, this.props.imageStyle]}
>           source={{uri: `${apiConfig.url}/images/messages/${this.props.currentMessage._id}/preview.jpg`}}
>         />
>       </TouchableOpacity>
>     );
>   }
> 
>   renderHtml() {
>     return ( 
>       <TouchableOpacity style={[styles.container, this.props.containerStyle]} onPress={() => {
>         Actions.chat_html({properties: this.props.currentMessage});
>       }}>
>       <Image
>           {...this.props.imageProps}
>           style={[styles.image, this.props.imageStyle]}
>           source={{ uri: this.props.currentMessage.template_image }}
>         />
>       </TouchableOpacity>
>     );
>   }
> 
>   render() {
>     if (this.props.currentMessage.file_type == 'pdf') {
>       return this.renderPdf();
>     } else if (this.props.currentMessage.template && this.props.currentMessage.template != 'none') {
>       return this.renderHtml();
>     }
>     return null;
>   }
> }
> 
> const styles = StyleSheet.create({
>   container: {
>   },
>   mapView: {
>     width: 150,
>     height: 100,
>     borderRadius: 13,
>     margin: 3,
>   },
>   image: {
>     width: 150,
>     height: 100,
>     borderRadius: 13,
>     margin: 3,
>     resizeMode: 'cover'
>   },
>   webview: {
>     flex: 1,
>   },
>   imageActive: {
>     flex: 1,
>     resizeMode: 'contain',
>   },
> });
> 
> CustomView.defaultProps = {
>   mapViewStyle: {},
>   currentMessage: {
>     image: null,
>     file_type: null,
>     template: null,
>     template_html: null,
>   },
>   containerStyle: {},
>   imageStyle: {},
> };
> 
> CustomView.propTypes = {
>   currentMessage: PropTypes.object,
>   containerStyle: ViewPropTypes.style,
>   mapViewStyle: ViewPropTypes.style,
>   imageStyle: Image.propTypes.style,
>   imageProps: PropTypes.object,
> };
> ```

Hi @alexbowers , about your "import apiConfig from '../../config/client.js';", you can share with us?

BR,
