### ISSUE TITLE
In some languages the text input box cuts the bottom part of letters

### ISSUE THREAD

**Issue by uriva** [FaridSafi/react-native-gifted-chat#555]
e.g. copy this string: ךךךך

**Comment by afloury** [comment]
I think, I have the same problem with my physical device :
![screenshot_2017-08-30-19-04-20](https://user-images.githubusercontent.com/18677074/29885356-c3d43960-8db6-11e7-94b9-4c60d2953854.png)

The first message is 'Hello developer' like the example, but it's not displaying correctly, sometimes it's good, sometimes the last word is missing, or the last letter of the last word, weird.

The problem doesn't appear in the simulator, but on my real device :
LG G3 (LG-D855) 2560 x 1440 pixels
Android 6.0
react 16.0.0-alpha.12
react-native 0.47.2
react-native-gifted-chat 0.2.7

If someone has an idea.

**Comment by brunocascio** [comment]
duplicated https://github.com/FaridSafi/react-native-gifted-chat/issues/531
