### ISSUE TITLE
Slow performance after doing nothing

### ISSUE THREAD

**Issue by Villar74** [FaridSafi/react-native-gifted-chat#557]
#### Issue Description

When i open chat, chatting with someone and just leave it open for a couple of minutes, input performance became very slow.

Any suggestions how to fix this?

```js
<GiftedChat
          isLoadingEarlier={this.state.isLoadingEarlier}
          label="Показать старые сообщения"
          loadEarlier={this.state.loadEarlier}
          locale="ru"
          textStyle={{fontFamily: AppConfig.baseFont}}
          renderBubble={this.renderBubble}
          messages={this.state.messages}
          onLoadEarlier={this.handleLoadMessages}
          onPressActionButton = {this.handleOpenCameraRoll}
          onSend={this.handleSend}
          placeholder={"Введите сообщение..."}
          renderAvatar={null}
          renderFooter={this.renderFooter}
          renderLoading={this.renderLoading}
          renderMessageImage={this.renderImageMessage}
          renderSend={this.renderSend}
          textAvailable={this.state.textAvailable}
          renderActions={this.renderAvatar}
          shouldRenderAvatar={()=> {return false;}}
          user={{
            _id: USER_ID,
          }}
        />
```

#### Additional Information

* React Native version: 0.42.3
* react-native-gifted-ch.at version: 0.1.5
* Platform(s) (iOS, Android, or both?): Android, ios not tested

**Comment by vgorte** [comment]
Hello @Villar74, 
Your code snippet is not sufficient to determin why you have performence drops. 

It could be that some components of functions of yours iterate many times over the messages array or basically every other possible cause. We simply can't tell with the given informations.
