### ISSUE TITLE
Web Socket 

### ISSUE THREAD

**Issue by SainiRohitSeasia** [FaridSafi/react-native-gifted-chat#558]
Have you used web socket  to create this gifted chat ?
Multiuser chat is possible ?

**Comment by varungupta85** [comment]
This is just a UI to show existing and type new chat messages. You have to plug in the code to retrieve existing messages and send new messages.

**Comment by afloury** [comment]
Example project with Socket.io and react-native-gifted-chat : https://github.com/vinnyoodles/react-native-socket-io-example

**Comment by SainiRohitSeasia** [comment]
Thanks @afloury .... but my main concern is to know that react-native gifted-chat is socket.io based or not.

**Comment by afloury** [comment]
Like @varungupta85 said, **react-native-gifted-chat is just a UI** there is no socket or server communication implemented, so you can use what you want and plug it on this UI lib to display your messages send and received by your server.

**Comment by CandyOgre** [comment]
@SainiRohitSeasia issue can be closed?

**Comment by brunocascio** [comment]
Hi @SainiRohitSeasia,

This library is just UI.
