### ISSUE TITLE
Sometimes text messages not display totally on my Android

### ISSUE THREAD

**Issue by afloury** [FaridSafi/react-native-gifted-chat#559]
Hi,

#### Issue Description

I think it's the same problem than issue #420 **Some of my Android users report messages being cut off.**
I create new issue to take it move because it seems to be an important problem if apps must be released into production, and I haven't found a solution for the moment.

On my Android (not in the simulator), some text in the bubble is not entirely displayed, the bubble takes the correct place for all words, but depending on the last words sometimes one word or letter is transparent. If I try to copy it and past it, there are all the words, so the string is complete.

Like this :
![screenshot_2017-08-30-19-04-20](https://user-images.githubusercontent.com/18677074/29885356-c3d43960-8db6-11e7-94b9-4c60d2953854.png)

#### Steps to Reproduce / Code Snippets

Launch a React Native application with react-native-gifted-chat and implement it in any way (example from README or advanced example [example/App.js](example/App.js)) on Android device which get the problem like mine -> LG G3 (LG-D855) 2560 x 1440 pixels with Android 6.0

#### Expected Results

Message display totally.

#### Additional Information

* React Native version: 0.47.2
* react-native-gifted-chat version: ^0.2.7
* Platform: Android 6.0
* Device: LG G3 (LG-D855) 2560 x 1440 pixels

**Comment by afloury** [comment]
If someone have the same problem, please add information about your device in a comment, it might be helping.

**Comment by afloury** [comment]
I found another display bug on my phone, the avatar with initials is present with just the first letter, it seems to be the same problem I think.

![screenshot_2017-09-11-15-13-59](https://user-images.githubusercontent.com/18677074/30276639-c95efeb2-9705-11e7-9882-7956758adee3.png)

I'm really the only one ?

**Comment by afloury** [comment]
Hi @brunocascio ,
Thanks for your reply.

I tested it and that didn't correct the problem.

![react native update](https://user-images.githubusercontent.com/18677074/31734804-275b3268-b440-11e7-8bdd-b1064e7c3eb7.png)

![screenshot_2017-10-18-19-57-31](https://user-images.githubusercontent.com/18677074/31734902-75813640-b440-11e7-93b8-77371f351fe0.png)

**Comment by afloury** [comment]
I am working on a solution, currently it corrects the problem, but I need to improve it because I don't have the open URL when you click on a link in a text message, or action on phone number...

here is my solution :

Add a renderMessageText to the GiftedChat component
```javascript
render() {
    return (
      <GiftedChat
        messages={this.state.messages}
        onSend={this.onSend}
        user={{
          _id: 1, // sent messages should have same user._id
        }}
        renderMessageText={this.renderMessageText}
      />
    );
  }
```

Make your own renderMessageText
```javascript
renderMessageText(props) {
    return (
      <Text style={{
        color: (props.position === 'right' ? 'snow' : 'black'),
        fontSize: 16,
        lineHeight: 20,
        marginTop: 5,
        marginBottom: 5,
        marginLeft: 10,
        marginRight: 10,
        fontFamily: 'normal',
      }}>
        {props.currentMessage.text}
      </Text>
    )
  }

```

Bind it in the constructor(props) function
```javascript
this.renderMessageText = this.renderMessageText.bind(this);
```

**Comment by wizebin** [comment]
I experienced a similar issue today with a non-chat related app, check your android settings for a font size setting, I found that setting the font size to "small" (which is actually the default font size) will "fix" this issue for me, anything larger seems to have issues being displayed.

For me it seems to be a react native issue, I'm guessing something to do with font size calculation not taking the extra setting into consideration? Will try to remember to report back with more details when I've fixed the issue in my app

**Comment by tboulis** [comment]
Im having the same problem with some devices... Any news on this?

**Comment by pierroo** [comment]
Same here; any news?

I also found out, similar to @wizebin, that changing the default android fontFamily fixed the issue.

(for example, from serif to roboto)
