### ISSUE TITLE
secureTextEntry prop for the TextInput doesn't seem to work.

### ISSUE THREAD

**Issue by tamg** [FaridSafi/react-native-gifted-chat#568]
#### Issue Description

I can't get `secureTextEntry` prop to obscure password text on the text input. All other props passed through `textInputProps` work. 

#### Steps to Reproduce / Code Snippets

```
   textInputProps: {
        autoCapitalize:"none",
        autoCorrect: false,
        secureTextEntry: true //not working
        placeholder: 'Password'
    }

  <GiftedChat style={chat}
        onSend={ (messages) => { this.props.onSend(messages) } }
        textInputProps={textInputProps}
        messages={this.props.messages}
   />
```

#### Expected Results

`secureTextEntry` should obscure the text on the text input

#### Additional Information

* React Native version: 0.46.1
* react-native-gifted-chat version: 0.2.5
* Platform(s) (iOS, Android, or both?): iOS

**Comment by brunocascio** [comment]
Hi @tamg, It seems to be related to this React Native issue https://github.com/facebook/react-native/pull/16272.

I tried your code and it works, so I think that you are using `multiline=true`. Is it right?
