### ISSUE TITLE
Private Chat

### ISSUE THREAD

**Issue by vohratom** [FaridSafi/react-native-gifted-chat#572]
Hi Farid,

I am so sorry, but I tried to contact you many different ways but without any luck. I just wanted to ask you if there is any chance to customize gifted chat to be more like Whatsapp with private chat rooms?

Thank you.

Tomas

**Comment by jjdp** [comment]
isn't that supposed to be non ui? more on the server side

**Comment by vohratom** [comment]
I do not understand  what do you mean exactly. I guess you have to customize the code somehow to create room ids but idk how :/

**Comment by jjdp** [comment]
this lib is pure UI only but if you meant a group chat then you have to roll out your customization

**Comment by vohratom** [comment]
Ok, thank you for your reply. I thought there is something like tuts how to customize it easily :)

**Comment by brunocascio** [comment]
Gifted chat is just a chat UI Library. This handles a list of messages instead of "rooms". I think a room is out of this library.

Thanks!
