### ISSUE TITLE
Support for render centered messages

### ISSUE THREAD

**Issue by verzil** [FaridSafi/react-native-gifted-chat#575]
##### i am currently working on a chat application that have system messages generated by the backend. It does not make logical sense for me to create a System User to display this message, so I am hoping to put the message in the center just like the Day component. However I am not sure where I would be able to achieve this,

 ###### **I've Tried** to make a CustomView, but that still does not allow me to center the message. I think it is because the Message component is expecting either "left" or "right" position prop, so I cannot pass a custom position.

**Comment by redwind** [comment]
you could fork this project then custom Message.js file to render centerd message as you expect

**Comment by pewh** [comment]
+1 need this very much. Centered message is common feature (like whatsapp) to notify if somebody has join or left the group

**Comment by adrianchinghc** [comment]
I've successfully implemented system messages in my current chat app. It's possible with the current setup but there will always be a warning message because I omitted `user` in my message object so that it doesn't use the `left` or `right` props.

If this is something needed by the community, I am willing to work on a PR to make it easier for developers to add system message.

What do you think @brunocascio ?

**Comment by adrianchinghc** [comment]
ChatBubble.js
```
const ChatBubble = (props) => {
  if (props.currentMessage.system) {
    return (
      <View style={styles.systemMessageContainer}>
        <Text style={styles.systemMessageText}>
          {systemMessage}
        </Text>
      </View>
    );
  }
  return (
    <Bubble
      {...props}
    />
  );
};
```

Chat.js
```
renderBubble = props => <ChatBubble {...props} />;

<GiftedChat 
  ...  
  renderBubble={this.renderBubble} 
/>
```

Message Object
```
{
  _id: 1,
  text: 'My message',
  createdAt: new Date(Date.UTC(2016, 5, 11, 17, 20, 0)),
  system: true,
  image: 'https://facebook.github.io/react/img/logo_og.png',
}
```
Notice that I've omitted the user in the message object. Instead I passed in `system: true`. This will however cause the `user should not be empty` warning.

**Comment by brunocascio** [comment]
Hi @adrianchinghc,

Thanks for your help. PR would be appreciated!

After that, we discuss with the others members about that :)

**Comment by brunocascio** [comment]
Yes! I was thinking about a system flag as well

**Comment by brunocascio** [comment]
Merged https://github.com/FaridSafi/react-native-gifted-chat/pull/608
