### ISSUE TITLE
onLongPress prop not working for image messages

### ISSUE THREAD

**Issue by maharjanaman** [FaridSafi/react-native-gifted-chat#577]
While trying to perform onLongPress for messages with image, only react-native-lightbox functions triggers.
Is there a work around for this?

**Comment by blcsntb** [comment]
@maharjanaman please check it https://github.com/blcsntb/react-native-gifted-chat/pull/1.

**Comment by rajscet** [comment]
Very bad solution. why we change in node module. stupid!
