### ISSUE TITLE
Textinput is hidden on Android

### ISSUE THREAD

**Issue by Clowning** [FaridSafi/react-native-gifted-chat#578]
#### Issue Description

Hi , i use react-native-gifted-chat on IOS and everythings work but on android, when i tap on the textinput, the keyboard rise up, le textinput too, everythings good but when i tap a letter, the textinput disappears (being the keyboard i suppose! 

* React Native version: 0.48.3
* react-native-gifted-chat version: 0.2.7
* Platform(s) (iOS, Android, or both?): Android

**Comment by jsappme** [comment]
same issue on android too

**Comment by Clowning** [comment]
I've fixed by this way : 

In GiftedChat, comment in resetInputToolbar() 

    // this.notifyInputTextReset();
    // const newComposerHeight = MIN_COMPOSER_HEIGHT;
    // const newMessagesContainerHeight = this.getMessagesContainerHeightWithKeyboard(newComposerHeight);
    // this.setState({
    //   text: this.getTextFromProp(''),
    //   composerHeight: newComposerHeight,
    //   messagesContainerHeight: this.prepareMessagesContainerHeight(newMessagesContainerHeight),
    // });

And in onInputSizeChanged comment all content ! 

After that it's working, and there are no side effect for me !

**Comment by pulpdood** [comment]
I have a similar issue
![image](https://user-images.githubusercontent.com/13587944/32697802-d6088300-c7ec-11e7-87a8-ef6512964a5b.png)

**Comment by davista123** [comment]
The way I finally got it to work was by using react-native-keyboard-spacer in the same <View/> as <GiftedChat/>

**Comment by hironarita** [comment]
@davista123 Thanks! This solution works for me as well.

**Comment by awadesmoline** [comment]
Thanks @davista123. Works great!

**Comment by mahanhaz** [comment]
@davista123 love you man, i was spending 2 month to fix this bug

**Comment by xcarpentier** [comment]
Just added this issue on README:
https://github.com/FaridSafi/react-native-gifted-chat#questions

**Comment by xcarpentier** [comment]
Please see here: https://github.com/FaridSafi/react-native-gifted-chat/issues/680#issuecomment-359699364

**Comment by esvm** [comment]
Man I love you. Really. I wanna sick you!

**Comment by Tempest1000** [comment]
@davista123 worked perfectly, thank you thank you thank you

**Comment by tapz** [comment]
At least without Expo KeyboardSpacer just duplicates the behaviour in Android. I'm still seeing the keyboard covering the textinput randomly in Android. Would really, really like to have a solution to this.

**Comment by akhilsanker** [comment]
Hi,
Any solution for this.
I am using custom input composer and the keyboard gets overlap with the input.

Thanks
