### ISSUE TITLE
Update when receiving new messages

### ISSUE THREAD

**Issue by rochapablo** [FaridSafi/react-native-gifted-chat#579]
I'm running the chat using two simulators (Android and IOS) where each have different users chatting between. Using ```loadEarlier, isLoadingEarlier and onLoadEarlier``` I'm trying to update the chat as I receive new messages.

I thought that when using onLoadEarlier I would be able to get notice about the new messages, but it's clearly that I'm missing something. 

I also thought about use some ```Interval``` to check for new data, but I don't see this as a good option.

```
constructor (props) {
    super(props)

    this.state = {
        loadEarlier: true,
        isLoadingEarlier: false,
        messages: []
    }

    this.onLoadEarlier = this.onLoadEarlier.bind(this)
}
```

```
_load () {
    api.getMessages().then((response) => {
        this.setState((previousState) => {
            return { messages: response, isLoadingEarlier: false }
        })
    })
}
```

```
onLoadEarlier () {
    this.setState((previousState) => {
      return { isLoadingEarlier: true }
    })
    this._load()
}
```

```
<GiftedChat
messages={this.state.messages}
loadEarlier={this.state.loadEarlier}
onLoadEarlier={this.onLoadEarlier}
isLoadingEarlier={this.state.isLoadingEarlier}
```

#### Additional Information

* React Native version: 0.47.2
* react-native-gifted-chat version: 0.2.7
* Platform(s) (iOS, Android, or both?): both

**Comment by ownikss** [comment]
LoadEarlier is using for load messages which was written earlier. For example, you have a chat with 100 and more messages. You don't need get all of them at once, but you can get 20 and load others if it is necessary.
About your problem, it depends on your backend. For example, my own chat was written with using socket-io and when somebody send message other clients get some event.
I think you need to use Interval for updating, If you can't get some event from server (for example, using socket-io or rest api).

**Comment by rochapablo** [comment]
@ownikss, you're right! As the backend started notify about new messages using firebase it made more sense.

Thank you.

**Comment by Srinidhi1561997** [comment]
@rochapablo, I have a doubt what will "load earlier message" button will do if there are no previous messages. Does it disable if the there are no more  previous message. If it's enabled then it's like mis-leading the people.

**Comment by rochapablo** [comment]
@Srinidhi1561997, sorry, but it's been a while and I'm not sure if I follow your comment.

**Comment by AMoktar** [comment]
So, How can I update UI when new message received ?

**Comment by EliotRaven** [comment]
> So, How can I update UI when new message received ?

the same questions
