### ISSUE TITLE
Input field cache is not cleaned

### ISSUE THREAD

**Issue by denstepa** [FaridSafi/react-native-gifted-chat#580]
#### Issue Description

Here is what I did:
1. clone repository
2. cd example, yarn, build android version
3. run Android version in development mode on the device (galaxy s8)

#### Steps to Reproduce / Code Snippets

Happens only on some devices (galaxy s8, android 7.1, Samsung keyboard, and on Android HTC One M7, Android 5.0.2, probably some other)

1. write a message
2. click send
3. press smth on the keyboard

#### Expected Results

the previous message stays in the input field
https://drive.google.com/open?id=0B7yMV1PreWPqVG1nY2JkYmhBOXc

#### Additional Information

* React Native version: [0.46.3]
* react-native-gifted-chat version: [latest]
* Platform(s) (iOS, Android, or both?): Android

**Comment by tjkang** [comment]
+1 same here

**Comment by evollu** [comment]
I have the same issue, seems to have to do with Predictive feature of Samsung Keyboard.
Is there a work around to turn off predictive for samsung?

**Comment by nikolaiwarner** [comment]
I was having similar trouble with other inputs on android not properly clearing. I made this little hack to clear out the predictive text: https://github.com/nikolaiwarner/react-native-text-input-reset ...perhaps that will help.

**Comment by evollu** [comment]
@nikolaiwarner I'm trying your repo. Does min SDK have to be 22?

**Comment by evollu** [comment]
I opened an issue to react native for tracking https://github.com/facebook/react-native/issues/16238

**Comment by nikolaiwarner** [comment]
There's a PR in progress on RN that should clear this up once it lands:
https://github.com/facebook/react-native/pull/12462

**Comment by brunocascio** [comment]
Close for now, since it is a bug from RN.

Please, feel free to reopen if needed.
