### ISSUE TITLE
RenderActions rendering nothing

### ISSUE THREAD

**Issue by ifalldev** [FaridSafi/react-native-gifted-chat#582]
#### Issue Description

Hi, I'm trying to allow my users to send images. To do this I understood that I have to fill `RenderAction` prop on GiftedChat but following the exemple App I didn't even render the button on the left side of the text box. The docs isn't clear about what the `prop` expect and what will do with it. 

#### Steps to Reproduce / Code Snippets

I put the `prop` on `GiftedChat` element:
```
<GiftedChat
          messages={this.filterMessages(this.props.messages[key])}
          onSend={this.onSend}
          user={{ _id: this.props.user.uid }}
          placeholder='Escreva uma mensagem'
          renderBubble={this.renderBubble.bind(this)}
          renderAction={this.renderCustomActions}
 />
```

And this is my method renderCustomActions:
```
renderCustomActions() {
    return (
      <TouchableOpacity
        style={styles.container}
      >
        <Text
          style={styles.iconText}
        >
          +
        </Text>
      </TouchableOpacity>
    );
  }
```

#### Expected Results

With that I want to see just a `+` button on the left side of the text box, is that right?

#### Additional Information

* React Native version: 0.45.1
* react-native-gifted-chat version: ^0.1.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by guerjon** [comment]
its renderActions with the S at the end 

`renderActions={() => this.renderCustomActions()}`

After on the renderCustomActions function, you should return the Actions Component 
you get this on the import
`import { GiftedChat, Actions } from 'react-native-gifted-chat'`

on the same component Actions you can onPressActionButton param

something like this 

`	renderCustomActions(props) {
	    return (
	      <Actions
	        onPressActionButton = {() => this.handleCustomActions()}
	        options={options}
	      />
	    );
  	}
`

when you push the left button, in this case, handleCustomActions() will be executed, I'm not sure why there is nothing of this in the documentation but you can find all this in the example and in the code.

**Comment by ifalldev** [comment]
Thank you @guerjon.

I feel so dumb, I guess its my tired and tricky mind. Syntax error.. All i need was in here:

>  its renderActions with the S at the end

Thanks for the explanation after that.

> but you can find all this in the example and in the code.

Yeah! Pretty sure, I saw all that there, shame on me...
