### ISSUE TITLE
Unnecessary commit hash dependencies

### ISSUE THREAD

**Issue by Rovack** [FaridSafi/react-native-gifted-chat#584]
#### Issue Description

Currently the dependencies on react-native-lightbox and react-native-action-sheet are using git URLs with specific commit hashes instead of published versions.
This is no longer necessary, as both repos have since published versions with the relevant commits. Namely, react-native-lightbox@0.7.0 (for [c84a854](https://github.com/oblador/react-native-lightbox/commit/c84a8543d4511fe6a44c3d7820747c9c1bddd875)), and react-native-action-sheet@1.0.1 (for [e73314d](https://github.com/expo/react-native-action-sheet/commit/e73314d994bbff1355dbd5a2cdea469f3f7fa496)).

The use of git repos instead of published versions causes issues when trying to install gifted chat behind a private registry, in environments that can't access GitHub, and is explicitly [discouraged by npm][1].

#### Additional Information

* React Native version: Any
* react-native-gifted-chat version: 0.2.7 (really anything above 0.1.2)
* Platform(s) (iOS, Android, or both?): Both

[1]: http://blog.npmjs.org/post/145724408060/dealing-with-problematic-dependencies-in-a

**Comment by brunocascio** [comment]
Fixed in: https://github.com/FaridSafi/react-native-gifted-chat/pull/523 (released in v0.2.8)

**Comment by Rovack** [comment]
Awesome, thanks @brunocascio!
