### ISSUE TITLE
How to use a customview for a video or audio preview?

### ISSUE THREAD

**Issue by denebchorny** [FaridSafi/react-native-gifted-chat#585]
#### Doubt Description

I am new using this library and I don't understand RN at all to get this idea as fast as I want. 

I would like a brief guide or advice on how to make a view to show information other than the standard but without changing how the text is showing. I just want a new tipe os information.

#### Code Snippets

i using the librery as is.
<GiftedChat
                            messages={this.state.messages}
                            renderSend={this.renderSend}
                            onSend={this.onSend}
                            placeholder="Escribe un mensaje"
                            user={{
                                _id: 1,
                            }}
/>

Now imagine I want to let the user to be able to send a video. I need to create a particular view, it could be just an image where the user clicks and shows a dialog. It doesn't matter. My doubt is where I have to check that the message is TYPE === 'VIDEO' and where to render the custom view? In the case the message is just a text I want to show the normal view as the library does without any change.

**Comment by brunocascio** [comment]
Hi @denebchorny, You can use the `renderBuble(props)` hook, and render your custom message view. This function receives as first argument relevant information of the current message that will be rendered.

I hope to help you.
