### ISSUE TITLE
Cannot Start the Example

### ISSUE THREAD

**Issue by njho** [FaridSafi/react-native-gifted-chat#588]
#### Issue Description

I am trying to start the example as per the description:

```
git clone https://github.com/FaridSafi/react-native-gifted-chat
cd react-native-gifted-chat/example
npm install
react-native run-android
```

#### Expected Results
I receive the following error after `npm install`:

```
npm ERR! GiftedChat@0.0.1 postinstall: `yarn run clean:example; yarn run clean:babelrc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the GiftedChat@0.0.1 postinstall script.
```

If I continue past this point with `react-native run-android`, I receive the following error:
```
error: bundling failed: "Unable to resolve module `prop-types` from `C:\\Programming\\react-native-gifted-chat\\src\\GiftedChat.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."
```

Thanks for the help!

#### Additional Information

* React Native version: 0.46.3
* react-native-gifted-chat version: 0.2.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by vgorte** [comment]
Hello @njho, 
Did you follow the error message and try to resolve the issue ? 
 
What I'm referring to is this part: 

> To resolve try the following:
> 1. Clear watchman watches: `watchman watch-del-all`.
> 2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
> 3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.


If not, please do so and tell us if something changed.

**Comment by brunocascio** [comment]
@njho Did you resolve this issue? However, I have pushed a new update in `master` branch. Could you try it?

Thanks

**Comment by rlimaeco** [comment]
I have the same issue, and how it's possible to the command yarn run clean:example; yarn run clean:babelrc works if it has a command before deleting everything, I'm new in js world, coming from python and I'm kind of lost here. I'm using the latest commit in master.

Manjaro 17.0.5
yarn 0.24.5
node v8.6.0
npm 5.5.1

**Comment by AshokICreate** [comment]
**is this issue resolved i am getting same error when i do npm install**

`➜  example git:(master) ✗ npm install
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated

> fsevents@1.1.3 install /Users/ashokr/Projects/Learning/mobile/Libraries/react-native-gifted-chat/example/node_modules/fsevents
> node install

[fsevents] Success: "/Users/ashokr/Projects/Learning/mobile/Libraries/react-native-gifted-chat/example/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> GiftedChat@0.0.1 postinstall /Users/ashokr/Projects/Learning/mobile/Libraries/react-native-gifted-chat/example
> yarn run clean:example; yarn run clean:babelrc

yarn run v1.3.2
$ rm -rf node_modules/react-native-gifted-chat/{node_modules,example}
✨  Done in 2.72s.
yarn run v1.3.2
error Command "clean:babelrc" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! GiftedChat@0.0.1 postinstall: `yarn run clean:example; yarn run clean:babelrc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the GiftedChat@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ashokr/.npm/_logs/2017-12-16T05_54_01_033Z-debug.log`

**Comment by JonathanOmisore** [comment]
The problem seems to go away if I remove this from package.json:
`yarn run clean:example;`

**Comment by mafiusu** [comment]
npm install deleted all the content in the /example folder. Even without `yarn run clean:example;`

**Comment by TheGreatAndrew** [comment]
I fixed mine, follow this: https://stackoverflow.com/questions/36119358/react-native-command-run-ios-unrecognized/36126924
So basically the problem is not the example, it's that you need to run yarn install instead of npm install.
