### ISSUE TITLE
Horizontal ScrollView as a customView

### ISSUE THREAD

**Issue by marionorato77** [FaridSafi/react-native-gifted-chat#589]
#### Issue Description

Horizontal ScrollView within a bubble not showing properly

#### Steps to Reproduce / Code Snippets

I tried to add a custom view containing a carousel with some options, but what I get is a very tall bubble with no content

#### Expected Results

I would like to show a carousel containing cards

#### Additional Information

* React Native version: 0.47.2
* react-native-gifted-chat version: 0.2.7
* Platform(s) (iOS, Android, or both?): iOS

**Comment by brunocascio** [comment]
Could you share a screenshot and your code?
