### ISSUE TITLE
Modal on GiftedChat

### ISSUE THREAD

**Issue by edcalderin** [FaridSafi/react-native-gifted-chat#590]
Hi.

I wanna put a modal component on GiftedChat, but It doesn't appear. How Could I solve this?

Thanks!!

**Comment by vgorte** [comment]
Hello @edcalderin, 
Would you be able to show us some of your code so we can help you figure that out? 
Do you get any errors or something like that?

**Comment by saumil-palm** [comment]
hello any solution on this ???
