### ISSUE TITLE
Animation on message display

### ISSUE THREAD

**Issue by redwind** [FaridSafi/react-native-gifted-chat#592]
**Sorry, this is not a bug report**

Any one has using telegram or whatsapp chat, we can see animation on message display, it's smoothly. So i would like to consult any idea for this animation.

As we know, gifted-chat force render from bottom by use 
`transform: [
      { scaleY: -1 },
    ]`
this is nice trick, but using this, message has been displayed immediately when data prop change. I tried to run animation to change message's height from 0 to fixed height  at message's componentDidMount but it doesn't work as expected; cause ListView still render a blank row for new message.
Another test, i remove all transform trick, then using:
`scrollToEnd({animation:true})`
to run animation scroll on message income, it's smoothly. But we have to scroll to bottom when access to list chat, it's a bad ux.

So, any one has any idea to help me ?

Thanks all !!!

**Comment by brunocascio** [comment]
Using `Animatable` library and `renderBubble` function, you can get the animations working.

**Comment by redwind** [comment]
@vgorte , @brunocascio 
Thanks for your reply, you all right. 
But before animation start, listview render blank row, will cause animation seem ugly.
another case, wrap bubble by Animatable will cause apply animation for all message when listview's data initialised.
As you can see in whatsapp or Tele, when new messages's comming, it smooth show from bottom.

**Comment by mafiusu** [comment]
@redwind @brunocascio @vgorte Anyone has an idea not to animate the previous messages? I preload it with the state messages but I just want only new messages to animate like @redwind write above.

**Comment by pskryuchkov** [comment]
Any updates? This kind of animation is the gold standart for all popular apps with chats (Instagram, Tinder, etc.)

https://user-images.githubusercontent.com/11331424/106201936-41ca5800-61ca-11eb-942f-044e5a38b87f.mov

**Comment by Stefan28BU** [comment]
> Any updates? This kind of animation is the gold standart for all popular apps with chats (Instagram, Tinder, etc.)
> 
>  RPReplay_Final1611869692.mov

 I achieved this effect by using position: 'absolute' in a custom Message component. Basically you need to create a wrapper component around the <Message /> component. Then implement the onLayout function to get the ListView row's height. Before you can obtain the actual row height, you need to add position:'absolute' to the wrapper's style prop so that the height of the new row would not affect the old listview's layout, then when you got the height, you can remove the absolute postion and animation the height from 0 to the obtained height.

**Comment by Stefan28BU** [comment]
@

> Any updates? This kind of animation is the gold standart for all popular apps with chats (Instagram, Tinder, etc.)
> 
>  RPReplay_Final1611869692.mov

Pasted my code here for your reference

`const CustomMessage = React.memo((props: any) => {
    const messageHeight = useSharedValue<undefined | number>(undefined);

    const [heightState, setHeightState] = useState(0);

    const [done, setDone] = useState(false);

    const themeColors: ThemeColorTypes = useSelector(
        (state: RootState) => state.setThemeColorsReducer
    );

    const transitionStyle = useAnimatedStyle(() => {
        return {
            height: messageHeight.value,
        };
    }, []);

    const onLayout = (e: LayoutChangeEvent) => {
        const tempHeight = e.nativeEvent.layout.height;

        if (!done) {
            messageHeight.value = 0;

            setHeightState(tempHeight);
        }
    };

    useEffect(() => {
        if (heightState !== 0) {
            setDone(true);
            messageHeight.value = withSpring(heightState, springConfig);
        }
    }, [heightState]);

    return (
        <Reanimated.View
            onLayout={onLayout}
            style={[
                {
                    position: heightState !== 0 ? undefined : 'absolute',
                    overflow: 'hidden',
                },
                transitionStyle,
            ]}
        >
            <Message {...props} />
        </Reanimated.View>
    );
});

CustomMessage.displayName = 'CustomMessage';

export default CustomMessage;`

**Comment by flunder** [comment]
I've managed to get this to work on iOS by adding LayoutAnimation. Not sure if this could cause performance issues further down the line but so far I haven't noticed anything and I'm glad I don't need to measure things.

Basic code:

```js
import { LayoutAnimation } from 'react-native';

const config = {
  duration: 350,
  create: { type: LayoutAnimation.Types.spring, springDamping: 0.7, property: 'opacity' },
  update: { type: LayoutAnimation.Types.spring, springDamping: 0.7, property: 'opacity' },
  delete: { type: 'linear', property: 'opacity' },
};

const Message = ({ props }) => {
  LayoutAnimation.configureNext(config);

  return <Bubble .... />
}
```

https://user-images.githubusercontent.com/91437/140083439-934e68f7-5331-42c0-9ce8-82be097d3b01.mp4

**Comment by admehta01** [comment]
Tried the solutions above - animating the height still looked weird to me as the letters start out all scrunched and then grow in size.

Instead I got pretty close to a decent looking animation (without needing to create a custom message component) by using `LayoutAnimation`:

```
const onSend = useCallback((messages = []) => {
  LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);

  setMessages((previousMessages) =>
    GiftedChat.append(previousMessages, messages)
  );
}, []);
```

**Comment by fukemy** [comment]
LayoutAnimation still the best thought

**Comment by wikramdas** [comment]
LayoutAnimation is awesome to use rather to do custom animation. Thanks @admehta01 for your suggestion.

**Comment by arnekolja** [comment]
Is there a way to make those LayoutAnimations the default for everything that's happening inside the chat?
