### ISSUE TITLE
Chat Messages inside of React Navigation Tab won't update until event triggered

### ISSUE THREAD

**Issue by nextriot** [FaridSafi/react-native-gifted-chat#593]
Hi.

I have the chat embedded in a non-visible tab (when it is within the initial tab on load, it renders as expected). 
Until I hit the enter key within the text input (to create a new line, not to send) the messages & UI aren't visible.

It seems as though whatever event triggers the rendering of the messages isn't being called. Currently my code is simply the basic usage example on in the Read me, but within a React Navigation Stack Navigator inside of a Tab Navigator.

Any help is appreciated, is there any method I can manually call, or is this a simply style fix? I've tried a few things, but to no resolve obviously.

**Comment by vgorte** [comment]
Hello @nextriot, 
The messages should render once the state of the messages array changes.
Can you show us how you update the messages array once you receive a new message?

You, theoretically, can force a component to [rerender ](https://reactjs.org/docs/react-component.html#forceupdate) with `forceUpdate()`. I would generally try not to use this methode though.

**Comment by nextriot** [comment]
Thanks for the reply @vgorte.

The issue was due to the containing components lifecycle being called whilst the view was technically off-screen. I assume this library hooks into one of the render methods. As the view wasn't visible until later - though the messages array was populated - the message elements themselves weren't actually shown until the next render update.

Within the react-navigation library there's a configuration object for tabs which accepts `lazy: true` which obviously defers the lifecycle until it's required. Adding this resolved the issue for me.

Thanks for the help.
