### ISSUE TITLE
Use Flatlist instead of Listview

### ISSUE THREAD

**Issue by zulianrizki** [FaridSafi/react-native-gifted-chat#596]
#### Improvement

Use Flatlist component that support inverted out of the box instead of Listview with invertedscrollview plugin.

https://facebook.github.io/react-native/docs/flatlist.html

thanks

**Comment by xcarpentier** [comment]
Hello @zulianrizki,
Please show this issue: #411 
Bye

**Comment by brunocascio** [comment]
duplicated https://github.com/FaridSafi/react-native-gifted-chat/issues/411
