### ISSUE TITLE
Messages being sorted the other way around

### ISSUE THREAD

**Issue by EduardJS** [FaridSafi/react-native-gifted-chat#599]
#### Issue Description

Hello gents! So basically, I don't know if this automatically does some sort of rendering, but if it does, I think it's in the opposite direction ? Basically from the example, I would imagine that it sorts the messages descending by `createdAt` prop ?

Please look at this picture: [https://i.imgur.com/ARyOXFM.jpg](https://i.imgur.com/ARyOXFM.jpg)
Note the array I'm giving it in, with all the messages sorted ASC, ( from first being the oldest, to the last being the most recent )

The rendering happens in exactly the opposite way. Is this intended ? If so, why ?

#### Expected Results

Rendering should be done in the same order as the given array of messages.

**Comment by zweck** [comment]
I'm having the same issue, in both version 2.5 and 2.7 :/  I'm going to try and debug it a bit further.

**Comment by EduardJS** [comment]
I think it’s because of the scroll view having to keep messages scrolled to the bottom.

Simple workaround is to use Array.reverse() on the messages array, then use unshift instead of push, when sending or receiving a mew message.

Don’t really think this is an issue now... it’s very similar to the issue I had when making the chat component for the Web, where I used flexDirection as column-reverse. Therefore I also had the newest messages up top.

Cheers

**Comment by zweck** [comment]
https://github.com/expo/react-native-invertible-scroll-view I think that’s what things like this exist for. But yeah, I just sorted decending by `createdAt`.

**Comment by derryc09** [comment]
Wondering if anyone had actual answer as to why this is happening...
I'm at latest version v0.8 and this issue persists.

**Comment by Joshmatjjen** [comment]
Using this to fix it:  

`<GiftedChat
            // ref={(ref) => setChatRef(ref)}
            messages={
              allMessages.reverse()
            }/>`
