### ISSUE TITLE
Injecting new message via redux to messages prop causes styling issue

### ISSUE THREAD

**Issue by wmonecke** [FaridSafi/react-native-gifted-chat#601]
#### Issue Description

When I fetch an existing chat form my firebase DB, it looks how it is supposed to: 

<img width="373" alt="screen shot 2017-10-09 at 1 02 26 pm" src="https://user-images.githubusercontent.com/24256469/31335254-0eb4f2a8-acf2-11e7-9708-262449b00bd3.png">

The time and the corners appear how they are supposed to. However, if I send a new message to firebase and receive the new array (which contains the newly created message), the message is missing the timestamp and also the corners don't display correctly.

<img width="373" alt="screen shot 2017-10-09 at 1 05 20 pm" src="https://user-images.githubusercontent.com/24256469/31335348-707a7be8-acf2-11e7-80b8-e4649e753bbc.png">

I don't know if this is how it should work in the first place or maybe I am just missing something. I have a theory that GiftedChat is not aware of these new messages and not re rendering correctly as it would if I called `GiftedChat.append()`,

#### Steps to Reproduce / Code Snippets

```
<GiftedChat
   isAnimated
   renderLoading={() => {}}
   locale={'es'}
   placeholder={'Escribe un mensaje...'}
   messages={this.props.currentChat} // comes from redux reducer
   onSend={message => this.onSend(message)}
   user={{
        _id: 1,
        name: user.name,
        avatar: user.photoURL
   }}
/>
```

**Comment by Frexuz** [comment]
Show your onSend and reducer code :)

**Comment by wmonecke** [comment]
@Frexuz the issue was that the createdAt value was a Dat object and firebase just accepts date objects as strings, thus not rendering the bubbles correctly. Thanks for your time anyways! :)

**Comment by Frexuz** [comment]
Good for others to know :) 👍
