### ISSUE TITLE
[Question] How to make left bubbles stick on the left ? (No avatar displayed)

### ISSUE THREAD

**Issue by l1br3** [FaridSafi/react-native-gifted-chat#604]
#### Issue Description

I don't want to display avatars, I want my left bubbles to stick on the left but I cannot find the right propStyle to pass to GiftedChat and don't even find where the left is applied.

I don't have an avatar prop in my messages and I can confirm that messageImage is not rendered [here](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/Bubble.js#L49)

Could you please tell me what prop I should pass and what is the right component to pass prop to ?

Thanks 

#### Additional Information

* React Native version: 0.48.2
* react-native-gifted-chat version: 0.2.8
* Platform(s) (iOS, Android, or both?): Android 8

**Comment by vgorte** [comment]
Hey @l1br3, 
that is actually pretty easy to do. 
You should check out the **README.md**. You can find all kinds of functions to help you customize your chat. 

One of those functions is called :  _renderAvatar_

> renderAvatar (Function) - Custom message avatar; set to null to not render any avatar for the message


So you can just use this function and set it to `null` like this: 
(This is the GC example)

 ```
 render() {
    return (
      <GiftedChat
        messages={this.state.messages}
        onSend={this.onSend}
        loadEarlier={this.state.loadEarlier}
        onLoadEarlier={this.onLoadEarlier}
        isLoadingEarlier={this.state.isLoadingEarlier}
        user={{
          _id: 1, // sent messages should have same user._id
        }}
        renderActions={this.renderCustomActions}
        renderBubble={this.renderBubble}
        renderCustomView={this.renderCustomView}
        renderFooter={this.renderFooter}
        renderAvatar = {null}
      />
    );
  }
}
```

This should work pretty good. Tell us if it worked for you!

**Comment by brunocascio** [comment]
Please feel free to reopen if the solution purposed by @vgorte does not work, but it should.

Thanks!

**Comment by l1br3** [comment]
@vgorte @brunocascio It was easy ! Thank you for your help !
