### ISSUE TITLE
Keyboard does not start with capital letter [Android only]

### ISSUE THREAD

**Issue by xVanjaZ** [FaridSafi/react-native-gifted-chat#610]
#### Issue Description

The keyboard does not start with a capital letter, while it does on IOS. 
Adding `autoCapitalize='sentences'` does not work.

#### Steps to Reproduce / Code Snippets

`
render() {
    return (
      <GiftedChat
        renderSend={this.renderSend}
        locale='nl'
        messages={this.state.messages}
        onSend={(messages) => this.onSend(messages)}
        placeholder='Typ je bericht...'
        user={{_id: this.props.authId}}
      />
    );
  }
`

* React Native version: `0.49`
* react-native-gifted-chat version: `0.2.9`
* Platform(s) (iOS, Android, or both?): `Android`

**Comment by filbertteo** [comment]
@xVanjaZ use this: `<GiftedChat textInputProps={{ autoCapitalize: 'sentences' }} />`

**Comment by xVanjaZ** [comment]
Thanks! Solved my issue
