### ISSUE TITLE
Render Avatar on each message

### ISSUE THREAD

**Issue by tangweikun** [FaridSafi/react-native-gifted-chat#611]
#### Issue Description

I want to show avatar on each message, not only show on the top or bottom, like the screenshot.
I just fork your repo and comment some code to make it work as my way.
Can you add a new feature to make that work?
Thanks!

![image](https://user-images.githubusercontent.com/13361639/31847700-154b2e14-b5e6-11e7-9376-7b008cfe2843.png)

**Comment by juanmanuelarze** [comment]
In MessageContainer.js line 42 you have a comment 
// add next and previous messages to hash to ensure updates
you just need change the program for "not ensure updates"

**Comment by Abhishekgarg727** [comment]
@tangweikun  i know its  late but for any other user who having issue to show avatar on every chat message , i think this will help.

**Solution
So i use two props of gifted chat:**

```
 showUserAvatar={true}
 showAvatarForEveryMessage={true}
```

**my code snippet**
```
<GiftedChat
                    messages={this.state.messages}
                    onSend={messages => {this.onSend(messages)}}
                    user={{_id: 1}} 
                    maxInputLength={1000}
                    alwaysShowSend={true}
                    renderBubble={(props)=>this.renderBubble(props)}
                    renderActions={(props) => this.renderActions(props)}
                    showUserAvatar={true}
                    showAvatarForEveryMessage={true}
                    parsePatterns={linkStyle => [
                            {
                                pattern: /#(\w+)/,
                                style: { ...linkStyle, color: 'lightgreen' },
                                onPress: props => alert(`link`),
                            },
                    ]}
                />
```

hope this helps.
