### ISSUE TITLE
moment.js doesn't find correct locale 

### ISSUE THREAD

**Issue by diegotsi** [FaridSafi/react-native-gifted-chat#614]
Hi Guys, moment.js just find 'en' in moment.locales() inside the initeLocale() func in GiftedChat.js.

I'm passing 'pt-br' in locale props but i put a console.log(moment.locales()) in GiftedChat.js and it just print  'en'.

To solve this,i edit the GiftedChat.js add the following line :

import {ptBr} from 'moment/locale/pt-br';

Does anyone know why it does not find other locations unless I import it?

**Comment by diegotsi** [comment]
the problem was with my moment.js version , i updated to 2.18.1 and solved the problem.

**Comment by Frexuz** [comment]
I use 2.18.1 as well, but it doesn't work for me. -> RN 0.49 / GiftedChat 0.2.7

```
        <GiftedChat
          messages={messages}
          onSend={(messages) => this.onSend(messages)}
          user={{
            _id: currentUser.id
          }}
          locale={'sv'}
        />
```

Like this, right?

**Comment by bang88** [comment]
@Frexuz You need import moment locale inside your component, eg I need `zh-cn` so I have to 

```ts
// tslint:disable-next-line:no-var-requires
require('moment/locale/zh-cn.js')
```

Thats it.

**Comment by Mexxerio** [comment]
Doesn't work for me. See https://github.com/FaridSafi/react-native-gifted-chat/issues/634

**Comment by Frexuz** [comment]
@bang88 works :)
