### ISSUE TITLE
message no showing

### ISSUE THREAD

**Issue by JayricMok** [FaridSafi/react-native-gifted-chat#615]
I just added this module, and I try the example to send some message. But nothing is showing up in the screen (no bubble no text), I `console.log(this.state.messages);` inside the `render` function, array of message is there. 

Example I used:

	import { GiftedChat } from 'react-native-gifted-chat';

	class Example extends React.Component {

	  state = {
	    messages: [],
	  };

	  componentWillMount() {
	    this.setState({
	      messages: [
	        {
	          _id: 1,
	          text: 'Hello developer',
	          createdAt: new Date(),
	          user: {
	            _id: 2,
	            name: 'React Native',
	            avatar: 'https://facebook.github.io/react/img/logo_og.png',
	          },
	        },
	      ],
	    });
	  }

	  onSend(messages = []) {
	    this.setState((previousState) => ({
	      messages: GiftedChat.append(previousState.messages, messages),
	    }));
	  }

	  render() {
	    return (
	      <GiftedChat
	        messages={this.state.messages}
	        onSend={(messages) => this.onSend(messages)}
	        user={{
	          _id: 1,
	        }}
	      />
	    );
	  }

	}

**Comment by vgorte** [comment]
Hello @JayricMok, 

try something like this: 

```

import React from 'react';
import {
  StyleSheet,
} from 'react-native';

import {GiftedChat, Actions, Bubble} from 'react-native-gifted-chat';

export default class Example extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      messages: [],
      loadEarlier: true,
      typingText: null,
      isLoadingEarlier: false,
    };
  }

    componentWillMount() {

      this.setState({
        messages: [
          {
            _id: 1,
            text: 'Hello developer',
            createdAt: new Date(),
            user: {
              _id: 2,
              name: 'React Native',
              avatar: 'https://facebook.github.io/react/img/logo_og.png',
            },
          },
        ]
      });
    }

    onSend(messages = []) {
      this.setState((previousState) => ({
        messages: GiftedChat.append(previousState.messages, messages),
      }));
    }

    render() {
      return (
        <GiftedChat
          messages={this.state.messages}
          onSend={(messages) => this.onSend(messages)}
          user={{
            _id: 1,
          }}
        />
      );
    }
}

const styles = StyleSheet.create({
  footerContainer: {
    marginTop: 5,
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 10,
  },
  footerText: {
    fontSize: 14,
    color: '#aaa',
  },
});

```

Note: This is the RNGC example with your code so you most likely don't need everything. You need to define the state in your constructor, which you were missing completely.
Should work like this and can be closed if you don't have any more questions or problems.

**Comment by JayricMok** [comment]
@vgorte Yes I tried to put `constructor` , still nothing show up. but i `console` the message , there is many array of message that I sent.

**Comment by vgorte** [comment]
So the code I posted does not work for you?

**Comment by JayricMok** [comment]
@vgorte yes, nothing show up. json stringify the `this.state.messages` have data : 

	[{
		"text": "hey what sup",
		"user": {
			"_id": 1
		},
		"createdAt": "2017-10-24T09:24:03.329Z",
		"_id": "c92e58c0-3f42-4488-b3e3-e6dd22818cca"
	}, {
		"_id": 1,
		"text": "Hello developer",
		"createdAt": "2017-10-24T09:23:43.504Z",
		"user": {
			"_id": 2,
			"name": "React Native",
			"avatar": "https://facebook.github.io/react/img/logo_og.png"
		}
	}]

**Comment by vgorte** [comment]
Do you have the latest version of RN and the latest gifted chat?

**Comment by JayricMok** [comment]
@vgorte how to check gifted chat version ? sorry im totally new. just added this module today

**Comment by vgorte** [comment]
Navigate to your app directory via terminal and try something like 

`react-native --version`

**Comment by JayricMok** [comment]
@vgorte for check react-native version is `react-native -v` how bout `react-native-gifted-chat` ?

**Comment by vgorte** [comment]
@JayricMok look into your package.json file and you should see gifted chat and your current version.

**Comment by JayricMok** [comment]
@vgorte I still facing still issue, send no message showing. 

react-native-cli: 2.0.1
react-native: 0.48.4
react-native-gifted-chat:0.30

**Comment by sourcesoft** [comment]
use lazy load for your navigation. If you're using `react-navigation` change `lazy` to true
https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig

**Comment by gigaga** [comment]
Hi,
I have the same issue on my Honor 8 under Android 7.
I haven't this problem (with the same code) from Android 8 emulator and from Android 5 device (HTC).

**Comment by Daley** [comment]
I have the same issue 
react-native: 0.48.2
react-native-gifted-chat:0.30

**Comment by sunny20131314** [comment]
how are you solve this issue? I have the same issue on my Honor 8 under Android 7 too. @gigaga

**Comment by subodhpareek18** [comment]
I think it could be a styling issue as well, especially if you're using it alongside other UI frameworks like native-base, try and force a height for your component.

**Comment by gigaga** [comment]
@sunny20131314
Not resolved :-(. In fact I can see elements in dom but it is not displayed.

**Comment by ShibinSurendranath** [comment]
The issue is unresolved with no error logged. I can see only the message box at bottom, but nothing else (none of the messages).
RN : 0.47
react-native-gifted-chat:0.3.0

Can styling be made part of documentation?

**Comment by sunny20131314** [comment]
@gigaga
i solve it with #486.

**Comment by gigaga** [comment]
@sunny20131314 thanks a lot ;)

**Comment by LuisRizo** [comment]
I had the same problem, fixed it with thanks to @sourcesoft.

My TabNavigator now looks like:
`const TalentTabs = TabNavigator(
    {
        ...
    },
    {
        lazy: true,
        ...
    }
)`

**Comment by OneOfOne** [comment]
```
RN: 0.55.4
react-native-gifted-chat: 0.4.3
```

Still have the problem, not using TabNavigator, #486 didn't help.
