### ISSUE TITLE
How to proper update message? (Eg: sent/received ticks)

### ISSUE THREAD

**Issue by ahmadsyamim** [FaridSafi/react-native-gifted-chat#618]
#### Issue Description

How to proper update message? (Eg: sent/received ticks)

#### Steps to Reproduce / Code Snippets

i use
GiftedChat.append(previousState.messages, data)
but the updated message moved. I want to update the message without moving the messages 

#### Additional Information

* React Native version: 0.47.2
* react-native-gifted-chat version: 0.2.8
* Platform(s) (iOS, Android, or both?): both

**Comment by vgorte** [comment]
Hello @ahmadsyamim , 
what exactly do you mean when you say : 

> I want to update the message without moving the messages 

Can you explain that in more detail? 

Do you want to add a message to an existing bubble?

**Comment by ahmadsyamim** [comment]
Hello @vgorte ,

i want to update existing messages. May i know the most proper way to do it?
Highly appreciated.

**Comment by GeoffreyPlitt** [comment]
+1

**Comment by mafiusu** [comment]
You could update your message with setState and set the received to true. Each message has a unique id.

**Comment by webraptor** [comment]
@mafiusu that won't work if messages are props and you state's kept using redux, for example... Updating a message will not trigger a re-render because of _MessageContainer.js_ _componentWillReceiveProps_ not handling changes properly.

**Comment by xcarpentier** [comment]
I close it here because it's related to this one: https://github.com/FaridSafi/react-native-gifted-chat/issues/654

**Comment by leonyhenn** [comment]
I just found an easy fix. Fork this repo, and in GiftedChat.js, instead of using this._messages and this.getMessages() to update messages to MessageContainer, you set a state (like this.state_messages) and call setState in componentDidMount(and comment out this.setMessages())

the bug of tick not rerendering on receive is due to this._messages and this.getMessages() do not rerender the GiftedChat component, but setState does the job.

**Comment by MarcoLLeite** [comment]
@leonyhenn That sounds like a good solution. 
Do you know if that use of the state was fixed already?
What about the tick? I have been noticing some weird behaviour with it as well. I use the local state to store me my messages and call setState() to update the sent and received ticks, but they don't seem to reflect on the ui until I do some other action like dismiss the keyboard. Maybe this is also related to the first issue you mentioned?
