### ISSUE TITLE
Prevent Keyboard to dismiss

### ISSUE THREAD

**Issue by jbosnjakovic** [FaridSafi/react-native-gifted-chat#619]
We have encountered one weird issue with the keyboard. Recorded behavior is expected and acceptable I guess, when application loose focus from the input text field it causes the keyboard to dismiss. How can we prevent that behavior and if the keyboard is up and microphone button is clicked, the keyboard needs to stay up? We have onPressIn and onPressOut events on the recording button. The application is rendered in the iPhone simulator. Any suggestions are welcome. Thanks

![bug with keyboard](https://user-images.githubusercontent.com/22400536/31997140-2ef1bd08-b98b-11e7-9d96-43c0722773d5.gif)

**Comment by xcarpentier** [comment]
I think this is because you lose focus on type mic...

**Comment by Uysim** [comment]
+1
