### ISSUE TITLE
Render custom component inside message area

### ISSUE THREAD

**Issue by leonel-lordford** [FaridSafi/react-native-gifted-chat#627]
Hi there and thanks for this amazing component... I have a question: can I add some "special messages" for the user to take some action in the app, like navigate to a specific screen or pop up a modal or similar? 

Thank you.

**Comment by MehdiAlouafi** [comment]
The documentation mentions those three props : 

renderMessage (Function) - Custom message container

renderMessageText (Function) - Custom message text

renderMessageImage (Function) - Custom message image

The first one fits your needs as it can return some TouchableOpacity container that, onPress, trigger whatever action you'd like

**Comment by ownikss** [comment]
I thing props renderCustomView is easier for this aim. If you want show your message in same bubble as other messages.
But if you want show specific view see MehdiAlouafi solution

**Comment by leonel-lordford** [comment]
I'll check both solutions ! Thanks...

**Comment by xcarpentier** [comment]
@leonel-lordford any news?

**Comment by xcarpentier** [comment]
Feel free to re-open if you need more informations.

**Comment by zarackritter** [comment]
Hi there, I feel like my issue has something to do with that.

I'm working on a chatbot and sometimes the chatbot response comes with a file or custom text. My question is, how can I show a customView after a bubble in a conversation?

Example:
Person: What about my payment?
Chatbot: Here is some information for you:
Chatbot: (image or file in another bubble)

I tried to put renderMessageText param inside message object but didn't work.

Thanks for your time friends!

**Comment by xcarpentier** [comment]
https://snack.expo.io/@xcarpentier/gifted-chat <- here you can see example of renderCustomView

**Comment by zarackritter** [comment]
Works fine!! Thank you!
