### ISSUE TITLE
Appending message using FCM event

### ISSUE THREAD

**Issue by KwangsubAhn** [FaridSafi/react-native-gifted-chat#632]
#### Issue Description

An error occurred when appending a message 

#### Steps to Reproduce / Code Snippets
* Below codes works find when I use with local method, but when I put the code inside FCM event method (  FCM.on(FCMEvent.Notification, async (notif) => ()  ), it throws an error.

```
FCM.on(FCMEvent.Notification, async (notif) => {
      if (this._mounted && notif.action === FCM.BACKEND_ACTION_MESSAGE) {
        const { state } = this.props.navigation;
        if (notif.chat_room_id === state.params.chatRoomId) {
          let arrMsg = [];
          let objMsg = {};
          objMsg._id = notif.message_id;
          objMsg.createdAt = new Date(notif.date);
          objMsg.text = notif.message;
          let objUsr = {};
          objUsr._id = parseInt(notif.sender_contact_id);
          objUsr.avatar = 'https://avatars0.githubusercontent.com/u/9919?v=4&s=40';
          objMsg.user = objUsr;
          
          arrMsg.push(objMsg);
          this.stateMessages = GiftedChat.append(this.stateMessages, arrMsg);  //### THIS THROWS AN ERROR
        }
      }
    });
```

#### Error Msg
Invalid Date
<unknown> 
.\node_modules\react-native-gifted-chat\src\MessageContainer.js: 44:38

PrepareMessages
.\node_modules\react-native-gifted-chat\src\MessageContainer.js: 40:28

componentWillRecediveProps
.\node_modules\react-native-gifted-chat\src\MessageContainer.js: 70:46

#### Additional Information

* React Native version: "react-native": "^0.48.4"
* react-native-gifted-chat version: "react-native-gifted-chat": "^0.2.7"
* FCM: "react-native-fcm": "^9.6.2"
* Platform(s) (iOS, Android, or both?): BOTH

**Comment by brunocascio** [comment]
Try to update to version 0.3.0

**Comment by andreluisjunqueira** [comment]
Same problem !

**Comment by brunocascio** [comment]
@andreluisjunqueira Which version are you using?

**Comment by andreluisjunqueira** [comment]
latest version.
when a try in debug mode works, but when a disable debug mode, i get this error "invalid date"

**Comment by brunocascio** [comment]
Check if the date variable Is not undefined. It is not seems to be an error of GC.. @KwangsubAhn how do you resolve this? :)

**Comment by prasannaballal** [comment]
The gifted chat expects the Date object. So if you are not sending date object it will not work in debug mode. When debugging with chrome, chrome does some magic and makes it work.
