### ISSUE TITLE
momentJS locale not accessible in GiftedChat component

### ISSUE THREAD

**Issue by Mexxerio** [FaridSafi/react-native-gifted-chat#634]
#### Issue Description

I'm trying to make use of the moment-js locales and I'm importing my required locale in my component. When I use moment normally it works fine and it lists my locale under `moment.locales()`

But somehow the `GiftedChat` component does not have access to that imported locale and when I put `console.log(moment.locales())` into `GiftedChat` it only listed `'en'` as available.

#### Steps to Reproduce / Code Snippets

```javascript
import React, { Component } from 'react'
import moment from 'moment'
import 'moment/locale/de'
import { GiftedChat } from 'react-native-gifted-chat';

class Example extends React.Component {

  state = {
    messages: [],
  };

  componentWillMount() {
    this.setState({
      messages: [
        {
          _id: 1,
          text: 'Hello developer',
          createdAt: new Date(),
          user: {
            _id: 2,
            name: 'React Native',
            avatar: 'https://facebook.github.io/react/img/logo_og.png',
          },
        },
      ],
    });
  }

  onSend(messages = []) {
    this.setState((previousState) => ({
      messages: GiftedChat.append(previousState.messages, messages),
    }));
  }

  render() {
    console.log(moment.locales());
    return (
      <GiftedChat
        messages={this.state.messages}
        onSend={(messages) => this.onSend(messages)}
        user={{
          _id: 1,
        }}
        locale='de'
      />
    );
  }

}
```

The `console.log` in the render function returns:
`["en", "de"]`

But if I put the same in the `initLocale` function of `GiftedChat.js` it only returns `["en"]`
https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/GiftedChat.js#L122

#### Expected Results

I'm expecting that the imported locales is accessible in `GiftedChat`, but it's not.

#### Additional Information

* React Native version: `^0.47.2`
* react-native-gifted-chat version: `^0.3.0`
* Platform(s) (iOS, Android, or both?): Android

**Comment by Mexxerio** [comment]
Ugh ... so I had momen on version `^2.19.2`

After I changed it to the same version GiftedChat is using, which is `^2.19.0` it magically worked.

**Comment by Frexuz** [comment]
We shouldn't have to downgrade our project dependencies for this to work :/
