### ISSUE TITLE
onInputTextChanged is triggered without typing after the componentDidMount()

### ISSUE THREAD

**Issue by mafiusu** [FaridSafi/react-native-gifted-chat#638]
#### Issue Description

The onInputTextChanged is triggered automatic when the chat view is loaded after componentDidMount( ). I need the onInputTextChanged to display that a user is currently writing to the chat. But always when a users enters a chat the method is fired automatic and it displays that someone is currently writing.

#### Steps to Reproduce / Code Snippets

`    this.onTyping = this.onTyping.bind(this);`
`    onInputTextChanged={this.onTyping}`

#### Expected Results

onInputTextChanged only fires when a user is currently writing.

#### Additional Information

* React Native version: 0.49.5
* react-native-gifted-chat version: react-native-gifted-chat@0.3.0
* Platform(s) (iOS, Android, or both?): both

**Comment by Prajna12** [comment]
Where should this code snippet be written? Adding it within GiftedChat tag is giving me errors

**Comment by mcmar** [comment]
This bug is affecting me too. In my case, I am updating text with `this.setState` in my `componentDidMount` and this is immediately overwriting it with the previous version of my text. That's because React calls `componentDidMount` on parents before children and also because all of the `componentDidMount` are called before `this.setState` takes effect (this may change w/ async rendering in React 17+).
I now have to differentiate this initial "fake" onInputTextChanged from "real" onInputTextChanged events. There's really no reason to call `onInputTextChanged` inside `componentDidMount`.

**Comment by CoderHuzaifa** [comment]
I made this custom logic for this:
this.state = {        
 isFirstTime:true,
 request:this.props.message
};

setCustomText =(Text)=>{
     
      if(Text == '' && !this.state.isFirstTime){
        this.setState({request:Text})
      }if(Text == '' && this.state.isFirstTime){
        this.setState({isFirstTime:false})
      }if(Text !== '' && !this.state.isFirstTime){
        this.setState({request:Text})
      }
    }
In OnTextChangedText:
           <GiftedChat style={{backgroundColor:'#3498db'}}
            text={this.state.request}
            onInputTextChanged={text => this.setCustomText(text)}
            messages={this.state.messages}
            onSend={this.onSend}
            renderAvatar ={null}
          user={{
              _id: 1,
            }}
          />
In my case it was clearing the pre-written text that I passed as props so I created this custom logic.

**Comment by MylesCaley** [comment]
Having same issue, slightly different workaround. We have a throttle in place because this is what we are using to notify the server that a user is responding.

```
render()

...

// this.workaround638 just sets the state for isTypingFirstTime to false.
const typingCallback = this.state.isTypingFirstTime
      ? this.workaround638
      : _.throttle(this.props.typing, 5000, { leading: true });

return (
      <View style={{ backgroundColor: "white", height: "100%", width: "100%" }}>
        <GiftedChat
          onInputTextChanged={typingCallback}
```

**Comment by marcin03** [comment]
I resolved this by modifying @Huzaifaak method:
`
constructor(props) {
    super(props);
    this.state = {isFirstInputTextUpdate:true};
}
  firstInputTextUpdate(){
    this.setState({isFirstInputTextUpdate:false})
  }

`
and in GiftedChat component:
`
<GiftedChat
onInputTextChanged={isFirstInputTextUpdate?firstInputTextUpdate:inputText => updateInputText(inputText)}
//...other props
/>
`

**Comment by marcin03** [comment]
I resolved this by modifying @Huzaifaak method:
```jsx
constructor(props) {
super(props);
this.state = {isFirstInputTextUpdate:true};
}

firstInputTextUpdate = () => {
this.setState({isFirstInputTextUpdate:false})
}
```
and in GiftedChat component:
```jsx
<GiftedChat
onInputTextChanged = {isFirstInputTextUpdate ? this.firstInputTextUpdate : inputText=>updateInputText(inputText)}
//...other props
/>
```

**Comment by inrecovery** [comment]
A clean solution that has worked well for us is to declare an isTyping state that defaults to false. Following this example you can keep logic outside of the render:

```jsx
const [isTyping, setIsTyping] = useState(false);
```

Your handler could look something like this:

```jsx
const onTypingHandler = () => {
    setIsTyping(true);

    isTyping 
      ? startTyping() 
      : endTyping()

    ...the rest the method / end typing handler
 };

```


And you just call your handler within GiftedChat
```jsx
<GiftedChat onInputTextChanged={onTypingHandler} ... /> 
```

**Comment by ArietNyshanbaev** [comment]
> A clean solution that has worked well for us is to declare an isTyping state that defaults to false. Following this example you can keep logic outside of the render:
> 
> ```js
> const [isTyping, setIsTyping] = useState(false);
> ```
> 
> Your handler could look something like this:
> 
> ```js
> const onTypingHandler = () => {
>     setIsTyping(true);
> 
>     isTyping 
>       ? startTyping() 
>       : endTyping()
> 
>     ...the rest the method / reset state ...
>  };
> ```
> 
> And you just call your handler within GiftedChat
> 
> ```js
> <GiftedChat onInputTextChanged={onTypingHandler} ... /> 
> ```

Nice trick but using state and updating it will lead us to re-rendering of component so we can use local variable to deal with that as :

`
// local variable
let eliminateFirstTimeTyping =  true;


// handler function
const handleTypeing = () =>  {
      if (eliminateFirstTimeTyping) {
	      eliminateFirstTimeTyping = false;
	      return null;
      }

      ...the rest the method / reset state ...
}

// render function

<GiftedChat onInputTextChanged={onTypingHandler} ... /> 
`

**Comment by sehrish30** [comment]
I think the simplest solution is to only trigger the function when user has typed something

const onTypingHandler = (text) => {
    if(text) {
     ...
   }
}

<GiftedChat onInputTextChanged={onTypingHandler} ... />

**Comment by hardikbotsplash** [comment]
@sehrish30  the above condition won't work when removing the text and last text wont be cleared as the condition will be false and will not cleared last text.

**Comment by KodyKendall** [comment]
Pretty surprised this is marked as closed when a solution hasn't been fixed in the core GiftedChat component. Shouldn't this be an active bug being tracked?
