### ISSUE TITLE
Render different kind of messages

### ISSUE THREAD

**Issue by Waltari10** [FaridSafi/react-native-gifted-chat#639]
Is there anyway to render different kinds of message layouts for different messages? I have property 'type' for my message objects and would like to change the message style depending on that property. How would I do that with Gifted Chat?

Rigth now my renderMessage function looks like this:

```
renderMessage (props) {
    return (
      <Message
        {...props}
        {...messageStyles}
      />
    )
  }
```

**Comment by mafiusu** [comment]
You could implement renderCustomView in your GiftedChat component. There you return your custom Component you want to display and from the render method of the new view you can check the types with:

```
     if(this.props.currentMessage.type) {
        return ( ...)
    }
```

Have also a look at the example of giftedchat. The LocationView will be displayed as a different kind of message.
