### ISSUE TITLE
how can change the color of the message box

### ISSUE THREAD

**Issue by dibiro** [FaridSafi/react-native-gifted-chat#640]
I need to change the color of the message box from blue to orange

**Comment by Frexuz** [comment]
```
renderBubble (props) {
    return (
      <Bubble
        {...props}
        wrapperStyle={{
          right: {
            backgroundColor: Colors.primary
          }
        }}
      />
    )
  }

<GiftedChat
  ...
  renderBubble={this.renderBubble}
```

**Comment by xcarpentier** [comment]
I close this issue but create a FAQ in readme to refer it: https://github.com/FaridSafi/react-native-gifted-chat#questions

**Comment by alamorre** [comment]
I see what you're doing but where does that Bubble component come from and how do you import it?

**Comment by kg-currenxie** [comment]
It's just the normal bubble from gifted-chat, but we just override the default styles

`import { Bubble } from 'react-native-gifted-chat'`

**Comment by juanmanuelco** [comment]
And if i wanna change the text color on bubble ?

**Comment by TaiPhamDuc** [comment]
This is my code: 
`         <Bubble
          wrapperStyle={{
            left: {
              backgroundColor: 'white',
              borderRadius: 5,
            },
            right: {
              backgroundColor: 'white',
              borderRadius: 5,
            },
          }}
          {...props}
        />`
the right bubble still blue, how can i change this color?

**Comment by boukarsall** [comment]
renderBubble (props) {
    return (
      <Bubble
        {...props}
        textStyle={{
            right: {
              color: "white"
            },
            left: {
              color: "white"
            }
          }}
      />
    )
  }

<GiftedChat
  ...
  renderBubble={this.renderBubble}

**Comment by boukarsall** [comment]
```
textStyle={{
            right: {
              color: "white"
            },
            left: {
              color: "white"
            }
          }}
```

**Comment by boukarsall** [comment]
```
renderBubble (props) {
      return (
        <Bubble
          {...props}
          textStyle={{
            right: {
              color: "white"
            },
            left: {
              color: "white"
            }
          }}
        />
      )
    }
```

**Comment by hackrx** [comment]
Can anyone tell me how can I change the shape of the message box
like this 
![image](https://user-images.githubusercontent.com/54453778/87680751-6bc2ac80-c79b-11ea-877c-69f2daa99f50.png)

**Comment by Nagasai97** [comment]
i too need to change the shape of this box...

**Comment by kg-currenxie** [comment]
Haven't tried, but it seems that you have to implement your own complete component, like the bubble itself: https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/Bubble.tsx 🤔

**Comment by capridigitalmedia** [comment]
how do i change the entire chat background color, and foregrounnd color

**Comment by deidalopez** [comment]
@capridigitalmedia This may be helpful
https://github.com/FaridSafi/react-native-gifted-chat/issues/268#issuecomment-263147449
> Simple solution.
> 
> ```
> <View style={{backgroundColor: '#yourcolor'}}>
>   <GiftedChat ...props />
> </View>
> ```

**Comment by saurabh-000** [comment]
@dibiro 
**you can use this prop of react native gifted chat**
`messagesContainerStyle={{backgroundColor:Colors.screenBackgroundColor,}}`

**Comment by saurabh-000** [comment]
@capridigitalmedia  
**you can use this prop of react native gifted chat to change the background color of**
`messagesContainerStyle={{backgroundColor:Colors.screenBackgroundColor,}}`

**Comment by rytilahti-juuso** [comment]
Below is a more complete example on how to modify the _*styles*_ of the text bubbles using functional components:
```javascript
import { GiftedChat, Bubble } from 'react-native-gifted-chat';
// ...Other imports

export default function ChatScreen() {
  
  const renderBubble = props => { 
    return ( 
      <Bubble 
        {...props} 
        textStyle={{ 
              right: { color: 'green', backgroundColor:'black' }, 
        }} 
        wrapperStyle={{
            right: { backgroundColor: 'red', }, 
            left: { backgroundColor: 'orange', }, 
        }} 
      />
    )}
  //... Other necessary code
  
  return (
    <GiftedChat
      renderBubble={renderBubble}
      // Other props..
    />
  );
}
```
