### ISSUE TITLE
Componenent keeps re-rendering

### ISSUE THREAD

**Issue by Medardas** [FaridSafi/react-native-gifted-chat#641]
When entering view with even the simplies example of GiftedChat from readme it keeps re-rendering the GiftedChat input field component infinitely.
This probably causes view's nativeEvent keep being fired in function onMainViewLayout() and updating height. 
Although, frankly latter could be a reason for the former as well. Couldn't work it out yet.

Before react-native 0.50.3 update it seemed to work fine

* React Native version: "react-native": "^0.50.3",
* react-native-gifted-chat version: "react-native-gifted-chat": "^0.3.0",
* Platform: Android, both on devices (nexus 6p) and various nexus emulators

**Comment by atyenoria** [comment]
+1
