### ISSUE TITLE
Messages show from the top - strange behavior

### ISSUE THREAD

**Issue by niros001** [FaridSafi/react-native-gifted-chat#646]
Hi i use RN v0.44 and gifted-chat v0.3.0
when i used the v0.2.7 i used that parameter:
```
listViewProps={{
                    removeClippedSubviews: false,
                    contentContainerStyle: { 'flexGrow': 1, 'justifyContent': 'flex-end' }
                }}
```
to show all the messages from the top and it looks perfect.
After i upgrade to v0.3.0 i can see all the messages from the top but the height is in the size of the screen for example:
If i have 2 messages i have "margin" or something between them and i see one message on the top and one message on the bottom, if i have 3 messages i have the same with another message in the middle, and so on...

**Comment by dtuan** [comment]
I think this is due to the change on "react-native-invertible-scroll-view": 
https://github.com/expo/react-native-invertible-scroll-view/commit/b493737e1b3696c8a828f3a90f09b441d7ee83ea

**Comment by mafiusu** [comment]
Is there any solution for this case?

**Comment by theberbie** [comment]
+1

**Comment by theberbie** [comment]
Solution: https://github.com/FaridSafi/react-native-gifted-chat/issues/599
