### ISSUE TITLE
Is there a way to manually dismiss the keyboard?

### ISSUE THREAD

**Issue by operate2v** [FaridSafi/react-native-gifted-chat#647]
Is there a way to manually dismiss the keyboard?
For example, if you type certain text, the keyboard dismisses.

* React Native version: 0.49.3
* react-native-gifted-chat version: latest
* Platform(s) (iOS, Android, or both?): both

**Comment by ownikss** [comment]
import dismissKeyboard from 'dismissKeyboard';

// for dismiss keyboard on your event:
dismissKeyboard();

**Comment by leonel-lordford** [comment]
Worked excellent !!!
Thanks...
LordFord.

**Comment by xcarpentier** [comment]
I close this issue but create a FAQ in readme to refer it: https://github.com/FaridSafi/react-native-gifted-chat#questions

**Comment by PolThm** [comment]
Sorry I don't understand where to put "import dismissKeyboard from 'dismissKeyboard';" and "dismissKeyboard();", can you help me please ?

**Comment by ownikss** [comment]
You should use module Keyboard from react-native to hide keyboard.

```
import { Keyboard } from 'react-native';

Keyboard.dismiss();
```

**Comment by PolThm** [comment]
Thank your for your response !

My research was finally "how to remove the keyboard", and I've finally succeeded with those 2 lines in the props : 
renderInputToolbar={() => {}}
minInputToolbarHeight={0}

I've another question (sorry I don't know where else to post it) : 
Is there a way to pass a function when I press the screen (because if I put a <TouchableWithoutFeedback> as parent it doesn't scroll anymore).

Thank you !

**Comment by kerubkim** [comment]
How did you guys detect user when pressing out of the textinput?
I noticed on android the keyboard stays even when I tried pressing out

**Comment by ownikss** [comment]
@kerubkim, I'm not sure that you need detect press out of textinput. If you want to hide keyboard on tap on scrollview, you can use `keyboardShouldPersistTaps='never'` ScrollView prop.

If you really want to handle click out of input, you can try `onStartShouldSetResponderCapture` prop for view. Add it to some root view, and function will be triggered on every screen touch

**Comment by FareeKhan** [comment]
> @kerubkim, I'm not sure that you need detect press out of textinput. If you want to hide keyboard on tap on scrollview, you can use `keyboardShouldPersistTaps='never'` ScrollView prop.

ggg

**Comment by mikedoubintchik** [comment]
What event do we tap into to dismiss keyboard on scoll?
