### ISSUE TITLE
The Textinput box does not support displaying emojis

### ISSUE THREAD

**Issue by yazhengwang** [FaridSafi/react-native-gifted-chat#648]
#### Issue Description

I add some emoji for the message, but this Textput does not support ! 

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): both

**Comment by yazhengwang** [comment]
![image](https://user-images.githubusercontent.com/14901532/33202490-b1211332-d137-11e7-9b9f-9a735fd5d79c.png)

**Comment by adrianchinghc** [comment]
@yazhengwang Do fill up the issue related information in your description and how can we reproduce this issue. I'm on Gifted Chat `v0.3.0` and React Native `v0.49.0` and emojis are showing up in my text input.
