### ISSUE TITLE
Clicking on the Input Text keyboard id hiding the input text and it is not moving upwards

### ISSUE THREAD

**Issue by bvnbbn** [FaridSafi/react-native-gifted-chat#651]
I have integrated the gifted chat in  my  android app but when I click on the input text keyboard appears but input text does not move up with the keyboard and the input text is hidden. I am testing it on a device.

import React, { Component } from 'react';
import { Container, Header, Content, Button, Text, Icon , Body} from 'native-base';
import {  StyleSheet , View , TextInput,KeyboardAvoidingView , Platform, ScrollView , TouchableOpacity } from 'react-native';

import { GiftedChat } from 'react-native-gifted-chat';

class ChatMessageScreen extends React.Component {

  state = {
    messages: [],
  };

  componentWillMount() {
    this.setState({
      messages: [
        {
          _id: 1,
          text: 'Hello developer',
          createdAt: new Date(),
          user: {
            _id: 2,
            name: 'React Native',
            avatar: 'https://facebook.github.io/react/img/logo_og.png',
          },
        },
      ],
    });
  }

  onSend(messages = []) {
    this.setState((previousState) => ({
      messages: GiftedChat.append(previousState.messages, messages),
    }));
  }

  render() {
    return (
      <GiftedChat
        messages={this.state.messages}
        onSend={(messages) => this.onSend(messages)}
        user={{
          _id: 1,
        }}
      
      />
    );
  }

}
export default ChatMessageScreen;

**Comment by hakuj** [comment]
@bvnbbn did you manage to fix this issue? I ask because I am having this issue as well
