### ISSUE TITLE
Animating Height Causes Clipping Until You Scroll

### ISSUE THREAD

**Issue by chrisbull** [FaridSafi/react-native-gifted-chat#652]
#### Issue Description

I have a view that needs to have a minimum view state (44px), where I just show the text input. And then when tapped [TextInput in GiftedChat] the view height is then increased to full view.

However the bug is that there seems to be a clipping issue and only a single (sometimes a few) but not all rows are re-rendered. And then it stays this way until you scroll the view.

Then when a user collapses the view back to the minimum state, and then re-opens, the view is clipped again, and the cycle persists.

My guess is there is some re-rendering code that is causing the view to render the single row ahead of time, but not all the rows, and then while animating, it's not getting updated. 

I've tried several approaches to make this work, including making a masked view with a full height view inside, and only animate the masked view - in hopes that the inside view will render all rows and correct height, and then the masked view will only animate up and down, but the inner view will always have a full height view. 

Here is a screen recording:
![image](https://user-images.githubusercontent.com/753112/33343650-fd5fe998-d43a-11e7-986f-93605a2d2989.GIF)

#### Steps to Reproduce / Code Snippets

```
<Animated.View
  style={[
    styles.chatAnimatedContainer,
    {
      height: this.state.chatAnimation.interpolate({
        inputRange: [0, 1],
        outputRange: [Metrics.chatBarHeight, Metrics.screenHeight],
      }),
    },
  ]}
>
  <View style={styles.chatContainer}>
    <GiftedChat
      ref={ref => (this._giftedChat = ref)}
      keyboardShouldPersistTaps="never"
      messages={this.state.messages}
      onSend={this.onSend}
      renderBubble={this.renderBubble}
      renderFooter={this.renderFooter}
      renderSystemMessage={this.renderSystemMessage}
      showUserAvatar
      user={{ _id: this.props.handle }}
      renderInputToolbar={() => (
        <ChatMessageBar
          unreadCount={this.state.unreadCount}
          onSend={this.onSend}
          onChangeText={this.onChangeText}
          onFocus={this.openChat}
        />
      )}
    />
  </View>
</Animated.View>
```

#### Expected Results

Expecting that when rending the height of the view or the container view, that all rows would appear naturally instead of appearing suddenly when scrolling.

#### Additional Information

* "react-native": "^0.50.3",
* "react-native-gifted-chat": "^0.3.0",
* Platform(s) (iOS, Android, or both?): iOS

**Comment by kevinsperrine** [comment]
@chrisbull Did you ever find a solution to this? I've come across the same problem and have resorted to simply not using animation on the iOS side.

**Comment by chrisbull** [comment]
@kevinsperrine  I don't believe I ever did. The issue lays with the get layout of the frame when it initializes the GiftedChat. If I were to revisit this, I might recommend putting the <View><GiftedChat> into a separate React.Component (call it GiftedChatWrapper), and then the above would be <Animated.View><GiftedChatWrapper /></Animated.View>... then in the GiftedChatWrapper, I'd manually set the height of the component in componentDidMount (or something in one of the lifecycle methods). This way when the <GiftedChat> mounts within the render of GiftedChatWrapper, it should hopefully have the correct height and width without clipping. Hope this helps.
