### ISSUE TITLE
Rename Send label, LoadEarlier label, and Copy Text options.

### ISSUE THREAD

**Issue by just4fun** [FaridSafi/react-native-gifted-chat#653]
#### Issue Description

1. `<Send />` and `<LoadEarlier />` shared same property `label` to indicate the text message, which means I could not rename them individually via `label` from top `<GiftedChat />` component in my local language.
2. I also want to rename `Copy Text` and `Cancel` for `<Bubble />` with my local language, but there are no properties exposed to top component.

#### Steps to Reproduce / Code Snippets

null

#### Expected Results

1. I can rename `Send` and `Load earlier messages` INDIVIDUALLY from top `<GiftedChat />` component.
2. I can rename `Copy Text` and `Cancel` from top `<GiftedChat />` component.

#### Additional Information

* React Native version: 0.42.2
* react-native-gifted-chat version: 0.1.4
* Platform(s) (iOS, Android, or both?): iOS

**Comment by mafiusu** [comment]
You could implement the renderSend Function as a prop for the gifted chat and there you will have a custom Send Btn (Label)

**Comment by leonel-lordford** [comment]
I just did that and worked OK ! I was able to change the label for an image representing Send action... works OK !
LordFord.

**Comment by just4fun** [comment]
@mafiusu yeah I can also use `renderLoadEarlier` and `renderBubble`. But what I want to do is to rename the text, not customize the original component such as use a icon for send action, hence the question here. Anyway, I think I should use these functions now.
