### ISSUE TITLE
How to render custom message object?

### ISSUE THREAD

**Issue by stlemon** [FaridSafi/react-native-gifted-chat#656]
#### Issue Description

want to render custom message object，
for example：
 <TouchableOpacity style={styles.Area} onPress={()=>{}}>
<Image source={require('../assets/xxxx.png')} resizeMode='contain' style={styles.Image}/>
</TouchableOpacity>

#### Expected Results

render this component as a message 

#### Additional Information

* React Native version: 0.44.3
* react-native-gifted-chat version: 0.27
* Platform(s) (iOS, Android, or both?): iOS

can you  tell me ? thanks!

**Comment by leonel-lordford** [comment]
I need this too.... someone recomended me to use renderCustomView but haven't tried yet :-(

**Comment by alexbowers** [comment]
Some documentation on this would be very useful

**Comment by stlemon** [comment]
Thanks a lot,everyone ! 
I've done it by looking at the example.
