### ISSUE TITLE
Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by sabbyt54** [FaridSafi/react-native-gifted-chat#659]
#### Issue Description

- Upon importing ```{ GiftedChat }``` into file, there is an error that states ```Cannot read property 'style' of undefined```

#### Steps to Reproduce / Code Snippets

```
npm install react-native-gifted-chat
import { GiftedChat } from 'react-native-gifted-chat'
```

#### Expected Results

No error importing module

#### Additional Information

* React Native version: 0.42.0
* react-native-gifted-chat version: 0.3.0
* Platform(s) (iOS, Android, or both?): Both

**Comment by xcarpentier** [comment]
Just on importing?
Could you please copy / past here your code?
Thanks

**Comment by Silvercast** [comment]
I think it's because of incompatible RN, you are using RN 0.42

**Comment by xcarpentier** [comment]
https://github.com/FaridSafi/react-native-gifted-chat/blob/master/README.md#dependency
