### ISSUE TITLE
Popover when clicking on Avatar

### ISSUE THREAD

**Issue by 12tp12** [FaridSafi/react-native-gifted-chat#660]
#### Issue Description

I want to implement a popover that pops right after clicking on a specific avatar,
what is the best implementation in this case and how? using renderAvatar props?

Thanks

* React Native version:  last version
* react-native-gifted-chat version:  last version
* Platform(s) (iOS, Android, or both?): both

**Comment by mafiusu** [comment]
You could use the onPressAvatar prop in the GiftedChat Component. I would simply show a Modal.

**Comment by 12tp12** [comment]
I thought about it, but if i want to show the modal next to the avatar?
the onPressAvatar  function returns 'user', without X,Y coordinates of the pressed avatar.

Thanks!

**Comment by LMestre14** [comment]
Why not render your own avatar? The component has a renderAvatar function option where you render your avatar.
You could use that and render an avatar with a touchableOpacity, and if touched render something above it

**Comment by xcarpentier** [comment]
@12tp12 Yes you should use renderAvatar...

**Comment by 12tp12** [comment]
Thanks everyone!

**Comment by xcarpentier** [comment]
I close your issue, but I create a question pointing here: https://github.com/FaridSafi/react-native-gifted-chat/blob/master/README.md#questions
