### ISSUE TITLE
Date is always showing above the last message

### ISSUE THREAD

**Issue by mafiusu** [FaridSafi/react-native-gifted-chat#661]
#### Issue Description
The day of the message is always showing above the last message. But in earlier versions it is only shown if the message has a different date above the other message. See screenshot below, all 3 messages are from the same date.

![Screenshot](https://img1.picload.org/image/drwrgrrr/simulatorscreenshot-iphone6-20.png)

**Comment by mafiusu** [comment]
Anyone can assert that the Messages are inverted and they start from the top? My project uses a different version of GiftedChat without inverted, how can I update it to the latest version?

**Comment by mafiusu** [comment]
Thank you. I've just tested it and it looks very curious with inverted={false}. I have except that my messages are starting at the top (like WhatsApp) from the Container. Actually it is starting from the top but my new messages are not appending at the bottom, but rather at the top. 

I thought that inverted just starts messages at the bottom, but if not thats ok.

**Comment by xcarpentier** [comment]
I think inverted is not for you actually.
Maybe it will better to have an option start at top.

@cooperka & @brunocascio what do you think...

**Comment by brzonsea** [comment]
Has anyone solved this problem? I'm using the latest release v.0.4.1, and the same problem with the dates are occuring.
I also see the dates right above the last message. How can we address this problem?

**Comment by mafiusu** [comment]
Can you provide us your code.. how did you setup the GiftedChat, did you use the inverted prop?

**Comment by brzonsea** [comment]
Yes,  I used the new inverted prop.
I set inverted={false}

**Comment by mafiusu** [comment]
I don't see the use of the inverted prop atm, it's not working properly. You you want start the messages from the top rather from the bottom? If yes, the inverted prop don't support this.

**Comment by brzonsea** [comment]
yes, indeed I want my messages to start from the top. It seems this works when I set inverted={false}
but the dates are not showing correctly.

**Comment by whitmanc** [comment]
Just as a note, this issue was resolved in a PR that was merged in master (https://github.com/FaridSafi/react-native-gifted-chat/pull/810). Discussion can be seen at https://github.com/FaridSafi/react-native-gifted-chat/issues/789
