### ISSUE TITLE
Issue with renderCustomView not being fired

### ISSUE THREAD

**Issue by alexbowers** [FaridSafi/react-native-gifted-chat#663]
#### Issue Description

I can't seem to get renderCustomView to be called.

#### Steps to Reproduce / Code Snippets

```
<GiftedChat
            messages={this.state.messages}
            renderInputToolbar={() => null}
            minInputToolbarHeight={0}
            renderCustomView={() => { console.log('Called'); }}
          />
```

#### Expected Results

A conosle log saying `Called` to be output.

I have also tried with an actual View, but that wasn't being called either.

#### Additional Information

* React Native version: 0.48.4
* react-native-gifted-chat version: 0.2.8
* Platform(s) (iOS, Android, or both?): ios (not tested Android)

**Comment by xcarpentier** [comment]
Did you type a message and send it to the ScrollView?

**Comment by alexbowers** [comment]
I upgraded versions and it worked. So i guess it was resolved at some other time. 

Thanks for the reply though.

**Comment by xcarpentier** [comment]
Ok 👍
So I close :)
