### ISSUE TITLE
Undefined is not an object(evaluating '_Backend.Backend.getUid')

### ISSUE THREAD

**Issue by prodrom** [FaridSafi/react-native-gifted-chat#664]
Hi guys,
i'm getting this 'undefined is not an object(evaluating '_Backend.Backend.getUid')'.

This is my Chat.js file:

export default class ChatPiskolog extends React.Component {

    static navigationOptions = {
        tabBarLabel: 'Randevu',
        headerLeft: null,
        headerStyle: {backgroundColor: '#263238'},
        title: 'PSİKOTERAPİ-CHAT',
        headerTitleStyle: {color: 'white', textAlign: 'center', alignSelf: 'center'},

    }

    state = {
        messages: []
    }

    componentWillMount () {
    }

    onSend(messages = []) {

        this.setState((previousState) => ({
            messages: GiftedChat.append(previousState.messages, messages),
        }));

    }
    render() {
        var {navigate} = this.props.navigation;

        var {params} = this.props.navigation.state;

        return (

            <View style={styles.container}>
                <Text>
                    {params.Baslik}
                </Text>

                <GiftedChat
                    messages={this.state.messages}
                    onSend={(message) => {
                        //send message to backend
                        Backend.sendMessage(message);
                    }}
                    user={{
                        _id: Backend.getUid(),
                        name: this.props.name,
                    }}
                />

            </View>
        )
    }

    componentDidMount () {
        Backend.loadMessages((message) => {
            this.setState((previousState) => {
                return {
                    messages: GiftedChat.append(previousState.messages, message),
                };
            });
        });
    }

    componentWillUnmount () {
        Backend.closeChat();
    }
}

ChatPiskolog.defaultProps = {
    name: 'Anonymous',
};

const styles = StyleSheet.create({

    container: {
        flex: 1,
        backgroundColor: '#fff',

    },

})
#### This is my backend.js

import firebase from 'firebase';

class Backend {

    uid = '';
    messageRef = null;

    constructor() {
        firebase.initializeApp({
            apiKey: "*************",
            authDomain: "************",
            databaseURL: "************",
            projectId: "***********",
            storageBucket: "*****************",
            messagingSenderId: "***********"
        });

        firebase.auth().onAuthStateChanged((user) => {
            if (user) {
                this.setUid(user.uid);
            } else {
                firebase.auth().signInAnonymously().catch((error) => {
                    alert(error.message);
                });
            }
        });

    }

    setUid(value) {
        this.uid = value;
    }

    getUid() {
        return this.uid;
    }

    loadMessages(callback) {
        this.messageRef = firebase.database().ref('messages');
        this.messageRef.off();
        const onReceive = (data) => {
            const message = data.val();
            callback({
                _id: data.key,
                text: message.text,
                createdAt: new Date(message.createdAt),
                user: {
                    _id:message.user._id,
                    name:message.user.name
            },
        });
        };
        this.messageRef.limitToLast(20).on('child_added', onReceive);
    }

    sendMessage(message) {
        for (let i = 0; i < message.length; i++) {
            this.messageRef.push({
                text: message[i].text,
                user: message[i].user,
                createdAt: firebase.database.ServerValue.TIMESTAMP,
            });
        }
    }

    closeChat() {
        if (this.messageRef) {
            this.messageRef.off();
        }
    }

}

export default new Backend();

#### Additional Information

"dependencies": {
		"firebase": "^4.8.0",
		"react": "^16.2.0",
		"react-native": "^0.50.4",
		"react-native-datepicker": "^1.6.0",
		"react-native-gifted-chat": "^0.3.0",
		"react-native-material-dropdown": "^0.5.2",
		"react-native-pages": "^0.6.1",
		"react-native-swipeout": "^2.3.3",
		"react-native-vector-icons": "^4.4.2",
		"react-navigation": "^1.0.0-beta.21",
		"util": "^0.10.3"
	},

**Comment by theberbie** [comment]
I think you're missing `this` when sending the message: this.Backend. 

Although, my understanding is that Backend is your entire background, is that correct? Wouldn't it make more sense to pass this uid as a prop?
