### ISSUE TITLE
Add unit/snapshot tests

### ISSUE THREAD

**Issue by cooperka** [FaridSafi/react-native-gifted-chat#671]
As described in https://github.com/FaridSafi/react-native-gifted-chat/issues/314, it would be great to have unit tests for this library, especially now that we're linting on CircleCI.

@xcarpentier suggested in https://github.com/FaridSafi/react-native-gifted-chat/pull/668#issuecomment-352665080 that he might be able to add them. If so, that would be fantastic!

See the [here](https://github.com/FaridSafi/react-native-gifted-chat/issues/314#issuecomment-268321130) for advice on Jest Snapshots if you're unfamiliar. Thanks!

**Comment by xcarpentier** [comment]
@cooperka  Yes I use it almost everyday (ie. not on the weekend... hum)
Jest Soon Soon Soon :)

**Comment by xcarpentier** [comment]
@cooperka PR #673
