### ISSUE TITLE
Different Bubble color for each user.

### ISSUE THREAD

**Issue by tonnth** [FaridSafi/react-native-gifted-chat#672]
#### Issue Description

If more than 2 user in a conversation.
How can I set Bubble color for each user?
Thank you in advance!

#### Additional Information

* React Native version: 0.50.3

**Comment by mafiusu** [comment]
Yes use the renderBubble prop of the GiftedChat and pass a function like this

`renderBubble={this.renderBubble}`

there you will return your Custom Bubble.js (Copy the code from the src folder in the node module)

```
  renderBubble(props) {
    return <Bubble {...props} />;
  }
```

In Bubble.js you will find the styles. You have to look at the wrapper in left and right and set the backgroundColor you want to.

**Comment by tonnth** [comment]
Thanks @mafiusu 
It work with 2 user in a conversation. But i want to set different corlor for each user in leftside like picture below and i dont know how to do that? [
![nh ch p man hinh 2017-12-20 luc 20 12 38](https://user-images.githubusercontent.com/18168836/34208922-cb378036-e5c2-11e7-9677-4799d1bafd2c.png)
](url)

**Comment by mafiusu** [comment]
Yes, I use this pattern to display usernames in different colors. You could use this function:

```
  getColor(username){
    let sumChars = 0;
    for(let i = 0;i < username.length;i++){
      sumChars += username.charCodeAt(i);
    }

    const colors = [
      '#e67e22', // carrot
      '#2ecc71', // emerald
      '#3498db', // peter river
      '#8e44ad', // wisteria
      '#e74c3c', // alizarin
      '#1abc9c', // turquoise
      '#2c3e50', // midnight blue
    ];
    return colors[sumChars % colors.length];
  }

```

Then you will pass the backgroundColor style in the Render Method of` Bubble.js`. You have to decide if it's left or right using` this.props.position === 'left' ? DO_Something : something else`
You just pass it like backgroundColor: getColor(username)

**Comment by tonnth** [comment]
It save my life.
Thank you @mafiusu .

**Comment by xcarpentier** [comment]
I close this issue but create a FAQ in readme to refer it: https://github.com/FaridSafi/react-native-gifted-chat#questions

**Comment by gianpaj** [comment]
FYI this is the code example you want:
```jsx
  renderBubble={props => {
    return (
      <Bubble
        {...props}
        textStyle={{
          right: {
            color: 'yellow',
          },
        }}
        wrapperStyle={{
          left: {
            backgroundColor: 'red',
          },
        }}
      />
    );
  }}
```

**Comment by PrimeTimeTran** [comment]
Hey guys, I've been struggling with understanding what you guys mean.

Could you please help me out a little bit more?

This is what my Gifted Chat looks like.
```
  render() {
    return (
      <GiftedChat
        messages={this.state.messages}
        renderBubble={this.renderBubble}
        onSend={messages => this.onSend(messages)}
        user={{
          _id: 1,
        }}
      />
    )
  }
```

There are the two helper functions. I'm not sure how to use them in order to pass each individual bubble a color in order to get a distinct color. Please advise.
```
  renderBubble = (props) => {
    let usernames = props.messages.map(message => message.user.full_name)
    let colors = usernames.map(username => this.getColor(username))

    return (
      <Bubble
        {...props}
        textStyle={{
          right: {
            color: 'yellow',
          },
        }}
        wrapperStyle={{
          left: {
            backgroundColor: colors,
          },
        }}
      />
    );
  }

  getColor(username){
    let sumChars = 0;
    for(let i = 0;i < username.length;i++){
      sumChars += username.charCodeAt(i);
    }

    const colors = [
      '#e67e22', // carrot
      '#2ecc71', // emerald
      '#3498db', // peter river
      '#8e44ad', // wisteria
      '#e74c3c', // alizarin
      '#1abc9c', // turquoise
      '#2c3e50', // midnight blue
    ];
    return colors[sumChars % colors.length];
  }
```

**Comment by jameshuynh** [comment]
Hey Loi,

Inside renderBubble function props, you could actually get the currentMessage and its user, then you could decide on the color of that bubble like below:

```js
renderBubble = props => {
    let username = props.currentMessage.user.full_name
    let color = this.getColor(username)

    return (
      <Bubble
        {...props}
        textStyle={{
          right: {
            color: 'white'
          }
        }}
        wrapperStyle={{
          left: {
            backgroundColor: color
          }
        }}
      />
    )
  }
```

**Comment by PrimeTimeTran** [comment]
@jameshuynh Ohhh, thanks bud!

**Comment by gianpaj** [comment]
How would you customize the color of the message timestamp?

i.e.
https://github.com/FaridSafi/react-native-gifted-chat/blob/36082ff059d0bf4ec8a51d701425183f3d665900/src/Time.js#L12-L15

This **doesn't** work:
```jsx
    <Bubble
        {...props}
        timeProps={{
          textStyle: {
            right: { color: colors.black },
          },
        }}
    />
```

**Comment by AndresTIY** [comment]
any luck @gianpaj ?

**Comment by lincolnfraley93** [comment]
so, the only way to achieve this behavior is by copying the source code for Bubble, which itself depends on other files in the source folder, as well as outside packages? shouldn't there be a 'getBubbleColor' prop? i mean, this is the first link under the Questions section on the readme, seems like a common enough issue that it warrants a better solution than basically forking the project...

**Comment by gianpaj** [comment]
The prop is not being passed down to the `Time.js` file. I'll make a pull request

**Comment by Delfshkrimm** [comment]
Just a tiny bit of additional information:
Combining @mafiusu and @gianpaj's answers, you don't actually need to write your own Bubble.js (or scaffold code out of the node_module). You can just import the Bubble component like so:
```
import Bubble from 'react-native-gifted-chat/lib/Bubble';
...
          renderBubble={props => {
            return (
              <Bubble
                {...props}
                wrapperStyle={{
                  left: {
                    backgroundColor: 'white',
                  },
                }}
              />
            );
          }}
```

**Comment by Nagasai97** [comment]
> FYI this is the code example you want:
> 
> ```js-jsx
>   renderBubble={props => {
>     return (
>       <Bubble
>         {...props}
>         textStyle={{
>           right: {
>             color: 'yellow',
>           },
>         }}
>         wrapperStyle={{
>           left: {
>             backgroundColor: 'red',
>           },
>         }}
>       />
>     );
>   }}
> ```

how to pass the props in the render 
this.renderBubble()----------------------???????

**Comment by gianpaj** [comment]
@Nagasai97 `renderBubble` is a prop of the `<GiftedChat>` component.

See my updated [comment](https://github.com/FaridSafi/react-native-gifted-chat/issues/672#issuecomment-397892548)

[All props](https://github.com/FaridSafi/react-native-gifted-chat#props) on README.

**Comment by Nagasai97** [comment]
@gianpaj can i get the code of onSend function for class component...?

**Comment by dexark** [comment]
Does anyone have an example of how to do it using typescript?

**Comment by MarquezMoore** [comment]
How is this done with functional component?

**Comment by GoyoBjS** [comment]
> How is this done with functional component?

This is the version with Functional Components

`const renderBubble = props => {
        return (
          <Bubble
            {...props}
            textStyle={{
              right: {
                color: 'yellow',
              },
            }}
            wrapperStyle={{
              left: {
                backgroundColor: 'red',
              },
            }}
          />
        );
      }`

And then: 

`<GiftedChat
            messages={messages}
            onSend={messages => onSend(messages)}
            user={{ 
                _id: 1
            }}
            **renderBubble={renderBubble}**
        />`

**Comment by rytilahti-juuso** [comment]
Below is a more complete answer on how to modify the **styles** of the text bubbles using functional components:
```javascript
import { GiftedChat, Bubble } from 'react-native-gifted-chat';
// ...Other imports

export default function ChatScreen() {
  
  const renderBubble = props => { 
        return ( 
        <Bubble 
          {...props} 
          textStyle={
              { right: { color: 'green', backgroundColor:'black' }, }
            } 
          wrapperStyle={{
              right: { backgroundColor: 'red', }, 
              left: { backgroundColor: 'orange', }, 
              }} 
        />
      )}
  //... Other necessary code
  return (
    <GiftedChat
      renderBubble={renderBubble}
      // Other props..
    />
  );
}

**Comment by pateljigar7210** [comment]
const renderTime = (props: TimeProps<IMessage>) => {
    return (
      <Time
        {...props}
        timeTextStyle={{
          left: {
            color: 'black',
          },
          right: {
            color: 'black',
          },
        }}
      />
    );
  };

  const renderBubble = (props: Bubble<any>["props"]) => {
    return (
      <Bubble
        {...props}
        wrapperStyle={{
          right: { borderTopRightRadius: 15, backgroundColor: '#ECF6FF' },
          left: { borderTopLeftRadius: 15, backgroundColor: '#F6F6F6' },
        }}
        textStyle={
          {
            right: { color: '#000000', fontFamily: "Poppins-Regular", },
            left: { color: '#000000', fontFamily: "Poppins-Regular", },
          }
        }
        renderTime={renderTime}
      />
    );
  };

**Comment by Srinath10X** [comment]
For those there is no change in the bubble styles just restart the server it works 
```js
        renderBubble={(props: any) => {
          return (
            <Bubble
              {...props}
              wrapperStyle={{
                right: {
                  backgroundColor: "black",
                },
                left: {
                  backgroundColor: "#E5E5EA",
                },
              }}
            />
          );
        }}
```
