### ISSUE TITLE
Prop 'inverted' not affect on message order

### ISSUE THREAD

**Issue by mastersam92** [FaridSafi/react-native-gifted-chat#678]
#### Issue Description

It seems like there not differents between `inverted={true}` AND `inverted={false}` prop in GiftedChat

Maybe, this is somehow connected with the hardcoded `inverted: true` in GiftedChat.js, line 74

#### Steps to Reproduce / Code Snippets

1. Set inverted prop to ture. Check messages order
2. Set inverted prop to false. Check messages order
3. There not differents in msg order

#### Expected Results

Different messages order depending on 'inverted' prop

#### Additional Information

* React-native-gifted-chat version: [0.3.0]

**Comment by longlongago2** [comment]
the same problem

**Comment by xcarpentier** [comment]
Could you test from master branch please?

**Comment by Pau1fitz** [comment]
Created a PR [here](https://github.com/FaridSafi/react-native-gifted-chat/pull/685) with some comments.

**Comment by brzonsea** [comment]
If inverted was removed from props, shouldn't the ReadMe.md be edited? It still says 'inverted' is a prop you can use...

**Comment by brzonsea** [comment]
When I npm install this package, the current version at master branch isn't the one that I am downloading. Hence, no 'inverted' prop for me to use. How can I download the version at master?
