### ISSUE TITLE
Change color of send  button

### ISSUE THREAD

**Issue by SytzeAndr** [FaridSafi/react-native-gifted-chat#681]
**Issue Description**

I want to change the color of the send button. I tried doing something similar to #640 (changing wrapperStyle -> style is also no solution) as that worked for me to change the color of the chat-bubble, but the color of the send button still remains the default blue one. What is going wrong here?

**code snippet**
```

renderSend(props) {
        return (
          <Send 
            {...props}
            wrapperStyle={{
            text: {
                  color: commonColor.brandPrimary
                }
            }}>
            </Send>
        );
    }
```
**Expected result**
A send button with a specified color

**Comment by mafiusu** [comment]
You should pass textStyle Object as a prop and not text. There you have your color: 'specific color'.

**Comment by pavithra2110** [comment]
Its's not working for me

`<Send
        {...props}
        wrapperStyle={{
          textStyle: {
                color: 'red'
              }
          }}
      >
      </Send>`
