### ISSUE TITLE
InputBox styling issue

### ISSUE THREAD

**Issue by anonrig** [FaridSafi/react-native-gifted-chat#687]
#### Issue Description

Hello,

I'm having this input box issue.

![img_71660b445423-1](https://user-images.githubusercontent.com/1935246/34454626-32b38c7c-ed80-11e7-913e-300afc616057.jpeg)

* Nodejs version: 9
* React version: 16
* React Native version: 0.51
* react-native-gifted-chat version: 0.3.0
* Platform(s) (iOS, Android, or both?): iOS

**Comment by anonrig** [comment]
why god why

**Comment by varungupta85** [comment]
I am assuming this is happening on iPhone X only. It has to do with the safe area view. You will need to reduce the top spacing above keyboard based on whether the keyboard is shown or not. I use my own fork due to which I can't share the exact changes.

**Comment by anonrig** [comment]
I've fixed it on my end, but it should be fixed on the library itself. It's not sustainable to have a fork or overriding an existing class just to fix a problem.
