### ISSUE TITLE
Emoji Display Issue

### ISSUE THREAD

**Issue by pavanmehta91** [FaridSafi/react-native-gifted-chat#688]
![emojis-dont-appear](https://user-images.githubusercontent.com/10721301/34477115-312794ae-efbd-11e7-96cd-49eb7df77439.png)
#### Issue Description

Emoji posted from Iphone does not show in android

#### Steps to Reproduce / Code Snippets

Send an emoji from Iphone device, check in android and you'd see a box

#### Expected Results

emoji should display

#### Additional Information

* Nodejs version: v8.9.3
* React version: 16
* React Native version: 0.47.2
* react-native-gifted-chat version: 0.3
* Platform(s) (iOS, Android, or both?): Both

**Comment by mafiusu** [comment]
This is not a problem of the Gifted Chat. The view for showing emojis is correct. How you handle sending the messages to other smartphones is the users issue. Probably it is a database conversion between the 2 clients (gifted chat).

**Comment by xcarpentier** [comment]
Agree with mafiusu, it's not related to this lib.
This is annoying, @mafiusu do you handle it yourself?

So I will close this issue.
