### ISSUE TITLE
No handler for URL on android

### ISSUE THREAD

**Issue by Dhanraj-bidchat** [FaridSafi/react-native-gifted-chat#689]
#### Issue Description
[
When user inputs Https://www.facebook.com on android devices and user clicks the link in the chat, its throwing No handler for URL issue.
For iOS its working fine.
]

#### Steps to Reproduce / Code Snippets
[
-just send text as the following link in gifted chat:
Https://www.facebook.com 
-on clicking on it, the No handler for url issue occur on android
]

#### Expected Results

[
On clicking on url, it should open the correct url in browser just like its opening in iPhone

]

#### Additional Information

* Nodejs version: [v9.3.0]
* React version: [16.0.0-alpha.12]
* React Native version: [0.47.1]
* react-native-gifted-chat version: [^0.2.7]
* Platform(s) (iOS, Android, or both?): [Android]

**Comment by agustind** [comment]
Still not fixed and I think it happens because it's capitalizing the first letter of the URL, maybe you have this configuration: textInputProps={{autoCapitalize:'sentences'}}

**Comment by Revocsid** [comment]
Same issue

**Comment by thuantvDr4** [comment]
#awsome, I faced with issue, and I handled it,. You need check in file Manifest.xml, 
and follow solution under

or you can view more at here 
[](https://stackoverflow.com/questions/64699801/linking-canopenurl-returning-false-when-targeting-android-30-sdk-on-react-native)

![image](https://user-images.githubusercontent.com/24288310/172566918-dccaee0e-408e-473f-bd82-bb06f23d9721.png)
