### ISSUE TITLE
How to access this.props.navigation in Action.js

### ISSUE THREAD

**Issue by mafiusu** [FaridSafi/react-native-gifted-chat#690]
#### Issue Description

I want to access this.props.navigation in my custom Action.js file that I return in renderActions prop of the Gifted Chat. But if I want to this.props it shows me only the GiftedChat props and not the Navigation prop 

#### Steps to Reproduce / Code Snippets

```
renderActions(props) {
    // this.props.navigation exists here
    return <Actions {...props} />;
}
```

I want to navigate to another screen to confirm if you want send the image or not after you take an image.

**Comment by xcarpentier** [comment]
You can pass navigation to GiftedChat, like that: ```javascript
<GiftedChat navigation={this.props.navigation}/>```

**Comment by mafiusu** [comment]
This was a bit out of scope of the gifted chat but anyways thank you it works. Sometimes you have to dig more into basic react native knowledge, in this particularly props

**Comment by xcarpentier** [comment]
@mafiusu Cool ;)
So I will close this issue.
