### ISSUE TITLE
Not Working for platform IOS, sdk version "24.0.0" (code 404)

### ISSUE THREAD

**Issue by hugoh1995** [FaridSafi/react-native-gifted-chat#691]
#### Issue Description

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by xcarpentier** [comment]
Need more info... please fill this issue template.

**Comment by xcarpentier** [comment]
Feel free to re-open with more info.
