### ISSUE TITLE
Create a custom view with player audio.

### ISSUE THREAD

**Issue by projectn3xt** [FaridSafi/react-native-gifted-chat#694]
Issue Description
Create a custom view with player audio.

Steps to Reproduce / Code Snippets
I insert my Audio Custom Component into renderCustomView

Expected Results
I want to pass style to Bubble to render this with flex:1, and show my player complete

Additional Information
Nodejs version: [v9.3.0]
React version: [16.0.0-alpha.12]
React Native version: [0.47.1]
react-native-gifted-chat version: [^0.2.7]
Platform(s) (iOS, Android, or both?): [Android]

**Comment by mafiusu** [comment]
You should show us some piece of code about your issue and provide some screenshots. 

Basically you use the prop renderCustomView in GiftedChat component. There you return your custom View component with `{..props}` inside your custom view you check if it is a record with:
`if(this.props.currentMessage.record){return (...)}`

**Comment by vaimeo** [comment]
I am facing same issue the documentation is not clear how to render the audio messages same like whatsapp i passed renderAuio to bubble but still there is some bugs
