### ISSUE TITLE
[FEATURE-REQUEST] Scroll to bottom if you scrolled through messages

### ISSUE THREAD

**Issue by mafiusu** [FaridSafi/react-native-gifted-chat#698]
Hello GiftedChat coders and users I'm working on a chat app since more than one month using this component. I would like to implement a feature like WhatsApp where the users can scroll down to the last message.

While you scrolling up there should appear a customizable View (like arrow down) to scroll down like in the screenshot below.

<img width="107" alt="bildschirmfoto 2018-01-11 um 15 53 37" src="https://user-images.githubusercontent.com/33623047/34831675-e2ee0980-f6e7-11e7-9edc-b8a2a1adf0fa.png">

What Do you think? Anyone has some hints to this feature?

**Comment by xcarpentier** [comment]
Can you provide a PR?

**Comment by mafiusu** [comment]
I've already forked the project and implement it. I will provide a PR in the weekend.

**Comment by msqar** [comment]
@mafiusu hey maf, thanks for the feature. But question, it says we can pass a scrollToBottomStyle but it's not used in the file, it's always using the stock styling in the renderScrollToBottomWrapper.

Shouldn't be like this by also passing the props styling  `this.props.scrollToBottomStyle`?

```
<View style={[styles.scrollToBottomStyle, this.props.scrollToBottomStyle]}>
        <TouchableOpacity
          onPress={this.scrollToBottom}
          hitSlop={{ top: 5, left: 5, right: 5, bottom: 5 }}
        >
          {this.renderScrollBottomComponent()}
        </TouchableOpacity>
      </View>
```

Thanks in advance.

**Comment by msqar** [comment]
Created this [PR](https://github.com/FaridSafi/react-native-gifted-chat/pull/1387)
