### ISSUE TITLE
parsePatterns prop doesn't do anything

### ISSUE THREAD

**Issue by jacklj** [FaridSafi/react-native-gifted-chat#699]
#### Issue Description

The `parsePatterns` prop doesn't seem to work.

#### Steps to Reproduce / Code Snippets
```js
<GiftedChat
   ... 
   parsePatterns={linkStyle => [
      { pattern: /#(\w+)/,
         style: { ...linkStyle, color: 'purple' },
         onPress: props => console.warn(props),
      },
   ]}
/>
```

#### Expected Results

I expected the parsePattern above to colour hashtags purple, and when you click on them, to get a console warn. But nothing happened, it didn't seem to be parsed.

![screen shot 2018-01-11 at 17 58 16](https://user-images.githubusercontent.com/3493438/34839296-0e7a2618-f6f9-11e7-9fe0-8968e45e6a0d.png)

[FILL THIS OUT]

#### Additional Information

* Nodejs version: 6.10
* React version: 16.0.0-alpha.12
* React Native version: 0.45.1
* react-native-gifted-chat version: 0.2.5
* Platform(s): iOS

**Comment by xcarpentier** [comment]
Can you provide an example on snack like this one: https://snack.expo.io/@xcarpentier/gifted-chat

But the GiftedChat version is 0.3.0 here...

**Comment by xcarpentier** [comment]
@jacklj I updated the snack code and that works correctly with your pattern: 
https://snack.expo.io/@xcarpentier/gifted-chat



![image](https://user-images.githubusercontent.com/923036/34952123-f3f3367c-fa18-11e7-93c1-15ba02f78a97.png)

**Comment by jacklj** [comment]
Hi, thanks yes I updated to 0.3.0 and now it works. Thanks very much for your help!
