### ISSUE TITLE
why inputToolbar position fixed has time delay？

### ISSUE THREAD

**Issue by imwr** [FaridSafi/react-native-gifted-chat#700]
hello, I have 2 questions : 
1.  why inputToolbar position fixed has time delay when the keyboard will show ?
2.  how to watch tap event of  the invertibleScrollView so that i can close my emoji assessory ? 
thanks!
![148ef5d51d4f18f7e024efee3ff696df](https://user-images.githubusercontent.com/5752728/34858336-bb312afa-f78a-11e7-8152-3b93fa13d5c5.gif)

**Comment by xcarpentier** [comment]
Hello,
Did you ever tested it with `isAnimated={false}`?

**Comment by imwr** [comment]
@xcarpentier yes,  has same issue

**Comment by xcarpentier** [comment]
@imwr do you experiment something different from ios?
