### ISSUE TITLE
Why this piece of code is redundant?

### ISSUE THREAD

**Issue by xcarpentier** [FaridSafi/react-native-gifted-chat#704]
https://github.com/FaridSafi/react-native-gifted-chat/blob/22072ea703794393677fbff9555544631eaaf3ad/src/GiftedChat.js#L448

AND 

https://github.com/FaridSafi/react-native-gifted-chat/blob/22072ea703794393677fbff9555544631eaaf3ad/src/GiftedChat.js#L445

**Comment by cooperka** [comment]
Feel free to fix it, looks like a minor duplication introduced in https://github.com/FaridSafi/react-native-gifted-chat/commit/368069142a00e01349b1894cff63d905ab62c41d.
