### ISSUE TITLE
Avatars display on `0.3.0` but not on the latest EDGE version

### ISSUE THREAD

**Issue by apparition47** [FaridSafi/react-native-gifted-chat#706]
#### Issue Description

Avatars display on `0.3.0` but not on the latest EDGE release (commit `22072ea703794393677fbff9555544631eaaf3ad`).

#### Steps to Reproduce / Code Snippets
```bash
# OK
npm i react-native-gifted-chat@0.3.0

# EDGE is BROKEN?
npm i https://github.com/FaridSafi/react-native-gifted-chat.git#22072ea703794393677fbff9555544631eaaf3ad
```
```html
        <GiftedChat
          ref={ref => (this.chat = ref)}
          messages={historyDisplay}
        />
```
```javascript
const historyDisplay = [
{_id: 284, text: "1", createdAt:"2018-01-16T06:39:24.364Z", user: {_id:2, avatar: require('../bluethingicon.png')}},
{_id: 283, text: "2", createdAt:"2018-01-16T06:39:24.364Z", user: {_id:0}},
];
```

#### Expected Results

![works](https://user-images.githubusercontent.com/3298414/34978004-1c38a5f0-fae0-11e7-97fb-af425da6536c.png)

#### Actual Result

![notwork](https://user-images.githubusercontent.com/3298414/34978010-2197d642-fae0-11e7-9556-4d526230c07a.png)

#### Additional Information

* Nodejs version: v8.5.0
* React version: 16.2.0
* React Native version: 0.52.0
* react-native-gifted-chat version: commit `22072ea703794393677fbff9555544631eaaf3ad`
* Platform(s) (iOS, Android, or both?): tested only on iOS

**Comment by xcarpentier** [comment]
We have a weird change in jest snapshot when upgrade to react-native 0.52.0 here https://github.com/FaridSafi/react-native-gifted-chat/pull/692#pullrequestreview-87282481

Maybe it's relative to that.

Did you test on 0.51 before?

**Comment by apparition47** [comment]
Just tried it on `0.51`. Still same issue.

**Comment by xcarpentier** [comment]
Can you test from this branch please: #fix-avatar? 
I removed the default on renderAvatar

**Comment by apparition47** [comment]
Looks like it works! Thanks.
