### ISSUE TITLE
Using GiftedChat inside ScrollView

### ISSUE THREAD

**Issue by brzonsea** [FaridSafi/react-native-gifted-chat#721]
I'm trying to use the GiftedChat component with other custom components together in a ScrollView.

The code looks like below: 

```
 <View style={{ flex: 1 }}>
    <Header />
    <ScrollView style={{ height: Dimensions.get('window').height }}>
        <SomeOtherComponent />
        <GiftedChat />
    </ScrollView>
</View>
```

I was hoping this would do the trick, but ti doesn't. 

For now I can only see the "SomeOtherComponent" on my screen, and there is no trace of 
GiftedChat.

Any ideas on how to fix this?

* Nodejs version: 9.3.0
* React version: 16.0.0
* React Native version: 0.51.0
* react-native-gifted-chat version: 0.3.0
* Platform(s) (iOS, Android, or both?): iOS

**Comment by brzonsea** [comment]
setting ScrollView contentContainerStyle to a certain height fixed the problem.

**Comment by nxnam1102** [comment]
try this https://github.com/FaridSafi/react-native-gifted-chat/issues/1898#issuecomment-876897856
