### ISSUE TITLE
How can I use GraphQL?

### ISSUE THREAD

**Issue by jamesagada** [FaridSafi/react-native-gifted-chat#723]
#### Issue Description

I am a newbie and will like to use GraphQL for the backend. How can I do this?

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by xcarpentier** [comment]
Hello @jamesagada,
This repo is not related to any backend. You can use any backend you want.

But to start graphql I suggest you to go here: https://www.graph.cool

**Comment by jamesagada** [comment]
Thanks. Does this mean Gifted does not need any backend? If it does, how will I integrate to the backend - any backend at all.

Sent from my iPhone

On 19 Jan 2018, at 11:08 PM, Xavier Carpentier <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @jamesagada<https://github.com/jamesagada>,
This repo is not related to any backend. You can use any backend you want.

But to start graphql I suggest you to go here: https://www.graph.cool

**Comment by xcarpentier** [comment]
Yes you need a backend for a chat app of course, but GiftedChat use only messages from props and give you a way to intercept new message.

With that you can do what you want.

Please see examples from readme.
