### ISSUE TITLE
Modal with copying text fires on 'short' press instead of method 'onLongPress'

### ISSUE THREAD

**Issue by pergunt** [FaridSafi/react-native-gifted-chat#728]
#### Issue Description

When I am scrolling the messages and my finger touches on a Buble - Modal is appearing immediatly. But how to avoid this if I wanna copy text only with longPress method?
"react-native": "0.51.0",
"react": "16.0.0",
"react-native-gifted-chat": "^0.3.0",
![chat](https://user-images.githubusercontent.com/28762071/35333957-57d48f5e-0119-11e8-9316-69c84c450bfe.png)

**Comment by filipemerker** [comment]
Anything on this issue?

**Comment by yuensunn** [comment]
You could set the `delayLongPress` props to any milliseconds.
```jsx
//Only trigger after 3 seconds of long pressing
<Bubble {...props} touchableProps={{ delayLongPress: 3000 }}/>
```
[Other available props](https://facebook.github.io/react-native/docs/touchablewithoutfeedback#delaylongpress)

**Comment by RichyTech01** [comment]
i want to implement this in react native how do i go about it, 

![image](https://github.com/FaridSafi/react-native-gifted-chat/assets/123807278/317be3dd-5b28-4b80-805c-73cc606d8c23)
