### ISSUE TITLE
Avatar does not show full

### ISSUE THREAD

**Issue by sy92th** [FaridSafi/react-native-gifted-chat#730]
![0-neu-d4-4d7f98489c386eed214c2db23ecf1982](https://user-images.githubusercontent.com/20162106/35378322-f43394a0-01e4-11e8-84b9-bc41be7bad02.jpg)

#### Object message
```
{
      _id: messageChatDTO.id,
      text: messageChatDTO.message,
      createdAt: new Date(messageChatDTO.createdDate),
      user: {
        _id: messageChatDTO.userId,
        name: messageChatDTO.nameUser,
        avatar:  URL_SERVER+'/getPhoto?access_token='+accessToken+'&lastModifiedDatePhoto='+messageChatDTO.lastModifiedDatePhoto
      }
}
```

#### Render
```
<GiftedChat
          showUserAvatar={true}
          messages={this.state.messages}
          onSend={(messages) => {
            this.onSend(messages);
          }}
          user={{ _id: idUser}}
/>
```

#### Additional Information
* Nodejs version: v6.11.3
* React version: 16.0.0
* React Native version: react-native: 0.50.3
* react-native-gifted-chat version: 0.3.0
* Platform: iOS

**Comment by xcarpentier** [comment]
I think it's because you picture is too huge in size. No?

**Comment by sy92th** [comment]
The current image size is 512x512.
This work well in android but on iOS, it seems to always load images with each message, even though it has the same URL as the previous message

**Comment by xcarpentier** [comment]
Can you provide a copy of that image to reproduce? Link or raw...

**Comment by sy92th** [comment]
https://drive.google.com/file/d/1471IfoZyePJaBwVZqGg90RZ_d3HpzZ3n/view?usp=sharing
This is the largest photo

**Comment by xcarpentier** [comment]
I don't see any issue with image itself on snack: https://snack.expo.io/SkEYg_uHf

<img width="362" alt="screen shot 2018-01-26 at 10 16 14" src="https://user-images.githubusercontent.com/923036/35432825-9e798ff4-0281-11e8-9bbd-fa9e2bcc41b5.png">

**Comment by sy92th** [comment]
I just saw it happen twice. Although I do not edit anything related to it.

**Comment by xcarpentier** [comment]
Ok, I think it's network issue, the image was not fully loaded I guess... what is your suggestion to improve it?

**Comment by barron9** [comment]
you can try with 128 or 64

**Comment by alexgnatrow** [comment]
![screen shot 2018-05-08 at 5 28 58 pm](https://user-images.githubusercontent.com/22867443/39763277-55fc7df4-52e5-11e8-8865-811862336bbc.png)
Same here. not a network issue, obviously))
could not find comprehensible guide how to customize avatar...
