### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ascariandrea** [FaridSafi/react-native-gifted-chat#731]
#### Issue Description

Missing type definition for typescript

#### Additional Information

No plan to add types definition for typescript?

**Comment by xcarpentier** [comment]
Why not... do you any resources somewhere or guideline to do it?
Or maybe a PR?

**Comment by ascariandrea** [comment]
I will be happy to submit a PR :)

**Comment by xcarpentier** [comment]
👌

**Comment by jpmoyn** [comment]
Hey @ascariandrea are you working on the types for this? It would be awesome to have this for a project im working on!

**Comment by ascariandrea** [comment]
@jpmoyn I'm gonna work on this in the next days

**Comment by omkarjoshi-cc** [comment]
@ascariandrea @xcarpentier Any update on this? I really need type definitions to continue using `react-native-gifted-chat`. I'm ready to submit a PR if you guys are busy. 🙂

**Comment by ascariandrea** [comment]
It's been released with [v0.4.3](https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/v0.4.3) @omkarjoshi-cc

**Comment by omkarjoshi-cc** [comment]
Thanks! @ascariandrea @xcarpentier

**Comment by omkarjoshi-cc** [comment]
Hey! There seems to be a problem with the latest release [v0.4.3](https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/v0.4.3). I tried installing using `npm i react-native-gifted-chat --save` and `npm i react-native-gifted-chat@0.4.3 --save` but the `index.d.ts` is not installed. I even tried installation using `npm i https://github.com/FaridSafi/react-native-gifted-chat#v0.4.3` but no luck. Can anyone of you please look into this? @ascariandrea @xcarpentier

**Comment by xcarpentier** [comment]
You should use master.
I will fix the package issue soon with next fix 0.4.4

**Comment by omkarjoshi-cc** [comment]
Thanks! 🙂

**Comment by ascariandrea** [comment]
Can we close this @xcarpentier ?

**Comment by omkarjoshi-cc** [comment]
@xcarpentier @ascariandrea 
The type for `showAvatarForEveryMessage` in `GiftedChatProps` is missing in the current typedefs. I've added it to the typedefs in my fork and I'm using it locally. I've also fixed the [this](https://github.com/FaridSafi/react-native-gifted-chat/issues/731#issuecomment-375194742) along with it. Shall I submit a PR for these minor fixes?

**Comment by ascariandrea** [comment]
Good job!
You should, definitely!

**Comment by brunolemos** [comment]
It shouldn't be required to use master to have the types

**Comment by mjrdnk** [comment]
Is this fixed? Both master and 0.4.3 do not install declarations file.
Can we fix this?

**Comment by lucsky** [comment]
Why is this closed ? Typescript types are definitely not available when installing current version (0.4.3).

**Comment by sibelius** [comment]
Master has types, check the code

**Comment by lucsky** [comment]
@sibelius that's exactly the point, **master** has types, the current **release** (0.4.3) does not.

**Comment by lucsky** [comment]
@sibelius yes that is the point: master has types, the **release** (0.4.3 at this moment) does not.

**Comment by lucsky** [comment]
@sibelius Just tested with 0.5, everything's fine.

(well, except for that `imageStyle` prop, but that's already fixed in master...)

Thanks!

**Comment by cmcaboy** [comment]
It appears to be working with 0.5 for me as well.

**Comment by xcarpentier** [comment]
#1190
