### ISSUE TITLE
How to send system message after click on "SEND" button without typing a message

### ISSUE THREAD

**Issue by programmer-RN** [FaridSafi/react-native-gifted-chat#733]
#### Issue Description

How to send system message after click on "SEND" button without typing a message
#### Additional Information

* Nodejs version: v8.9.4
* React version:  "^16.0.0",
* React Native version: "^0.51.0",
* react-native-gifted-chat version:  "^0.3.0",
* Platform(s) (iOS, Android, or both?): both

**Comment by xcarpentier** [comment]
Just add `system: true` to your message Object before putting it to your messages Array.

**Comment by programmer-RN** [comment]
Hi, thank you for your reply. May I know where I should put the `system:true`?

**Comment by mafiusu** [comment]
@programmer-RN 

e.g. Chat Message

```
{
  _id: 1,
  text: 'My message',
  createdAt: new Date(Date.UTC(2016, 5, 11, 17, 20, 0)),
  user: {
    _id: 2,
    name: 'React Native',
    avatar: 'https://facebook.github.io/react/img/logo_og.png',
  },
  image: 'https://facebook.github.io/react/img/logo_og.png',
  // Any additional custom parameters are passed through
}
```

for you e.g. System Message

```
{
  _id: 1,
  text: 'This is a system message',
  createdAt: new Date(Date.UTC(2016, 5, 11, 17, 20, 0)),
  system: true,
  // Any additional custom parameters are passed through
}
```

**Comment by programmer-RN** [comment]
Hi, thank you for your response. I have tried this, but this one is not my expected result. I want to click on `Send button` (shown as image above)and then send the `Cancel Offer`, default message to messages array of Gifted Chat to display.
