### ISSUE TITLE
Avatar image in documentation returns 404

### ISSUE THREAD

**Issue by joel1st** [FaridSafi/react-native-gifted-chat#734]
#### Examples and documentation that use the react logo for an avatar are now referencing a dead link.

In your browser go to: https://facebook.github.io/react/img/logo_og.png
Observe the 404 page not found.

I'm happy to put a PR up, but perhaps we should reference an image we control (perhaps committed in the examples folder) Thoughts?

**Comment by xcarpentier** [comment]
If you look at example-expo/assets you can find an avatar
