### ISSUE TITLE
Strange layout when on keyboard up in Android.

### ISSUE THREAD

**Issue by kkotkkio** [FaridSafi/react-native-gifted-chat#736]
#### Issue Description

I've got a strange layout on enter any key with keyboard in Android.
I'm using with react-native-keyboard-spacer.

#### Steps to Reproduce / Code Snippets
```
      <View style={[s.container]}>
        <CustomHeader title="문성수" nav={this.props.navigation} share={false}/>
        <GiftedChat
          messages={this.state.messages}
          onSend={messages => this.onSend(messages)}
          user={{
            _id: 1,
          }}
          forceGetKeyboardHeight={true}
          locale='ko'
          placeholder='내용'
          renderSend={this.renderSend}
        />
        {Platform.OS === 'android' ? <KeyboardSpacer /> : null }
      </View>
```

```
const s = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
});
```

#### Expected Results

1. First, It look well and no problem.

![chat_1](https://user-images.githubusercontent.com/23737489/35506383-693dff2a-052c-11e8-947f-1e1dc49da636.png)

2. Second, On cursor in textInput, It look well.

![chat_2](https://user-images.githubusercontent.com/23737489/35506386-6b48b5e4-052c-11e8-8551-33a1546e5e52.png)

3. But I enter any text, the layout on top move top of top more.

![chat_3](https://user-images.githubusercontent.com/23737489/35506390-6d25d6da-052c-11e8-8333-3198253fdce2.png)

#### Additional Information

  Environment:
    OS:  macOS Sierra 10.13.1
    Node:  6.11.3
    Yarn:  1.3.2
    npm:  5.6.0
    Watchman:  4.9.0

  Packages: (wanted => installed)
    react-native: 0.50
    react: 16.0.0
    react-native-keyboard-spacer : 0.4.1
    react-native-gifted-chat : 0.3.0

  Target Platform: Android 6.0

**Comment by creedmangrum** [comment]
I was seeing this running the demo on my android device as well. The "return" key also does not submit the message. I may jump in and submit a PR on this if I have some time soon.

**Comment by hussainahmad** [comment]
@kkotkkio @creedmangrum  did you fixed this issue, as I am getting the same issue when setting  `forceGetKeyboardHeight={true}` but if I set this prop false then when after message send Textinput overlap on message List

**Comment by hussainahmad** [comment]
I got my issue I am getting this issue due to `bottomOffset`  which I needed for` IOS` , BTW thanks
