### ISSUE TITLE
Can I use mysql to save the message?

### ISSUE THREAD

**Issue by tranvannhat** [FaridSafi/react-native-gifted-chat#738]
#### Issue Description

Can I use mysql to save the message?
Can I customize the message object? Compulsory use of your format?

**Comment by xpsdeset** [comment]
Yes you can use mysql to save messages. 
Use the text generated by send button to insert into your mysql. 
Also you can use any format just map it when populating the chats.

**Comment by xcarpentier** [comment]
Hi, I add this question to readme/questions ;)

**Comment by Simwenya** [comment]
how do you connect giftedChat  to mysql

**Comment by tranvannhat** [comment]
thanks bro. Closed

**Comment by LesedimotaungNC** [comment]
a graph ql example would be awesomer

**Comment by josemiguelo** [comment]
> a graphql example would be awesome

This has worked for me:

``javascript
....
const onSend = (newMessages: IMessage[] = []) => {
    newMessages.forEach(message => {
      client
        .mutate({
          variables: {
            ...
          },
          mutation: YOUR_MUTATION,
        })

        .then(response => {
          setMessagesHistory(prevMessages =>
            GiftedChat.append(prevMessages, message)
          )
        })
        .catch(error => {
          // error logic
        })
    })
  }
    return (

        <GiftedChat
          messages={yourMessagesFromState}
          onSend={messages => onSend(messages)}
          .....
        />
    )
```
