### ISSUE TITLE
Render single bubble

### ISSUE THREAD

**Issue by pergunt** [FaridSafi/react-native-gifted-chat#739]
I need to show an error of the current message if sending was false cause server error. When I trying to do that all bubbles taking red color instead of las sended message. How to implement style for last sended message (bubble/MessageText) ?

**Comment by xcarpentier** [comment]
Please see https://github.com/FaridSafi/react-native-gifted-chat/issues/640

**Comment by ivanFullStackSenior** [comment]
I saw that and i tried to  import buble to sindle component and render in the root component/ But when i take the server error end  give red color for the right bubble - ALL sended bubbles makes red text color. I need only one which not was sent.

**Comment by xcarpentier** [comment]
You have to deal with props.currentMessage and add condition to apply your
style or not.

**Comment by ivanFullStackSenior** [comment]
I am not understood that clearly cause i saw keys in currentMessage obj and there is no style or 'color' key. Only text, id, createdAt, {user: _id}. No color

**Comment by xcarpentier** [comment]
Do you have position? left or right?

**Comment by ivanFullStackSenior** [comment]
In 'currentMessage' obj - no. Only those keys which I described allow.

**Comment by mafiusu** [comment]
In the message object you could provide a custom parameter called sent/received. If currentMessage obj has the key sent with false you will render your Bubble accordingly. As @xcarpentier describes you have to  add condition to apply your style or not.

**Comment by ivanFullStackSenior** [comment]
![image](https://user-images.githubusercontent.com/28762071/35849521-89ef9324-0b2a-11e8-975e-53aefde016d8.png)
Like this?

**Comment by ivanFullStackSenior** [comment]
![code](https://user-images.githubusercontent.com/28762071/35851915-15c3b13a-0b32-11e8-8f5b-cb7fdd15dfc6.png)
![code 2](https://user-images.githubusercontent.com/28762071/35851917-15e4f660-0b32-11e8-8945-08219f0526d8.png)
![bubble](https://user-images.githubusercontent.com/28762071/35852026-6af5f37a-0b32-11e8-884a-49d238870f49.jpg)
In the message object or in the currentMessage obj? See my code please. Where I go wrong?

**Comment by mafiusu** [comment]
I will give you an example.

1. Provide renderBubble prop for the GiftedChat component
`<GiftedChat renderBubble={this.renderBubble} />`
2. Implement renderBubble
After you import Bubble from the GiftedChat you can return your Bubble component based on the currentMessage like this:

```
  renderBubble(props) {
    if(!props.currentMessage.sent){
    // if current Message has not been sent, return other Bubble with backgroundColor red for example
      return (
        <Bubble
        wrapperStyle={{
          right: { backgroundColor: 'red' },
        }}
        {...props}
      />
      );
    }
    return (
      // Return your normal Bubble component if message has been sent.
      <Bubble {...props}  />
    );
  }

```
