### ISSUE TITLE
Messages displayed on one side only (left hand side of the screen)

### ISSUE THREAD

**Issue by rohitrkbe** [FaridSafi/react-native-gifted-chat#741]
#### Issue Description

Even if more than 2-3 user is using the app, messages are being displayed on the left side of the screen. cannot differentiate between them (sender who sent what messages)

#### Steps to Reproduce / Code Snippets
codes pushed on my GitHub. link: https://github.com/rohitrkbe/ReactNativeSimpleChatAppWithFirebaseAuth

#### Expected Results

as per the description in the video: https://www.youtube.com/watch?v=VTnFDc3IFag

#### Additional Information

* Nodejs version: 9.4.0
* React version: 16.2.0
* React Native version: 0.52.2
* react-native-gifted-chat version: ^0.3.0
* Platform(s) (iOS, Android, or both?): android

**Comment by mafiusu** [comment]
Each client has to provide a user prop to the GiftedChat with the user-id like user `user={{_id: INDIVIDUAL_USER_ID}}`

In the messages each object has a user key with ` user={{ _id: USER_ID_FROM_SENDER}} `

Have also a look in the documentation.

**Comment by rohitrkbe** [comment]
Was doing the same. Followed every single step as shown in the tutorial video. Also implemented the same. Generated unsigned APK and was using it on two android phones. But when sending messages from both by passing the username, each message is being shown on left side only

**Comment by shekharskamble** [comment]
Having the same issue, provided the _id but all previous messages are showing on the left side including my _id

**Comment by rohitrkbe** [comment]
I think, id will be number, still not tried with a number. If you find any solution, do let me know.....

**Comment by Trnsmt** [comment]
Hi!
I think the issue here is that the main component has no way of knowing which _id of the two users present in the state is _id the logged in user (the one to the right). You can fix this by setting the logged in _id in the onSend function.

Let's say the chat is between two users, you and a friend, with the respective _id 6 and 4. 

the code should be :


 <GiftedChat
            messages={messages}
            onSend={messages => this.onSend(messages)}
            user={{
            _id: 6,
          }}/>


Obvisouly not hardcoded in the onSend function, but the { user._id } of the logged in user.
This works.

**Comment by dsog** [comment]
That solution makes sense but it doesn't work. I have the same issue and all the messages are rendered on the left.

**Comment by dsog** [comment]
The explanation mentioned by @Trnsmt is correct.

@rohitrkbe, the problem is actually a small typo in the `Backend.js` code. There is no `message.user.id`. It is instead `message.user._id`.

So the full `loadMessages` function would look like this:
```javascript
loadMessages(callback) {
    this.messagesRef = firebase.database().ref("messages");
    this.messagesRef.off();
    const onReceive = data => {
      const message = data.val();
      callback({
        _id: data.key,
        text: message.text,
        createdAt: new Date(message.createdAt),
        user: {
          _id: message.user._id,
          name: message.user.name,
        }
      });
    };
    this.messagesRef.limitToLast(20).on("child_added", onReceive);
  }
```

**Comment by o-x-y-g-e-n** [comment]
> I think, id will be number, still not tried with a number. If you find any solution, do let me know.....

I checked with `Strings` as `_id` and it works. I faced an similar issue. Make sure when you load the messages, you have userID linked with the message

`  useEffect(() => {
    const unsubscribe = onSnapshot(
      query(
        collection(db, `rooms/${room.id}/messages`),
        orderBy('createdAt', 'desc')
      ),
      (snapshot) => {
        const newMessages = [];
        snapshot.forEach((doc) => {
          const { _id, createdAt, user, updatedAt, ...rest } = doc.data();
          const docVal = doc.data();
          console.log("authorID")
          console.log(_id);
          const userz = room && room.userIds && room.userIds.length > 0 && room.userIds.find((u) => u === _id) || {
            _id: docVal["user"]._id,
          };

          newMessages.push({
            ...rest,
            _id,
            createdAt: createdAt?.toMillis() || undefined,
            user: {
              _id: docVal["user"]._id,
            },
            updatedAt: updatedAt?.toMillis() || undefined,
          });
        });

        setMessages(newMessages);
      }
    );

    return () => unsubscribe();
  }, [room.id, room.usersIds]);`
  
  This is my sample of loadMessages
