### ISSUE TITLE
Not working the onSend() function in custom InputToolBar

### ISSUE THREAD

**Issue by XiaoLinSoft** [FaridSafi/react-native-gifted-chat#744]
I've made the custom InputToolbar.
My code is:

  onSend = (messages = []) => {
    messages.forEach(m => this.props.dispatch(sendMessage(this.chatId, m.text)))
    this.setState({text: ''})
  }

<GiftedChat
              text={this.state.text}
              messages={data}
              onSend={this.onSend}
              renderInputToolbar={() => (
                <View style={styles.inputToolbarContainer}>
                  <View style={styles.inputWrapper}>
                    <View style={{ flex: 5,justifyContent: 'center', }}>
                      <TextInput
                        value={this.state.text}
                        ref={component => this.messageInput = component}
                        multiline={true}
                        onChangeText={this.onInputTextChanged.bind(this)}
                        placeholder="Type a message here..."
                      />
                    </View>
                  </View>
                  <View>
                    <TouchableOpacity onPress={() => this.onSend()} style={{ marginRight: 8, }}>
                        <Image source={require('../../assets/Images_Icons/btn_chat_send.png')}/>
                    </TouchableOpacity>
                  </View>
                </View>
              )}
              user={{
                _id: this.props.currentUserUid,
              }}
          />

But I can't send the message.
Could you please help me?

**Comment by gianpaj** [comment]
If you just want to customise the Send button you can use the `renderSend` prop instead of `renderInputToolbar`, for example like this:

```jsx
import Ionicons from 'react-native-vector-icons/Ionicons';

  renderSend(props) {
    return (
      <Send {...props}>
        <View style={{ marginBottom: 5, marginRight: 10 }}>
          <Ionicons
            name="md-send"
            size={29}
          />
        </View>
      </Send>
    );
  }

{/* ... */}

<GiftedChat
  renderSend={this.renderSend}
...
/>
```

**Comment by XiaoLinSoft** [comment]
OK, Thank you.

**Comment by kingsonly** [comment]
i want to achieve same thing as above and i actually want to change the design of text input too

**Comment by hindsricardo** [comment]
@gianpaj  is there a list of props somewhere like <Send ? I can't seem to determine what components can be edited in the chat
