### ISSUE TITLE
Keyboard reacts unexpectedly with some Android devices (Not all)

### ISSUE THREAD

**Issue by ahmedsamyabdelhay** [FaridSafi/react-native-gifted-chat#748]
#### Issue Description

On some android devices the keyboard reacts with the input box as expected and on other devices the keyboard covers it up.

I added keyboardAvoidingView with padding behavior. It solved the covering problem but caused the other devices that react normally with the keyboard to have the input box height to increase and push the messages list up in a bad way. 
![27950567_1476525799126640_1322346078_o](https://user-images.githubusercontent.com/19243543/36069063-19851afe-0eeb-11e8-804a-8d2e970234c3.png)

#### Steps to Reproduce / Code Snippets

You can see it through using the demo you provided with samsung galaxy s6 edge

#### Expected Results

Keyboard should push the input box up not cover it.

#### Additional Information

* Nodejs version: Latest
* React Native version: Latest
* react-native-gifted-chat version: Latest
* Platform(s) (iOS, Android, or both?): Android

**Comment by xcarpentier** [comment]
Thank you for reporting issue. This is a current one.

Can you please give us the android version?

Also did you try the `forceGetKeyboardHeight` props?

**Comment by ahmedsamyabdelhay** [comment]
@xcarpentier Android 7.0 ... No I haven't tried forceGetKeyboardHeight ... but I managed to do a workaround by using RN keybaord listeners to get the keyboard height then I wrapped the GiftedChat component in a view and made sure that its height always be equal to Container Height - (Keyboard Height + Header Height)

**Comment by xcarpentier** [comment]
@ahmedsamyabdelhay interesting, do you think it's something you can import into this GiftedChat?

I mean: it supposed to managed it already but maybe you have the fix on your own code that can fix it for everyone ;)

Thanks

**Comment by ahmedsamyabdelhay** [comment]
@xcarpentier I will be more than happy to help ... just tell me how to do it.
