### ISSUE TITLE
seen in input field message (composer)

### ISSUE THREAD

**Issue by lorenz199x** [FaridSafi/react-native-gifted-chat#749]
#### Issue Description

- how to add seen in composer or text input field in creating messages
![image](https://user-images.githubusercontent.com/29396889/36082686-98745414-0fe6-11e8-88f4-14b536278de0.png)

#### Expected Results
when the cursor is in composer or input box all new message will be seen like in messenger

#### Additional Information

* Nodejs version: v6.11.2
* React version: 16.0.0
* React Native version: 0.50.0
* react-native-gifted-chat version:  "^0.3.0",
* Platform(s) (iOS, Android, or both?): android

**Comment by gianpaj** [comment]
Do you want to mark messages as seen when somebody taps on the TextInput?

Modifying the data in messages array is up to you to decide when and write the logic for that.

To do that you'll probably need to use your own custom`renderInputToolbar` function/prop and execute this logic/function when the `onFocus` callback is triggered ([RN docs](https://facebook.github.io/react-native/docs/textinput.html#onfocus)).

**Comment by lorenz199x** [comment]
thanks i already solve it using renderComposer
