### ISSUE TITLE
Reply for Particular Message

### ISSUE THREAD

**Issue by anilgurindapalli** [FaridSafi/react-native-gifted-chat#750]
Hi There,

How to Implement whatsapp type reply in react-native-gifted-chat...

![reply](https://user-images.githubusercontent.com/30103626/36201746-09c4c66e-11a7-11e8-8c25-4c5aaf6ee87d.jpg)

**Comment by mafiusu** [comment]
I did some prototyping on this nice feature last day. And here is my outcome:

![Gif of Reply](https://im3.ezgif.com/tmp/ezgif-3-34580ebd7b.gif)

Some steps you will need for implementing this.

**1. Trigger a reply**
You could trigger your reply by longPress on a bubble or you could implement a swipe to the bubbles like WhatsApp. I choosed the onLongPress Method. 

**2. render ChatFooter**
Like WhatsApp you can notify the user that they are actually replying on a message by showing the ChatFooter (like in the Gif above)

```
//ChatFooter.js
        <View style={{height: 50, flexDirection: 'row'}}>
        <View style={{height:50, width: 5, backgroundColor: 'red'}}></View>
        <View style={{flexDirection: 'column'}}>
            <Text style={{color: 'red', paddingLeft: 10, paddingTop: 5}}>{replyTo}</Text>
            <Text style={{color: 'gray', paddingLeft: 10, paddingTop: 5}}>{replyMsg}</Text>
        </View>
        <View style={{flex: 1,justifyContent: 'center',alignItems:'flex-end', paddingRight: 10}}>
            <TouchableOpacity onPress={dismiss}>
                <Icon name="x" type="feather" color="#0084ff" />
            </TouchableOpacity>
        </View>
      </View>
```

**3. You will need a MessageReply component**
You can pass a key to the message object that indicates, that this message is a reply. With that key you can render a custom Bubble to display the replyMsg.

```
//MessageReply.js
  render() {
    const {replyTo, replyMsg} = this.props.currentMessage;
    return (
      <View style={[styles.container, this.props.containerStyle]}>
        <View style={{ padding: 5}}>
          <View style={{backgroundColor: '#005CB5', borderRadius: 15}}>
            <View style={{flexDirection: 'row',}}>
              <View style={{height:50, width: 10, backgroundColor: '#00468A', borderTopLeftRadius: 15, borderBottomLeftRadius: 15}} />
                <View style={{flexDirection: 'column'}}>
                  <Text style={{color: 'white', paddingHorizontal: 10, paddingTop: 5, fontWeight: '700'}}>{replyTo}</Text>
                  <Text style={{color: 'white', paddingHorizontal: 10, paddingTop: 5}}>{replyMsg}</Text>
                </View>
            </View>
          </View>
        </View>
      </View>
    );
  }

```

**Comment by anilgurindapalli** [comment]
@mafiusu Thanks for the Message...
can u send the detailed code.. i'm new to React native.. little bit confused..

![screenshot_2018-02-22-15-41-02](https://user-images.githubusercontent.com/30103626/36532615-28b4bac0-17e7-11e8-81ec-8f7ad483ddf5.png)

**Comment by anilgurindapalli** [comment]
@mafiusu  it worked.. Thank u so much..

**Comment by ChrisEdson** [comment]
Hey @mafiusu, I’m trying to hack this together myself. If you could share the code, that would be incredible!

**Comment by Faolain** [comment]
@anilgurindapalli did you receive any extra code or did you just use what mafiusu listed above?

**Comment by mafiusu** [comment]
@ChrisEdson I'm a bit late here but if you and @Faolain want the complete source code, you can contact me through Twitter. 

It would be a nice feature to have for this library.

**Comment by xcarpentier** [comment]
@mafiusu any PR?

**Comment by mafiusu** [comment]
> @mafiusu any PR?

If I have more free time, I'll do a PR soon :)

**Comment by ikrav4ic** [comment]
@mafiusu Hi
Can you share code of gifted chat reply messages? Try to modify by myself? but it didn't work yet

**Comment by mafiusu** [comment]
I will do a PR if I have finally more free time finally! 

@ikrav4ic You can contact me through Twitter. My Twitter is linked on my GitHub profile

**Comment by vkkan** [comment]
@mafiusu Sent twitter message , pls share the code

**Comment by vkkan** [comment]
> @mafiusu Thanks for the Message...
> can u send the detailed code.. i'm new to React native.. little bit confused..
> 
> ![screenshot_2018-02-22-15-41-02](https://user-images.githubusercontent.com/30103626/36532615-28b4bac0-17e7-11e8-81ec-8f7ad483ddf5.png)

pls share your working code

**Comment by vkkan** [comment]
> @mafiusu it worked.. Thank u so much.. We can close the Issue..

pls share the working sample

**Comment by vkkan** [comment]
Does anyone can provide full example of this ?

**Comment by mafiusu** [comment]
Hey @vkkan the instruction to rebuild this example is listed above with full code parts.

**Comment by syrakozz** [comment]
@anilgurindapalli hey can you plz send details code or full exmaple

**Comment by AreebVohra** [comment]
> 
> 
> Hey @vkkan the instruction to rebuild this example is listed above with full code parts.

what example are you referring to?

**Comment by mafiusu** [comment]
Hello @AreebVohra I was referring to my own example that I have posted for this issue. It is listed above.

**Comment by AreebVohra** [comment]
i'am try to recreate this example
======================================
renderBubble = props => {
    return (
      <Bubble
        {...props}
        textStyle={{
          right: { color: 'white' },
          left: { color: 'white' },
        }}
        wrapperStyle={{
          left: { backgroundColor: '#2ecc71' }
        }}
      />
    )
  }

  chatFooter = () => {
    const { replyTo, replyMsg } = this.props.currentMessage;
    return (
      <View style={{ height: 50, flexDirection: 'row', display: 'none' }}>
        <View style={{ height: 50, width: 5, backgroundColor: 'red' }}></View>
        <View style={{ flexDirection: 'column' }}>
          <Text style={{ color: 'red', paddingLeft: 10, paddingTop: 5 }}>{replyTo}</Text>
          <Text style={{ color: 'gray', paddingLeft: 10, paddingTop: 5 }}>{replyMsg}</Text>
        </View>
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'flex-end', paddingRight: 10 }}>
          <TouchableOpacity>
            <Feather name="x" color="#0084ff" />
          </TouchableOpacity>
        </View>
      </View>
    )
  }

  render() {
    var user = {
      _id: this.state.userId || -1,
      name: this.state.username,
      avatar: require('../../assets/user.png'),
    };
    return (
      <GiftedChat
        messages={this.state.messages}
        onSend={this.onSend}
        user={user}
        renderUsernameOnMessage={true}
        timeTextStyle={{ left: { color: 'white' } }}
        scrollToBottom={true}
        renderBubble={this.renderBubble}
        renderChatFooter={this.chatFooter}
      />
    );
  }
======================================
this is that i have done so far

**Comment by AreebVohra** [comment]
just point me in the right direction

Thank you Kindly

**Comment by AreebVohra** [comment]
> 
> 
> I did some prototyping on this nice feature last day. And here is my outcome:
> 
> ![Gif of Reply](https://camo.githubusercontent.com/9bd8dca508278b101789f411aca54e3d3f0850d5/68747470733a2f2f7468756d62732e6766796361742e636f6d2f4c6f6e656c79476c6172696e67426c7565626972642d73697a655f726573747269637465642e676966)
> 
> Some steps you will need for implementing this.
> 
> **1. Trigger a reply**
> You could trigger your reply by longPress on a bubble or you could implement a swipe to the bubbles like WhatsApp. I choosed the onLongPress Method.
> 
> **2. render ChatFooter**
> Like WhatsApp you can notify the user that they are actually replying on a message by showing the ChatFooter (like in the Gif above)
> 
> ```
> //ChatFooter.js
>         <View style={{height: 50, flexDirection: 'row'}}>
>         <View style={{height:50, width: 5, backgroundColor: 'red'}}></View>
>         <View style={{flexDirection: 'column'}}>
>             <Text style={{color: 'red', paddingLeft: 10, paddingTop: 5}}>{replyTo}</Text>
>             <Text style={{color: 'gray', paddingLeft: 10, paddingTop: 5}}>{replyMsg}</Text>
>         </View>
>         <View style={{flex: 1,justifyContent: 'center',alignItems:'flex-end', paddingRight: 10}}>
>             <TouchableOpacity onPress={dismiss}>
>                 <Icon name="x" type="feather" color="#0084ff" />
>             </TouchableOpacity>
>         </View>
>       </View>
> ```
> 
> **3. You will need a MessageReply component**
> You can pass a key to the message object that indicates, that this message is a reply. With that key you can render a custom Bubble to display the replyMsg.
> 
> ```
> //MessageReply.js
>   render() {
>     const {replyTo, replyMsg} = this.props.currentMessage;
>     return (
>       <View style={[styles.container, this.props.containerStyle]}>
>         <View style={{ padding: 5}}>
>           <View style={{backgroundColor: '#005CB5', borderRadius: 15}}>
>             <View style={{flexDirection: 'row',}}>
>               <View style={{height:50, width: 10, backgroundColor: '#00468A', borderTopLeftRadius: 15, borderBottomLeftRadius: 15}} />
>                 <View style={{flexDirection: 'column'}}>
>                   <Text style={{color: 'white', paddingHorizontal: 10, paddingTop: 5, fontWeight: '700'}}>{replyTo}</Text>
>                   <Text style={{color: 'white', paddingHorizontal: 10, paddingTop: 5}}>{replyMsg}</Text>
>                 </View>
>             </View>
>           </View>
>         </View>
>       </View>
>     );
>   }
> ```

in point # 3 you said to pass a key to the message object how did you implemet that?

**Comment by akkamboj** [comment]
Hi @mafiusu 
Can you provide me the sample code.

**Comment by MitJNext** [comment]
Hi @mafiusu 
Nice code. Can you show the particular example including everything.
Your .gif image is also incomplete just showing menu after longPress() click.
Can you show the full gif, we need to see how it actually looks.

**Comment by bfk1690** [comment]
Can you provide me the sample code.

**Comment by MayankSingh173** [comment]
> @mafiusu it worked.. Thank u so much.. We can close the Issue..

Can you please share the code. I'm new to React Native

**Comment by joy-mollick** [comment]
@mafiusu please share your code ,It will be nice for me for my project

**Comment by FayyazAliKhan1** [comment]
onLongPress(context, message) {
    let {idOfMessage, disable} = this.state;
and this.setState is undefined when i use it in action sheet call back function for 
.....

**Comment by chganesh** [comment]
Hi @mafiusu , @AGurindapalli  can you share me  complete sample code for reply particular message. i tried your steps but didn't find right solution. please help me on that. 

thanks in advance

**Comment by chganesh** [comment]
Thank you @mafiusu its working fine for me.

**Comment by alvintankc** [comment]
@mafiusu can you share the complete sample code for this? It will definitely help me with my project!

**Comment by kmarv** [comment]
please share the full code file

**Comment by raci-aivy** [comment]
HINT:
All important steps and lines of code already exist above. Please read the comments and the Gifted Chat documentation.

**Comment by dolahimself** [comment]
onLongPress() {
    if (this.props.onLongPress) {
      this.props.onLongPress(this.context, this.props.currentMessage);
    } else {
      if (this.props.currentMessage.text) {
        const options = [
          'Copy Text',
          'Cancel',
        ];
        const cancelButtonIndex = options.length - 1;
        this.context.actionSheet().showActionSheetWithOptions({
          options,
          cancelButtonIndex,
        },
        (buttonIndex) => {
          switch (buttonIndex) {
            case 0:
              Clipboard.setString(this.props.currentMessage.text);
              break;
          }
        });
      }
    }
  }



use this guy (onLongPress - a props, checks docs) to call the chatFooter above when reply is true, then the messageReply on renderCustomView props.

**Comment by docongminh1** [comment]
thank you

> I did some prototyping on this nice feature last day. And here is my outcome:
> 
> ![Gif of Reply](https://camo.githubusercontent.com/4208b0920bd24f4f3b527d7b17c7ab09ae00beef82915588b7cb26e7e0fa21a4/68747470733a2f2f7468756d62732e6766796361742e636f6d2f4c6f6e656c79476c6172696e67426c7565626972642d73697a655f726573747269637465642e676966)
> 
> Some steps you will need for implementing this.
> 
> **1. Trigger a reply** You could trigger your reply by longPress on a bubble or you could implement a swipe to the bubbles like WhatsApp. I choosed the onLongPress Method.
> 
> **2. render ChatFooter** Like WhatsApp you can notify the user that they are actually replying on a message by showing the ChatFooter (like in the Gif above)
> 
> ```
> //ChatFooter.js
>         <View style={{height: 50, flexDirection: 'row'}}>
>         <View style={{height:50, width: 5, backgroundColor: 'red'}}></View>
>         <View style={{flexDirection: 'column'}}>
>             <Text style={{color: 'red', paddingLeft: 10, paddingTop: 5}}>{replyTo}</Text>
>             <Text style={{color: 'gray', paddingLeft: 10, paddingTop: 5}}>{replyMsg}</Text>
>         </View>
>         <View style={{flex: 1,justifyContent: 'center',alignItems:'flex-end', paddingRight: 10}}>
>             <TouchableOpacity onPress={dismiss}>
>                 <Icon name="x" type="feather" color="#0084ff" />
>             </TouchableOpacity>
>         </View>
>       </View>
> ```
> 
> **3. You will need a MessageReply component** You can pass a key to the message object that indicates, that this message is a reply. With that key you can render a custom Bubble to display the replyMsg.
> 
> ```
> //MessageReply.js
>   render() {
>     const {replyTo, replyMsg} = this.props.currentMessage;
>     return (
>       <View style={[styles.container, this.props.containerStyle]}>
>         <View style={{ padding: 5}}>
>           <View style={{backgroundColor: '#005CB5', borderRadius: 15}}>
>             <View style={{flexDirection: 'row',}}>
>               <View style={{height:50, width: 10, backgroundColor: '#00468A', borderTopLeftRadius: 15, borderBottomLeftRadius: 15}} />
>                 <View style={{flexDirection: 'column'}}>
>                   <Text style={{color: 'white', paddingHorizontal: 10, paddingTop: 5, fontWeight: '700'}}>{replyTo}</Text>
>                   <Text style={{color: 'white', paddingHorizontal: 10, paddingTop: 5}}>{replyMsg}</Text>
>                 </View>
>             </View>
>           </View>
>         </View>
>       </View>
>     );
>   }
> ```

thank you

**Comment by Wilted98** [comment]
```
import React, {useState, useCallback} from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  Platform,
  Vibration,
} from 'react-native';
import {
  Bubble,
  GiftedChat,
  InputToolbar,
  Composer,
  MessageText,
} from 'react-native-gifted-chat';
// import MCI from 'react-native-vector-icons/MaterialCommunityIcons';
import {SwipeRow} from 'react-native-swipe-list-view';
import Icon from 'react-native-vector-icons/Feather';

const Gifted = ({id}) => {
  const [messages, setMessages] = useState(null);

  const [replyMsg, setReplyMsg] = React.useState({
    replyId: null,
    text: '',
    user: null,
  });

  const renderBubble = props => {
    return (
      <>
        <BubbleComp props={props} />
      </>
    );
  };

  const BubbleComp = ({props}) => {
    const {text, system} =
      props.currentMessage;
    const onLeftAction = useCallback(
      ({isActivated}) => {
        if (isActivated) {
          Vibration.vibrate(50);
          setReplyMsg({
            replyId: props.currentMessage._id,
            text,
            user: props.currentMessage?.user?.name,
          });
        }
      },
      [id],
    );

    return (
      <SwipeRow
        useNativeDriver
        onLeftActionStatusChange={onLeftAction}
        disableLeftSwipe
        disableRightSwipe={
          system ||
          props.currentMessage.user?.name === currentUser?.nickname ||
          props.currentMessage.isReply ||
          props.currentMessage?.audio ||
          props.currentMessage?.image
        }
        leftActivationValue={90}
        leftActionValue={0}
        swipeKey={id + ''}>
        <></>
        <Bubble
          {...props}
          re
          wrapperStyle={{
            left: {backgroundColor: '#F4183B', marginBottom: 10},
            right: {backgroundColor: '#D4D4D4', marginBottom: 10},
          }}
          textStyle={{
            left: {color: '#fff'},
            right: {color: '#2A2E31'},
          }}
          timeTextStyle={{
            left: {color: '#fff'},
            right: {color: '#2A2E31'},
          }}
          tickStyle={{
            color: props.currentMessage?.seen ? '#01A35D' : '#999',
          }}>
          <></>
        </Bubble>
      </SwipeRow>
    );
  };

  const Reply = () => {
    return (
      <View
        style={{
          height: 55,
          flexDirection: 'row',
          marginTop: 10,
          backgroundColor: 'rgba(0,0,0,.1)',
          borderRadius: 10,
          position: 'relative',
        }}>
        <View style={{height: 55, width: 5, backgroundColor: 'red'}}></View>
        <View style={{flexDirection: 'column', overflow: 'hidden'}}>
          <Text
            style={{
              color: 'red',
              paddingLeft: 10,
              paddingTop: 5,
              fontWeight: 'bold',
            }}>
            {replyMsg?.user}
          </Text>
          <Text
            style={{
              color: '#034f84',
              paddingLeft: 10,
              paddingTop: 5,
              marginBottom: 2,
            }}>
            {replyMsg.text}
          </Text>
        </View>
        <View
          style={{
            flex: 1,
            alignItems: 'flex-end',
            paddingRight: 2,
            position: 'absolute',
            right: 0,
            top: 0,
          }}>
          <TouchableOpacity
            onPress={() => setReplyMsg({replyId: null, text: '', user: null})}>
            <Icon name="x" type="feather" color="#0084ff" size={20} />
          </TouchableOpacity>
        </View>
      </View>
    );
  };
  const ReplyWrapper = ({id}) => {
    return <Reply id={id} />;
  };

  const renderInputToolbar = props => {
    return (
      <InputToolbar
        {...props}
        placeholder="Type your message here..."
        containerStyle={{
          marginLeft: 15,
          marginRight: 15,
          marginBottom: 5,
          borderRadius: 25,
          borderColor: '#fff',
          borderTopWidth: 0,
        }}
        textInputStyle={{color: '#000'}}
        renderComposer={props1 => {
          return (
            <View style={{flex: 1}}>
              {replyMsg.replyId && <ReplyWrapper id={replyMsg.replyId} />}
              <Composer {...props1} />
            </View>
          );
        }}
        textInputProps={{
          multiline: true,
          returnKeyType: 'go',
          onSubmitEditing: () => {
            if (props.text && props.onSend) {
              let text = props.text;
              props.onSend({text: text.trim()}, true);
            }
          },
        }}
      />
    );
  };

  let platformConf =
    Platform.OS === 'ios'
      ? {
          minInputToolbarHeight: 58,
          bottomOffset: 0,
        }
      : {};

  const CustomMessageText = props => {
    return (
      <>
        <View style={{padding: 5}}>
          <View style={{backgroundColor: '#005CB5', borderRadius: 15}}>
            <View style={{flexDirection: 'row'}}>
              <View
                style={{
                  height: '100%',
                  width: 10,
                  backgroundColor: '#00468A',
                  borderTopLeftRadius: 15,
                  borderBottomLeftRadius: 15,
                }}
              />
              <View style={{flexDirection: 'column'}}>
                <Text
                  style={{
                    color: 'white',
                    paddingHorizontal: 10,
                    paddingTop: 5,
                    fontWeight: '700',
                  }}>
                  {props.currentMessage?.isReply?.name}
                </Text>
                <Text
                  style={{
                    color: 'white',
                    paddingHorizontal: 10,
                    paddingTop: 5,
                    marginBottom: 5,
                  }}>
                  {props.currentMessage?.isReply?.text}
                </Text>
              </View>
            </View>
          </View>
        </View>

        <MessageText {...props} />
      </>
    );
  };

  const renderMessageText = props => {
    if (props.currentMessage.isReply) {
      return <CustomMessageText {...props} />;
    }
    return <MessageText {...props} />;
  };

  return (
    <>
      <GiftedChat
        messages={messages}
        // onSend={message => onSend(message)}  // Don't forget to uncomment this.
        user={{
          _id: currentUser?._id,
          name: currentUser?.nickname,
          avatar: currentUser?.profileImage?.url,
        }}
        renderBubble={renderBubble}
        renderInputToolbar={renderInputToolbar}
        // onLongPress={onLongPress}
        alwaysShowSend
        renderSend={renderSend}
        // disableComposer={audioPressed}
        shouldUpdateMessage={() => true}
        renderMessageText={renderMessageText}
        // renderMessageAudio={props => renderAudio(props)}
        // renderActions={() => (
        //   <React.Fragment>
        //     <TouchableOpacity onPress={() => handleChoosePhoto()}>
        //       <MCI
        //         style={{
        //           alignItems: 'center',
        //           justifyContent: 'center',
        //           marginBottom: 9,
        //           marginLeft: 7,
        //           transform: [{rotate: '-45deg'}],
        //         }}
        //         name="attachment"
        //         size={30}
        //         color="#273C66"
        //       />
        //     </TouchableOpacity>
        //   </React.Fragment>
        // )}
        {...platformConf}
      />
    </>
  );
};

export default Gifted;

```

**Comment by sinclairjaza** [comment]
> mafiusu

Can you please share your code? 
I am unable to finalize the integration of replying.

**Comment by Tanle90** [comment]
hello, can you please share your code. 
Thanks

**Comment by tatva-muntazir** [comment]
Hey @mafiusu, Thank you so much for this code. it works very well. First 2 steps are working good but in 3rd step i have found your code and your gif is different. (For initially design of already sent reply messages) 

Can you please provide me code sample of this ? I have try to reach out you through the twitter but i can't.
Please help me 

Thanks in advance.

**Comment by tatva-muntazir** [comment]
If anyone have this working code then please share with me, i am stuck in 3rd step.

**Comment by Tanle90** [comment]
ib me @tatva-muntazir, my slype letuan.nt3

**Comment by Tanle90** [comment]
> If anyone have this working code then please share with me, i am stuck in 3rd step.

Ib me, my skype: letuan.nt3
