### ISSUE TITLE
Use GiftedChat.onSend method in a custom footer

### ISSUE THREAD

**Issue by jjimenezlopez** [FaridSafi/react-native-gifted-chat#752]
#### Issue Description

Hi, I have a particular case that I don't know how to achieve. I have my GiftedChat, and I have added a custom footer through the `renderChatFooter` method. This footer is a list of buttons with suggested messages to the user. If the user clicks in one of them, the text on it have to be sent as a message. I want to send this text using the original onSend method, so I take advantage of the gifted chat logic, such as building the message object, or calling `scrollToBottom` method. But if I call `this.props.onSend()` from my footer, my `onSend` method is called instead of the GiftedChat one.

I don't know how to do that or if it is even possible, I would appreciate some help.

#### Steps to Reproduce / Code Snippets

My `Chat` component:

```javascript
  renderChatFooter(props) {
    return (
      <AssistedResponses {...props} />
    );
  }

  render() {
    return (
      <GiftedChat
        messages={this.props.messages}
        onSend={messages => this.props.onSend(messages)}
        renderChatFooter={this.renderChatFooter}
        ...
      />
    );
  }
```

And my Footer component:
```jsx
<ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ flexDirection: 'row' }}>
  {this.props.assistedResponses.map((option) => { // eslint-disable-line arrow-body-style
      return (
        <TouchableOpacity key={option.key} onPress={() => this.props.onSend({ text: option.text })}>
          <View style={assistedResponsesStyles.response}>
            <Text style={assistedResponsesStyles.responseText}>{option.text}</Text>
          </View>
        </TouchableOpacity>
      );
    })
  }
</ScrollView>
```

#### Additional Information

* Nodejs version: v6.11.2
* React version: 16.0.0
* React Native version: 0.51.0
* react-native-gifted-chat version: 0.3.0
* Platform(s) (iOS, Android, or both?): both

**Comment by roshansingh21** [comment]
I ran into same issue. I would appreciate some help.

**Comment by shafqatbari** [comment]
+1
