### ISSUE TITLE
View disappear when typing on android

### ISSUE THREAD

**Issue by jackmatrix** [FaridSafi/react-native-gifted-chat#766]
I have faced this issue also in ios but I've fixed it by putting a `KeyboardSpacer` but i'm still run into this problem with android. Moreover, when i want to type after sending a message, the input still contains the text of the previous message sent. 

Any suggestions ?

**Comment by hammadj** [comment]
@jackmatrix how did you fix the disappearing view on android?

**Comment by wangdicoder** [comment]
Same issue for me
