### ISSUE TITLE
How to force clear input after sending message ?

### ISSUE THREAD

**Issue by jackmatrix** [FaridSafi/react-native-gifted-chat#767]
I'm facing a problem with android. 

Each time i send a message the input seems to be cleared but when i start typing again the previous value is merged to the new value.

Ex : if i want to send 2 messages "Hello" and "World"

first i send "Hello" then when i start to write "World" my input display "HelloW" so the value of the last send is merged to the new value. 

This happend only on android. i've tried to manually manage by affecting the value of `onInputTextChanged` to `text` props and then clear it at each send but it doesn't fix it. 

Any suggestion ?

**Comment by jackmatrix** [comment]
Okay i located the issue. It is caused by `KeyBoardSpacer`. When i remove it, i no longer get this problem. However without `KeyBoardSpacer` my chat view disappear when the keyboard show up. So i still need an alternative to `KeyBoardSpacer to push my view up when i want to start typing. 

Suggestions ?

**Comment by emmaielle** [comment]
+1

**Comment by Anees-Raja** [comment]
`const clearTextState = () => {
  this.setState({ text: '' })
}`
call this function inside onSend

`const onSend = (message) => {
    //send message
    return clearTextState()
}`
inside gifted chat

`<GiftedChat value={this.state.text} />`

**Comment by mabualwafa** [comment]
Hi @Anees-Raja , could you please add more details about your solution?

**Comment by zachrnolan** [comment]
Also facing this issue on Android. I tried @Anees-Raja's advice and still couldn't get it to work.

**Comment by zachrnolan** [comment]
Found a workaround. I have two different Galaxy S7's and one of them had autosuggest/correct on by default. That phone was the one having this issue. I forced autoCorrect off in Gifted Chat and this issue went away.

Just add this prop to your GitftedChat component:
```
textInputProps={{
    autoCorrect: false
}}
```

**Comment by mayesto** [comment]
Hi, i have the same problem. Did you found any fix for this?

**Comment by richardmillen94** [comment]
A dirty workaround for this that I'm currently using is setting the autoCorrect prop to `false` and then `true` again `onSend` (only for Android devices).
```state = {
    messages: [],
    androidAutoCorrectFix: true,
}
onSend(messages = []) {
    this.setState(
        previousState => ({
            messages: GiftedChat.append(previousState.messages, messages),
            androidAutoCorrectFix: Platform.OS !== 'android'
        }),
        Platform.OS === 'android' && (() => this.setState({androidAutoCorrectFix: true}))
    )
}

render() {
    return (
        <GiftedChat
            textInputProps={{
                autoCorrect: Platform.OS === 'ios' || this.state.androidAutoCorrectFix
            }}
            messages={this.state.messages}
            onSend={messages => this.onSend(messages)}
            user={{
                _id: 1
            }}
        />
    )
}```

**Comment by arik-gamerlink** [comment]
Is this fixed or anything?

**Comment by Eddie-CooRo** [comment]
I'm having the same issue
I've tried both controlling gifted chat text and turning off autocomplete and neither of them helped me, any other suggestions?

**Comment by ahartzog** [comment]
I'm seeing this on android as well right now. Disabling autocorrect completely resolves the issue, but of course presents it's own issues.

**Comment by KienPM** [comment]
I've tried both controlling gifted chat text and turning off autocomplete and neither of them helped me
Anyone fixed that?

**Comment by KienPM** [comment]
> I'm seeing this on android as well right now. Disabling autocorrect completely resolves the issue, but of course presents it's own issues.

please tell me how did you disable autocorrect, I can't disable autocorrect

**Comment by hnrqsss** [comment]
I'm still with this issue, i was try everything here , autocorrect, cleartext, block input when sending, but i still with this problem.
RN 59.8 GIfted-chat 0.9.6.

**Comment by sislovesmedotcom** [comment]
+1

**Comment by mvelebit** [comment]
+1

**Comment by xcarpentier** [comment]
Please open a new issue with an expo snack example to be able to reproduce with exact android version.
Thanks
