### ISSUE TITLE
Expensive render / Takes a second or two to initialize

### ISSUE THREAD

**Issue by brunolemos** [FaridSafi/react-native-gifted-chat#769]
#### Issue Description

GiftedChat is a bit slow to initialize : to show some cached messages. Seems like it's not optimized for performance.

Related report on this comment: https://github.com/FaridSafi/react-native-gifted-chat/issues/298#issuecomment-337107434 by @amitava82 

#### Steps to Reproduce / Code Snippets

Render a GiftedChat with a dozen messages set.

#### Expected Results

See messages instantly, without seeing a loader nor a blank screen.

#### Additional Information

* Nodejs version: 8.9.0
* React version: 16.2.0
* React Native version: 0.52.2
* react-native-gifted-chat version: 0.2.9
* Platform(s) (iOS, Android, or both?): iOS (did not test on android)

**Comment by amitava82** [comment]
Yes, it is because of the md5 calculation that adds up time depending on number of messages. Once #705 gets merged, it should be fast

**Comment by nuonical** [comment]
@Jarred-Sumner I removed the MD5 calculation and just used id's, and I didn't really see a performance difference.

**Comment by luisrodge** [comment]
Any updates on this yet?

**Comment by Faolain** [comment]
any thoughts here @FaridSafi ?

**Comment by adilosa** [comment]
Still experiencing this issue. I've added a spinner underneath the `<GiftedChat>` component to smooth out the UX a bit, but the delay is still too long. 

I also noticed the Chat screen with `<GiftedChat>` gets unmounted when navigating back to the main contacts list screen. Perhaps this issue could be mitigated by leaving the Chat screen mounted.

**Comment by michelepapale1996** [comment]
![image](https://user-images.githubusercontent.com/9197981/53370540-433fd580-394e-11e9-9682-03d47e29d1a4.png)

Maybe, I'm late, but check the readme!

**Comment by piranna** [comment]
We are having the same problem here.

**Comment by iskenz** [comment]
Same here !

**Comment by hubermat** [comment]
Same here.

**Comment by aravi365** [comment]
The issue still persist! Any workarounds?? anyone ??

**Comment by noway** [comment]
Can this be reopened?

**Comment by noway** [comment]
It might be happening because the component spends first render on getting the height of the parent view: https://github.com/FaridSafi/react-native-gifted-chat/blob/3900884f73583aefb9d344c679297cf5d7c935c9/src/GiftedChat.tsx#L395

**Comment by axeljeremy7** [comment]
anyone has fixed or can explain?

**Comment by fractalmarc** [comment]
following, experiencing some supreme, UI-blocking slowness with long chat threads (100+ messages)

**Comment by AliSaeed090** [comment]
Still facing the same issue. Is there any update or any fix? using  "react-native-gifted-chat": "^0.16.3",

**Comment by dwome** [comment]
Same for me. Experiencing the performance slow down even for simple text messages

**Comment by GeorgiIvanovPXL** [comment]
Same

**Comment by WillSmithTE** [comment]
I see there are already some sponsors on this project, what would it take to push this great library's focus towards performance for a while?

**Comment by derek-primumco** [comment]
I'm not sure anyone has identified why the first-pass rendering is so slow.
