### ISSUE TITLE
Hitting the send button a few times after each other results in duplicate messages

### ISSUE THREAD

**Issue by koppelaar** [FaridSafi/react-native-gifted-chat#77]
If I type "asdf" while after every letter quickly hitting the Send button, the expected result would be 4 messages:
- A
- S
- D
- F

Instead, I get these four messages:
- A
- As
- Asd
- Asdf

![asdf](https://cloud.githubusercontent.com/assets/1379402/13731724/709a1ecc-e970-11e5-8c60-633d5c2f8fa8.jpg)

**Comment by koppelaar** [comment]
This is probably the same issue as #70

**Comment by koppelaar** [comment]
I've tried quite a few different things to resolve this, but it seems very hard to fix. I've tried various ways of preventing the textInput from still accepting input after the send button has been pressed. 

I've tried things like:
- clearing the text value using setNativeProps (instead of through setState) to avoid depending on the render cycle
- adding a second hidden TextInput and shifting the focus to this TextInput
- disabling the TextInput

It seems that these blocking measures need quite some time to effectuate and that it's easy to keep typing some characters in the meanwhile. 

Does anybody have ideas on how to resolve this?

**Comment by DorianLutmann** [comment]
Has anyone actually solved that? Having the same issue here, I have to manually focus on the TextInput for the textInput to get cleared after pressing Send.

**Comment by terijyu** [comment]
Will this ever be fixed? :(

**Comment by terijyu** [comment]
@alizbazar  @bpeters
