### ISSUE TITLE
Cloning example and doing npm install causes files to delete

### ISSUE THREAD

**Issue by masudhossain** [FaridSafi/react-native-gifted-chat#773]
#### Issue Description

I cloned the repo cd into example and did `npm install`. Then it deleted all files within example folder.

#### Steps to Reproduce / Code Snippets
git clone https://github.com/FaridSafi/react-native-gifted-chat
cd react-native-gifted-chat/example
npm install

#### Expected Results

I expected it to install, but it instead deleted the files in example.

#### Additional Information

* React version: "react": "16.0.0-alpha.12"
* React Native version: "react-native": "0.46.3"
* react-native-gifted-chat version: "version": "0.0.1"
* Platform(s) (iOS, Android, or both?): Both

**Comment by mafiusu** [comment]
It will work if you are using the yarn command.

**Comment by p-glynn** [comment]
@mafiusu which yarn command are you referring to?

**Comment by ngothanhtai** [comment]
I have the same problem with `npm install` but working when using `yarn install`. Thanks @mafiusu!
