### ISSUE TITLE
How to disable Emojis ?

### ISSUE THREAD

**Issue by jackmatrix** [FaridSafi/react-native-gifted-chat#774]
I need to disable emojis for my chat app. When my keyboard appear, the emoji icon is visible and i need to make it unavailable to insert emojis in discussions. 

Any suggestions ?

**Comment by gianpaj** [comment]
this is not directly related to this package. check some of the answers for native iOS solutions
https://stackoverflow.com/questions/25861468/how-to-disable-ios-8-emoji-keyboard

**Comment by jackmatrix** [comment]
Thanks but these solutions aren't applicable on a react native configuration. 

I need to change the keyboard type inside `react-native-gifted-chat`

**Comment by ericdebelak** [comment]
For anyone looking for possible solutions, you can pass `textInputProps` to the `Composer` component. You can use that to change the `keyboardType` to something that doesn't allow emojis. For instance `textInputProps={{keyboardType: Platform.OS === 'android' ? 'visible-password' : 'ascii-capable'}}`. You can see a visual representation of the keyboard types here: https://lefkowitz.me/visual-guide-to-react-native-textinput-keyboardtype-options/. I did this in the `renderComposer` method.
