### ISSUE TITLE
Keyboard blocking over text input - iOS

### ISSUE THREAD

**Issue by abedinski** [FaridSafi/react-native-gifted-chat#775]
#### Issue Description

I am using the gifted chat library to send a message, however, when the keyboard is displayed the TextInput is hidden. 

#### Steps to Reproduce / Code Snippets

Inside the render method
 
`                    : question ?
                        <View>
                            <ChatBox text={question.text} textStyle={{fontSize: this.state.customFontSize}} />
                            <View>
                                {actionMenuContent}
                            </View>
                        </View>`

`createActionMenu() {
        if (this.state.isAnswering) {
            return (
                <View style={styles.answeringView}>
                    <GiftedChat
                        placeholder={'Type an answer...'}
                        text={this.state.answerText}
                        onInputTextChanged={txt => this.setState({ answerText: txt })}
                        onSend={this.answerQuestion.bind(this)}
                        textStyle={{color:'red', fontSize: 22}}
                    />
                </View>
            )`

`answeringView: {
        flex: 1,
        height: 45,
        marginTop: 500,
        flexDirection: 'row',
        justifyContent: 'center',
        paddingHorizontal: 10,
        paddingVertical: 3,
        backgroundColor: '#EEE',
    },`

![photo_2018-03-01_11-53-08](https://user-images.githubusercontent.com/5396417/36841034-42625666-1d47-11e8-892a-6bdd035919bc.jpg)
![photo_2018-03-01_11-53-13](https://user-images.githubusercontent.com/5396417/36841035-44d60d66-1d47-11e8-832c-07a5f4637154.jpg)

#### Expected Results

The TextInput should be displayed on top of the keyboard. I have been dealing with this for quite some time now. Any help would be appreciative. Thanks.

**Comment by yoonzm** [comment]
I same

**Comment by isthaison** [comment]
So.. 
You using  KeyboardAvoidingView.
IOS was added earlier

**Comment by selfeky** [comment]
did you find a solution?
@yoonzm @isthaison @hakuj

**Comment by fbartho** [comment]
I'm looking for a solution for this too, if anybody knows one.

**Comment by c-goettert** [comment]
I could fix this by setting a negative `bottomOffset`- prop for GiftedChat on iOS. Looks like a hacky workaround, but seems to do it's job...

```
<GiftedChat bottomOffset={-40} />
```
