### ISSUE TITLE
[Feature request] Prevent the text input to be cleared when the onSend() function fails/rejects

### ISSUE THREAD

**Issue by gianpaj** [FaridSafi/react-native-gifted-chat#777]
#### Feature Request Description

The `onSend(messages)` function doesn't seem to have a callback.

So, for example, if the app cannot connect to the backend the input field text will be cleared no matter if the message was sent successfully or not.

For example, the device is offline, I would like to show an error and allow to retry once it's connected again.

#### Expected changes

The `onSend()` to have a callback to handle this.

#### Additional Information

* react-native-gifted-chat version: ^0.3.0

**Comment by jeffnian88** [comment]
+1
Is it possible that textInput keep text when onSend return false?

**Comment by ewal** [comment]
@gianpaj, I just figured it out. Bind the function to a property function in your component class like such:
```javascript
class Chat extends Component {
  ...
  handleOnSend = messages => (
    CallSomeApiEndpoint(messages[0].text); // Or get the text from the state
  );
  ...
  render() {
    return (
      <GiftedChat
        ...
        text={this.state.text}
        onInputTextChanged={text => this.setState({ text })}
        ...
        // Working
        onSend={this.handleOnSend}

        // NOT working
        onSend={messages =>
          CallSomeApiEndpoint(messages[0].text);
        }
       ...
      />
    );
  }
}
```

I use Redux for managing the state, but I guess the above will work. Otherwise, try Redux :)

**Comment by ewal** [comment]
The solution I used is to override the `renderSend` combined with controlling the `text` property with `onInputTextChanged`.
```javascript
  renderSend = props => (
    <Send
      {...props}
      onSend={this.handleOnSend}
      }}
    />
  );

  <GiftedChat
    ....
    text={/* text from state manager */}
    onInputTextChanged={/* store your text somewhere */}
    renderSend={this.renderSend}
    ....
   />
```

Now it's up to you to clear the input field after each send.

**Comment by ewal** [comment]
@gianpaj, hope it helps! Just ping me if you want a complete code example. Otherwise, maybe we could close this issue?

**Comment by DilnaMohandasNT** [comment]
@ewal can you share complete code example
