### ISSUE TITLE
How to change the color of date in giftedchat?

### ISSUE THREAD

**Issue by prmehta24** [FaridSafi/react-native-gifted-chat#778]
#### Issue Description

I'm having a problem finding how to change the color of the date.

#### Steps to Reproduce / Code Snippets

![date_color_issue](https://user-images.githubusercontent.com/31245318/36918197-1a1f9c48-1e7f-11e8-8af1-001cf2774f0c.jpg)

#### Expected Results

I want to change the color to black.

#### Additional Information

* Nodejs version: 4.6.1
* React version: 
* React Native version: 0.50.3
* react-native-gifted-chat version: 
* Platform(s) (iOS, Android, or both?): Android, Haven't checked iOS

**Comment by mafiusu** [comment]
Yes you can easy do that with the GiftedChat.

First you will need to import the Day component
`import {GiftedChat, Day} from 'react-native-gifted-chat';`

then you have to provide the renderDay prop for the GiftedChat and there you will pass a function like that:

```
  renderDay(props) {
    return <Day {...props} textStyle={{color: 'red'}}/>
  }

        <GiftedChat 
          messages={this.state.messages}
          onSend={messages => this.onSend(messages)}
          user={{
            _id: 1,
          }}
          renderDay={this.renderDay}
        />
```

The renderDay function just returns the normal component with the prop textStyle, there you will pass an object that specifies the textStyle of the day. Have a look also at the src folder of the GiftedChat and the Day.js file for more information.

**Comment by prmehta24** [comment]
It worked !!!
Thanks for the quick reply @mafiusu .

**Comment by PhilippeMelo** [comment]
It Worked for me too, Thank you guys!!!!!

**Comment by kannimuthud** [comment]
>   renderDay(props) {
>     return <Day {...props} textStyle={{color: 'red'}}/>
>   }
> 
>         <GiftedChat 
>           messages={this.state.messages}
>           onSend={messages => this.onSend(messages)}
>           user={{
>             _id: 1,
>           }}
>           renderDay={this.renderDay}
>         />
what is means {...props}

**Comment by deyanskiq** [comment]
It means that we are spreading all the `props` to `Day` component in order to keep the behavior and change only the desired one e.g `textColor`

**Comment by bilalyaqoob** [comment]
timeTextStyle={{
          left: {
            color: 'black',
          },
          right: {
            color: 'black',
          },
        }}

**Comment by zubairhixol** [comment]
Need to show date/day sticky on message window scroll like whatsapp. Anyone pls help me
