### ISSUE TITLE
showAvatarForEveryMessage

### ISSUE THREAD

**Issue by hironarita** [FaridSafi/react-native-gifted-chat#782]
#### Issue Description

showAvatarForEveryMessage prop doesn't work when I set the value to true

#### Steps to Reproduce / Code Snippets

`<GiftedChat
					showAvatarForEveryMessage={true}
					renderAvatarOnTop={true}
					showUserAvatar={true}
					renderBubble={(props: any) => this.renderBubble(props)}
					renderAvatar={(props: any) => this.renderAvatar(props)}
					renderInputToolbar={() => this.renderInputToolbar()}
					messages={this.mappedMessages}
					user={{ _id: this.props.RenterId }} />`

#### Expected Results

Avatar to show on every message.

#### Additional Information

* Nodejs version: 5.6.0
* React version: 16.2.0
* React Native version: 0.54.0
* react-native-gifted-chat version: 0.3.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by bhtruong93** [comment]
@hironarita how are you ingesting the repo? I found that npm was serving me an outdated version which was causing this problem. Maybe an updated package need to be published?

**Comment by hironarita** [comment]
@bhtruong93 Through npm. Did you fix the issue? Which files from npm do I have to replace?

**Comment by hironarita** [comment]
@bhtruong93 I replaced Avatar.js and it worked.

@FaridSafi There's an old version of Avatar.js on npm right now. Could you push the latest? Thank you.

**Comment by apparition47** [comment]
@hironarita use version 0.4.3 and not 0.3.0. It contains the new `showAvatarForEveryMessage` prop.

```
$ npm i react-native-gifted-chat@0.4.3 --save
```
