### ISSUE TITLE
App crashes when typing a new message quickly after sending the previous one

### ISSUE THREAD

**Issue by Billydubb** [FaridSafi/react-native-gifted-chat#784]
#### Issue Description

The app crashes when you type in a message and hit send and then quickly start typing the next message.

#### Steps to Reproduce / Code Snippets
```
import React from 'react';

import { GiftedChat } from 'react-native-gifted-chat';

  
export default class GiftedChatExample extends React.Component {	

	state = {
		messages: [],
	  }
	
	  componentWillMount() {
		this.setState({
		  messages: [
				{
			  _id: 1,
			  text: 'Hello developer',
			  createdAt: new Date(),
			  user: {
						_id: 2,
						name: 'React Native',
						avatar: 'https://facebook.github.io/react/img/logo_og.png',
			  },
				},
		  ],
		})
	  }
	
	  onSend(messages = []) {
		this.setState(previousState => ({
		  messages: GiftedChat.append(previousState.messages, messages),
		}))
	  }
	
	  render() {
		return (
		  <GiftedChat
				messages={this.state.messages}
				onSend={messages => this.onSend(messages)}
				user={{
			  _id: 1,
				}}
		  />
		)
	  }

}
```

The code snippet above is the simply the example application given on the github page.

Steps to reproduce the crash:
* Type a message and hit send.
* Very quickly after hitting send start typing again. 
* The app will crash.

![mar-08-2018 18-14-44](https://user-images.githubusercontent.com/1459741/37165315-9eea9f28-22fc-11e8-80ed-fa9a3b8aa46b.gif)

#### Expected Results

* You should be able to type the second message even quickly after the first one without the app crashing.

#### Additional Information

* Nodejs version: 6.9.0
* React version: 16.2.0
* React Native version: 0.53.0
* react-native-gifted-chat version: 0.3.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by nimamyscreen** [comment]
I have same problem , any solution for that ?

"react": "^16.2.0",
"react-native": "^0.53.0",
"react-native-gifted-chat": "^0.4.3",
Platform(s) (iOS, Android, or both?): Android

**Comment by tonydatw** [comment]
why is this closed? I am having the same issue, and, altough my app is not crashing, but the previous message will not be appended if i start typing the next one too quickly
