### ISSUE TITLE
Custom message object

### ISSUE THREAD

**Issue by Anees-Raja** [FaridSafi/react-native-gifted-chat#788]
Is there any way to pass a custom message object to gifted chat without modifying node_modules? I just want to pass my own custom message object into the onSend() function of src/GiftedChat.js

**Comment by colloquet** [comment]
If I were you I would just write a custom onSend function wrapper that transforms the message object via a format function before passing into GiftedChat. 😄

**Comment by Anees-Raja** [comment]
How I solved it (hacky) --> 

Fork project host on your own repo and use that repo as the source for react-native-gifted-chat in package.json

In react-native-gifted-chat/src/GiftedChat.js modify the message object in the onSend() function, make sure you leave required stuff like _id and then it should work.

**Comment by AreebVohra** [comment]
@Anees-Raja could you share your code or GiftedChat.js I'm trying to implement something similar
