### ISSUE TITLE
How to change the background color of ListView ?

### ISSUE THREAD

**Issue by M1chaelChen** [FaridSafi/react-native-gifted-chat#795]
#### Issue Description

Try to change the background color of ListView, but couldn't find any props to do that.

**Comment by dionbaby** [comment]
I am also trying to figure out how to change it.
My current solution is set __backgroundColor__ in **styles.container** in **MessageContainer.js**.

:((

**Comment by M1chaelChen** [comment]
@dionbaby Found the style props to listview which is `listViewProps`. I change the listview background color by doing this:
```
listViewProps={{
  style: {
    backgroundColor: 'white',
  },
}}
```
