### ISSUE TITLE
How to make header stick to screen when pressing "Type a message"

### ISSUE THREAD

**Issue by meurling** [FaridSafi/react-native-gifted-chat#799]
#### Issue Description
Right now my chat screen looks like this:
```
    <View style={{flex: 1}}>
        <Header {props...} />
        <GiftedChat {props...}/>
    </View>
```

When I press the "Type a message" bar at the bottom and the keyboard appears, my Header disappears, how do I make it stick?
I tried giving the header `position: absolute`, but it didn't help and also made the header un-clickable!

Thanks!

**Comment by zarnifoulette** [comment]
Hello, did you find a solution ?

**Comment by meurling** [comment]
@zarnifoulette No, right now I have just accepted it, haven't had time to look into it anymore.
Would be great if someone had a solution! 🥇

**Comment by ddereszewski** [comment]
It will be great to be able to provide headerCompontent which will be displayed as a first element in the chat and be part of the message scroll

**Comment by DnEgorWeb** [comment]
Hello, did anyone find a solution? @zagoa @ddereszewski ?

**Comment by DnEgorWeb** [comment]
I solved this problem replacing android:windowSoftInputMode="adjustPan" to android:windowSoftInputMode="adjustResize" in AndroidManifest.xml. Don't forget to rebuild your application after any changes in AndroidManifest.xml, cause your current build won't see the difference.

**Comment by nandiniparimi1107** [comment]
But what if other screens need adjust pan? I dont think its feasible to just change the manifest file

**Comment by Graymark** [comment]
Did someone finf a solution to this issue?
I'm developping an app which is using react-native-gifted-chat and i have the same issue

**Comment by msqar** [comment]
Any idea on how to solve this? This only happens on Android for me. I'm using NativeBase's header. Whenever the keyboard is opened, my entire header disappears because is being pushed to top lol.

**Comment by maxim-kushnarov-dev-optima** [comment]
Have the same issue, would be great to have a solution!

**Comment by msqar** [comment]
@maxim-kushnarov-dev-optima i fixed it by using adjustResize in AndroidManifest.xml, i had a wrong `android:windowSoftInputMode`

**Comment by maxim-kushnarov-dev-optima** [comment]
@msqar But it will accept adjustResize for all screens, or could we make it only for screen where we have a chat ?

**Comment by msqar** [comment]
@maxim-kushnarov-dev-optima unfortunately, nope. Although the best one to use is adjustResize otherwise it will push the content up, and that's pretty undesired.

**Comment by maxim-kushnarov-dev-optima** [comment]
@msqar Thanks, it was very helpful!

**Comment by c-jain** [comment]
I am also facing the same issue, would be great to have a solution!
