### ISSUE TITLE
Message SENT/RECEIVED tick mark not rendering

### ISSUE THREAD

**Issue by Suraj-Tiwari** [FaridSafi/react-native-gifted-chat#804]
#### Issue Description

Component don't update after changing messages.sent/received = true;

#### Steps to Reproduce / Code Snippets

this.state.messages[this.state.messages.indexOf(message_id) + 1].sent = true;
this.setState({ messages: this.state.messages });

#### Expected Results

Component should re render with a tick mark

#### Additional Information

* Nodejs version: v9.3.0
* React version: 16.3.0-alpha.2
* React Native version: 0.54.2
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): BOTH

**Comment by mafiusu** [comment]
This will not work. State Object is always changing with the` setState()` Method and not by the assign operator.

**Comment by brunocascio** [comment]
You should use immutable functions in order to keep it working.

```
this.setState({ messages: this.state.messages.map(m => {
  if (m.id === message.id) {
    return {
      ...m,
      sent: true
    }
  }
  return m;
})
```

**Comment by Suraj-Tiwari** [comment]
#808 
+ TODO: Add mark message as read. Will work on it next weekend.

**Comment by Suraj-Tiwari** [comment]
> Help wanted #808 @brunocascio
