### ISSUE TITLE
iOS InputAccessoryView coming with RN v0.55 release 

### ISSUE THREAD

**Issue by mafiusu** [FaridSafi/react-native-gifted-chat#806]
With the next major release of React Native the InputAccessoryView from iOS will be able to used. It would make some nice changes to the GiftedChat.

https://facebook.github.io/react-native/blog/2018/03/22/building-input-accessory-view-for-react-native.html

![input-accessory-3](https://user-images.githubusercontent.com/33623047/37798122-0fa24160-2e1c-11e8-9378-c0b4f13f921d.gif)

**Comment by brunolemos** [comment]
+1 Came here to post the same thing.

**Comment by brunolemos** [comment]
+1 Came here to post the same thing.
Sadly it's iOS only for now.

**Comment by brunolemos** [comment]
+1

Came here to post the same thing.
Sadly it's iOS only for now.

**Comment by catherinepricillas** [comment]
@mafiusu Hi, Mafiusu. I'm sorry for getting out of context, but how do you adjust gifted chat navbar and input toolbar for iPhone X? Thank you!

**Comment by mafiusu** [comment]
hello @catherinepricillas did you try using the React Native SafeAreaView? https://www.youtube.com/watch?v=C5gMteV-4-Y

**Comment by igorarkhipenko** [comment]
@mafiusu I've just got the same problem with bottom margin. Did you find any workaround?

**Comment by catherinepricillas** [comment]
hi, @igorarkhipenko, do you find any solution to the problem? thankyou

**Comment by igorarkhipenko** [comment]
hi @catherinepricillas 
Yeah, I've got one. For some reason `SafeAreaView` doesn't work well when it wraps `GiftedChat` component completely. But it does how it is supposed to when you render custom `InputToolbar` wrapped into `SafeAreaView`.
```
renderInputToolbar = (props) => {
    return (
      <SafeAreaView>
        <InputToolbar {...props} />
      </SafeAreaView>
    );
  }
...
const toolbarProps = IS_IPHONE_X
      ? { renderInputToolbar: props => this.renderInputToolbar(props) }
      : {}

    return (
        <GiftedChat
          {...othersProps}
          {...toolbarProps}
        />
```
The reason why I added additional checking for Iphone X is that `SafeAreaView` creates margin for others models too which shouldn't be there for sure.
Hope it will help you.

**Comment by cihancil** [comment]
The problem still exists on iPhone X. 

![screen shot 2018-06-15 at 18 38 43](https://user-images.githubusercontent.com/9278709/41479473-fa545a64-70d3-11e8-913f-8237c5b0bb18.png)

Wrapping InputToolbar with a SafeAreaView causes other problems.
