### ISSUE TITLE
Unable to customize date text color

### ISSUE THREAD

**Issue by jnrepo** [FaridSafi/react-native-gifted-chat#814]
#### Issue Description

Unable to change the color of the date, while its possible to change the color of the text.

#### Steps to Reproduce / Code Snippets

What I'm doing right now to change colors of the bubbles and message text. However, this will not change the color of the dates.

```
      <Bubble
        {...props}
        wrapperStyle={{
          left: {
            backgroundColor: '#5bc236',
            marginBottom: 5
          },
          right: {
            backgroundColor: '#f3f3f3',
            marginBottom: 5
          }
        }}
        textProps={{
          style: {
            color: props.position === 'left' ? '#ffffff' : '#000000',
          },
        }}
      />
```
#### Expected Results

Date and Message colors are matching and are able to customized.

#### Additional Information

* Nodejs version: 9.7.1
* React version: 16.2.0
* React Native version: 0.53.3
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by mafiusu** [comment]
does this work for you? https://github.com/FaridSafi/react-native-gifted-chat/issues/778

**Comment by mafiusu** [comment]
Does this work for you? https://github.com/FaridSafi/react-native-gifted-chat/issues/797

**Comment by jnrepo** [comment]
@mafiusu yes, is there somewhere I can get the version with the fix?

**Comment by mafiusu** [comment]
@jnrepo yes from master
`"react-native-gifted-chat": "https://github.com/FaridSafi/react-native-gifted-chat.git",`

**Comment by Bronsequences** [comment]
Any news on this fix being release via NPM? We've forked this repo to get the changes currently available in master but would like to switch back to referencing your module via NPM if possible.

**Comment by judygab** [comment]
@jnrepo I have this module installed via NPM, when would the fix be available there?
