### ISSUE TITLE
How to show the user's name?

### ISSUE THREAD

**Issue by heyv5** [FaridSafi/react-native-gifted-chat#817]
the name of user object is look like a useless props.....

**Comment by mafiusu** [comment]
It's not useless. The username is used here https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/GiftedAvatar.js to display individuals letters of the username in the Avatar.

**Comment by bamne123** [comment]
Do we have example to show username except Slack example.
Slack example, is the only way to show Username?
