### ISSUE TITLE
SafeAreaView causes performance and loading issues

### ISSUE THREAD

**Issue by tehwayne** [FaridSafi/react-native-gifted-chat#818]
#### Issue Description

When wrapping giftedchat with SafeAreaView the rendering takes longer which results in the flatlist "jumping" on first load since it loads the time and other details slower for some reason.

#### Steps to Reproduce / Code Snippets

Wrap giftedchat in SafeAreaView

#### Expected Results

Normal performance, ideally with little lag/no jumping of elements in the chatbox.

#### Additional Information

* Nodejs version: 
* React version: 
* React Native version: 0.48
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by bamne123** [comment]
I am also getting jumping effect but without SafeAreaView, may be issue with library.
