### ISSUE TITLE
how to render Sending  ???

### ISSUE THREAD

**Issue by dungnguyen10989** [FaridSafi/react-native-gifted-chat#822]
Hi everybody !
I'm building a Chat feature in my app that can send & show images.
Can anybody suggest me a solution to show sending view when i upload image to my server, until upload succeeds it will be disabled or it will change to error if progress upload with errors.

**Comment by ulazarevicfb** [comment]
Maybe you can try with renderFooter, store flag in state and then based on that state render custom footer if needed.
