### ISSUE TITLE
Hide / Filter email and telephone number before sending message to the backend

### ISSUE THREAD

**Issue by msubratt** [FaridSafi/react-native-gifted-chat#823]
#### Issue Description

Can I Hide / Filter email and telephone number before sending message to the backend?

I know that the plugin already use react-native-parsed text to filter emails and phone numbers etc, however I have not been able to hide the emails from the conversation.

**Comment by rajasaur** [comment]
I suppose you can add a parse property that contains "phone" and "email" handlers which will strip out the phone/email. This will make the chat text go through your filter before the ParsedText does the default behaviour.

Checkout MessageText.js for the parse property send to ParsedText

**Comment by msubratt** [comment]
Thanks but I managed to filter both the email and telephone number without modifying MessageText.js. I just had to extract the emails and telephone number using regEx and hide the characters.
