### ISSUE TITLE
RFC: Quick Replies

### ISSUE THREAD

**Issue by watadarkstar** [FaridSafi/react-native-gifted-chat#826]
Not sure if this library can do suggested responses but it would be very helpful for people who build chat bots.

Something like this:
![customer-chat](https://user-images.githubusercontent.com/3059371/38707968-d31ad128-3e81-11e8-94c0-e98abfe61b7b.png)

Facebook calls them `quick_replies`: https://developers.facebook.com/docs/messenger-platform/send-messages/quick-replies

Kik calls them `suggested_responses`
https://dev.kik.com/#/docs/messaging#suggested-response-keyboard

Telegram calls them `inline_keyboard` https://core.telegram.org/bots#inline-keyboards-and-on-the-fly-updating

**Comment by watadarkstar** [comment]
@xcarpentier @brunocascio @FaridSafi Looking for input on the API for this feature as I'm planning to work on this feature. 

RFC:The API I'm thinking of is:

**Message:**

```javascript
{
  _id: 1,
  text: 'My message',
  "quickReplies":[
      {
        "contentType":"text",
        "title":"Yes",
        "imageUrl":"http://example.com/img/yes.png"
      },
      {
        "contentType":"text",
        "title":"No",
        "imageUrl":"http://example.com/img/no.png"
      }
    ]
  // Any additional custom parameters are passed through
}
```

**Component Props:**

`onQuickReply` (Function) - Callback when sending a quick reply

```javascript
onQuickReply(quickReply) {
   if(quickReply.contentType === "text") {
         // send text message
    } else if (quickReply.contentType === "location") {
        // send location
    } else if (quickReply.contentType === "camera") {
        // open camera
    }
    // infinite possibilities 
}
...
<GiftedChat onQuickReply={quickReply => this.onQuickReply(quickReply)}>}
```

**Comment by xcarpentier** [comment]
@watadarkstar yes yes 👍
But nothing block to use renderActions or renderAccessory to do it now I guess...

**Comment by xcarpentier** [comment]
Or renderMessage

**Comment by watadarkstar** [comment]
@xcarpentier True I guess you can just use `renderMessage` to get inline responses, but this would be more convenient.

**Comment by pdoggi** [comment]
@watadarkstar Love this idea, how can I help complete this feature?

**Comment by pdoggi** [comment]
@watadarkstar I'm sorry I didn't see your message earlier! I would love to work together on this! The best way to reach me is via email and phone. What's a good way to exchange contact information?

**Comment by husseinraoouf** [comment]
any news about the Quick replies 
Note: your Version of the Library with initial  quick replies and it is not usable yet

**Comment by watadarkstar** [comment]
@husseinraoouf @pdoggi I wish I had more time for this but feel free to take over my fork and complete the feature 😄

**Comment by husseinraoouf** [comment]
@watadarkstar No Problem :smile:
I will Try To Implement this feature as soon as I could any one can feel free to help

**Comment by pdoggi** [comment]
hey sorry, I've been super busy as well. 😞

**Comment by grinono** [comment]
any updates regarding this?

**Comment by OlivierBessi** [comment]
Hello @watadarkstar, @husseinraoouf, @pdoggi - I am interested in this very useful initiative. I was wondering if you got a change to progress the development of this item? Thakn you!

**Comment by watadarkstar** [comment]
@OlivierBessi @grinono Unfortunately, I don't have the bandwidth to work on this but feel free to submit a PR 😄

**Comment by Webdev259** [comment]
can i make application for phone call , messages,block number, etc etc auto response application using react native
