### ISSUE TITLE
AlwaysShowSend prop not working

### ISSUE THREAD

**Issue by moulie415** [FaridSafi/react-native-gifted-chat#828]
#### Issue Description

When I use alwaysShowSend={true} the behaviour is the same

#### Steps to Reproduce / Code Snippets

use alwaysShowSend props and pass in true

#### Expected Results

send button always shows on text input

#### Additional Information

* Nodejs version: 8.9.1
* React version: 2.0.1
* React Native version: 0.53.3
* react-native-gifted-chat version: 15.5.10
* Platform(s) (iOS, Android, or both?): both

**Comment by hegelstad** [comment]
https://github.com/FaridSafi/react-native-gifted-chat/blob/091de08d3b5c0bf1cf6f295779162ebf42c5c1b2/src/Send.js#L9

This line haven't been built and included in the latest npm package `0.4.3`.

@FaridSafi

**Comment by hegelstad** [comment]
@FaridSafi can you fix this? the source code is correct but its not included in the npm release.

**Comment by hegelstad** [comment]
@xcarpentier Hi, are you able to fix this? should only take a couple minutes.

**Comment by thedmeyer** [comment]
What's the solution here? Please update the npm package

**Comment by tuononh** [comment]
Not working in lastest release `^0.4.3`

**Comment by harrydry2** [comment]
@FaridSafi has done a fantastic job. But we would all really appreciate this being fixed. Has anyone come up with a fix?

**Comment by Abhishekgarg727** [comment]
is anyone got fix for alwaysShowSend  in gifted chat

**Comment by harrydry2** [comment]
change it in the actual npm module. not as hard as it soudns
