### ISSUE TITLE
messageTextProps is not being passed down

### ISSUE THREAD

**Issue by watadarkstar** [FaridSafi/react-native-gifted-chat#830]
Looks like this code:

https://github.com/FaridSafi/react-native-gifted-chat/blob/edf8fffcb196170e5bdecd077f0065731d2c3f93/example-slack-message/src/SlackBubble.js#L44-L60

makes use of `messageTextProps` but I don't see it being passed down as props or used. Can we gut this? Or can someone clarify what this was meant for? And can we add it to the `propTypes`?

**Comment by gianpaj** [comment]
ping

**Comment by gianpaj** [comment]
please re-open. this is still not fixed

**Comment by woodcockjosh** [comment]
Still broken

**Comment by watadarkstar** [comment]
I re-opened the issue @woodcockjosh @gianpaj

**Comment by woodcockjosh** [comment]
FYI my workaround to this was to re-render the gifted chat with an empty list, then re-render again with an actual list. I event emitters to achieve this.

**Comment by watadarkstar** [comment]
@woodcockjosh You could try to patch it yourself with: https://www.npmjs.com/package/patch-package
