### ISSUE TITLE
How to get currentMessage

### ISSUE THREAD

**Issue by TheGreatAndrew** [FaridSafi/react-native-gifted-chat#833]
I tried to use this.props.currentMessage.text (from onLongPress()), and nothing works. 
still trying to figuring out how to get it? 
error: undefined is not an object (evaluating ...)
already this.onLongPress.bind(this)
look for solutions by cloning the whole rep, but still ... don't understand

**Comment by 72apps** [comment]
GiftedChat passes the 'currentMessage' object as the second parameter in the onLongPress callback.
[](https://github.com/FaridSafi/react-native-gifted-chat/blob/0c046de0a35edffca716e01af7aa87aa9e52a991/src/Bubble.js#L30)

Here's what my code looks like...
``` 
<GiftedChat
     onLongPress={(ctx, currentMessage) => console.log(ctx, currentMessage)}
     keyboardShouldPersistTaps={'handled'}
     messages={this.props.messages}
     onSend={this.onSend.bind(this)}
     renderSend={this._renderSend.bind(this)}
     renderActions={this._renderCustomActions.bind(this)}
     renderMessageImage={this._renderMessageImage.bind(this)}
     user={{
        _id: this.props.profile.user.id,
      }} />
```
