### ISSUE TITLE
Some components broken in 18:9 devices like OnePlus 5T

### ISSUE THREAD

**Issue by victorkvarghese** [FaridSafi/react-native-gifted-chat#835]
#### Issue Description

I tried running the basic example in the GitHub library description. everything works fine on iOs. but the UI is broken in 18:9 devices like OnePlus 5T

#### Steps to Reproduce / Code Snippets

Basic Example
   ```
<GiftedChat
                    messages={this.state.messages}
                    showUserAvatar
                    isAnimated
                    renderAvatar={this.renderAvatar}
                    onSend={messages => this.onSend(messages)}
                    user={{
                        _id: 1,
                        name: 'Vicky'
                    }}
                />
```
#### Results

![screenshot_20180418-150447](https://user-images.githubusercontent.com/15869386/38924378-70f19a7a-431a-11e8-8d5d-31bf1b3a02cc.jpg)

#### Additional Information

* React version: ^16.3.0-alpha.1
* React Native version: ^0.54.2
* react-native-gifted-chat version: ^0.4.3
* Platform(s) (iOS, Android, or both?): Android

**Comment by akiladevinda** [comment]
Same issue. Is this fixed now or not ?

**Comment by victorkvarghese** [comment]
Use fontFamily .. I used roboto font to fix the issue

**Comment by akiladevinda** [comment]
@victorkvarghese  what is the file need to change the fontFamily ??

**Comment by victorkvarghese** [comment]
@akiladevinda u need to specify custom Avatar component and everything with text with fontFamily
