### ISSUE TITLE
Time component missing textStyle prop in constructor

### ISSUE THREAD

**Issue by ulazarevicfb** [FaridSafi/react-native-gifted-chat#836]
Time component is missing textStyle prop in constructor, textStyle is specified in defaultProps and used in Time component render, but not specified as parameter in constructor.

renderTime(props) {
        const timeStyle = {
            color: 'blue'
        };
        return <Time {...props} textStyle={{left: timeStyle, right: timeStyle}}></Time>
 }
textStyle is being ignored

I tried to fix this, and succeed.

In file node_modules/react-native-gifted-chat/src/Time.js

export default function Time({ position, containerStyle, currentMessage, timeFormat, **textStyle** }, context) {
  return (
    <View style={[styles[position].container, containerStyle[position]]}>
      <Text style={[styles[position].text, textStyle[position]]}>
        {moment(currentMessage.createdAt)
          .locale(context.getLocale())
          .format(timeFormat)}
      </Text>
    </View>
  );
}

* Nodejs version: 9.8.0
* React version: 16.2.0
* React Native version: 0.53.3
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): both

**Comment by pentarex** [comment]
It is already fixed and merged. 
https://github.com/FaridSafi/react-native-gifted-chat/pull/798
You have two options:
1. Fork my repo
2. Wait for release

**Comment by userbq201** [comment]
+ 1
update bug pls
