### ISSUE TITLE
[BUG][PLEASE HELP]Incorrect height of InputToolBar when first rendering messages

### ISSUE THREAD

**Issue by kevinscience** [FaridSafi/react-native-gifted-chat#837]
#### Issue Description

Incorrect height of InputToolBar when first rendering messages. It's more like screen flickering when open the page. But I found that it is the wrong height of inputTollBar.

if I set:
```
textInputProps={{
                        onLayout:(event)=>console.log(event.nativeEvent.layout)
                    }}
```

The output is:
```
{y: 6, width: 365, x: 10, height: 33}
{y: 6, width: 365, x: 10, height: 200}
{y: 6, width: 365, x: 10, height: 33}
```
You can tell there is magnificent layout change happened.

Therefore I did more test. I set a textInput multiline=false, and then I set a timer when textInput onLayout got called to set its multiline to be true. No matter how long I set to setTimeout, the textInput will flicker as soon as multiline = true.

```
multiline: !this.state.viewLoading,
onLayout:(event)=> {
       console.log(event.nativeEvent.layout)
        let timer = setTimeout(()=>this.setState({viewLoading:false},()=>console.log('viewLoading', this.state)),10000);
}
```

#### Steps to Reproduce / Code Snippets

```
 componentWillMount() {
        for(let i=0; i<staticMessages.length ; i++){
            this.setState(previousState => ({
                messages: GiftedChat.append(previousState.messages, staticMessages[i]),
            }))
        }
    }
```

#### Expected Results

No Flickering when opening the screen

#### Additional Information

* React version: "16.3.0-alpha.1"
* React Native version: "https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz"
* react-native-gifted-chat version: "^0.4.3"
* Platform(s) (iOS, Android, or both?): iOS, haven't tried on Android

![giftedchat](https://user-images.githubusercontent.com/19722517/38964737-7fb4b700-4346-11e8-99b1-e5225052dc6d.gif)

**Comment by kevinscience** [comment]
This bug makes me really confused. Is there any help for this one? I really appreciate it!

**Comment by uncledent** [comment]
Yeah, this bug is annoying, 
I have a temporary workaround for that. Add this:

``` 
<GiftedChat
onLayout={() => {this.setState({ viewLoading: }}
textInputProps={{ multiline: !this.state.viewLoading}}
/>
```

So you just disable multiline until component layout loading.

**Comment by kevinscience** [comment]
Thank you for your solution! I really appreciate it!

**Comment by radiodario** [comment]
I don't see `onLayout` as a prop on giftedChat, how does that solution work @uncledent?

**Comment by uncledent** [comment]
@radiodario It’s inherited from the ScrollView

**Comment by radiodario** [comment]
i've added the callback to the element but it does not get executed?

**Comment by uncledent** [comment]
@radiodario I really don't know what could be your problem, at works for me.

**Comment by kevinscience** [comment]
@uncledent I really appreciate your answer. You have pointed to a right direction for me. If I set 'multiline' to false, there won't be this problem anymore. There is no onLayout as a prop for GiftedChat. I tried it in 'textInputProps', it seems it gets called before textInput flickering.

**Comment by kevinscience** [comment]
This is really a great repo. It has 5.1K stars. 
But am I the only one who is experiencing this bug? And no one care about this unbearable issue?
I checked the src code. In Composer.js, onContentSizeChange(e) will be called at the start of rendering with wrong contentSize.height.
`contentSize {width: 0, height: 240}`
