### ISSUE TITLE
[Performace] After chatting for a while input box start taking delay to show typed message in input box.

### ISSUE THREAD

**Issue by Suraj-Tiwari** [FaridSafi/react-native-gifted-chat#840]
#### Issue Description
After chatting for some time. When user types it takes a while to appear in message input box (Delay Varies by devices);

#### Steps to Reproduce / Code Snippets
Keep chatting for a long time with same user.

#### Expected Results
Smooth work

[FILL THIS OUT]

#### Additional Information
After chatting for some time. When user types it takes a while to appear in message input box (Delay Varies by devices);

* Nodejs version: [9.3.0]
* React version: [16.3.1]
* React Native version: [0.55.2]
* react-native-gifted-chat version: [0.4.3]
* Platform(s) (iOS, Android, or both?): [ANDROID]

**Comment by rzdev** [comment]
@Suraj-Tiwari Thanks so much for this, i have this problem too.

My issue on Lag
https://github.com/FaridSafi/react-native-gifted-chat/issues/850

**Comment by Waltari10** [comment]
Same here! I don't understand though why this is fixing the problem. 🤔 Isn't this the exact way that react-native recommends doing TextInput? How can it slow down Android?https://facebook.github.io/react-native/docs/textinput.html

**Comment by Waltari10** [comment]
Possibly related issue: https://github.com/facebook/react-native/issues/18916

**Comment by ahartzog** [comment]
Commenting out the line breaks text clearing on iOS for me, this appears to resolve it well:

`value={Platform.OS === 'ios' ? this.props.text : null}`

**Comment by OSPFNeighbour** [comment]
+1

Without this my JS and UI FPS drop to about 3fps while typing. with this fix applied they stay at about 50fps

**Comment by iamrommel** [comment]
No pull request for this?

**Comment by richeterre** [comment]
@ahartzog, if make the change you suggested

`value={Platform.OS === 'ios' ? this.props.text : null}`

the input field no longer gets cleared when I submit a message. Does this not happen for you? I'm on version 0.4.3.

**Comment by aamir0** [comment]
With the suggested fix of `value={Platform.OS === 'ios' ? this.props.text : null}`, the box clears on Android, but it takes a second or so. If you start typing in that time (which isn't hard to do), the box won't clear at all.
