### ISSUE TITLE
Using custom JSON objects from server response

### ISSUE THREAD

**Issue by kkrishnan90** [FaridSafi/react-native-gifted-chat#844]
Is there any way to use custom JSON objects to use in gifted chat ? Like you have _id as the primary identifier key but in my server the response will be like id, from, to , message etc. Would love to use this library. Thanks a ton in advance.

**Comment by wispoz** [comment]
any luck with this?

**Comment by kkrishnan90** [comment]
Nope.. I'm still waiting for someone to enlighten me on this so that this library is worth plugging in all my upcoming projects.
