### ISSUE TITLE
[iOS] First message border radius not working

### ISSUE THREAD

**Issue by watadarkstar** [FaridSafi/react-native-gifted-chat#845]
#### Issue Description

I have this issue where `borderRadius` on a multi-part message is not showing up on my first message in the multi-part message on iOS only. See image below:

![screen shot 2018-04-30 at 11 12 11 am](https://user-images.githubusercontent.com/3059371/39434779-8f2805f0-4c67-11e8-95cb-136212bbb945.png)

My `styles.js`:

```javascript
  left: StyleSheet.create({
    container: {
      flex: 1,
      alignItems: "flex-start"
    },
    wrapper: {
      borderRadius: 9,
      backgroundColor: Color.leftBubbleBackground,
      marginRight: 60,
      minHeight: 20,
      justifyContent: "flex-end"
    },
    containerToNext: {
      borderBottomLeftRadius: 3
    },
    containerToPrevious: {
      borderTopLeftRadius: 3
    }
  }),
```

and inside `MessageBubble.js`:

```jsx
import LinearGradient from "react-native-linear-gradient";

<LinearGradient
          colors={
            position === "right"
              ? [
                  Color.rightBubbleBackgroundStart,
                  Color.rightBubbleBackgroundEnd
                ]
              : [Color.leftBubbleBackground, Color.leftBubbleBackground]
          }
          style={[
            styles[position].wrapper,
            this.props.wrapperStyle[position],
            this.handleBubbleToNext(),
            this.handleBubbleToPrevious()
          ]}
        >
...
</LinearGradient>
```

#### Steps to Reproduce / Code Snippets

(see above)

#### Expected Results

Rounded corners on all messages. Or a way to configure the first message?

#### Additional Information

* Nodejs version: v8.9.4
* React version: "16.3.0-alpha.1",
* React Native version: "https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz",
* react-native-gifted-chat version: "^0.4.3",
* Platform(s) (iOS, Android, or both?): iOS only

**Comment by fukemy** [comment]
I think with LinearGradient as `Bubble background`, it's cause much laggy in Chat application
