### ISSUE TITLE
Can not run example

### ISSUE THREAD

**Issue by hoangvuanhdevelopervn** [FaridSafi/react-native-gifted-chat#846]
I follow this in example

**# Run the example**
_git clone https://github.com/FaridSafi/react-native-gifted-chat
cd react-native-gifted-chat/example
npm install
react-native run-ios_

but when run npm install it's error and remove all file in example folder like this:

<img width="1440" alt="screen shot 2018-05-02 at 10 16 54 am" src="https://user-images.githubusercontent.com/29293495/39503822-13eefc86-4df2-11e8-8f16-7a9316c01ba8.png">

**Comment by Thanmai-C** [comment]
Try removing the .babelrc file in the folder, and then run react-native run-ios

**Comment by hoangvuanhdevelopervn** [comment]
@Thanmai-C thank you, i will try. I have one more question: How can attach file in the conversation, like doc, text, mp3, video....? How to do that?

**Comment by Thanmai-C** [comment]
I am not sure, think it is not implemented you have to do it.

For the above mentioned issue, you can try yarn install instead of npm install.
Refer: https://github.com/FaridSafi/react-native-gifted-chat/issues/588

**Comment by hoangvuanhdevelopervn** [comment]
@Thanmai-C Thank you.

**Comment by KevinColemanInc** [comment]
I am not able to run the example either.
`$ yarn install` completes successfully, but `$ react-native run-ios` does not.

I tried removing the `.babelrc` file

If you run `$ npm install`, everything in the directory is deleted.

**Comment by Faolain** [comment]
Same issue, example does not run

**Comment by sarykemmoun** [comment]
Hello.
Same issue.
`npm install` doesn't work. `yarn install` works.
but `react-native run-ios` fails with error: `C compiler cannot create executables`.
Did anyone succeed to run it? thanks
