### ISSUE TITLE
giftedchat with firebase

### ISSUE THREAD

**Issue by aggounix** [FaridSafi/react-native-gifted-chat#849]
#### Issue Description

I am using gifted chat with firebase database. I get messages on loading but when  someone write something to me, i get duplicated messages (for expamle i get the olders messages twice displayed onn messages list)

#### Steps to Reproduce / Code Snippets

I use the event : on("value", snapshot) to append new messages to the list
when I use on ("child_added, snapshot) it get worse, I get error messages  : "sources for assign must be an object"

I am using react native with expo app

#### Expected Results

Is there any example with firebase used in a gifted chat example

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version:16.2.0
* React Native version: 25.0.0
* react-native-gifted-chat version: 0.3.0
* Platform(s) (iOS, Android, or both?): Android
* Expo: 25.0.0

**Comment by rizeon** [comment]
It is up to you to handle data that comes in to GiftedChat, not other way round.

I personally use Firebase + Redux + Gifted Chat, I am not too 100% happy with this lib but overall it works.

In Chat container on componentDidMount I retrieve messages from firebase.
Then I dispatch it to redux store handling potential duplicates in reducer.
( Because we get objects with keys from firebase and not arrays as Gifted chat requires we can merge current state with incoming new data )
In component I map state from redux to the structure that Gifted chat requires.


( Additionally whenever I enter component when I call method to get new messeges I can use current redux state to only retrieve messages after the messages I currently have )

**Comment by aggounix** [comment]
Thx for the answer, I found this project and helped me a lot : https://github.com/FaridSafi/ChatApp
this was very useful
By the way do you know how to add messages when the app is closed (meaning doing notfications and adding not read messages)

**Comment by rizeon** [comment]
I haven't got to that part yet however I would suggest not reading/writing any data when app is closed.
IMO it is much better to do notifications and only read new messages when app comes into foreground.

I personally do not use Expo however I see there is some Expo solution for notifications, read up on it, there should be some payload possible with notification so you can act on it in your app and open proper screen.

If not using Expo while still using Firebase (rnfirebase) I would suggest Google's solution https://rnfirebase.io/docs/v4.1.x/notifications/introduction

**Comment by aggounix** [comment]
I am using Expo, and I found a tutorial to use FCM with expo notifications
By the way how to get the missed messages when app comes into foreground from the firebase database 
Do you keep a list of unread messages in the users nodes until he opens the app, or just keep the last message id read by the user and get messages beginning from this id ?
please advise

**Comment by rizeon** [comment]
IMO there are two main, simple options.
You can mark messages as displayed (read) handling it in chat component (for example using https://reactjs.org/docs/react-component.html#componentdidupdate updating in Firebase ) 

Or make it really simple and always show newly loaded messages as 'unread' (for example Bolded ) - that would work for user's single device.

That really depends on your exact requirements / design.

Proper chat with all the gimmicks like Facebook messenger has is whole another project so keep in mind that there should be some line you should stop improving it unless of course you are building chat app. In my case it's just an addition to the app.
