### ISSUE TITLE
focusTextInput() - Imperative methods

### ISSUE THREAD

**Issue by Fed0t** [FaridSafi/react-native-gifted-chat#851]
#### Issue Description

focusTextInput() - Open the keyboard and focus the text input box

how should i use focusTextInput();

And second issue is  that I need TextInput reference for my KeyboardAccessoryView ! a callback for ref textinput will be perfect!

**Comment by jlobusta** [comment]
How did you use focusTextInput @Fed0t ?

> #### Issue Description
> focusTextInput() - Open the keyboard and focus the text input box
> 
> how should i use focusTextInput();
> 
> And second issue is that I need TextInput reference for my KeyboardAccessoryView ! a callback for ref textinput will be perfect!

**Comment by hupptechnologies** [comment]
@jlobusta Using gifted chat ref.

`this.chatRef.focusTextInput()`

```
<GiftedChat
   ref={(ref) => (this.chatRef = ref)}
   ....
/>
```
