### ISSUE TITLE
Bottom offset between InputToolbar and keyboard

### ISSUE THREAD

**Issue by melihmucuk** [FaridSafi/react-native-gifted-chat#852]
#### Issue Description

<img width="367" alt="screen shot 2018-05-09 at 14 59 13" src="https://user-images.githubusercontent.com/3147488/39813596-bbb01f20-5399-11e8-8727-ce82deeaceb2.png">

#### Steps to Reproduce / Code Snippets

```javascript
const COMPOSER_HEIGHT = 60;

****
renderInputToolbar(props) {
   return <InputToolbar {...props} containerStyle={[styles.inputToolBar]} />;
}

renderComposer(props) {
   return <Composer 
             {...props} 
             placeholder={'Type a message...'} 
             placeholderColor={'#BCBCBC'} 
             textInputStyle={styles.composerText}
          />;
}

****

<GiftedChat
  composerHeight={COMPOSER_HEIGHT}
  minInputToolbarHeight={COMPOSER_HEIGHT}
  renderAvatar={null}
  messages={currentInbox ? currentInbox.messages.slice().reverse() : []}
  renderBubble={props => this.renderBubble(props)}
  renderMessageText={props => this.renderMessageText(props)}
  renderTime={props => this.renderTime(props)}
  renderInputToolbar={props => this.renderInputToolbar(props)}
  renderComposer={props => this.renderComposer(props)}
  renderActions={props => this.renderActions(props)}
  renderSend={props => this.renderSend(props)}
  renderMessageImage={props => this.renderMessageImage(props)}
  onSend={messages => this.onSend(messages)}
  user={user}
/>

****

styles

inputToolBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    maxHeight: COMPOSER_HEIGHT,
    minHeight: COMPOSER_HEIGHT,
    justifyContent: 'center',
    borderTopWidth: 0,
    shadowOpacity: 0.10,
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: -2
    },
    elevation: 2,
    shadowRadius: 2
  },
  composerText: {
    maxHeight: COMPOSER_HEIGHT,
    fontFamily: 'Quicksand-Medium',
    color: '#333333',
    fontSize: Normalize(14),
  },
```

#### Additional Information

* Nodejs version: v9.2.1
* React version: 16.0.0
* React Native version: v0.51.0
* react-native-gifted-chat version: v0.3.0
* Platform(s) (iOS, Android, or both?): iOS

**Comment by LorienHW** [comment]
I see the same issue in v0.4.3 using the sample code from the readme:
```
<GiftedChat
              messages={this.state.messages}
              onSend={messages => this.onSend(messages)}
              user={{
                _id: 1,
              }}
            />
```

**Comment by melihmucuk** [comment]
@LorienHW didn't work for me.

**Comment by LorienHW** [comment]
@melihmucuk could be its working different in version v0.4.3 than in v0.3.0. You could try upgrading to the latest version, or look for a similar property/feature in the version you are using. If you look inside of the gifted-chat module for the code that is handling the onKeyboardWillShow/onKeyboardDidShow events you can see the code that is calculating how to adjust the chat view offsets when the keyboard is shown.

**Comment by theorytank** [comment]
I've been facing this for weeks now.  Just realized today that the issue isn't Gifted Chat (for me anyway).

Are you using native-base?  Are you wrapped in a <Content> container?

Try setting <Content enableAutomaticScroll={false}> and see if that fixes your issue.

The problem is the two components are "helping" each other by shifting the view upwards to compensate for the keyboard.  Note, that <Content> is actually a react-native-keyboard-aware-scroll-view <https://github.com/APSL/react-native-keyboard-aware-scroll-view> so if you're using that it might be the same issue.

I had to create a way for my app to know when the Chat view was showing (as it is a modal) and disable the automatic scroll.  Everything works like gold after that.

Special mention to @tomtom25 for looking outside the Gifted Chat code to solve it.  Good job buddy. (I'll never hear the end of this).

**Comment by diamont1001** [comment]
Solved it by setting `bottomOffset` and `react-native-iphone-x-helper.getBottomSpace`

like this:

```js
import {getBottomSpace} from 'react-native-iphone-x-helper';
<View style={paddingBottom: getBottomSpace()}>
...
  <GiftedChat
    messages={this.state.messages}
    bottomOffset={getBottomSpace()}
    onSend={messages => this.onSend(messages)}
    user={{
      _id: 1,
    }}
  />
</View>
```

**Comment by zach-luman** [comment]
Any updated solution here?

**Comment by brascene** [comment]
Looks like this is still an issue:
![Simulator Screen Shot - iPhone 11 - 2022-06-17 at 22 26 56](https://user-images.githubusercontent.com/20214107/174396748-8c01f692-3b02-4f96-807c-0f21b8578101.png)

**Comment by irodeanu** [comment]
`import { useSafeAreaInsets } from 'react-native-safe-area-context';`
`const insets = useSafeAreaInsets()`

and 

`
       <GiftedChat
        wrapInSafeArea={false}
        bottomOffset={insets.bottom}
... />
`
