### ISSUE TITLE
Mentions / autocomplete

### ISSUE THREAD

**Issue by PvanHengel** [FaridSafi/react-native-gifted-chat#855]
Hi there,  this library is awesome!  I was wondering if there is a way to do mentions or type ahead when entering a message, obviously we can parse and display after the message is written but would like a way to at least mention users with the @ sign simmilar to how this form works on github or slack.  Any pointers to an example would be great!

**Comment by nonotest** [comment]
I have looked around a little and ended up rolling my own.. 
lots of regex work though and a bit messy.

Anyway following if someone finds a good library !

**Comment by ddereszewski** [comment]
Did you find out something? I try using https://github.com/harshq/react-native-mentions it has hard time working together with gifted chat

**Comment by jariwalabhavesh** [comment]
@ddereszewski : Have fixed or implement  mention with gifted chat

**Comment by deepak-netsoft** [comment]
Hi @jariwalabhavesh  Did you found any solution?
