### ISSUE TITLE
Firebase integrations

### ISSUE THREAD

**Issue by augmen** [FaridSafi/react-native-gifted-chat#857]
how to integrate with firebase ? is it production ready ? whats the message transporter have you used socket ?

**Comment by ewal** [comment]
Integrating with a service such as Firebase or Pusher is not in the scope of this project. That part you have to figure out on your own 😄

**Comment by augmen** [comment]
is it full stack ?

**Comment by ewal** [comment]
I suggest that you start reading this article https://firebase.googleblog.com/2016/01/the-beginners-guide-to-react-native-and_84.html.

Other resources:
https://rnfirebase.io/
https://github.com/invertase/react-native-firebase
