### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by arayaryoma** [FaridSafi/react-native-gifted-chat#860]
#### Issue Description
React's life-cycle methods: `componentWillMount()` , `componentWillReceiveProps` , `componentWillUpdate` will be deprecated on v16.3.
Because the latest version of React Native depends to React v16.2, a few warnings will be displayed when I use GiftedChat component.
Do you have any plan to solve those warnings?
The deprecated methods are used at
- https://github.com/FaridSafi/react-native-gifted-chat/blob/85c6b0d69abe39018d34aa3b22a17a7f18e6029c/src/GiftedChat.js#L105
- https://github.com/FaridSafi/react-native-gifted-chat/blob/c4e3863a9e294d9e6977211d3e83ab16552da4f4/src/InputToolbar.js#L25
- https://github.com/FaridSafi/react-native-gifted-chat/blob/4dea9ba580380ad33ea8521c8335e42d15451901/src/MessageContainer.js#L42
- https://github.com/FaridSafi/react-native-gifted-chat/blob/85c6b0d69abe39018d34aa3b22a17a7f18e6029c/src/GiftedChat.js#L117

#### Steps to Reproduce / Code Snippets

Use GiftedChat component on latest version of React Native.

#### Expected Results

No warnings.

#### Additional Information

* Nodejs version: 9.1..1
* React version: 16.2.0
* React Native version: 0.55.0
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): both

Thank you for reading.

**Comment by karltaylor** [comment]
+!

**Comment by edgarogh** [comment]
This is still relevant today. I started receiving the warnings after migrating to React Native v0.60.

|                          | Version           |
|--------------------------|-------------------|
| React Native             | 0.60.0 (@latest)  |
| react-native-gifted-chat | ^0.9.11 (@latest) |

I'd love to help but I don't have the time right now.
