### ISSUE TITLE
Random caps-lock when writing messages

### ISSUE THREAD

**Issue by jaaberg** [FaridSafi/react-native-gifted-chat#862]
#### Issue Description

Recently, when writing messages, the text input has been acting like crazy, and swtiching between caps and non-caps characters at totally random times when writing. 

Edit: Found the source: iOS automatically caps the next character after an `.`, `?` etc. But if the last sign of your message is `.` or `?`, and you jump back and tries to edit already written text, it gets confused in some way.

#### Steps to Reproduce / Code Snippets

Edit: 
1) Any iOS-device and RNGC (tested on v0.3.0 and v0.4.3)
2) Use the same example as in the readme.
3) Write `Hi` followed by two spaces so that iOS automatically fills inn `Hi. ` and sets caps for the next letter. 
4) Instead of writing more, move the cursor to be between the `H` and the `i` and try to write something. Now the caps is confused and vil automatically be on, and if you try to turn it off it just turns on again for the next letter. 

I made an expo snack: [https://snack.expo.io/SJ4SnU6CG](https://snack.expo.io/SJ4SnU6CG). Remember to switch to the iOS simulator in the lower right corner. 

#### Expected Results

Caps lock randomly turns on and off while writing, but shouldn't. 

#### Additional Information

* React version: 16.3.0-alpha.1
* React Native version: 0.54
* react-native-gifted-chat version: 0.3.0
* Platform(s) (iOS, Android, or both?): iOS (but maybe both, not sure)

This was my setup, but also tested on RNGC v0.4.3 with same problem. This is not a problem with the regular react-native textinput.

**Comment by jaaberg** [comment]
After some digging, it seems like this is a react-native issue with controlled `TextInputs`. I've created an issue there as well. 

https://github.com/facebook/react-native/issues/19389

**Comment by dchersey** [comment]
FYI, that issue was possibly fixed with RN 0.56 but the CAPS behavior is still randomly re-occuring for some of my users for the chat app I have built using Gifted Chat.  It's less frequent, but perhaps triggered by another sequence of actions.  Anybody else still seeing it?
