### ISSUE TITLE
Not rendering new updated messages when using a redux property for messages

### ISSUE THREAD

**Issue by mypark** [FaridSafi/react-native-gifted-chat#863]
#### Issue Description

Not rendering new messages when using a redux property for messages.  It renders the initial set of messages fine, just not the new ones.

#### Steps to Reproduce / Code Snippets

1. set messages to reference a redux connected property `this.props.messages` instead of `this.state.messages`
2. send new message with a redux flux action -> update store -> triggers render again with an updated messages property that includes the new message appended.

```
   let { user, conversations: { messages } } = this.props;

   <GiftedChat
      messages={messages}
      onSend={newMessages => this.onSend(newMessages)}
      user={{
        _id: user.id,
      }}
      textInputProps={{ autoFocus: conversationId ? false : true }}
      listViewProps={{ style: { backgroundColor: 'transparent' } }}
    />
```

#### Expected Results

The new message item has not rendered on the UI even though the render method has triggered again with the updated data.  How do I trigger the from the redux update - should I  do something on componentWillReceiveProps?

#### Additional Information

    "react": "16.3.1",
    "react-native": "^0.55.3",
    "react-native-gifted-chat": "^0.4.3",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-actions": "^2.3.0",
    "redux-observable": "^0.18.0",
    "rxjs": "^5.5.10",

**Comment by mypark** [comment]
it was an issue with my reducer - mutating state.messages when i needed to clone state.messages before updating.

**Comment by prasannaballal** [comment]
Helped me.
Thanks for posting.
