### ISSUE TITLE
User Name style

### ISSUE THREAD

**Issue by 6axter82** [FaridSafi/react-native-gifted-chat#866]
#### User Name style

Is there any way to change the style of a user name?

If the name of the user is toooooooo long, I want to be able to truncate the name with `...` and put some horizontal padding into it.

**Comment by emilkarl** [comment]
You could probably handle this before sending it to Gifted Chat. Check name length and truncate. You also got a built-in stuff in React Native you can use if you want to extend this repo. https://facebook.github.io/react-native/docs/text.html#ellipsizemode
