### ISSUE TITLE
Can't display images when using Redux

### ISSUE THREAD

**Issue by MeKyleH** [FaridSafi/react-native-gifted-chat#872]
#### Issue Description
I'm using redux so I can save my messages in a database and load them between multiple users and multiple sessions. My GiftedChat component uses a custom onSend function that stores the messages in the database. However, I can't ever get an image to be added to the messageText. 

As you can see the from the log below the image never gets added to messageText so it isn't ever saved to the database or displayed to the user.

#### Steps to Reproduce / Code Snippets

Here's what my code looks like:
```
<GiftedChat
    messages={messagesList}
   onSend={(messageText) => {
    this.props.messageCreate({ messageText, otherUserId, myFriendId, otherFriendId });
  }}
  createdAt={new Date()}
  image={{ uri: testImage }}
  user={{
    _id: otherUserId,
    name: myName
  }}
  renderActions={this.renderActions.bind(this)}
  renderBubble={this.renderBubble}
  renderInputToolbar={this.renderInputToolbar}
  renderTime={this.renderTime.bind(this)}
  renderMessageImage={this.renderMessageImage}
/>
```

Here's what messageText looks like when I log it:
```
messageText Array [
  Object {
    "_id": "dsdsfas-sdkfs-fjds-dh-fhsdfs",
    "createdAt": 2018-05-25T18:33:15.155Z,
    "text": "My test message",
    "user": Object {
      "_id": "73safdhf2",
      "name": "Peter Parker",
    },
  },
]
```

#### Expected Results

Image is added to the messageText object so that I can save it to the database and display it to the user.

#### Additional Information

* Nodejs version: 9.3.0
* React version: 16.3.1
* React Native version: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): Both

**Comment by MeKyleH** [comment]
I was able to resolve this issue by switching from using onSend as a prop in the <GiftedChat> component to using a custom renderSend method and recreating the message. I'm able to add images to the messages now as well, but I can't display the image before the message is sent though. If anyone has any thoughts that would be helpful.

**Comment by ewal** [comment]
The image prop is just a string. You are passing an object in your example. And the image should be attached to each message, not the GiftedChat component.
