### ISSUE TITLE
InputToolBar spacing on iPhoneX

### ISSUE THREAD

**Issue by MeKyleH** [FaridSafi/react-native-gifted-chat#874]
#### Issue Description

There is an issue with iPhoneX where you either have the message that you are typing overlap with the bottom bar and can't see all of your text, or if you add a marginBottom you overlap with the avatar from the most recent message.

Here is some text entered into the text box:
![simulator screen shot - iphone x - 2018-05-26 at 14 33 07](https://user-images.githubusercontent.com/10005680/40580382-dac4adc6-60f1-11e8-8c03-5b6ba491d6da.png)

If you add one more character you get this strange artifact:
![simulator screen shot - iphone x - 2018-05-26 at 14 33 09](https://user-images.githubusercontent.com/10005680/40580385-eafc53ec-60f1-11e8-9b6e-db8ee6332c04.png)

If you style the input toolbar then it overlaps the Initials Avatar of the last message:
![simulator screen shot - iphone x - 2018-05-26 at 14 33 55](https://user-images.githubusercontent.com/10005680/40580389-faf3889c-60f1-11e8-969f-91ae0ad588e5.png)

#### Steps to Reproduce / Code Snippets

Default inputToolbar code:
```
  renderInputToolbar(props) {
    return <InputToolbar {...props} containerStyle={styles.inputToolbarStyle} />;
  }
```

Here is the styling:
```
inputToolbarStyle: {
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: CommonStyles.colors.middleGrey,
    borderRadius: 25
  },
```

#### Expected Results

Should be able to add some padding below the avatar or at least line up the bottom of the avatar with the bottom of the last message

#### Additional Information

* Nodejs version: 9.3.0
* React version: 16.3.1
* React Native version: Expo version 27
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): Both

**Comment by MeKyleH** [comment]
I was able to fix the overlap by adding marginBottom: 5 to Avatar.js styles.left.container on line 73. I don't know if other people are having this problem as well.

**Comment by ewal** [comment]
@MeKyleH, just out of curiosity, do you wrap GiftedChat in a SafeAreaView?

**Comment by MeKyleH** [comment]
@ewal I wasn't wrapping it in a SafeAreaView. However, after adding that it resolved the strange artifact with the text not displaying correctly when typing. Thanks so much!

**Comment by ewal** [comment]
Awesomeness 😄

**Comment by anceque** [comment]
@ewal and what to do when you have it inside of `SafeAreaView`? it created some nasty bottom spacing when the keyboard is open :(

**Comment by msqar** [comment]
Any tutorial on how you achieved that look & feel? i'm super lost! :/

**Comment by msqar** [comment]
@anceque can you show me what bottomOffset you put? didn't get the "by the height of bottom safeArea" part.

**Comment by phil-flyclops** [comment]
This library gives you a nice interface to get the right value for bottomOffset on iPhoneX and no offset on other phones https://github.com/ptelad/react-native-iphone-x-helper

**Comment by diamont1001** [comment]
@msqar 

Solved it by setting `bottomOffset` and `react-native-iphone-x-helper.getBottomSpace`

like this:

```js
import {getBottomSpace} from 'react-native-iphone-x-helper';

<View style={paddingBottom: getBottomSpace()}>
...
  <GiftedChat
    messages={this.state.messages}
    bottomOffset={getBottomSpace()}
    onSend={messages => this.onSend(messages)}
    user={{
      _id: 1,
    }}
  />
</View>
```

**Comment by mcanikhilprajapati** [comment]
bottomOffset working perfect. 
Thanks @diamont1001 you saved my time

**Comment by theneekz** [comment]
I've found that the bottom offset doesn't detect any changes while the keyboard is open. This is still an issue for me
