### ISSUE TITLE
ImageMessage：how to zoom in and click image to close lightbox ?

### ISSUE THREAD

**Issue by 12343954** [FaridSafi/react-native-gifted-chat#875]
#### Issue Description

how to customize the ImageMessage to zoom in and click image itself to close the lightbox？

thank you so much !

#### Steps to Reproduce / Code Snippets

![wechatimg13](https://user-images.githubusercontent.com/1804003/40614279-e0812f4a-62b4-11e8-8f7d-804574efeff9.jpeg)

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: v8.2.1
* React version: 16.0.0
* React Native version: 0.50.3
* react-native-gifted-chat version: ^0.4.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by loyoliteabid** [comment]
Any updates on this?

**Comment by pradeep351** [comment]
How to zoom photo in msgs?

**Comment by pradeep351** [comment]
@loyoliteabid  I tried to execute your code, but getting error of "Undefined ({...otherProps})".

**Comment by loyoliteabid** [comment]
@pradeep351, I meant `{...otherProps}` as the other required props for `<GiftedChat />`.  That was confusing so now  I have edited my code.

**Comment by pradeep351** [comment]
@loyoliteabid  Thanks for sharing the code. It's working now.

**Comment by SaiKiran322** [comment]
@12343954  Can u please provide your code snippet for sending images in chat please!!!

**Comment by 12343954** [comment]
@loyoliteabid thank you very much ! your code seemed works well !

**Comment by 12343954** [comment]
@SaiKiran322 post images , use axios.post({}) or fetch(post) with 'Content-Type': 'multipart/form-data' and FormData



`
import ImagePicker from 'react-native-image-picker';
...
let postData = new FormData();

// k store a image {image, filename, type} after 'ImagePicker' select a image
postData.append(`file`, {
    uri: k.image,
    name: k.filename,
    type: mime.lookup(k.filename),
});

// console.log(postData)

postData.append('userid', this.user._id);
postData.append('group', this.groupID);

axios.post(WebAPI.url.chat.PostImage,
    postData,
    {
        headers: { 'Content-Type': 'multipart/form-data', },
    }
).then(response => {
    // console.log(response.data)
    const { return_code, msg, data } = response.data;
    if (return_code) {  // upload succeed , server end will return a remote image url in 'data' field
        if (this.isSignalRconnected) {

            // upload succeed , i call my signalr service to send message on real-time, you can use other chat services
            this.proxy.invoke('send', this.user._id, this.user.name, JSON.stringify(data[0]), 'image', this.groupID, true, null);  

        } else {
            // this.addLocalMessage(messages[0]);
        }

        // upload succeed , add it to local message queue to show out
        this.postWebAPIMessage(JSON.stringify(data[0]), ChatMessageType.IMAGE);

    }
}).catch(error => {
    console.log('line:690: MessageScreen - onSend - PostImage', error)
})
})
`

**Comment by SaiKiran322** [comment]
@12343954 im done with the back end part .i want to know how to load that images in gifted chat using that messageImage  function .

**Comment by 12343954** [comment]
@SaiKiran322 
simple way is using the ’react-native-gifted-chat‘ example code
or using @loyoliteabid his code  

```
renderMessageImage = (props) => {
    let image = props.currentMessage;
    let v_width, v_height, max_height = 500;

    if (typeof (props.currentMessage) === 'string') {
        image = JSON.parse(props.currentMessage);
    }

    let radio = image.width / image.height;
    if (image.width >= image.height) {  //w:200,h:100, rate:2
        v_width = 200;
        v_height = v_width / radio
    } else {
        v_height = 200;
        v_width = v_height * radio;
    }

    return (
        <MessageImage
            {...props}
            imageStyle={{ borderRadius: 0, height: v_height, width: v_width, backgroundColor: 'black' }}
            imageProps={{ defaultSource: require('../../Images/bg_image.jpg') }}
        />)
}

render(){
        <GiftedChat 
            renderMessageImage={this.renderMessageImage} />
}

```
