### ISSUE TITLE
Feature Idea: ship the TypeScript types for this project

### ISSUE THREAD

**Issue by fbartho** [FaridSafi/react-native-gifted-chat#876]
#### Issue Description

Currently the package.json for this repo gets modified when deploying to NPM.

In GitHub, it has a `"types": "index.d.ts"` entry, but in npm, it does not include this file.

#### Steps to Reproduce / Code Snippets

1. Using npm/yarn, Install react-native-gifted-chat
2. Diff package.json in node_modules with package.json on GitHub.
3. Notice how the types line is gone, and no index.d.ts exists in the npm node_module.

#### Expected Results

It'd be great if TypeScript types were available in this node_module.

#### Additional Information

* Nodejs version: 10.x | 9.x
* React version: 16.3.x
* React Native version: 0.55.x
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): Both

**Comment by fbartho** [comment]
Accidentally duplicated #731

**Comment by lucasbento** [comment]
I believe it's because there has been no release after https://github.com/FaridSafi/react-native-gifted-chat/commit/7232ac023e11068b4eb7ae1ed72e848914ddf786.

cc @xcarpentier, would you be able to release a new version? I'm looking forward for the types as well.

**Comment by fbartho** [comment]
@lucasbento: https://github.com/FaridSafi/react-native-gifted-chat/pull/877 I also made some fixes to the types, I’d love to help contribute more!

**Comment by lucsky** [comment]
@lucasbento is right, the `index.d.ts` file has been removed from `.npmignore` *after* the 0.4.3 release so the release notes are basically incorrect, Typescript typings are not available. There should either be a new 0.4.3 release or a 0.4.4.

**Comment by lucsky** [comment]
Poke @xcarpentier 😇

**Comment by fbartho** [comment]
My experience is that things are successfully landing in `master` but they aren't getting deployed at all, so my team's project is directly using `master` as our target "version"

**Comment by xcarpentier** [comment]
#1190
