### ISSUE TITLE
Temporary solution of “GIF” message（display or upload）

### ISSUE THREAD

**Issue by 12343954** [FaridSafi/react-native-gifted-chat#878]
#### Issue Description

CameraRollPicker doesn't return the gif's original path，so，you can't display the gif with <Image/>, or upload it to server end.

#### Steps to Reproduce / Code Snippets

**solution：**

use **“react-native-image-picker”** instead of **“react-native-camera-roll-picker”**

https://stackoverflow.com/questions/50588672/react-native-cameraroll-getphotos-gif-uri-no-animation-why

#### Expected Results

![untitled](https://user-images.githubusercontent.com/1804003/40698824-af06e9c8-6403-11e8-9551-6d9d5b3ca71e.gif)

#### Additional Information

* Nodejs version: v8.2.1
* React version: 16.0.0
* React Native version: 0.50.3
* react-native-gifted-chat version: ^0.4.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by nagasai-tilicho** [comment]
Still having issues in android
