### ISSUE TITLE
Android nav bar disappear when keyboard up (react-native-navigation)

### ISSUE THREAD

**Issue by sirawat93** [FaridSafi/react-native-gifted-chat#883]
Nav bar disappear when keyboard is on in Android.

<img width="343" alt="screen shot 2018-06-04 at 2 52 49 pm" src="https://user-images.githubusercontent.com/6262268/40905399-05668a82-6808-11e8-939e-b1fcb15329eb.png">

<img width="346" alt="screen shot 2018-06-04 at 2 53 38 pm" src="https://user-images.githubusercontent.com/6262268/40905408-112dc04c-6808-11e8-9f57-59b1e21deb48.png">

* Nodejs version: 8.11.2
* React version: 16.0.0
* React Native version: 0.53
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): Android
* react-native-navigation version: 1.1.462

**Comment by zarnifoulette** [comment]
Same here, did you find a solution ?

**Comment by sirawat93** [comment]
after some of digging, it seems when keyboard is up,

**Comment by sirawat93** [comment]
not yet

**Comment by SinanBaymammadli** [comment]
I had changed my AndroidManifest.xml to this

<activity
        ...
        android:windowSoftInputMode="stateAlwaysHidden">

When i reverted back to this, it is fixed.

<activity
        ...
        android:windowSoftInputMode="adjustResize">

**Comment by sirawat93** [comment]
thank your for ur respond @SinanBaymammadli  
but I just tested this on release App, the result was still the same.

**Comment by zarnifoulette** [comment]
My problem is solve when I don't use the chat in the root component of RNN.

**Comment by CodingPapi** [comment]
@zagoa hi, I have tried your solution, but no luck.
can U show me some detail code about this? thanks!

**Comment by sibelius** [comment]
Fix using android manifest

**Comment by arunkrishnang86** [comment]
Any update on this?
