### ISSUE TITLE
How to delete a already loaded chat bubble?

### ISSUE THREAD

**Issue by bastolaxantos** [FaridSafi/react-native-gifted-chat#884]
I am loading the chat from my own server. I managed to put a delete option which appear on long pressing   
chat bubble. I want to remove that bubble from screen when user deletes it. How can i achieve it?

**Comment by ewal** [comment]
Just delete it from your store/state. The chat should re-render and the message will be removed.

**Comment by nolife08021** [comment]
@bastolaxantos  Hi, how do you put the delete option when onlongpress called?

**Comment by bastolaxantos** [comment]
> @bastolaxantos Hi, how do you put the delete option when onlongpress called?

There is already onLongPress props, you can use that one. By default it shows 'copy text', you can add Delete option there.
