### ISSUE TITLE
Inline images in message?

### ISSUE THREAD

**Issue by emilkarl** [FaridSafi/react-native-gifted-chat#885]
#### Issue Description

Trying to get inline images in messages to work. Adding a separate pattern and `renderText` function. But they end up in the same line as the text. I would like them to be on separate lines and split the text.

It also never replaces all occurrences of my pattern, just the first one? 

![image](https://user-images.githubusercontent.com/10711/40909559-25493534-67ea-11e8-8861-4968524cf02a.png)

#### Steps to Reproduce / Code Snippets

```javascript
renderImage = (matchingString, matches) => (
  <View
    style={{
      paddingVertical: 10,
    }}
  >
    <MessageImage currentMessage={{ image: matches[1] }} />
  </View>
);

render() {
  return (
    <SafeAreaView style={styles.screen}>
      <GiftedChat
        parsePatterns={() => [
          {
            pattern: /\[IMG:(.+?)\]/gi,
            style: {},
            onPress: () => {},
            renderText: this.renderImage,
          },
        ]}
      />
    </SafeAreaView>
  );
}
```

#### Additional Information

* Nodejs version: v8.9.4
* React version: 16.3.1
* React Native version: 0.55.4
* react-native-gifted-chat version: ^0.4.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by ewal** [comment]
Solved in this pr https://github.com/FaridSafi/react-native-gifted-chat/pull/892, if you use Markdown, that is.

**Comment by AkAyush** [comment]
Hi, I am using react-native-gifted-chat and i wanted to know, how to restrict the user to input any phone number or email address in chat ?? 

In My second scenario, I want to replace my chated phone number or email with ********* so that the end user cant see the shared number or email for the privacy reason.

  
PLEASE HELP I AM NEW WITH THIS LIBRARY

**Comment by ewal** [comment]
@AkAyush, your question is not related to the current issue. Please direct your question in a new issue. However, you'll find your solution here: https://github.com/taskrabbit/react-native-parsed-text

**Comment by emilkarl** [comment]
I agree with @ewal @AkAyush . This is a separate question but you might be able to do something like this...

```javascript
render() {
  const renderPhone = (matchingString, matches) => (<Text>*********</Text>);
  return (
    <GiftedChat
      parsePatterns={() => [
        {
          pattern: 'phone',
          renderText: renderPhone,
        },
      ]}
    />
  );
}
```

**Comment by AkAyush** [comment]
Thank You so much @emilkarl, it's working 👍
