### ISSUE TITLE
Render Time outside of bubble

### ISSUE THREAD

**Issue by deepakdezire23** [FaridSafi/react-native-gifted-chat#887]
#### Issue Description
I have to show time outside of bubble. How  can i achieve this?

#### Additional Information

* Nodejs version: 5.3.0
* React version: 16.0.0
* React Native version: 0.50.3
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?):Android

**Comment by Thyix** [comment]
Same question here ! @deepakdezire23

**Comment by juanscilingo** [comment]
I think you can achieve this by copying the Bubble component from gifted chat (https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/Bubble.js) into your code and modifying it to render the time outside of the bubble (the this.renderTime() function call), and then passing it to the renderBubble prop of gifted chat.
