### ISSUE TITLE
"Type message.."Input is behind keyboard

### ISSUE THREAD

**Issue by alfizo** [FaridSafi/react-native-gifted-chat#899]
#### Issue Description
"Type message.."Input is behind keyboard
you cant see what your typing until u remove keyboard.

#### Steps to Reproduce / Code Snippets
I opened the project with expo and tried to type

#### Expected Results
Input Textbox should be above keyboard on focus so you can see what you are typing.
[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
![whatsapp image 2018-06-10 at 23 43 25](https://user-images.githubusercontent.com/19353947/41206697-4e84d2e6-6d08-11e8-8898-8c1098065e6e.jpeg)

**Comment by alfizo** [comment]
After investigation i learned this issue only happens with expo. 
I found a fix on a previous post [#461](https://github.com/FaridSafi/react-native-gifted-chat/issues/461)

import React, { Component } from 'react';
import { View, Platform } from 'react-native';
import KeyboardSpacer from 'react-native-keyboard-spacer';
import { GiftedChat } from 'react-native-gifted-chat';

export default class Chat extends Component {
  render() {
    const giftedChatMessages = [
      ...
    ];
    return (
      <View style={{flex: 1}}>
        <GiftedChat
          messages={giftedChatMessages}
          onSend={newMessages => onSend(newMessages[0].text)}
          user={{
              _id: 1,
          }}
          renderAvatar={() => null}
        />
        {Platform.OS === 'android' ? <KeyboardSpacer /> : null }
      </View>   
    )
  }
}

**Comment by pareshr13** [comment]
Thanks.

**Comment by ibenettaleb** [comment]
> Thank You!

**Comment by lwf804** [comment]
Thanks @alfizo !

**Comment by todovica** [comment]
Thanks! :)
