### ISSUE TITLE
Replace the phone and email into the chat with ******* 

### ISSUE THREAD

**Issue by AkAyush** [FaridSafi/react-native-gifted-chat#900]
#### Issue Description

Hi, I am using react-native-gifted-chat and I wanted to know, how to restrict the user to input any phone number or email address in chat ??

In My second scenario, I want to replace my chated phone number or email with ********* so that the end user cant see the shared number or email for the privacy reason.

PLEASE HELP I AM NEW WITH THIS LIBRARY

* React version: "16.3.1"
* React Native version: 0.55.1
* react-native-gifted-chat version: ^0.4.3
* Platform(s) (iOS, Android, or both?): both

**Comment by emilkarl** [comment]
@AkAyush how did you solve this? 🎉 

Reference: #885

**Comment by AkAyush** [comment]
Yes, thank you @emilkarl

**Comment by Faolain** [comment]
Can you please close this issue @AkAyush ?
