### ISSUE TITLE
Calculate message container height

### ISSUE THREAD

**Issue by userbq201** [FaridSafi/react-native-gifted-chat#902]
```
      <AnimatedView
        style={{
          height: this.state.messagesContainerHeight,
        }}
      >
```

After show keyboard and hide calculate height very slow. What to do ? My decision
```
      <AnimatedView
        style={{
          height: '100%',
          paddingBottom: this.props.minInputToolbarHeight + 10
        }}
      >
```
And now height = 100% and toolbar not change height

**Comment by userbq201** [comment]
my solution
https://github.com/userbq201/react-native-gifted-chat/commit/04c7b0a652d744cdcba72e56b4fa4afb6f374c01

**Comment by DingTaiKeji** [comment]
According to your solution, Android works well, but the InputToolbar is covered by the keyboard on iOS.

**Comment by userbq201** [comment]
@DingTaiKeji for ios use KeyboardAvoidingView

**Comment by userbq201** [comment]
easy. No lags.
