### ISSUE TITLE
CRASH textInput focused inside TabNavigator inside StackNavigator

### ISSUE THREAD

**Issue by munkhbaatar999** [FaridSafi/react-native-gifted-chat#903]
#### Issue Description
My structure 
Stack Navigator -> TabNavigator -> ChatScreeStack -> NewChat 

When textInput or keyboard appear then CRASHING error named native DrawTextLine
But i put normal TextInput instead of giftedChat works fine.

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by gogogous88** [comment]
same problem here

**Comment by gogogous88** [comment]
well, my problem solved by upgrade expo 23.0.0 to 24.0.0
I believe it is due to the problem of RN 0.50.0 not compatible with gifted chat on iOS

**Comment by munkhbaatar999** [comment]
aan i'm gonna try that out soon then recomment.
