### ISSUE TITLE
Show attachment before sending the message

### ISSUE THREAD

**Issue by Zain-ulHassan** [FaridSafi/react-native-gifted-chat#905]
i want to show the attachment(image, file etc) above the input before sending message, is there any way to do this.

**Comment by ahartzog** [comment]
Assuming you have the path to the image in state...

` renderChatFooter = () => {
    if (this.state.imagePath) {
      return (
        <View>
          <Text>Image loaded:</Text>
          <Image
            source={{ uri: this.state.imagePath }}
            style={{ height: 75, width: 75 }}
          />
        </View>
      );
    }

    return null;
  };`
