### ISSUE TITLE
How to customize the accessory height?

### ISSUE THREAD

**Issue by ATShiTou** [FaridSafi/react-native-gifted-chat#911]
#### Issue Description

I'd like to develop an app like wechat:

![image](https://user-images.githubusercontent.com/38748693/41807908-32b54c38-7700-11e8-9719-8dee4a68395d.png)

I tried to custom the accessory height like this:
```
<GiftedChat
    renderAccessory={()=><View style={{height:300}}/>
/>
```
But failed.
#### Steps to Reproduce / Code Snippets

I looked up the lib source code ,and try to change accessoryStyle
```
<GiftedChat
    renderAccessory={()=><View style={{flex:1}}/>
    accessoryStyle={{height: 300}}
/>
```
It works, but the accessory has covered the message container.
#### Expected Results

Custom the accessory height and do not cover the message container.

#### Additional Information

* Nodejs version:  10.0.0
* React version: 16.3.1
* React Native version: 0.55.4
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by moerabaya** [comment]
@ATShiTou did you manage to fix it?

**Comment by ATShiTou** [comment]
NO，I give up to use this library and do it myself.

**Comment by HarryPT** [comment]
@ATShiTou Can you share your solution, please?

**Comment by Durisvk** [comment]
@k1115 @moerabaya @ATShiTou 

based on the PR #1524 that is not yet merged,
you can still extend the class both in pure javascript and typescript,

here's a TypeScript example:

```tsx
class GiftedChatExtended extends GiftedChat {
  componentDidUpdate(prevProps: GiftedChatProps, prevState: any, snapshot?: any) {
    super.componentDidUpdate && super.componentDidUpdate(prevProps, prevState, snapshot);

    if (prevProps.minInputToolbarHeight !== this.props.minInputToolbarHeight) {
      this.setState({
        messagesContainerHeight: this.prepareMessagesContainerHeight(
          this.getBasicMessagesContainerHeight() - this.getKeyboardHeight()
        ),
      });
    }
  }
}
```

and then use `GiftedChatExtended` however you'd use original `GiftedChat` component

**Comment by shamilovtim** [comment]
@Durisvk very clever work, nice job.

**Comment by SiroSong** [comment]
why i can't find this.prepareMessagesContainerHeight() in GiftedChat? It isn't here? but I return the value without wrapped with it, the messageContarinerHeight make work yet.

**Comment by madsrode** [comment]
This seems to do the job
`        renderInputToolbar={(props) => {
          return <InputToolbar {...props} accessoryStyle={{
            height: showAccessory ? 44 : 0
          }} />;
        }}`

**Comment by huy-lv** [comment]
@Durisvk your suggestion worked but this may leads infinity loop

**Comment by fukemy** [comment]
i think better get keyboard height first, then set accessoryHeight to keyboardHeight, any solution? Thanks

**Comment by fukemy** [comment]
hi, any solution for this case?

**Comment by fukemy** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> It works, but the accessory has covered the message container.

it's working in ios but android failed, accessoryView still cover messageContainer

**Comment by fukemy** [comment]
> This seems to do the job `renderInputToolbar={(props) => { return <InputToolbar {...props} accessoryStyle={{ height: showAcc ? 44 : 0 }} />; }}`

it's working in ios but android failed, accessoryView still cover messageContainer
