### ISSUE TITLE
Inverted = false causes message list to scroll-to-top on send

### ISSUE THREAD

**Issue by willdady** [FaridSafi/react-native-gifted-chat#912]
#### Issue Description

Message list scrolls-to-top when submitting a new message when `inverted={false}`

#### Steps to Reproduce / Code Snippets

Set `inverted={false}`

#### Expected Results

The README says...

> inverted (Bool) - Reverses display order of messages; default is true

... the message order is reversed as expected however it **also** causes the message list to scroll-to-top when a new message is entered which seems like the wrong behavior

#### Additional Information

* Nodejs version: 8.10.0
* React version: 16.3.0-alpha.1
* React Native version: 0.54.4
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by guopeng1994** [comment]
did u resolve it ? any solutions?

**Comment by naiger** [comment]
same problem here

**Comment by Parthasarath** [comment]
I'm also facing this issue,Did u resolve it?@willdady

**Comment by jonasfrid** [comment]
Same issue here! Anyone found a solution?

**Comment by willdady** [comment]
Workaround I've used is to not set `inverted` and to reverse the order of the messages array using [lodash's reverse function](https://lodash.com/docs/4.17.11#reverse) before passing it to the `messages` prop.

**Comment by songxiaoliang** [comment]
Same issue here! Anyone found a solution?
