### ISSUE TITLE
Weird height on message field on iOS using a fixed footer

### ISSUE THREAD

**Issue by maendamedia** [FaridSafi/react-native-gifted-chat#915]
I use a custom footer (audio player) on all screens. I set this fixed on the App.js where I use React-Navigation routes. In the render part I render the Drawernavigator, followed by the Player component.

If I open a chat page on iOS and try to sent a message, the textfield is a very large field. This is because of the player component. If I remove that, it is ok.
Is there a way to fix this? Or maybe I miss something?

**Comment by AntoineGrandchamp** [comment]
I had a similar problem. The problem was that I was using a KeyboardAvoidingView and react-native-gifted-chat already handle the keyboard height.

**Comment by maendamedia** [comment]
Sorry for terrible late response. I just picked up the project haha.
I still have same problem i do not use KeyboardAvoidingView anywhere yet. I do see that it is caused by a component i render on bottom of the app on every page. If i remove it, it is ok.

BUt... there is nothing in that component which seems to cause this haha.

Any ideas

**Comment by AndrzejKaczynski** [comment]
> I had a similar problem. The problem was that I was using a KeyboardAvoidingView and react-native-gifted-chat already handle the keyboard height.

that's true, it helped in my case
