### ISSUE TITLE
Message container needs to reflect minInputToolbarHeight when prop changes

### ISSUE THREAD

**Issue by watadarkstar** [FaridSafi/react-native-gifted-chat#920]
#### Issue Description

I have a use case where I hide/show the input toolbar by passing `minInputToolbarHeight` in props. Hence, I need the messages container height to reflect on changes of `minInputToolbarHeight`.

Outdated PRs:
https://github.com/FaridSafi/react-native-gifted-chat/pull/537 @kesha-antonov  
https://github.com/FaridSafi/react-native-gifted-chat/pull/498 @peteroid  

#### Steps to Reproduce / Code Snippets

Dynamically change `minInputToolbarHeight` via state.

#### Expected Results

Height changes when props change.

#### Additional Information

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.1 AI-173.4720617

Packages:
  react: 16.2.0 => 16.2.0
  react-native: 0.51.0 => 0.51.0
  react-native-gifted-chat => "0.4.3"

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/flyreel-eb36a54c-2ec6-4fef-8948-75ef7a13a44c.tar.gz

**Comment by jascination** [comment]
@watadarkstar This is still an issue in 2021 as far as I can tell, any idea if this was ever attempted to be resolved / if there's any way around it?

I have a custom input field for a chatbot whose height changes dynamically, and I want to ensure the chat screen doesn't get hidden behind it.

**Comment by watadarkstar** [comment]
@jascination Its been a really long time since I've looked at this bug. I can check my codebase and see what I did in the next few days.

**Comment by jascination** [comment]
That's be awesome. I might make a new issue for it as well, cos it seems to still be an issue.

**Comment by watadarkstar** [comment]
Please do and tag me in the new issue @jascination
