### ISSUE TITLE
Regression: Showing keyboard on an empty chat does not resize the message view.

### ISSUE THREAD

**Issue by baytelman** [FaridSafi/react-native-gifted-chat#923]
#### Issue Description

On Latest commit #1fedba2:
When keyboard shows up, the message area doesn't resize, hiding the input field.

#### Steps to Reproduce / Code Snippets

- New chat
- Show keyboard by focusing the text area.
- The keyboard shows up
= Message area doesn't resize
= Input field is hidden.

#### Expected Results

= Message area should resize and input field visible.

#### Additional Information

* Nodejs version: `v8.9.4`
* React version: `react@16.3.1`
* React Native version: `https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz`(version "0.55.2")
* react-native-gifted-chat version: `Commit #1fedba21`
* Platform(s) (iOS, Android, or both?): `iOS`

**Comment by kesha-antonov** [comment]
+1 !!!

**Comment by ahartzog** [comment]
Still seeing this issue after updating to the commit referenced above (#052094d). 

I've tried both with forceGetKeyboardHeight and without.

![image](https://user-images.githubusercontent.com/9828263/43679273-b2b000a2-97f0-11e8-87fb-b981cc9c8da4.png)

**Comment by rossgeesman** [comment]
I'm having a similar problem. Messages will continue to be added to behind the keyboard. It seems the list should scroll to the bottom so the last message is always visible.
<img width="434" alt="screen shot 2018-09-06 at 12 39 36 pm" src="https://user-images.githubusercontent.com/3291745/45181072-311c8000-b1d2-11e8-9c3b-5149486624f5.png">
