### ISSUE TITLE
custom vars on chat message

### ISSUE THREAD

**Issue by Andresagustin** [FaridSafi/react-native-gifted-chat#924]
Hi guys, I have a quick question. I need to pass the channelID to the server on each chat message without editing the message itself. There is any way to add as a parameter on the component?

like:

  <GiftedChat
        messages={this.state.messages}
        onSend={messages => this.onSend(messages)}
        placeholder={'Escriba su mensaje'}
        user={this.state.myUser}
        channelID={'THISISWHATIMLOOKINGFOR'}
      />

so I can get the channel id on the backend like

{ text: 'Ggh',
  user: '773767704195',
  createdAt: '2018-07-09T05:48:54.064Z',
  _id: 'c8ddd763-53f4-4bae-b343-0fee6368aee6',
 channelID: 'THISISWHATIMLOOKINGFOR' }

Thanks!!

**Comment by magworkss** [comment]
@Andresagustin which approach did you choose for fixing this issue ?
