### ISSUE TITLE
Avatar with SVG files "uri" is slowly rendering for both OS, and disappearing in iOS

### ISSUE THREAD

**Issue by alexgnatrow** [FaridSafi/react-native-gifted-chat#925]
Avatar with SVG files uri is slowly rendering for both OS, and furthermore they are disappering after scrolling up and down again on Android, and seem not to in iOS.

###This is my avatar renderer:
`<View key={props.currentMessage.id}>
        <View>
          <View hex={hex} onTouchEnd={this.handleOpenCtxMenu}>
            {isCurrentUser ? (
              <View>
                <Text isMe>Me:</Text>
              </View>
            ) : (
              <Avatar
                {...props}
                imageStyle={{
                  left: {
                    backgroundColor: 'transparent',
                    height: 130,
                    width: 90,
                    left: -12.5,
                    top: 2
                  },
                  right: {
                    backgroundColor: 'rgb(182, 246, 106)'
                  }
                }}
                onPressAvatar={
                  !isBusy ? e => this.handleAvatarPress(e, user) : () => {}
                }
              />
            )}
          </View>
        </View>
        <View>
          {!isCurrentUser && (
            <View>
              <Text>{`${name} :`}</Text>
            </View>
          )}
          <Text>{text}</Text>
        </View>
      </View>`

###This is the object I am pushing to message array, which I I apply to GiftedChat component after:
{
          _id: id,
          text: message,
          createdAt: new Date(sent_dt),
          user: {
            _id: user_id,
            name: username,
            avatar: `${url}.svg`,
            hex: hex
          }

It should at least not disappear at scroll back down as it does in Android.

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0

* react-native-gifted-chat version: 0.4.3

**Comment by arifo** [comment]
same issue, any fix or workaround for this?
