### ISSUE TITLE
Keyboard very slow!

### ISSUE THREAD

**Issue by userbq201** [FaridSafi/react-native-gifted-chat#926]
rn - 0.55
chat 0.4.3

I quickly type and UI is very slow. Wtf ? 
What kind of gesture did you write?

**Comment by userbq201** [comment]
I'm thinking of writing my ui

**Comment by ahartzog** [comment]
Android presumably?

This is an issue in react native that is fixed in 0.56

But windows dev is broken in 0.56

Good luck!

**Comment by userbq201** [comment]
@ahartzog 0.56 ? What is problem ?

**Comment by userbq201** [comment]
@ahartzog  this ? [link](https://github.com/facebook/react-native/commit/1b4187fc414352cd3724e2d4df2009f5a045fe3f)

**Comment by ahartzog** [comment]
Yes that. But 0.56 has a regression where if you're doing development on a windows environment you can't do anything right now, so I'm just warning you of that.

**Comment by userbq201** [comment]
@ahartzog  How to be in 0,55?

**Comment by userbq201** [comment]
upgrade ?

**Comment by userbq201** [comment]
@ahartzog  [analogue chat](https://snack.expo.io/ByptnEUmQ?session_id=snack-session-Hkf-eIU7Q)

**Comment by userbq201** [comment]
i remove composer and keyboard has become normal

**Comment by bilalsyed001** [comment]
https://github.com/facebook/react-native/issues/20119

**Comment by userbq201** [comment]
@bilalsyed001 With simple input all right. In this chat lots of odd code, props and etc.

**Comment by shaheem-khanzada** [comment]
@userbq201 remove all console before making a release build and then check

**Comment by userbq201** [comment]
@shaheem-khanzada thereis already

**Comment by richeterre** [comment]
Based on the reactions, I expected this change to fix the issue, but instead it turned out that the input field would no longer get cleared after submitting a message. Did anyone else have this experience?

**Comment by chris-divvito** [comment]
@richeterre - You're correct, if you are doing this you'll need another way to reset the text input.

For us, we add to the `textInputProps` the following:  `ref: textInput => this.textInput = textInput,`
then in the `onSend` handler we do `if (this.textInput) this.textInput.setNativeProps({text:''});`

That said, this is hanging around from an earlier time and I know that these days it's better to set up refs using forwardRefs, so you might want to look them up and implement it that way instead.

**Comment by neel132** [comment]
@batuhansahan your solution works like a charm... Thanks :)
But In android how it is possible to set a default value of TextInput as it is initialized to null ?

**Comment by faustoct** [comment]
any idea when will release it?
