### ISSUE TITLE
[performance] too slow when keyboard open and close 

### ISSUE THREAD

**Issue by shaheem-khanzada** [FaridSafi/react-native-gifted-chat#927]
![video-1531510785](https://user-images.githubusercontent.com/37620819/42723230-941dce7c-8773-11e8-9742-a920a505aaf2.gif)

**Comment by shaheem-khanzada** [comment]
solved my removing all console in release build

**Comment by oxy88** [comment]
can u explain more?

**Comment by ClickMakers** [comment]
can you explain how can we fix it?

**Comment by shaheem-khanzada** [comment]
@oxy88 @ClickMakers just remove all console.log statements from code and make a release build to test
