### ISSUE TITLE
Is there a possible way to load all components before navigation transition?

### ISSUE THREAD

**Issue by leonyhenn** [FaridSafi/react-native-gifted-chat#928]
#### Issue Description
I am using react-native with react navigation, and I am trying to avoid the slow initialization as mentioned here https://github.com/FaridSafi/react-native-gifted-chat/issues/606 https://github.com/FaridSafi/react-native-gifted-chat/issues/228  https://github.com/FaridSafi/react-native-gifted-chat/issues/473 , but unfortunately there is no luck. So i am trying to find a workaround to avoid buggy user experience, one that I found was used by WeChat. 

![giphy](https://user-images.githubusercontent.com/16746119/42805761-addb82e2-897a-11e8-9268-7e3868b0a62f.gif)

notice: 1st, 3rd and 4th window(by the order of being clicked) all has chat record, so they load slow. But 2nd window(the one with green thumbnail) do not have any chat content in there, so it load fast.

And all new windows are not being navigated to until they are fully loaded. In WeChat there is no waiting like in  https://github.com/FaridSafi/react-native-gifted-chat/issues/606

I am wondering if it is possible that after all custom component are loaded(I find GiftedChat itself finishes loading before custom components), gifted chat gives a call back to componentDidMount so that react navigation can start transition animation by then.

#### Steps to Reproduce / Code Snippets
 https://github.com/FaridSafi/react-native-gifted-chat/issues/606
#### Expected Results

like in the gif, navigation transition start until all component in chat page are loaded

#### Additional Information

* Nodejs version: I use expo, sdk28
* React version: 16.3.1
* React Native version: expo sdk28 --> RN 0.54
* react-native-gifted-chat version: "^0.4.3"
* Platform(s) (iOS, Android, or both?):ios, haven't tried Android yet
#606 @FaridSafi @vgorte @brunocascio 

On ios simulator there is no such issue all things are nice and smooth, but on ios phone it will delay on navigation for sure.

**Comment by gmmp** [comment]
react: 16.2.0"
react-native: 0.52.2
i got the similar issue on ios device.when i navigate to the gifted-chat page at the first time after app opened, it stuck around 4 seconds. not issue on ios simulator and android deivce.

**Comment by gmmp** [comment]
page A: with button A (navigate to gifted-chat).
when i prees button A at the first time,it stuck at page A around 4 seconds.
