### ISSUE TITLE
Hello, I used Microsoft Bot Framework & direct line Js with Gifted chat. But I am receiving  echo response from microsoft bot. Please see my code and let me know how to remove the echo part

### ISSUE THREAD

**Issue by kiranchaitanya22** [FaridSafi/react-native-gifted-chat#930]
#### Issue Description

Hello, I used Microsoft Bot Framework & direct line Js with Gifted chat. But I am receiving echo response from Microsoft bot. Please see my code and let me know how to remove the echo part

#### Steps to Reproduce / Code Snippets

import React, { Component } from 'react'
import { StyleSheet, View } from 'react-native'
import { GiftedChat } from 'react-native-gifted-chat'
import { DirectLine } from 'botframework-directlinejs'

import PrimaryBackground from '../../../../components/PrimaryBackground'
import bg_one from '../../../../assets/images/bg_one.png'

const directLine = new DirectLine({
  secret: '' // TODO: Pull this out of the code into a .env variable
})
const botMessageToGiftedMessage = botMessage => ({
  ...botMessage,
  _id: botMessage.id,
  createdAt: botMessage.timestamp,
  user: {
    _id: 2,
    name: 'kiran',
    avatar:
      'https://vignette.wikia.nocookie.net/mycun-the-movie/images/c/c9/Despicable-Me-2-Minion-names-and-picture-Tom.jpg/revision/latest?cb=20150714154704'
  }
})
function giftedMessageToBotMessage(message) {
  return {  
    from: { id: 1, name: 'Kiran C' },
    type: 'message',
    text: message.text
  }
}
export default class Example extends React.Component {
  state = {
    messages: []
  }
  constructor(props) {
    super(props)
    directLine.activity$.subscribe(botMessage => {
      console.log('botMessage', botMessage)
      const newMessage = botMessageToGiftedMessage(botMessage)
      this.setState({ messages: [newMessage, ...this.state.messages] })
    })
  } 
  onSend = messages => {
    this.setState({ messages: [...messages, ...this.state.messages] })
    messages.forEach(message => {
      directLine
        .postActivity(giftedMessageToBotMessage(message))
        .subscribe(() => console.log('success'), () => console.log('failed'))
    })
  }
  render() {
    
    return (
      <View style={styles.container}>
        <PrimaryBackground source={bg_one} />
        <GiftedChat
          
          placeholder={'Hello Kiran! Please type the message'}
          user={{ _id: 1 }}
          messages={this.state.messages}
          onSend={this.onSend}
        />
      </View>
      
    )
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1
  }
})

#### Expected Results
<img width="358" alt="screen shot 2018-07-18 at 1 31 01 pm" src="https://user-images.githubusercontent.com/25836488/42906124-ff028764-8a8e-11e8-88a6-66f34a67b81f.png">

#### Actual Result

<img width="355" alt="screen shot 2018-07-18 at 1 31 47 pm" src="https://user-images.githubusercontent.com/25836488/42906155-1b45497a-8a8f-11e8-8e11-b84d9b4dfc34.png">

**Comment by MicrosoftCSA** [comment]
I saw this issue. Setting the below property to false solved the issue.

alwaysShowSend (Bool) - Always show send button in input text composer; default false, show only when text input is not empty.

**Comment by ICJames** [comment]
I am also getting the same issue. I am using pretty much the same code as  @kiranchaitanya22 . I changed the following as per @MicrosoftCSA suggestion but the message still gets echoed in the response :-(

`<GiftedChat`
                    `alwaysShowSend={false}`
                    `placeholder={'Hello Kiran! Please type the message'}`
                    `user={{ _id: 1 }}`
                    `messages={this.state.messages}`
                    `onSend={this.onSend}`
`/>`

Any help would be awesome, thanks :-)

**Comment by MicrosoftCSA** [comment]
Oops. My last solution wasn't solution sorry, that was another issue to do with showing the send button on Android.


The solution for the duplicate messages was:

Add a property sentMessage to state:

state = {
    messages: [],
    sentMessage: null
};

For every message sent in onSend log the message sent in state:

messages.forEach(message => {
    this.setState({sentMessage: message.text});

    directLine
        .postActivity(giftedMessageToBotMessage(message))
        .subscribe(() => console.log("success"), () => console.log("failed"));
});

Finally when the choosing what is written back out by the bot, do not write the message if we sent it:

if(botMessage.text === this.state.sentMessage) {
    return;
}

Hopefully this solves your issue.
