### ISSUE TITLE
Can you nest this component in views?

### ISSUE THREAD

**Issue by chriswill21** [FaridSafi/react-native-gifted-chat#936]
Is it possible to put this component into a view and then make that view one of many nested views in a root component? The idea is that you have this chat in the bottom of the page, and something else above it earlier in the page.

**Comment by pavlea** [comment]
Yes you can, just need to set container view `flex: 1` or width and height to 100% or some other percentage.

**Comment by jatarga** [comment]
According to my limited tests, no you **can't**.
