### ISSUE TITLE
Need to auto-scroll to a particular message of a chat conversation

### ISSUE THREAD

**Issue by Thyix** [FaridSafi/react-native-gifted-chat#938]
Good afternoon,

I have a chat messages thread and I want to scroll to a particular message by it's Id. I have searched and haven't found anything so far.

e.g. : I have a 'message search' scene in my application. When you enter something in the search bar, every messages from every contacts are fetched and I display only some that corresponds with the entry.  

When I click on a particular message of a particular contact, I navigate to this contact chat conversation. 

The only thing I need is scrolling to that particular message. I know every message have an Id, that's why I wanted to know if there's a method to move directly to a specific message by providing the chat Id.

Hope you can help me with this 👍

#### Additional Information

* Nodejs version: v8.9.4
* React version: 16.2.0
* React Native version: 0.55.4
* react-native-gifted-chat version: 0.4.3
* Platform(s) (IOS&Android): (IOS v11.2, Android v6.0)

**Comment by leron8** [comment]
I will also be looking forward to having this feature. I see that gifted chat uses RN's FlatList (https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/MessageContainer.js) so this could be used https://facebook.github.io/react-native/docs/virtualizedlist.html#scrolltooffset Which I see they have that function in Gifted chat also:

scrollTo(options) {
    if (this.flatListRef) {
      this.flatListRef.scrollToOffset(options);
    }
  }

I haven't been able to dig in more to see how to implement it though. I hope it helps in some way!

**Comment by alexvaltin97** [comment]
Also looking for it

**Comment by flashimxd** [comment]
I'm looking for something similar...
Let me know if you guys figure out how to do that.

**Comment by maulikdhameliya** [comment]
@leron8 : created this scrolling functionality ?

**Comment by leron8** [comment]
Hello @maulikdhameliya I haven't implemented it. Been busy. I believe @Thyix might have worked on a PR, but not sure though.

**Comment by Thyix** [comment]
Didn't find anything yet, sadly :(

**Comment by testshallpasswork** [comment]
Technically, as alluded gifted chat uses Flatlist internally and it could be that you can use [scrollToIndex](https://facebook.github.io/react-native/docs/flatlist#scrolltoindex) but as documentation states it depends on [getItemLayout](https://facebook.github.io/react-native/docs/flatlist#getitemlayout) and that depends on giving Flatlist heights to the items upfront. 
@leron8 Your PR would be able to calculate variable item heights?

**Comment by leron8** [comment]
Hey @testshallpasswork I can't work on PR right now. @Thyix was but he says he hasn't found anything yet :'(

**Comment by anhtukhtn** [comment]
I'm waiting for this also. Hope.

**Comment by anhtukhtn** [comment]
I finally did it by myself with v0.4.3.
The idea is:
1. Get ref of the list view `chatListView`.
2. Get position of the message view. Because in v0.4.3, Gifted chat using `InvertibleScrollView`. So I have to using `onLayout` of the `view` in `InvertibleScrollView`. Then I store them in a stored dictionary.

==> Scroll to message: Get position (`messageViewY`) of message view from the stored dictionary. Then: 
```
let scrollY = messageViewY - this.chatListView.scrollProperties.visibleLength;
this.chatListView.scrollTo({ x: 0, y: scrollY, animated: true });
```

**Comment by SrWildman** [comment]
@anhtukhtn can you please provide a little more detail on this? I have my reference to gifted chat but am a little confused after that.

**Comment by anhtukhtn** [comment]
I did it with v0.4.3 ,when gifted-chat used `InvertibleScrollView`. It uses `FlatList` in v0.5 now.
So my solution maybe not work anymore.

If you still use v0.4.3. You can see more detail from forked repo 
https://github.com/anhtukhtn/react-native-gifted-chat/commit/8408a24f41fd8f2c14902c9681094c375919821b
https://github.com/anhtukhtn/react-native-invertible-scroll-view/commit/fa7ee55ffcb08809b9a32e34510ab4ff56c5b419

**Comment by parthya** [comment]
This was simpler than I thought. I have created a PR https://github.com/FaridSafi/react-native-gifted-chat/pull/1157

@Thyix Can you check if it works for you, if you haven't found a solution already.

**Comment by infaz** [comment]
> I finally did it by myself with v0.4.3.
> The idea is:
> 
> 1. Get ref of the list view `chatListView`.
> 2. Get position of the message views. Because in v0.4.3, gifted-chat using `InvertibleScrollView`. So I have to using a callback from `onLayout` of the `View` in `InvertibleScrollView`. Then I store them in a stored dictionary.
> 
> ==> Scroll to message: Get position (`messageViewY`) of message view from the stored dictionary. Then:
> 
> ```
> let scrollY = messageViewY - this.chatListView.scrollProperties.visibleLength;
> this.chatListView.scrollTo({ x: 0, y: scrollY, animated: true });
> ```

It says scrollTo in not a function. Any idea what might the reason?

**Comment by anhtukhtn** [comment]
@infaz Did you link it with `ListView` ref? I did it with v0.4.3. 
At the current version >v0.6, `GiftedChat` changed the container to `FlatList`.

**Comment by LuckyShine001** [comment]
I want a scenario that on particular condition the chat should not scroll to the bottom(latest message), unless user manually scroll it. 
can we achieve it with updated gifted-chat version?

**Comment by JonnyBurger** [comment]
My strategy:

- Store in redux or in a state the message that you would like to focus
- Pass each message row a field `focusedMessage={}`
- do a check in the component, if `props.focusedMessage === this.props.message` then `ref.measure`, then `props.scrollToOffset`

- In the GiftedChat component, in the renderMessage section:

```jsx
shouldScrollTo={(offset: number) => {
	ref.current._messageContainerRef.current.scrollToOffset({
		offset: scrollViewHeight - offset // for inverted
	});
}}
```

**Comment by romanmashkovskiy** [comment]
@JonnyBurger 
As I understood you do it this way:
`<GiftedChat
          .........
          renderMessage={this.renderMessage}
          ref={this.chatListRef}
          shouldScrollTo={(offset) => {
            this.chatListRef.current._messageContainerRef.current.scrollToOffset({
              offset: scrollViewHeight - offset
            });
          }}
          focusedMessage={focusedMessage}
        />`
Could you please explain how to calculate offset and scrollViewHeight?
And 
`  renderMessage(props) {
    if (props.focusedMessage && props.currentMessage._id === props.focusedMessage.id) {
      props.shouldScrollTo(.....)
    }
    return <Message text={props.currentMessage.text}/>;
  }`

**Comment by JonnyBurger** [comment]
@romanmashkovskiy By `scrollViewHeight` I meant scroll view position, sorry. It can be calculated by listening to `onScroll` event of the ScrollView. The `offset` is already given in the callback, it doesn't need to be calculated.

**Comment by romanmashkovskiy** [comment]
@JonnyBurger As I understood I should call shouldScrollTo in my renderMessage if current message is equal to focused. Correct?

**Comment by JonnyBurger** [comment]
Yes, in my chat message view I have the following:

```
	componentDidUpdate(prevProps) {
		if (
			this.props.currentMessage?._id === this.props.scrollToMessage &&
			!prevProps.scrollToMessage
		) {
			this.ref.current?.measure((fx, fy, width, height, px, py) => {
				this.props.shouldScrollTo(py);
				Animated.timing(this.animatedValue, {
					toValue: 100,
					duration: 200
				}).start();
			});
		}
		if (
			prevProps.currentMessage._id === prevProps.scrollToMessage &&
			!this.props.scrollToMessage
		) {
			Animated.timing(this.animatedValue, {
				toValue: 0,
				duration: 1000
			}).start();
		}
	}
```

**Comment by romanmashkovskiy** [comment]
@JonnyBurger I added ref to my GiftedChat component `<GiftedChat ref={this.chatListRef} />`. But this.chatListRef.measure is not a function

**Comment by JonnyBurger** [comment]
Add the ref to each message. Also it might be `ref.current.measure`.

**Comment by 4RGUS** [comment]
> Add the ref to each message. Also it might be `ref.current.measure`.

I couldn't find measure inside ref._message._messageContainerRef.current or ref.current.measure. Did any one get the exact location of this.

**Comment by darron1217** [comment]
@4RGUS 
I solved it by calling FlatList's `scrollToIndex`
```
      giftedChatRef.current?._messageContainerRef?.current?.scrollToIndex({
        animated: true,
        index: 5,
      });
```

**Comment by Haseebshah936** [comment]
@darron1217 Can you share the code for this as I am still facing the same issue. Here is my code actually I am implementing this right now. If you can point out the issue it would be better. Thanks


    
    import { Button, StyleSheet, Text, View } from "react-native";
    import React, { useState, useCallback, useEffect, useRef } from "react";
    import { GiftedChat } from "react-native-gifted-chat";
    
    const Chat = () => {
      const [messages, setMessages] = useState([]);
      const chatRef = useRef();
    
      const scrollToMessage = (messageId) => {
        // Find the index of the message with the given id
        const index = messages.findIndex((message) => message._id === messageId);
    
        if (index !== -1) {
          chatRef?.current?._messageContainerRef?.current?.scrollToIndex({
            animated: true,
            index,
          });
        }
      };
    
      const onSend = useCallback((messages = []) => {
        setMessages((previousMessages) =>
          GiftedChat.append(previousMessages, messages)
        );
      }, []);
    
      useEffect(() => {
        setMessages([
          {
            _id: 1,
            text: "Hello developer",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=frx37t2e",
            },
          },
          {
            _id: 2,
            text: "Hello developer",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=ygwv82z2",
            },
          },
          {
            _id: 3,
            text: "Hello developer",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=046hexjr",
            },
          },
          {
            _id: 4,
            text: "Hello developer",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=xpa7if4h",
            },
          },
          {
            _id: 5,
            text: "Hello developer",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=nnpomnq6",
            },
          },
          {
            _id: 6,
            text: "Hello developer",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=4zkvkqdw",
            },
          },
          {
            _id: 7,
            text: "Hello developer",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=o6xyponw",
            },
          },
          {
            _id: 8,
            text: "Hello developer",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=0z9knn1c",
            },
          },
          {
            _id: 9,
            text: "Hello developer",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=6zpig8jj",
            },
          },
          {
            _id: 10,
            text: "Hello developer",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=n9p2srox",
            },
          },
          {
            _id: 11,
            text: "Hello developer",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=wtbwokzl",
            },
          },
          {
            _id: 12,
            text: "Hello developer",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=mp8jrixk",
            },
          },
          {
            _id: 13,
            text: "Hello developer",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=b389yyjp",
            },
          },
          {
            _id: 14,
            text: "Hello developer",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=hn6i6cif",
            },
          },
          {
            _id: 15,
            text: "Hello developer",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=44yqkzdi",
            },
          },
          {
            _id: 16,
            text: "Hello developer",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=rwiu9qe7",
            },
          },
          {
            _id: 17,
            text: "Hello developer1",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=8ulzt9ea",
            },
          },
          {
            _id: 18,
            text: "Hello developer1",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=8ulzt9ea",
            },
          },
          {
            _id: 19,
            text: "Hello developer1",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=8ulzt9ea",
            },
          },
          {
            _id: 20,
            text: "Hello developer1",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=8ulzt9ea",
            },
          },
          {
            _id: 21,
            text: "Hello developer1",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=8ulzt9ea",
            },
          },
          {
            _id: 22,
            text: "Hello developer1",
            createdAt: new Date(),
            user: {
              _id: 2,
              name: "React Native",
              avatar: "https://api.lorem.space/image/face?w=40&h=40&hash=8ulzt9ea",
            },
          },
        ]);
      }, []);
      return (
        <View style={{ flex: 1 }}>
          <GiftedChat
            messages={messages}
            onSend={(messages) => onSend(messages)}
            user={{ _id: 1 }}
            //   renderSend={(props) => <CustomSend {...props} />}
            scrollToBottom={true}
            ref={this.chatRef}
          />
          <Button title="Scroll" onPress={() => scrollToMessage(22)} />
        </View>
      );
    };
    
    export default Chat;

**Comment by sreerajzion** [comment]
GiftedChat not support ref now
