### ISSUE TITLE
How to add another TextInput and Button under Message Input

### ISSUE THREAD

**Issue by dantn93** [FaridSafi/react-native-gifted-chat#939]
#### Issue Description
I use KeyboardAvoidingView tag under the Gifted Chat. In the KeyboardAvoidingView, I add my TextInput. When I focus on my TextInput, it has a big space between Gifted Chat and my TextInput.

#### Steps to Reproduce / Code Snippets

<View style={styles.container}>
    <GiftedChat
        messages={this.state.messages}
        onSend={messages => this.onSend(messages)}
        user={{
          _id: this.state.username
        }}
    />
    <KeyboardAvoidingView
        behavior="padding"
    >
        <TextInput
        style={{height: 35, width: 300, backgroundColor: 'white', borderRadius: 5, justifyContent: 'center', paddingLeft: 5,}}
        />
        </KeyboardAvoidingView>
</View>

#### Expected Results
I expect that it has no space between GiftedChat and my TextInput

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: 16.4.1
* React Native version: 0.56.0
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by BLOCKMATERIAL** [comment]
Up
