### ISSUE TITLE
Can't input Chinese PinYin

### ISSUE THREAD

**Issue by cuiying408** [FaridSafi/react-native-gifted-chat#944]
Hi,

I am developing chat application and was going to use this source. But couldn't input Chinese PinYin. 
Any solution?

Regards,

#### Additional Information

* Nodejs version: 8.9.1
* React version: 16.3.1
* React Native version: 0.55.4
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): iOS v11

**Comment by Jeremy-JM** [comment]
I also have this problem:
React version: ^16.3.0-alpha.1
React Native version: 0.54.4
react-native-gifted-chat version: 0.4.3
Platform: only iOS All version.

Do you have resolve this issue?
@cuiying408
