### ISSUE TITLE
Issue sending consecutive messages

### ISSUE THREAD

**Issue by justinhartson1** [FaridSafi/react-native-gifted-chat#945]
#### Issue Description

I wonder if you can help me?  

I am working on an application which was developed by a developer who is no longer in business.  He integrated your React-Native-Gifted-Chat package in the application and it is working really well with Push Notifications when single messages/chats are exchanged between the sender and receiver.  The problem occurs when a sender sends two messages, one after the other, and the receiver clicks on the second Push Notification.  This opens the messaging app, but the message is not displayed, however, if the recipient sends a reply, the screen changes and the full and complete  message thread is visible. If the exercise is repeated it appears that the full message screen is regenerated, so that you have to close the message thread screen  down several times to get back to the original messages list screen.

Have you any idea where the problem may lie please? Thanks in advance for your help

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT] - Send two message one after the other and open the second push notification

#### Expected Results

[Any advice ]

#### Additional Information

* Nodejs version: [FILL THIS OUT]  -     8.5
* React version: [FILL THIS OUT]     -    16.0
* React Native version: [FILL THIS OUT]     -    0.43  
* react-native-gifted-chat version: [FILL THIS OUT]   -    0.1.5
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]   -   iOs and Android

**Comment by wentingxi** [comment]
+1
