### ISSUE TITLE
Why is returning an empty view if the message array is empty?

### ISSUE THREAD

**Issue by emilkarl** [FaridSafi/react-native-gifted-chat#947]
Why is this done instead of implementing `ListEmptyComponent` on the `FlatList`? Any special reason for it? 

```javascript
render() {
    if (this.props.messages.length === 0) {
      return <View style={styles.container} />;
    }
//...
```

RN docs: https://facebook.github.io/react-native/docs/flatlist#listemptycomponent
https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/MessageContainer.js#L121

**Comment by MingFaiYau** [comment]
i think is because this way is easier to handle.
But if you set refresh or load more function in the List, this coding seems cant do that.

**Comment by gsdatta** [comment]
Reopening this - this seems really bad and isn't documented. Breaks the fact that this is just a listview.
