### ISSUE TITLE
Bad scrolling with Android Pie 9 and Pixel 2 XL

### ISSUE THREAD

**Issue by zupodaniel** [FaridSafi/react-native-gifted-chat#951]
#### Issue Description

When scrolling enters in the "momentum" phase (after releasing finger) the chat view starts to scroll in the opposite direction

#### Steps to Reproduce / Code Snippets

Just scrolls the chat view using fast finger swipe

#### Additional Information

* React Native version: 0.55.0
* react-native-gifted-chat version: 0.4.3
* Platform(s): Android 9

**Comment by gusgoose** [comment]
Yes, I have noticed this too. Interestingly, though, I have noticed precisely the same problem with Airbnb's chat in their app. I suppose it's unlikely they use gifted chat in their app, but there's a good chance that bit is built in react native... So perhaps something to do with a particular implementation of listview?

**Comment by zupodaniel** [comment]
It's possible to be related to react-native-invertible-scroll-view. As soon as possible I'll create an issue there.

**Comment by dolphinflow86** [comment]
+1

**Comment by rsmelo92** [comment]
+1 (pixel 1 android 9)

**Comment by ggsrivas** [comment]
did anyone find any workaround for this? React native ticket has few workarounds but that requires modifying the react-native code and then building and generating the .aar file. Does anyone have any other suggestion?

**Comment by mandrigin** [comment]
@ggsrivas it's an issue in scrollviews in Android 9, they break momentum when you apply negative scaling to them (that exactly what scroll view inversion does in RN). 
So the options that I see are:
- not using inverted scrollviews and inverting the data instead
- bundling your own scrollview implementation for Android (as a native module, maybe it is possible to inherit the scrollview and override `fling` method.

**Comment by ramon90** [comment]
I am having the same issue it is not fixed in rn v0.57.7

**Comment by erez-guesty** [comment]
any update?

**Comment by rsmelo92** [comment]
Apparently fixed on new release 0.58 https://github.com/facebook/react-native/commit/b971c5b

**Comment by MamyChow** [comment]
Add inverted={false} in props solve my problem
