### ISSUE TITLE
GiftedChat doesn't allow enter message in the input field after sending the first one.

### ISSUE THREAD

**Issue by khuongdv** [FaridSafi/react-native-gifted-chat#952]
#### Issue Description

GiftedChat doesn't allow enter message in the input field after sending the first one.

#### Steps to Reproduce / Code Snippets

This is my code:

```
<GiftedChat
                  alwaysShowSend
                  textInputProps={{style: {fontSize:11, fontFamily: AppContext.FONT.MAIN_FONT, width: '80%'}}}
                  onInputTextChanged={(para) => {
                    console.log('onInputTextChanged', para)
                  }}
                  maxInputLength={1000}
                  messages={this.state.messages}
                  onSend={(messages = []) => {
                    console.log('ETNER MESSAGE', messages)
                    this.setState(previousState => ({
                      messages: GiftedChat.append(previousState.messages, messages),
                    }), () => {
                      if (!this.firestoreRefChat || messages.length === 0) {
                        return
                      }
                      const msg = messages[0]
                      this.firestoreRefChat.doc(uuidv4()).set(msg)
                    })
                  }}
                  user={{
                    _id: this.props.currentUser.email,
                    avatar: this.props.currentUser.avatar,
                    name: this.props.currentUser.name,
                  }}
                />
```
This way, GiftedChat show all message in Firebase. But if I enter text message manually, it accept only one time. After sending the first message, GiftedChat don't allow me to input next message (tried to type in but no text display)

Another point is, even `alwaysShowSend` is enabled but SEND button is not always dislayed.

<img width="504" alt="screen shot 2018-08-23 at 1 55 22 pm" src="https://user-images.githubusercontent.com/7438397/44509607-627a5380-a6dc-11e8-8937-770bbcc655bd.png">

#### Expected Results

- Send button is always displayed

- I can type in message and send it multiple time. 

#### Additional Information

* Nodejs version: v9.6.1
* React version: 16.3.1
* React Native version: 0.55.1
* react-native-gifted-chat version: ^0.4.3
* Platform(s) (iOS, Android, or both?): Android

**Comment by dengue8830** [comment]
same here, i have to wait 4 seconds in order to see the text displayed in the input text

steps:
write something > send > keep writting > `nothing shows in the input text` > keep writing > `after 4 seconds` > text shows in input text

env info
```
Binaries:
      Node: 8.11.3 - /usr/bin/node
      npm: 6.4.1 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 7, 8
        Build Tools: 19.0.0, 19.1.0, 20.0.0, 21.1.1, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-14 | ARM EABI v7a, android-16 | ARM EABI v7a, android-21 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-asset: 1.1.2
      react-native-cli: 2.0.1
```

**Comment by dengue8830** [comment]
i fixed changing GiftedChat.js#351 from 100 mills to 0

```diff
setTimeout(() => {
        if (this.getIsMounted() === true) {
          this.setIsTypingDisabled(false);
        }
-      }, 100);
+      }, 0);
```

**Comment by dengue8830** [comment]
it was a debugger problem, fixed stopping remote debugging option -.-
