### ISSUE TITLE
MessageText limit number of lines

### ISSUE THREAD

**Issue by SimonBao** [FaridSafi/react-native-gifted-chat#956]
#### Issue Description

I want to limit the message text to only render maximum two lines of text, anything larger results in ellipsis.

Is there something like ```<Text numberOfLines={2}>...</Text>``` for react-native-gifted-chat MessageText?

#### Code Snippets
```
          <MessageText
            {...messageTextProps}
            textStyle={textStyle}
            customTextStyle={styles[this.props.position].quotedMessageStyle}
            currentMessage={quotedMessage.text ? quotedMessage : cameraImage}
          />
```

* React Native version: 0.56
* react-native-gifted-chat version: 0.4.3
* Platform: Android and IOS

**Comment by yosukapro** [comment]
Any solution?
