### ISSUE TITLE
Pattern for removing temporary messages once app receives response from server

### ISSUE THREAD

**Issue by waltermvp** [FaridSafi/react-native-gifted-chat#957]
Hello, first of all thank your for this great lib. 
I have a question on what pattern makes sense to maintain temporary messages state. Given that a temporary message is added to the `messages` prop the moment the user hits the send button  but **before the response is returned** to the app there is no way to generate a matching ID locally (the server will return with its own messageID). What patterns are recommended to remove the temporary message?

### Approach 1 match message text value

Off the top of my head I thought of matching the actual message text in order to remove the temporary message (once the response is received), but that does not feel right. 

### Approach 2 replace entire messages array with response

Replacing the entire messages array with what is returned from the network also does not take into account if the request failed

**Comment by waltermvp** [comment]
@FaridSafi shameless ask for help :)

**Comment by shaheem-khanzada** [comment]
@waltermvp use renderFooter(){} to show local message in a list , when u press send button u get a local message from props save that message in a state and then use condition  
 ` <giftedChat>
        {...props}
    renderFooter={this.state.localMessage.length > 0 ? this.renderFooter() : null} 
   </giftedChat>}`

**Comment by shaheem-khanzada** [comment]
@waltermvp make sure when u receive mesage from server u also have to empty the state like this.setState({localMessage: [] })

**Comment by waltermvp** [comment]
@shaheem-khanzada  exactly the direction I was looking for thank you. Will respond in a week or so once i have actually implemented your suggestion. Once again thanks.

**Comment by shaheem-khanzada** [comment]
@waltermvp no problem let me know if u need more help

**Comment by nandiniparimi1107** [comment]
@shaheem-khanzada Do you have a working example for renderFooter ?

Apparently, renderFooter does not get triggered on state change, I have been struggling with this for a week now.
Here is the code : 
```
 componentDidMount() {
    autorun(() => {
      this.setState({
        isTyping: true or false (depending on your condition),
      });
    });
  }
renderFooter = () => {
      if (this.state.isTyping) {
        if (this.typingTimeoutTimer == null) {
          this.startTimer();
        }
        return <TypingIndicator />;
      } 
    return null;
  };


 render() {
    return (
      <GiftedChat
        messages={this.giftedChatMessages}
        onSend={this.onSend}
        renderAvatar={null}
        renderFooter={this.renderFooter}
        user={{
          _id: someid,
        }}
        imageStyle={{}}
      />
    );
  } 
```

**Comment by deepak-jha-kgp** [comment]
@nandiniparimi1107  you need to pass this.isTyping as extraData in giftedChat
