### ISSUE TITLE
White space above inputToolBar in IOS

### ISSUE THREAD

**Issue by redmond-ingenuity** [FaridSafi/react-native-gifted-chat#959]
#### Issue Description
Theres a white space above inputToolBar in IOS when keyboard goes up. but not in android
![image](https://user-images.githubusercontent.com/35834310/45018451-b847e780-b05c-11e8-9643-dde75d5db9c6.png)

* Nodejs version: v8.3.0
* React Native version: 0.55.4
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): IOS

**Comment by ivukusic** [comment]
@redmond-ingenuity it is an old issue, but did you resolve it and how?
