### ISSUE TITLE
Gifted chat show tab bar when user typing

### ISSUE THREAD

**Issue by Webdev55486** [FaridSafi/react-native-gifted-chat#963]
#### Issue Description
I am using gifted chat for my chat view.
on ios it's working perfectly.
Problem was in Android, 
When user typing need to hide Tab bar.
below Image: 

![image](https://user-images.githubusercontent.com/28510084/45195578-e6ab0a00-b28a-11e8-91b1-62f7adc77dee.png)

for that Tabvar, I am using react-native-navigation

I need to result like below

![image](https://user-images.githubusercontent.com/28510084/45195653-3984c180-b28b-11e8-9fb6-db6ba9108510.png)

Please help me

* Nodejs version: v10.9.0
* React version: 16.2.0
* React Native version: ^0.55.4
* react-native-gifted-chat version: ^0.3.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by AdamLee321** [comment]
Did you manage to fix this as I have the exact same issue.
