### ISSUE TITLE
undefined is not an object (evaluating '_react3.default.PropTypes.string')

### ISSUE THREAD

**Issue by Chinezefitzge** [FaridSafi/react-native-gifted-chat#966]
![screenshot_20180907-103352](https://user-images.githubusercontent.com/43063849/45212786-b1ec8200-b28d-11e8-9c69-2b182b8b3505.png)
//This is for the home.js file
import React from "react";
import {
  View,
  Text,
  StyleSheet,
  TextInput,
  TouchableOpacity
} from "react-native";
import { Actions } from "react-native-router-flux";

class Home extends React.Component {
  state = {
    name: ""
  };
  render() {
    return (
      <View>
        <Text style={styles.title}>Enter your name:</Text>
        <TextInput
          underlineColorAndroid="transparent"
          style={styles.nameInput}
          placeholder="Gerald"
          onChangeText={text => {
            this.setState({
              name: text
            });
          }}
          value={this.state.name}
        />
        <TouchableOpacity
          onPress={() => {
            //navigating to the next page
            Actions.chat({
              name: this.state.name
            });
          }}
        >
          <Text style={styles.buttonText}>Next</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

var styles = StyleSheet.create({
  title: {
    marginTop: 20,
    marginLeft: 20,
    fontSize: 20
  },
  nameInput: {
    height: 40,
    borderWidth: 2,
    borderColor: "black",
    margin: 20,
    padding: 5
  },
  buttonText: {
    marginLeft: 20,
    fontSize: 20
  }
});

export default Home;

//for the chat.js file
import React from "react";
import { GiftedChat } from "react-native-gifted-chat";
import PropTypes from "prop-types";

class Chat extends React.Component {
  state = {
    messages: []
  };
  render() {
    return (
      <GiftedChat
        messages={this.state.messages}
        onSend={message => {
          //backend message
        }}
        user={{
          _id: 1
        }}
      />
    );
  }
}

//am having error here.
Chat.defaultProps = {
  name: "Gerald"
};
Chat.propTypes = {
  name: React.PropTypes.string
};

export default Chat;

* Nodejs version: [8.11.3]
* React version: [16.3.1]
* React Native version: [0.55.2]
* react-native-gifted-chat version: [0.4.3]
* Platform(s) Android

**Comment by sibelius** [comment]
```
React.PropTypes.string
```

does not work anymore,

not a problem with this package
