### ISSUE TITLE
Help with GiftedAvatar component

### ISSUE THREAD

**Issue by yasso1am** [FaridSafi/react-native-gifted-chat#967]
#### Issue Description

I am not automatically getting user initials as their Avatar if no avatar is supplied.  I see there is a GiftedAvatar component in the src folder, however I don't know how to implement it, or what prop to pass to the GiftedChat component to get the avatar initials to display.  I'm not sure if this is a default feature that just isn't working properly, or if I've done something to override it.  Any help on getting this feature to work would be greatly appreciated.

#### Steps to Reproduce / Code Snippets

COMPONENT DID MOUNT (initializing my formatted comments)
```
  componentDidMount(){
    const { comments } = this.props.location.state
    let commentsArray = []
    for (let c of comments) {
      commentsArray.push({
        _id: c.id,
        text: c.content,
        createdAt: c.created_at,
        user: {
          _id: c.author.id,
          name: c.author.name,
          avatar: c.author.photo_url
        }
      })
    }
    this.setState({formattedComments: commentsArray})
  }

```
ON SEND
```
  onSend = (messages) => {
    let text = messages[0].text
    const { dispatch } = this.props
    const { skitId } = this.props.location.state
    let newMessage = {
      _id: messages[0]._id,
      text: messages[0].text,
      createdAt: new Date(),
      user: {
        _id: this.props.user.user.id,
        name: this.props.user.user.name,
        avatar: this.props.user.user.photo_url
      }
    }
    this.setState( previousState => ({
      formattedComments: GiftedChat.append(newMessage, previousState.formattedComments)
    }))
    dispatch(addComment(text, skitId))
  }
```
GIFTED CHAT COMPONENT
```
        <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
          <View style={{flex: 1}}>
            { formattedComments !== [] ?
            <GiftedChat
              placeholder="Add a comment..."
              // keyboardShouldPersistTaps={'handled'}
              showUserAvatar={true}
              messages={formattedComments}
              onSend={messages => this.onSend(messages) }
              user={{
                _id: this.props.user.user.id
              }}
            />
            :
            null
            }
          </View>
        </TouchableWithoutFeedback>
```

#### Expected Results

This is the current behavior

![screenshot 2018-09-07 12 52 21](https://user-images.githubusercontent.com/39067243/45240270-e582d880-b29c-11e8-966d-2787c4f9086c.png)

I would like users who don't have an avatar (for me it would be this.props.user.user.photo_url === "") to display with the GiftedAvatar component next to their name

<img width="290" alt="screenshot 2018-09-07 12 55 16" src="https://user-images.githubusercontent.com/39067243/45240398-6510a780-b29d-11e8-833a-670f45bb4891.png">

#### Additional Information

All of my testing is currently done via the simulator and latest version of XCode, Expo, iOS, Node, and React. I created this application six days ago.

**Comment by Abhishekgarg727** [comment]
@yasso1am  giftedChat is just UI library it does not provide user initial support, however you can achieve same effect using this 
API  `https://ui-avatars.com/api/?name=John+Doe`

read docs [here ](https://ui-avatars.com/)and it is open source .
