### ISSUE TITLE
_id to id?

### ISSUE THREAD

**Issue by cheuk3** [FaridSafi/react-native-gifted-chat#968]
is it possible to use "id" instead of "_id"?

**Comment by onusvishal** [comment]
same issue .

**Comment by sibelius** [comment]
not right now

**Comment by onusvishal** [comment]
use this design https://github.com/vshalvaghasiya/React-Native-FirebaseChat

**Comment by Faolain** [comment]
Thanks @onusvishal but I don't use Firebase so I'm not sure this can help unless I'm looking in the wrong place? Is there a particular place within this project that a mapping pattern is used?
