### ISSUE TITLE
Parsing HTML tags in bubbles

### ISSUE THREAD

**Issue by jbosnjakovic** [FaridSafi/react-native-gifted-chat#971]
Hello, 

I'm interested in showing HTML tags in bubbles. Is this even possible? 

Any advice and suggestions will be greatly appreciated. Thanks

![image](https://user-images.githubusercontent.com/22400536/45539196-4bc1ab00-b809-11e8-8662-86f0c823ee09.png)

**Comment by saggiyogesh** [comment]
Facing the same issue, Trying to fork and use `react-native-htmlview` module

**Comment by Brokray** [comment]
@jbosnjakovic and @saggiyogesh did any of you find a viable solution ?     
At the moment, I can easily parse the HTML **but** I can't keep the sweet ParsedText of MessageText.js which allow linkStyle for email, phone and such.

How is it going for you ?

**Comment by saggiyogesh** [comment]
Forked and implemented Html view to parse / show html in chat view 

https://github.com/saggiyogesh/react-native-gifted-chat

**Comment by Brokray** [comment]
Fair enough, thanks for your answer.     
Sadly I would like to keep `<ParsedText>` and make it work with `<HTMLView >`, however it feels like there is no easy way to do that at the moment.

**Comment by abhishek10ju** [comment]
I did try solutions with as suggested by  @saggiyogesh but that does not work if HTML has <table> tags. In fact tried to replace table tags with iframes in same solution. No luck so far.
Can it be implemented using CustomView implementation and engage WebView ?

**Comment by saggiyogesh** [comment]
@abhishek10ju 
Pls check whether your HTML is rendered correctly by `react-native-htmlview`. 
If yes, then only the above solution will work.

**Comment by abhishek10ju** [comment]
Thanks @saggiyogesh . As I mentioned, table tag is not being rendered with htmlview. Do you think that solution with CustomView (using WebView) implementation can work ? I tried but no success so far :(

   <GiftedChat
                 messages={this.state.messages}
                 showUserAvatar={true}
                 scrollToBottom={true}
                 renderFooter={this.renderFooter}
                 sendCommand={this.sendCommand}
                 renderCustomView={this.renderCustomView}
                 onSend={messages => this.onSend(messages)}
                 user={{
                   _id: 1
                 }}
               />

CustomView.js
----------------------
import PropTypes from 'prop-types';
import React from 'react';
import {
  View,
  Image,
  Linking,
  Platform,
  StyleSheet,
  TouchableOpacity,
  ViewPropTypes,
  WebView,
  Text
} from 'react-native';
//import WebView from 'react-native-webview';

export default class CustomView extends React.Component {


  renderHtml() {
    return (
        <WebView
        source={{html: this.props.currentMessage.text}}
        style={{flex: 1}} 
        />
    );
  }

  render() {
    if (this.props.currentMessage.contentType == 'html') {
      return this.renderHtml();
    }
    return null;
  }
}


const textStyle = {
  fontSize: 16,
  lineHeight: 20,
  marginTop: 5,
  marginBottom: 5,
  marginLeft: 10,
  marginRight: 10,
};

const styles = {
  left: StyleSheet.create({
    container: {flex: 1},
    text: {
      color: 'black',
      ...textStyle,
    },
    link: {
      color: 'black',
      textDecorationLine: 'underline',
    },
  }),
  right: StyleSheet.create({
    container: {},
    text: {
      color: 'white',
      ...textStyle,
    },
    link: {
      color: 'white',
      textDecorationLine: 'underline',
    },
  }),
};

CustomView.contextTypes = {
  actionSheet: PropTypes.func,
};

CustomView.defaultProps = {
  position: 'left',
  currentMessage: {
    text: '',
  },
  containerStyle: {},
  textStyle: {},
  linkStyle: {},
  customTextStyle: {},
  textProps: {},
  parsePatterns: () => [],
};

CustomView.propTypes = {
  position: PropTypes.oneOf(['left', 'right']),
  currentMessage: PropTypes.object,
  containerStyle: PropTypes.shape({
    left: ViewPropTypes.style,
    right: ViewPropTypes.style,
  }),
  textStyle: PropTypes.shape({
    left: Text.propTypes.style,
    right: Text.propTypes.style,
  }),
  linkStyle: PropTypes.shape({
    left: Text.propTypes.style,
    right: Text.propTypes.style,
  }),
  parsePatterns: PropTypes.func,
  textProps: PropTypes.object,
  customTextStyle: Text.propTypes.style,
};

**Comment by lewatt23** [comment]
@abhishek10ju  any solution so far? facing the same problem....
