### ISSUE TITLE
Dynamically hiding and showing InputToolbar causes white space sometimes.

### ISSUE THREAD

**Issue by watadarkstar** [FaridSafi/react-native-gifted-chat#974]
#### Issue Description

Dynamically hiding and showing keyboard causes white space sometimes (see screenshot). We hide the InputToolbar when we have suggested responses and do not hide it when we don't.

#### Steps to Reproduce / Code Snippets

It happens sometimes on iPhone X and iPhone 6. Its hard to reproduce.

Code:

```jsx
<GiftedChat
minInputToolbarHeight={this.getInputToolbarHeight()}
renderInputToolbar={this.renderInputToolbar}
...
/>
...
getInputToolbarHeight = () => (this.hideInputToolbar() ? 0 : 44);
...
  renderInputToolbar = props => (
    <InputToolbar
      {...props}
      navigation={this.props.navigation}
      hideInputToolbar={this.hideInputToolbar()}
    />
  );
...
hideInputToolbar = () => {
    const latestMessage = _.first(this.props.messages) || null;
    const hideInputToolbar =
      latestMessage === null ||
      ((latestMessage.suggestedActions &&
        latestMessage.suggestedActions.actions.length !== 0) ||
        latestMessage.user._id === this.props.user._id ||
        latestMessage.type === "typing");
    return hideInputToolbar;
  };
```

#### Expected Results

No white space.

#### Additional Information

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.1.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2
"react-native-gifted-chat":
      "https://github.com/watadarkstar/react-native-gifted-chat#fix/min-input-toolbar-height",

![screen shot 2018-09-19 at 9 16 05 am](https://user-images.githubusercontent.com/3059371/45755646-fe6c8180-bbec-11e8-9902-f01ac414072c.png)

**Comment by shaheem-khanzada** [comment]
same here
