### ISSUE TITLE
Scroll to bottom on send / Message 

### ISSUE THREAD

**Issue by saxs4x** [FaridSafi/react-native-gifted-chat#975]
#### Issue Description

Hi, i'm using inverted == false, and the chat doesn't scroll to bottom auto. The message it's displayed at the top.

#### Steps to Reproduce / Code Snippets

`
 onCreatePress(messages = []) {
        this.setState(previousState => ({
            messages: GiftedChat.append(previousState.messages, messages)
        }));
    }

<GiftedChat
                    listViewProps={{
                        refreshControl: <RefreshControl
                            refreshing={this.props.loading}
                            onRefresh={this.onEndReached}
                            enabled={true}/>
                    }}
                    style={{flex: 1}}
                    messages={this.state.messages}
                    text={this.props.hiMessage}
                    onInputTextChanged={text => this.onTextChange(text)}
                    onSend={messages => this.onCreatePress(messages)}
                    user={{
                        _id: this.props.user.id,
                    }}
                    inverted={false}
                    keyboardShouldPersistTaps={'never'}
                    isAnimated={true}
                    renderAvatar={null}
                    renderBubble={this.renderBubble}
                    renderMessageText={this.renderText}
                    renderMessageImage={this.renderImage}
                    renderTime={this.renderTime}
                    renderComposer={this.renderComposer.bind(this)}
                    renderInputToolbar={this.renderInput.bind(this)}
                    renderSend={this.renderSend.bind(this)}
                    renderSystemMessage={this.renderSystemMessage}
                />`

#### Expected Results

Sending the message the chat should scroll automatic at the bottom, and the message should go there to.

#### Additional Information

* Nodejs version: v9.7.1
* React version: 5.10.0
* React Native version: 0.56.0
* react-native-gifted-chat version: 5.10.0
* Platform(s) (iOS, Android, or both?): BOTH

**Comment by kanso-michael** [comment]
Think this is because of calling `scrollToOffset` on a `FlatList`
https://github.com/FaridSafi/react-native-gifted-chat/blob/052094d4dd1f2cd2726454605cf53ff115b5b9fa/src/MessageContainer.js#L82

It is passing through `y: 0` in the `options` object
https://github.com/FaridSafi/react-native-gifted-chat/blob/1fedba2203e29d35832e4939e1857f44ab398ab9/src/GiftedChat.js#L301

FlatList docs state:
https://facebook.github.io/react-native/docs/flatlist#scrolltooffset

```
Valid params keys are:

'offset' (number) - The offset to scroll to. In case of horizontal being true, the offset is the x-value, in any other case the offset is the y-value. Required.
'animated' (boolean) - Whether the list should do an animation while scrolling. Defaults to true.
```

I don't currently have time for a full fix right now, but my suggestion if you need this working asap and you are using `inverted=false`, is to swap `scrollToOffset` to `scrollToEnd`.

**Comment by Faolain** [comment]
@kanso-michael can you please submit a PR?

**Comment by dekameron22** [comment]
+1

**Comment by jonasfrid** [comment]
+1

**Comment by hubermat** [comment]
Same problem here. I have ```inverted=true``` (default), but on send it does not scroll to the bottom to show the new message.

In addition, if ```scrollToBottom=true```, the scrolltToButtom button is shown, but tapping on it has not effect!

It seems to me, that programmatical scrolling is not working at all.

Tested on iPhone X Simulator, iOS 12.2
GiftedChat: 0.9.0
react-native: 0.59.0
