### ISSUE TITLE
alwaysShowSend prop does not work 

### ISSUE THREAD

**Issue by harrydry2** [FaridSafi/react-native-gifted-chat#978]
alwaysShowSend prop does work. This issue has been documented several times. Has anyone worked out a fix for this? 

Great library btw :)

**Comment by xstable** [comment]
Here is how you can adjust sendbutton for your needs: https://github.com/FaridSafi/react-native-gifted-chat/pull/487

@FaridSafi BTW: `alwaysShowSend` are not yet implemented, so would be nice if you could implement it.

**Comment by helielson** [comment]
For some reason the `src/Send.js` file on `v0.4.3` is outdated.
Here the latest commit is from 2017: https://github.com/FaridSafi/react-native-gifted-chat/commits/v0.4.3/src/Send.js

But on the master it's from May 30: https://github.com/FaridSafi/react-native-gifted-chat/commits/master/src/Send.js

**Comment by helielson** [comment]
All 4.x versions have the same problem

**Comment by alfonsosn** [comment]
@helielson thanks for finding the solution to the problem! Seems like forking the library is probably the best thing to do for now.

**Comment by shubham1164** [comment]
That worked for me. Thanks

**Comment by xstable** [comment]
It's fixed in 0.7.2
