### ISSUE TITLE
renderTime color???

### ISSUE THREAD

**Issue by yuwenbai** [FaridSafi/react-native-gifted-chat#979]
I have seen the code about custom Time Text style  on the master but not branch not the version 0.4.3

**Comment by ravisublime** [comment]
Had the same issue.

**Comment by tapz** [comment]
Sadly, does not seem to exist in the npm version.

**Comment by Shrekie** [comment]
```
    renderTime(props) {
      return (
        <Time
          {...props}
          textStyle={{
            right: {
              color: "black"
            },
            left: {
              color: "white"
            }
          }}
        />
      );
    }
```

**Comment by shahzaibmuneeb** [comment]
> ```
>     renderTime(props) {
>       return (
>         <Time
>           {...props}
>           textStyle={{
>             right: {
>               color: "black"
>             },
>             left: {
>               color: "white"
>             }
>           }}
>         />
>       );
>     }
> ```

Just tried to use it and the prop seems to be 'timeTextStyle'

**Comment by DilnaMohandasNT** [comment]
timeTextStyle={{
          right: {
            color: 'black',
          },
          left: {
            color: 'white',
          },
        }}
