### ISSUE TITLE
First line is always hidden after line break on iOS

### ISSUE THREAD

**Issue by ziyafenn** [FaridSafi/react-native-gifted-chat#981]
#### Issue Description

After typing the first line of text and pressing enter to break the line, the first line is always hidden on top of the text field.
If i want to see it, i either have to delete any line break or scroll up the text field.

On Android there is no problem with that.

Any way to fix it?

I use non-modified components.

#### Additional Information

* React version:  16.3.1
* React Native version: 55.4
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by mcmar** [comment]
@ziyafenn Did you learn anything that you can share here? I see you closed this 9 day ago

**Comment by ziyafenn** [comment]
@ziyafenn i think it was some styling problem. Tbh don't remember what i changed but it works fine now.
