### ISSUE TITLE
Render action options in a custom modal.

### ISSUE THREAD

**Issue by rabindrachhachan** [FaridSafi/react-native-gifted-chat#983]
In the current version, action options are rendered in actionSheet. The actionSheet accept only string/Text elements as a parameter to render. How can I render my own custom modal.( Main action buttons, sub actions button with text ). I tried to open my custom modal on action icon pressed as in example app. But modal is not coming up.

#### Steps to Reproduce / Code Snippet
1. Render a customAction components.
2. In example app , onActionPressed will open a actionSheet with two options. I want to open a custom modal instead of actionSheet . My option styles is different from what actionSheet expect.

In customAction.js

onActionPressed = ()=>{
this.setState({showModal: !this.state.showModal})
}

render(){
            return(<View>
               {render action icon with onPress set to onActionPressed//TouchableOpacity}
                {showModal&&<Modal/> // modal }
                </View>  )
}
       

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: 8.*.*
* React version: 16.*.*
* React Native version: 0.51
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): Both

**Comment by Donhv** [comment]
any update for this?
