### ISSUE TITLE
components within MessageContainer can't be seen by Calabash

### ISSUE THREAD

**Issue by kaitlynbrown** [FaridSafi/react-native-gifted-chat#985]
#### Issue Description
When querying elements on the screen using the Calabash console, I don't seem to be able to see any components inside of the `MessageContainer`. I've tried adding `testID`s to individual `Message`s, as well as to the `ListView`. When I inspect the elements using React Native Debugger, the `testID`s show up, however when I use Calabash to query for these `testID`s, they do not show up. They also don't show up when I query based on the text contents of the messages.

I *can* use `testID` to locate the Text Input component. I can also locate the send button by querying by text (unfortunately there doesn't seem to be a way to attach a `testID` to the send button).

I also have no trouble querying components anywhere else in my app. I even tried setting up a `ListView` with elements in it on a different page and was able to query it and its contents just fine

#### Additional Information

* Nodejs version: 9.11.2
* React version: 16.3.1
* React Native version: 0.55.2
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): Android (haven't tested on iOS yet)

**Comment by Joshandrews43** [comment]
I am having the same issue with detox. Can find everything using detox except the actual chat bubbles themselves, even if I wrap them in a `View` and put the ID on that.
