### ISSUE TITLE
 User nickname does not show

### ISSUE THREAD

**Issue by SerekKiri** [FaridSafi/react-native-gifted-chat#986]
#### Issue Description

When i'm ussing

```javascript
user: { _id: el.author.id, name: el.author.username, avatar: el.author.avatarUrl }
```
I can see only avatar, username does not show

**Comment by rkzhap123** [comment]
That's not a bug,
I know that the "name" variable is for check the message send by me or other people.

You want to see the Nickname, you can see this page. 

https://github.com/FaridSafi/react-native-gifted-chat/tree/master/example-slack-message
