### ISSUE TITLE
InputToolbar 

### ISSUE THREAD

**Issue by MMelek00** [FaridSafi/react-native-gifted-chat#989]
#### Issue Description

InputToolbar stick to the buttom of the screen
and not avoiding the messages View
After Building Standalone App with expo
![43302767_541009006351525_4396121163164549120_n](https://user-images.githubusercontent.com/35879347/46575691-ed27c100-c9b1-11e8-82f2-a1d75ae0b885.jpg)

#### Steps to Reproduce / Code Snippets

renderInputToolbar(props) {
    return (
      <InputToolbar
        {...props}
        containerStyle={{ backgroundColor: colors.primary }}
      />
    );
  }
#### Expected Results

![43225098_108202970096378_2602058558497357824_n](https://user-images.githubusercontent.com/35879347/46575708-4f80c180-c9b2-11e8-9e01-8e4564e4b248.jpg)

#### Additional Information

* Nodejs version: v8.11.3
* React version: 16.3.1
* React Native version: 0.55.4
* react-native-gifted-chat version: ^0.4.3
* Platform(s) (iOS, Android, or both?): Android
*expo version:^30.0.0

**Comment by goodryanboy** [comment]
try to add this in your manifest in side the <activity android:windowSoftInputMode="adjustPan">

**Comment by scmyhexinhao** [comment]
They had solution to this issue on their home page already.Look below:
For Expo, there are almost 2 solutions to fix it:

adding KeyboardAvoidingView after GiftedChat
adding an opaque background status bar on app.json https://docs.expo.io/versions/latest/guides/configuration.html#androidstatusbar

**Comment by Thomazella** [comment]
if the main view changes height it'll trigger an `onLayout` handler in Gifted chat causing the input to reset to bottom, even if keyboard is open

**Comment by MMelek00** [comment]
thank you guys non of that worked but already solve it by adding "react-native-keyboard-spacer" to avoid view

**Comment by nandiniparimi1107** [comment]
What about the ejected apps? This solution only works for expo.

**Comment by xstable** [comment]
> They had solution to this issue on their home page already.Look below:
> For Expo, there are almost 2 solutions to fix it:
> 
> adding KeyboardAvoidingView after GiftedChat
> adding an opaque background status bar on app.json https://docs.expo.io/versions/latest/guides/configuration.html#androidstatusbar
> 
> I add following after GiftedChat then problem fixed.

@scmyhexinhao 
Link doesn't work anymore. So you added "what exactly".
Seems the thing you added is missing in your comment
