### ISSUE TITLE
[Bug] Component <Actions />, wrong ActionSheet options behavior

### ISSUE THREAD

**Issue by erbud** [FaridSafi/react-native-gifted-chat#991]
#### Issue Description

When an option is pressed on the ActionSheet of the <Actions /> component it's execute this option and all the next options of the ActionSheet defined in renderActions method.

#### Steps to Reproduce / Code Snippets

1. Add GiftedChat component overwriting renderActions method

```
render() {
  <GiftedChat
    …
    renderActions={(props) => this.renderActions(props)}
    …
  />
}
```

2. Overwrite renderActions method:

```
_renderActions(props) {
  const options = {
    'Image gallery': (props) => {
      console.log('pick image');
    },
    'Take a picture': (props) => {
      console.log('take picture');
    },
    'Cancel': () => {
      console.log('cancel');
    }
  };
  return (
    <Actions {...props} options={options} />
  );
};
```

3. When an option is pressed on the ActionSheet of the <Actions /> component it's execute this option and all the next options of the ActionSheet defined in renderActions method.

Examples:

_Output on press 'Image gallery' option:_
> pick image
> take picture
> cancel

_Output on press 'Take a picture' option:_
> take picture
> cancel

_Output on press 'Cancel' option:_
> cancel

#### Expected Results

That when an option is pressed on the ActionSheet of the <Actions /> component only execute the option selected.

#### Additional Information

* Nodejs version: 9.10.1
* React version: 16.3.1
* React Native version: 0.55.2
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): Android (on unproven iOS)

#### SOLUTION

In the onActionsPress method of /src/Actions.js remove the statement "return;" of the Object.keys() loop.

```
onActionsPress() {
  const options = Object.keys(this.props.options);
  const cancelButtonIndex = Object.keys(this.props.options).length - 1;
  this.context.actionSheet().showActionSheetWithOptions(
    {
      options,
      cancelButtonIndex,
      tintColor: this.props.optionTintColor,
    },
    (buttonIndex) => {
      let i = 0;
      Object.keys(this.props.options).forEach((key) => {
        if (this.props.options[key]) {
          if (buttonIndex === i) {
            this.props.options[key](this.props);
            // return;
          }
          i += 1;
        }
      });
    },
  );
}
```

**Comment by BatDroid** [comment]
i have this issue too
